// Algebra 2 Regents — August 2023 (Part I: Multiple Choice)
export default {
  id: 'a2-aug-2023',
  subject: 'algebra-2',
  year: 2023,
  session: 'August',
  totalMinutes: 180,
  questions: [
    { number: 1,  part: 'A', text: 'Using the Rational Root Theorem, which is a possible rational root of p(x) = 2x³ − 3x + 6?', choices: ['±3', '±4', '±5', '±7'], topic: 'Polynomial Functions', correct: 0 },
    { number: 2,  part: 'A', text: 'Which is equivalent to x^(−2/3)?', choices: ['1/∛(x²)', '∛(x²)', '−x^(2/3)', 'x^(2/3)'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 3,  part: 'A', text: 'Solve: log₁₀(x) = −2', choices: ['x = −20', 'x = 0.01', 'x = 100', 'x = −2'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 4,  part: 'A', text: 'The graph of y = sin(x) is shifted π/2 units to the right. Which equation represents this shift?', choices: ['y = sin(x − π/2)', 'y = sin(x + π/2)', 'y = sin(x) − π/2', 'y = sin(x) + π/2'], topic: 'Trigonometric Functions', correct: 0 },
    { number: 5,  part: 'A', text: 'Which value of r indicates the strongest linear correlation?', choices: ['r = 0.3', 'r = −0.9', 'r = 0.5', 'r = −0.4'], topic: 'Statistics & Probability', correct: 1 },
    { number: 6,  part: 'A', text: 'What is the result of dividing (6 + 3i) by 3?', choices: ['2 + i', '3 + i', '6 + i', '2 + 3i'], topic: 'Complex Numbers', correct: 0 },
    { number: 7,  part: 'A', text: 'Which polynomial has exactly three real zeros?', choices: ['x² + 1', 'x³ − x', 'x⁴ + 1', 'x² − 4'], topic: 'Polynomial Functions', correct: 1 },
    { number: 8,  part: 'A', text: 'Simplify: ∜(81x⁸)', choices: ['3x²', '9x⁴', '3x⁴', '9x²'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 9,  part: 'A', text: 'Which equation represents exponential growth?', choices: ['y = 5(0.8)^x', 'y = 5(1.3)^x', 'y = 5x²', 'y = −5(1.3)^x'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 10, part: 'A', text: 'What is cos(2π/3)?', choices: ['1/2', '−1/2', '√3/2', '−√3/2'], topic: 'Trigonometric Functions', correct: 1 },
    { number: 11, part: 'A', text: 'The heights of students are normally distributed with mean 65 inches and standard deviation 3 inches. What percent of students are taller than 68 inches?', choices: ['16%', '32%', '84%', '68%'], topic: 'Statistics & Probability', correct: 0 },
    { number: 12, part: 'A', text: 'What is the complex conjugate of −2 + 5i?', choices: ['2 − 5i', '−2 − 5i', '2 + 5i', '5 − 2i'], topic: 'Complex Numbers', correct: 1 },
    { number: 13, part: 'A', text: 'If f(x) = x⁴ − 5x² + 4, which values are roots of f?', choices: ['x = ±1, ±2', 'x = ±1, ±4', 'x = ±2, ±4', 'x = ±4'], topic: 'Polynomial Functions', correct: 0 },
    { number: 14, part: 'A', text: 'Simplify: (3/x) + (2/x²)', choices: ['(3x + 2)/x²', '5/x³', '(3 + 2x)/x²', '5/x²'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 15, part: 'A', text: 'What is ln(e³)?', choices: ['e³', '3', '3e', '1/3'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 16, part: 'A', text: 'What is the value of sec(60°)?', choices: ['2', '1/2', '√3', '2√3/3'], topic: 'Trigonometric Functions', correct: 0 },
    { number: 17, part: 'A', text: 'A sample has mean 80 and standard deviation 10. Which interval captures approximately 95% of the data assuming normal distribution?', choices: ['[70, 90]', '[60, 100]', '[50, 110]', '[75, 85]'], topic: 'Statistics & Probability', correct: 1 },
    { number: 18, part: 'A', text: 'What is i^(23)?', choices: ['1', 'i', '−1', '−i'], topic: 'Complex Numbers', correct: 3 },
    { number: 19, part: 'A', text: 'Which expression represents the quotient when x³ + 8 is divided by (x + 2)?', choices: ['x² − 2x + 4', 'x² + 2x − 4', 'x² + 2x + 4', 'x² − 2x − 4'], topic: 'Polynomial Functions', correct: 0 },
    { number: 20, part: 'A', text: 'Solve: ∛(2x − 1) = 3', choices: ['x = 14', 'x = 13', 'x = 7', 'x = 4'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 21, part: 'A', text: 'A population of bacteria doubles every 3 hours. If the initial population is 500, which expression gives the population after t hours?', choices: ['500 · 2^(t/3)', '500 · 3^(t/2)', '500 + 2t', '500e^(3t)'], topic: 'Exponential & Logarithmic Functions', correct: 0 },
    { number: 22, part: 'A', text: 'Which is equivalent to tan(θ) in terms of sin and cos?', choices: ['sin(θ)/cos(θ)', 'cos(θ)/sin(θ)', 'sin(θ) · cos(θ)', '1/sin(θ)'], topic: 'Trigonometric Functions', correct: 0 },
    { number: 23, part: 'A', text: 'Which of the following is a real number?', choices: ['√(−9)', '√(−16)', '(2 + i)(2 − i)', '3i + 4i'], topic: 'Complex Numbers', correct: 2 },
    { number: 24, part: 'A', text: 'In how many ways can 5 books be arranged on a shelf?', choices: ['25', '120', '60', '20'], topic: 'Statistics & Probability', correct: 1 },
  ]
}
