// Algebra 2 Regents — June 2019 (Part I: Multiple Choice)
export default {
  id: 'a2-jun-2019',
  subject: 'algebra-2',
  year: 2019,
  session: 'June',
  totalMinutes: 180,
  questions: [
    { number: 1,  part: 'A', text: 'Which is the correct factored form of 8x³ − 27?', choices: ['(2x − 3)(4x² + 6x + 9)', '(2x + 3)(4x² − 6x + 9)', '(2x − 3)³', '(2x − 3)(4x² − 6x + 9)'], topic: 'Polynomial Functions', correct: 0 },
    { number: 2,  part: 'A', text: 'Simplify: (√5 + √2)(√5 − √2)', choices: ['3', '7', '√3', '√10'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 3,  part: 'A', text: 'Solve: log₂(x − 1) = 3', choices: ['x = 9', 'x = 7', 'x = 5', 'x = 4'], topic: 'Exponential & Logarithmic Functions', correct: 0 },
    { number: 4,  part: 'A', text: 'What is the exact value of sin(π/3)?', choices: ['1/2', '√3/2', '√2/2', '√3'], topic: 'Trigonometric Functions', correct: 1 },
    { number: 5,  part: 'A', text: 'Which term describes a distribution that is skewed to the right?', choices: ['The mean is greater than the median', 'The mean is less than the median', 'The mean equals the median', 'The distribution is symmetric'], topic: 'Statistics & Probability', correct: 0 },
    { number: 6,  part: 'A', text: 'What is i^(75)?', choices: ['1', 'i', '−1', '−i'], topic: 'Complex Numbers', correct: 3 },
    { number: 7,  part: 'A', text: 'Which polynomial function could have the graph that crosses the x-axis at x = −2 and touches but does not cross at x = 1?', choices: ['f(x) = (x + 2)(x − 1)²', 'f(x) = (x − 2)(x + 1)²', 'f(x) = (x + 2)²(x − 1)', 'f(x) = (x − 2)²(x + 1)'], topic: 'Polynomial Functions', correct: 0 },
    { number: 8,  part: 'A', text: 'Simplify: (x²y⁻¹)/(x⁻¹y²)', choices: ['x³/y³', 'x³y³', 'x/y', 'y³/x³'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 9,  part: 'A', text: 'What is the solution to e^x = 15?', choices: ['x = log(15)', 'x = ln(15)', 'x = 15e', 'x = log₁₅(e)'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 10, part: 'A', text: 'What is the value of tan(π/4)?', choices: ['√2/2', '√3', '1', '√3/3'], topic: 'Trigonometric Functions', correct: 2 },
    { number: 11, part: 'A', text: 'A box-and-whisker plot has Q1 = 20 and Q3 = 50. What is the interquartile range?', choices: ['70', '30', '25', '35'], topic: 'Statistics & Probability', correct: 1 },
    { number: 12, part: 'A', text: 'What is the result of multiplying (3 − 2i) by its complex conjugate?', choices: ['13', '5', '9 + 4i', '6'], topic: 'Complex Numbers', correct: 0 },
    { number: 13, part: 'A', text: 'How many turning points can a polynomial of degree 5 have at most?', choices: ['5', '4', '3', '6'], topic: 'Polynomial Functions', correct: 1 },
    { number: 14, part: 'A', text: 'What is the simplified form of (2/x) · (x/(x+1))?', choices: ['2/(x+1)', '2x/(x+1)', '2x', '2'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 15, part: 'A', text: 'Solve: 2^(2x) − 5 · 2^x + 4 = 0', choices: ['x = 0 and x = 2', 'x = 0 and x = 1', 'x = 1 and x = 2', 'x = −1 and x = 2'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 16, part: 'A', text: 'Which identity is equivalent to cos(2θ)?', choices: ['2sin(θ)cos(θ)', 'cos²(θ) − sin²(θ)', 'sin²(θ) + cos²(θ)', '2cos²(θ) + 1'], topic: 'Trigonometric Functions', correct: 1 },
    { number: 17, part: 'A', text: 'A data set is normally distributed with mean 100 and standard deviation 15. What percent of data falls between 85 and 115?', choices: ['34%', '50%', '68%', '95%'], topic: 'Statistics & Probability', correct: 2 },
    { number: 18, part: 'A', text: 'Which of the following represents a complex number in polar-like standard form?', choices: ['3 + 4i', '√(−5)', '4i²', '3i³'], topic: 'Complex Numbers', correct: 0 },
    { number: 19, part: 'A', text: 'The polynomial p(x) = x⁴ − 1 factors completely as', choices: ['(x² + 1)(x + 1)(x − 1)', '(x² − 1)²', '(x + 1)²(x − 1)²', '(x² + 1)²'], topic: 'Polynomial Functions', correct: 0 },
    { number: 20, part: 'A', text: 'Solve: (x + 3)/(x − 1) = 2', choices: ['x = 5', 'x = 4', 'x = −5', 'x = 3'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 21, part: 'A', text: 'Which represents the graph of f(x) = 2^(−x)?', choices: ['Decreasing exponential curve', 'Increasing exponential curve', 'A line with negative slope', 'A parabola opening downward'], topic: 'Exponential & Logarithmic Functions', correct: 0 },
    { number: 22, part: 'A', text: 'The function f(x) = sin(x) is transformed to g(x) = sin(2x + π). What is the phase shift?', choices: ['π/2 to the left', 'π to the left', 'π/2 to the right', 'π to the right'], topic: 'Trigonometric Functions', correct: 0 },
    { number: 23, part: 'A', text: 'Which equation has 3i as a solution?', choices: ['x² + 9 = 0', 'x² − 9 = 0', 'x² + 3 = 0', 'x + 3i = 0'], topic: 'Complex Numbers', correct: 0 },
    { number: 24, part: 'A', text: 'A student randomly guesses on a 5-question true/false quiz. What is the probability of getting all 5 correct?', choices: ['1/32', '1/16', '1/25', '1/10'], topic: 'Statistics & Probability', correct: 0 },
  ]
}
