// Earth Science Regents — August 2019
// Source: esci82019-examw.pdf, esci82019-sk.pdf
export default {
  id: 'es-august-2019',
  subject: 'earth-science',
  year: 2019,
  session: 'August',
  totalMinutes: 180,
  questions: [
    {
      number: 1,
      part: 'A',
      text: 'Most asteroids in our solar system are located in the asteroid belt between the orbits of Mars and Jupiter. What is the approximate distance from the Sun to the asteroid belt?',
      choices: [
        '129 million km',
        '210 million km',
        '403 million km',
        '1103 million km',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'Mars orbits at about 228 million km and Jupiter at about 778 million km; the asteroid belt lies between them, so 403 million km is the only value that falls in that range.',
      diveDeep: 'Use the Solar System Data table in the Earth Science Reference Tables to look up mean distances from the Sun. A common trap is picking 210 million km, which is just inside Mars’s orbit, or 1103 million km, which is beyond Jupiter. On the exam, eliminate any answer smaller than Mars’s distance or larger than Jupiter’s distance first. Remembering the ordering of planetary distances quickly narrows multiple-choice astronomy questions.',
    },
    {
      number: 2,
      part: 'A',
      text: 'A table shows tide data for a location on the north shore of Long Island, New York. On Tuesday, high tides occur at 12:11 a.m. and 12:36 p.m., and low tides at 6:23 a.m. and 6:49 p.m. On Wednesday, high tides occur at 1:02 a.m. and 1:27 p.m., and a low tide at 7:15 a.m. Based on these data, what is the most likely time of the next high tide?',
      choices: [
        '1:53 p.m.',
        '7:40 a.m.',
        '7:40 p.m.',
        '1:53 a.m.',
      ],
      topic: 'General',
      correct: 0,
      image: '/images/exams/es-august-2019/q2.png',
      explanation: 'Each successive high tide arrives about 25–26 minutes later than the previous day; adding ~26 minutes to the 1:27 p.m. high tide gives the next high tide at about 1:53 p.m.',
      diveDeep: 'Tides cycle roughly every 12 hours 25 minutes because the Moon takes about 24 hours 50 minutes to return to the same position overhead. To solve, find the pattern in the data rather than guessing: the daily delay here is consistent at about 25 minutes. A common trap is choosing a low-tide time (7:40 a.m./p.m.) when the question asks for the next high tide. Always confirm whether you need the next high or low event before answering.',
    },
    {
      number: 3,
      part: 'A',
      text: 'Which planet takes longer to complete one rotation on its axis than it does to complete one orbit of the Sun?',
      choices: [
        'Mercury',
        'Venus',
        'Earth',
        'Mars',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'Venus has a rotation period (about 243 Earth days) that is longer than its period of revolution around the Sun (about 225 Earth days), so its day is longer than its year.',
      diveDeep: 'Rotation is spinning on an axis (one day); revolution is orbiting the Sun (one year). Venus is unusual not only for its very slow rotation but also for spinning in the opposite (retrograde) direction. The Solar System Data table in the Reference Tables lists both period of rotation and period of revolution, so this can be answered by direct comparison. A typical mistake is confusing the two periods, so label each column carefully before comparing.',
    },
    {
      number: 4,
      part: 'A',
      text: 'Jupiter is a Jovian planet. Compared to the terrestrial planets, Jupiter has a',
      choices: [
        'shorter period of revolution',
        'shorter distance to the Sun',
        'greater density',
        'greater mass',
      ],
      topic: 'Astronomy',
      correct: 3,
      explanation: 'Jovian (gas giant) planets like Jupiter are far more massive than the small, rocky terrestrial planets, so Jupiter has a much greater mass.',
      diveDeep: 'Terrestrial planets (Mercury, Venus, Earth, Mars) are small, dense, and rocky, while Jovian planets (Jupiter, Saturn, Uranus, Neptune) are large but low in density because they are gaseous. The trap answer is greater density: Jupiter is huge but its density (about 1.3 g/cm³) is actually lower than rocky Earth (5.5 g/cm³). Jovian planets also lie farther from the Sun and have longer periods of revolution, eliminating the first two choices. Use the Reference Tables data columns to verify mass and density quickly.',
    },
    {
      number: 5,
      part: 'A',
      text: 'The entire constellation of Orion is visible in the night sky in January to an observer in New York State. Which statement explains why this constellation is not visible in the night sky to this observer in June?',
      choices: [
        'Earth rotates on its axis.',
        'Earth revolves around the Sun.',
        'The constellation Orion orbits the Sun.',
        'The tilt of Earth’s axis changes throughout the year.',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'As Earth revolves around the Sun, the night side faces different regions of space at different times of year, so constellations visible in winter are behind the Sun (daytime sky) in summer.',
      diveDeep: 'Different constellations are seen in different seasons because of Earth’s revolution, while the daily rising and setting of stars is due to rotation. The trap answer "tilt changes" is false: Earth’s axis stays tilted 23.5° and points toward the same spot (Polaris) all year. Constellations do not orbit the Sun. To distinguish rotation from revolution effects, remember that rotation causes daily (hourly) changes and revolution causes yearly (seasonal) changes.',
    },
    {
      number: 6,
      part: 'A',
      text: 'The approximate age of the universe is estimated to be',
      choices: [
        '4.6 million years',
        '4.6 billion years',
        '13.8 million years',
        '13.8 billion years',
      ],
      topic: 'Astronomy',
      correct: 3,
      explanation: 'The universe is estimated to be about 13.8 billion years old based on the Big Bang theory and observations of cosmic expansion.',
      diveDeep: 'Do not confuse the age of the universe (13.8 billion years) with the age of Earth and the solar system (4.6 billion years). The trap answers swap these two numbers and also test billion vs. million. Evidence for the universe’s age comes from the redshift of galaxies and the cosmic microwave background radiation. Memorizing the pair 13.8 billion (universe) and 4.6 billion (Earth) prevents the most common mistake on this question.',
    },
    {
      number: 7,
      part: 'A',
      text: 'A photograph shows the apparent path of the Sun photographed at 20-minute intervals and combined into one photograph. Which motion is responsible for the apparent path of the Sun shown in the photograph?',
      choices: [
        'Earth’s rotation',
        'Earth’s revolution',
        'Sun’s rotation',
        'Sun’s revolution',
      ],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-august-2019/q7.png',
      explanation: 'The Sun appears to move across the sky during a single day because Earth rotates on its axis once every 24 hours.',
      diveDeep: 'The apparent daily motion of the Sun, Moon, and stars across the sky (about 15° per hour) is caused by Earth’s rotation, not by the objects actually moving around us. Revolution causes seasonal changes in the Sun’s path over a year, not the day-long arc shown here. The key clue is the short 20-minute interval, indicating a daily (rotational) effect. The Sun appears to move 15° every hour, so 20 minutes corresponds to about 5° of apparent motion.',
    },
    {
      number: 8,
      part: 'A',
      text: 'The mass extinction of the dinosaurs, approximately 65.5 million years ago, is inferred by most scientists to have been caused by',
      choices: [
        'a large energy surge from the surface of the Sun',
        'the occurrence of a major ice age',
        'an impact event occurring on Earth’s surface',
        'earthquakes occurring along crustal plate boundaries',
      ],
      topic: 'General',
      correct: 2,
      explanation: 'Most scientists infer that a large asteroid or comet impact about 65.5 million years ago caused the mass extinction at the end of the Cretaceous, including the dinosaurs.',
      diveDeep: 'The Geologic History of New York State table in the Reference Tables marks this extinction at the end of the Mesozoic Era (Cretaceous Period) and notes the inferred meteor impact. Evidence includes a worldwide layer of iridium-rich clay and the Chicxulub crater. The impact threw dust into the atmosphere, blocking sunlight and disrupting food chains. Ice ages and earthquakes are real geologic events but are not the cause linked to this particular extinction.',
    },
    {
      number: 9,
      part: 'A',
      text: 'A diagram represents Earth as viewed from space. Letter A represents the angle of tilt of Earth’s rotational axis. Line XY is perpendicular to the plane of Earth’s orbit. What is the value of the angle represented by letter A?',
      choices: [
        '15.0°',
        '23.5°',
        '66.5°',
        '90.0°',
      ],
      topic: 'Astronomy',
      correct: 1,
      image: '/images/exams/es-august-2019/q9.png',
      explanation: 'Earth’s rotational axis is tilted 23.5° from the line perpendicular to the plane of its orbit, and that perpendicular is exactly what line XY represents.',
      diveDeep: 'Earth’s axis is tilted 23.5° from the vertical (perpendicular to orbit) or, equivalently, 66.5° from the orbital plane itself. The trap answer 66.5° is the angle measured from the plane rather than from the perpendicular, so read carefully which reference line the angle is measured against. This 23.5° tilt is what produces the seasons. Identify the perpendicular line first, then the angle to the axis is always 23.5°.',
    },
    {
      number: 10,
      part: 'A',
      text: 'In the spring, when snow cover on the land melts, the water will most likely infiltrate Earth’s surface where that land surface is',
      choices: [
        'still frozen with a steep slope',
        'still frozen with a gentle slope',
        'no longer frozen with a steep slope',
        'no longer frozen with a gentle slope',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'Infiltration is greatest where the ground is unfrozen (so pore spaces are open) and the slope is gentle (so water stays in place long enough to soak in).',
      diveDeep: 'Frozen ground acts like an impermeable layer, forcing meltwater to run off instead of soaking in, and steep slopes speed runoff. The factors favoring infiltration are: permeable (unfrozen) ground, gentle slope, and unsaturated soil. The opposite conditions (frozen ground or steep slope) increase surface runoff and the risk of flooding. Picture water needing time and open pore spaces to seep downward when answering infiltration questions.',
    },
    {
      number: 11,
      part: 'A',
      text: 'Water is returned from Earth’s surface to the atmosphere by',
      choices: [
        'condensation and transpiration',
        'condensation and precipitation',
        'evaporation and transpiration',
        'evaporation and precipitation',
      ],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'Evaporation (from water and soil surfaces) and transpiration (release of water vapor by plants) both move water from the surface up into the atmosphere as water vapor.',
      diveDeep: 'In the water cycle, evaporation and transpiration add water vapor to the air, while condensation and precipitation return water to the surface. The combined term for surface-to-air water transfer is "evapotranspiration." The trap choices pair an upward process with a downward one (condensation or precipitation). Sort each process by its direction of water movement, then pick the option where both go upward.',
    },
    {
      number: 12,
      part: 'A',
      text: 'Which type of sediment sample normally has the greatest permeability rate?',
      choices: [
        'unsorted pebbles',
        'unsorted sand',
        'sorted pebbles',
        'sorted sand',
      ],
      topic: 'Water Cycle',
      correct: 2,
      explanation: 'Permeability increases with larger, well-sorted particles; sorted pebbles have large, uniform pore spaces that allow water to pass through fastest.',
      diveDeep: 'Permeability depends on particle size and sorting: larger particles and good sorting mean bigger, connected pore spaces. Unsorted sediment has small particles filling the gaps between large ones, which reduces permeability. Between sorted pebbles and sorted sand, the larger pebbles win because bigger pores allow faster flow. Remember the rule: large, rounded, well-sorted particles equal high permeability.',
    },
    {
      number: 13,
      part: 'A',
      text: 'The presence of which atmospheric condition will most likely result in clear skies in Binghamton, New York?',
      choices: [
        'high humidity',
        'high-pressure center',
        'increasing wind speed',
        'dewpoint equal to air temperature',
      ],
      topic: 'General',
      correct: 1,
      explanation: 'In a high-pressure center, air sinks and warms, which prevents cloud formation and produces clear, fair weather.',
      diveDeep: 'High pressure means descending, diverging air that inhibits condensation, giving clear skies; low pressure means rising air, cloud formation, and storms. When the dewpoint equals the air temperature, relative humidity is 100% and clouds or fog are likely — the opposite of clear. The trap answers (high humidity, dewpoint = temperature) all describe conditions favorable for clouds. Associate "high pressure" with sunny weather and "low pressure" with stormy weather.',
    },
    {
      number: 14,
      part: 'A',
      text: 'Which changes in air temperature and atmospheric pressure will normally be recorded by a weather balloon when it is released at Earth’s surface and rises through the troposphere?',
      choices: [
        'a decrease in both air temperature and atmospheric pressure',
        'a decrease in air temperature and an increase in atmospheric pressure',
        'an increase in both air temperature and atmospheric pressure',
        'an increase in air temperature and a decrease in atmospheric pressure',
      ],
      topic: 'Meteorology',
      correct: 0,
      explanation: 'Within the troposphere, both air temperature and atmospheric pressure decrease as altitude increases.',
      diveDeep: 'The Selected Properties of Earth’s Atmosphere table shows temperature falling throughout the troposphere and pressure dropping continuously with height. Pressure always decreases with altitude because there is less air above pushing down. Temperature behavior is layer-dependent (it rises again in the stratosphere), but the question specifies the troposphere, where it falls. Use the atmosphere chart to confirm both trends rather than relying on memory alone.',
    },
    {
      number: 15,
      part: 'A',
      text: 'Which gas is most effective in absorbing incoming harmful ultraviolet radiation in Earth’s stratosphere before that radiation reaches Earth’s surface?',
      choices: [
        'nitrogen',
        'hydrogen',
        'oxygen',
        'ozone',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'Ozone (O₃) in the stratosphere absorbs most of the Sun’s harmful ultraviolet radiation, shielding Earth’s surface.',
      diveDeep: 'The ozone layer sits in the stratosphere and is essential for protecting life from UV radiation. Although ordinary oxygen (O₂) plays a role in forming ozone, it is ozone (O₃) specifically that does the bulk of UV absorption. Nitrogen, the most abundant atmospheric gas, does not significantly absorb UV. Distinguish O₂ (oxygen) from O₃ (ozone) when reading the choices — that subscript is the key.',
    },
    {
      number: 16,
      part: 'A',
      text: 'The major cause of monsoon rains in India and southeast Asia is seasonal',
      choices: [
        'shifts in the prevailing wind belts',
        'shifts in ocean currents',
        'changes in the energy radiated from the Sun',
        'changes in worldwide atmospheric temperatures',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'Monsoons are caused by seasonal shifts in prevailing winds, which reverse direction and bring moist ocean air onshore in summer.',
      diveDeep: 'Monsoons result from differential heating of land and ocean: in summer, land heats faster, creating low pressure that draws moist sea air inland, shifting the prevailing winds and bringing heavy rain. In winter the pattern reverses, producing dry conditions. The Sun’s radiated energy output is essentially constant, so that choice is wrong. Tie monsoons to seasonal wind reversal driven by land-vs-sea heating contrasts.',
    },
    {
      number: 17,
      part: 'A',
      text: 'A cross section represents the windward and leeward sides of a mountain, with arrows showing the direction of air movement over the mountain. Points X and Y represent locations on Earth’s surface, with X on the windward side and Y on the leeward side. Compared to the temperature and water vapor content of the air at location X, the temperature and water vapor content at location Y are most likely',
      choices: [
        'warmer and wetter',
        'warmer and drier',
        'cooler and wetter',
        'cooler and drier',
      ],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-august-2019/q17.png',
      explanation: 'Air rising on the windward side cools and loses moisture as precipitation; descending on the leeward side it warms and is drier, so location Y is warmer and drier than X.',
      diveDeep: 'This describes the rain-shadow effect: windward slopes are cool and wet (rising, cooling, condensing air), while leeward slopes are warm and dry (sinking, warming air that has already lost its moisture). The trap is to assume both sides behave the same. Always track the air’s path: up the windward side it cools and rains out, down the leeward side it warms and dries. Leeward deserts (like the Great Basin) form this way.',
    },
    {
      number: 18,
      part: 'A',
      text: 'Which surface ocean current transports cool water to lower latitudes?',
      choices: [
        'Gulf Stream',
        'Peru Current',
        'West Greenland Current',
        'East Australia Current',
      ],
      topic: 'Climate',
      correct: 1,
      explanation: 'The Peru Current flows from higher (cooler) latitudes toward the equator along South America’s west coast, carrying cool water to lower latitudes.',
      diveDeep: 'Use the Surface Ocean Currents map in the Reference Tables, where cold currents are shown as dashed arrows and warm currents as solid arrows. Cold currents generally flow toward the equator (lower latitudes) on the eastern sides of oceans, while warm currents like the Gulf Stream and East Australia Current carry warm water poleward. The trick is matching both the temperature (cool) and direction (toward lower latitudes). The Peru Current is a classic cold, equatorward current.',
    },
    {
      number: 19,
      part: 'A',
      text: 'Which land surface characteristics produce the greatest amount of absorption of insolation at Earth’s surface?',
      choices: [
        'dark color and rough texture',
        'dark color and smooth texture',
        'light color and rough texture',
        'light color and smooth texture',
      ],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'Dark, rough surfaces absorb the most insolation because dark colors absorb (rather than reflect) light and rough textures trap incoming radiation.',
      diveDeep: 'Absorption is greatest for dark-colored, rough surfaces; reflection is greatest for light-colored, smooth surfaces. Light, smooth surfaces (like snow or ice) have a high albedo and reflect most insolation back to space. The trap is mixing one good factor with one poor factor; the best absorber needs both dark color and rough texture. This is why a dark asphalt road gets much hotter than a light sandy beach in the same sunlight.',
    },
    {
      number: 20,
      part: 'A',
      text: 'The planetary surface winds and air currents near Earth’s equator are usually',
      choices: [
        'converging and sinking',
        'diverging and sinking',
        'converging and rising',
        'diverging and rising',
      ],
      topic: 'General',
      correct: 2,
      explanation: 'Near the equator, intense solar heating causes air to rise, and surface winds from both hemispheres converge there, producing a low-pressure belt with abundant rainfall.',
      diveDeep: 'The Planetary Wind and Moisture Belts diagram shows air rising at the equator (0°) and at 60° (zones of low pressure, cloudy and wet) and sinking at 30° and the poles (high pressure, dry). At the equator, the trade winds converge and warm air rises, creating the rainy tropics. The trap answers reverse either the convergence or the vertical motion. Memorize: equator = converging and rising = low pressure and wet.',
    },
    {
      number: 21,
      part: 'A',
      text: 'Oxygen in Earth’s early atmosphere was first produced during the Precambrian from',
      choices: [
        'cyanobacteria in Earth’s oceans',
        'volcanic activity along plate boundaries',
        'the absorption of sunlight by plants',
        'evaporation of ocean water',
      ],
      topic: 'Meteorology',
      correct: 0,
      explanation: 'Photosynthetic cyanobacteria in the early oceans were the first organisms to release free oxygen into Earth’s atmosphere during the Precambrian.',
      diveDeep: 'The Geologic History table notes that the earliest evidence of oxygen-producing cyanobacteria appears in the Precambrian, long before land plants existed. These microbes carried out photosynthesis in the oceans, gradually building up atmospheric oxygen in what is called the Great Oxygenation Event. The trap "absorption of sunlight by plants" is wrong because complex plants evolved much later, in the Paleozoic. Link early atmospheric oxygen specifically to ocean cyanobacteria.',
    },
    {
      number: 22,
      part: 'A',
      text: 'Which life-form existed on Earth for the shortest period of time?',
      choices: [
        'dinosaurs',
        'trilobites',
        'ammonoids',
        'placoderm fish',
      ],
      topic: 'Geologic Time',
      correct: 3,
      explanation: 'On the Geologic History of New York State chart, the bar (time range) for placoderm fish is the shortest of the four organisms listed.',
      diveDeep: 'This question is answered directly from the Geologic History of New York State table by comparing the lengths of the existence bars for each index fossil. Placoderm fish appeared and went extinct within the Paleozoic over a relatively brief span, while trilobites, ammonoids, and dinosaurs each persisted longer. The trap is guessing from memory; instead measure each bar’s span against the time scale. Always read these ranges directly from the chart for accuracy.',
    },
    {
      number: 23,
      part: 'A',
      text: 'During the late Silurian epoch, very salty seas extended from New York State to Michigan. These environmental conditions resulted in the formation of halite layers. At the same time, Eurypterus remipes lived in nearby environments. Both the halite layers and Eurypterus remipes fossils can now be used to identify a specific geologic time interval because both formed over a',
      choices: [
        'large geographic area and in a short geologic time',
        'large geographic area and in a long geologic time',
        'small geographic area and in a short geologic time',
        'small geographic area and in a long geologic time',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'A good time marker (index fossil or correlatable rock layer) must form over a wide geographic area but during a short interval of geologic time.',
      diveDeep: 'Index fossils, like Eurypterus remipes (New York’s state fossil), are useful precisely because the organism was widespread but existed only briefly, pinning down a narrow time interval. The same logic applies to the widespread, quickly deposited halite layers. The traps reverse one of these conditions; a fossil found only in a small area or over a very long time would be a poor time indicator. Remember: good index = widespread + short-lived.',
    },
    {
      number: 24,
      part: 'A',
      text: 'If it takes a P-wave five minutes to travel from the epicenter of an earthquake to a seismic station, approximately how long will it take an S-wave to travel that same distance?',
      choices: [
        '15 minutes',
        '12 minutes',
        '9 minutes',
        '4 minutes',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'Using the Earthquake P-wave and S-wave Travel Time graph, a P-wave travel time of 5 minutes corresponds to a distance where the S-wave takes about 9 minutes.',
      diveDeep: 'Use the P-wave/S-wave travel-time graph in the Reference Tables: find where the P-wave curve reads 5 minutes (about 3,400 km), then read the S-wave curve at that same distance, which gives roughly 9 minutes. S-waves always travel slower than P-waves, so the answer must be greater than 5 minutes, eliminating choice D. The gap between the two arrival times grows with distance, which is how seismologists locate epicenters.',
    },
    {
      number: 25,
      part: 'A',
      text: 'Earthquake S-waves do not pass through which two interior Earth layers?',
      choices: [
        'rigid mantle and asthenosphere',
        'asthenosphere and stiffer mantle',
        'stiffer mantle and outer core',
        'outer core and inner core',
      ],
      topic: 'Geology',
      correct: 3,
      explanation: 'S-waves cannot travel through liquids, and the outer core is liquid; because S-waves are blocked there, they never reach the inner core either.',
      diveDeep: 'The Inferred Properties of Earth’s Interior diagram shows the outer core as the only liquid layer, which creates the S-wave shadow zone. Since S-waves are stopped at the liquid outer core, they cannot pass through it or the inner core beyond it. This behavior is the key evidence that the outer core is liquid. P-waves, by contrast, pass through all layers but bend (refract). Remember: S-waves = solids only; liquid outer core blocks them.',
    },
    {
      number: 26,
      part: 'A',
      text: 'A cross section represents the bedrock structure of a section of Earth’s crust. Letters A through H represent rock units. Line XY represents a fault. The rock layers have not been overturned. Rock unit A is an igneous intrusion with contact metamorphism zones. When did faulting along line XY occur?',
      choices: [
        'after the intrusion of rock unit A',
        'after the deposition of rock units B, C, and D',
        'after the formation of rock units E and F',
        'before the formation of rock units G and H',
      ],
      topic: 'Geology',
      correct: 2,
      image: '/images/exams/es-august-2019/q26.png',
      explanation: 'A fault must be younger than every rock unit it cuts through; since the fault displaces units E and F, it formed after those units existed.',
      diveDeep: 'This uses the principle of cross-cutting relationships: any fault or intrusion is younger than the rocks it cuts. Trace which units the fault line offsets and which it does not. The fault here cuts E and F (so it is younger than them) but is itself cut by or unrelated to younger features, fixing its relative age. A common error is ignoring "not overturned," which guarantees the original order from oldest (bottom) to youngest (top) by superposition.',
    },
    {
      number: 27,
      part: 'A',
      text: 'A cross section represents rock units within Earth’s crust, showing granite bedrock, sandstone above it, and granite inclusions within the sandstone. The age of the granite that makes up the inclusions is most likely',
      choices: [
        'older than the sandstone, but the same age as the granite bedrock',
        'older than the sandstone and the granite bedrock',
        'younger than the sandstone, but the same age as the granite bedrock',
        'younger than the sandstone and the granite bedrock',
      ],
      topic: 'Geology',
      correct: 0,
      image: '/images/exams/es-august-2019/q27.png',
      explanation: 'By the principle of inclusions, fragments contained within a rock are older than the rock that holds them, so the granite inclusions are older than the sandstone but came from the same-age granite bedrock.',
      diveDeep: 'The principle of inclusions states that pieces embedded in another rock must have existed first, making them older than their host. Here the granite inclusions weathered out of the granite bedrock and were then deposited within the forming sandstone, so they share the bedrock’s age and predate the sandstone. The trap is assuming inclusions are younger because they sit inside a younger layer. Always ask: which formed first, the fragment or the rock surrounding it?',
    },
    {
      number: 28,
      part: 'A',
      text: 'A portion of the Generalized Landscape Regions of New York State map shows the location of the Catskill Aqueduct that flows into the Kensico Reservoir, which supplies the residents of New York City with drinkable water. Which sequence shows the order of landscape regions that are crossed as water flows through the Catskill Aqueduct?',
      choices: [
        'Allegheny Plateau, Hudson-Mohawk Lowlands, Taconic Mountains, Newark Lowlands',
        'Allegheny Plateau, Hudson-Mohawk Lowlands, Hudson Highlands, Manhattan Prong',
        'Atlantic Coastal Plain, Newark Lowlands, Hudson Highlands, Hudson-Mohawk Lowlands',
        'Atlantic Coastal Plain, Manhattan Prong, Hudson Highlands, Allegheny Plateau',
      ],
      topic: 'General',
      correct: 1,
      image: '/images/exams/es-august-2019/q28.png',
      explanation: 'Tracing the aqueduct route southward on the Generalized Landscape Regions map crosses the Allegheny Plateau, Hudson-Mohawk Lowlands, Hudson Highlands, and Manhattan Prong in that order.',
      diveDeep: 'Use the Generalized Landscape Regions of New York State map in the Reference Tables and follow the aqueduct’s path from the Catskill source region toward New York City. Read the labeled regions in sequence rather than guessing. The trap answers include regions that lie far from the route, such as the Atlantic Coastal Plain or Taconic Mountains. Carefully match each region the line passes through, in order, to eliminate impossible sequences.',
    },
    {
      number: 29,
      part: 'A',
      text: 'A map shows the land area in New York State drained by the Oswego River and its tributaries, including areas near Lake Ontario, Rochester, Binghamton, Elmira, Ithaca, Syracuse, Utica, Geneva, and the Erie Canal. The land area drained by the Oswego River and its tributaries is called a',
      choices: [
        'delta',
        'watershed',
        'water table',
        'floodplain',
      ],
      topic: 'Water Cycle',
      correct: 1,
      image: '/images/exams/es-august-2019/q29.png',
      explanation: 'A watershed (drainage basin) is the entire land area that drains into a particular river and its tributaries.',
      diveDeep: 'A watershed is all the land from which water flows into a single river system, separated from neighboring basins by divides. A delta is the sediment deposit at a river’s mouth, the water table is the top of the saturated zone underground, and a floodplain is the flat land bordering a river that floods. The trap is confusing these water-related terms. Focus on the phrase "land area drained by a river" — that defines a watershed.',
    },
    {
      number: 30,
      part: 'A',
      text: 'A photograph shows a portion of the Genesee River in western New York. Letters A, B, C, and D are locations in the river, with A on an outer bend, B on an inner bend, C on a straight section, and D on another outer bend. At which location would deposition of sediments most likely be greater than erosion?',
      choices: [
        'A',
        'B',
        'C',
        'D',
      ],
      topic: 'Water Cycle',
      correct: 2,
      image: '/images/exams/es-august-2019/q30.png',
      explanation: 'Deposition exceeds erosion where water moves slowest; on the inside of a meander bend the current is slow, so sediment is deposited there.',
      diveDeep: 'In a meandering stream, water flows fastest on the outside of a bend (causing erosion and cut banks) and slowest on the inside (causing deposition and point bars). The answer key marks the inner-bend location as the depositional site. The trap is choosing an outer bend, where erosion dominates. Remember the rule: outside of the curve = fast water = erosion; inside of the curve = slow water = deposition.',
    },
    {
      number: 31,
      part: 'A',
      text: 'The rate of soil development in tropical areas is usually greater than the rate of soil development in arctic areas because tropical areas have',
      choices: [
        'less chemical weathering and a scarcity of living organisms',
        'less chemical weathering and an abundance of living organisms',
        'more chemical weathering and a scarcity of living organisms',
        'more chemical weathering and an abundance of living organisms',
      ],
      topic: 'Climate',
      correct: 3,
      explanation: 'Tropical climates are warm and wet, which speeds up chemical weathering, and they support abundant living organisms; both factors accelerate soil formation.',
      diveDeep: 'Chemical weathering is fastest in warm, moist climates because heat and water drive the chemical reactions that break down rock. Tropical regions also teem with plants, animals, and microbes that add organic matter and aid weathering. Arctic regions are cold and dry, slowing both processes, so soil forms slowly there. The trap pairs one correct factor with one wrong one; the tropics have both more chemical weathering and more organisms.',
    },
    {
      number: 32,
      part: 'A',
      text: 'New York State’s Finger Lakes exist today because',
      choices: [
        'U-shaped valleys were dammed by glacial sediments',
        'V-shaped valleys are being eroded by streams',
        'a drop in sea level occurred, leaving the lakes',
        'a rise in sea level occurred, flooding the region',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'The Finger Lakes formed when glaciers carved deep U-shaped valleys that were later dammed at their ends by deposits of glacial sediment, trapping water.',
      diveDeep: 'Glaciers carve broad, deep U-shaped valleys, whereas streams carve narrow V-shaped valleys. As the glaciers retreated, they left behind moraines (sediment dams) that blocked the valley ends, allowing meltwater to pool into the long, deep Finger Lakes. The trap "V-shaped valleys" describes stream erosion, not glacial. Sea-level changes are irrelevant for these inland lakes. Associate U-shaped valleys and lake-damming with glacial activity.',
    },
    {
      number: 33,
      part: 'A',
      text: 'Which igneous rock could physically weather to beach sand that contains the minerals pyroxene, plagioclase feldspar, and olivine?',
      choices: [
        'dunite',
        'granite',
        'peridotite',
        'gabbro',
      ],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'Gabbro is composed of pyroxene, plagioclase feldspar, and olivine, so weathering it would release exactly those minerals into the sand.',
      diveDeep: 'Use the Scheme for Igneous Rock Identification chart, which shows each rock’s mineral composition. Gabbro contains plagioclase feldspar, pyroxene, and olivine, matching the sand. Granite contains quartz and potassium feldspar instead, so it is wrong. Dunite and peridotite are dominated by olivine and lack the full pyroxene-plagioclase combination. Match all three listed minerals to a single rock using the composition bars on the chart.',
    },
    {
      number: 34,
      part: 'A',
      text: 'Which two physical properties of graphite make it a good mineral for use in pencils?',
      choices: [
        'luster and fracture',
        'cleavage and color',
        'hardness and streak',
        'greasy feel and composition',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'Graphite is very soft (low hardness) so it scratches off easily onto paper, and it leaves a dark gray-to-black streak — the mark you write with.',
      diveDeep: 'The Properties of Common Minerals chart lists graphite as soft (hardness 1–2) with a black-to-gray streak, both ideal for marking paper. Hardness lets bits flake off as you write, and the streak is the color of the mark left behind. The trap "greasy feel and composition" names a real property (graphite does feel greasy) but composition does not explain its writing ability. Focus on the properties that physically allow it to make a mark: softness and streak.',
    },
    {
      number: 35,
      part: 'A',
      text: 'Which mineral is produced when two atoms of iron chemically combine with three atoms of oxygen?',
      choices: [
        'garnet',
        'pyrite',
        'magnetite',
        'hematite',
      ],
      topic: 'Geology',
      correct: 3,
      explanation: 'Two iron atoms combined with three oxygen atoms give the formula Fe₂O₃, which is the composition of hematite.',
      diveDeep: 'The Properties of Common Minerals chart lists hematite’s composition as Fe₂O₃ and magnetite’s as Fe₃O₄ — note the different ratios. The trap is magnetite, another iron oxide, but its formula has three iron and four oxygen atoms, not two and three. Pyrite is FeS₂ (an iron sulfide) and garnet is a silicate, so both are eliminated by composition. Translate the worded ratio (2 Fe : 3 O) into a formula and match it to the chart.',
    },
    // Part B-1: Questions 36–38 are based on a map showing the locations of Jamestown, Watertown, and Kingston in New York State.
    {
      number: 36,
      part: 'B-1',
      context: 'Base your answers to questions 36 through 38 on the map below and on your knowledge of Earth science. The map shows the locations of Jamestown, Watertown, and Kingston in New York State.',
      text: 'Compared to the time of sunrise in Kingston, the time of sunrise in Jamestown would be approximately',
      choices: [
        '1 hour earlier',
        '1 hour later',
        '20 minutes earlier',
        '20 minutes later',
      ],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-august-2019/q36.png',
      explanation: 'Jamestown lies west of Kingston, and because Earth rotates west to east, locations farther west experience sunrise later — about 20 minutes later for this small longitude difference.',
      diveDeep: 'Earth rotates 15° of longitude per hour, so 1° equals 4 minutes of time; the roughly 5° longitude gap between the two cities gives about 20 minutes. Because the Sun rises in the east, eastern locations see sunrise first and western locations later. The trap is the direction (earlier vs. later): farther west = later sunrise. Determine which city is west, then estimate the time difference from the longitude separation.',
    },
    {
      number: 37,
      part: 'B-1',
      context: 'Base your answers to questions 36 through 38 on the map below and on your knowledge of Earth science. The map shows the locations of Jamestown, Watertown, and Kingston in New York State.',
      text: 'An observer in Watertown, New York, would see the star Polaris at an altitude of approximately',
      choices: [
        '44°',
        '45°',
        '75°',
        '76°',
      ],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-august-2019/q37.png',
      explanation: 'The altitude of Polaris equals the observer’s latitude; Watertown is at about 44° N, so Polaris appears at an altitude of about 44°.',
      diveDeep: 'A key rule in Earth science: the altitude of Polaris above the northern horizon equals your latitude. Read Watertown’s latitude from the map (about 44° N) and that is your answer directly. The trap choices (75°, 76°) tempt students who confuse latitude with longitude or misread the grid. Always recall "Polaris altitude = latitude" for any northern-hemisphere observer.',
    },
    {
      number: 38,
      part: 'B-1',
      context: 'Base your answers to questions 36 through 38 on the map below and on your knowledge of Earth science. The map shows the locations of Jamestown, Watertown, and Kingston in New York State.',
      text: 'Earth’s system of longitude is based on which motion?',
      choices: [
        'Earth’s rotation',
        'the Sun’s rotation',
        'Earth’s revolution around the Sun',
        'the Sun’s revolution around Earth',
      ],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-august-2019/q38.png',
      explanation: 'Longitude and time zones are based on Earth’s rotation, which carries each meridian past the Sun once every 24 hours.',
      diveDeep: 'Earth rotates 360° of longitude in 24 hours, which is why longitude underlies our system of time (15° = 1 hour). Latitude, by contrast, relates to the Sun’s angle and the poles, not rotation timing. The trap answers involving the Sun’s motion are incorrect because the apparent solar motion is itself a result of Earth’s rotation. Connect longitude and time directly to Earth’s daily spin.',
    },
    // Part B-1: Questions 39–41 are based on the passage and photograph about the Patagonia Marble Caves found in South America.
    {
      number: 39,
      part: 'B-1',
      context: 'Base your answers to questions 39 through 41 on the passage and photograph below and on your knowledge of Earth science. The Patagonia Marble Caves of South America are found on the shores of General Carrera Lake at a location of 46.5° S 72° W. Most of the water in the lake comes from the melting of nearby glaciers. Over the last 6200 years, the water of the lake has been weathering and eroding the marble bedrock found along the shores and within the lake itself, producing countless caves, mazes, columns, and tunnels.',
      text: 'A map shows four locations in South America, labeled A, B, C, and D. Which lettered point on the map best represents the location of the Patagonia Marble Caves?',
      choices: [
        'A',
        'B',
        'C',
        'D',
      ],
      topic: 'Maps',
      correct: 2,
      image: '/images/exams/es-august-2019/q39.png',
      explanation: 'The coordinates 46.5° S, 72° W place the caves in southern South America, matching point C on the map.',
      diveDeep: 'Plot the latitude and longitude separately: 46.5° S is well south of the equator (toward the southern tip of the continent) and 72° W is on the western (Pacific) side. Find where those two lines intersect to identify the correct point. The traps are points at the wrong latitude (too far north) or wrong longitude (eastern side). Always cross-reference both coordinates rather than estimating from one.',
    },
    {
      number: 40,
      part: 'B-1',
      context: 'Base your answers to questions 39 through 41 on the passage and photograph below and on your knowledge of Earth science. The Patagonia Marble Caves of South America are found on the shores of General Carrera Lake at a location of 46.5° S 72° W. Most of the water in the lake comes from the melting of nearby glaciers. Over the last 6200 years, the water of the lake has been weathering and eroding the marble bedrock, producing countless caves, mazes, columns, and tunnels.',
      text: 'Which two processes formed the marble bedrock shown in the photograph?',
      choices: [
        'heat and pressure',
        'compaction and cementation',
        'melting and solidification',
        'precipitation and evaporation',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'Marble is a metamorphic rock, and metamorphic rocks form from heat and pressure that recrystallize a parent rock (limestone, in this case).',
      diveDeep: 'Marble forms when limestone is subjected to heat and pressure, recrystallizing into a metamorphic rock, as shown on the Scheme for Metamorphic Rock Identification. The trap "compaction and cementation" describes how sedimentary rocks (like limestone) form, and "melting and solidification" describes igneous rocks. Match the rock type to its formation process: metamorphic = heat and pressure. Knowing the three rock-forming process pairs lets you answer these quickly.',
    },
    {
      number: 41,
      part: 'B-1',
      context: 'Base your answers to questions 39 through 41 on the passage and photograph below and on your knowledge of Earth science. The Patagonia Marble Caves of South America are found on the shores of General Carrera Lake at a location of 46.5° S 72° W. Most of the water in the lake comes from the melting of nearby glaciers. Over the last 6200 years, the water of the lake has been weathering and eroding the marble bedrock, producing countless caves, mazes, columns, and tunnels.',
      text: 'Most marble is composed primarily of',
      choices: [
        'quartz and/or potassium feldspar',
        'calcite and/or dolomite',
        'halite and/or olivine',
        'pyroxene and/or plagioclase feldspar',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Marble forms from limestone or dolostone, so it is composed primarily of the carbonate minerals calcite and/or dolomite.',
      diveDeep: 'The Scheme for Metamorphic Rock Identification lists marble’s composition as calcite and/or dolomite, the same carbonate minerals found in its parent rocks limestone and dolostone. This is why the lake water can chemically weather (dissolve) the marble to form caves — carbonate minerals react with slightly acidic water. The trap "quartz and/or potassium feldspar" describes quartzite or gneiss, not marble. Link marble to carbonate minerals and dissolution-based cave formation.',
    },
    // Part B-1: Questions 42–44 are based on photographs showing a digital weather device and two weather instruments (A and B).
    {
      number: 42,
      part: 'B-1',
      context: 'Base your answers to questions 42 through 44 on the photographs below and on your knowledge of Earth science. One photograph shows a digital device that recorded several weather variables including inside/outside temperature, humidity, cloud cover, time, date, pressure, pressure trend, wind direction (SSE), and wind speed. The second photograph shows two weather instruments, labeled A and B.',
      text: 'The barometric pressure was recorded on the digital device in millibars. What is the equivalent air pressure in inches of mercury (Hg)?',
      choices: [
        '29.59 in of Hg',
        '29.60 in of Hg',
        '29.62 in of Hg',
        '29.65 in of Hg',
      ],
      topic: 'Meteorology',
      correct: 2,
      image: '/images/exams/es-august-2019/q42.png',
      explanation: 'Using the Pressure conversion scale in the Reference Tables, the recorded millibar value aligns with about 29.62 inches of mercury.',
      diveDeep: 'The Earth Science Reference Tables include a Pressure scale that converts between millibars and inches of mercury side by side. Read across from the given millibar reading to the inches-of-mercury column to find the equivalent. The answer choices are very close together, so read the scale carefully and line up the values precisely. Standard sea-level pressure (1013.2 mb = 29.92 in Hg) is a useful checkpoint to confirm you are reading the scale in the right direction.',
    },
    {
      number: 43,
      part: 'B-1',
      context: 'Base your answers to questions 42 through 44 on the photographs below and on your knowledge of Earth science. One photograph shows a digital device that recorded several weather variables including inside/outside temperature, humidity, cloud cover, time, date, pressure, pressure trend, wind direction (SSE), and wind speed. The second photograph shows two weather instruments, labeled A and B.',
      text: 'Based on the outside air temperature and relative humidity shown on the digital device, what is the approximate dewpoint for the time shown on the device?',
      choices: [
        '8°C',
        '12°C',
        '18°C',
        '31°C',
      ],
      topic: 'Meteorology',
      correct: 2,
      image: '/images/exams/es-august-2019/q43.png',
      explanation: 'Using the Dewpoint chart with the device’s dry-bulb (air) temperature and relative humidity, the dewpoint reads approximately 18°C.',
      diveDeep: 'The Dewpoint table in the Reference Tables is normally entered with the dry-bulb temperature and the wet-bulb depression, but it can also be cross-referenced with relative humidity. Higher relative humidity means the dewpoint is closer to the actual air temperature. The trap 31°C would imply the dewpoint exceeds the air temperature, which is impossible — dewpoint can never be higher than air temperature. Use that ceiling to eliminate unreasonable choices before reading the chart.',
    },
    {
      number: 44,
      part: 'B-1',
      context: 'Base your answers to questions 42 through 44 on the photographs below and on your knowledge of Earth science. One photograph shows a digital device that recorded several weather variables. The second photograph shows two weather instruments, labeled A and B.',
      text: 'Which table correctly identifies weather instruments A and B and the weather variable that each measures?',
      choices: [
        'A = wind vane / wind direction; B = anemometer / wind speed',
        'A = anemometer / wind direction; B = wind vane / wind speed',
        'A = anemometer / wind speed; B = wind vane / wind direction',
        'A = wind vane / wind speed; B = anemometer / wind direction',
      ],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-august-2019/q44.png',
      explanation: 'Instrument A is a wind vane, which points into the wind to show wind direction, and instrument B is a cup anemometer, which spins to measure wind speed.',
      diveDeep: 'A wind vane has an arrow/tail that pivots to indicate the direction the wind comes from, while an anemometer has rotating cups whose spin rate measures wind speed. The traps swap the instrument names or the variables they measure. Match each instrument to both its correct name and its correct variable. Remember: vane = direction (points), anemometer = speed (spins).',
    },
    // Part B-1: Questions 45–47 are based on diagrams of a Foucault pendulum and the Coriolis effect on planetary winds.
    {
      number: 45,
      part: 'B-1',
      context: 'Base your answers to questions 45 through 47 on the diagrams below and on your knowledge of Earth science. Diagram A represents a Foucault pendulum set up at a particular location on Earth. The line on the floor marked 0 is the path of the pendulum when it was first set in motion, with apparent shifts shown at 2-hour intervals over 8 hours. Diagram B represents the curving of planetary winds located in two areas of Earth’s surface due to the Coriolis effect, showing the original and deflected paths of wind in both hemispheres.',
      text: 'The apparent shift in the direction of swing of a Foucault pendulum and the curving of winds by the Coriolis effect are both evidence of Earth’s',
      choices: [
        'tilt',
        'shape',
        'rotation',
        'revolution',
      ],
      topic: 'Astronomy',
      correct: 2,
      image: '/images/exams/es-august-2019/q45.png',
      explanation: 'Both the apparent shift of a Foucault pendulum and the Coriolis deflection of winds are classic evidence that Earth rotates on its axis.',
      diveDeep: 'A Foucault pendulum appears to change its swing direction over time because the ground beneath it (Earth) is rotating, not the pendulum itself. The Coriolis effect deflects moving air and water to the right in the Northern Hemisphere and left in the Southern Hemisphere, again due to rotation. The traps (tilt, revolution) are evidence for seasons, not for the daily spin. Memorize the standard "evidence of rotation" list: Foucault pendulum and Coriolis effect.',
    },
    {
      number: 46,
      part: 'B-1',
      context: 'Base your answers to questions 45 through 47 on the diagrams below and on your knowledge of Earth science. Diagram A represents a Foucault pendulum. The apparent shift of the path of the pendulum is shown at two-hour intervals for the first eight hours of pendulum motion. During the eight hours, the pendulum’s path was displaced 60 degrees from where it started.',
      text: 'In diagram A, the apparent shift of the path of the pendulum is shown at two-hour intervals for the first eight hours of pendulum motion. During the eight hours, the pendulum’s path was displaced 60 degrees from where it started. How many degrees did the apparent path of the pendulum change each hour (h)?',
      choices: [
        '7.5°/h',
        '15°/h',
        '60°/h',
        '120°/h',
      ],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-august-2019/q46.png',
      explanation: 'Rate = change in value ÷ time = 60° ÷ 8 hours = 7.5° per hour.',
      diveDeep: 'Apply the rate of change formula from the Reference Tables: divide the total change (60°) by the total time (8 hours) to get 7.5°/h. The trap 15°/h is Earth’s rotation rate (360° ÷ 24 h), which is not what this question asks. Always plug into rate = (final − initial) ÷ time and double-check the units. Reading the question for the actual quantities given prevents using a memorized-but-wrong value.',
    },
    {
      number: 47,
      part: 'B-1',
      context: 'Base your answers to questions 45 through 47 on the diagrams below and on your knowledge of Earth science. Diagram B represents the curving of planetary winds in the Northern and Southern hemispheres due to the Coriolis effect, showing the original direction of wind and the deflected path of wind.',
      text: 'In diagram B, what are the names of the planetary wind belts formed by the deflected winds shown in the Northern and Southern hemispheres?',
      choices: [
        'Northern: Southeast winds; Southern: Northwest winds',
        'Northern: Southwest winds; Southern: Northwest winds',
        'Northern: Northeast winds; Southern: Southeast winds',
        'Northern: Northwest winds; Southern: Southeast winds',
      ],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-august-2019/q47.png',
      explanation: 'Winds are named for the direction they come from; the deflected belts shown correspond to southwest winds in the Northern Hemisphere and northwest winds in the Southern Hemisphere.',
      diveDeep: 'Use the Planetary Wind and Moisture Belts diagram and remember that winds are named for the direction FROM which they blow, not toward. The Coriolis effect bends winds right in the Northern Hemisphere and left in the Southern Hemisphere, producing the curved arrows shown. The trap is naming winds by the direction they head toward. Trace each arrow back to its origin direction to label the belt correctly.',
    },
    // Part B-1: Questions 48–50 are based on a cross section showing the boundary between the Juan de Fuca Plate and the North American Plate.
    {
      number: 48,
      part: 'B-1',
      context: 'Base your answers to questions 48 through 50 on the cross section below and on your knowledge of Earth science. The cross section shows the boundary between the Juan de Fuca Plate and the North American Plate, with the Juan de Fuca Plate (oceanic crust) subducting beneath the North American Plate (continental crust), with mantle shown below both plates.',
      text: 'In which diagram do the arrows best represent the relative motion of the upper mantle at this plate boundary?',
      choices: [
        'arrows showing mantle moving upward beneath both plates equally',
        'arrows showing mantle moving only toward the Juan de Fuca side',
        'arrows showing mantle moving only away from the boundary on both sides',
        'arrows showing mantle convecting downward beneath the subducting oceanic plate and upward elsewhere',
      ],
      topic: 'Plate Tectonics',
      correct: 3,
      image: '/images/exams/es-august-2019/q48.png',
      explanation: 'At a subduction (convergent) boundary, mantle convection carries material downward where the dense oceanic plate sinks, with rising flow elsewhere, driving the plate motion.',
      diveDeep: 'Mantle convection cells drive plate tectonics: hot material rises, spreads, cools, and sinks. At a subduction zone the descending oceanic plate is associated with downward-moving (sinking) mantle flow, consistent with the convergent arrows on the Tectonic Plates and Inferred Properties diagrams in the Reference Tables. The traps show uniform or symmetric flow that would not produce subduction. Match the mantle arrows to the direction the dense plate is sinking.',
    },
    {
      number: 49,
      part: 'B-1',
      context: 'Base your answers to questions 48 through 50 on the cross section below and on your knowledge of Earth science. The cross section shows the boundary between the Juan de Fuca Plate and the North American Plate, with oceanic crust subducting beneath continental crust.',
      text: 'Compared to the crust of the North American Plate, the crust of the Juan de Fuca Plate is',
      choices: [
        'thicker and less dense',
        'thicker and more dense',
        'thinner and less dense',
        'thinner and more dense',
      ],
      topic: 'Geology',
      correct: 3,
      image: '/images/exams/es-august-2019/q49.png',
      explanation: 'The Juan de Fuca Plate is oceanic crust, which is thinner and more dense than the continental crust of the North American Plate, which is why it subducts beneath it.',
      diveDeep: 'Oceanic crust is basaltic, thin (about 5–10 km), and dense (about 3.0 g/cm³), while continental crust is granitic, thick (up to ~70 km), and less dense (about 2.7 g/cm³). Because the oceanic plate is denser, it sinks beneath the continental plate at convergent boundaries — exactly the subduction shown. The Inferred Properties of Earth’s Interior chart confirms these density and thickness differences. Remember: oceanic = thin and dense; continental = thick and less dense.',
    },
    {
      number: 50,
      part: 'B-1',
      context: 'Base your answers to questions 48 through 50 on the cross section below and on your knowledge of Earth science. The cross section shows the boundary between the Juan de Fuca Plate and the North American Plate.',
      text: 'The boundary between the asthenosphere and the stiffer mantle is located below the Earth’s surface at a depth of approximately',
      choices: [
        '100 km',
        '700 km',
        '2500 km',
        '3000 km',
      ],
      topic: 'Geology',
      correct: 1,
      image: '/images/exams/es-august-2019/q50.png',
      explanation: 'On the Inferred Properties of Earth’s Interior diagram, the boundary between the asthenosphere and the stiffer mantle lies at a depth of about 700 km.',
      diveDeep: 'The Inferred Properties of Earth’s Interior diagram in the Reference Tables labels each layer boundary by depth: the asthenosphere extends to roughly 700 km, where the stiffer mantle begins. The traps correspond to other boundaries — 100 km is near the lithosphere/asthenosphere transition, and 2900 km is the mantle/outer-core boundary. Read depth values directly off the chart rather than estimating. Knowing the labeled depths of each interior boundary makes these questions straightforward.',
    },
  ],
}
