// Earth Science Regents — August 2024
// Source: esci82024-examw.pdf, esci82024-sk.pdf
export default {
  id: 'es-august-2024',
  subject: 'earth-science',
  year: 2024,
  session: 'August',
  totalMinutes: 180,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'A graph shows the change in water level height measured in meters (m) at the Brooklyn Bridge in New York City on July 9, 2018. According to the pattern shown on the graph, the next high tide will occur on July 10 at approximately',
      choices: ['5:24 a.m.', '6:53 a.m.', '5:24 p.m.', '6:53 p.m.'],
      topic: 'General',
      correct: 1,
      image: '/images/exams/es-august-2024/q1.png',
    },
    {
      number: 2, part: 'A',
      text: 'Which event is correlated with an asteroid impact on Earth that occurred approximately 65 million years ago?',
      choices: ['extinction of the ammonoids', 'the breaking up of Pangaea', 'closing of the Iapetus Ocean', 'peak development of eurypterids'],
      topic: 'Astronomy',
      correct: 0,
    },
    {
      number: 3, part: 'A',
      text: 'Light observed from most galaxies in our universe shows a shift toward the',
      choices: ['blue end of the spectrum and is evidence of a contracting universe', 'blue end of the spectrum and is evidence of an expanding universe', 'red end of the spectrum and is evidence of a contracting universe', 'red end of the spectrum and is evidence of an expanding universe'],
      topic: 'Astronomy',
      correct: 3,
    },
    {
      number: 4, part: 'A',
      text: 'The Milky Way is classified as a',
      choices: ['large constellation', 'metallic asteroid', 'spiral galaxy', 'white dwarf star'],
      topic: 'General',
      correct: 2,
    },
    {
      number: 5, part: 'A',
      text: 'What is the approximate altitude of Polaris at Riverhead, New York?',
      choices: ['41°', '49°', '73°', '90°'],
      topic: 'General',
      correct: 0,
    },
    {
      number: 6, part: 'A',
      text: 'Which instrument provides direct evidence of Earth\'s rotation? (Four instruments are shown: a barometer, a compass, a Foucault pendulum, and a thermometer.)',
      choices: ['barometer', 'compass', 'Foucault pendulum', 'thermometer'],
      topic: 'Meteorology',
      correct: 3,
    },
    {
      number: 7, part: 'A',
      text: 'Rural areas on Long Island, New York, receive approximately the same amount of yearly precipitation as the urban areas of New York City. Compared to rural areas on Long Island, the urban areas of New York City most likely have',
      choices: ['less runoff and less infiltration', 'less runoff and more infiltration', 'more runoff and less infiltration', 'more runoff and more infiltration'],
      topic: 'Meteorology',
      correct: 2,
    },
    {
      number: 8, part: 'A',
      text: 'Which diagram best represents the positions of the equator, Earth\'s axis with the North Pole labeled (N), and Polaris (*) relative to each other? (Polaris is directly above the North Pole, aligned with Earth\'s axis.)',
      choices: ['Polaris above equator, axis tilted', 'Polaris beside axis, not aligned', 'Polaris directly above North Pole, aligned with axis', 'Polaris below equator'],
      topic: 'General',
      correct: 3,
      image: '/images/exams/es-august-2024/q8.png',
    },
    {
      number: 9, part: 'A',
      text: 'Earth\'s early atmosphere is inferred to have been formed during the Early Archean Era primarily by',
      choices: ['asteroid impacts', 'coal-forming forests', 'radioactive decay', 'volcanic outgassing'],
      topic: 'Meteorology',
      correct: 3,
    },
    {
      number: 10, part: 'A',
      text: 'In the water cycle, it can be inferred that precipitation has occurred if',
      choices: ['grass is covered with frost', 'trees are covered with snow', 'coastal fog moves inland', 'ponds are covered with ice'],
      topic: 'Meteorology',
      correct: 1,
    },
    {
      number: 11, part: 'A',
      text: 'The photograph shows the Great Square of Pegasus, consisting of a pattern of four stars, as viewed from New York State during the fall season. Which motion causes this square pattern of stars to be visible in the nighttime sky from New York State in the fall, but not in the spring?',
      choices: ['rotation of Earth on its axis', 'rotation of stars in the Great Square of Pegasus', 'revolution of Earth around the Sun', 'revolution of the Great Square of Pegasus around Earth'],
      topic: 'Astronomy',
      correct: 2,
      image: '/images/exams/es-august-2024/q11.png',
    },
    {
      number: 12, part: 'A',
      text: 'The arrow on which map shows the most likely path of a hurricane in the Atlantic Ocean?',
      choices: ['Map (1) — straight north path', 'Map (2) — straight west path', 'Map (3) — curved northeast path', 'Map (4) — southeast path'],
      topic: 'Meteorology',
      correct: 3,
      image: '/images/exams/es-august-2024/q12.png',
    },
    {
      number: 13, part: 'A',
      text: 'The diagram represents a thunderstorm cloud. Arrows represent air motion within the cloud — updrafts of warm air and downdrafts of cold air. This air motion is caused by',
      choices: ['density differences', 'electromagnetic energy', 'molecular collisions', 'increased transpiration'],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-august-2024/q13.png',
    },
    {
      number: 14, part: 'A',
      text: 'What is the relative humidity when the dry-bulb temperature is 28°C and the wet-bulb temperature is 15°C?',
      choices: ['12%', '13%', '21%', '4%'],
      topic: 'Meteorology',
      correct: 2,
    },
    {
      number: 15, part: 'A',
      text: 'Which diagram best represents the wavelength of incoming solar radiation received on Earth and the wavelength of outgoing radiation? (Incoming solar = shortwave; outgoing Earth radiation = longwave.)',
      choices: ['Incoming longwave / outgoing shortwave', 'Incoming shortwave / outgoing longwave — correct', 'Incoming and outgoing both shortwave', 'Incoming and outgoing both longwave'],
      topic: 'General',
      correct: 1,
      image: '/images/exams/es-august-2024/q15.png',
    },
    {
      number: 16, part: 'A',
      text: 'Which statement best explains why most of the surface of Lake Erie usually remains as liquid water in late autumn, even though surrounding land surfaces and air temperatures may be below freezing?',
      choices: ['Water has a higher specific heat than land.', 'Land surfaces change temperature more slowly than water surfaces.', 'Warm winds from the land blow onto the surface of the lake.', 'Energy absorption by the water is needed in order to freeze the surface of the lake.'],
      topic: 'Meteorology',
      correct: 0,
    },
    {
      number: 17, part: 'A',
      text: 'A photograph shows the large-scale eruption of volcanic ash from Mount Kelud in Indonesia in 2014. This volcanic ash in the atmosphere causes',
      choices: ['less transparency and a decrease in reflection of insolation', 'less transparency and an increase in reflection of insolation', 'more transparency and a decrease in reflection of insolation', 'more transparency and an increase in reflection of insolation'],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-august-2024/q17.png',
    },
    {
      number: 18, part: 'A',
      text: 'Ireland and England, islands along the northwest coast of Europe, have climates that are warmer than the climate of New York State, even though these islands are located farther north. This increased average temperature is mostly due to heat supplied by the prevailing winds and the',
      choices: ['Canary Current', 'North Atlantic Current', 'North Equatorial Current', 'Labrador Current'],
      topic: 'Climate',
      correct: 1,
    },
    {
      number: 19, part: 'A',
      text: 'The diagram shows the front fin bones of a Devonian fish and the front leg bones of a present-day amphibian (labeled a, b, c = humerus, radius, ulna). Similarities in bone structure and arrangement between these two animals support the inference that these animals',
      choices: ['both lived during the Devonian Period', 'have a common ancestor', 'lived in an arid environment', 'became fossilized the same way'],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-august-2024/q19.png',
    },
    {
      number: 20, part: 'A',
      text: 'Surface bedrock found in the St. Lawrence Lowlands region of New York State was formed during which periods of geologic time?',
      choices: ['Triassic and Jurassic', 'Mississippian and Pennsylvanian', 'Silurian and Devonian', 'Cambrian and Ordovician'],
      topic: 'Geology',
      correct: 3,
    },
    {
      number: 21, part: 'A',
      text: 'Volcanic ash is most useful for determining the relative age of rock layers because the ash is deposited during a',
      choices: ['short period of time over a large area', 'short period of time over a small area', 'long period of time over a large area', 'long period of time over a small area'],
      topic: 'Geology',
      correct: 0,
    },
    {
      number: 22, part: 'A',
      text: 'Sediments that form a sedimentary rock usually are deposited in a layer that is parallel to Earth\'s surface. This statement best describes the',
      choices: ['law of superposition', 'theory of evolution', 'principle of original horizontality', 'rule of crosscutting relationships'],
      topic: 'Geology',
      correct: 2,
    },
    {
      number: 23, part: 'A',
      text: 'The diagram represents rock columns I and II found at two different locations. Different rock layers are labeled A, B, C, D at location I and X at location II. The rock layers have not been overturned. Which labeled rock layer at location I would most likely have the same relative age as rock layer X at location II?',
      choices: ['A', 'B', 'C', 'D'],
      topic: 'Geology',
      correct: 2,
      image: '/images/exams/es-august-2024/q23.png',
    },
    {
      number: 24, part: 'A',
      text: 'Which evidence supports the inference that South America and Africa were once joined together as part of the supercontinent Pangaea?',
      choices: ['Desert climates are found in the interior of both South America and Africa.', 'Rock and fossil correlation can be made where the two continents appear to fit together.', 'Mountain glaciers are found in the interiors of both South America and Africa.', 'The age of oceanic bedrock is youngest along the coastlines of the two continents and oldest at the Mid-Atlantic Ridge.'],
      topic: 'Plate Tectonics',
      correct: 1,
    },
    {
      number: 25, part: 'A',
      text: 'The Tonga Trench is located at which type of plate boundary?',
      choices: ['convergent', 'divergent', 'transform', 'complex'],
      topic: 'Plate Tectonics',
      correct: 0,
    },
    {
      number: 26, part: 'A',
      text: 'The map shows a stream drainage pattern (radial pattern — streams flowing outward from a central high point). This drainage pattern most likely formed on the surface bedrock of which block diagram?',
      choices: ['flat plateau', 'dome-shaped structure', 'tilted beds', 'folded mountains'],
      topic: 'Water Cycle',
      correct: 3,
      image: '/images/exams/es-august-2024/q26.png',
    },
    {
      number: 27, part: 'A',
      text: 'The Hudson River begins its flow at Lake Tear of the Clouds near Mt. Marcy, NY (elevation 4293 feet) and travels 162 miles to Troy, NY (elevation 2 feet). The gradient of the Hudson River between Lake Tear of the Clouds and Troy is approximately',
      choices: ['4291.00 ft/mi', '81.00 ft/mi', '26.49 ft/mi', '0.04 ft/mi'],
      topic: 'Water Cycle',
      correct: 2,
    },
    {
      number: 28, part: 'A',
      text: 'The mountain landscape at Old Forge, New York, and the plateau landscape at Slide Mt., New York, are classified based on the differences in',
      choices: ['climate', 'weathering', 'stream drainage', 'bedrock structure'],
      topic: 'Geology',
      correct: 3,
    },
    {
      number: 29, part: 'A',
      text: 'The diagram represents a landscape region located in the southwestern United States. The steep slopes and sharp angular features of this region indicate that, compared to New York State, the climate where this landscape is developing most likely has',
      choices: ['lower temperatures and a lower amount of precipitation', 'lower temperatures and a higher amount of precipitation', 'higher temperatures and a lower amount of precipitation', 'higher temperatures and a higher amount of precipitation'],
      topic: 'Climate',
      correct: 2,
      image: '/images/exams/es-august-2024/q29.png',
    },
    {
      number: 30, part: 'A',
      text: 'A photograph shows a valley between two mountains in Acadia National Park in the state of Maine. The shape of this valley is best described as',
      choices: ['U-shaped and eroded by moving ice', 'U-shaped and eroded by running water', 'V-shaped and eroded by moving ice', 'V-shaped and eroded by running water'],
      topic: 'Geology',
      correct: 0,
      image: '/images/exams/es-august-2024/q30.png',
    },
    {
      number: 31, part: 'A',
      text: 'The photograph shows three different pebbles that have been transported for different amounts of time in a stream. The erosional process that has shaped these pebbles over time is',
      choices: ['abrasion, which causes less rounding', 'abrasion, which causes more rounding', 'sandblasting, which causes less rounding', 'sandblasting, which causes more rounding'],
      topic: 'Water Cycle',
      correct: 1,
      image: '/images/exams/es-august-2024/q31.png',
    },
    {
      number: 32, part: 'A',
      text: 'Which satellite photograph best shows the result of the deposition of river sediments into a large body of water?',
      choices: ['Image showing delta formation at river mouth', 'Image showing straight coastline', 'Image showing fjord', 'Image showing barrier island'],
      topic: 'Water Cycle',
      correct: 0,
    },
    {
      number: 33, part: 'A',
      text: 'The diagram represents a stream in a valley. Letter X represents a surface feature associated with the stream. Which surface feature is represented by letter X?',
      choices: ['floodplain', 'kettle lake', 'water table', 'watershed'],
      topic: 'Water Cycle',
      correct: 0,
      image: '/images/exams/es-august-2024/q33.png',
    },
    {
      number: 34, part: 'A',
      text: 'The famous green-sand beach on the Big Island of Hawaii gets its color from green colored grains of which mineral?',
      choices: ['pyrite', 'gypsum', 'olivine', 'hematite'],
      topic: 'Geology',
      correct: 2,
    },
    {
      number: 35, part: 'A',
      text: 'Which metamorphic rock forms only by contact metamorphism?',
      choices: ['slate', 'gneiss', 'marble', 'hornfels'],
      topic: 'Geology',
      correct: 3,
    },

    // Part B-1
    {
      number: 36, part: 'B-1',
      context: 'A geologic cross section shows the bedrock structure beneath a portion of the Hudson Highlands and Newark Lowlands landscape regions along the border between New York State and northern New Jersey. Letters X and Y identify bedrock units. The Palisades Sill igneous intrusion is identified.',
      text: 'Fossil evidence of which animal is most likely preserved in bedrock unit X?',
      choices: ['Coelophysis', 'Phacops', 'Eurypterus', 'Tetragraptus'],
      topic: 'Geology',
      correct: 0,
      image: '/images/exams/es-august-2024/q36.png',
    },
    {
      number: 37, part: 'B-1',
      context: 'A geologic cross section shows the bedrock structure beneath a portion of the Hudson Highlands and Newark Lowlands landscape regions along the border between New York State and northern New Jersey. Letters X and Y identify bedrock units. The Palisades Sill igneous intrusion is identified.',
      text: 'Compared to the other bedrock units, the relative age of the Palisades Sill intrusion is',
      choices: ['younger than X, but older than Y', 'younger than Y, but older than X', 'younger than both X and Y', 'older than both X and Y'],
      topic: 'Geology',
      correct: 2,
      image: '/images/exams/es-august-2024/q37.png',
    },
    {
      number: 38, part: 'B-1',
      context: 'A geologic cross section shows the bedrock structure beneath a portion of the Hudson Highlands and Newark Lowlands landscape regions along the border between New York State and northern New Jersey. The Palisades Sill igneous intrusion is identified.',
      text: 'Approximately how many million years ago (mya) did the intrusion of the Palisades Sill occur?',
      choices: ['100 mya', '200 mya', '300 mya', '400 mya'],
      topic: 'General Review',
      correct: 1,
      image: '/images/exams/es-august-2024/q38.png',
    },
    {
      number: 39, part: 'B-1',
      context: 'A map represents an imaginary continent on a planet with climate conditions similar to Earth. Points A through G represent locations on the continent. Arrows represent the general direction of prevailing winds. Mountains are shown.',
      text: 'Which climate factor causes location B to have a warmer climate than location E?',
      choices: ['latitude', 'longitude', 'vegetative cover', 'nearness to a large body of water'],
      topic: 'Climate',
      correct: 0,
      image: '/images/exams/es-august-2024/q39.png',
    },
    {
      number: 40, part: 'B-1',
      context: 'A map represents an imaginary continent on a planet with climate conditions similar to Earth. Points A through G represent locations on the continent. Mountains are shown.',
      text: 'At which location does high elevation cause temperatures to remain low all year with frequent snow events?',
      choices: ['E', 'F', 'G', 'D'],
      topic: 'Geologic Time',
      correct: 1,
      image: '/images/exams/es-august-2024/q40.png',
    },
    {
      number: 41, part: 'B-1',
      context: 'Diagrams represent the apparent paths and solar noon positions of the Sun on specific dates at four different Earth locations (A, B, C, D). Location D is at the North Pole.',
      text: 'At which location and on which date would the observer not experience sunrise or sunset?',
      choices: ['location A on June 21', 'location B on December 21', 'location C on March 21 or September 23', 'location D on December 21'],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-august-2024/q41.png',
    },
    {
      number: 42, part: 'B-1',
      context: 'Diagrams represent the apparent paths and solar noon positions of the Sun on specific dates at four different Earth locations (A, B, C, D).',
      text: 'For the observer at location B, the Sun appears to move across the sky on June 21 at the rate of',
      choices: ['1°/hour', '15°/hour', '23.5°/hour', '365°/hour'],
      topic: 'Astronomy',
      correct: 1,
      image: '/images/exams/es-august-2024/q42.png',
    },
    {
      number: 43, part: 'B-1',
      context: 'Diagrams represent the apparent paths and solar noon positions of the Sun on specific dates at four different Earth locations (A, B, C, D). Location C is in the Southern Hemisphere.',
      text: 'Which phrase most accurately describes the length and direction of the observer\'s noontime shadow at location C on December 21 and June 21?',
      choices: ['same length, but in opposite directions', 'same length in the same direction', 'different lengths, but in the opposite directions', 'different lengths in the same direction'],
      topic: 'General Review',
      correct: 0,
      image: '/images/exams/es-august-2024/q43.png',
    },
    {
      number: 44, part: 'B-1',
      context: 'Diagrams represent the apparent paths and solar noon positions of the Sun on specific dates at four different Earth locations.',
      text: 'Which statement best explains why the solar noon position of the Sun changes throughout the year at each of these locations?',
      choices: ['The orbital velocity of Earth increases as it travels around the Sun.', 'The tilt of Earth\'s axis changes in a cyclic pattern.', 'Earth revolves around the Sun on a tilted axis.', 'Earth rotates faster in the summer and slower in the winter.'],
      topic: 'Astronomy',
      correct: 2,
      image: '/images/exams/es-august-2024/q44.png',
    },
    {
      number: 45, part: 'B-1',
      context: 'Map I shows the East African Rift System including the Ethiopian Rift and East African Rift, located along the edges of three tectonic plates (Nubian, Somalian, Arabian). In April 2018, a large crack formed in the eastern branch of the rift.',
      text: 'What event is associated with the formation of the large crack in the eastern branch of the East African Rift in April 2018?',
      choices: ['tsunami', 'flooding', 'downwarping', 'earthquake'],
      topic: 'Plate Tectonics',
      correct: 3,
    },
    {
      number: 46, part: 'B-1',
      context: 'Map I shows the East African Rift System. Active rifts occur where tectonic plates are pulling apart (divergent boundary).',
      text: 'Which characteristic best describes the rock that forms at Earth\'s surface where these active rifts occur?',
      choices: ['volcanic', 'plutonic', 'clastic', 'bioclastic'],
      topic: 'Geology',
      correct: 0,
    },
    {
      number: 47, part: 'B-1',
      context: 'Map I shows the East African Rift System including the Afar Region to the north and three tectonic plates: Nubian, Somalian, and Arabian.',
      text: 'On which major tectonic plate is the Afar Region located?',
      choices: ['Eurasian Plate', 'African Plate', 'Arabian Plate', 'Indian-Australian Plate'],
      topic: 'Plate Tectonics',
      correct: 1,
    },
    {
      number: 48, part: 'B-1',
      context: 'A diagram represents our solar system planets in order of distance from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.',
      text: 'In which set of planets is the orbital period of revolution of the first planet listed approximately one-half the orbital period of revolution of the second planet listed?',
      choices: ['Jupiter and Neptune', 'Jupiter and Uranus', 'Uranus and Saturn', 'Uranus and Neptune'],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-august-2024/q48.png',
    },
    {
      number: 49, part: 'B-1',
      context: 'A diagram represents our solar system planets in order of distance from the Sun.',
      text: 'Compared to the planets closer to the Sun, the planets beyond Mars have',
      choices: ['warmer surface temperatures', 'greater densities', 'shorter periods of rotation', 'layers of rocky composition'],
      topic: 'Astronomy',
      correct: 2,
      image: '/images/exams/es-august-2024/q49.png',
    },
    {
      number: 50, part: 'B-1',
      context: 'A diagram represents our solar system planets in order of distance from the Sun.',
      text: 'The solar system formed from',
      choices: ['precipitation over millions of years', 'the outgassing from volcanic eruptions', 'compaction and cementation of materials', 'contraction of a giant cloud of gas and debris'],
      topic: 'Meteorology',
      correct: 3,
      image: '/images/exams/es-august-2024/q50.png',
    },
  ],
}
