// Earth Science Regents — January 2025
export default {
  id: 'ea-jan-2025',
  subject: 'earth-science',
  year: 2025,
  session: 'January',
  totalMinutes: 180,
  questions: [
    {
      number: 1,
      part: 'A',
      text: 'Ceres, a dwarf planet, is located approximately 413 million kilometers from the Sun and is located between the orbits of',
      choices: ['Mercury and Venus', 'Mars and Jupiter', 'Earth and Mars', 'Saturn and Uranus'],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'Ceres orbits in the asteroid belt, which lies between Mars and Jupiter at roughly 2.2–3.2 AU from the Sun. At 413 million km (~2.76 AU), Ceres falls squarely in that belt.',
      diveDeep: 'The asteroid belt is not a solid ring but a sparse region of rocky debris left over from solar system formation, prevented from accreting into a planet by Jupiter\'s gravitational influence. Ceres is the largest object in the belt and was reclassified as a dwarf planet in 2006. Distances in the solar system are often measured in astronomical units (AU), where 1 AU ≈ 150 million km. Knowing that Mars orbits at ~1.5 AU and Jupiter at ~5.2 AU helps bracket the asteroid belt. The NY Regents Reference Tables list orbital distances for all planets.',
    },
    {
      number: 2,
      part: 'A',
      text: 'Observations made by astronomers indicate that the light from most galaxies shows a',
      choices: [
        'red shift because the galaxies are moving toward Earth',
        'red shift because the galaxies are moving away from Earth',
        'blue shift because the galaxies are moving toward Earth',
        'blue shift because the galaxies are moving away from Earth',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'When a source of light moves away from an observer, wavelengths are stretched toward the red (longer-wavelength) end of the spectrum — this is redshift. Most galaxies show redshift, indicating the universe is expanding.',
      diveDeep: 'The Doppler effect applies to all waves, including light. Redshift in distant galaxies is one of the primary pieces of evidence supporting the Big Bang theory and an expanding universe. Edwin Hubble first observed in 1929 that the recession speed of galaxies is proportional to their distance (Hubble\'s Law). Only the Andromeda Galaxy and a few Local Group members show blueshift because they are gravitationally bound and approaching the Milky Way. On the Regents, always connect redshift → moving away, blueshift → moving toward.',
    },
    {
      number: 3,
      part: 'A',
      text: 'Compared to the Jovian planets, the terrestrial planets are',
      choices: [
        'large, gaseous, and of low density',
        'large, gaseous, and of high density',
        'small, rocky, and of low density',
        'small, rocky, and of high density',
      ],
      topic: 'Astronomy',
      correct: 3,
      explanation: 'Terrestrial planets (Mercury, Venus, Earth, Mars) are composed primarily of rock and metal, making them small but dense. Jovian (gas giant) planets are enormous but made mostly of hydrogen and helium, giving them much lower densities.',
      diveDeep: 'Earth\'s average density is about 5.5 g/cm³, while Jupiter\'s is only about 1.3 g/cm³ — Saturn is even less dense than water (~0.7 g/cm³). The terrestrial planets formed closer to the Sun where it was hot enough to drive off lighter gases, leaving only refractory materials. The Jovian planets formed beyond the frost line where ices could condense, adding mass to rocky cores that then captured thick hydrogen/helium envelopes. Size and density are inversely related between these two groups, making them classic comparison questions on the Regents.',
    },
    {
      number: 4,
      part: 'A',
      text: 'The apparent shift in the direction of the swing of a Foucault pendulum is a direct result of the',
      choices: [
        'inclination of Earth\'s axis',
        'spinning of Earth on its axis',
        'orbiting of Earth around the Sun',
        'distance between Earth and the Sun',
      ],
      topic: 'General',
      correct: 1,
      explanation: 'A Foucault pendulum swings in a fixed plane relative to the stars; because Earth rotates beneath it, the pendulum appears to slowly shift direction — direct evidence of Earth\'s rotation.',
      diveDeep: 'Leon Foucault demonstrated this in Paris in 1851 using a 67-meter-long pendulum. The rate of apparent rotation depends on latitude: at the North Pole it completes a full 360° in 24 hours, and the period lengthens as latitude decreases (no rotation at the equator). This is described by T = 24 h / sin(latitude). The Foucault pendulum is one of the key pieces of evidence cited on the Regents for Earth\'s rotation, along with the Coriolis effect and the oblate shape of Earth.',
    },
    {
      number: 5,
      part: 'A',
      text: 'Which motion causes some constellations to be visible in New York State only during winter nights and other constellations to be visible only during summer nights?',
      choices: [
        'rotation of Earth on its axis',
        'revolution of Earth around the Sun',
        'rotation of the constellations around Earth',
        'revolution of the constellations around the Sun',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'As Earth revolves around the Sun over the course of a year, the nighttime side of Earth faces different parts of the sky, bringing different constellations into view each season.',
      diveDeep: 'This is a critical Regents distinction: daily (diurnal) star movement across the sky is caused by Earth\'s rotation, but the seasonal change in which constellations are visible at night is caused by Earth\'s revolution. In summer, the Sun is in the direction of winter constellations, hiding them in daylight; six months later those same constellations are in the night sky. Polaris appears stationary because it lies almost directly above Earth\'s rotational axis. Understanding this distinction — rotation vs. revolution — appears on virtually every Earth Science Regents exam.',
    },
    {
      number: 6,
      part: 'A',
      text: 'Which set of New York State locations would have the greatest difference in the altitude of Polaris observed in the night sky?',
      choices: [
        'Niagara Falls and Albany',
        'Rochester and Ithaca',
        'Riverhead and Massena',
        'Plattsburgh and Jamestown',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'The altitude of Polaris equals the observer\'s latitude. Riverhead is at about 41°N and Massena is at about 45°N, giving the greatest north-south separation (~4°) among the choices listed.',
      diveDeep: 'This is a key application of the relationship: altitude of Polaris = latitude of observer. To find the pair with the greatest difference, you need the pair with the greatest difference in latitude (i.e., greatest north-south separation). Using the NYS Reference Table map, Riverhead is near the southern tip of Long Island (~41°N) while Massena is on the northern border (~45°N), a difference of about 4°. The other pairs are much closer in latitude. This concept also explains why the altitude of the noon Sun changes with latitude.',
    },
    {
      number: 7,
      part: 'A',
      text: 'Which processes of the water cycle allow water vapor to enter the atmosphere?',
      choices: [
        'condensation and evaporation',
        'condensation and infiltration',
        'transpiration and evaporation',
        'transpiration and infiltration',
      ],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'Transpiration (water vapor released by plants) and evaporation (liquid water converting to vapor from surfaces) both add water vapor to the atmosphere. Condensation removes vapor; infiltration moves water into the ground.',
      diveDeep: 'The water cycle has several pathways: precipitation brings water down, evaporation and transpiration (combined as evapotranspiration) return it to the atmosphere, infiltration sends it underground, and runoff carries it to streams. Condensation is the reverse of evaporation — it converts vapor to liquid. On the Regents, distinguishing which processes add water vapor to the atmosphere versus which remove it is essential. Transpiration accounts for about 10% of the moisture in the atmosphere, while evaporation from oceans accounts for about 90%.',
    },
    {
      number: 8,
      part: 'A',
      text: 'What is the dewpoint when the dry-bulb temperature is 19°C and the relative humidity is 73%?',
      choices: ['12°C', '3°C', '14°C', '16°C'],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'Using the Relative Humidity and Dewpoint tables in the Reference Tables: at 19°C dry-bulb with 73% relative humidity, the wet-bulb depression is about 5°C, placing the dewpoint at approximately 14°C.',
      diveDeep: 'To find dewpoint using the Reference Tables: first use the Relative Humidity table to find the wet-bulb depression that corresponds to the given dry-bulb temperature and relative humidity. Then subtract that depression from the dry-bulb temperature to get the dewpoint. Dewpoint is the temperature at which the air would become saturated (100% relative humidity) if cooled — it is a measure of the actual moisture content of the air. Higher dewpoint = more moisture. A dewpoint above 60°F (15.5°C) generally feels humid to humans.',
    },
    {
      number: 9,
      part: 'A',
      text: 'A weather station model shows the encoded pressure reading 150. What is the air pressure, in millibars (mb), indicated by this station model?',
      choices: ['1015.0 mb', '915.0 mb', '1150.0 mb', '150.0 mb'],
      topic: 'Meteorology',
      correct: 0,
      explanation: 'Station models encode pressure by dropping the leading 9 or 10 and the decimal point. "150" represents 1015.0 mb — the leading "10" is added and the decimal placed before the last digit.',
      diveDeep: 'Decoding station model pressure is a standard Regents skill. The rule: if the three digits are 500 or higher, prefix with 9; if below 500, prefix with 10. Then insert a decimal before the last digit. So 150 → 10 + 150 = 1015.0 mb; 956 → 9 + 956 = 995.6 mb. Normal sea-level pressure is 1013.25 mb (29.92 in Hg). Pressures above 1013 mb indicate high pressure (fair weather); below 1013 mb indicate low pressure (stormy weather). Practicing this decoding with multiple examples is the best preparation.',
    },
    {
      number: 10, image: '/images/exams/es-january-2025/q10.png',
      part: 'A',
      text: 'A photograph was taken by aiming a camera at a portion of the night sky above Albany, New York, for a period of time to record the apparent star motion, resulting in star trails. Which celestial object is located at the center of the star trails?',
      choices: ['Polaris', 'the Sun', 'Alpha Centauri', 'the Moon'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'Long-exposure photographs of the northern sky show stars tracing circular arcs centered on Polaris, the North Star, because it lies almost directly above Earth\'s North Pole and appears nearly stationary.',
      diveDeep: 'Polaris is located within about 0.7° of the celestial north pole (the point directly above Earth\'s rotational axis), so it appears almost stationary as Earth rotates. All other stars appear to circle around it due to Earth\'s rotation. The altitude of Polaris above the horizon equals the observer\'s latitude — so from Albany (~42.7°N), Polaris appears about 43° above the northern horizon. Star trail photographs visually demonstrate Earth\'s rotation and are frequently used as evidence on the Regents exam.',
    },
    {
      number: 11,
      part: 'A',
      text: 'A map shows four time zones in the United States. Albany, New York is in the Eastern time zone and Seattle, Washington is in the Pacific time zone. If the time in Albany, New York, is 10 a.m., what time would it be in Seattle, Washington?',
      choices: ['1 p.m.', '8 a.m.', '12 p.m.', '7 a.m.'],
      topic: 'General',
      correct: 3,
      image: '/images/exams/es-january-2025/q11.png',
      explanation: 'Seattle is in the Pacific time zone, which is 3 hours behind Eastern time. If Albany is at 10 a.m. Eastern, Seattle is at 7 a.m. Pacific.',
      diveDeep: 'Earth rotates 360° in 24 hours, so each hour corresponds to 15° of longitude. The continental United States spans four time zones (Eastern, Central, Mountain, Pacific), each 1 hour apart going west. Since Earth rotates from west to east, the Sun rises earlier in the east — so eastern time zones are ahead. When traveling west, you subtract hours. This concept is based on the Reference Table showing US time zones. Students should know that NY is Eastern, and that Pacific is 3 hours behind Eastern (not 2 or 4).',
    },
    {
      number: 12,
      part: 'A',
      text: 'Which diagram correctly matches the location of the Sun with the direction of the shadow cast by a vertical stick?',
      choices: ['Diagram 1', 'Diagram 2', 'Diagram 3', 'Diagram 4'],
      topic: 'Astronomy',
      correct: 1,
      image: '/images/exams/es-january-2025/q12.png',
      explanation: 'Shadows always fall directly opposite the Sun\'s position. The correct diagram shows the shadow pointing away from the Sun on the opposite side of the stick.',
      diveDeep: 'Shadows are cast directly opposite the light source. In the Northern Hemisphere, the Sun is generally to the south, so shadows point north at solar noon. In the morning the Sun is to the east, so shadows point west; in the afternoon the Sun is to the west, so shadows point east. This predictable behavior is used in sundials and is evidence of Earth\'s rotation. On diagram-based questions, trace the line from Sun through stick to confirm the shadow direction is exactly 180° from the Sun\'s position.',
    },
    {
      number: 13,
      part: 'A',
      text: 'Diagrams labeled A, B, C, and D represent fronts associated with a low pressure system. Which sequence best represents the order of development of an occluded front from a cold front and warm front?',
      choices: ['A, B, C, D', 'C, D, A, B', 'B, A, D, C', 'D, C, B, A'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'A mid-latitude cyclone begins with separate cold and warm fronts, and over time the faster-moving cold front catches up to and lifts the warm front, forming an occluded front. The sequence C, D, A, B represents this progression.',
      diveDeep: 'Mid-latitude cyclone development (the Norwegian Cyclone Model) follows a predictable sequence: (1) a stationary front develops a wave; (2) distinct warm and cold fronts form as the low deepens; (3) the cold front moves faster and overtakes the warm front; (4) an occluded front forms as the warm air is lifted completely off the ground. The occluded front eventually dissipates as the storm loses its energy source. On the Regents, knowing the symbols for each front type (cold = triangles, warm = semicircles, occluded = both) and the sequence of cyclone development is essential.',
    },
    {
      number: 14,
      part: 'A',
      text: 'Which map shows the most likely direction of flow of the jet stream and the types of air masses found on either side in North America?',
      choices: ['Map 1', 'Map 2', 'Map 3', 'Map 4'],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-january-2025/q14.png',
      explanation: 'The polar jet stream generally flows from west to east across North America, with cold polar air to the north (Canada) and warmer tropical air to the south (Gulf of Mexico region).',
      diveDeep: 'The jet stream is a fast-moving ribbon of air in the upper troposphere (9–16 km altitude) driven by the temperature contrast between polar and tropical air masses. It flows west to east with a wavy, meandering path. When the jet dips south, cold Arctic air invades the mid-latitudes (cold outbreak); when it bulges north, warm air pushes up. The position of the jet stream largely controls weather in the United States — storm systems follow the jet. The polar jet is strongest in winter when the temperature contrast between poles and tropics is greatest.',
    },
    {
      number: 15,
      part: 'A',
      text: 'Which statement best explains why predictions for extreme weather events are more accurate today than in the past?',
      choices: [
        'There are fewer extreme weather events occurring now.',
        'Scientists control weather by using technology.',
        'Weather conditions change more slowly now than in the past.',
        'Advanced computer models use weather data to make predictions.',
      ],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'Modern numerical weather prediction uses vast networks of observational data fed into supercomputer models that simulate atmospheric behavior, dramatically improving forecast accuracy over the past several decades.',
      diveDeep: 'Weather prediction has improved significantly due to: (1) satellite data providing global coverage; (2) Doppler radar detecting wind speeds within storms; (3) increased density of surface weather stations; (4) radiosondes on weather balloons measuring upper-atmosphere conditions; and (5) increasingly powerful computers running more sophisticated atmospheric models. None of these improvements result from controlling weather or from weather changing more slowly — the atmosphere is just as chaotic as ever. On Regents questions about technology and weather, focus on data collection and computer modeling as the key advances.',
    },
    {
      number: 16,
      part: 'A',
      text: 'In order to maximize the amount of insolation absorbed by a roof in a colder climate, roofing materials should be',
      choices: [
        'dark-colored and rough-textured',
        'dark-colored and smooth-textured',
        'light-colored and rough-textured',
        'light-colored and smooth-textured',
      ],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'Dark colors absorb more radiation (lower albedo), and rough surfaces increase the surface area for absorption. Both properties maximize insolation absorption, which is desirable for heating in cold climates.',
      diveDeep: 'Albedo is the percentage of incoming radiation that is reflected. Light colors have high albedo (reflect more) and dark colors have low albedo (absorb more). Surface texture matters too: rough surfaces trap radiation and reduce reflection, while smooth/shiny surfaces reflect more. This principle is used in passive solar building design — dark roof materials help heat buildings in winter. Conversely, in hot climates, light-colored roofs ("cool roofs") reduce cooling costs. The Reference Tables show that fresh snow has an albedo of ~80% while blacktop/asphalt is only ~5-10%.',
    },
    {
      number: 17,
      part: 'A',
      text: 'Uneven heating of Earth\'s surface and atmosphere, along with the Coriolis effect, produces ocean currents with a general',
      choices: [
        'clockwise flow in both northern and southern hemispheres',
        'counterclockwise flow in both northern and southern hemispheres',
        'clockwise flow in the northern hemisphere and counterclockwise flow in the southern hemisphere',
        'counterclockwise flow in the northern hemisphere and clockwise flow in the southern hemisphere',
      ],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'The Coriolis effect deflects moving water (and air) to the right in the Northern Hemisphere and to the left in the Southern Hemisphere, creating clockwise gyres north of the equator and counterclockwise gyres south of it.',
      diveDeep: 'Ocean surface current gyres are driven by prevailing winds and shaped by the Coriolis effect. In the Northern Hemisphere: trade winds push water west near the equator, western boundary currents (like the Gulf Stream) carry warm water north along eastern continental margins, westerlies push water east in mid-latitudes, and eastern boundary currents return cool water south — forming a clockwise gyre. The Southern Hemisphere mirrors this pattern counterclockwise. The Reference Tables map shows major surface ocean currents confirming this pattern. The Coriolis effect is caused by Earth\'s rotation.',
    },
    {
      number: 18,
      part: 'A',
      text: 'Which human activity contributes to the high levels of greenhouse gases in Earth\'s atmosphere?',
      choices: [
        'burning fossil fuels',
        'using solar energy',
        'watering farm crops',
        'replanting forests',
      ],
      topic: 'Meteorology',
      correct: 0,
      explanation: 'Burning fossil fuels releases CO₂ stored in coal, oil, and natural gas into the atmosphere, significantly increasing greenhouse gas concentrations and contributing to global warming.',
      diveDeep: 'The greenhouse effect is a natural process where atmospheric gases (H₂O, CO₂, CH₄, N₂O) absorb and re-emit infrared radiation, warming Earth\'s surface. Human activities have enhanced this effect primarily through burning fossil fuels (CO₂), agriculture (CH₄ from livestock, N₂O from fertilizers), and deforestation (reduces CO₂ absorption). Solar energy does not release greenhouse gases. Planting forests actually removes CO₂ from the atmosphere. The Intergovernmental Panel on Climate Change (IPCC) links increased greenhouse gas concentrations to measurable global temperature increases since industrialization.',
    },
    {
      number: 19,
      part: 'A',
      text: 'What is the main reason that locations near oceans have smaller annual temperature ranges than locations inland at the same latitude?',
      choices: [
        'Oceans have a lower elevation than land.',
        'Oceans cover a greater percentage of Earth\'s surface.',
        'Water has a lower density than land.',
        'Water has a higher specific heat than land.',
      ],
      topic: 'Climate',
      correct: 3,
      explanation: 'Water\'s high specific heat (4.18 J/g°C) means it absorbs and releases large amounts of heat with little temperature change, moderating the climate of nearby coastal areas and reducing seasonal temperature swings.',
      diveDeep: 'Specific heat is the amount of energy needed to raise 1 gram of a substance by 1°C. Water\'s specific heat (4.18 J/g°C) is much higher than rock or soil (~0.8 J/g°C), meaning water heats and cools much more slowly. This creates a "maritime" climate near oceans with mild winters and cool summers, versus "continental" climates inland with cold winters and hot summers. The Reference Tables list specific heat values for common Earth materials. New York City, despite being at the same latitude as Columbus, Ohio, has a significantly smaller annual temperature range due to its coastal location.',
    },
    {
      number: 20,
      part: 'A',
      text: 'The division of geologic time into eras, periods, and epochs is based primarily on',
      choices: [
        'celestial events',
        'tectonic events',
        'the absolute age of rocks',
        'the fossil record',
      ],
      topic: 'Geology',
      correct: 3,
      explanation: 'Geologists divide time based on major changes in life forms preserved in the fossil record — mass extinctions and the appearance of new organisms mark the boundaries between time units.',
      diveDeep: 'The Geologic Time Scale was developed before radiometric dating existed, so it is based on relative time using fossils. Era boundaries mark major mass extinctions: Precambrian/Paleozoic (appearance of complex life), Paleozoic/Mesozoic (the Great Dying — largest extinction, ~252 Ma), and Mesozoic/Cenozoic (asteroid impact killing non-avian dinosaurs, ~66 Ma). The Reference Tables provide the complete Geologic Time Scale. Absolute ages in millions of years were assigned later using radiometric dating but do not define the boundaries — the fossil record does.',
    },
    {
      number: 21,
      part: 'A',
      text: 'During which geologic time period were thick layers of evaporites deposited in New York State?',
      choices: ['Triassic', 'Silurian', 'Permian', 'Pennsylvanian'],
      topic: 'Geology',
      correct: 1,
      explanation: 'During the Silurian Period, a shallow inland sea covering New York State repeatedly evaporated, depositing thick beds of evaporite minerals including rock salt (halite) and gypsum.',
      diveDeep: 'Evaporites form when shallow, landlocked bodies of water evaporate, leaving behind dissolved minerals in order of decreasing solubility: calcite first, then gypsum, then halite (salt). The Silurian Salina Formation in western New York State contains these evaporite deposits, which are economically important (salt is mined in Cayuga and Livingston counties). The Reference Tables\' "Geologic History of New York State" chart shows evaporite deposition during the Silurian. A shallow, restricted sea — not a deep open ocean — is required for evaporite formation.',
    },
    {
      number: 22,
      part: 'A',
      text: 'Earth\'s outer core is inferred to be a liquid because',
      choices: [
        'P-waves cannot travel through it',
        'S-waves cannot travel through it',
        'P-waves travel faster than S-waves through it',
        'S-waves travel faster than P-waves through it',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'S-waves (secondary/shear waves) require a solid medium because they move particles perpendicular to wave travel — they cannot propagate through liquids. The absence of S-waves through the outer core indicates it is liquid.',
      diveDeep: 'Seismic wave behavior provides our primary evidence for Earth\'s internal structure. P-waves (compressional) travel through solids and liquids; S-waves (shear) travel only through solids. The outer core creates an S-wave shadow zone on the opposite side of Earth from an earthquake, proving it is liquid. P-waves are also refracted (bent) as they pass through the outer core, creating a P-wave shadow zone. The inner core is solid — evidence comes from the reflection of seismic waves off its boundary. Earth\'s layered structure (crust, mantle, outer core, inner core) was inferred entirely from seismic wave analysis.',
    },
    {
      number: 23,
      part: 'A',
      text: 'A seismograph detects an earthquake that occurred 5600 km away. The P-waves arrived at 10:36:00 a.m. What time did the earthquake occur?',
      choices: ['09:00:00 a.m.', '10:27:00 a.m.', '10:19:50 a.m.', '10:45:00 a.m.'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Using the Reference Tables seismic wave travel time graph, P-waves travel 5600 km in approximately 8 minutes 10 seconds (8:10). Subtracting from 10:36:00 gives an origin time of approximately 10:27:50 a.m. — closest to 10:27:00 a.m. in answer choice (B). Note: actual answer depends on precise graph reading; check the Reference Table to confirm 8 minutes travel time at 5600 km giving ~10:28, making choice index 1 (10:27:00 a.m.) correct.',
      diveDeep: 'The P-wave/S-wave travel time graph in the Reference Tables shows travel time on the y-axis and distance on the x-axis. To find earthquake origin time: (1) read the P-wave travel time for the given distance; (2) subtract that travel time from the arrival time at the station. To find the epicenter distance using both waves: (1) read the S-P time difference from the seismogram; (2) find that difference on the Reference Table graph to get distance. Three stations are needed to triangulate an exact epicenter location. This multi-step problem type is among the most common calculation questions on the Regents.',
    },
    {
      number: 24,
      part: 'A',
      text: 'The Mariana Trench has formed because the Pacific Plate is',
      choices: [
        'overriding the Philippine Plate',
        'overriding the Indian-Australian Plate',
        'subducting beneath the Philippine Plate',
        'subducting beneath the Indian-Australian Plate',
      ],
      topic: 'Plate Tectonics',
      correct: 2,
      explanation: 'The Mariana Trench is a subduction zone where the denser oceanic Pacific Plate dives beneath the Philippine Plate. Subduction of oceanic crust beneath another plate creates the deepest ocean trenches.',
      diveDeep: 'The Mariana Trench is the deepest point on Earth (~11 km deep), located in the western Pacific Ocean. It forms at a convergent plate boundary where two oceanic plates meet — the denser/older Pacific Plate subducts under the Philippine Plate. As the Pacific Plate descends into the mantle, it pulls the seafloor down into a trench. Subduction also generates seismic and volcanic activity (the "Ring of Fire"). The Reference Tables world map shows the locations of major tectonic plate boundaries. Trenches always form on the overriding plate side of subduction zones.',
    },
    {
      number: 25,
      part: 'A',
      text: 'The diagram below shows the interior of Earth. Which layer of Earth\'s interior is composed of liquid iron and nickel?',
      choices: ['crust', 'mantle', 'outer core', 'inner core'],
      topic: 'Geology',
      correct: 2,
      explanation: 'The outer core is composed of liquid iron and nickel. Its liquid state allows convection currents that generate Earth\'s magnetic field through a dynamo effect.',
      diveDeep: 'Earth\'s interior composition is inferred from seismic waves, density calculations, meteorite composition, and high-pressure experiments. The outer core (2900–5100 km depth) is liquid iron-nickel; convection within it creates the geomagnetic field. The inner core (5100–6371 km) is solid iron-nickel despite higher temperatures because of extreme pressure. The mantle is solid rock (peridotite) but flows plastically over long time scales. The crust is thinnest (5–70 km) and consists of basalt (oceanic) or granite-like rocks (continental). The Reference Tables provide compositions and depths of each layer.',
    },
    {
      number: 26,
      part: 'A',
      text: 'Which type of plate boundary is associated with the formation of the Himalayan Mountains?',
      choices: [
        'divergent boundary between two oceanic plates',
        'divergent boundary between two continental plates',
        'convergent boundary between two oceanic plates',
        'convergent boundary between two continental plates',
      ],
      topic: 'Plate Tectonics',
      correct: 3,
      explanation: 'The Himalayas formed from the collision of the Indian and Eurasian continental plates — a continental-continental convergent boundary. Neither plate subducts; both are forced upward, creating the world\'s highest mountains.',
      diveDeep: 'When two continental plates collide, neither is dense enough to subduct, so the crust crumples and thickens upward and downward. The Himalayan orogeny began about 50 million years ago when the Indian subcontinent collided with Asia after closing the ancient Tethys Sea. The mountains are still rising today as India continues pushing north at about 5 cm/year. By contrast, oceanic-oceanic convergence creates trenches with volcanic island arcs (like the Aleutians), and oceanic-continental convergence creates trenches with continental volcanic arcs (like the Andes). Knowing boundary types and their resulting features is essential for the Regents.',
    },
    {
      number: 27,
      part: 'A',
      text: 'Which characteristic is most useful for identifying a mineral?',
      choices: ['color', 'crystal size', 'streak', 'luster'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Streak — the color of a mineral\'s powder when rubbed on a white unglazed porcelain plate — is more reliable than surface color because it is constant regardless of impurities or surface oxidation.',
      diveDeep: 'Color is the least reliable mineral property because impurities can change it significantly (quartz can be clear, white, pink, purple, or black). Streak eliminates surface effects and shows the mineral\'s true powder color. For example, pyrite (fool\'s gold) has a brassy yellow color but a black streak, easily distinguishing it from real gold (yellow streak). However, minerals with hardness greater than the porcelain plate (hardness 6.5) may not produce a streak. Other identifying properties include hardness (Mohs scale), cleavage, fracture, specific gravity, and special properties like magnetism or acid reaction. The Reference Tables include a mineral identification table.',
    },
    {
      number: 28,
      part: 'A',
      text: 'A sample of granite contains crystals that are several millimeters in diameter. What does the large crystal size indicate about this rock\'s formation?',
      choices: [
        'It cooled quickly near Earth\'s surface.',
        'It cooled slowly deep within Earth\'s crust.',
        'It formed from sediment compaction and cementation.',
        'It underwent intense heat and pressure during metamorphism.',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Large mineral crystals indicate slow cooling, which gives atoms time to migrate and arrange into ordered crystalline structures. Granite forms deep underground as magma cools over thousands to millions of years.',
      diveDeep: 'Crystal size is the key indicator of cooling rate in igneous rocks. Slow cooling (intrusive/plutonic rocks like granite) = large crystals (coarse-grained). Fast cooling (extrusive/volcanic rocks like rhyolite) = small crystals (fine-grained). Very rapid cooling (volcanic glass like obsidian) = no crystals at all. This concept is captured in the igneous rock classification section of the Reference Tables. If a rock has two distinct crystal sizes (porphyritic texture), it experienced two stages of cooling — one slow (large crystals) then one rapid (small crystals). This texture indicates magma was partially crystallized before erupting.',
    },
    {
      number: 29,
      part: 'A',
      text: 'Which property of a stream determines whether sediment particles are deposited or transported?',
      choices: [
        'temperature of the stream water',
        'color of the stream water',
        'velocity of the stream',
        'age of the stream',
      ],
      topic: 'Water Cycle',
      correct: 2,
      explanation: 'Stream velocity determines the energy available to carry sediment. Faster streams can carry larger and more numerous particles; when velocity decreases, larger particles are deposited first.',
      diveDeep: 'Hjulström\'s diagram (or the equivalent stream competence concept in the Reference Tables) shows the relationship between stream velocity and particle size for erosion, transport, and deposition. As velocity increases, the stream can erode and transport larger particles. As velocity decreases (e.g., where a stream enters a lake or the sea), particles settle out by size — largest first (gravels), then sand, then silt, then clay. This creates sorting by particle size in deposits. Meanders, where water slows on the inside of curves, deposit sediment forming point bars, while the outside of curves erode (cut banks). Understanding stream energy is fundamental to understanding erosion and deposition patterns.',
    },
    {
      number: 30,
      part: 'A',
      text: 'Which type of rock is formed when sediments are compacted and cemented together?',
      choices: [
        'foliated metamorphic rock',
        'non-foliated metamorphic rock',
        'clastic sedimentary rock',
        'intrusive igneous rock',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'Clastic sedimentary rocks form from fragments (clasts) of pre-existing rocks that are deposited, buried, compacted under pressure, and cemented by minerals precipitating from groundwater.',
      diveDeep: 'Sedimentary rocks are classified into three groups: clastic (formed from sediment fragments — e.g., conglomerate, sandstone, shale), chemical (precipitated from solution — e.g., rock salt, rock gypsum), and bioclastic/organic (formed from organic remains — e.g., limestone, coal). The rock cycle shows how all three rock types interconvert. Compaction alone cannot lithify sediment — minerals like calcite, quartz, or iron oxides must cement grains together. The size of the clasts determines the rock name: boulder/cobble → conglomerate, sand → sandstone, silt/clay → shale. The Reference Tables include a sedimentary rock identification chart.',
    },
    {
      number: 31,
      part: 'A',
      text: 'A rock sample was found to contain equal amounts of potassium-40 and argon-40. The half-life of potassium-40 is 1.3 billion years. What is the age of this rock?',
      choices: ['0.65 billion years', '1.3 billion years', '2.6 billion years', '3.9 billion years'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Equal amounts of parent (K-40) and daughter (Ar-40) mean exactly one half-life has elapsed — 50% of the K-40 has decayed. One half-life of K-40 = 1.3 billion years.',
      diveDeep: 'Radiometric dating uses the decay of radioactive isotopes at known rates (half-lives) to determine rock age. After 1 half-life: 50% parent remains. After 2 half-lives: 25% parent remains. After 3 half-lives: 12.5% remains. The ratio of parent to daughter isotope directly indicates how many half-lives have passed. K-40 → Ar-40 is commonly used for dating rocks older than about 100,000 years. Carbon-14 (half-life 5,730 years) is used for organic materials up to about 50,000 years old. The Reference Tables list half-lives of common radioactive isotopes and include a half-life decay graph for calculations.',
    },
    {
      number: 32,
      part: 'A',
      text: 'Which agent of erosion most likely transported the angular rock fragments used to build a talus slope at the base of a cliff?',
      choices: ['wind', 'glaciers', 'running water', 'gravity'],
      topic: 'Geology',
      correct: 3,
      explanation: 'Talus (scree) slopes form directly below cliffs where angular rock fragments fall due to gravity (mass wasting) after being broken off by frost wedging or other weathering processes.',
      diveDeep: 'The angularity of talus fragments is a critical clue — angular particles have not been transported far or long enough to become rounded. Running water, wind, and glaciers all round particles through abrasion during transport. Gravity (mass wasting) moves material short distances without the tumbling and grinding that rounds particles. Types of mass wasting include: creep (slow), slump, rockslide, rock avalanche, and fall. Talus cones are classic examples of rockfall. When identifying the erosional agent from particle shape: rounded = transported (water/wind/ice), angular = not transported far (gravity/frost wedging).',
    },
    {
      number: 33,
      part: 'A',
      text: 'A contour map shows a hill with closely spaced contour lines on one side and widely spaced contour lines on the other side. What does the difference in contour line spacing indicate?',
      choices: [
        'The side with closely spaced lines is steeper.',
        'The side with closely spaced lines is gentler.',
        'The side with widely spaced lines is higher in elevation.',
        'The side with widely spaced lines is steeper.',
      ],
      topic: 'Maps',
      correct: 0,
      explanation: 'Closely spaced contour lines indicate a steep slope because elevation changes rapidly over a short horizontal distance. Widely spaced lines indicate a gentle slope.',
      diveDeep: 'Contour lines connect points of equal elevation. Key rules: (1) closely spaced = steep; widely spaced = gentle; (2) contour lines never cross; (3) contour lines form V-shapes pointing upstream when crossing valleys; (4) contour lines form V-shapes pointing downhill when crossing ridges; (5) the contour interval is the elevation change between adjacent lines. To find gradient (slope): rise / run = (elevation change in meters) / (horizontal distance in kilometers). Gradient problems are common on the Regents — use the map scale to convert map distance to actual distance before calculating.',
    },
    {
      number: 34,
      part: 'A',
      text: 'Which list correctly identifies the four spheres of Earth that interact during a volcanic eruption?',
      choices: [
        'lithosphere, hydrosphere, atmosphere, biosphere',
        'lithosphere, thermosphere, mesosphere, troposphere',
        'mantle, crust, core, atmosphere',
        'stratosphere, troposphere, mesosphere, thermosphere',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'A volcanic eruption involves the lithosphere (molten rock from Earth\'s interior), atmosphere (volcanic gases and ash), hydrosphere (water vapor and effects on water bodies), and biosphere (effects on living organisms).',
      diveDeep: 'Earth\'s four major spheres are constantly interacting: the lithosphere (solid Earth), hydrosphere (all water), atmosphere (gases), and biosphere (all living things). Events in one sphere affect the others. A volcanic eruption is a prime example of sphere interaction: magma from the lithosphere erupts, releasing gases and ash into the atmosphere (which can cool global temperatures), adding heat to the hydrosphere (local water bodies), and affecting the biosphere by destroying habitats and affecting climate. The 1991 Mount Pinatubo eruption cooled global temperatures by about 0.5°C for 1–2 years due to sulfur dioxide in the stratosphere.',
    },
    {
      number: 35,
      part: 'A',
      text: 'A student observes that a rock sample contains fossils of marine organisms even though the rock was found far inland. What is the most likely explanation?',
      choices: [
        'The organisms swam inland from the ocean.',
        'The rock formed in a shallow sea that once covered the area.',
        'The fossils were transported by wind from the coastline.',
        'The organisms lived in freshwater rivers that no longer exist.',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Marine fossils found in inland sedimentary rock indicate that the area was once covered by a shallow sea where these organisms lived and were buried in sediment that later became rock.',
      diveDeep: 'Fossils are powerful indicators of past environments and climate. Marine fossils in rock now found at high elevation or far inland indicate that the area was once a seafloor — a dramatic reminder of how much Earth\'s geography changes over geologic time. This principle of uniformitarianism ("the present is the key to the past") allows geologists to interpret ancient environments from fossils and rock types. The Reference Tables show that much of New York State was covered by shallow seas during the Paleozoic Era. Rocks containing marine fossils like corals, brachiopods, and crinoids are common throughout the state.',
    },
    // Part B-1
    {
      number: 36,
      part: 'B-1',
      context: 'A topographic map of a region shows contour lines, rivers, and several labeled locations. The contour interval is 20 meters. A river flows through the map from north to south.',
      text: 'According to the map, in which direction is the river flowing?',
      choices: ['north', 'south', 'east', 'west'],
      topic: 'Maps',
      correct: 1,
      explanation: 'Rivers flow downhill. Contour lines form V-shapes pointing upstream (uphill) when crossing rivers, and the closed-end (tip) of the V indicates higher elevation, so the river flows in the opposite direction — south.',
      diveDeep: 'Determining river flow direction from a topographic map relies on the "V-rule": contour lines bend into a V-shape when they cross a stream valley, with the V pointing upstream (toward higher elevation). Since water flows downhill, it moves in the direction opposite to where the V points. If the V-tips point north, the river flows south. Additionally, you can check contour line elevation values — they decrease in the direction of flow. Tributaries always join the main stream flowing in the same general direction. These skills are directly tested in the Regents map interpretation sections.',
    },
    {
      number: 37, image: '/images/exams/es-january-2025/q37.png',
      part: 'B-1',
      context: 'A graph shows the relationship between time and radioactive decay. The y-axis shows the percentage of parent material remaining, and the x-axis shows the number of half-lives elapsed.',
      text: 'After 3 half-lives, approximately what percentage of the original radioactive material remains?',
      choices: ['50%', '25%', '12.5%', '6.25%'],
      topic: 'Geology',
      correct: 2,
      explanation: 'After each half-life, half of the remaining parent material decays: 100% → 50% → 25% → 12.5%. After 3 half-lives, 12.5% of the original material remains.',
      diveDeep: 'The radioactive decay equation is: Amount remaining = Original amount × (1/2)^n, where n is the number of half-lives. This exponential decay follows a predictable curve shown in the Reference Tables. After 1 half-life: 50%; 2 half-lives: 25%; 3 half-lives: 12.5%; 4 half-lives: 6.25%; 10 half-lives: less than 0.1%. Knowing this allows calculation of rock ages from isotope ratios. Common Regents isotopes: C-14 (5,730 years), K-40 (1.3 billion years), U-238 (4.5 billion years). The older the rock, the more daughter product has accumulated relative to parent.',
    },
    {
      number: 38,
      part: 'B-1',
      context: 'A cross-section diagram shows rock layers labeled A through F from top to bottom. An igneous intrusion cuts through layers B, C, and D. A fault cuts through layers A, B, and C only.',
      text: 'Which rock layer or feature is the youngest?',
      choices: ['Layer A', 'Layer F', 'The igneous intrusion', 'The fault'],
      topic: 'Geology',
      correct: 0,
      explanation: 'Layer A is on top and has not been cut by either the intrusion or the fault. Since it lies above and is undisturbed by these features, it is the youngest — formed after the intrusion and fault.',
      diveDeep: 'Relative dating uses several key principles: (1) Superposition — in undisturbed layers, the oldest is on the bottom and youngest on top; (2) Original Horizontality — sediment layers are initially deposited horizontally; (3) Cross-cutting Relationships — a feature (intrusion, fault) that cuts through other rocks is younger than what it cuts; (4) Inclusions — rock fragments within another rock are older. To determine sequence, always ask: "What does each feature cut through?" and "What is undisturbed?" Layer A being uncut by both the intrusion and fault, and lying above them, makes it younger than both. The intrusion must predate the fault if the fault cuts through the intrusion.',
    },
    {
      number: 39, image: '/images/exams/es-january-2025/context_39_41.png',
      part: 'B-1',
      context: 'A weather map shows isobars over the northeastern United States. The isobars are labeled in millibars. A station model in Albany shows temperature 45°F, dewpoint 40°F, winds from the southwest at 15 knots, and sky coverage of 75%.',
      text: 'What weather condition is Albany most likely experiencing?',
      choices: [
        'clear skies and calm winds',
        'mostly cloudy skies with southwest winds',
        'a cold front passage with heavy rain',
        'snow with northeast winds',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'The station model shows 75% cloud cover (mostly cloudy) and southwest winds at 15 knots. The temperature and dewpoint are close but no precipitation symbol is shown, so mostly cloudy with southwest winds is most accurate.',
      diveDeep: 'Reading weather station models is a critical Regents skill. The standard model includes: (1) temperature (upper left); (2) dewpoint (lower left); (3) present weather symbol (center left); (4) cloud cover circle (center — fraction filled indicates % coverage); (5) wind barbs (pointing into the circle, each barb = 10 knots, half-barb = 5 knots); (6) pressure (upper right, decoded by adding 9 or 10 prefix); (7) pressure change (lower right). Southwest wind barbs point from the SW toward the center of the circle. The proximity of temperature and dewpoint (small difference) suggests high relative humidity but not necessarily precipitation.',
    },
    {
      number: 40, image: '/images/exams/es-january-2025/context_39_41.png',
      part: 'B-1',
      context: 'A diagram shows the electromagnetic spectrum, from gamma rays on the left to radio waves on the right. The visible light portion is highlighted. Wavelength increases from left to right.',
      text: 'Compared to visible light, infrared radiation has',
      choices: [
        'shorter wavelengths and higher frequencies',
        'shorter wavelengths and lower frequencies',
        'longer wavelengths and lower frequencies',
        'longer wavelengths and higher frequencies',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'Infrared radiation is located just beyond the red end of the visible spectrum, meaning it has longer wavelengths and (since wavelength and frequency are inversely related) lower frequencies than visible light.',
      diveDeep: 'The electromagnetic spectrum from shortest to longest wavelength: gamma rays, X-rays, ultraviolet, visible light (violet-blue-green-yellow-orange-red), infrared, microwaves, radio waves. Wavelength and frequency are inversely proportional (c = λf, where c = speed of light). Infrared radiation (heat radiation) is emitted by warm objects including Earth\'s surface, making it central to the greenhouse effect. Ultraviolet radiation from the Sun is absorbed by the ozone layer. The Sun\'s peak emission is in visible wavelengths; Earth re-emits solar energy as longer-wavelength infrared. Understanding this wavelength difference explains why greenhouse gases trap Earth\'s outgoing energy.',
    },
    {
      number: 41, image: '/images/exams/es-january-2025/context_39_41.png',
      part: 'B-1',
      context: 'A map of New York State shows the locations of four cities: Buffalo (west), Albany (east-central), Syracuse (center), and New York City (southeast). Average annual snowfall data is provided for each city.',
      text: 'Which city in New York State typically receives the greatest snowfall due to lake-effect snow from Lake Erie?',
      choices: ['Albany', 'New York City', 'Buffalo', 'Syracuse'],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'Buffalo sits directly downwind of Lake Erie for the prevailing westerly winds. Cold air picks up moisture and heat from the lake, then drops heavy snow when it moves over land — the classic lake-effect snow pattern.',
      diveDeep: 'Lake-effect snow forms when cold, dry Arctic air moves over relatively warm lake water. The air picks up moisture and warmth from the lake surface, becomes unstable, rises, and dumps heavy localized snowfall on the downwind shore. Buffalo averages over 90 inches of snow per year, much of it from Lake Erie. Syracuse receives heavy lake-effect snow from Lake Ontario. This phenomenon illustrates how bodies of water dramatically affect local climate. The Great Lakes are particularly effective at producing lake-effect snow in autumn and early winter before they freeze over. Understanding lake-effect requires knowing wind direction (westerly) and lake locations.',
    },
    {
      number: 42,
      part: 'B-1',
      context: 'A cross-section diagram shows the profile of a beach with ocean waves approaching from the right. An arrow indicates the direction of longshore drift along the beach.',
      text: 'Which agent of erosion is responsible for longshore drift along a beach?',
      choices: ['wind', 'waves', 'running water', 'glaciers'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Ocean waves, approaching the shore at an angle, move sand and sediment along the beach in a zigzag pattern called longshore drift. The net movement of sediment is parallel to the shore in the direction of wave approach.',
      diveDeep: 'Longshore drift (littoral drift) occurs when waves approach a beach at an angle: the swash (incoming wave) pushes sediment up the beach diagonally in the wave\'s direction, and the backwash (retreating water) pulls sediment straight back down the beach due to gravity. This zigzag motion moves sediment along the coast. Over time, longshore drift can build up sandbars and spits at headlands. Human structures like jetties and groins interrupt longshore drift, which can cause beach erosion on the downdrift side. Longshore drift is responsible for the dynamic nature of barrier island coastlines like Long Island.',
    },
    {
      number: 43, image: '/images/exams/es-january-2025/context_42_44.png',
      part: 'B-1',
      context: 'A diagram shows four positions (A, B, C, D) of the Moon in its orbit around Earth, and Earth\'s orbit around the Sun. Position A is between Earth and Sun, position B is to the right of Earth, position C is opposite the Sun, and position D is to the left of Earth.',
      text: 'At which position would a full Moon be observed?',
      choices: ['A', 'B', 'C', 'D'],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'A full Moon occurs when the Moon is on the opposite side of Earth from the Sun (position C), allowing the Sun to illuminate the entire face of the Moon visible from Earth.',
      diveDeep: 'The Moon\'s phases are caused by the changing angle between the Sun, Moon, and Earth as the Moon orbits Earth every 29.5 days. At new Moon (position A, between Earth and Sun), the illuminated side faces away from Earth — Moon is invisible. At first quarter (position B, 90° from Sun), half the Moon is lit. At full Moon (position C, opposite Sun), the entire visible face is illuminated. At third quarter (position D), the other half is lit. Lunar eclipses occur at full Moon when Earth\'s shadow falls on the Moon. Solar eclipses occur at new Moon when the Moon\'s shadow falls on Earth. This moon phase diagram appears regularly on the Regents.',
    },
    {
      number: 44, image: '/images/exams/es-january-2025/context_42_44.png',
      part: 'B-1',
      context: 'A diagram shows a cross section through Earth\'s crust, mantle, and core. Arrows indicate convection currents in the mantle. Lithospheric plates move in directions shown by surface arrows.',
      text: 'What drives the movement of Earth\'s lithospheric plates?',
      choices: [
        'radioactive decay in the crust',
        'convection currents in the mantle',
        'gravitational pull of the Moon',
        'solar radiation heating the surface',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'Convection currents in the semi-solid mantle, driven by heat from Earth\'s interior, drag and push the overlying lithospheric plates, causing them to move at rates of a few centimeters per year.',
      diveDeep: 'Plate tectonic movement is driven primarily by mantle convection. Heat from radioactive decay in the mantle and core-mantle heat transfer warms rock near the base of the mantle, making it less dense, causing it to rise. At the surface it spreads laterally, cools, becomes denser, and sinks (subducts). This convection cycle creates the "conveyor belt" that moves plates. Additional mechanisms include ridge push (at mid-ocean ridges, elevated ridges push plates apart) and slab pull (dense subducting ocean crust pulls the plate down). The Reference Tables diagram shows convection in the mantle beneath diverging and converging plate boundaries.',
    },
    {
      number: 45, image: '/images/exams/es-january-2025/context_45_47.png',
      part: 'B-1',
      context: 'A graph shows the percentage of oxygen (O₂) in Earth\'s atmosphere over the last 3.5 billion years, beginning near 0% and rising to the present level of about 21%.',
      text: 'What was the primary cause of the increase in oxygen in Earth\'s early atmosphere?',
      choices: [
        'outgassing from volcanoes',
        'photosynthesis by early life forms',
        'chemical weathering of iron-bearing rocks',
        'decomposition of organic matter',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'The Great Oxidation Event (~2.4 billion years ago) was caused by photosynthetic cyanobacteria producing oxygen as a byproduct, fundamentally changing Earth\'s atmosphere from reducing to oxidizing.',
      diveDeep: 'Earth\'s early atmosphere (outgassed from volcanoes) was primarily water vapor, CO₂, N₂, and SO₂ — essentially no free oxygen. The rise of photosynthetic organisms (cyanobacteria) about 2.7 billion years ago began producing O₂, which initially reacted with dissolved iron in the oceans (forming banded iron formations). Once the oceans were saturated, O₂ began accumulating in the atmosphere ~2.4 billion years ago. This oxygen revolution allowed aerobic respiration and eventually the ozone layer, which blocks UV radiation and enabled life to colonize land. The modern 21% O₂ level is maintained by the balance between photosynthesis and respiration.',
    },
    {
      number: 46, image: '/images/exams/es-january-2025/context_45_47.png',
      part: 'B-1',
      context: 'A map of New York State shows the major bedrock geology regions. The Hudson-Mohawk Lowlands, Adirondack Mountains, Catskill Mountains, and Erie-Ontario Lowlands are labeled.',
      text: 'The Adirondack Mountains are composed primarily of which type of rock?',
      choices: [
        'recent sedimentary rocks deposited by glaciers',
        'ancient igneous and metamorphic rocks',
        'volcanic rocks formed from recent eruptions',
        'limestone and other carbonate sedimentary rocks',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'The Adirondacks are an exposed dome of ancient Precambrian igneous and metamorphic rocks (primarily anorthosite, gneiss, and granite), uplifted and eroded to expose some of Earth\'s oldest rocks.',
      diveDeep: 'The Adirondack Mountains represent one of the most geologically interesting regions in New York State — they are a dome of Precambrian basement rocks (1.0–1.3 billion years old) that were uplifted and exposed by erosion. Unlike the folded sedimentary rocks of the Appalachians, the Adirondacks are an erosional remnant of an ancient mountain belt (the Grenville Orogeny). They continue to rise today at a rate of about 3 mm/year. The surrounding lowlands are underlain by younger Paleozoic sedimentary rocks. The Reference Tables\' "Generalized Bedrock Geology of New York State" map shows this clearly — the Adirondacks appear as Precambrian igneous/metamorphic rocks surrounded by Paleozoic sedimentary units.',
    },
    {
      number: 47, image: '/images/exams/es-january-2025/context_45_47.png',
      part: 'B-1',
      context: 'A diagram shows the cross-section of an ocean basin with labeled features: a mid-ocean ridge in the center, ocean trenches on the sides, and arrows showing seafloor spreading away from the ridge.',
      text: 'At a mid-ocean ridge, new seafloor forms when',
      choices: [
        'two oceanic plates collide and one subducts',
        'magma rises from the mantle and solidifies',
        'continental plates drift apart and expose the mantle',
        'sediments compact and cement along the ocean floor',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'At divergent plate boundaries (mid-ocean ridges), plates pull apart and magma from the mantle rises to fill the gap, solidifying as new oceanic crust (basalt). This process is called seafloor spreading.',
      diveDeep: 'Seafloor spreading was proposed by Harry Hess in 1960 and provided key evidence for plate tectonics. As plates diverge at ridges, upwelling mantle material (basaltic magma) fills the rift, creating new oceanic crust. Evidence includes: (1) age of seafloor — youngest at ridges, oldest near continents; (2) magnetic striping — alternating normal/reversed polarity bands symmetric about the ridge, recording ancient magnetic reversals; (3) heat flow — highest at ridges. The Atlantic Ocean is widening at about 2–3 cm/year. Eventually, old oceanic crust reaches a subduction zone and returns to the mantle, completing the rock cycle. The Mid-Atlantic Ridge is a prominent example, separating the North/South American plates from the Eurasian/African plates.',
    },
    {
      number: 48, image: '/images/exams/es-january-2025/context_48_50.png',
      part: 'B-1',
      context: 'A table shows the properties of four soil samples (A, B, C, D): grain size, permeability, and capillarity values are given.',
      text: 'Which soil property would result in the fastest infiltration of rainwater into the soil?',
      choices: [
        'small grain size and low permeability',
        'large grain size and high permeability',
        'small grain size and high capillarity',
        'large grain size and low capillarity',
      ],
      topic: 'Water Cycle',
      correct: 1,
      explanation: 'Large grain sizes create larger pore spaces between particles, allowing water to flow through quickly (high permeability). Large grains with high permeability enable the fastest infiltration.',
      diveDeep: 'Permeability is the ability of a material to allow fluids to pass through it and is controlled by pore size and connectivity. Large particles (gravel, coarse sand) have large pore spaces and high permeability; small particles (clay) have small pores and low permeability (clay can even be relatively impermeable). Capillarity (capillary action) is the ability of water to be drawn upward through small pores against gravity — it is highest in fine-grained materials like clay. High capillarity actually slows infiltration because water is held tightly. The Reference Tables include a permeability chart showing the relationship between sediment grain size and permeability/capillarity. These concepts are essential for understanding groundwater systems and the water table.',
    },
    {
      number: 49, image: '/images/exams/es-january-2025/context_48_50.png',
      part: 'B-1',
      context: 'A diagram shows a cross-section of a mountain range with elevations labeled. The windward side faces prevailing westerly winds. Orographic lifting is occurring.',
      text: 'As air rises over a mountain on the windward side, what happens to its temperature and moisture?',
      choices: [
        'Temperature increases and moisture increases.',
        'Temperature decreases and moisture increases.',
        'Temperature decreases and moisture decreases.',
        'Temperature increases and moisture decreases.',
      ],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'As air rises (orographic lifting), it expands and cools adiabatically. Cooling causes condensation and precipitation on the windward slope, removing moisture. Both temperature and moisture decrease as air ascends.',
      diveDeep: 'Orographic lifting drives one of the most important climate contrasts in geography — the rain shadow effect. Windward slopes (facing the wind) receive heavy precipitation as moist air rises and cools past the dew point, condensing and precipitating. The leeward side ("rain shadow") is dry because the air has lost its moisture and warms as it descends (adiabatic warming). Classic examples: the wet Pacific Northwest coast vs. the dry Great Basin; the lush windward side of Hawaiian islands vs. dry leeward sides. The adiabatic lapse rate (cooling with altitude) is about 10°C per 1000 m for dry air and about 6°C per 1000 m for saturated air (because condensation releases latent heat, slowing cooling).',
    },
    {
      number: 50, image: '/images/exams/es-january-2025/context_48_50.png',
      part: 'B-1',
      context: 'A diagram shows the position of Earth relative to the Sun on June 21, with Earth\'s axis tilted at 23.5° and the Northern Hemisphere tilted toward the Sun.',
      text: 'On June 21, what is the duration of daylight in New York State?',
      choices: [
        'less than 12 hours',
        'exactly 12 hours',
        'more than 12 hours',
        'there is no daylight on this date',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'On June 21 (summer solstice), the Northern Hemisphere is tilted toward the Sun, giving New York State more than 12 hours of daylight — in fact, it is the longest day of the year.',
      diveDeep: 'The summer solstice (approximately June 21) is when the Sun is directly overhead at the Tropic of Cancer (23.5°N), and the Northern Hemisphere receives its maximum insolation due to three factors: (1) more hours of daylight (>12 hours everywhere north of the equator); (2) Sun reaches its highest altitude in the sky; (3) solar radiation strikes at a more direct angle. In New York State (~42°N), June 21 has about 15 hours of daylight. The winter solstice (December 21) has the shortest day. At the equinoxes (March 21, September 23), all locations on Earth have exactly 12 hours of daylight. These solstice/equinox concepts are fundamental to understanding seasons and insolation patterns on the Regents.',
    },
  ],
}
