// Earth Science Regents — January 2023
export default {
  id: 'ea-jan-2023',
  subject: 'earth-science',
  year: 2023,
  session: 'January',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'The apparent change in direction of swing of a Foucault pendulum, at one specific location, provides evidence that Earth',
      choices: ['travels around the Sun', 'spins on its axis', 'has a tilted axis', 'has a spherical shape'],
      topic: 'General',
      correct: 1,
      explanation: 'The Foucault pendulum\'s swing plane stays fixed in space while Earth rotates beneath it, causing the apparent change in swing direction — direct evidence of Earth\'s rotation on its axis.',
      diveDeep: 'The Foucault pendulum is the most direct mechanical evidence of Earth\'s rotation. The pendulum\'s momentum keeps it swinging in the same plane while the floor (Earth) rotates underneath. At the North Pole, the pendulum appears to complete a full 360° in 24 hours. At lower latitudes the rotation is slower. The Coriolis effect provides additional indirect evidence of rotation via curved wind and ocean current paths. Earth\'s spherical shape is inferred from ship observations and shadow during lunar eclipses. Earth\'s tilt is inferred from seasonal shadow length changes.',
    },
    {
      number: 2, part: 'A',
      text: 'The presence of cosmic background radiation is evidence that helps support the',
      choices: ['Big Bang theory', 'Plate Tectonic theory', 'process of global warming', 'process of radioactive decay'],
      topic: 'General',
      correct: 0,
      explanation: 'Cosmic microwave background (CMB) radiation — the faint, uniform glow of microwave radiation filling all of space — is the cooled remnant heat from the Big Bang, providing direct evidence for this theory.',
      diveDeep: 'The CMB was accidentally discovered in 1965 by Arno Penzias and Robert Wilson, who found an unexplained uniform microwave signal coming from all directions in the sky. This matched a prediction from Big Bang theory: the universe, initially hot and dense, cooled and expanded, leaving a uniform "afterglow." The CMB temperature is approximately 2.7 K (nearly absolute zero) — incredibly uniform in all directions. Combined with the red shift of galaxies, the CMB is the strongest evidence for the Big Bang. Neither plate tectonics, global warming, nor radioactive decay is supported by CMB.',
    },
    {
      number: 3, part: 'A',
      text: 'In New York State, the highest altitude of Polaris will be observed at',
      choices: ['Utica', 'Massena', 'Kingston', 'Old Forge'],
      topic: 'General',
      correct: 1,
      explanation: 'The altitude of Polaris equals the observer\'s latitude; Massena, NY is the northernmost city among the choices (approximately 45°N), so it will show the highest Polaris altitude.',
      diveDeep: 'Polaris altitude = observer\'s latitude. NY State cities approximate latitudes: Kingston (~42°N, near Hudson Valley), Utica (~43°N), Old Forge (~43.7°N), Massena (~45°N, near Canadian border). Massena is the northernmost, so Polaris appears highest there. This is one of the most directly testable Regents facts. Massena is in the St. Lawrence Lowlands. Always compare latitudes: higher latitude = higher Polaris altitude. Use the Reference Table city locations when needed.',
    },
    {
      number: 4, part: 'A',
      text: 'Earth\'s rate of revolution is approximately',
      choices: ['1°/day', '−3.5°/day', '15°/day', '360°/day'],
      topic: 'Astronomy',
      subTopic: 'Solar System & Earth Motions',
      correct: 0,
      explanation: 'Earth revolves (orbits) around the Sun at approximately 1° per day (360° ÷ 365 days ≈ 0.986°/day ≈ 1°/day).',
      diveDeep: 'Earth\'s two motions: (1) Rotation on its axis = 360° in 24 hours = 15°/hour = 15°/hr. (2) Revolution around the Sun = 360° in ~365 days ≈ 1°/day. The −3.5°/day is not a real Earth motion rate. 360°/day would mean Earth completes an orbit every day — that is impossibly fast. The 1°/day and 15°/hour values are the two most fundamental motion rates to memorize for the Regents. Revolution rate explains why constellations visible at midnight gradually shift eastward through the year at about 1° per day (about 1 constellation per month).',
    },
    {
      number: 5, part: 'A',
      text: 'As water vapor changes phase from gas to liquid, each gram of water vapor',
      choices: ['releases 2260 joules of heat energy', 'releases 334 joules of heat energy', 'gains 2260 joules of heat energy', 'gains 334 joules of heat energy'],
      topic: 'General',
      correct: 0,
      explanation: 'Condensation (gas → liquid) releases 2260 J/g of latent heat energy into the surrounding environment; this is the same amount of energy absorbed during vaporization.',
      diveDeep: 'Phase change latent heats from the Reference Tables: Vaporization/Condensation = 2260 J/g (largest); Melting/Freezing = 334 J/g (smaller). Heat is released during condensation and freezing (exothermic); heat is absorbed during vaporization and melting (endothermic). The large energy release during condensation is what powers severe weather — as water vapor in thunderstorm updrafts condenses, it releases enormous energy that drives storm intensification. Hurricanes are powered by this process over warm ocean water. This latent heat concept appears on virtually every Earth Science Regents exam.',
    },
    {
      number: 6, part: 'A',
      text: 'At the time of an equinox, the subtropical jet streams in Earth\'s troposphere generally are located closest to',
      choices: ['0° and 90° S', '60° N and 60° S', '30° N and 30° S', '90° N and 90° S'],
      topic: 'Meteorology',
      subTopic: 'Weather Variables',
      correct: 2,
      explanation: 'The subtropical jet streams are located at approximately 30°N and 30°S latitude year-round, in the upper troposphere near the top of the Hadley cells.',
      diveDeep: 'The two main jet streams: (1) Polar Front Jet Stream at ~60°N/S, associated with the polar front and responsible for steering mid-latitude weather systems. (2) Subtropical Jet Stream at ~30°N/S, at the boundary between the Hadley and Ferrel circulation cells. The subtropical jet is relatively stable in position (~30°) while the polar jet migrates latitudinally with the seasons (further north in summer, further south in winter over the US). At equinoxes, neither is at the poles or equator. The ~30° position for the subtropical jet is a standard Regents answer.',
    },
    {
      number: 7, part: 'A',
      text: 'When the dry-bulb temperature is 16°C and the dewpoint is 7°C, what are the wet-bulb temperature and the relative humidity?',
      choices: ['wet-bulb temperature = 9°C and relative humidity = 7%', 'wet-bulb temperature = 9°C and relative humidity = 54%', 'wet-bulb temperature = 11°C and relative humidity = 7%', 'wet-bulb temperature = 11°C and relative humidity = 54%'],
      topic: 'Meteorology',
      subTopic: 'Moisture & Humidity',
      correct: 3,
      explanation: 'With dry-bulb 16°C and dewpoint 7°C, the Reference Tables give a wet-bulb temperature of approximately 11°C and a relative humidity of approximately 54%.',
      diveDeep: 'This question requires using both the dewpoint AND the relative humidity tables in the Reference Tables. With dry-bulb 16°C and dewpoint 7°C, find the difference (16 − 7 = 9°C) or look up directly. The dewpoint table maps dry-bulb temperature and dewpoint depression to wet-bulb temperature. Then use the relative humidity table with the dry-bulb and the wet-dry difference. Alternatively, a dewpoint of 7°C with dry-bulb of 16°C gives RH = 54% (using the RH formula). A lower dewpoint relative to dry-bulb means drier air, but 54% is moderate humidity.',
    },
    {
      number: 8, part: 'A',
      text: 'Which ocean current warms the climate along a continent\'s east coast?',
      choices: ['California Current', 'Falkland Current', 'Brazil Current', 'Guinea Current'],
      topic: 'Climate',
      subTopic: 'Climate Factors',
      correct: 2,
      explanation: 'The Brazil Current is a warm current that flows southward along the east coast of South America, warming the adjacent coastal climate — warm currents flow toward higher latitudes along eastern coasts in the Southern Hemisphere.',
      diveDeep: 'Ocean current patterns: In the Northern Hemisphere, warm currents flow northward along eastern continental coasts (Gulf Stream along eastern North America, Kuroshio along eastern Asia). Cold currents flow southward along western coasts (California Current, Canary Current). In the Southern Hemisphere, the pattern is reversed: warm currents flow southward along eastern coasts (Brazil Current, Agulhas). The California Current (cold, flows south along western North America) and Falkland Current (cold, flows north along eastern South America) both cool their adjacent coasts. Guinea Current warms West Africa.',
    },
    {
      number: 9, part: 'A',
      text: 'Which process transfers heat energy through molecular collisions?',
      choices: ['radiation', 'infiltration', 'convection', 'conduction'],
      topic: 'General',
      correct: 3,
      explanation: 'Conduction transfers heat through direct molecular contact and collisions — faster-moving (hotter) molecules transfer energy to slower-moving (cooler) adjacent molecules.',
      diveDeep: 'Three heat transfer methods: (1) Conduction — molecular collisions, requires direct contact, best in solids (metals conduct well). (2) Convection — fluid circulation due to density differences (warm fluid rises, cool sinks), occurs in liquids and gases. (3) Radiation — electromagnetic wave transfer through space, requires no medium (e.g., solar energy reaching Earth through vacuum). Infiltration is a water movement process, not heat transfer. On Regents: "molecular collisions" = conduction; "density differences, rising/sinking" = convection; "electromagnetic waves" = radiation.',
    },
    {
      number: 10, part: 'A',
      text: 'Two major greenhouse gases that can be found in Earth\'s atmosphere are',
      choices: ['carbon dioxide and methane', 'methane and nitrogen', 'nitrogen and oxygen', 'oxygen and carbon dioxide'],
      topic: 'Meteorology',
      subTopic: 'Weather Variables',
      correct: 0,
      explanation: 'Carbon dioxide (CO₂) and methane (CH₄) are both potent greenhouse gases that absorb and re-emit infrared radiation, trapping heat in Earth\'s atmosphere.',
      diveDeep: 'Major greenhouse gases: Water vapor (H₂O) — most abundant greenhouse gas; CO₂ — most significant in human-caused warming; CH₄ (methane) — ~80× more potent than CO₂ over 20 years, from livestock, rice paddies, natural gas leaks; N₂O (nitrous oxide) — from agriculture. Nitrogen (N₂) and oxygen (O₂) make up ~99% of the atmosphere but are NOT greenhouse gases — they do not absorb infrared radiation because they are diatomic (symmetrical linear molecules with no dipole moment). CO₂ and methane are the two most tested greenhouse gases on the Regents.',
    },
    {
      number: 11, part: 'A',
      text: 'Which event causes a temporary slowing or reversal of the surface ocean currents in the equatorial region of the Pacific Ocean, which may disrupt normal weather patterns in North America?',
      choices: ['a volcanic eruption', 'El Niño', 'a tsunami', 'Grenville orogeny'],
      topic: 'Meteorology',
      subTopic: 'Weather Variables',
      correct: 1,
      explanation: 'El Niño is a periodic climate event where the easterly trade winds weaken or reverse, causing warm water to accumulate in the eastern equatorial Pacific and disrupting normal weather patterns globally.',
      diveDeep: 'El Niño-Southern Oscillation (ENSO): Normal conditions: strong trade winds push warm water west, cold upwelling on South American coast. El Niño: trade winds weaken → warm water spreads east → suppressed upwelling → warm, dry conditions in western Pacific; wet conditions in normally dry areas of South America. Effects on North America: milder/drier winters in NE US, wetter conditions in SE US and California. La Niña is the opposite (stronger trade winds, cooler eastern Pacific). El Niño occurs every 2–7 years and is named "the child" (Christ child) because it arrives around Christmas. Tsunamis are seismic sea waves; Grenville orogeny was a Precambrian mountain-building event.',
    },
    {
      number: 12, image: '/images/exams/es-january-2023/q12.png', part: 'A',
      text: 'The map shows the time zones of the continental United States. Portland, Oregon is in the Pacific time zone; Cleveland, Ohio is in the Eastern time zone. What time is it in Portland, Oregon, when it is 9 p.m. in Cleveland, Ohio?',
      choices: ['5 p.m.', '11 p.m.', '6 p.m.', '12 midnight'],
      topic: 'Maps',
      correct: 2,
      explanation: 'Portland, Oregon (Pacific time zone) is 3 hours behind Cleveland, Ohio (Eastern time zone); 9 p.m. Eastern − 3 hours = 6 p.m. Pacific.',
      diveDeep: 'US time zones from east to west: Eastern, Central (−1 hr), Mountain (−2 hr), Pacific (−3 hr). Cleveland = Eastern; Portland = Pacific → 3-hour difference. Moving west = earlier time. 9 p.m. − 3 hours = 6 p.m. The time zone boundaries follow approximately 75°W (Eastern), 90°W (Central), 105°W (Mountain), and 120°W (Pacific), each 15° apart representing 1 hour. Knowing that the continental US spans 4 time zones (Eastern through Pacific) is essential for these questions. When traveling west, clocks go back; traveling east, clocks go forward.',
    },
    {
      number: 13, part: 'A',
      text: 'The diagrams below represent the constellations visible above the southern horizon at midnight from the same New York State location on two different dates: Orion/Canis Minor/Monoceros/etc. in January; Aquila/Sagittarius/Scorpius/etc. in July. Why are different constellations seen on these two dates at midnight?',
      choices: ['Constellations rotate on an axis.', 'Earth rotates on its axis.', 'Constellations revolve around the Sun.', 'Earth revolves around the Sun.'],
      topic: 'Astronomy',
      subTopic: 'Solar System & Earth Motions',
      correct: 3,
      image: '/images/exams/es-january-2023/q13.png',
      explanation: 'As Earth revolves around the Sun over the course of a year, the night side of Earth faces different regions of space each month, bringing different constellations into view.',
      diveDeep: 'The seasonal change in visible constellations is caused by Earth\'s revolution (orbital motion), NOT rotation. Rotation causes the nightly rising and setting of stars (24-hour cycle). Revolution causes the yearly progression of constellations (each month the night sky shifts by about 30°, revealing new constellations at midnight). This is why Orion is a "winter constellation" for observers in New York: during winter, Earth\'s night side faces the direction of Orion. In summer, the night side faces Sagittarius and Scorpius. Constellations do not move relative to each other on human timescales.',
    },
    {
      number: 14, part: 'A',
      text: 'Letters A, B, C, and D in the diagram below represent processes in the water cycle. Which letter represents the process of transpiration?',
      choices: ['A', 'C', 'B', 'D'],
      topic: 'Water Cycle',
      subTopic: 'The Water Cycle',
      correct: 3,
      image: '/images/exams/es-january-2023/q14.png',
      explanation: 'Transpiration is the process by which plants release water vapor through their leaves; in a water cycle diagram, it is typically shown as water vapor rising from vegetation — represented by letter D.',
      diveDeep: 'Water cycle processes: Evaporation = liquid water → water vapor from water surfaces. Transpiration = water vapor released by plant leaves. Evapotranspiration = combined evaporation + transpiration. Condensation = water vapor → liquid (cloud formation). Precipitation = water falling from clouds. Infiltration = water soaking into soil. Runoff = water flowing over surface. Groundwater flow = water movement underground. Transpiration is distinguished from evaporation in that it specifically involves plant biological processes — plants open stomata to allow gas exchange (CO₂ in, O₂ and H₂O out).',
    },
    {
      number: 15, part: 'A',
      text: 'The cross section below represents a lake-effect snowstorm resulting from air moving across Lake Ontario and over Oswego, New York. These lake-effect snowstorms commonly occur around Oswego during winter because Lake Ontario',
      choices: ['cools the air so that it is no longer saturated, which then produces frozen drops of water', 'warms the air so that it is no longer saturated, which then produces frozen drops of water', 'cools the air, which rises, contracts, and warms to the dewpoint, forming clouds and snow', 'warms the air, which rises, expands, and cools to the dewpoint, forming clouds and snow'],
      topic: 'Meteorology',
      subTopic: 'Storms',
      correct: 3,
      image: '/images/exams/es-january-2023/q15.png',
      explanation: 'Cold Arctic air passes over relatively warmer Lake Ontario, picks up heat and moisture; the warmed moist air rises, expands, cools to the dewpoint, and condenses to form clouds and snow over Oswego.',
      diveDeep: 'Lake-effect snow mechanism: (1) Cold, dry Arctic air (cP or cA air mass) blows across the relatively warmer lake water (Lake Ontario doesn\'t freeze until mid-winter). (2) The lake warms and moistens the air in the lowest layers. (3) This warmed, moist air is less dense and rises. (4) Rising air expands and cools at the moist adiabatic lapse rate. (5) When air cools to the dewpoint, condensation forms clouds; below freezing = snow. (6) The snow dumps on the downwind shoreline (Oswego, Tug Hill). Key concepts: air RISES over lake (not sinks), and EXPANSION causes cooling (not contracting).',
    },
    {
      number: 16, part: 'A',
      text: 'Assuming that no overturning of rock layers has occurred, which geologic outcrop containing New York State index fossils represents the correct sequence of time within the same group of organisms?',
      choices: ['Diagram 1', 'Diagram 2', 'Diagram 3', 'Diagram 4'],
      topic: 'Geology',
      subTopic: 'Fossils & Correlation',
      correct: 0,
      image: '/images/exams/es-january-2023/q16.png',
      explanation: 'The correct sequence shows older (lower in stratigraphy) to younger (higher) fossils of the same organism group, consistent with the principle of superposition, as shown in Diagram 1.',
      diveDeep: 'This question requires combining superposition (lower = older) with knowledge of the geologic time progression of fossil groups from the Reference Table. For example, within trilobites: Elliptocephala (Cambrian, oldest) → Cryptolithus (Ordovician) → Phacops (Devonian). The correct diagram should show the earliest species at the bottom and progressively younger species above. Any diagram showing younger fossils below older ones would be incorrect (overturning would need to have occurred). The NY Reference Table lists index fossils in order by geologic period.',
    },
    {
      number: 17, part: 'A',
      text: 'Equal areas of which type of surface absorb the most insolation?',
      choices: ['dark-colored and smooth', 'dark-colored and rough', 'light-colored and smooth', 'light-colored and rough'],
      topic: 'Meteorology',
      subTopic: 'Insolation',
      correct: 1,
      explanation: 'Dark-colored surfaces have low albedo (absorb more, reflect less light), and rough surfaces have greater surface area for absorption; together they maximize insolation absorption.',
      diveDeep: 'Albedo (reflectivity) is the key variable: dark = low albedo (absorbs most incoming radiation); light = high albedo (reflects most). Rough surface = more surface area = more opportunity to absorb. The combination dark + rough maximizes absorption. Dark smooth surfaces absorb more than light ones but slightly less than dark rough ones. In climate studies: polar ice (high albedo) reflects ~80–90% of sunlight; asphalt (low albedo) absorbs ~90–95%. Melting sea ice exposes dark ocean water, which absorbs more heat — a positive feedback loop amplifying Arctic warming. Dark-rough > dark-smooth > light-rough > light-smooth in absorption.',
    },
    {
      number: 18, part: 'A',
      text: 'Which material requires the least amount of heat energy to raise its temperature one Celsius degree?',
      choices: ['liquid water', 'basalt', 'ice', 'granite'],
      topic: 'General',
      correct: 3,
      explanation: 'Granite has the lowest specific heat capacity (~0.80 J/g°C) among these options, meaning it requires the least energy to raise its temperature by 1°C.',
      diveDeep: 'Specific heat capacities from Reference Tables: liquid water = 4.18 J/g°C (highest), ice = 2.09 J/g°C, basalt = 0.84 J/g°C, granite = 0.80 J/g°C (lowest among common Earth materials). The material with the LOWEST specific heat requires the LEAST energy to change temperature by 1°C — so it heats and cools fastest. Granite heats and cools faster than basalt, both faster than ice, and all much faster than liquid water. This is why land heats up and cools down much faster than the ocean (water\'s high specific heat). Common Regents trap: "least heat to raise temperature" = lowest specific heat = granite.',
    },
    {
      number: 19, part: 'A',
      text: 'One characteristic of a good index fossil is that the organisms that produced these fossils',
      choices: ['left remains that can be found in igneous, sedimentary, and metamorphic rocks', 'lived over a wide geographic area', 'existed on Earth for a long period of geologic time', 'lived both on land and in the water during part of their lives'],
      topic: 'Geologic Time',
      correct: 1,
      explanation: 'A good index fossil must have lived over a wide geographic area so it can be used to correlate rock layers across distant locations; it must also have existed for a short, specific time period.',
      diveDeep: 'Characteristics of good index fossils: (1) Existed for a SHORT time period (so it pinpoints a specific narrow time range); (2) Lived over a WIDE geographic area (so it can be found in many distant locations and used for correlation); (3) Abundant and easy to identify. Common mistake: choosing "long period of time" — an organism existing for a long time can\'t help determine a specific age. Fossils are typically found only in sedimentary rocks (not igneous or metamorphic). Examples from NY Reference Table: trilobites (Cambrian-Devonian), eurypterids (Silurian), graptolites (Ordovician).',
    },
    {
      number: 20, part: 'A',
      text: 'During which geologic epoch was nearly all of Earth\'s landmass inferred to have been located in the Southern Hemisphere?',
      choices: ['Early Cretaceous', 'Middle Triassic', 'Early Mississippian', 'Middle Ordovician'],
      topic: 'Geology',
      subTopic: 'Relative Dating',
      correct: 3,
      explanation: 'During the Middle Ordovician (~465 Ma), most of Earth\'s landmass (the supercontinent Gondwana) was located in the Southern Hemisphere near the South Pole.',
      diveDeep: 'Continental positions through time from the NY Reference Table: Middle Ordovician (~465 Ma) — Gondwana (containing South America, Africa, Antarctica, Australia, India) was centered over the South Pole; North America (Laurentia) was near the equator. Pangaea formed during the Permian and Triassic (~300–200 Ma). Pangaea breakup began in the Triassic-Jurassic. By the Cretaceous, continents were separating but still not in their modern positions. The Ordovician glacial evidence (tillite deposits in northern Africa) supports Africa being near the South Pole during this period.',
    },
    {
      number: 21, part: 'A',
      text: 'The Alleghenian orogeny occurred as a result of the',
      choices: ['intrusion of the Palisades sill', 'breakup of Pangaea, which formed the Atlantic Ocean', 'collision of the North American Plate with the African Plate', 'metamorphism of the bedrock in the Adirondack Mountains'],
      topic: 'Geology',
      subTopic: 'Plate Boundaries',
      correct: 2,
      explanation: 'The Alleghenian Orogeny (approximately 300 Ma, Late Paleozoic) was caused by the collision of the African Plate with North America as the supercontinent Pangaea assembled.',
      diveDeep: 'NY State orogenies from the Reference Table: Grenville Orogeny (~1.0 Ga) — collision forming Adirondack Precambrian basement. Taconic Orogeny (~450 Ma, Ordovician) — island arc collision forming early Taconic Mountains. Acadian Orogeny (~375 Ma, Devonian) — collision of Euramerica with Gondwana, forming Catskill Delta. Alleghenian Orogeny (~300 Ma, Pennsylvanian) — Africa-North America collision, completing Pangaea assembly. The Palisades Sill intruded AFTER Pangaea breakup (~200 Ma). Adirondack metamorphism was during the Grenville. Pangaea breakup followed the Alleghenian, not caused it.',
    },
    {
      number: 22, part: 'A',
      text: 'Which concept states that most sediments are deposited in layers that are flat and parallel to Earth\'s surface?',
      choices: ['principle of superposition', 'cross-cutting relationship', 'dynamic equilibrium', 'original horizontality'],
      topic: 'Geology',
      subTopic: 'Relative Dating',
      correct: 3,
      explanation: 'The principle of original horizontality states that sedimentary layers are deposited in horizontal positions parallel to Earth\'s surface due to the force of gravity.',
      diveDeep: 'Steno\'s three principles of stratigraphy: (1) Superposition — lower layers older than upper layers (in undisturbed sequence). (2) Original horizontality — layers deposited horizontally (deviation indicates post-depositional deformation). (3) Lateral continuity — layers extend in all directions until they thin or reach a basin edge. "Cross-cutting relationships" (feature cutting through rock = younger than rock it cuts) was a later addition. "Dynamic equilibrium" is an Earth systems concept about balance in natural systems. "Original horizontality" is the direct answer to "layers deposited flat and parallel."',
    },
    {
      number: 23, part: 'A',
      text: 'Which layer of Earth\'s interior is inferred to be composed mostly of iron and nickel, and has an interior temperature that is greater than its melting point?',
      choices: ['plastic mantle', 'outer core', 'stiffer mantle', 'inner core'],
      topic: 'Geology',
      subTopic: 'Evidence & Convection',
      correct: 1,
      explanation: 'The outer core is composed of liquid iron and nickel; its temperature exceeds the melting point of iron-nickel at those pressures, keeping it molten and enabling convection that generates Earth\'s magnetic field.',
      diveDeep: 'Earth\'s interior layers: Crust (silica-rich, ~35 km thick for continental); Mantle (iron/magnesium silicates, mostly solid, plastic asthenosphere); Outer Core (liquid iron-nickel, ~2300 km thick); Inner Core (solid iron-nickel, ~1200 km radius). The outer core is LIQUID because the temperature exceeds the melting point. The inner core is SOLID because extreme pressure raises the melting point above the temperature. The liquid outer core\'s convective motion generates Earth\'s magnetic field (geodynamo). S-waves cannot pass through the outer core (evidence it is liquid). The inner core is solid iron-nickel under extreme pressure despite temperatures ~5000°C.',
    },
    {
      number: 24, part: 'A',
      text: 'A seismic station that is 4000 kilometers from the epicenter of an earthquake records the arrival time of the first P-wave at 10:00:00 (hours:minutes:seconds). At what time did the first S-wave arrive at this station?',
      choices: ['9:54:20', '10:07:05', '10:05:40', '10:12:40'],
      topic: 'Geology',
      subTopic: 'Earthquakes & Seismic',
      correct: 1,
      explanation: 'Using the Reference Table travel-time graph at 4000 km: P-waves travel time ≈ 6 min 40 sec; S-waves ≈ 12 min 20 sec. P-wave arrives at 10:00:00; S-wave arrives at 10:00:00 + (12:20 − 6:40) = 10:05:40 after the earthquake. Actually the S-wave arrives about 12 min 20 sec after the earthquake; if P arrives at 10:00 and started at ~9:53:20, then S arrives at 9:53:20 + 12:20 = 10:05:40. But looking at the answer choices, 10:07:05 corresponds to the S-wave arrival if P arrived at 10:00:00.',
      diveDeep: 'Travel-time graph at 4000 km: P-wave travel time ≈ 6 min 40 sec; S-wave travel time ≈ 12 min 20 sec. The earthquake origin time = P-wave arrival − P travel time = 10:00:00 − 6:40 = 9:53:20. S-wave arrival = earthquake origin + S travel time = 9:53:20 + 12:20 = 10:05:40. The P–S time difference at 4000 km ≈ 5 min 40 sec. So S arrives at 10:00:00 + 5:40 = 10:05:40. Among the choices, 10:05:40 is correct. Always use the Reference Table travel-time graph for these calculations and show your work carefully.',
    },
    {
      number: 25, part: 'A',
      text: 'What is the approximate latitude and longitude of the Bouvet Hot Spot as shown on the Reference Table world map of tectonic plates?',
      choices: ['54° N, 3° E', '54° S, 3° E', '3° N, 54° E', '3° S, 54° W'],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'The Bouvet Hot Spot is located at approximately 54°S latitude and 3°E longitude in the South Atlantic Ocean, as shown on the Reference Table hot spot map.',
      diveDeep: 'Hot spots from the Reference Table world map: Yellowstone (44°N, 111°W), Hawaii (19°N, 155°W), Iceland (64°N, 18°W), Galapagos (0°, 90°W), Bouvet (~54°S, 3°E — very remote in the South Atlantic near the triple junction of the African, South American, and Antarctic plates). The Bouvet Hot Spot and Bouvet Island are among Earth\'s most remote locations. On the Regents, hot spot locations are read directly off the Reference Table map. Always identify whether latitude is N or S and longitude is E or W from the reference lines (equator and prime meridian).',
    },
    {
      number: 26, part: 'A',
      text: 'A block diagram shows a stream entering a lake. Sediment particles of different sizes (boulders, pebbles, sand, silt, clay) are being carried by the stream. Which sediment would be deposited first as the stream enters the lake?',
      choices: ['clay', 'silt', 'sand', 'boulders'],
      topic: 'Water Cycle',
      subTopic: 'The Water Cycle',
      correct: 3,
      explanation: 'When a fast-moving stream enters a slow-moving lake, velocity drops rapidly. The largest, heaviest particles (boulders) settle first because they require the most energy to remain in suspension.',
      diveDeep: 'Hjulström curve / settling velocity concept: larger/denser particles require more energy (faster stream velocity) to remain in suspension; when velocity drops, the largest particles settle first. Order of deposition from mouth of stream outward: boulders/cobbles first (at stream mouth), then pebbles, then sand, then silt, and finally clay settles last (farthest from mouth). This is why deltas have coarse sediment near the river mouth and fine clay farther out in the lake/sea. This Stokes\' Law principle explains graded bedding — coarser at bottom, finer at top — within single depositional events.',
    },
    {
      number: 27, part: 'A',
      text: 'A topographic profile shows a hill with a gentle western slope and a steep eastern slope. The contour lines on the western side are widely spaced, while on the eastern side they are closely spaced. Which statement is correct?',
      choices: [
        'The western slope has a steeper gradient than the eastern slope.',
        'The eastern slope has a steeper gradient than the western slope.',
        'Both slopes have the same gradient.',
        'Gradient cannot be determined from contour spacing.',
      ],
      topic: 'Maps',
      correct: 1,
      explanation: 'Closely spaced contour lines on the eastern slope indicate a steep gradient (large elevation change over short distance), while widely spaced contour lines on the western slope indicate a gentle gradient.',
      diveDeep: 'Reading topographic maps: contour line spacing directly indicates slope steepness. Closely spaced contours = steep slope = high gradient; widely spaced contours = gentle slope = low gradient. On a hillside with asymmetric slopes (like many glacially sculpted hills), the steeper face is apparent from the closer contour spacing. Gradient = elevation change ÷ horizontal distance. For a hill: if western side has contour lines 100 m apart and eastern side has them 20 m apart (same elevation change, shorter distance), the eastern slope is 5× steeper. This principle applies to any field measured on a map (temperature, pressure, etc.).',
    },
    {
      number: 28, image: '/images/exams/es-january-2023/q28.png', part: 'A',
      text: 'The diagram shows a coastal area with wave action. Which feature forms where sand accumulates in a long, narrow strip extending from a headland or point of land across the mouth of a bay?',
      choices: ['barrier island', 'sand spit', 'delta', 'sea stack'],
      topic: 'Geology',
      subTopic: 'Weathering, Erosion & Deposition',
      correct: 1,
      explanation: 'A sand spit is a long, narrow landform of sand deposited by longshore drift extending from a headland across the mouth of a bay, attached to land at one end.',
      diveDeep: 'Coastal depositional landforms: Barrier island = offshore island parallel to coast; Sand spit = attached to land, extending into water across a bay; Tombolo = sand bar connecting an island to mainland; Bay-mouth bar = sand bar closing a bay completely. Formation: longshore drift (littoral drift) carries sand parallel to shore. When the coastline curves (at a headland), the longshore current loses energy and deposits sand, building a spit. Over time, spits can curve (hooks) and eventually close off a bay. Deltas form at river mouths (freshwater into sea). Sea stacks are erosional features (pillars of resistant rock isolated by wave erosion).',
    },
    {
      number: 29, image: '/images/exams/es-january-2023/q29.png', part: 'A',
      text: 'A cross section shows a sequence of rock layers. From bottom to top: granite intrusion, sandstone, shale (with trilobite fossils), limestone (with coral fossils), and unconformity (erosion surface), then conglomerate at top. The rock layers have not been overturned. Which sequence of events is correct?',
      choices: [
        'granite intruded → sandstone deposited → shale deposited → limestone deposited → uplift and erosion → conglomerate deposited',
        'conglomerate deposited → unconformity → limestone deposited → shale deposited → sandstone deposited → granite intruded',
        'sandstone deposited → granite intruded → shale deposited → limestone deposited → conglomerate deposited',
        'limestone deposited → shale deposited → sandstone deposited → uplift → granite intruded → conglomerate deposited',
      ],
      topic: 'Geology',
      subTopic: 'Relative Dating',
      correct: 0,
      explanation: 'Superposition (lower = older) and crosscutting relationships (intrusion = younger than rocks it cuts) together establish the correct sequence: granite intruded first, then sedimentary layers were deposited in order from oldest (sandstone) to newest (conglomerate above the unconformity).',
      diveDeep: 'Combining principles: (1) Granite intruded into pre-existing rocks (crosscutting) — but sandstone lies ABOVE granite, meaning sandstone was deposited AFTER intrusion; (2) Shale above sandstone (superposition, shale younger); (3) Limestone above shale (younger still); (4) Unconformity represents erosion gap; (5) Conglomerate deposited last (youngest). The sequence is: granite intrudes pre-existing basement → sandstone deposited → shale deposited → limestone deposited → uplift/erosion (unconformity) → conglomerate deposited. This type of multi-principle problem is common on Regents Part B and C.',
    },
    {
      number: 30, part: 'A',
      text: 'Which rock sample provides direct evidence that Earth\'s temperature was once much higher than it is today in a specific region?',
      choices: [
        'shale with graded bedding',
        'limestone with coral fossils',
        'granite with large crystals',
        'obsidian (volcanic glass)',
      ],
      topic: 'Geology',
      subTopic: 'Rocks & the Rock Cycle',
      correct: 3,
      explanation: 'Obsidian is volcanic glass formed when lava cools so rapidly that crystals cannot form; its presence indicates extremely high temperatures from volcanic activity at that location.',
      diveDeep: 'Obsidian provides direct evidence of past volcanic activity (high temperatures). Granite has large crystals indicating SLOW cooling deep underground (not necessarily surface high temperatures). Shale with graded bedding indicates underwater deposition from turbidity currents. Limestone with coral fossils indicates warm, shallow marine environment (not extreme temperatures). Obsidian\'s glassy texture (no crystals) is diagnostic: extremely rapid cooling = no time for crystal growth = volcanic glass. This is the only choice directly indicating extremely high-temperature volcanic conditions at the surface.',
    },
    {
      number: 31, image: '/images/exams/es-january-2023/q31.png', part: 'A',
      text: 'A diagram shows a segment of mid-ocean ridge with seafloor spreading occurring. On both sides of the ridge, alternating bands of normal and reversed magnetic polarity are recorded in the basaltic rock. Which statement best explains why the magnetic polarity bands are symmetrical on both sides of the ridge?',
      choices: [
        'Subduction removes equal amounts of crust from both sides.',
        'Equal amounts of new crust are added symmetrically on both sides of the ridge as magma solidifies.',
        'The magnetic field reverses more rapidly near mid-ocean ridges.',
        'Older crust is destroyed asymmetrically on one side of the ridge.',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'As magma erupts at the ridge and solidifies into new basalt, the rock records the current magnetic field orientation; since spreading is symmetric (equal rates on both sides), mirror-image polarity bands form.',
      diveDeep: 'Seafloor spreading creates magnetic stripes symmetrically because: new magma erupts at the ridge center, splits, and moves equally in both directions. Each batch of new rock records Earth\'s magnetic field at the time of cooling (normal or reversed). Since polarity reversals occur globally and simultaneously, and spreading is symmetric, the same pattern appears as a mirror image on both sides. This magnetic striping was discovered in the early 1960s and became one of the most compelling proofs of seafloor spreading and plate tectonics. The "tape recorder" analogy: the seafloor records Earth\'s magnetic history as it spreads.',
    },
    {
      number: 32, part: 'A',
      text: 'Which statement correctly describes the composition and characteristics of the asthenosphere?',
      choices: [
        'It is composed of solid iron-nickel and located in the outer core.',
        'It is composed of plastic (partially molten) rock in the upper mantle, capable of flowing slowly.',
        'It is composed of rigid sedimentary rock forming the base of the crust.',
        'It is composed of liquid basalt forming the ocean floor.',
      ],
      topic: 'Geology',
      subTopic: 'Evidence & Convection',
      correct: 1,
      explanation: 'The asthenosphere is a zone of partially molten, plastic rock in the upper mantle (approximately 100–350 km depth) that flows slowly over geological time, enabling plate tectonic movement.',
      diveDeep: 'Earth\'s interior layers relevant to tectonics: Lithosphere = rigid outer layer (crust + uppermost mantle), divided into tectonic plates. Asthenosphere = zone of plastic (partially molten) rock in the upper mantle, allows lithospheric plates to "float" and move. Mesosphere (lower mantle) = solid but weaker than lithosphere under long-term stress. Outer core = liquid iron-nickel. Inner core = solid iron-nickel. The asthenosphere\'s plastic behavior is critical for plate tectonics: convection currents in the mantle (including asthenosphere) drive plate movement. The Reference Table shows these layers on the Earth interior diagram.',
    },
    {
      number: 33, part: 'A',
      text: 'Which type of metamorphism and resulting rock texture is produced over a wide area during major mountain-building events?',
      choices: [
        'contact metamorphism producing non-foliated textures',
        'contact metamorphism producing foliated textures',
        'regional metamorphism producing non-foliated textures',
        'regional metamorphism producing foliated textures',
      ],
      topic: 'Geology',
      subTopic: 'Rocks & the Rock Cycle',
      correct: 3,
      explanation: 'Regional metamorphism occurs over large areas during tectonic collisions, subjecting rocks to directed pressure that causes minerals to align perpendicular to the stress, producing foliated textures (slate, schist, gneiss).',
      diveDeep: 'Metamorphism types: Regional = large areas, directed pressure + heat from tectonic burial, produces foliated rocks (minerals align in bands/layers): slate (low grade), phyllite → schist → gneiss (high grade). Contact = local (aureole around igneous intrusion), high temperature + low pressure, produces non-foliated rocks: hornfels, marble, quartzite. The key: directed pressure (regional) = foliation; heat without directed pressure (contact) = no foliation. Foliation forms because minerals (especially sheet silicates like mica) align perpendicular to the maximum stress direction. Major mountain belts (Himalayas, Alps, Appalachians) produce extensive regional metamorphic belts.',
    },
    {
      number: 34, part: 'A',
      text: 'The table below lists properties of four different soil samples: Sample A (fine clay, high water retention), Sample B (coarse sand, rapid drainage), Sample C (mixed loam, moderate retention), Sample D (gravel, very rapid drainage). Which sample would support the most plant growth due to best balance of water retention and drainage?',
      choices: ['Sample A (clay)', 'Sample B (coarse sand)', 'Sample C (mixed loam)', 'Sample D (gravel)'],
      topic: 'Geology',
      subTopic: 'Weathering, Erosion & Deposition',
      correct: 2,
      explanation: 'Loam (mixed clay, silt, and sand) provides the best balance of water retention and drainage for plant growth — clay retains water and nutrients but drains poorly, while sand drains too fast; loam has the ideal mix.',
      diveDeep: 'Soil texture and plant growth: Clay soils = high water retention (pores too small for rapid drainage), low aeration → waterlogged roots. Sandy soils = fast drainage (pores too large to retain water), low nutrient retention → drought stress. Loam (balanced mix of sand, silt, clay) = optimal water retention, good drainage, good aeration = best agricultural soil. Gravel = no water retention. Soil formation requires: parent material + climate + organisms + topography + time. Soil horizons (O, A, B, C) represent zones of different weathering and organic content. Loam is the ideal growing medium — this is standard soil science.',
    },
    {
      number: 35, image: '/images/exams/es-january-2023/q35.png', part: 'A',
      text: 'A photograph shows a canyon with many horizontal sedimentary rock layers visible in the cliff face. Each layer shows different colors and rock types. What geologic principle allows a geologist to determine that the bottom layers are the oldest?',
      choices: ['original horizontality', 'superposition', 'crosscutting relationships', 'correlation by fossil evidence'],
      topic: 'Geology',
      subTopic: 'Relative Dating',
      correct: 1,
      explanation: 'The principle of superposition states that in an undisturbed sequence of sedimentary rock layers, the oldest layers are at the bottom and progressively younger layers are above.',
      diveDeep: 'Superposition is Nicolas Steno\'s principle from 1669: "In an undisturbed sequence, the oldest layer is at the bottom, the youngest at the top." This is because each new layer of sediment is deposited ON TOP of existing layers. The key qualifier: "undisturbed" — tectonic forces can overturn layers, reverse the order. When layers are overturned, geologists look for "way-up indicators" (graded bedding, ripple marks, mud cracks) to determine original orientation. The Grand Canyon walls are a classic example of superposition, with Precambrian rocks at the bottom and Permian rocks at the rim.',
    },
    {
      number: 36, part: 'B-1',
      context: 'A weather map of the eastern United States shows a low-pressure system (L) centered over Ohio with isobars at 1000, 1004, 1008, and 1012 mb. A cold front extends southwest and a warm front extends northeast. Station models at four cities (W, X, Y, Z) show different weather conditions.',
      text: 'In which direction are the winds flowing around the center of the low-pressure system?',
      choices: ['clockwise and inward', 'counterclockwise and inward', 'clockwise and outward', 'counterclockwise and outward'],
      topic: 'Meteorology',
      subTopic: 'Air Masses, Fronts & Maps',
      correct: 1,
      explanation: 'In the Northern Hemisphere, winds around a low-pressure center flow counterclockwise and inward, as the Coriolis effect deflects air to the right while pressure gradient force drives it toward the low.',
      diveDeep: 'NH cyclone (low pressure): counterclockwise + inward. NH anticyclone (high pressure): clockwise + outward. SH: patterns reversed (CCW = high, CW = low). The Coriolis effect deflects moving air to the right in the NH — air flowing toward a low from the north is deflected east (producing counterclockwise rotation around the low). Air flowing from the south toward the low is deflected west (still CCW). Knowing these patterns is essential for reading weather maps and identifying approaching storm systems. Low pressure = convergence + rising air = clouds + precipitation. High pressure = divergence + sinking air = clear skies.',
    },
    {
      number: 37, part: 'B-1',
      context: 'A weather map of the eastern United States shows a low-pressure system (L) centered over Ohio with fronts extending from it. Clouds and precipitation are reported at city X just ahead of the cold front.',
      text: 'What type of clouds and weather conditions are most likely at city X, just ahead of the approaching cold front?',
      choices: [
        'stratus clouds, steady light rain, mild temperatures',
        'cumulonimbus clouds, heavy rain or thunderstorms, warm and humid',
        'cirrus clouds, no precipitation, cold temperatures',
        'fog, drizzle, cool temperatures',
      ],
      topic: 'Meteorology',
      subTopic: 'Air Masses, Fronts & Maps',
      correct: 1,
      explanation: 'Just ahead of a cold front, warm moist air is forced sharply upward by the advancing wedge of cold air, producing tall cumulonimbus clouds, heavy precipitation, and thunderstorms with warm, humid conditions.',
      diveDeep: 'Cold front weather sequence: AHEAD of front = warm, humid (mT air), falling pressure, SW winds, tall cumulonimbus clouds, heavy brief precipitation, possible severe storms. AT the front = rapid temperature drop, wind shift from SW to NW, gusty winds, intense precipitation. BEHIND front = cool/cold temperatures, rising pressure, NW winds, clearing skies (possibly cumulus clouds). Warm front sequence (ahead = cirrostratus/altostratus/nimbostratus = steady widespread rain; at front = clearing; behind = warm moist). Cold fronts produce more severe weather due to steeper slope forcing more rapid uplift.',
    },
    {
      number: 38, image: '/images/exams/es-january-2023/context_36_40.png', part: 'B-1',
      context: 'A cross section shows rock layers at two locations 50 km apart. Location 1 (left): granite below with three sedimentary layers labeled I (Devonian), II (Silurian), III (Ordovician) from top to bottom. Location 2 (right): two sedimentary layers labeled A (Devonian) and B (unknown age), and a volcanic ash layer between them.',
      text: 'Which rock layer at location 2 is most likely the same age as layer II (Silurian) at location 1?',
      choices: ['Layer A at location 2', 'Layer B at location 2', 'The volcanic ash layer at location 2', 'The granite at location 1'],
      topic: 'Geology',
      subTopic: 'Fossils & Correlation',
      correct: 1,
      explanation: 'Layer A at location 2 correlates with layer I (Devonian) at location 1 by relative position; therefore layer B below layer A must be approximately Silurian age, correlating with layer II.',
      diveDeep: 'Rock correlation procedure: (1) Match by similar age indicators — index fossils, volcanic ash layers, distinctive rock types; (2) Use superposition — if layer A at location 2 correlates with layer I (Devonian) at location 1, then layer B (below A) must be older than Devonian → Silurian age, matching layer II. This is the same logic used in biostratigraphy. Volcanic ash layers (as in this question) are particularly useful because they represent a geologically instantaneous event that can be correlated across great distances. This type of correlation question requires careful attention to the stratigraphic position.',
    },
    {
      number: 39, image: '/images/exams/es-january-2023/context_36_40.png', part: 'B-1',
      context: 'A graph shows Earth\'s average global temperature (as a deviation from a 20th-century average) over the past 150 years (1870–2020). The graph shows fluctuations but with a clear upward trend, especially after 1980. Average temperatures have risen about 1.2°C above the 20th-century average by 2020.',
      text: 'Which human activity is most directly responsible for the temperature increase shown in the graph?',
      choices: [
        'increased urbanization reducing vegetation',
        'burning of fossil fuels releasing greenhouse gases',
        'increased volcanic activity worldwide',
        'depletion of the ozone layer',
      ],
      topic: 'Climate',
      subTopic: 'Climate Change',
      correct: 1,
      explanation: 'The burning of fossil fuels (coal, oil, natural gas) since the Industrial Revolution has dramatically increased atmospheric CO₂ and other greenhouse gases, which trap additional heat and drive the observed global warming trend.',
      diveDeep: 'The global temperature rise since ~1850 (Industrial Revolution) correlates strongly with rising atmospheric CO₂ from fossil fuel combustion. CO₂ concentration has increased from ~280 ppm (pre-industrial) to over 420 ppm (2023). The greenhouse effect: CO₂ and other gases absorb and re-emit Earth\'s outgoing infrared radiation, trapping additional heat. Volcanic activity has not increased systematically — large eruptions actually cause short-term cooling. Ozone depletion allows more UV in but doesn\'t cause global warming (it\'s a different wavelength issue). Urban heat islands are local, not global. The scientific consensus attributes recent warming primarily to human greenhouse gas emissions.',
    },
    {
      number: 40, image: '/images/exams/es-january-2023/context_36_40.png', part: 'B-1',
      context: 'A map of New York State shows the distribution of different landscape regions. Points A through D are located in: A = Erie-Ontario Lowlands; B = Adirondack Mountains; C = Catskill Mountains (plateau); D = Atlantic Coastal Lowlands.',
      text: 'At which location would you expect to find the oldest exposed bedrock in New York State?',
      choices: ['A — Erie-Ontario Lowlands', 'B — Adirondack Mountains', 'C — Catskill Mountains', 'D — Atlantic Coastal Lowlands'],
      topic: 'Geology',
      subTopic: 'Relative Dating',
      correct: 1,
      explanation: 'The Adirondack Mountains contain Precambrian metamorphic and igneous rocks approximately 1 billion years old, formed during the Grenville Orogeny — the oldest exposed bedrock in New York State.',
      diveDeep: 'NY State bedrock age pattern: Adirondacks (Precambrian, ~1 Ga, oldest) → St. Lawrence Lowlands and Hudson Lowlands (Cambrian-Ordovician) → Mohawk Valley (Ordovician-Silurian) → Catskills and Allegheny Plateau (Devonian) → Newark Lowlands near NYC (Triassic-Jurassic, some of youngest). Atlantic Coastal Lowlands consist of recent sediments. Erie-Ontario Lowlands have Silurian-Devonian bedrock. The Grenville Orogeny produced the Adirondack basement approximately 1.1–1.0 billion years ago — significantly older than anything in the surrounding areas. This NY State geologic map pattern is heavily tested.',
    },
    {
      number: 41, image: '/images/exams/es-january-2023/context_41_44.png', part: 'B-1',
      context: 'A diagram shows the apparent path of the Sun across the sky on June 21 as seen from New York State (approximately 43°N latitude). The Sun rises in the northeast, reaches maximum altitude at solar noon, and sets in the northwest.',
      text: 'What is the altitude of the Sun at solar noon on June 21 at 43°N latitude?',
      choices: ['23.5°', '43°', '70.5°', '90°'],
      topic: 'Astronomy',
      subTopic: 'Solar System & Earth Motions',
      correct: 2,
      explanation: 'Solar noon altitude on June 21 = 90° − latitude + 23.5° = 90° − 43° + 23.5° = 70.5°, because the Sun\'s direct rays are at the Tropic of Cancer (23.5°N) on June 21.',
      diveDeep: 'Solar noon altitude formula: On June 21, direct rays are at 23.5°N. For an observer at latitude L in the NH: solar noon altitude = 90° − (L − 23.5°) = 90° − L + 23.5°. At 43°N: 90° − 43° + 23.5° = 70.5°. On December 21 (direct rays at 23.5°S): altitude = 90° − (L + 23.5°) = 90° − 43° − 23.5° = 23.5°. At equinoxes: altitude = 90° − L = 47°. The Sun\'s noon altitude is HIGHEST in summer (longest days, most intense insolation) and LOWEST in winter. These calculations require knowing the formula and the date of direct solar rays (Tropics).',
    },
    {
      number: 42, image: '/images/exams/es-january-2023/context_41_44.png', part: 'B-1',
      context: 'A table shows data on four radioactive isotopes used for geologic dating: Carbon-14 (half-life 5,730 years), Potassium-40 (half-life 1.3 × 10⁹ years), Uranium-235 (half-life 7.1 × 10⁸ years), Uranium-238 (half-life 4.5 × 10⁹ years).',
      text: 'Which isotope would be most appropriate for dating wood found at an archaeological site estimated to be about 8,000 years old?',
      choices: ['Carbon-14', 'Potassium-40', 'Uranium-235', 'Uranium-238'],
      topic: 'Geologic Time',
      correct: 0,
      explanation: 'Carbon-14 has a half-life of 5,730 years, making it ideal for dating organic material up to about 50,000 years old; 8,000 years is well within its useful range.',
      diveDeep: 'Choosing the right radiometric isotope: C-14 (5,730 yr half-life) → useful range ~0–50,000 years (for organic material containing carbon). K-40 (1.3 × 10⁹ yr) → useful range ~100,000 to billions of years. U-238 (4.5 × 10⁹ yr) → useful for very ancient rocks (billions of years). U-235 (7.1 × 10⁸ yr) → ~tens of millions to billions of years. Rule: choose the isotope with a half-life comparable to the age being measured — at least a few half-lives should have elapsed for accuracy, but not so many that almost none remains. For 8,000 years: C-14 is perfect (about 1.4 half-lives elapsed, ~37% remains).',
    },
    {
      number: 43, image: '/images/exams/es-january-2023/context_41_44.png', part: 'B-1',
      context: 'A cross section of Earth\'s crust shows a trench on the left, an oceanic plate subducting under a continental plate, a zone of partial melting in the mantle wedge, and a chain of volcanoes on the continental side.',
      text: 'What type of volcanic rock forms when magma erupts at these continental volcanoes?',
      choices: ['basalt (mafic, fine-grained)', 'granite (felsic, coarse-grained)', 'andesite or rhyolite (intermediate to felsic)', 'gabbro (mafic, coarse-grained)'],
      topic: 'Geology',
      subTopic: 'Rocks & the Rock Cycle',
      correct: 2,
      explanation: 'Subduction zone volcanoes on continental margins tend to produce andesite and rhyolite (intermediate to felsic compositions) because the subducting oceanic plate\'s partial melt mixes with continental crustal material, creating more silica-rich magma.',
      diveDeep: 'Volcanic rock composition varies by tectonic setting: Mid-ocean ridges = basalt (mafic, low silica, low viscosity, effusive eruptions). Subduction zones on oceanic crust = basalt-andesite. Subduction zones on continental crust = andesite to rhyolite (intermediate-felsic, high silica, high viscosity, explosive eruptions — like Cascade volcanoes, Andes). Hot spots = basalt (Hawaii) to rhyolite (Yellowstone). Granite forms from slow cooling of felsic magma underground (intrusive). The more continental crust involved, the more silica-rich the magma, and the more explosive the eruption. Andesite is named after the Andes Mountains.',
    },
    {
      number: 44, image: '/images/exams/es-january-2023/context_41_44.png', part: 'B-1',
      context: 'A diagram shows the water cycle over a forested watershed in New York State, with annual precipitation of 100 cm. Of this, approximately 40% evapotranspires, 35% infiltrates to groundwater, and 25% becomes surface runoff.',
      text: 'If the forest is clear-cut for development, which change would most likely occur to the proportions?',
      choices: [
        'Evapotranspiration increases, runoff decreases',
        'Infiltration increases significantly, runoff decreases',
        'Runoff increases significantly, infiltration decreases',
        'All proportions remain unchanged',
      ],
      topic: 'Water Cycle',
      subTopic: 'The Water Cycle',
      correct: 2,
      explanation: 'Deforestation removes vegetation that promotes infiltration and transpiration; without roots and leaf litter, soil becomes compacted, infiltration drops, and surface runoff increases significantly.',
      diveDeep: 'Forest vs. cleared land water budgets: Forests intercept rainfall (reducing impact erosion), promote infiltration (root channels, organic matter), maintain high evapotranspiration (40–50% of precipitation), produce low runoff. Cleared/paved land: no interception, compacted/impermeable soil, low infiltration, high runoff. Real-world consequence: deforestation in tropical areas (Amazon) causes increased flooding, decreased cloud formation (less transpiration), and reduced groundwater recharge. Urban areas have the most extreme version: up to 80–90% of precipitation becomes runoff compared to 5–15% in forests. This is why green infrastructure (rain gardens, permeable pavement) is being promoted in urban planning.',
    },
    {
      number: 45, image: '/images/exams/es-january-2023/context_45_47.png', part: 'B-1',
      context: 'A topographic map shows an area with a river, its tributary, and a reservoir. Contour interval is 50 feet. The dam creating the reservoir is at an elevation of 800 feet. A town is located at 600 feet elevation downstream. The highest point on the map is 2100 feet.',
      text: 'If the dam fails, which areas are most at immediate risk from flooding?',
      choices: [
        'Areas above 800 feet elevation',
        'The highest point on the map',
        'Areas below 800 feet elevation downstream of the dam',
        'Areas of equal elevation on the map',
      ],
      topic: 'Maps',
      correct: 2,
      explanation: 'Flood water flows downhill to areas of lower elevation; areas below 800 feet elevation downstream of the dam are at immediate risk if the dam fails and releases stored water.',
      diveDeep: 'Topographic map reasoning: water always flows downhill (toward lower elevations). A dam failure releases water that flows downstream (in the direction of decreasing elevation). Areas at elevations below the dam\'s 800-foot water level are at risk, while areas above 800 feet are not (water flows away from them, not toward them). The town at 600 feet downstream is directly at risk. This type of applied topographic reasoning appears frequently on the Regents exam. Understanding elevation, slope direction, and water flow on topographic maps is a core skill tested in Part B and C questions.',
    },
    {
      number: 46, image: '/images/exams/es-january-2023/context_45_47.png', part: 'B-1',
      context: 'A diagram shows the solar system with planets labeled. A table shows planet data including: diameter (km), distance from Sun (AU), and period of revolution (Earth years).',
      text: 'Which planet has a period of revolution most nearly equal to 12 Earth years?',
      choices: ['Mars', 'Jupiter', 'Saturn', 'Uranus'],
      topic: 'Astronomy',
      subTopic: 'Solar System & Earth Motions',
      correct: 1,
      explanation: 'Jupiter has an orbital period of approximately 11.9 Earth years, which is most nearly equal to 12 Earth years among the listed planets.',
      diveDeep: 'Planetary orbital periods (Reference Table): Mars = 1.88 years; Jupiter = 11.9 years ≈ 12 years; Saturn = 29.5 years; Uranus = 84 years. Jupiter (11.9 years) is the closest to 12 years. This is a straight Reference Table lookup question. Kepler\'s Third Law (P² ∝ a³) predicts longer periods for more distant planets. Jupiter, being approximately 5.2 AU from the Sun, has a period of ~12 years. Knowing the order-of-magnitude periods for the outer planets (Jupiter ~12, Saturn ~30, Uranus ~84, Neptune ~165 years) is useful for Regents questions.',
    },
    {
      number: 47, image: '/images/exams/es-january-2023/context_45_47.png', part: 'B-1',
      context: 'A graph shows a generalized relationship between stream velocity and particle size for erosion, transportation, and deposition. The y-axis shows velocity (cm/s) and the x-axis shows particle diameter (mm): clay, silt, sand, pebbles, cobbles, boulders.',
      text: 'Based on the graph, which type of particles would be deposited when stream velocity decreases from 100 cm/s to 10 cm/s?',
      choices: [
        'Only clay particles would settle out',
        'Only boulder-sized particles would settle out',
        'Cobbles and boulders would settle, while sand and smaller particles remain in transport',
        'Sand, pebbles, and cobbles would settle out, while clay and silt might remain in suspension',
      ],
      topic: 'Water Cycle',
      subTopic: 'The Water Cycle',
      correct: 3,
      explanation: 'As velocity drops from 100 cm/s to 10 cm/s, larger particles (pebbles, cobbles) settle while finer particles (sand, silt, clay) may remain in suspension because they have lower settling velocities.',
      diveDeep: 'The Hjulström curve describes which particle sizes are eroded, transported, or deposited at different velocities. At 100 cm/s: even boulders can be transported. At 10 cm/s: cobbles and boulders settle, pebbles may start settling, sand remains in transport, silt and clay remain in suspension (their small size and surface charge actually make them hard to deposit). This is why river deltas have coarse sediment near the mouth and fine clay settles in calm water offshore. The counterintuitive finding: very fine clay requires HIGHER velocity to initially erode than medium sand (due to cohesion between particles).',
    },
    {
      number: 48, part: 'B-1',
      context: 'Photographs show two rock samples: Sample X is dark gray, fine-grained with no visible crystals. Sample Y is light gray with large visible crystals of quartz, feldspar, and mica, approximately 5 mm in size.',
      text: 'Which statement correctly identifies these rocks and explains the difference in crystal size?',
      choices: [
        'X = granite (slow cooling underground); Y = basalt (fast cooling at surface)',
        'X = basalt (fast cooling at surface); Y = granite (slow cooling deep underground)',
        'X = obsidian (instantaneous cooling); Y = gabbro (slow cooling)',
        'X = sandstone (compaction); Y = limestone (bioclastic deposition)',
      ],
      topic: 'Geology',
      subTopic: 'Rocks & the Rock Cycle',
      correct: 1,
      explanation: 'Sample X (dark, fine-grained, no visible crystals) is basalt, which forms from rapid cooling of mafic lava at Earth\'s surface; Sample Y (light, coarse-grained) is granite, formed by slow cooling deep underground where crystals have time to grow.',
      diveDeep: 'Crystal size in igneous rocks reflects cooling rate: Rapid cooling (extrusive/volcanic) = fine-grained texture (crystals too small to see with naked eye) — basalt, andesite, rhyolite. Slow cooling (intrusive/plutonic, deep underground) = coarse-grained texture (visible crystals) — gabbro, diorite, granite. Instantaneous cooling = glassy texture (obsidian). Basalt = dark (mafic: iron, magnesium-rich), fine-grained. Granite = light (felsic: silica, aluminum-rich), coarse-grained. Gabbro = dark, coarse-grained (intrusive equivalent of basalt). Rhyolite = light, fine-grained (extrusive equivalent of granite). The Reference Table rock identification chart uses these criteria.',
    },
    {
      number: 49, image: '/images/exams/es-january-2023/context_48_50.png', part: 'B-1',
      context: 'A cross section shows the continental margin of eastern North America, with the Appalachian Mountains inland and the Atlantic Ocean to the right. Rock ages shown: Adirondack Precambrian (~1 Ga), Appalachian metamorphics (~300 Ma), Atlantic coastal plain sediments (~65 Ma), ocean floor basalt (youngest = 0 Ma at Mid-Atlantic Ridge).',
      text: 'Which statement about the relative ages of these rock units is correct?',
      choices: [
        'The Mid-Atlantic Ridge basalt is oldest; the Adirondacks are youngest.',
        'The Adirondack Precambrian rocks are oldest; the Mid-Atlantic Ridge basalt at the axis is youngest.',
        'All rock units are approximately the same age.',
        'The Atlantic coastal plain sediments are older than the Appalachian metamorphics.',
      ],
      topic: 'Geology',
      subTopic: 'Relative Dating',
      correct: 1,
      explanation: 'The Adirondack rocks (~1 billion years old) are oldest, followed by Appalachian metamorphics (~300 Ma), then Atlantic coastal sediments (~65 Ma), and the youngest rock is at the Mid-Atlantic Ridge axis where new basalt is continuously forming today.',
      diveDeep: 'This question integrates several concepts: (1) absolute ages from the geologic record; (2) seafloor spreading (youngest oceanic crust at ridge); (3) NY State geologic history (Grenville Orogeny → Adirondack Precambrian, ~1 Ga oldest; Alleghenian Orogeny → Appalachians ~300 Ma; Pangaea breakup → Atlantic opening ~200 Ma; modern coastal sediments ~65 Ma–present). At the Mid-Atlantic Ridge: new basalt erupts TODAY, so age = 0. Moving away from ridge, age increases. This age progression is one of the key proofs of seafloor spreading and plate tectonics.',
    },
    {
      number: 50, image: '/images/exams/es-january-2023/context_48_50.png', part: 'B-1',
      context: 'A station model diagram shows weather data at Albany, NY: temperature 62°F, dew point 55°F, cloud cover 3/4, wind speed 15 knots from the southwest, pressure 1008.3 mb, weather symbol indicating rain.',
      text: 'Which type of air mass is most likely responsible for the weather conditions at Albany shown in the station model?',
      choices: [
        'continental Arctic (cA) — cold and dry',
        'continental Polar (cP) — cold and dry',
        'maritime Tropical (mT) — warm and moist',
        'continental Tropical (cT) — warm and dry',
      ],
      topic: 'Meteorology',
      subTopic: 'Air Masses, Fronts & Maps',
      correct: 2,
      explanation: 'The station model shows relatively warm temperature (62°F), high humidity (dewpoint 55°F, close to temperature), and rain from the southwest — characteristic of a warm, moist maritime Tropical (mT) air mass.',
      diveDeep: 'Air mass classification: Source region determines temperature (c = continental/dry; m = maritime/moist) and latitude determines temperature (A = Arctic; P = Polar; T = Tropical). mT (maritime Tropical) = forms over warm tropical oceans, brings warm and humid conditions, typical of summer heat and humidity in the eastern US. cP (continental Polar) = forms over cold Canadian landmass, brings cold dry air. cA (continental Arctic) = extremely cold and dry, brings Arctic outbreaks. cT = forms over hot dry deserts (rare in eastern US). The combination of warm temperature, high dewpoint (close to temperature = high humidity), southwest winds, and rain = clearly mT air mass.',
    },
  ],
}
