// Earth Science Regents — June 2025
// Source: esci62025-exam.pdf, esci62025-sk.pdf
export default {
  id: 'es-june-2025',
  subject: 'earth-science',
  year: 2025,
  session: 'June',
  totalMinutes: 180,
  questions: [
    {
      number: 1,
      part: 'A',
      text: 'The heliocentric model of the solar system shows the',
      choices: [
        'temperature of the Sun compared to the temperature of the planets',
        'age of the Sun compared to the age of the planets',
        'location of the planets in relation to the Sun',
        'size of the planets in relation to the Sun',
      ],
      topic: 'Astronomy',
      correct: 2,
    },
    {
      number: 2,
      part: 'A',
      text: 'A graph shows ocean tides at Battery Park in New York City from February 9 to February 15, 2020, with Moon phases shown. Compared to tides that occur during other Moon phases, which conclusion about tides that occur during a full moon can be made from the graph?',
      choices: [
        'High tide is lower when there is a full moon.',
        'Low tide is higher when there is a full moon.',
        'The tidal range is greater when there is a full moon.',
        'The tidal range is less when there is a full moon.',
      ],
      topic: 'Astronomy',
      correct: 2,
      image: '/images/exams/es-june-2025/q2.png',
    },
    {
      number: 3,
      part: 'A',
      text: 'Evidence of Earth\'s rotation on its axis is provided by both the',
      choices: [
        'Doppler effect and El Niño',
        'Doppler effect and the Coriolis effect',
        'Foucault pendulum and El Niño',
        'Foucault pendulum and the Coriolis effect',
      ],
      topic: 'Climate',
      correct: 3,
    },
    {
      number: 4,
      part: 'A',
      text: 'At which New York State location is the observed altitude of Polaris approximately 42°?',
      choices: [
        'Rochester',
        'New York City',
        'Plattsburgh',
        'Binghamton',
      ],
      topic: 'Astronomy',
      correct: 3,
    },
    {
      number: 5,
      part: 'A',
      text: 'A diagram represents a portion of Earth\'s latitude and longitude system. Location A is at 30°N, 30°W and location B is at 30°S, 45°E. When the time at location A is 12 noon, what time is it at location B?',
      choices: [
        '8 a.m.',
        '9 a.m.',
        '3 p.m.',
        '4 p.m.',
      ],
      topic: 'Maps',
      correct: 0,
      image: '/images/exams/es-june-2025/q5.png',
    },
    {
      number: 6,
      part: 'A',
      text: 'Orion is a constellation of stars that is visible in the evening sky in New York State from November through February. Orion is not visible the rest of the year because',
      choices: [
        'Earth rotates on its axis',
        'Earth revolves around the Sun',
        'Orion rotates on its axis',
        'Orion revolves around Earth',
      ],
      topic: 'Astronomy',
      correct: 1,
    },
    {
      number: 7,
      part: 'A',
      text: 'The hydrosphere is a relatively thin layer of',
      choices: [
        'solid rock making up approximately 70% of Earth\'s surface',
        'solid rock making up approximately 30% of Earth\'s surface',
        'water covering approximately 70% of Earth\'s surface',
        'water covering approximately 30% of Earth\'s surface',
      ],
      topic: 'Geology',
      correct: 2,
    },
    {
      number: 8,
      part: 'A',
      text: 'Earth revolves around the Sun at a rate of approximately',
      choices: [
        '1° per day',
        '360° per day',
        '15° per hour',
        '23.5° per hour',
      ],
      topic: 'Astronomy',
      correct: 0,
    },
    {
      number: 9,
      part: 'A',
      text: 'A diagram represents Earth\'s position relative to the Sun\'s rays on September 23, with the Sun\'s direct rays striking the equator at solar noon. During the next six months, the angle of the Sun\'s rays striking the equator at solar noon will',
      choices: [
        'decrease only',
        'decrease then increase',
        'increase only',
        'increase then decrease',
      ],
      topic: 'Astronomy',
      correct: 1,
    },
    {
      number: 10,
      part: 'A',
      text: 'Which type of unsaturated sediment will have the greatest permeability during a rainstorm?',
      choices: [
        'rounded and tightly packed',
        'rounded and loosely packed',
        'flattened and tightly packed',
        'flattened and loosely packed',
      ],
      topic: 'Geology',
      correct: 1,
    },
    {
      number: 11,
      part: 'A',
      text: 'A diagram represents four different apparent paths of the Sun (labeled A, B, C, and D) across the sky at four different locations, with angles 48° and 24.5° shown. Which line best represents the apparent path of the Sun across the sky on December 21 in New York State?',
      choices: [
        'A',
        'B',
        'C',
        'D',
      ],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-june-2025/q11.png',
    },
    {
      number: 12,
      part: 'A',
      text: 'Which table correctly indicates the locations of the polar front jet stream and subtropical jet stream near the time of the equinox?',
      choices: [
        'Polar Front at 60°N and 60°S; Subtropical at 30°N and 30°S',
        'Polar Front at 30°N and 30°S; Subtropical at 60°N and 60°S',
        'Polar Front at 90°N and 90°S; Subtropical at 30°N and 30°S',
        'Polar Front at 90°N and 90°S; Subtropical at 60°N and 60°S',
      ],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-june-2025/q12.png',
    },
    {
      number: 13,
      part: 'A',
      text: 'A station model shows weather conditions at Syracuse, New York with temperature 86°F, dew point 80°F, and winds from a specific direction. What is the best description of the weather at Syracuse?',
      choices: [
        'hot and dry with winds from the east',
        'hot and humid with winds from the east',
        'hot and humid with winds from the west',
        'hot and dry with winds from the west',
      ],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-june-2025/q13.png',
    },
    {
      number: 14,
      part: 'A',
      text: 'Which air mass is characterized by high relative humidity and low air temperature?',
      choices: [
        'maritime polar',
        'maritime tropical',
        'continental polar',
        'continental tropical',
      ],
      topic: 'Meteorology',
      correct: 0,
    },
    {
      number: 15,
      part: 'A',
      text: 'A flow chart shows heat sources that provide energy for Earth\'s systems, with internal heat sources (types A and B) and one external heat source (type C). Which correctly identifies heat source types A, B, and C?',
      choices: [
        'A = solar energy; B = volcanic activity; C = radioactive decay',
        'A = radioactive decay; B = residual heat from Earth\'s formation; C = solar energy',
        'A = solar energy; B = radioactive decay; C = residual heat from Earth\'s formation',
        'A = radioactive decay; B = solar energy; C = volcanic activity',
      ],
      topic: 'Geologic Time',
      correct: 1,
      image: '/images/exams/es-june-2025/q15.png',
    },
    {
      number: 16,
      part: 'A',
      text: 'A visible satellite image of the eastern United States shows clouds as white and land/water as gray or black. Which weather variable can be most accurately forecast using this satellite image?',
      choices: [
        'air temperature',
        'wind speed',
        'areas of precipitation',
        'type of precipitation',
      ],
      topic: 'Meteorology',
      correct: 2,
      image: '/images/exams/es-june-2025/q16.png',
    },
    {
      number: 17,
      part: 'A',
      text: 'Cross sections show widely separated outcrops (1, 2, and 3) with rock layers containing fossils W, X, Y, and Z. The rock layers have not been overturned. Which column represents the correct sequence of fossils (oldest at bottom) based on correlation of the three outcrops?',
      choices: [
        'Y, Z, W, X (bottom to top)',
        'X, Y, Z, W (bottom to top)',
        'Z, Y, X, W (bottom to top)',
        'Z, Y, W, X (bottom to top)',
      ],
      topic: 'Geologic Time',
      correct: 0,
      image: '/images/exams/es-june-2025/q17.png',
    },
    {
      number: 18,
      part: 'A',
      text: 'Which land surface absorbs the greatest amount of insolation?',
      choices: [
        'dark color and rough texture',
        'dark color and smooth texture',
        'light color and rough texture',
        'light color and smooth texture',
      ],
      topic: 'Climate',
      correct: 0,
    },
    {
      number: 19,
      part: 'A',
      text: 'During which era of Earth\'s geologic history did oceanic oxygen begin to enter Earth\'s atmosphere?',
      choices: [
        'Cenozoic Era',
        'Paleozoic Era',
        'Early Archean Era',
        'Early Proterozoic Era',
      ],
      topic: 'Geologic Time',
      correct: 3,
    },
    {
      number: 20,
      part: 'A',
      text: 'When did humans appear on Earth?',
      choices: [
        'before abundant grazing mammals and after the earliest flowering plants',
        'before the earliest grasses and after large carnivorous mammals',
        'during the same time as mastodonts and mammoths',
        'during the same time as the first forests and ammonoids',
      ],
      topic: 'Geologic Time',
      correct: 2,
    },
    {
      number: 21,
      part: 'A',
      text: 'If a rock contained 200 grams of the radioactive isotope potassium-40 (⁴⁰K) when it was formed, but now contains only 25 grams of potassium-40, how many years ago did the rock form?',
      choices: [
        '1.3 × 10⁹ years',
        '2.6 × 10⁹ years',
        '3.9 × 10⁹ years',
        '5.2 × 10⁹ years',
      ],
      topic: 'Geology',
      correct: 2,
    },
    {
      number: 22,
      part: 'A',
      text: 'The Alleghenian and Acadian orogenies were caused by which geologic process?',
      choices: [
        'deposition of minerals in evaporate basins',
        'original opening of oceans',
        'widespread coastal deposition',
        'collision of landmasses',
      ],
      topic: 'Geology',
      correct: 3,
    },
    {
      number: 23,
      part: 'A',
      text: 'The continents of Africa and South America were inferred to be two separate continents',
      choices: [
        '59 million years ago',
        '119 million years ago',
        '232 million years ago',
        '359 million years ago',
      ],
      topic: 'General Review',
      correct: 0,
    },
    {
      number: 24,
      part: 'A',
      text: 'Which surface feature was produced by crustal movements at a divergent plate boundary?',
      choices: [
        'San Andreas Fault',
        'Peru-Chile Trench',
        'Southeast Indian Ridge',
        'Tasman Hot Spot',
      ],
      topic: 'Plate Tectonics',
      correct: 2,
    },
    {
      number: 25,
      part: 'A',
      text: 'Which Earth layer has a density similar to the density of Mercury?',
      choices: [
        'oceanic crust',
        'stiffer mantle',
        'outer core',
        'inner core',
      ],
      topic: 'Geology',
      correct: 1,
    },
    {
      number: 26,
      part: 'A',
      text: 'Which factor is primarily responsible for the development of the stream drainage patterns in New York State?',
      choices: [
        'bedrock age',
        'bedrock structure',
        'types of fossils in the bedrock',
        'amount of fossils in the bedrock',
      ],
      topic: 'Geology',
      correct: 1,
    },
    {
      number: 27,
      part: 'A',
      text: 'Which processes result in the formation of soil?',
      choices: [
        'the compaction and cementation of sediments',
        'the melting and solidification of minerals',
        'biological activity and the weathering of rocks',
        'the addition of heat and pressure to bedrock',
      ],
      topic: 'Geology',
      correct: 2,
    },
    {
      number: 28,
      part: 'A',
      text: 'A table shows the densities of four mineral samples of equal size transported in a stream: olivine (3.5 g/cm³), garnet (4.0 g/cm³), quartz (2.7 g/cm³), and pyrite (5.0 g/cm³). As this stream flows into a lake, which mineral sample would most likely be deposited first?',
      choices: [
        'olivine',
        'garnet',
        'quartz',
        'pyrite',
      ],
      topic: 'Geology',
      correct: 3,
      image: '/images/exams/es-june-2025/q28.png',
    },
    {
      number: 29,
      part: 'A',
      text: 'Hematite and magnetite are mined as ores because they contain the element',
      choices: [
        'iron',
        'sulfur',
        'aluminum',
        'oxygen',
      ],
      topic: 'General Review',
      correct: 0,
      image: '/images/exams/es-june-2025/q29.png',
    },
    {
      number: 30,
      part: 'A',
      text: 'A cross section represents a portion of Earth\'s crust with a basalt intrusion containing several inclusions including limestone, sandstone, shale, and siltstone layers. The relative age of the limestone inclusion is',
      choices: [
        'younger than the basalt and older than the sandstone layer',
        'younger than the basalt and older than the limestone layer',
        'older than the basalt and older than the shale layer',
        'older than the basalt and older than the siltstone layer',
      ],
      topic: 'Geology',
      correct: 3,
      image: '/images/exams/es-june-2025/q30.png',
    },
    {
      number: 31,
      part: 'A',
      text: 'A block diagram represents the magnetic orientation of igneous bedrock on the seafloor on the western and eastern sides of a mid-ocean ridge. Locations A, B, and X are on the west side; locations C and D are on the east side. Which location is the same age as location X?',
      choices: [
        'A',
        'B',
        'C',
        'D',
      ],
      topic: 'Geology',
      correct: 3,
      image: '/images/exams/es-june-2025/q31.png',
    },
    {
      number: 32,
      part: 'A',
      text: 'A photograph shows an escarpment feature formed by uplift and erosion. An escarpment is best described as a',
      choices: [
        'steep, rocky cliff',
        'coastal shoreline',
        'mountain ridge',
        'depositional basin',
      ],
      topic: 'Geology',
      correct: 0,
      image: '/images/exams/es-june-2025/q32.png',
    },
    {
      number: 33,
      part: 'A',
      text: 'A photograph shows parallel scratches on the surface of a rock. Which erosional agent most likely produced these parallel scratches?',
      choices: [
        'wind',
        'glacier',
        'wave action',
        'running water',
      ],
      topic: 'Geology',
      correct: 1,
      image: '/images/exams/es-june-2025/q33.png',
    },
    {
      number: 34,
      part: 'A',
      text: 'Hornfels is commonly formed when existing rock is changed due to',
      choices: [
        'regional metamorphism of bituminous coal',
        'contact with rising magma from tectonic activity',
        'foliation from the pressure of overlying rock layers',
        'seismic activity along a fault in Earth\'s crust',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      image: '/images/exams/es-june-2025/q34.png',
    },
    {
      number: 35,
      part: 'A',
      text: 'A diagram represents a stream entering a lake. Letters A and D are in the lake, letters B and C are in the stream. At which two locations in the stream will the greatest amount of deposition be occurring?',
      choices: [
        'A and B',
        'B and C',
        'C and D',
        'D and A',
      ],
      topic: 'Geology',
      correct: 2,
      image: '/images/exams/es-june-2025/q35.png',
    },
    {
      number: 36,
      part: 'B-1',
      text: 'A diagram represents Earth orbiting the Sun with positions labeled A, B, C, and D, showing aphelion (152 million km) and perihelion (147 million km). Approximately how many days does Earth take to move from position A to position D?',
      choices: [
        '91 days',
        '183 days',
        '274 days',
        '365 days',
      ],
      topic: 'Astronomy',
      correct: 2,
    },
    {
      number: 37,
      part: 'B-1',
      text: 'Using the same Earth orbit diagram showing position A at perihelion with location X marked on Earth, which latitude on Earth is represented by location X?',
      choices: [
        'Tropic of Cancer',
        'Tropic of Capricorn',
        'Arctic Circle',
        'Antarctic Circle',
      ],
      topic: 'Climate',
      correct: 2,
    },
    {
      number: 38,
      part: 'B-1',
      text: 'If the tilt of Earth\'s axis were increased from 23.5° to 31°, the Northern Hemisphere summer would become',
      choices: [
        'warmer and winter would become warmer',
        'warmer and winter would become cooler',
        'cooler and winter would become cooler',
        'cooler and winter would become warmer',
      ],
      topic: 'General Review',
      correct: 1,
    },
    {
      number: 39,
      part: 'B-1',
      text: 'The Dead Sea is the lowest point on Earth\'s surface and is 10 times saltier than the ocean. Small amounts of dissolved minerals are transported in and left behind when water evaporates. Which mineral is most commonly found on the shores of the Dead Sea?',
      choices: [
        'halite',
        'hematite',
        'quartz',
        'talc',
      ],
      topic: 'Geology',
      correct: 0,
      image: '/images/exams/es-june-2025/q39.png',
    },
    {
      number: 40,
      part: 'B-1',
      text: 'A map shows the tectonic plate boundary located at the Dead Sea, between the Sinai Sub-plate and the Arabian Plate. Which type of tectonic plate boundary is found where the Dead Sea is located?',
      choices: [
        'complex or uncertain',
        'convergent',
        'divergent',
        'transform',
      ],
      topic: 'Plate Tectonics',
      correct: 3,
      image: '/images/exams/es-june-2025/q40.png',
    },
    {
      number: 41,
      part: 'B-1',
      text: 'A seismogram and data table show: P-wave arrival at 02:30:00 p.m., S-wave arrival at 02:34:00 p.m., distance to epicenter 2600 km. At what time did this earthquake occur?',
      choices: [
        '02:21:00 p.m.',
        '02:25:00 p.m.',
        '02:26:00 p.m.',
        '02:35:00 p.m.',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      image: '/images/exams/es-june-2025/q42.png',
    },
    {
      number: 42,
      part: 'B-1',
      text: 'Using the same earthquake data (epicenter 2600 km away, P-wave at 02:30:00 p.m.), which seismogram shows P and S waves arriving closest together (smallest time difference between P and S waves), indicating it was recorded closest to the epicenter?',
      choices: [
        'Seismogram with P and S waves very close together',
        'Seismogram with P and S waves slightly separated',
        'Seismogram with P and S waves moderately separated',
        'Seismogram with P and S waves widely separated',
      ],
      topic: 'Plate Tectonics',
      correct: 0,
      image: '/images/exams/es-june-2025/q42.png',
    },
    {
      number: 43,
      part: 'B-1',
      text: 'A graph shows the evolution of brachiopods (Orthida, Rhynchonellida, Spiriferida, Terebratulida) from the early Cambrian to the present. What does this graph indicate about the history of the Orthida group?',
      choices: [
        'They existed for the longest period of geologic time.',
        'Some types in the Orthida group still exist today.',
        'More types lived during the Silurian period than the Ordovician period.',
        'Many types have lived in the past and are now extinct.',
      ],
      topic: 'Geologic Time',
      correct: 3,
    },
    {
      number: 44,
      part: 'B-1',
      text: 'Using the brachiopod evolution graph, which two other fossil groups found in New York State first appeared on Earth during the same geologic time period that the Orthida Brachiopod group first appeared?',
      choices: [
        'trilobites and ammonoids',
        'trilobites and gastropods',
        'eurypterids and ammonoids',
        'eurypterids and gastropods',
      ],
      topic: 'Geologic Time',
      correct: 1,
    },
    {
      number: 45,
      part: 'B-1',
      text: 'Using the brachiopod evolution graph, which brachiopod group had the greatest number of types of organisms existing at the time of existence of the New York State index fossil Platyceras?',
      choices: [
        'Orthida',
        'Rhynchonellida',
        'Spiriferida',
        'Terebratulida',
      ],
      topic: 'Geologic Time',
      correct: 2,
    },
    {
      number: 46,
      part: 'B-1',
      text: 'A contour map of the Big Island of Hawaii shows Kailua-Kona on the west side, Hilo on the east side, and the arrow representing prevailing winds blowing from the east. Compared to Kailua-Kona, the amount of rainfall received at Hilo is',
      choices: [
        'less due to Hilo being at a lower longitude',
        'less due to Hilo receiving winds containing less moisture',
        'greater due to Hilo being at a lower longitude',
        'greater due to Hilo receiving winds containing more moisture',
      ],
      topic: 'Maps',
      correct: 3,
    },
    {
      number: 47,
      part: 'B-1',
      text: 'After visible light is absorbed by the land surfaces of the Big Island of Hawaii, which form of long-wave electromagnetic energy is radiated?',
      choices: [
        'x rays',
        'ultraviolet',
        'infrared',
        'gamma rays',
      ],
      topic: 'Climate',
      correct: 2,
    },
    {
      number: 48,
      part: 'B-1',
      text: 'Compared to Puna (a coastal area on the Big Island of Hawaii), Mauna Loa has a cooler climate because Mauna Loa',
      choices: [
        'is farther from the ocean',
        'has a higher elevation',
        'is located in a different wind belt',
        'receives less insolation',
      ],
      topic: 'Climate',
      correct: 1,
    },
    {
      number: 49,
      part: 'B-1',
      text: 'A block diagram shows a portion of Earth\'s crust with: Area A (runoff), Area B (infiltration), Zone C (capillary action), Zone D (saturation), and the water table. An increase in yearly precipitation would most likely cause',
      choices: [
        'decreased erosion of soil at area A',
        'decreased infiltration of rainwater at area B',
        'increased groundwater in zone C, lowering the water table',
        'increased groundwater in zone D, raising the water table',
      ],
      topic: 'Water Cycle',
      correct: 3,
      image: '/images/exams/es-june-2025/q48.png',
    },
    {
      number: 50,
      part: 'B-1',
      text: 'Using the same water cycle block diagram, process X (shown above area B) represents',
      choices: [
        'transpiration',
        'precipitation',
        'condensation',
        'radiation',
      ],
      topic: 'Water Cycle',
      correct: 0,
      image: '/images/exams/es-june-2025/q48.png',
    },
  ],
}
