// Life Science: Biology Regents — August 2025
export default {
  id: 'ls-aug-2025',
  subject: 'life-science',
  year: 2025,
  session: 'August',
  totalMinutes: 180,
  questions: [
    {
      number: 2,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Maple trees produce sap that circulates sugar, water, and other molecules throughout the plant. Root hairs are single-celled structures that exchange oxygen and carbon dioxide in soil air pockets and absorb water from soil.',
      text: 'Which statement best explains why the function of sap and root hairs is necessary for the functioning of plant cells to maintain homeostasis?',
      choices: [
        'Cellular respiration occurs only in root cells since the sap only travels to those cells.',
        'The sugar in the sap combines with carbon dioxide to form new sugars for the root cells.',
        'Sap and root hairs contribute to the transport of materials necessary for the plant cells to carry out cellular respiration.',
        'Sap and root hairs contain the raw materials required for the root cells to carry out photosynthesis.',
      ],
      correct: 2,
      explanation: 'Sap transports sugars and water to all plant cells; root hairs absorb water and exchange gases. Together they deliver glucose and oxygen — the raw materials for cellular respiration — to all cells, enabling ATP production and homeostasis.',
      diveDeep: 'Cellular respiration requires glucose (transported via phloem in sap) and oxygen (absorbed by root hairs from soil air pockets). ATP produced by respiration powers all cellular functions, maintaining homeostasis. Choice A is wrong because sap travels throughout the entire plant (via phloem), not just to root cells. Choice B is wrong because sugar + CO₂ is not a biological reaction — photosynthesis uses CO₂ + H₂O + light to MAKE sugar. Choice D is wrong because photosynthesis occurs in leaves (with chloroplasts), not in root cells (which lack chloroplasts). Root cells rely on cellular respiration, not photosynthesis. The vascular system (xylem: water/minerals upward; phloem: sugars throughout) is a key transport system ensuring all cells get the materials they need.', image: '/images/exams/ls-aug-2025/context_1_4.png' },
    {
      number: 3,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Past maple syrup production (1950-1999) shows high production at latitudes 44-48°N (Canada/northern US). Future projections (2090-2099) show production shifting northward with reduced/eliminated production at lower latitudes.',
      text: 'Which statement provides evidence to explain how the changing climate will affect maple trees and syrup production in the future?',
      choices: [
        'The optimal areas for maple syrup production will shift northward where temperatures are cooler.',
        'The optimal areas where maple syrup was produced from 1950 to 1999 will stay the same in the future.',
        'Future maple syrup production will mainly occur in latitudes between 38 and 42 degrees, since maple trees will be more successful in that range.',
        'Maple trees will not survive in northern areas in the future, therefore maple syrup production will stop.',
      ],
      correct: 0,
      explanation: 'The maps show production zones shifting to higher latitudes (northward/cooler regions) in 2090-2099 compared to 1950-1999. Rising temperatures make currently optimal areas too warm, pushing ideal maple conditions north.',
      diveDeep: 'Species range shifts are a documented response to climate change. Sugar maples require cold winters and specific freeze-thaw cycles to produce sap. As temperatures rise, these conditions shift northward to cooler latitudes. The maps clearly show the production zone moving from latitudes 40-48°N (1950-1999) to latitudes 44-50°N+ (2090-2099). Choice B is wrong because the maps directly show the zones changing — this contradicts the data. Choice C is wrong because latitudes 38-42° are expected to become too warm for optimal maple production — the trend shows northern shift, not southward. Choice D is wrong because maple trees can adapt their range northward — the maps show production continuing in northern areas, just shifting. Climate-induced range shifts affect agriculture, biodiversity, and ecosystem services.', image: '/images/exams/ls-aug-2025/context_1_4.png' },
    {
      number: 5,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Bluefin tuna release millions of eggs and sperm simultaneously. Only 2 out of every 30 million fertilized eggs reach adulthood. Young tuna practice cannibalism in nutrient-poor spawning waters, then travel in schools once large enough.',
      text: 'Which piece of evidence best supports how the tuna\'s spawning behavior provides a survival advantage?',
      choices: [
        'If a pathogen infects some of the fish in the school during spawning, then others will most likely become infected.',
        'Due to the large number of fish, the school must move from one area to another because food quickly runs out.',
        'It is more likely that many offspring will be hatched, increasing the likelihood that some will reproduce.',
        'If there are many fish in one area, wastes accumulate more quickly, and oxygen levels decrease.',
      ],
      correct: 2,
      explanation: 'Releasing millions of eggs and sperm simultaneously ensures many fertilized eggs, dramatically increasing the probability that at least some offspring survive to adulthood and reproduce — an r-selected reproductive strategy.',
      diveDeep: 'This r-selection strategy involves: high numbers of offspring, low parental investment per offspring, high mortality rate, but statistical guarantee that some survive to reproduce. With 30 million fertilized eggs producing only 2 adults, survival is extremely low (0.0000067%). But the sheer number of initial eggs ensures that 2 adults per reproductive pair is reliably achieved — enough to maintain the population. Choices A, B, and D all describe DISADVANTAGES of schooling/spawning (pathogen spread, resource depletion, oxygen depletion) — they would argue against the behavior providing an advantage. Choice C correctly identifies the survival advantage: statistical inevitability that some offspring survive due to sheer numbers. Compare to K-selection (humans): few offspring, high parental investment, high survival rate per individual.',
    },
    {
      number: 7,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Survivorship curves: Curve A (dashed) — stays high until old age, then drops sharply. Curve B (solid diagonal) — constant death rate throughout life. Curve C (dash-dot) — sharp decline early in life, low survivors by adulthood. Bluefin tuna: only 2 of 30 million fertilized eggs reach adulthood.',
      text: 'A student claimed that C best represents the survivorship curve of a bluefin tuna. Which factor explains this claim?',
      choices: [
        'Millions of eggs and sperm are released at the same time in the same area of the ocean.',
        'An extremely small number of the young that hatch survive to adulthood.',
        'The young migrate to a different region of the ocean upon reaching a certain size.',
        'Because they practice cannibalism, approximately half of the young reach adulthood.',
      ],
      correct: 1,
      explanation: 'Curve C shows high mortality in early life — the sharp drop indicates most individuals die young. Bluefin tuna exemplify this: out of 30 million fertilized eggs, only 2 reach adulthood, meaning 99.9999933% die early in life.',
      diveDeep: 'Three survivorship curve types: Type I (Curve A) = most individuals survive to old age (humans, elephants, K-selected). Type II (Curve B) = constant death rate at all ages (birds, squirrels). Type III (Curve C) = high early mortality, survivors live long (oysters, fish, sea turtles, r-selected species). Bluefin tuna fit Type III perfectly: only 2 of 30 million eggs = 99.9999% die early. This is the definition of Curve C\'s early sharp decline. Choice A is wrong because large simultaneous spawning describes the reproductive strategy, not the survival pattern over time. Choice C is wrong because migration is a behavior, not directly related to the survivorship shape. Choice D is wrong because cannibalism doesn\'t result in approximately half surviving — it\'s one of MANY factors contributing to extreme early mortality. The survivorship curve shape tells us when in life death is most likely to occur.',
    },
    {
      number: 10,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'In the 1800s, unregulated hunting reduced bison herds from tens of millions to fewer than 1,000 individuals. Conservation efforts since have helped populations recover to about 200,000 today.',
      text: 'In the 1800s, unregulated hunting reduced bison herds from tens of millions of individuals to fewer than 1,000. How might the DNA of the modern bison populations compare with the DNA of ancestral populations prior to the 1800s?',
      choices: [
        'Modern bison have more genetic diversity than their ancestors as a result of an increase in available mates.',
        'Modern bison have less genetic diversity than the population before the 1800s did as a result of increased random mutations.',
        'The DNA of the modern bison is identical to that of bison living before the 1800s because they all evolved from the same common ancestor.',
        'The DNA of modern bison shows less genetic diversity compared to their ancestors due to the limited genetic variation remaining in their population.',
      ],
      correct: 3,
      explanation: 'The bottleneck effect: reducing millions of bison to <1,000 eliminated most genetic variation. Only the alleles present in those ~1,000 survivors exist in modern populations. Less diversity = less ability to adapt to environmental changes.',
      diveDeep: 'Genetic bottleneck: a dramatic population reduction that eliminates most genetic variation by chance. The surviving ~1,000 bison represented only a tiny fraction of the original genetic diversity — many alleles were simply lost because no individual carrying those alleles survived the hunting. Modern bison populations, even after recovering numerically to ~200,000, have less genetic diversity than the original millions because they all descend from those ~1,000 survivors. Consequences: reduced ability to adapt to new diseases, environmental changes, or parasites. Choice A is wrong — more mates doesn\'t increase genetic diversity if all mates come from the same limited gene pool. Choice B is wrong — random mutations arise slowly and couldn\'t compensate for the massive diversity loss; mutations are also not the primary source of genetic variation for this timescale. Choice C is wrong — all organisms share common ancestry, but that doesn\'t make their DNA identical. Bottleneck ≠ identical DNA to ancestors.',
    },
    {
      number: 11,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Silkworm metabolic pathways: macromolecules from mulberry plant (polysaccharides, disaccharides, lipids) → subunits → glucose → ATP. Glucose + nitrogen → amino acid subunits → worm-specific proteins. Lipid subunits → worm-specific lipids.',
      text: 'Based on information in the model, which statement describes the chemical process by which the energy in glucose from the mulberry plant is converted and made available to the silkworm?',
      choices: [
        'Cellular respiration within the cells of the silkworm breaks the bonds of glucose to release energy that can be used to produce ATP, a usable source of cellular energy.',
        'Cellular respiration within the cells of the mulberry tree breaks the bonds of glucose to release amino acids, a usable source of cellular energy.',
        'Digestion within the cells of the silkworm breaks the bonds of glucose to release amino acids that can be used to build ATP for energy.',
        'Digestion within the cells of the mulberry tree breaks the bonds of glucose to release elements that can be used to build lipids for energy.',
      ],
      correct: 0,
      explanation: 'Cellular respiration in silkworm cells breaks glucose bonds, releasing energy stored in ATP — the universal cellular energy currency. The model shows glucose → ATP as the energy conversion pathway.',
      diveDeep: 'Cellular respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. It occurs in the silkworm\'s cells (mitochondria), not in the mulberry tree. Key distinctions: Cellular respiration = energy extraction from glucose → ATP production. Digestion = mechanical/chemical breakdown of food → absorbable nutrients. ATP is the energy currency, not amino acids. Choice B is wrong because cellular respiration occurs in the silkworm cells, not in the mulberry tree (the glucose came FROM the tree, but it\'s broken down IN the worm). Choice C is wrong because cellular respiration (not digestion) produces ATP, and amino acids are not used to build ATP — ATP is built from adenosine + phosphate groups. Choice D is wrong because lipids provide energy but aren\'t ATP; and again, the process occurs in the worm, not the tree. The model explicitly shows: macromolecules → glucose → ATP.', image: '/images/exams/ls-aug-2025/context_11_14.png' },
    {
      number: 13,
      part: 'A',
      topic: 'Human Body Systems',
      context: 'Silkworm moth antenna model: scent molecules from mulberry leaves → enter pores in antenna outer skin → detected by receptor-nerve endings → signal sent via nerve to brain. The worm then eats the leaves, using digestive system to metabolize nutrients.',
      text: 'Which statement best describes how the organization and interactions of two systems present within the silkworm moth enables it to find and use mulberry leaves as their source of nutrients?',
      choices: [
        'Special receptors in the nervous system of the silkworm pick up the scent of the mulberry leaves and send messages to the muscular system to spin a silk cocoon.',
        'Receptors in the nervous system within the antennae pick up scent molecules from mulberry leaves. The silkworm is able to find and eat the leaves, using the digestive system to break down the nutrient molecules into a usable form.',
        'The nervous system of the silkworm sends messages to the digestive system to begin to break down the fats that are taken in to produce new muscle tissue for movement.',
        'The muscular system sends messages to the nervous system to receive scent messages from the mulberry leaves.',
      ],
      correct: 1,
      explanation: 'Nervous system receptors in antennae detect mulberry scent → silkworm locates and eats leaves → digestive system breaks down macromolecules into usable nutrients. These two systems interact to enable feeding behavior.',
      diveDeep: 'Two-system interaction: Nervous system (detection/coordination) + Digestive system (nutrient processing). Step 1: Scent molecules from mulberry → antenna receptors (nervous system) → nerve signals → brain → behavior (move toward leaves). Step 2: Silkworm eats leaves → digestive system breaks down starch, proteins, lipids into glucose, amino acids, fatty acids → absorbed and used for cellular respiration and biosynthesis. Choice A is wrong because spinning silk cocoons is a later life stage (adult moth, not larva feeding), and the muscular system doesn\'t initiate silk spinning. Choice C is wrong because the digestive system doesn\'t receive messages from the nervous system to break down fats specifically for muscle tissue — this reverses the actual pathway and mixes functions. Choice D reverses the systems — muscular system doesn\'t send messages to nervous system to detect scent. Scent detection is initiated by the nervous system, not muscles.', image: '/images/exams/ls-aug-2025/context_11_14.png' },
    {
      number: 15,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Two graphs: Global Ivory Sales (1977-2015) show increase from ~100 to ~400 records/unit by 1989, then sharp drop to ~50 by 1993, then gradual rise again. African Elephant Population: early 1900s ~10 million, 1979 ~1 million, 1989 ~0.5 million, 2007 ~0.5 million, 2016 ~0.5 million.',
      text: 'Researchers claimed that elephants were being poached for their tusks, which are composed of ivory. Based on data provided in the graphs, which statement best explains this claim?',
      choices: [
        'Between 1977 and 2016, both graphs show a similar trend.',
        'Between 1977 and 1989, ivory sales increased, and African elephant population size decreased.',
        'Between 1980 and 2007, predators stopped preying on elephants, and the African elephant population size increased.',
        'Between 1979 and 1990, it was illegal to hunt elephants.',
      ],
      correct: 1,
      explanation: 'From 1977-1989, ivory sales surged from ~100 to ~400 records/unit while elephant populations plummeted. This inverse correlation supports the claim that high ivory demand drove poaching, causing population collapse.',
      diveDeep: 'Scientific evidence for a claim requires data showing a pattern consistent with the hypothesis. If poaching drives population decline, we expect: more ivory sales → fewer elephants (inverse correlation). The data confirms: 1977-1989, ivory sales ↑ 400% while elephant population ↓ from ~1 million to ~0.5 million. This correlation (not proof, but strong evidence) supports the poaching claim. Choice A is wrong because the graphs don\'t show the SAME trend — ivory sales and population show OPPOSITE trends (one up, one down). Choice C is wrong because it introduces predators — no data on predation is provided, and elephants don\'t have significant natural predators as adults. Choice D makes a legal claim not supported by the graphs. The graphs show 1989 ivory sales peaked then crashed — this coincides with the 1989 CITES ivory ban, which caused the sales decline. Before the ban, high sales correlated with population decline.', image: '/images/exams/ls-aug-2025/context_15_19.png' },
    {
      number: 16,
      part: 'A',
      topic: 'Genetics & Heredity',
      context: 'Tusklessness data: 1969: 10.5% tuskless; 1972: 12.2%; 1988: 32.6%; 1989: 38.2%; 1990: 34.9%; 1991: 33.3%; 1992: 30.2%; 1993: 27.7%. Heavy poaching of tusked elephants occurred through the late 1980s.',
      text: 'Which statement best describes a trend in tusklessness represented in the data table?',
      choices: [
        'From 1988 to 1991 the frequency of tusklessness decreased.',
        'From 1969 to 1989 the frequency of tusklessness increased.',
        'From 1969 to 1993 the total number of tuskless females remained constant.',
        'From 1989 to 1991 the total number of tuskless females increased.',
      ],
      correct: 1,
      explanation: 'Tusklessness frequency increased from 10.5% (1969) to 38.2% (1989) — nearly a fourfold increase over 20 years. This is a clear increasing trend driven by selective poaching of tusked elephants.',
      diveDeep: 'Reading data tables carefully: Tusklessness % from 1969-1989: 10.5% → 12.2% → (gap) → 32.6% → 38.2% — consistently increasing. This is artificial selection: poachers selectively killing tusked elephants created selection pressure favoring tusklessness. Tuskless females survived and reproduced at higher rates → tuskless allele increased in frequency. Choice A is wrong because from 1988 (32.6%) to 1991 (33.3%), tusklessness slightly INCREASED (not decreased). Choice C is wrong because total numbers of tuskless females changed (they increased substantially from 26 in 1969 to 63 in 1989, etc.). Choice D is wrong because from 1989 (63 tuskless) to 1990 (104 tuskless) to 1991 (57 tuskless) — numbers fluctuate; between 1989-1991 specifically, 63→57 = decreased total number (even though sample sizes differ). The percentage trend (1969-1989) is the clearest and most consistent pattern in the data.', image: '/images/exams/ls-aug-2025/context_15_19.png' },
    {
      number: 17,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'Tusklessness in African elephants is caused by a dominant allele, lethal to male offspring. Heavy poaching of tusked elephants from the 1970s-1990s selected for tuskless females. Tusklessness frequency rose from ~10% in 1969 to ~38% by 1989.',
      text: 'Which statement about how humans affected the elephant population is supported by the evidence provided?',
      choices: [
        'The decrease in global ivory sales resulted in a decrease in tuskless male elephants.',
        'The chance of producing tuskless males increased as a result of the tighter enforcement on poachers.',
        'Poaching has led to an increase in the tuskless trait among female elephants.',
        'The demand for ivory has led to a decrease in the number of tuskless female elephants producing offspring.',
      ],
      correct: 2,
      explanation: 'Poachers selectively killed tusked elephants for ivory, removing them from the breeding population. This artificial selection increased the frequency of tusklessness in females over time — documented in the data (10.5% → 38.2%).',
      diveDeep: 'Artificial/human-driven selection: poaching eliminated tusked elephants preferentially → tuskless females had higher survival and reproduction → tuskless allele frequency increased. This is a real-world example of rapid evolution driven by human hunting pressure. Choice A is wrong because tuskless MALES cannot exist — the tusklessness allele is lethal to males (X-linked lethal). So there are no tuskless males to decrease. Choice B is wrong for the same reason — tuskless males aren\'t possible with this allele. Choice D reverses the evidence — tuskless females increased (not decreased) because they survived poaching better than tusked females. Human activities as drivers of rapid evolution is a critical Regents theme: hunting, pesticide use, antibiotic use — all can rapidly change allele frequencies in populations.', image: '/images/exams/ls-aug-2025/context_15_19.png' },
    {
      number: 18,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Behavioral table: Tusked elephants can dig deep holes in compacted soil for water/minerals, eat fibrous/woody vegetation, use both tusks and trunk to knock down trees. Tuskless elephants mainly use existing holes, eat grasses and soft vegetation, can only use trunk to knock down trees.',
      text: 'Which statement identifies the claim, supported by evidence, that a shift to more tuskless elephants could disrupt the stability of the local ecosystem?',
      choices: [
        'The amount of grass available to other herbivores in the ecosystem would decrease.',
        'There would be more deep watering holes available within the ecosystem.',
        'The amount of living woody vegetation available to organisms in the ecosystem would decrease.',
        'Soil-dwelling organisms would be more vulnerable to predators, and their number would decline.',
      ],
      correct: 0,
      explanation: 'Tuskless elephants eat more grasses and soft vegetation (vs. tusked elephants eating woody vegetation). More tuskless elephants → more grass consumption → less grass available for other herbivores → ecosystem disruption.',
      diveDeep: 'Ecosystem stability depends on balanced resource consumption across species. Tusked elephants primarily eat fibrous and woody vegetation — leaving grasses relatively intact. Tuskless elephants shift to eating more grasses and soft vegetation. If more elephants are tuskless, grass consumption increases → grass becomes limiting → other herbivores (zebras, gazelles, etc.) face food scarcity → cascade effects through food web. Choice B is wrong because tuskless elephants mainly USE existing holes (not dig new ones) → fewer new holes would be dug → fewer deep watering holes, not more. Choice C is wrong because tuskless elephants eat LESS woody vegetation — so woody vegetation would actually increase if tusked elephants decline. Choice D is wrong because tuskless elephants knock down fewer trees (using trunk only), so soil disturbance from tree uprooting decreases — actually less soil exposure, not more.', image: '/images/exams/ls-aug-2025/context_15_19.png' },
    {
      number: 20,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Four models showing phytoplankton and arrows. Model 1: CO₂ and water enter phytoplankton, glucose and oxygen exit (arrows going outward from phytoplankton). Represents photosynthesis with correct directionality.',
      text: 'Which model below best identifies how phytoplankton cycle carbon between two of Earth\'s spheres?',
      choices: [
        'CO₂ and water enter phytoplankton, glucose and oxygen exit (photosynthesis: hydrosphere/atmosphere → biosphere)',
        'Glucose and oxygen enter phytoplankton, CO₂ and water exit (respiration)',
        'CO₂ and water exit phytoplankton, glucose and oxygen enter',
        'Glucose and oxygen exit phytoplankton, CO₂ and water enter (alternative respiration)',
      ],
      correct: 0,
      explanation: 'Phytoplankton perform photosynthesis: CO₂ and water (from atmosphere/hydrosphere) enter and are converted to glucose and oxygen (released to hydrosphere/atmosphere). This cycles carbon from the atmosphere/hydrosphere (abiotic) into the biosphere (living phytoplankton).',
      diveDeep: 'Carbon cycling between Earth\'s spheres: Atmosphere/Hydrosphere (CO₂ dissolved in seawater) → Biosphere (phytoplankton cells, organic carbon in glucose). Photosynthesis: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. The arrow direction matters: reactants ENTER the organism, products EXIT. CO₂ and water enter (consumed) → glucose and oxygen exit (produced). This moves carbon from the abiotic (atmosphere/hydrosphere) into the biotic (biosphere). The other models show cellular respiration (reverse: glucose + O₂ enter, CO₂ + H₂O exit) or incorrect arrow directions. Phytoplankton are responsible for ~50% of global photosynthesis, making them crucial for carbon cycling between spheres. On the Regents, arrow direction in process models must be carefully evaluated.', image: '/images/exams/ls-aug-2025/q20.png' },
    {
      number: 23,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Krill fecal pellets drop to the ocean floor and remain there for many years. Krill contribute to removing up to 12 billion tons of carbon from the atmosphere each year. A carbon sink absorbs more carbon than it releases.',
      text: 'A carbon sink is anything that absorbs more carbon from the environment than it releases. Which process carried out by krill results in the accumulation and storage of carbon for a period of time?',
      choices: [
        'Photosynthesis in the atmosphere releases carbon to the atmosphere.',
        'Respiration in the geosphere releases carbon wastes into the atmosphere.',
        'Elimination of wastes in the hydrosphere stores carbon on the ocean floor.',
        'Acidification in the biosphere stores carbon in the bodies of organisms.',
      ],
      correct: 2,
      explanation: 'Krill excrete fecal pellets (containing carbon from eaten phytoplankton) that sink to the ocean floor and remain there for many years — a carbon sink in the hydrosphere/geosphere. This long-term storage prevents carbon from returning to the atmosphere.',
      diveDeep: 'The biological carbon pump: phytoplankton absorb CO₂ → krill eat phytoplankton → krill produce carbon-rich fecal pellets that sink (marine snow) → pellets accumulate on ocean floor for years → carbon sequestered away from atmosphere. This is the hydrosphere (ocean) as a long-term carbon sink. Choice A is wrong because photosynthesis doesn\'t occur in the atmosphere, and krill don\'t photosynthesize. Choice B is wrong because respiration releases CO₂ (not stores it), and it occurs in the biosphere (krill cells), not the geosphere. Choice D is wrong because acidification is a chemical process (CO₂ + H₂O → carbonic acid), not a carbon storage mechanism in organisms. The key Regents concept: fecal pellets = biological carbon export from surface to deep ocean = carbon sink function of marine food webs.',
    },
    {
      number: 24,
      part: 'A',
      topic: 'Genetics & Heredity',
      context: 'KRT1 gene DNA sequence: TAC AGA GGA GTG TTT AGC TCC TTC (codes for keratin in skin). KRT12 gene DNA sequence: TAC TTC AAT CCC TAT TGT CTG TTC (codes for keratin in cornea of eye). These different sequences produce different keratin proteins with different locations and functions.',
      text: 'Which statement best provides evidence that supports the explanation that the sequence of DNA determines proteins?',
      choices: [
        'The structure of KRT1 and KRT12 mRNA determines the DNA code that is translated to produce a specific protein with a specific shape, which determines its function.',
        'The structure of the KRT1 and KRT12 genes determines the genetic information present in protein that determines the function of each DNA molecule.',
        'The DNA that codes for KRT1 and KRT12 is different, resulting in different protein structures with different functions.',
        'The structure of each protein determines the order of bases in DNA. The KRT1 and KRT12 proteins are different, resulting in different functions.',
      ],
      correct: 2,
      explanation: 'KRT1 and KRT12 have different DNA sequences → different mRNA → different amino acid sequences → different protein structures → different functions (skin vs. cornea). DNA sequence directly determines protein identity and function.',
      diveDeep: 'Central dogma: DNA sequence → mRNA sequence → amino acid sequence → protein structure → protein function. KRT1 DNA ≠ KRT12 DNA → different mRNAs → different amino acids → different 3D protein shapes → different biological functions (skin keratin vs. corneal keratin). This is the fundamental evidence that DNA sequence determines protein. Choice A reverses the relationship: mRNA doesn\'t determine DNA code — DNA is transcribed INTO mRNA, not the other way. The sequence of information flow: DNA → RNA → protein (not RNA → DNA → protein). Choice B incorrectly states proteins determine DNA function — proteins don\'t determine their own DNA. Choice D also reverses the causality: proteins don\'t determine the order of DNA bases. Protein structure results FROM DNA sequence, not the other way around. Regents: students must know that DNA → protein, not protein → DNA.', image: '/images/exams/ls-aug-2025/context_24_28.png' },
    {
      number: 27,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Modified keratinocytes contain a properly functioning version of the keratin-producing gene (KRT10). These cells are transplanted into a patient with keratin disorder. Skin cells normally divide by mitosis throughout life for skin renewal.',
      text: 'Which claim best explains why only one generation of genetically modified keratinocytes must be genetically altered and transplanted into an individual in order for that individual to continue producing appropriate amounts of keratin?',
      choices: [
        'The lab-grown keratinocytes will undergo meiosis and pass the keratin DNA to future generations of skin cells.',
        'The modified cells will undergo mitosis and pass the functioning keratin gene on to future generations of skin cells.',
        'Only the modified skin cells will be able undergo mitosis, causing all body cells of the individual to produce appropriate levels of keratin.',
        'When the cells undergo meiosis, the DNA will be modified in future generations of skin cells to include only the genes for appropriate levels of keratin production.',
      ],
      correct: 1,
      explanation: 'The transplanted modified keratinocytes undergo mitosis, producing daughter cells with identical functioning keratin genes. These daughter cells also divide by mitosis, perpetuating the corrected gene through all subsequent generations of skin cells.',
      diveDeep: 'Mitosis produces genetically identical daughter cells. One transplanted modified keratinocyte → divides by mitosis → 2 identical daughter cells (each with functioning KRT10 gene) → each divides again → 4 cells → exponential proliferation, all with the corrected gene. This is why gene therapy with somatic cells can work long-term without repeated treatment. Choice A is wrong because skin cells (somatic cells) don\'t undergo meiosis — meiosis only occurs in gonads to produce gametes. If skin cells used meiosis, they would produce cells with half the chromosome number (23 instead of 46), which would be non-functional. Choice C is wrong because modified skin cells don\'t influence other body cells — each cell type maintains its own gene expression independently. Keratinocytes don\'t signal liver cells to produce keratin. Choice D is wrong because meiosis doesn\'t occur in skin cells (same error as A).', image: '/images/exams/ls-aug-2025/context_24_28.png' },
    {
      number: 28,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'Crocodile scales, cat claws, and dog/cat fur are all composed of keratin, but the keratin in each structure is not identical and performs different functions. All three represent different modifications of the same ancestral protein.',
      text: 'Based on the evidence provided, which statement best explains the variation in keratin structure and function as represented by these organisms?',
      choices: [
        'These organisms needed different structures to survive in their environments. The DNA that codes for keratin changed to improve each of these organisms\' chance of survival.',
        'The gene responsible for the production of keratin in each organism had survivable changes to the DNA sequence, which were passed on to offspring.',
        'All of these organisms had ancestors that lived in the same environment and produced keratin that then mutated to produce different structures which were passed on to their offspring.',
        'Keratin most likely appeared first in crocodiles. The ancestors of the other organisms inherited the keratin gene from the crocodiles and modified it to adapt to their environment.',
      ],
      correct: 1,
      explanation: 'Random mutations in keratin-coding genes produced slightly different keratin proteins in different lineages. Those variations that were beneficial (or at least not harmful) were passed to offspring and became the characteristic keratin of each species.',
      diveDeep: 'Evolution of protein diversity: a single ancestral keratin gene underwent random mutations over millions of years in different lineages. Mutations that produced better scales in reptiles, better claws in cats, or better fur in mammals were selected for. These survivable changes accumulated and were inherited. This is divergent evolution from a common ancestor. Choice A implies organisms needed changes and DNA "changed to improve" survival — this is Lamarckian thinking (directed evolution). Mutations are random, not directed toward a goal. Choice C is not supported — these organisms don\'t share recent common environments (crocodiles are reptiles, cats are mammals — different habitats and evolutionary histories). Choice D incorrectly implies inheritance of the keratin gene from crocodiles to mammals — horizontal gene transfer doesn\'t work this way between such distantly related animals. The correct explanation: random mutations + natural selection of survivable variants + vertical inheritance.', image: '/images/exams/ls-aug-2025/context_24_28.png' },
    {
      number: 30,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'Comparison of nephron loop length: Beaver (short loop, fresh water, maximal urine concentration 520 milliosmoles/L, ratio 1.7:1). Human (medium loop, land with moderate moisture, 1400 mOsm/L, 4.5:1). Kangaroo rat (longest loop, desert with low moisture, 5500 mOsm/L, 16.0:1).',
      text: 'Which explanation, based on the evidence provided, supports the claim that natural selection leads to the adaptations that control water regulation in specific environments?',
      choices: [
        'The shorter nephron loop in humans produces urine with the lowest urine:blood plasma ratio.',
        'The kangaroo rat has a long nephron loop and produces urine with the highest urine:blood plasma ratio.',
        'There is no relationship between the nephron length and maximal urine concentration.',
        'Mammalian kidneys have nephron loops that are the same length regardless of their environment.',
      ],
      correct: 1,
      explanation: 'The kangaroo rat has the longest nephron loop AND the highest urine concentration (5500 mOsm/L, 16:1 ratio) — consistent with living in the driest environment. This correlation between nephron length and urine concentration demonstrates natural selection adapting kidney structure to water-scarce environments.',
      diveDeep: 'Evidence-based natural selection: environment (water availability) correlates with nephron structure (loop length) and function (urine concentration). Pattern: least water available → longest loop → most concentrated urine. Beaver (freshwater, abundant water) → short loop → dilute urine. Human (moderate moisture) → medium loop → moderately concentrated urine. Kangaroo rat (desert, minimal water) → longest loop → most concentrated urine. Natural selection: kangaroo rats with longer loops produced more concentrated urine → retained more water → survived better in desert → passed longer-loop genes to offspring. Choice A is wrong because humans DON\'T have the shortest loop — beavers do. Choice C is wrong because the data clearly shows a relationship (longer loop = more concentrated urine). Choice D is wrong because the diagram explicitly shows different loop lengths in different species adapted to different environments.', image: '/images/exams/ls-aug-2025/context_29_32.png' },
    {
      number: 31,
      part: 'A',
      topic: 'Human Body Systems',
      context: 'Kangaroo rat escape maneuver: detects rattlesnake strike using hearing, vision, or sensing ground vibrations → initiates escape response → launches itself into air. 81% of snake strikes accurate; 78% of time kangaroo rats evaded a lethal bite.',
      text: 'Which statement best describes an interaction that occurs between body systems during the kangaroo rat\'s lightning-quick maneuver?',
      choices: [
        'The respiratory and nervous systems interact when sending a signal to the spinal cord to leap.',
        'The circulatory and nervous systems interact when sending a signal to the leg muscles.',
        'The respiratory and muscular systems interact to slow cellular respiration prior to the muscle contraction.',
        'The nervous and muscular systems interact to trigger the leg muscle to contract.',
      ],
      correct: 3,
      explanation: 'The escape maneuver requires: nervous system detects threat → sends nerve impulses → muscular system (leg muscles) contracts → kangaroo rat leaps. This is the fundamental nervous system-muscular system interaction for all voluntary movement.',
      diveDeep: 'Escape response pathway: Sensory input (hearing/vibration/vision) → sensory neurons → brain/spinal cord processing → motor neurons → neuromuscular junction → muscle fiber contraction → leg extends → leap. The nervous system is the command center; the muscular system is the effector. This is the core interaction for all animal movement. Choice A is wrong because the respiratory system is not directly involved in sending neural signals to muscles. Respiration provides oxygen but doesn\'t transmit movement signals. Choice B is partially correct (circulatory delivers oxygen), but the circulatory system doesn\'t send SIGNALS to muscles — that\'s the nervous system\'s role. Choice C is wrong because cellular respiration increases (not slows) before intense muscle contraction — more ATP is needed for the burst of activity, requiring more respiration. Key concept: nervous system (signal transmission) + muscular system (force generation) = coordinated movement.', image: '/images/exams/ls-aug-2025/context_29_32.png' },
    {
      number: 33,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'Fossil skeletons of ancestral whales: Pakicetus (55 mya, terrestrial, 4-legged), Rodhocetus (47 mya, predominantly aquatic, reduced hind limbs), Dorudon (40 mya, fully aquatic, vestigial pelvis/back leg), Balaena (present day, fully aquatic, no visible hind limbs).',
      text: 'Which statement includes scientific information that best explains how modern whales may have descended from land-living mammals?',
      choices: [
        'Early ancestors of whales became more adapted to live on land, due to their paddle-like feet.',
        'The total number of whale species with a non-functional pelvis increased on land and in water.',
        'Ancestors of modern whales had leg and pelvic bones, which are present in more modern whales.',
        'Some ancestral whales learned aquatic behaviors that could be passed on to offspring.',
      ],
      correct: 2,
      explanation: 'Fossil evidence shows transitional forms: Pakicetus (four functional legs) → Rodhocetus (reduced hind limbs) → Dorudon (non-functional pelvis/back leg vestigial structures) → Balaena (modern whale). Persistent pelvic/leg bones in modern whales are homologous structures indicating land-dwelling ancestry.',
      diveDeep: 'Vestigial structures are remnants of ancestral traits that have been reduced or lost function. Modern whales retain small pelvic bones embedded in their bodies — no longer connected to limb bones, serving no locomotor function, but evidence of ancestors who walked on land. Fossil sequence shows progressive limb reduction over ~25 million years. Choice A reverses the direction — ancestors were becoming more AQUATIC, not more terrestrial. Paddle-like feet (Rodhocetus) show aquatic adaptation. Choice B is confusing — the total number of species doesn\'t explain the evolutionary pathway. Choice D is Lamarckian — behaviors learned by individuals cannot be genetically passed to offspring. Genetic mutations in limb-development genes (Hox genes) caused limb reduction; individuals with better aquatic adaptations survived to reproduce. Fossil record + vestigial structures = strongest evidence for whale evolution from land mammals.', image: '/images/exams/ls-aug-2025/context_33_36.png' },
    {
      number: 34,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'Whale and shark have similar streamlined body shapes (fusiform) despite being genetically very different. Whales are mammals (descended from land-dwelling ancestors); sharks are cartilaginous fish (ancient aquatic lineage).',
      text: 'Based on evidence, which statement explains how whales and sharks have evolved to have similar body shapes?',
      choices: [
        'All aquatic organisms are closely related so they are likely to look the same.',
        'Marine mammals evolved directly from fish and therefore share many structural similarities.',
        'Whales and sharks possess identical genetic mutations in their genome which determine their similar body shape.',
        'The body shape of whales and sharks allows them to swim efficiently, which improves their chances of survival.',
      ],
      correct: 3,
      explanation: 'This is convergent evolution: whales (mammals) and sharks (fish) independently evolved similar streamlined body shapes because this form provides superior swimming efficiency. The same environmental pressure (aquatic locomotion) selected for the same solution in unrelated lineages.',
      diveDeep: 'Convergent evolution: unrelated species evolve similar traits due to similar selective pressures in similar environments. Both whales and sharks need to move efficiently through water → streamlined body reduces drag → better hunting/escape → higher survival → selected for. Despite having completely different DNA (sharks separated from mammalian lineage ~450 million years ago), the same environmental pressure produced similar shapes. Choice A is wrong because all aquatic organisms are NOT closely related — sharks (cartilaginous fish) and whales (mammals) are extremely distant relatives. Similar habitat ≠ close relationship. Choice B is wrong because mammals did NOT evolve directly from fish — the evolutionary tree shows: fish → amphibians → reptiles → mammals (terrestrial), then some mammals returned to the sea. Choice C is wrong because the mutations are NOT identical — convergent evolution achieves similar results through different genetic pathways. Whales and sharks have very different genomes.', image: '/images/exams/ls-aug-2025/context_33_36.png' },
    {
      number: 36,
      part: 'A',
      topic: 'Evolution & Natural Selection',
      context: 'Transposon locations in mammals: Whale (locations 1, 2, 3, 5), Camel (no shared transposons), Cow (locations 1, 2, 4), Hippopotamus (locations 1, 2, 3). Shared transposons indicate shared ancestry.',
      text: 'Which types of evidence would best demonstrate patterns that could be used to determine the evolutionary relationships between goats and the other organisms?',
      choices: [
        'Embryonic development, habitat, DNA sequences',
        'DNA sequences, location of transposons, skeletal structures',
        'Habitat, embryonic similarities, fossil record',
        'Leg bones, coloration, number of transposons',
      ],
      correct: 1,
      explanation: 'DNA sequences, transposon locations, and skeletal structures provide multiple lines of molecular and structural evidence for evolutionary relationships — all three are used in the table and diagrams shown. Habitat is not evidence of relatedness (convergent evolution).',
      diveDeep: 'Multiple lines of evidence for evolutionary relationships: (1) DNA sequences — similar base sequences indicate common ancestry (molecular evidence). (2) Location of transposons — randomly inserted DNA segments shared in the same location indicate inheritance from a common ancestor (powerful molecular clock). (3) Skeletal structures — homologous bones indicate structural common ancestry. Choice A is wrong because "habitat" is not evidence of evolutionary relationship — similar habitats cause convergent evolution, misleading relationship assessments. Dolphins (mammals) and sharks (fish) share habitat but are very distantly related. Choice C is wrong because habitat misleads (same reason), and while fossil record and embryonic similarities are useful, they are weaker than molecular evidence. Choice D is wrong because "coloration" can be due to convergent evolution (not shared ancestry), and "number of transposons" matters less than LOCATION (the specific positions, as shown in the table, indicate shared ancestry).', image: '/images/exams/ls-aug-2025/context_33_36.png' },
    {
      number: 37,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Process X: fertilization (Cell A = sperm + Cell B = egg → new single cell). Process Y: mitosis (new single cell → 2 cells → 4 cells → morula). Process Z: differentiation (ICM cells → nerve, liver, muscle, intestinal, cheek cells → fetus → adult).',
      text: 'Which statement explains why Process X is necessary to maintain the continuity of life?',
      choices: [
        'It results in a cell that contains all of the genetic material needed to form an embryo.',
        'It guarantees the survival of the offspring in any kind of environment.',
        'It produces offspring with only traits that are favorable for survival.',
        'It assures that each parent passes on identical genetic material to the offspring.',
      ],
      correct: 0,
      explanation: 'Fertilization (Process X) combines sperm (23 chromosomes) and egg (23 chromosomes) to form a zygote with the full complement of 46 chromosomes — all the genetic material needed to develop into a complete organism.',
      diveDeep: 'Fertilization is essential for sexual reproduction because it: (1) Restores the diploid chromosome number (haploid gametes → diploid zygote). (2) Combines genetic material from two parents → genetic diversity in offspring. (3) Produces a single cell (zygote) with all genetic instructions needed for complete development. Process X = fertilization = STARTING POINT for embryo development. Choice B is wrong because fertilization doesn\'t guarantee survival — environmental factors, competition, and chance determine survival. Choice C is wrong because fertilization combines random genetic material from both parents — not only favorable traits. Unfavorable alleles can also be inherited. Choice D is wrong because each parent passes DIFFERENT (not identical) genetic material. Parents contribute different gametes; sexual reproduction specifically creates diversity by combining different parental genomes. Identical genetic material would be asexual reproduction.',
    },
    {
      number: 38,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Diagrams showing cells with chromosome numbers: (1) 23 → 46+23; (2) 46 → 46+46; (3) 46 → 23+23; (4) 23 → 46+46. Process Y is mitosis, which produces cells with the same chromosome number as the parent cell.',
      text: 'Which diagram best summarizes how Process Y results in the typical number of chromosomes present in the nucleus of each human cell?',
      choices: [
        'A cell with 23 chromosomes divides to produce two cells, one with 46 and one with 23 chromosomes',
        'A cell with 46 chromosomes divides to produce two cells, each with 46 chromosomes',
        'A cell with 46 chromosomes divides to produce two cells, each with 23 chromosomes',
        'A cell with 23 chromosomes divides to produce two cells, each with 46 chromosomes',
      ],
      correct: 1,
      explanation: 'Mitosis (Process Y) produces two daughter cells with the same chromosome number as the parent cell. Human cells have 46 chromosomes, so mitosis: 46 → 46 + 46 (identical to parent). This maintains the diploid chromosome number in all body cells.',
      diveDeep: 'Mitosis vs. Meiosis chromosome numbers: MITOSIS: parent cell (diploid, 46) → DNA replication → cell division → 2 daughter cells (diploid, 46 each). Purpose: growth, repair, replacement. MEIOSIS: parent cell (diploid, 46) → DNA replication → 2 rounds of division → 4 daughter cells (haploid, 23 each). Purpose: gamete production. Process Y is mitosis (grows the embryo from 1 → 2 → 4 → many cells). Starting cell (zygote from fertilization) has 46 chromosomes. Each mitotic division must produce cells with 46 chromosomes to maintain normal development. Choice A is wrong because mitosis doesn\'t produce cells with different chromosome numbers (one with 46, one with 23). Choice C describes meiosis (46 → 23 + 23). Choice D is impossible — a cell with 23 chromosomes (haploid gamete) cannot produce cells with 46 chromosomes through mitosis alone (that would require fertilization).', image: '/images/exams/ls-aug-2025/q38.png' },
    {
      number: 40,
      part: 'A',
      topic: 'Cells & Cell Processes',
      context: 'Human development sequence: Morula → Blastocyst (ICM forms) → Process Z (differentiation) → nerve cells, liver cells, skeletal muscle cells, intestinal cells, cheek cells → Fetus → Adult. Process Y (mitosis) continues throughout life for growth and repair.',
      text: 'Which statement best summarizes the result of Process Y at all stages of human development, from the new single cell stage to the adult stage?',
      choices: [
        'Damaged genes are eliminated and favorable genes are passed on to the next generation of human cells.',
        'Cells are produced that can be used to produce offspring, which will increase the chance of the species surviving.',
        'The genetic variation between the cells of the developing organism is increased and new cell types are formed.',
        'The number of cells that make up the organism increases and the organism is capable of growth and repair.',
      ],
      correct: 3,
      explanation: 'Mitosis (Process Y) continuously produces new cells throughout life — increasing cell number for growth during development, and replacing damaged/worn cells for repair throughout adulthood. Both functions maintain the organism.',
      diveDeep: 'Mitosis functions: (1) GROWTH — zygote (1 cell) → infant → child → adult. More cells = larger organism. (2) REPAIR — replacing damaged cells (skin healing, liver regeneration, blood cell production). (3) MAINTENANCE — replacing cells with short lifespans (red blood cells live ~120 days, skin cells ~2-4 weeks). Process Y (mitosis) is NOT for: creating gametes (meiosis does that), increasing genetic variation (mitosis produces identical cells), or eliminating damaged genes. Choice A is wrong because mitosis doesn\'t selectively eliminate damaged genes — it copies DNA as-is, including mutations. DNA repair occurs separately before cell division. Choice B is wrong because mitosis doesn\'t produce gametes — gametes are produced by meiosis in reproductive organs. Choice C is wrong because mitosis produces genetically IDENTICAL cells (no increased genetic variation). Differentiation (Process Z) creates new cell types, not mitosis itself.',
    },
    {
      number: 42,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Florida panther: reduced from historical millions to 20-30 individuals by mid-1980s. Conservation efforts (1995: released 8 Texas female panthers) increased population to ~200 individuals today. Territory reduced from entire SE USA to small area in south Florida.',
      text: 'Which explanation regarding the Florida panther would best be supported by the evidence in the information provided?',
      choices: [
        'The average panther reproductive rate will increase in order to maintain the panther population.',
        'If their territory decreases because of housing developments, it will become easier for the males to find genetically diverse mates.',
        'Due to the size of the population, genetic variation is most likely low, decreasing the ability of the panther population to adapt to environmental changes.',
        'The panther population has rebounded and will most likely continue to rise, regardless of changes to their habitat.',
      ],
      correct: 2,
      explanation: 'The population bottleneck (20-30 individuals in the 1980s) severely reduced genetic diversity. Even with recovery to ~200, low genetic variation from the bottleneck limits adaptability to diseases, environmental changes, and new selective pressures.',
      diveDeep: 'Small population → genetic bottleneck → reduced genetic diversity → reduced adaptive capacity. With only 20-30 individuals as founders, only the alleles present in those few individuals exist in modern populations. Inbreeding (mating among close relatives due to small pool) further reduces diversity. The Texas panthers were introduced specifically to add new alleles and reverse inbreeding depression. Choice A is wrong because reproductive rate doesn\'t automatically increase to maintain population size — it depends on resources, health, and genetic fitness. Choice B is wrong because smaller territory means fewer potential mates (not more) and MORE restricted gene flow → less diversity, not more. Choice D is wrong because panther survival absolutely depends on habitat — loss of territory → less prey → less space for males → population decline. The evidence describes ongoing habitat threats as major concerns.', image: '/images/exams/ls-aug-2025/context_42_45.png' },
    {
      number: 43,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Balanced Florida ecosystem pyramid: Panthers (top) → Wild Hogs → Deer → Plants (base). If panthers go extinct, top predator is removed from the ecosystem suddenly.',
      text: 'Which pyramid of biomass would best represent the Florida ecosystem if the panthers went extinct, causing a sudden imbalance in the ecosystem?',
      choices: [
        'Plants (base, wide) → Deer → Wild Hogs (top, widest)',
        'Deer (top) → Plants → Wild Hogs (widest)',
        'Wild Hogs (top, widest) → Deer → Plants (base, narrow)',
        'Deer → Wild Hogs → Plants',
      ],
      correct: 2,
      explanation: 'Without panthers, wild hogs face no top predator control and their population explodes (widest at the level of wild hogs). However, increased hogs eat more vegetation, reducing plant biomass. The pyramid inverts at the hog level — wild hogs become the most abundant trophic level.',
      diveDeep: 'Trophic cascade from predator removal: Panthers control wild hog populations. Remove panthers → wild hogs increase dramatically (no predation) → hogs overgraze plants → plant biomass decreases. Resulting imbalanced pyramid: Wild Hogs (largest, no predation control) → Deer (still present but competing with hogs) → Plants (reduced by overgrazing). Normal pyramid: Plants > Deer > Wild Hogs > Panthers (energy decreases up the chain). Imbalanced pyramid has wild hogs bulging out of proportion. Choice A is wrong because without predation control on hogs, deer would NOT become the top trophic level. Choice B is wrong because plants wouldn\'t be in the middle of a pyramid — producers always form the base. Choice D doesn\'t make biological sense (deer can\'t be at the top of a food chain without plants at the base). The key concept: removing a top predator causes population explosion of prey (trophic cascade).', image: '/images/exams/ls-aug-2025/context_42_45.png' },
    {
      number: 44,
      part: 'A',
      topic: 'Ecosystems & Ecology',
      context: 'Habitat fragmentation divides panther territory into isolated fragments separated by highways and developments. Model shows original habitat → fragmentation → smaller isolated habitat fragments with highway cutting through.',
      text: 'Which statement supports the claim that habitat fragmentation will increase the likelihood of the Florida panther becoming extinct?',
      choices: [
        'Habitat fragmentation can interfere with panther migration patterns and access to resources.',
        'Fragmentation will increase biodiversity that could lead to decreased resource availability.',
        'Competition between panthers living in different habitat fragments will increase.',
        'Panthers will be more likely to migrate to new habitats that lack feral hogs and raccoons.',
      ],
      correct: 0,
      explanation: 'Fragmentation isolates habitat patches, preventing panthers from roaming their large territories (males need ~200 sq miles). Isolated fragments limit access to prey, mates, and water — reducing population viability and increasing extinction risk.',
      diveDeep: 'Habitat fragmentation effects: (1) Reduced territory size → insufficient prey → starvation. (2) Isolation → restricted gene flow → inbreeding → reduced fitness. (3) Blocked migration routes → panthers killed attempting to cross highways. (4) Edge effects — more exposed habitat edges → increased human-wildlife conflict. Panthers require LARGE territories (males: ~200 mi²) and range across multiple habitat types for food. Fragmentation directly prevents this. Choice B is wrong because fragmentation decreases biodiversity (isolated populations, edge effects, habitat loss) — it doesn\'t increase it. Choice C is wrong because fragmented populations are isolated from each other — they don\'t compete across fragment boundaries; instead, inbreeding occurs within each fragment. Choice D is incorrect — panthers need habitat with prey (wild hogs and raccoons are important food sources). Moving to habitat WITHOUT prey would lead to starvation, not survival.', image: '/images/exams/ls-aug-2025/context_42_45.png' },
  ],
}
