// Geometry Regents — August 2019 (Part I: Multiple Choice)
export default {
  id: 'geo-aug-2019',
  subject: 'geometry',
  year: 2019,
  session: 'August',
  totalMinutes: 180,
  questions: [
    { number: 1,  part: 'A', text: 'Triangle ABC has vertices A(1, 2), B(5, 2), and C(3, 6). Which single transformation maps △ABC onto a congruent triangle with vertices A\'(−1, 2), B\'(−5, 2), and C\'(−3, 6)?', choices: ['Translation', 'Reflection over the y-axis', 'Rotation of 180°', 'Dilation of factor −1'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 2,  part: 'A', text: 'A model of a room uses a scale of 1 inch = 4 feet. If the room is 20 feet × 16 feet, what are the model dimensions?', choices: ['5 in × 4 in', '4 in × 5 in', '80 in × 64 in', '5 in × 3 in'], topic: 'Similarity & Proof', correct: 0 },
    { number: 3,  part: 'A', text: 'Two concentric circles have radii 5 and 8. What is the area of the annulus (ring) between them?', choices: ['13π', '25π', '39π', '64π'], topic: 'Circles', correct: 2 },
    { number: 4,  part: 'A', text: 'What is the perimeter of a triangle with vertices (0, 0), (6, 0), and (0, 8)?', choices: ['14', '20', '24', '28'], topic: 'Coordinate Geometry', correct: 1 },
    { number: 5,  part: 'A', text: 'A sphere has a diameter of 10. What is its volume in terms of π?', choices: ['125π/3', '250π/3', '500π/3', '1000π/3'], topic: '3D Geometry & Volume', correct: 2 },
    { number: 6,  part: 'A', text: 'In a right triangle, angle A = 63° and the side adjacent to A is 11. What is the side opposite to A to the nearest tenth?', choices: ['4.9', '8.4', '12.3', '21.6'], topic: 'Trigonometry', correct: 3 },
    { number: 7,  part: 'A', text: 'Which of the following represents a rotation of 180° about the origin applied to point (3, −5)?', choices: ['(5, 3)', '(−3, 5)', '(−5, −3)', '(5, −3)'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 8,  part: 'A', text: 'In △ABC, angle A = 32°, angle B = 58°. What can be concluded about the triangle?', choices: ['It is equilateral', 'It is right with right angle at C', 'It is obtuse', 'It is isosceles'], topic: 'Similarity & Proof', correct: 1 },
    { number: 9,  part: 'A', text: 'Two chords intersect inside a circle. One chord is divided into segments 8 and 6. If one segment of the other chord is 4, what is the other segment?', choices: ['10', '11', '12', '14'], topic: 'Circles', correct: 2 },
    { number: 10, part: 'A', text: 'A line perpendicular to y = 4x − 3 passes through (8, 1). What is its equation?', choices: ['y = −(1/4)x + 3', 'y = 4x − 31', 'y = −(1/4)x + 9', 'y = (1/4)x − 1'], topic: 'Coordinate Geometry', correct: 0 },
    { number: 11, part: 'A', text: 'A pyramid has a square base with side 12 and volume 576. What is the height?', choices: ['4', '6', '12', '16'], topic: '3D Geometry & Volume', correct: 2 },
    { number: 12, part: 'A', text: 'A road rises 3 feet for every 40 feet of horizontal distance. What is the angle of inclination to the nearest tenth of a degree?', choices: ['4.3°', '5.7°', '7.2°', '8.5°'], topic: 'Trigonometry', correct: 0 },
    { number: 13, part: 'A', text: 'A point (2, 7) is dilated by a scale factor of 3 centered at (0, 1). What are the coordinates of the image?', choices: ['(6, 21)', '(6, 19)', '(6, 22)', '(2, 19)'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 14, part: 'A', text: 'In △ABC with AB ∥ DE (D on AC, E on BC), if DC = 8, AC = 20, and BC = 15, what is EC?', choices: ['6', '8', '10', '12'], topic: 'Similarity & Proof', correct: 0 },
    { number: 15, part: 'A', text: 'An arc has a length of 6π in a circle with circumference 24π. What is the central angle of the arc?', choices: ['45°', '60°', '90°', '120°'], topic: 'Circles', correct: 2 },
    { number: 16, part: 'A', text: 'Two vertices of an equilateral triangle are (0, 0) and (6, 0). What is the y-coordinate of the third vertex?', choices: ['3', '3√2', '3√3', '6'], topic: 'Coordinate Geometry', correct: 2 },
    { number: 17, part: 'A', text: 'A cylinder has the same height and radius. If the radius is 4, what is the volume?', choices: ['16π', '32π', '64π', '128π'], topic: '3D Geometry & Volume', correct: 2 },
    { number: 18, part: 'A', text: 'The hypotenuse of a 30-60-90 triangle is 18. What is the length of the shorter leg?', choices: ['6', '9', '9√2', '9√3'], topic: 'Trigonometry', correct: 1 },
    { number: 19, part: 'A', text: 'How many lines of symmetry does a regular hexagon have?', choices: ['3', '4', '6', '12'], topic: 'Congruence & Transformations', correct: 2 },
    { number: 20, part: 'A', text: 'In two similar polygons with linear ratio 5:3, if the area of the larger is 75, what is the area of the smaller?', choices: ['25', '27', '33', '45'], topic: 'Similarity & Proof', correct: 1 },
    { number: 21, part: 'A', text: 'A circle is inscribed in a square with side 10. The circle is tangent to all four sides. What is the area of the circle?', choices: ['10π', '25π', '50π', '100π'], topic: 'Circles', correct: 1 },
    { number: 22, part: 'A', text: 'The diagonals of rhombus ABCD bisect each other at right angles. If one diagonal is 12 and the other is 16, what is the side of the rhombus?', choices: ['10', '12', '14', '20'], topic: 'Coordinate Geometry', correct: 0 },
    { number: 23, part: 'A', text: 'The volume of a cone is 48π. If the height is 9, what is the radius?', choices: ['2', '3', '4', '6'], topic: '3D Geometry & Volume', correct: 2 },
    { number: 24, part: 'A', text: 'In △ABC with right angle at C, if sin(A) = 7/25, what is cos(B)?', choices: ['7/25', '24/25', '7/24', '25/7'], topic: 'Trigonometry', correct: 0 },
  ]
}
