// Algebra 1 Regents — June 2022 (Part I: Multiple Choice)
export default {
  id: 'a1-jun-2022',
  subject: 'algebra-1',
  year: 2022,
  session: 'June',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'What is the solution to 6x − 9 = 15?', choices: ['4', '3', '6', '1'], topic: 'Linear Equations & Inequalities', correct: 0 },
    { number: 2, part: 'A', text: 'Which graph represents a function with exactly one x-intercept?', choices: ['A line with a positive slope and nonzero y-intercept', 'A horizontal line at y = 0', 'A parabola with vertex at the origin opening upward', 'A vertical line at x = 3'], topic: 'Functions & Relations', correct: 2 },
    { number: 3, part: 'A', text: 'The system y = 2x − 4 and y = −x + 5 intersects at', choices: ['(3, 2)', '(2, 0)', '(1, −2)', '(4, 4)'], topic: 'Systems of Equations', correct: 0 },
    { number: 4, part: 'A', text: 'What is the product of (x − 5)(x + 5)?', choices: ['x² − 25', 'x² + 25', 'x² − 10x + 25', 'x² + 10x − 25'], topic: 'Polynomials & Factoring', correct: 0 },
    { number: 5, part: 'A', text: 'Which value is a root of f(x) = x² − 2x − 8?', choices: ['4', '−4', '2', '8'], topic: 'Quadratic Functions', correct: 0 },
    { number: 6, part: 'A', text: 'The five-number summary of a data set is: Min = 10, Q1 = 25, Med = 40, Q3 = 55, Max = 70. The interquartile range is', choices: ['30', '60', '15', '40'], topic: 'Statistics & Probability', correct: 0 },
    { number: 7, part: 'A', text: 'Which linear equation passes through (2, 5) and (4, 9)?', choices: ['y = 2x + 1', 'y = x + 3', 'y = 3x − 1', 'y = 2x − 1'], topic: 'Linear Equations & Inequalities', correct: 0 },
    { number: 8, part: 'A', text: 'What is the value of f(−3) if f(x) = x² + 2x − 1?', choices: ['2', '14', '−4', '4'], topic: 'Functions & Relations', correct: 0 },
    { number: 9, part: 'A', text: 'Which system has the solution (−1, 4)?', choices: ['y = −x + 3 and y = 2x + 6', 'y = x + 5 and y = 4', 'y = 3x + 7 and y = −x + 3', 'y = x − 1 and y = 4x + 8'], topic: 'Systems of Equations', correct: 0 },
    { number: 10, part: 'A', text: 'What is the degree of the polynomial 5x⁴ − 3x² + 7x − 2?', choices: ['4', '3', '2', '5'], topic: 'Polynomials & Factoring', correct: 0 },
    { number: 11, part: 'A', text: 'The equation of the axis of symmetry of y = 3x² − 12x + 7 is', choices: ['x = 2', 'x = −2', 'x = 4', 'x = −4'], topic: 'Quadratic Functions', correct: 0 },
    { number: 12, part: 'A', text: 'A bag contains 10 tiles labeled 1–10. What is the probability of drawing a prime number?', choices: ['2/5', '1/2', '3/10', '1/5'], topic: 'Statistics & Probability', correct: 0 },
    { number: 13, part: 'A', text: 'Which inequality represents "three less than twice a number is at most 11"?', choices: ['2n − 3 ≤ 11', '3 − 2n ≤ 11', '2n + 3 ≤ 11', '2(n − 3) ≤ 11'], topic: 'Linear Equations & Inequalities', correct: 0 },
    { number: 14, part: 'A', text: 'Which best describes the function f(x) = 0.5(2)^x?', choices: ['Exponential growth with initial value 0.5', 'Exponential decay', 'Linear with positive slope', 'Constant function'], topic: 'Functions & Relations', correct: 0 },
    { number: 15, part: 'A', text: 'The graphs of y = x + 4 and y = x² − 2 intersect at which points?', choices: ['(−2, 2) and (3, 7)', '(2, 6) and (−3, 1)', '(0, 4) and (3, 7)', '(−1, 3) and (4, 8)'], topic: 'Systems of Equations', correct: 0 },
    { number: 16, part: 'A', text: 'Which expression is equivalent to 2x² − 8?', choices: ['2(x² − 4)', '2(x − 4)²', '2(x − 2)(x − 2)', '(2x + 4)(x − 2)'], topic: 'Polynomials & Factoring', correct: 0 },
    { number: 17, part: 'A', text: 'What is the maximum value of f(x) = −2(x + 1)² + 8?', choices: ['8', '−8', '1', '2'], topic: 'Quadratic Functions', correct: 0 },
    { number: 18, part: 'A', text: 'Which statement about the mean and median is always true for symmetric data sets?', choices: ['Mean equals median', 'Mean is greater than median', 'Median is greater than mean', 'No relationship between mean and median'], topic: 'Statistics & Probability', correct: 0 },
    { number: 19, part: 'A', text: 'Solve: |2x − 3| = 7. What are the solutions?', choices: ['x = 5 and x = −2', 'x = 5 and x = 2', 'x = −5 and x = −2', 'x = −5 and x = 2'], topic: 'Linear Equations & Inequalities', correct: 0 },
    { number: 20, part: 'A', text: 'Given f(x) = 3x + 1, what is the inverse function f⁻¹(x)?', choices: ['(x − 1)/3', '(x + 1)/3', '3x − 1', '3/(x + 1)'], topic: 'Functions & Relations', correct: 0 },
    { number: 21, part: 'A', text: 'A store sells pencils for $0.25 each and pens for $1.50 each. A student buys a total of 12 items for $6.75. How many pencils did the student buy?', choices: ['9', '7', '6', '3'], topic: 'Systems of Equations', correct: 0 },
    { number: 22, part: 'A', text: 'Which expression represents 16x⁴ written with a rational exponent?', choices: ['(4x²)²', '4²x⁴', '16^(1/4) · x', '(2x)⁴'], topic: 'Polynomials & Factoring', correct: 3 },
    { number: 23, part: 'A', text: 'The zeros of the quadratic f(x) = 2x² − 5x − 3 are', choices: ['x = 3 and x = −1/2', 'x = −3 and x = 1/2', 'x = 3 and x = 1/2', 'x = −3 and x = −1/2'], topic: 'Quadratic Functions', correct: 0 },
    { number: 24, part: 'A', text: 'A data set of quiz scores is: 55, 62, 78, 80, 85, 90, 95. Which measure best represents the typical score?', choices: ['Median = 80', 'Mean = 80', 'Mode = 55', 'Range = 40'], topic: 'Statistics & Probability', correct: 0 },
  ]
}
