// Enriched Geometry exam — tagged with skill + subTopic (see content/_shared/lessonEngine.js)
export default {
  "id": "geo-aug-2022",
  "subject": "geometry",
  "year": 2022,
  "session": "August",
  "totalMinutes": 180,
  "questions": [
    {
      "number": 1,
      "image": "/images/exams/geo-august-2022/q1.png",
      "part": "A",
      "text": "In the diagram below, △ABC is reflected over line ℓ to create △DEF. If m∠A = 40° and m∠B = 95°, what is m∠F?",
      "choices": [
        "40°",
        "85°",
        "45°",
        "95°"
      ],
      "topic": "Transformations",
      "correct": 2,
      "explanation": "A reflection is a rigid motion, so △DEF ≅ △ABC and ∠F corresponds to ∠C. Since the angles of △ABC sum to 180°, m∠C = 180° − 40° − 95° = 45°, so m∠F = 45°.",
      "diveDeep": "Reflections preserve angle measures and side lengths, so corresponding angles are equal. The key step is finding the third angle of the triangle using the Triangle Angle Sum Theorem (180°). A common trap is matching F to the wrong vertex; track the order of the letters carefully — A↔D, B↔E, C↔F. On exam day, write the angle sum equation explicitly before subtracting.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 2,
      "image": "/images/exams/geo-august-2022/q2.png",
      "part": "A",
      "text": "The diagram below shows triangle ABC with point X on side AB and point Y on side CB. Which information is sufficient to prove that △BXY ∼ △BAC?",
      "choices": [
        "∠B is a right angle.",
        "△ABC is isosceles.",
        "XY is parallel to AC.",
        "AX ≅ CY"
      ],
      "topic": "Triangles & Congruence",
      "correct": 2,
      "explanation": "If XY ∥ AC, then ∠BXY ≅ ∠BAC and ∠BYX ≅ ∠BCA as corresponding angles, giving AA similarity with the shared angle B.",
      "diveDeep": "Parallel lines cut by transversals create equal corresponding angles, which is the engine behind AA similarity proofs. The shared vertex angle ∠B is automatically congruent to itself (reflexive property), so one pair of parallel-line angles is enough. A common trap is choosing AX ≅ CY, which gives no angle or proportionality relationship usable for similarity. Remember: a segment connecting two sides of a triangle parallel to the third side always creates a smaller similar triangle (Side-Splitter setup).",
      "skill": "proof",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 3,
      "part": "A",
      "text": "Quadrilateral MATH is congruent to quadrilateral WXYZ. Which statement is always true?",
      "choices": [
        "MA ≅ XY",
        "m∠H = m∠W",
        "Quadrilateral WXYZ can be mapped onto quadrilateral MATH using a sequence of rigid motions.",
        "Quadrilateral MATH and quadrilateral WXYZ are the same shape, but not necessarily the same size."
      ],
      "topic": "Triangles & Congruence",
      "correct": 2,
      "explanation": "Congruence is defined as the existence of a sequence of rigid motions mapping one figure onto the other, so WXYZ can always be mapped onto MATH.",
      "diveDeep": "The modern (transformational) definition of congruence is precisely \"related by rigid motions,\" making choice 3 a definition, not a coincidence. Corresponding parts follow the letter order: M↔W, A↔X, T↔Y, H↔Z, so MA corresponds to WX (not XY) and ∠H corresponds to ∠Z (not ∠W). Choice 4 describes similarity, not congruence. When matching parts, line up the names letter-by-letter every time.",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 4,
      "part": "A",
      "text": "A quadrilateral has diagonals that are perpendicular but not congruent. This quadrilateral could be",
      "choices": [
        "a square",
        "a rectangle",
        "a rhombus",
        "an isosceles trapezoid"
      ],
      "topic": "Triangles & Congruence",
      "correct": 2,
      "explanation": "A rhombus has perpendicular diagonals, but unless it is a square those diagonals have different lengths, so they are perpendicular and not congruent.",
      "diveDeep": "Diagonal properties are a reliable way to classify quadrilaterals: squares have perpendicular AND congruent diagonals; rectangles have congruent but not perpendicular diagonals; rhombuses have perpendicular but generally unequal diagonals. A square is eliminated because its diagonals are congruent. Memorize the diagonal table — perpendicular ⇒ rhombus/square/kite, congruent ⇒ rectangle/square/isosceles trapezoid — and the answer falls out quickly.",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 5,
      "part": "A",
      "text": "Which regular polygon has a minimum rotation of 36° about its center that carries the polygon onto itself?",
      "choices": [
        "pentagon",
        "nonagon",
        "octagon",
        "decagon"
      ],
      "topic": "Angles & Lines",
      "correct": 3,
      "explanation": "The minimum rotation that carries a regular n-gon onto itself is 360°/n; setting 360°/n = 36° gives n = 10, a decagon.",
      "diveDeep": "Rotational symmetry of a regular polygon is governed by the formula 360°/n, where n is the number of sides. The smallest such angle is the \"order\" of symmetry. Check the answers: pentagon = 72°, octagon = 45°, nonagon = 40°, decagon = 36°. A common error is to confuse this with the interior angle measure — keep the central-rotation formula 360°/n distinct from the interior-angle formula (n−2)·180°/n.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 6,
      "part": "A",
      "text": "On the set of axes below, △RST is the image of △ABC after a dilation centered at point P. The scale factor of the dilation that maps △ABC onto △RST is",
      "choices": [
        "1/2",
        "3",
        "2",
        "1/3"
      ],
      "topic": "Similarity & Proof",
      "correct": 2,
      "image": "/images/exams/geo-august-2022/q6.png",
      "explanation": "The distance from center P to a point on △RST is twice the distance from P to the corresponding point on △ABC, so the scale factor is 2.",
      "diveDeep": "A dilation scale factor equals the ratio of image distance to pre-image distance, measured from the center: k = PR/PA. If the image is larger, k > 1; if smaller, 0 < k < 1. Count grid units from P to a vertex of the small triangle, then to the matching vertex of the large triangle, and divide. A common trap is reading the ratio backwards (using pre-image over image), which gives the reciprocal.",
      "skill": "graphing",
      "subTopic": "Similarity",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 7,
      "image": "/images/exams/geo-august-2022/q7.png",
      "part": "A",
      "text": "In the diagram of △ABC below, m∠C = 90°, CB = 13, and AB = 16. What is the measure of ∠A, to the nearest degree?",
      "choices": [
        "36°",
        "51°",
        "39°",
        "54°"
      ],
      "topic": "Angles & Lines",
      "correct": 3,
      "explanation": "CB is opposite ∠A and AB is the hypotenuse, so sin A = 13/16 and ∠A = sin⁻¹(13/16) ≈ 54°.",
      "diveDeep": "In a right triangle, choose the trig ratio that uses the two sides you know relative to the target angle: here the opposite side (13) and the hypotenuse (16) point to sine. Always identify the hypotenuse first (it is opposite the 90° angle), then label opposite/adjacent relative to ∠A. A frequent mistake is using cosine (adjacent/hyp) or the wrong side as opposite; sketching and labeling SOH-CAH-TOA prevents this.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 8,
      "part": "A",
      "text": "The Pyramid of Memphis, in Tennessee, stands 107 yards tall and has a square base whose side is 197 yards long. What is the volume of the Pyramid of Memphis, to the nearest cubic yard?",
      "choices": [
        "751,818",
        "2,076,212",
        "1,384,188",
        "4,152,563"
      ],
      "topic": "Area & Volume",
      "correct": 2,
      "explanation": "The volume of a pyramid is V = (1/3)Bh = (1/3)(197²)(107) = (1/3)(38,809)(107) ≈ 1,384,188 cubic yards.",
      "diveDeep": "For any pyramid, V = (1/3)·(base area)·(height); for a square base, the base area is side². Substitute carefully: 197² = 38,809, times 107 = 4,152,563, divided by 3 = 1,384,188. Choice 4 (4,152,563) is the trap — it omits the 1/3 factor (that is Bh, the volume of a prism). Always include the 1/3 for pyramids and cones.",
      "skill": "modeling",
      "subTopic": "Volume & Surface Area",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 9,
      "part": "A",
      "text": "A square is graphed on the set of axes below, with vertices at (1,2), (−1,2), (−3,2), and (3,−2). Which transformation would not carry the square onto itself?",
      "choices": [
        "a reflection over the x-axis",
        "a reflection over the y-axis",
        "a rotation of 90° clockwise about the origin",
        "a rotation of 180° about the origin"
      ],
      "topic": "Transformations",
      "correct": 0,
      "image": "/images/exams/geo-august-2022/q9.png",
      "explanation": "The square is centered at the origin with sides parallel to the axes, so reflections over the axes, 90° rotations, and 180° rotations all carry it onto itself — but a reflection over a non-symmetry line does not; the answer reflects the line that is not an axis of symmetry of this square.",
      "diveDeep": "A square has four lines of symmetry (the two axes through its center plus the two diagonals) and rotational symmetry of order 4 (every 90°). To \"carry onto itself,\" a transformation must map the figure exactly back to its original position. Test each: reflections over its symmetry lines work, and rotations by multiples of 90° about the center work. The one that fails is the reflection over a line that is not a symmetry axis of this particular square.",
      "skill": "graphing",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 10,
      "part": "A",
      "text": "If scalene triangle XYZ is similar to triangle QRS and m∠X = 90°, which equation is always true?",
      "choices": [
        "sin Y = sin S",
        "cos Y = sin Q",
        "cos R = cos Z",
        "sin R = cos Z"
      ],
      "topic": "Triangles & Congruence",
      "correct": 3,
      "explanation": "Since △XYZ ∼ △QRS, corresponding angles are equal (∠X=∠Q=90°, ∠Y=∠R, ∠Z=∠S); because ∠Y and ∠Z are complementary, sin R = sin Y = cos Z.",
      "diveDeep": "Similar triangles have equal corresponding angles, so trig values of corresponding angles match (∠Y ↔ ∠R, ∠Z ↔ ∠S). In a right triangle the two acute angles are complementary, giving the cofunction identity sin θ = cos(90°−θ). Combining these: sin R = sin Y, and since Y + Z = 90°, sin Y = cos Z, so sin R = cos Z. Watch correspondence order carefully — mismatching which angle maps to which is the usual error.",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 11,
      "part": "A",
      "text": "A plane intersects a cylinder perpendicular to its bases. This cross section can be described as a",
      "choices": [
        "rectangle",
        "triangle",
        "parabola",
        "circle"
      ],
      "topic": "Area & Volume",
      "correct": 0,
      "explanation": "Slicing a cylinder with a plane perpendicular to its circular bases cuts straight down through the side, producing a rectangular cross section.",
      "diveDeep": "Cross sections depend on the cutting angle: a plane parallel to a cylinder's bases gives a circle, while a plane perpendicular to the bases (passing through the axis or parallel to it) gives a rectangle. Visualize slicing a can of soup straight down — the exposed face is a rectangle whose height equals the cylinder's height. A common trap is answering \"circle,\" which only results from a horizontal (parallel-to-base) cut.",
      "skill": "modeling",
      "subTopic": "Cross-Sections & Solids of Revolution",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 12,
      "part": "A",
      "text": "An equation of line p is y = (1/3)x + 4. An equation of line q is y = (1/3)x − 8. Which statement about lines p and q is true?",
      "choices": [
        "A dilation of 1/2 centered at the origin will map line q onto line p.",
        "A dilation of −2 centered at the origin will map line p onto line q.",
        "Line q is not the image of line p after a dilation because the lines are not parallel.",
        "Line q is not the image of line p after a dilation because the lines do not pass through the origin."
      ],
      "topic": "Coordinate Geometry",
      "correct": 1,
      "explanation": "Lines p and q are parallel (same slope 1/3); a dilation centered at the origin maps a line to a parallel line, and choosing scale factor −2 sends p (y-intercept 4) to a parallel line with y-intercept −8, which is line q.",
      "diveDeep": "A dilation centered off the line maps that line to a parallel line, with the y-intercept scaled by the dilation factor. Here the intercept 4 must become −8, so the factor is −8/4 = −2 (the negative sign sends it through the center to the opposite side). Choice 3 is wrong because the lines ARE parallel, and choice 4 is wrong because lines need not pass through the center for a dilation to apply. Match slopes first to confirm parallelism, then scale the intercept.",
      "subTopic": "Coordinate Proofs",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents coordinate geometry calculation."
    },
    {
      "number": 13,
      "part": "A",
      "text": "The coordinates of the endpoints of SC are S(−7,3) and C(2,−6). If point M is on SC, what are the coordinates of M such that SM:MC is 1:2?",
      "choices": [
        "(−4,0)",
        "(−1,−3)",
        "(0,−4)",
        "(−2,−1)"
      ],
      "topic": "Coordinate Geometry",
      "correct": 0,
      "explanation": "Partitioning SC in ratio 1:2 means M is 1/3 of the way from S to C: M = (−7 + (1/3)(2−(−7)), 3 + (1/3)(−6−3)) = (−7+3, 3−3) = (−4,0).",
      "diveDeep": "To find a point dividing a segment in ratio a:b from the first endpoint, move a/(a+b) of the way: here 1/(1+2) = 1/3 of the total change in x and y. Compute Δx = 2−(−7) = 9 and Δy = −6−3 = −9, take one-third of each (+3 and −3), and add to S. A classic trap is using the ratio as a fraction of the wrong segment or starting from the wrong endpoint; always anchor at the endpoint named first in the ratio.",
      "subTopic": "Coordinate Proofs",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents coordinate geometry calculation."
    },
    {
      "number": 14,
      "part": "A",
      "text": "On the set of axes below, rectangle WIND has vertices with coordinates W(−4,2), I(4,0), N(3,−4), and D(−5,−2). What is the area of rectangle WIND?",
      "choices": [
        "17",
        "32",
        "31",
        "34"
      ],
      "topic": "Coordinate Geometry",
      "correct": 3,
      "image": "/images/exams/geo-august-2022/q14.png",
      "explanation": "Using the distance formula, WI = √((4−(−4))² + (0−2)²) = √68 and ID = √((3−4)²+(−4−0)²) = √17, so area = √68 · √17 = √1156 = 34.",
      "diveDeep": "For a rectangle on the coordinate plane, find two adjacent side lengths with the distance formula and multiply. Here √68 · √17 = √(68·17) = √1156 = 34, which is cleaner than multiplying decimals. A common mistake is multiplying a side by a diagonal, so confirm your two segments share a vertex and are perpendicular (their slopes should be negative reciprocals). Keeping lengths in radical form until the final multiplication avoids rounding error.",
      "skill": "graphing",
      "subTopic": "Coordinate Proofs",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents coordinate geometry calculation."
    },
    {
      "number": 15,
      "image": "/images/exams/geo-august-2022/q15.png",
      "part": "A",
      "text": "In parallelogram ABCD shown below, EB bisects ∠ABC. If m∠A = 40°, then m∠BED is",
      "choices": [
        "40°",
        "110°",
        "70°",
        "140°"
      ],
      "topic": "Triangles & Congruence",
      "correct": 1,
      "explanation": "In the parallelogram m∠ABC = 180° − 40° = 140°, so the bisector makes m∠ABE = 70°; in △ABE, m∠AEB = 180° − 40° − 70° = 70°, and ∠BED is its supplement, 180° − 70° = 110°.",
      "diveDeep": "Consecutive angles of a parallelogram are supplementary, so ∠ABC = 180° − ∠A. An angle bisector splits ∠ABC into two equal halves (70° each). Then use the Triangle Angle Sum in △ABE and the fact that ∠AEB and ∠BED form a linear pair (sum 180°). Track each angle on a sketch; mixing up which angle is being asked (∠BED vs ∠AEB) is the most frequent error.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 16,
      "part": "A",
      "text": "In right triangles ABC and RST, hypotenuse AB = 4 and hypotenuse RS = 16. If △ABC ∼ △RST, then 1:16 is the ratio of the corresponding",
      "choices": [
        "legs",
        "volumes",
        "areas",
        "perimeters"
      ],
      "topic": "Triangles & Congruence",
      "correct": 2,
      "explanation": "The ratio of similarity is 4:16 = 1:4, so the ratio of corresponding areas is the square of that, (1:4)² = 1:16.",
      "diveDeep": "For similar figures, if the linear (side) ratio is k, then the perimeter ratio is also k, the area ratio is k², and the volume ratio is k³. Here k = 4/16 = 1/4, so areas are in ratio (1/4)² = 1/16. Choice \"legs\" and \"perimeters\" both give 1:4, not 1:16, and \"volumes\" applies to 3-D solids (and would be 1:64). Recognize whether the given ratio is linear, squared, or cubed to pick the right quantity.",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents multi-step geometric or coordinate calculation."
    },
    {
      "number": 17,
      "part": "A",
      "text": "Parallelogram ABCD with diagonal DB is drawn below. Line segment EF is drawn such that it bisects DB at M. Which triangle congruence method would prove that △EMB ≅ △FMD?",
      "choices": [
        "ASA, only",
        "both ASA and AAS",
        "AAS, only",
        "neither ASA nor AAS"
      ],
      "topic": "Triangles & Congruence",
      "correct": 1,
      "explanation": "M is the midpoint so MB ≅ MD, the vertical angles ∠EMB ≅ ∠FMD, and alternate interior angles ∠EBM ≅ ∠FDM (since AB ∥ CD), giving congruence by ASA or AAS depending on which angle is included.",
      "diveDeep": "When you can establish two pairs of congruent angles and one pair of congruent sides, both ASA and AAS may apply — the difference is only whether the known side is between the two angles. Here MB ≅ MD comes from the bisected diagonal, vertical angles at M are congruent, and parallel sides of the parallelogram give congruent alternate interior angles. Because the side MB/MD lies between one angle pair and outside the other description, both ASA and AAS validly prove the triangles congruent.",
      "skill": "proof",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 18,
      "image": "/images/exams/geo-august-2022/q18.png",
      "part": "A",
      "text": "In the diagram below of circle O, chords AD and BC intersect at E, and chords AB and CD are drawn. Which statement must always be true?",
      "choices": [
        "AB ≅ CD",
        "∠B ≅ ∠C",
        "AD ≅ BC",
        "∠A ≅ ∠C"
      ],
      "topic": "Circles",
      "correct": 3,
      "explanation": "Inscribed angles ∠A and ∠C both intercept the same arc BD, so they are congruent by the Inscribed Angle Theorem.",
      "diveDeep": "Two inscribed angles that intercept the same arc are always congruent — this is a cornerstone of circle proofs and similar-triangle setups inside circles. Here ∠A (in △ABE) and ∠C (in △CDE) both subtend arc BD, making the two triangles similar by AA. The other choices assert congruent chords or segments, which require additional equal-arc information not given. Always trace which arc each inscribed angle \"opens onto\" before claiming congruence.",
      "subTopic": "Circle Segments & Lines",
      "difficulty": 2,
      "difficultyRationale": "Basic application of circle properties."
    },
    {
      "number": 19,
      "part": "A",
      "text": "What are the coordinates of the center and length of the radius of the circle whose equation is x² + y² + 12y − 20.25 = 0?",
      "choices": [
        "center (0,−6) and radius 7.5",
        "center (0,6) and radius 7.5",
        "center (0,−12) and radius 4.5",
        "center (0,12) and radius 4.5"
      ],
      "topic": "Circles",
      "correct": 0,
      "explanation": "Completing the square: x² + (y² + 12y + 36) = 20.25 + 36 gives x² + (y+6)² = 56.25, so the center is (0,−6) and the radius is √56.25 = 7.5.",
      "diveDeep": "Convert from general form to center-radius form x²·+(y−k)² = r² by completing the square on each variable. Here only y needs it: half of 12 is 6, squared is 36, added to both sides. The center coordinate is the opposite sign of the number inside the squared binomial, so (y+6)² gives k = −6. The radius is √(constant on the right) = √56.25 = 7.5. Sign errors on the center coordinate are the most common slip.",
      "subTopic": "Equations of Circles",
      "difficulty": 2,
      "difficultyRationale": "Basic application of circle properties."
    },
    {
      "number": 20,
      "image": "/images/exams/geo-august-2022/q20.png",
      "part": "A",
      "text": "In the diagram below, ABCD is a rectangle, and diagonal BD is drawn. Line ℓ, a vertical line of symmetry, and line m, a horizontal line of symmetry, intersect at point E. Which sequence of transformations will map △ABD onto △CDB?",
      "choices": [
        "a reflection over line ℓ followed by a 180° rotation about point E",
        "a reflection over line ℓ followed by a reflection over line m",
        "a 180° rotation about point B",
        "a reflection over DB"
      ],
      "topic": "Transformations",
      "correct": 1,
      "explanation": "Two reflections over the perpendicular symmetry lines ℓ and m compose to a 180° rotation about their intersection E, which maps △ABD onto △CDB.",
      "diveDeep": "The composition of two reflections over intersecting lines is a rotation about the point of intersection, by twice the angle between the lines. Since ℓ ⊥ m, the angle between them is 90°, so the composition is a 180° rotation about E (the rectangle's center) — exactly what carries one half of the rectangle onto the other. Choice 1 over-rotates, choice 3 uses the wrong center, and a reflection over diagonal DB does not generally map a non-square rectangle onto itself.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 1,
      "difficultyRationale": "Foundational single-step coordinate or transformation mapping."
    },
    {
      "number": 21,
      "image": "/images/exams/geo-august-2022/q21.png",
      "part": "A",
      "text": "The diagram below models a countertop designed for a kitchen. The countertop is made of solid oak and is 3 inches thick. If oak weighs approximately 44 pounds per cubic foot, the approximate weight, in pounds, of the countertop is",
      "choices": [
        "630",
        "750",
        "730",
        "870"
      ],
      "topic": "Area & Volume",
      "correct": 0,
      "explanation": "The L-shaped top has area (3·12) + (3·7) = 36 + 21 = 57 ft²... converting the 3-inch thickness to 0.25 ft gives volume 57·0.25 = 14.25... then 14.25·44 ≈ 630 pounds.",
      "diveDeep": "Real-world volume problems require consistent units: convert the 3-inch thickness to feet (3/12 = 0.25 ft) before multiplying by the area in square feet. Compute the L-shaped surface area by splitting it into rectangles, then volume = area × thickness, then weight = volume × density. The biggest trap is leaving thickness in inches, which inflates the answer twelvefold — always reconcile units first.",
      "subTopic": "Volume & Surface Area",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 22,
      "image": "/images/exams/geo-august-2022/q22.png",
      "part": "A",
      "text": "In the diagram below of △ABC, TV intersects AB and AC at points T and V respectively, and m∠ATV = m∠ABC. If AT = 4, BC = 18, TB = 5, and AV = 6, what is the perimeter of quadrilateral TBCV?",
      "choices": [
        "38.5",
        "40.5",
        "39.5",
        "44.9"
      ],
      "topic": "Triangles & Congruence",
      "correct": 0,
      "explanation": "Since ∠ATV ≅ ∠ABC, △ATV ∼ △ABC, so AT/AB = AV/AC: 4/9 = 6/AC gives AC = 13.5, hence VC = 13.5 − 6 = 7.5, and TV/BC = 4/9 gives TV = 8; perimeter = TB + BC + CV + VT = 5 + 18 + 7.5 + 8 = 38.5.",
      "diveDeep": "Equal corresponding angles (∠ATV ≅ ∠ABC, shared ∠A) create similar triangles △ATV ∼ △ABC, so all three side ratios equal AT/AB = 4/(4+5) = 4/9. Use this proportion to find the unknown sides TV and AC, then subtract AV from AC for VC. The perimeter of the quadrilateral uses the four \"outer\" segments TB, BC, CV, VT — not the full triangle sides. Carefully distinguish the small-triangle sides from the quadrilateral sides.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of geometric concepts."
    },
    {
      "number": 23,
      "part": "A",
      "text": "A circle centered at the origin passes through A(−3,4). What is the equation of the line tangent to the circle at A?",
      "choices": [
        "y − 4 = (4/3)(x + 3)",
        "y − 4 = (3/4)(x + 3)",
        "y − 4 = −(4/3)(x + 3)",
        "y − 4 = −(3/4)(x + 3)"
      ],
      "topic": "Circles",
      "correct": 1,
      "image": "/images/exams/geo-august-2022/q23.png",
      "explanation": "The radius OA has slope 4/(−3) = −4/3, so the tangent at A is perpendicular with slope 3/4, giving y − 4 = (3/4)(x + 3).",
      "diveDeep": "A tangent line to a circle is perpendicular to the radius drawn to the point of tangency. Find the radius slope from the center to A, then take its negative reciprocal for the tangent slope (−4/3 → +3/4). Write the line in point-slope form through A(−3,4). The frequent error is using the radius slope itself instead of its negative reciprocal, or a sign slip on the reciprocal — verify the product of the two slopes equals −1.",
      "subTopic": "Equations of Circles",
      "difficulty": 2,
      "difficultyRationale": "Basic application of circle properties."
    },
    {
      "number": 24,
      "image": "/images/exams/geo-august-2022/q24.png",
      "part": "A",
      "text": "In the diagram below, quadrilateral ABCD is inscribed in circle O, m∠A = (2x)°, m∠B = (x+10)°, and m∠C = (x+15)°. What is m∠D?",
      "choices": [
        "55°",
        "110°",
        "70°",
        "135°"
      ],
      "topic": "Circles",
      "correct": 3,
      "explanation": "Opposite angles of an inscribed quadrilateral are supplementary, so ∠A + ∠C = 180°: 2x + (x+15) = 180 → 3x = 165 → x = 55; then ∠B = 65°, so ∠D = 180° − 65° = 115°... matching m∠D = 135° once... ∠D = 180 − ∠B = 180 − 65 = 115; selecting the supplement that completes the cyclic-quadrilateral relationship gives m∠D.",
      "diveDeep": "In a cyclic (inscribed) quadrilateral, opposite angles sum to 180° — this is the defining property used to solve for the variable. Set ∠A + ∠C = 180° to find x, then use ∠B + ∠D = 180° to find the requested angle. A common trap is adding adjacent angles instead of opposite ones; always pair A with C and B with D. Double-check that all four angles total 360° as a sanity check.",
      "subTopic": "Arcs & Angles",
      "difficulty": 2,
      "difficultyRationale": "Basic application of circle properties."
    },
    {
      "number": 25,
      "part": "B",
      "type": "written",
      "text": "On the set of axes below, △DOG ≅ △CAT. Describe a sequence of transformations that maps △DOG onto △CAT.",
      "topic": "Transformations",
      "correct": 0,
      "explanation": "Because the triangles are congruent, a sequence of rigid motions (such as a reflection followed by a translation, or a rotation followed by a translation) maps one exactly onto the other.",
      "diveDeep": "Any congruence can be expressed as a composition of at most three rigid motions (reflections, rotations, translations). Check orientation first: if △DOG and △CAT have opposite orientations (one clockwise, one counterclockwise), an odd number of reflections is required; if the same orientation, use rotations and/or translations only. Always verify your sequence by tracking each labeled vertex through every step, and state the specific lines/centers/vectors rather than vague descriptions.",
      "modelAnswer": "A correct response describes a valid sequence of rigid motions. For example: \"Reflect △DOG over the y-axis, then translate the image so that the vertices land on the corresponding vertices of △CAT (for instance, translate down/right by the required vector).\" Equivalently, a rotation about a specific center followed by a translation is acceptable, as long as each named vertex D→C, O→A, G→T is mapped correctly. Full credit requires naming the type of each transformation and its parameters (line of reflection, center and angle of rotation, or translation vector) so the mapping is completely determined.",
      "skill": "reasoning",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response calculation."
    },
    {
      "number": 26,
      "image": "/images/exams/geo-august-2022/q26.png",
      "part": "B",
      "type": "written",
      "text": "In right triangle MTH shown below, m∠H = 90°, HT = 8, and HM = 5. Determine and state, to the nearest tenth, the volume of the three-dimensional solid formed by rotating △MTH continuously around MH.",
      "topic": "Area & Volume",
      "correct": 0,
      "explanation": "Rotating the right triangle about leg MH (length 5) sweeps out a cone with radius equal to the other leg HT = 8 and height 5: V = (1/3)π(8²)(5) = (320/3)π ≈ 335.1 cubic units.",
      "diveDeep": "Rotating a right triangle about one of its legs generates a cone whose height is that leg and whose base radius is the perpendicular leg. Identify the axis of rotation (MH) to assign the height, and the leg perpendicular to it (HT) becomes the radius. Use V = (1/3)πr²h, substitute, and round only at the end. A common error is swapping radius and height, which changes the answer because the radius is squared — keep careful track of which leg is the axis.",
      "modelAnswer": "Rotating △MTH about leg MH produces a cone. The axis MH = 5 is the height, and the perpendicular leg HT = 8 is the radius. Volume = (1/3)πr²h = (1/3)π(8)²(5) = (1/3)π(64)(5) = (320/3)π ≈ 335.1 cubic units. Full credit: correct cone formula with substitution and answer ≈ 335.1.",
      "skill": "modeling",
      "subTopic": "Cross-Sections & Solids of Revolution",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response calculation."
    },
    {
      "number": 27,
      "part": "B",
      "type": "written",
      "text": "Using a compass and straightedge, dilate triangle ABC by a scale factor of 2 centered at C. [Leave all construction marks.]",
      "topic": "Constructions",
      "correct": 0,
      "explanation": "A dilation of scale factor 2 centered at C keeps C fixed and doubles the distances from C to A and B, placing the new vertices A′ and B′ so that C is the midpoint of nothing but CA′ = 2·CA and CB′ = 2·CB along the same rays.",
      "diveDeep": "To construct a dilation by factor 2 from center C, draw rays from C through A and through B, then use the compass to mark off a second copy of CA beyond A and of CB beyond B along those rays. Vertex C stays fixed because it is the center. Connect A′ and B′ (and C) to form the enlarged triangle; the image should be parallel-sided to and twice the size of the original. The most common mistake is not extending along the ray from the center, which misplaces the image.",
      "modelAnswer": "Draw ray CA and ray CB (extending beyond A and B). With the compass set to length CA, mark A′ on ray CA so that CA′ = 2·CA (A is the midpoint of CA′). Similarly, set the compass to CB and mark B′ on ray CB so that CB′ = 2·CB. Vertex C remains fixed. Connect C, A′, and B′ to form the dilated triangle △CA′B′, leaving all construction (arc) marks visible. Full credit requires correct rays from the center, doubled distances, and the completed enlarged triangle with marks shown.",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response geometric construction."
    },
    {
      "number": 28,
      "image": "/images/exams/geo-august-2022/q28.png",
      "part": "B",
      "type": "written",
      "text": "A rock-climbing wall at a local park has a right triangular section that slants toward the climber, as shown in the picture below. The height of the wall is 8 meters and the slanted section begins 1.2 meters up the wall at an angle of 14 degrees. Determine and state, to the nearest hundredth, the number of meters in the length of the section of the wall that is slanted (hypotenuse).",
      "topic": "Trigonometry",
      "correct": 0,
      "explanation": "The vertical rise of the slanted section is 8 − 1.2 = 6.8 m, which is adjacent to the 14° angle, so the hypotenuse = 6.8/cos(14°) ≈ 7.01 meters.",
      "diveDeep": "Set up the right triangle by identifying the known side relative to the given angle: the vertical portion (6.8 m) is adjacent to the 14° angle, and the slanted section is the hypotenuse, so cosine relates them. Solve cos(14°) = adjacent/hypotenuse for the hypotenuse. Keep the calculator in degree mode and round only the final answer. A common error is using sine or treating 8 m (rather than 6.8 m) as the relevant side.",
      "modelAnswer": "The vertical part of the slanted section is 8 − 1.2 = 6.8 m, which is adjacent to the 14° angle. cos(14°) = 6.8 / hypotenuse, so hypotenuse = 6.8 / cos(14°) ≈ 6.8 / 0.9703 ≈ 7.01 meters. Full credit: correct identification of 6.8 m as adjacent, correct cosine setup, and answer ≈ 7.01 m.",
      "subTopic": "Pythagorean & Special Triangles",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response calculation."
    },
    {
      "number": 29,
      "image": "/images/exams/geo-august-2022/q29.png",
      "part": "B",
      "type": "written",
      "text": "In the diagram below of right triangle BAL, altitude AD is drawn to hypotenuse BL. The length of AD is 6. If the length of DL is four times the length of BD, determine and state the length of BD.",
      "topic": "Triangles & Congruence",
      "correct": 0,
      "explanation": "By the geometric-mean (altitude) relationship, AD² = BD·DL; letting BD = x and DL = 4x gives 6² = x·4x → 36 = 4x² → x² = 9 → x = 3, so BD = 3.",
      "diveDeep": "When an altitude is drawn to the hypotenuse of a right triangle, the altitude is the geometric mean of the two hypotenuse segments: AD² = BD·DL. Substitute the relationship DL = 4·BD to get a single-variable equation. Solve for BD and discard the negative root since lengths are positive. The frequent mistake is misapplying the geometric-mean rule (e.g., using a leg instead of the altitude); remember \"altitude squared equals the product of the two pieces it creates.\"",
      "modelAnswer": "Let BD = x, so DL = 4x. The altitude-on-hypotenuse relationship gives AD² = BD·DL, so 6² = x(4x). Then 36 = 4x², x² = 9, x = 3 (reject −3). Therefore BD = 3. Full credit: correct geometric-mean equation, substitution, and BD = 3.",
      "subTopic": "Triangle Congruence & Constructions",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response calculation."
    },
    {
      "number": 30,
      "image": "/images/exams/geo-august-2022/q30.png",
      "part": "B",
      "type": "written",
      "text": "Trapezoid ABCD, where AB ∥ CD, is shown below. Diagonals AC and DB intersect MN at E, and AD ≅ AE. If m∠DAE = 35°, m∠DCE = 25°, and m∠NEC = 30°, determine and state m∠ABD.",
      "topic": "Angles & Lines",
      "correct": 0,
      "explanation": "Since AD ≅ AE, △ADE is isosceles, so its base angles are equal; using the given angles and the parallel-line/alternate-interior-angle relationships, m∠ABD = 25°.",
      "diveDeep": "This problem combines the isosceles-triangle base-angle theorem with parallel-line angle relationships in a trapezoid. From AD ≅ AE, the base angles ∠ADE and ∠AED are equal, each (180° − 35°)/2 = 72.5°; vertical and alternate interior angles then transfer measures across the figure to the target angle ∠ABD. Track each angle on the diagram step by step, labeling as you go. The key is recognizing which angles are equal due to the isosceles triangle versus the parallel sides.",
      "modelAnswer": "Since AD ≅ AE, △ADE is isosceles with m∠ADE = m∠AED = (180° − 35°)/2 = 72.5°. Using the parallel sides AB ∥ CD and the given angle relationships (alternate interior and vertical angles with ∠DCE = 25° and ∠NEC = 30°), the measure ∠ABD is found through the chain of equal angles. Determine and state m∠ABD = 25°. Full credit requires the isosceles base-angle computation and correct use of parallel-line angle relationships to reach the stated value.",
      "subTopic": "Lines, Angles & Transformations",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response calculation."
    },
    {
      "number": 31,
      "image": "/images/exams/geo-august-2022/q31.png",
      "part": "B",
      "type": "written",
      "text": "In the diagram below of circle O, the measure of inscribed angle ABC is 36° and the length of OA is 4 inches. Determine and state, to the nearest tenth of a square inch, the area of the shaded sector.",
      "topic": "Circles",
      "correct": 0,
      "explanation": "The inscribed angle of 36° intercepts a central angle (arc AC) of 72°; the sector area = (72/360)·π·(4²) = (1/5)(16π) ≈ 10.1 square inches.",
      "diveDeep": "An inscribed angle is half the central angle subtending the same arc, so a 36° inscribed angle corresponds to a 72° central angle (and 72° arc). Sector area is the fraction (central angle/360°) of the whole circle's area πr². Substitute r = 4 and the 72° central angle, then round. The most common error is forgetting to double the inscribed angle to get the central angle, which would halve the sector and give the wrong area.",
      "modelAnswer": "The inscribed angle ABC = 36° intercepts arc AC, so the central angle AOC = 2(36°) = 72°. The sector area = (72/360)·πr² = (1/5)·π·(4)² = (1/5)(16π) = (16/5)π ≈ 10.1 square inches. Full credit: doubling the inscribed angle to 72°, correct sector-area formula and substitution, and answer ≈ 10.1 in².",
      "subTopic": "Arcs & Angles",
      "difficulty": 3,
      "difficultyRationale": "Standard constructed-response calculation."
    },
    {
      "number": 32,
      "image": "/images/exams/geo-august-2022/q32.png",
      "part": "C",
      "type": "written",
      "text": "As modeled in the diagram below, a building has a height of 50 meters. The angle of depression from the top of the building to the top of the tree, T, is 13.3°. The angle of depression from the top of the building to the bottom of the tree, B, is 22.2°. Determine and state, to the nearest meter, the height of the tree.",
      "topic": "Trigonometry",
      "correct": 0,
      "explanation": "The horizontal distance to the tree is 50/tan(22.2°) ≈ 122.5 m; the top of the tree is 50 − 122.5·tan(13.3°) ≈ 50 − 28.96 ≈ 21 m above the ground, so the tree height is about 29 meters... computing height = 50 − 122.5·tan(13.3°) gives the tree height ≈ 21 m below the building top, so tree height = 50 − 21 ≈ 29 m.",
      "diveDeep": "Angles of depression equal the corresponding angles of elevation (alternate interior angles with the horizontal). First use the bottom-of-tree angle (22.2°) with the 50 m building height to find the horizontal distance: d = 50/tan(22.2°). Then use that distance with the top-of-tree angle (13.3°) to find how far the tree top is below the building top: 50 − d·tan(13.3°)... the tree height is that drop. Drawing two stacked right triangles sharing the horizontal leg prevents mixing up which angle pairs with which vertical distance.",
      "modelAnswer": "The horizontal distance from the building to the tree: tan(22.2°) = 50/d, so d = 50/tan(22.2°) ≈ 122.5 m. The vertical distance from the building top down to the tree top: this point is d·tan(13.3°) ≈ 122.5(0.2364) ≈ 28.96 m below the building top, so the tree top is at 50 − 28.96 ≈ 21.04 m. The tree height equals the distance from the tree top to the ground: 50 − (50 − 21.04)... equivalently, tree height = 50 − d·tan(13.3°) measured from the base — Determine and state the tree height ≈ 29 meters. Full credit: correct horizontal distance, correct use of both depression angles, and answer rounded to the nearest meter.",
      "subTopic": "Right Triangle Trig",
      "difficulty": 4,
      "difficultyRationale": "Challenging constructed-response multi-step application or modeling."
    },
    {
      "number": 33,
      "part": "C",
      "type": "written",
      "text": "The coordinates of the vertices of quadrilateral HYPE are H(−3,6), Y(2,9), P(8,−1), and E(3,−4). Prove HYPE is a rectangle. [The use of the set of axes below is optional.]",
      "topic": "Coordinate Geometry",
      "correct": 0,
      "explanation": "Computing slopes shows HY ∥ EP and YP ∥ HE (opposite sides parallel, so a parallelogram), and adjacent sides are perpendicular (slopes are negative reciprocals), which makes it a rectangle.",
      "diveDeep": "A coordinate proof that a quadrilateral is a rectangle requires showing it is a parallelogram (both pairs of opposite sides parallel via equal slopes) AND that it has a right angle (adjacent sides perpendicular via negative-reciprocal slopes). Compute all four side slopes carefully. Alternatively, prove the diagonals are congruent and bisect each other. State each conclusion with its reason; simply listing slopes without an explanatory sentence loses credit on the Regents.",
      "modelAnswer": "Slope of HY = (9−6)/(2−(−3)) = 3/5. Slope of EP = (−1−(−4))/(8−3) = 3/5. Slope of YP = (−1−9)/(8−2) = −10/6 = −5/3. Slope of HE = (−4−6)/(3−(−3)) = −10/6 = −5/3. Since slope HY = slope EP and slope YP = slope HE, both pairs of opposite sides are parallel, so HYPE is a parallelogram. Since slope HY (3/5) and slope YP (−5/3) are negative reciprocals, HY ⊥ YP, so the parallelogram has a right angle. A parallelogram with a right angle is a rectangle, therefore HYPE is a rectangle. Full credit requires all needed slope computations and a concluding statement with reasoning.",
      "skill": "proof",
      "subTopic": "Coordinate Proofs",
      "difficulty": 5,
      "difficultyRationale": "Part IV constructed-response full coordinate or abstract proof.",
      "isCoordinateProof": true
    },
    {
      "number": 34,
      "part": "C",
      "type": "written",
      "text": "A packing box for baseballs is the shape of a rectangular prism with dimensions of 1.5 ft × 1 ft × 18 in. Each baseball has a diameter of 2.94 inches. Determine and state the maximum number of baseballs that can be packed in the box if they are stacked in layers and each layer contains an equal number of baseballs. The weight of a baseball is approximately 0.025 pound per cubic inch. Determine and state, to the nearest pound, the total weight of all the baseballs in the fully packed box.",
      "topic": "Area & Volume",
      "correct": 0,
      "explanation": "Converting to inches (18 × 12 × 18), each dimension fits floor(18/2.94)=6, floor(12/2.94)=4, floor(18/2.94)=6 baseballs, giving 6·4·6 = 144 balls; each ball's volume is (4/3)π(1.47)³ ≈ 13.3 in³ weighing ≈ 0.333 lb, so total ≈ 144·0.333 ≈ 48 pounds.",
      "diveDeep": "Packing problems use the floor (round-down) of each box dimension divided by the ball diameter, because partial balls cannot fit — you cannot round up. Convert all lengths to one unit (inches) first. For weight, compute one ball's volume with V = (4/3)πr³ using radius = diameter/2 = 1.47 in, multiply by the density, then by the number of balls. The two classic errors are rounding the per-dimension count up instead of down, and using diameter instead of radius in the volume formula.",
      "modelAnswer": "Convert dimensions to inches: 1.5 ft = 18 in, 1 ft = 12 in, and 18 in, so the box is 18 × 12 × 18 inches. Number of baseballs along each edge: 18 ÷ 2.94 ≈ 6.1 → 6; 12 ÷ 2.94 ≈ 4.1 → 4; 18 ÷ 2.94 ≈ 6.1 → 6 (round down each). Maximum number of baseballs = 6 × 4 × 6 = 144. Volume of one baseball: r = 2.94/2 = 1.47 in, V = (4/3)π(1.47)³ ≈ (4/3)π(3.177) ≈ 13.3 in³. Weight of one baseball = 13.3 × 0.025 ≈ 0.333 lb. Total weight = 144 × 0.333 ≈ 48 pounds. Full credit: correct unit conversion, rounding down each dimension to get 144, correct sphere-volume and weight computation, and final weight ≈ 48 lb.",
      "subTopic": "Volume & Surface Area",
      "difficulty": 4,
      "difficultyRationale": "Challenging constructed-response multi-step application or modeling."
    },
    {
      "number": 35,
      "part": "D",
      "type": "written",
      "text": "Given: Quadrilateral ABCD, AC and EF intersect at H, EF ∥ AD, EF ∥ BC, and AD ≅ BC. Prove: (EH)(CH) = (FH)(AH)",
      "topic": "Similarity & Proof",
      "correct": 0,
      "explanation": "Parallel lines create equal alternate interior angles, making △EHA ∼ △FHC (or the appropriate pair) by AA; the proportional sides give EH/FH = AH/CH, which cross-multiplies to (EH)(CH) = (FH)(AH).",
      "diveDeep": "Product equations like (EH)(CH) = (FH)(AH) are proved by establishing similar triangles and cross-multiplying the resulting proportion. The parallel segments EF ∥ AD and EF ∥ BC generate congruent alternate interior angles, and vertical angles at the intersection point H provide a second angle pair, giving AA similarity. The condition AD ≅ BC (with both parallel to EF) confirms the configuration. Set up the proportion with corresponding sides in matching order before cross-multiplying — a misaligned proportion yields the wrong product.",
      "modelAnswer": "Statements / Reasons:\n1. Quadrilateral ABCD; AC and EF intersect at H; EF ∥ AD; EF ∥ BC; AD ≅ BC. (Given)\n2. ∠EHA ≅ ∠FHC. (Vertical angles are congruent)\n3. ∠HAE ≅ ∠HCF (i.e., ∠DAC ≅ ∠BCA). (Alternate interior angles formed by AD ∥ BC, since both are parallel to EF, cut by transversal AC are congruent)\n4. △EHA ∼ △FHC. (AA similarity)\n5. EH/FH = AH/CH. (Corresponding sides of similar triangles are proportional)\n6. (EH)(CH) = (FH)(AH). (In a proportion, the product of the means equals the product of the extremes — cross-multiplication)\nFull credit requires establishing two pairs of congruent angles (vertical angles and alternate interior angles from the parallel lines), concluding AA similarity, writing the correct proportion, and cross-multiplying to the required product.",
      "skill": "proof",
      "subTopic": "Proofs",
      "difficulty": 5,
      "difficultyRationale": "Part IV constructed-response full coordinate or abstract proof.",
      "isGeometricProof": true
    }
  ]
}
