// Geometry Regents — August 2024 (Part I: Multiple Choice)
export default {
  id: 'geo-aug-2024',
  subject: 'geometry',
  year: 2024,
  session: 'August',
  totalMinutes: 180,
  questions: [
    { number: 1,  part: 'A', text: 'Which transformation maps triangle ABC to triangle A\'B\'C\' such that the two triangles are congruent and have opposite orientations?', choices: ['Translation', 'Dilation', 'Reflection', 'Rotation'], topic: 'Congruence & Transformations', correct: 2 },
    { number: 2,  part: 'A', text: 'In triangles PQR and STU, PQ/ST = QR/TU = PR/SU. What can be concluded?', choices: ['The triangles are congruent by SSS', 'The triangles are similar by SSS~', 'The triangles are similar by AA', 'The triangles are congruent by SAS'], topic: 'Similarity & Proof', correct: 1 },
    { number: 3,  part: 'A', text: 'A circle has a diameter with endpoints (2, 1) and (8, 5). What is the center of the circle?', choices: ['(3, 2)', '(5, 3)', '(4, 3)', '(6, 4)'], topic: 'Circles', correct: 1 },
    { number: 4,  part: 'A', text: 'The line segment connecting A(−1, 3) and B(5, −1) has what slope?', choices: ['2/3', '−2/3', '3/2', '−3/2'], topic: 'Coordinate Geometry', correct: 1 },
    { number: 5,  part: 'A', text: 'A cylinder has a radius of 4 and height of 10. What is its volume?', choices: ['80π', '120π', '160π', '40π'], topic: '3D Geometry & Volume', correct: 2 },
    { number: 6,  part: 'A', text: 'In a right triangle, if the adjacent leg is 7 and the hypotenuse is 25, what is tan(θ) where θ is the angle at the adjacent leg\'s vertex?', choices: ['7/25', '24/7', '7/24', '24/25'], topic: 'Trigonometry', correct: 1 },
    { number: 7,  part: 'A', text: 'Two triangles are congruent by AAS. Which set of conditions satisfies this?', choices: ['Two sides and the included angle', 'Two angles and a non-included side', 'Three pairs of equal sides', 'Two sides and a non-included angle'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 8,  part: 'A', text: 'If △ABC ~ △DEF with AB = 9 and DE = 6, and the perimeter of △DEF is 30, what is the perimeter of △ABC?', choices: ['20', '30', '45', '54'], topic: 'Similarity & Proof', correct: 2 },
    { number: 9,  part: 'A', text: 'Two tangent segments are drawn from an external point P to a circle, touching at A and B. If PA = 3x − 2 and PB = x + 8, what is PA?', choices: ['3', '5', '13', '15'], topic: 'Circles', correct: 2 },
    { number: 10, part: 'A', text: 'What is the equation of the line through (3, −2) with slope 4?', choices: ['y = 4x + 14', 'y = 4x − 14', 'y = 4x + 2', 'y = 4x − 5'], topic: 'Coordinate Geometry', correct: 1 },
    { number: 11, part: 'A', text: 'A rectangular prism has length 5, width 4, and height 3. What is its surface area?', choices: ['60', '94', '120', '47'], topic: '3D Geometry & Volume', correct: 1 },
    { number: 12, part: 'A', text: 'In a 30-60-90 triangle, the shorter leg is 5. What is the length of the hypotenuse?', choices: ['5√2', '5√3', '10', '10√3'], topic: 'Trigonometry', correct: 2 },
    { number: 13, part: 'A', text: 'A point (4, −3) is rotated 180° about the origin. What are its new coordinates?', choices: ['(−4, 3)', '(3, −4)', '(−4, −3)', '(4, 3)'], topic: 'Congruence & Transformations', correct: 0 },
    { number: 14, part: 'A', text: 'In △ABC, DE is drawn parallel to BC with D on AB and E on AC. If AD = 4, DB = 6, and AE = 5, what is EC?', choices: ['3', '7.5', '8', '12'], topic: 'Similarity & Proof', correct: 1 },
    { number: 15, part: 'A', text: 'The equation x² + y² − 6x + 4y = 3 represents a circle. What is its radius?', choices: ['3', '4', '16', '4√1'], topic: 'Circles', correct: 1 },
    { number: 16, part: 'A', text: 'A line passes through (0, 5) and (4, 0). What is its equation?', choices: ['5x + 4y = 20', '4x + 5y = 20', '5x − 4y = 20', '4x − 5y = 20'], topic: 'Coordinate Geometry', correct: 0 },
    { number: 17, part: 'A', text: 'A sphere has a volume of 288π. What is its radius?', choices: ['4', '6', '8', '12'], topic: '3D Geometry & Volume', correct: 1 },
    { number: 18, part: 'A', text: 'From the top of a 40-foot building, the angle of depression to a point on the ground is 30°. How far is that point from the base of the building?', choices: ['20 ft', '20√3 ft', '40√3 ft', '40 ft'], topic: 'Trigonometry', correct: 2 },
    { number: 19, part: 'A', text: 'Which statement is true about a line of reflection?', choices: ['It is always horizontal', 'It is the perpendicular bisector of each segment joining a point to its image', 'It always passes through the origin', 'It maps every point to a different point'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 20, part: 'A', text: 'The altitudes of a triangle meet at the', choices: ['Centroid', 'Circumcenter', 'Incenter', 'Orthocenter'], topic: 'Similarity & Proof', correct: 3 },
    { number: 21, part: 'A', text: 'A central angle of 120° intercepts an arc. What is the arc length if the radius is 9?', choices: ['3π', '6π', '9π', '18π'], topic: 'Circles', correct: 1 },
    { number: 22, part: 'A', text: 'What is the distance from the point (2, −1) to the line y = 3?', choices: ['2', '3', '4', '5'], topic: 'Coordinate Geometry', correct: 2 },
    { number: 23, part: 'A', text: 'A cone and a cylinder share the same base radius and height. The volume of the cone is what fraction of the cylinder\'s volume?', choices: ['1/4', '1/3', '1/2', '2/3'], topic: '3D Geometry & Volume', correct: 1 },
    { number: 24, part: 'A', text: 'In right triangle ABC with the right angle at C, if AC = 8 and BC = 15, what is sin(A)?', choices: ['8/17', '15/17', '8/15', '15/8'], topic: 'Trigonometry', correct: 1 },
  ]
}
