// Geometry Regents — June 2024 (Part I: Multiple Choice)
export default {
  id: 'geo-june-2024',
  subject: 'geometry',
  year: 2024,
  session: 'June',
  totalMinutes: 180,
  questions: [
    { number: 1,  part: 'A', text: 'Which transformation maps a figure onto a congruent image without changing its orientation?', choices: ['Dilation', 'Translation', 'Reflection', 'Glide Reflection'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 2,  part: 'A', text: 'Two triangles are proven congruent by SAS. Which information is necessary?', choices: ['Three pairs of congruent sides', 'Two congruent sides and the included angle', 'Two congruent angles and a non-included side', 'All three pairs of congruent angles'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 3,  part: 'A', text: 'What is the distance between points (1, 4) and (5, 1)?', choices: ['3', '4', '5', '7'], topic: 'Coordinate Geometry', correct: 2 },
    { number: 4,  part: 'A', text: 'An inscribed angle intercepts an arc of 80°. What is the measure of the inscribed angle?', choices: ['160°', '80°', '40°', '20°'], topic: 'Circles', correct: 2 },
    { number: 5,  part: 'A', text: 'If △ABC ~ △DEF with scale factor 2:1, and AB = 8, what is DE?', choices: ['16', '8', '4', '2'], topic: 'Similarity & Proof', correct: 2 },
    { number: 6,  part: 'A', text: 'A point P(5, 3) is reflected over the y-axis. What are its new coordinates?', choices: ['(−5, 3)', '(5, −3)', '(−5, −3)', '(3, 5)'], topic: 'Congruence & Transformations', correct: 0 },
    { number: 7,  part: 'A', text: 'What is the volume of a cone with radius 6 and height 9?', choices: ['54π', '108π', '162π', '324π'], topic: '3D Geometry & Volume', correct: 1 },
    { number: 8,  part: 'A', text: 'Which statement about a tangent to a circle is always true?', choices: ['It passes through the center', 'It intersects the circle at two points', 'It is perpendicular to the radius at the point of tangency', 'It is parallel to every chord'], topic: 'Circles', correct: 2 },
    { number: 9,  part: 'A', text: 'In a right triangle, sin(θ) = 5/13. What is cos(θ)?', choices: ['5/12', '12/13', '13/5', '5/13'], topic: 'Trigonometry', correct: 1 },
    { number: 10, part: 'A', text: 'The midpoint of segment AB with A(2, 6) and B(8, 2) is', choices: ['(5, 4)', '(4, 5)', '(10, 8)', '(3, 4)'], topic: 'Coordinate Geometry', correct: 0 },
    { number: 11, part: 'A', text: 'Two similar solids have a linear scale factor of 3:1. What is the ratio of their volumes?', choices: ['3:1', '6:1', '9:1', '27:1'], topic: '3D Geometry & Volume', correct: 3 },
    { number: 12, part: 'A', text: 'A triangle has angles of 50° and 70°. What is the third angle?', choices: ['40°', '50°', '60°', '80°'], topic: 'Similarity & Proof', correct: 2 },
    { number: 13, part: 'A', text: 'The equation of a circle with center (−3, 5) and radius 4 is', choices: ['(x+3)² + (y−5)² = 16', '(x−3)² + (y+5)² = 16', '(x+3)² + (y−5)² = 4', '(x−3)² + (y−5)² = 16'], topic: 'Circles', correct: 0 },
    { number: 14, part: 'A', text: 'A line has slope 3/4. What is the slope of a perpendicular line?', choices: ['3/4', '−4/3', '4/3', '−3/4'], topic: 'Coordinate Geometry', correct: 1 },
    { number: 15, part: 'A', text: 'Which congruence shortcut does NOT guarantee triangle congruence?', choices: ['ASA', 'SSS', 'SSA', 'AAS'], topic: 'Congruence & Transformations', correct: 2 },
    { number: 16, part: 'A', text: 'In a 45-45-90 triangle, if each leg is 6, what is the hypotenuse?', choices: ['6', '6√2', '6√3', '12'], topic: 'Trigonometry', correct: 1 },
    { number: 17, part: 'A', text: 'The midsegment of a triangle connecting the midpoints of two sides is parallel to and __ as long as the third side.', choices: ['Twice', 'Equal', 'Half', 'One-third'], topic: 'Similarity & Proof', correct: 2 },
    { number: 18, part: 'A', text: 'Two chords PQ and RS intersect inside a circle at T. PT = 3, TQ = 8, RT = 4. What is TS?', choices: ['6', '9', '32', '2.67'], topic: 'Circles', correct: 0 },
    { number: 19, part: 'A', text: 'What is the surface area of a sphere with radius 3?', choices: ['12π', '36π', '108π', '36'], topic: '3D Geometry & Volume', correct: 1 },
    { number: 20, part: 'A', text: 'An observer at ground level measures a 45° angle of elevation to a treetop. If the tree is 30 feet tall, how far is the observer from the base?', choices: ['15 ft', '30 ft', '30√2 ft', '60 ft'], topic: 'Trigonometry', correct: 1 },
    { number: 21, part: 'A', text: 'The centroid of a triangle divides each median in the ratio', choices: ['1:1', '1:2', '2:1', '3:1'], topic: 'Coordinate Geometry', correct: 2 },
    { number: 22, part: 'A', text: 'A rotation of 90° counterclockwise about the origin maps (x, y) to', choices: ['(y, x)', '(−y, x)', '(y, −x)', '(−x, −y)'], topic: 'Congruence & Transformations', correct: 1 },
    { number: 23, part: 'A', text: 'Arc length for a 120° central angle in a circle with radius 9 is', choices: ['3π', '6π', '9π', '12π'], topic: 'Circles', correct: 1 },
    { number: 24, part: 'A', text: 'Using the Law of Cosines, in triangle ABC with a=7, b=5, c=8, what does cos(C) equal?', choices: ['(49+25−64)/70', '(64+25−49)/80', '(49+64−25)/112', '(25+64−49)/80'], topic: 'Trigonometry', correct: 2 },
  ]
}
