// Living Environment Regents — August 2022
export default {
  id: 'le-august-2022',
  subject: 'living-environment',
  year: 2022,
  session: 'August',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'Which process is responsible for the growth and repair of body tissues in multicellular organisms?',
      choices: [
        'meiosis',
        'mitosis',
        'fertilization',
        'mutation',
      ],
      topic: 'Reproduction',
      correct: 1,
    },
    {
      number: 2, part: 'A',
      text: 'In an ecosystem, energy flows from the Sun to producers and then to consumers. At each step in this energy transfer, most of the energy is',
      choices: [
        'stored in the bodies of organisms at the next trophic level',
        'lost as heat to the environment',
        'converted to chemical energy in the atmosphere',
        'recycled back to the producers',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 3, part: 'A',
      text: 'Identical twins develop from a single fertilized egg that splits into two cells. These twins have identical DNA, yet they may have different fingerprints. This difference is most likely due to',
      choices: [
        'mutations in the DNA of one twin that occurred after the split',
        'differences in the environments of each twin during development',
        'the twins inheriting different chromosomes from their parents',
        'the twins using different genes to control development',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 4, part: 'A',
      text: 'The sequence of amino acids in a protein is determined by the',
      choices: [
        'shape of the ribosome that produces the protein',
        'sequence of bases in the DNA gene for that protein',
        'type of lipid molecules surrounding the cell',
        'number of mitochondria in the cell',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 5, part: 'A',
      text: 'A symbiotic relationship in which one organism benefits and the other is neither harmed nor helped is called',
      choices: [
        'mutualism',
        'commensalism',
        'parasitism',
        'predation',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 6, part: 'A',
      text: 'The extinction of a keystone species in an ecosystem would most likely result in',
      choices: [
        'increased stability because fewer species compete for the same resources',
        'a dramatic change in the structure and function of the ecosystem',
        'rapid recovery of the ecosystem due to the resilience of other species',
        'no significant change because other species would immediately fill the niche',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 7, part: 'A',
      text: 'An organism that feeds on dead organic matter and breaks it down into simpler substances is called a',
      choices: [
        'producer',
        'primary consumer',
        'decomposer',
        'carnivore',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 8, part: 'A',
      text: 'Which cell organelle is most directly involved in the production of proteins?',
      choices: [
        'mitochondria',
        'ribosome',
        'vacuole',
        'cell membrane',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 9, part: 'A',
      text: 'Humans have intentionally bred dogs for specific traits such as size, coat color, and temperament. This process is an example of',
      choices: [
        'natural selection',
        'genetic mutation',
        'artificial selection',
        'sexual reproduction',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 10, part: 'A',
      text: 'Antibiotics are drugs that kill bacteria. Some bacteria have developed resistance to antibiotics. The development of antibiotic resistance in a bacterial population is an example of',
      choices: [
        'Lamarckian evolution — bacteria developed resistance because they needed to survive',
        'natural selection — bacteria with random mutations survived and passed resistance to offspring',
        'genetic engineering — scientists modified bacterial DNA to produce resistant strains',
        'selective breeding — humans chose resistant bacteria for reproduction',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 11, part: 'A',
      text: 'Which statement best describes the function of mitochondria in a cell?',
      choices: [
        'They produce proteins for use in and outside the cell.',
        'They carry out cellular respiration to produce ATP for cell activities.',
        'They contain the DNA that controls all cell activities.',
        'They regulate what enters and exits the cell.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 12, part: 'A',
      text: 'The relationship between flowering plants and the bees that pollinate them is an example of',
      choices: [
        'parasitism — the bee benefits while the plant is harmed',
        'competition — both species compete for the same resources',
        'mutualism — both species benefit from the relationship',
        'commensalism — the bee benefits while the plant is unaffected',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 13, part: 'A',
      text: 'Which statement best explains why the offspring produced by sexual reproduction are genetically different from each parent?',
      choices: [
        'Sexual reproduction does not involve DNA; offspring develop new genetic information.',
        'The offspring receive a unique combination of alleles from both parents through gametes.',
        'Sexual reproduction causes mutations that produce new genetic information.',
        'Gametes from each parent contain the same genetic information.',
      ],
      topic: 'Reproduction',
      correct: 1,
    },
    {
      number: 14, part: 'A',
      text: 'When the concentration of glucose in the blood rises after a meal, the pancreas releases insulin. Insulin causes cells to take up glucose, lowering blood glucose levels. This is an example of',
      choices: [
        'active transport across the cell membrane',
        'a negative feedback mechanism that maintains homeostasis',
        'a positive feedback mechanism that amplifies the response',
        'the immune response to foreign substances in the blood',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 15, part: 'A',
      text: 'Two species of squirrels live in the same forest and eat the same types of nuts. These two species are most likely engaged in',
      choices: [
        'mutualism',
        'competition',
        'predation',
        'parasitism',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 16, part: 'A',
      text: 'In humans, the structure of red blood cells makes them well suited for carrying oxygen. Red blood cells lack a nucleus, giving them more room for hemoglobin. The shape and function of red blood cells is most directly determined by',
      choices: [
        'the oxygen level in the blood',
        'the activity of specific genes in red blood cell precursors',
        'the temperature of the blood',
        'the hormones produced by the kidneys',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 17, part: 'A',
      text: 'What is the primary reason why the burning of fossil fuels is a concern for the environment?',
      choices: [
        'It depletes the supply of fossil fuels, which are needed for photosynthesis.',
        'It releases large amounts of carbon dioxide, contributing to the greenhouse effect.',
        'It produces oxygen that reacts with water to form acid rain.',
        'It cools the atmosphere by releasing heat from combustion.',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 18, part: 'A',
      text: 'The CRISPR/Cas9 system allows scientists to precisely edit genes in living organisms. This technology could be used to',
      choices: [
        'create organisms that are genetically identical to existing species',
        'correct genetic mutations that cause diseases',
        'increase the rate of natural selection in wild populations',
        'produce new species without the need for reproduction',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 19, part: 'A',
      text: 'Which situation would most likely lead to an increase in the biodiversity of an ecosystem?',
      choices: [
        'introduction of a predator that eliminates all competitors',
        'restoration of a wetland habitat that was previously drained for agriculture',
        'application of pesticides that kill all insects in the area',
        'planting of a single crop species in a previously wild area',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 20, part: 'A',
      text: 'A student compares two cells under a microscope. Cell A has a cell wall, large central vacuole, and chloroplasts. Cell B lacks these structures. Cell A is most likely from a',
      choices: [
        'bacterium',
        'plant',
        'fungus',
        'animal',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 21, part: 'A',
      text: 'The development of antibiotic resistance in bacteria is similar to the development of pesticide resistance in insects. Both examples illustrate that',
      choices: [
        'organisms can intentionally change their genetic makeup to survive threats',
        'natural selection acts on variation in populations to produce adapted individuals',
        'all organisms will eventually become resistant to any chemical used against them',
        'genetic engineering can rapidly produce resistant populations of organisms',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 22, part: 'A',
      text: 'Which process produces the most ATP for use in cell activities?',
      choices: [
        'photosynthesis',
        'fermentation',
        'aerobic cellular respiration',
        'transcription',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 23, part: 'A',
      text: 'The human immune system responds to an infection by producing proteins that recognize and bind to specific molecules on the surface of pathogens. These proteins are called',
      choices: [
        'antigens',
        'antibodies',
        'hormones',
        'enzymes',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 24, part: 'A',
      text: 'Which statement best describes the relationship between genes and traits?',
      choices: [
        'Each gene controls the expression of all traits in an organism.',
        'Genes provide instructions for making proteins that determine traits.',
        'Traits are passed to offspring through the environment, not through genes.',
        'All traits in an organism are determined by a single gene.',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 25, part: 'A',
      text: 'The geographic isolation of a population can lead to speciation because',
      choices: [
        'isolated populations experience the same environmental pressures as the original population',
        'geographic barriers allow gene flow between isolated populations',
        'isolated populations accumulate different genetic changes over time, making interbreeding impossible',
        'geographic isolation increases the mutation rate in isolated populations',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 26, part: 'A',
      text: 'Lichens are organisms composed of a fungus and a photosynthetic alga living in a close association. The alga provides the fungus with food through photosynthesis, and the fungus provides the alga with water and protection. This relationship is an example of',
      choices: [
        'parasitism',
        'mutualism',
        'competition',
        'predation',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 27, part: 'A',
      text: 'Which activity would best help maintain biodiversity in a region?',
      choices: [
        'clearing forests and replacing them with a single crop plant',
        'draining wetlands to create farmland',
        'establishing wildlife corridors between fragmented habitats',
        'introducing invasive species to control pest populations',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 28, part: 'A',
      text: 'In humans, type 1 diabetes is an autoimmune disease in which the immune system mistakenly destroys the insulin-producing cells of the pancreas. Which statement best explains why this is harmful?',
      choices: [
        'Without insulin, blood glucose levels cannot be regulated, leading to dangerously high blood sugar.',
        'Without insulin, the pancreas produces too much glucagon, causing blood sugar to drop too low.',
        'Without insulin, the body cannot absorb amino acids for protein synthesis.',
        'Without insulin, the liver cannot store glycogen, causing immediate energy loss.',
      ],
      topic: 'Human Body',
      correct: 0,
    },
    {
      number: 29, part: 'A',
      text: 'A scientist discovers two species of birds that look very similar but do not interbreed with each other. Comparing the DNA sequences of these two species would be useful for',
      choices: [
        'determining how closely related the two species are',
        'predicting future evolutionary changes in each species',
        'showing that the two species evolved from completely different ancestors',
        'proving that the birds will eventually interbreed',
      ],
      topic: 'Genetics',
      correct: 0,
    },
    {
      number: 30, part: 'A',
      text: 'In photosynthesis, plants use carbon dioxide, water, and light energy to produce',
      choices: [
        'ATP and carbon dioxide',
        'glucose and oxygen',
        'nitrogen and glucose',
        'water and ATP',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A graph shows the population sizes of predator (lynx) and prey (snowshoe hare) species over a 90-year period. The graph shows regular cycles: when hare populations increase, lynx populations increase shortly after; when hare populations decline, lynx populations also decline.',
      text: 'Based on the graph, which statement best describes the relationship between the lynx and snowshoe hare populations?',
      choices: [
        'The lynx population drives changes in the hare population, with lynx increasing first.',
        'The hare population drives changes in the lynx population, with hares increasing first.',
        'Both populations increase and decrease at exactly the same time.',
        'The two populations are not related and change independently.',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2022/q31.png',
    },
    {
      number: 32, part: 'B-1',
      context: 'A graph shows regular cycles between lynx and snowshoe hare populations over 90 years.',
      text: 'According to the graph, what most likely happens to the lynx population when the hare population reaches its lowest point?',
      choices: [
        'The lynx population increases rapidly due to less competition for food.',
        'The lynx population begins to decline due to reduced food supply.',
        'The lynx population remains stable because lynx can switch to other prey.',
        'The lynx population is not affected because lynx are apex predators.',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2022/q32.png',
    },
    {
      number: 33, part: 'B-1',
      context: 'A diagram shows the human digestive system with labels on various organs.',
      text: 'In which organ does the majority of nutrient absorption occur?',
      choices: [
        'stomach',
        'large intestine',
        'small intestine',
        'esophagus',
      ],
      topic: 'Human Body',
      correct: 2,
      image: '/images/exams/le-august-2022/q33.png',
    },
    {
      number: 34, part: 'B-1',
      context: 'A diagram shows a DNA molecule being used as a template for mRNA synthesis, followed by the mRNA being used to produce a protein at a ribosome.',
      text: 'The process by which mRNA is produced from a DNA template is called',
      choices: [
        'translation',
        'replication',
        'transcription',
        'mutation',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-august-2022/q34.png',
    },
    {
      number: 35, part: 'B-1',
      text: 'A researcher wants to determine if a new fertilizer increases the growth rate of tomato plants. She grows 30 plants with the new fertilizer and 30 plants without. All other growing conditions are kept identical. After 8 weeks, she measures the height of each plant. What is the purpose of the 30 plants grown without fertilizer?',
      choices: [
        'They serve as the experimental group to test the effect of fertilizer.',
        'They serve as the control group to compare against the fertilizer group.',
        'They provide extra data that will be averaged with the fertilizer group.',
        'They are used to determine the optimal amount of fertilizer to use.',
      ],
      topic: 'General Review',
      correct: 1,
    },
    {
      number: 36, part: 'B-1',
      text: 'A population of moths lives in an area where tree bark is light gray. Most moths are light gray and blend into the bark, while a few are dark. After industrial pollution turns the tree bark dark, which change in the moth population is most likely to occur over many generations?',
      choices: [
        'All light-colored moths will change their color to dark to survive.',
        'The frequency of dark-colored moths will increase as they are better camouflaged.',
        'The frequency of light-colored moths will increase as they are better camouflaged.',
        'No change will occur because moth color is not affected by the environment.',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 37, part: 'B-1',
      context: 'A diagram shows a generalized cell with various organelles labeled A through E.',
      text: 'Which labeled organelle in the diagram is responsible for releasing energy from glucose molecules through cellular respiration?',
      choices: [
        'A — cell membrane',
        'B — nucleus',
        'C — mitochondria',
        'D — ribosome',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-august-2022/q37.png',
    },
    {
      number: 38, part: 'B-1',
      context: 'A diagram shows a generalized cell with various organelles labeled A through E.',
      text: 'In which labeled organelle does protein synthesis take place?',
      choices: [
        'A — cell membrane',
        'B — nucleus',
        'C — mitochondria',
        'D — ribosome',
      ],
      topic: 'Cell Biology',
      correct: 3,
      image: '/images/exams/le-august-2022/q38.png',
    },
    {
      number: 39, part: 'B-1',
      text: 'A student reads that a new species of beetle was discovered in a rainforest. The article states that scientists expect this beetle may be extinct before it is fully studied. The most likely reason for this concern is',
      choices: [
        'the beetle population is growing rapidly and competing with other species',
        'habitat destruction in rainforests is occurring faster than species can be catalogued',
        'the beetle is a parasitic species that will be eliminated by its host species',
        'all beetle species eventually go extinct because they cannot adapt to change',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 40, part: 'B-1',
      context: 'A pedigree chart shows three generations of a family and the inheritance of a trait. In the chart, some individuals are shaded (affected) and others are not shaded (unaffected).',
      text: 'Based on the pedigree, if two unaffected parents have an affected child, the trait is most likely',
      choices: [
        'dominant, because both parents must have the trait to pass it on',
        'recessive, because both parents must carry the recessive allele without showing the trait',
        'sex-linked, because only males can be affected by the trait',
        'caused by a new mutation not inherited from either parent',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-august-2022/q40.png',
    },
    {
      number: 41, part: 'B-1',
      text: 'Which process describes the movement of water molecules from an area of high water concentration to an area of low water concentration through a semipermeable membrane?',
      choices: [
        'active transport',
        'endocytosis',
        'osmosis',
        'facilitated diffusion',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 42, part: 'B-1',
      text: 'In ecosystems, the total amount of energy available decreases at each trophic level. This means that',
      choices: [
        'producer populations must be larger than consumer populations',
        'carnivores always have more energy available than herbivores',
        'energy flows in a cycle through the ecosystem',
        'decomposers have access to more energy than producers',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 43, part: 'B-1',
      text: 'Scientists studying evolution often use the concept of homologous structures — body parts that have the same basic structure but are used for different functions in different species. Homologous structures are evidence of evolution because they suggest that',
      choices: [
        'all species have identical functions for all body parts',
        'different species with similar structures share a common ancestor',
        'structures that serve different functions cannot be related',
        'evolution always produces the same structures in different species',
      ],
      topic: 'Genetics',
      correct: 1,
    },
  ],
}
