// Living Environment Regents — August 2025
export default {
  id: 'li-aug-2025',
  subject: 'living-environment',
  year: 2025,
  session: 'August',
  totalMinutes: 180,
  questions: [
    {
      number: 1,
      part: 'A',
      text: 'Which mechanism is used to maintain a stable internal environment in humans?',
      choices: [
        'use of guard cells to control water loss and gas exchange',
        'destruction of the immune system by the AIDS virus',
        'increased perspiration during periods of intense activity',
        'an allergic reaction to pollen from cats',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Increased perspiration during intense activity is an example of homeostasis — the body increases sweating to release heat and maintain a stable internal temperature.',
      diveDeep: 'Homeostasis is the maintenance of a stable internal environment despite external changes. The human body uses feedback mechanisms to regulate temperature, blood sugar, water balance, and many other variables. Sweating is a negative feedback response to overheating: temperature rises → sweat glands activated → evaporation cools the body → temperature drops back to normal. Guard cells (choice A) are a plant structure. AIDS destroys the immune system (choice B) — this is an example of the body failing to maintain homeostasis, not maintaining it. Allergic reactions (choice D) are misdirected immune responses, not homeostatic mechanisms. Students should recognize homeostatic examples vs. disruptions.',
    },
    {
      number: 2,
      part: 'A',
      text: 'Industrial processes often release lead and copper compounds into waterways, which could then have adverse effects on human health. Previously, methods to remove these compounds were expensive and often produced toxins themselves. Researchers have now found that minced banana peels are able to quickly absorb lead and copper from river water. In addition, banana peels are non-toxic and inexpensive. The use of the banana peels in this case is probably a',
      choices: [
        'poor use of resources, because it introduces a new organism into the ecosystem',
        'trade-off, because the more toxic methods might still be used',
        'simple proposal, which will increase the costs of cleaning up the waterways',
        'good use of resources, which can help to restore a natural ecosystem',
      ],
      topic: 'General',
      correct: 3,
      image: '/images/exams/le-august-2025/q2.png',
      explanation: 'Using banana peels is a good use of resources because they are inexpensive, non-toxic, and effective at removing harmful pollutants, helping to restore a cleaner, healthier ecosystem.',
      diveDeep: 'This question tests environmental decision-making and the concept of trade-offs. A trade-off involves accepting some negative consequence in exchange for a benefit. Using banana peels eliminates the trade-off of toxic removal methods — it is inexpensive AND non-toxic AND effective. Introducing banana peels (already a natural product) is not introducing a new organism to the ecosystem; they are organic matter. Students should evaluate each choice against the information given: the passage states banana peels are inexpensive (not costly) and non-toxic (no negative trade-off), making "good use of resources" the clear best answer.',
    },
    {
      number: 3,
      part: 'A',
      text: 'Which abiotic factor would most directly limit the size of a gray squirrel population?',
      choices: [
        'variety of food sources',
        'number of predators',
        'availability of water in the forest',
        'amount of nitrogen in the atmosphere',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Water is an abiotic (non-living) factor, and its availability directly limits population size because all organisms require water for survival, metabolism, and reproduction.',
      diveDeep: 'Abiotic factors are non-living environmental components: water, temperature, light, soil minerals, pH, and atmospheric gases. Biotic factors are living components: predators, prey, competitors, parasites, and food sources. The question specifically asks for an ABIOTIC factor. Food variety and predator numbers are biotic factors. Nitrogen in the atmosphere (~78%) is essentially unlimited and not a direct limiting factor for animals. Water availability, temperature, and light are the most commonly tested abiotic limiting factors on the Living Environment Regents. Students must distinguish clearly between biotic and abiotic factors — this distinction appears on nearly every exam.',
    },
    {
      number: 4,
      part: 'A',
      text: 'Human chromosomes differ from the chromosomes of fruit flies in that human chromosomes',
      choices: [
        'are made from only four kinds of bases',
        'contain only 46 genes',
        'may be involved in both mitosis and meiosis',
        'have different sequences of bases',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'All organisms use DNA made of the same four bases (A, T, G, C), but the specific sequences of bases differ between species, giving each species its unique genetic information.',
      diveDeep: 'DNA is universal across all living organisms — the same four nucleotide bases (adenine, thymine, guanine, cytosine) are used, and the same genetic code translates codons to amino acids. The differences between species arise from the specific sequences of these bases. All chromosomes in dividing cells (in species that reproduce sexually) can be involved in mitosis (body cells) and meiosis (reproductive cells). Humans have 46 chromosomes with approximately 20,000–25,000 genes — not just 46 genes. Students should remember: DNA structure and bases are universal; DNA sequence is species/individual-specific.',
    },
    {
      number: 5,
      part: 'A',
      text: 'One major benefit of the use of water power is that it',
      choices: [
        'does not produce a significant amount of carbon dioxide as a waste product',
        'increases the production of oxygen in the atmosphere',
        'has no impact on the rivers that are used',
        'increases the recycling of nutrients',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'Hydroelectric power generates electricity without combustion, so it does not release significant amounts of carbon dioxide (a greenhouse gas), unlike fossil fuel power plants.',
      diveDeep: 'Hydroelectric power uses the kinetic energy of flowing water to turn turbines and generate electricity. Unlike fossil fuels, it does not produce CO₂ or other combustion byproducts during operation. However, it is NOT without environmental impact — dams can disrupt river ecosystems, block fish migration, flood upstream habitats, and alter downstream water flow and temperature. So choice C (no impact on rivers) is incorrect. Water power does not directly affect atmospheric oxygen production or nutrient cycling. Students should evaluate renewable energy sources for their actual benefits AND limitations when answering Regents questions.',
    },
    {
      number: 6,
      part: 'A',
      text: 'Adding chlorine to drinking water in many modern cities has been credited with reducing outbreaks of diseases, such as cholera. Some scientists claim that adding chlorine may result in by-products in the water that may very slightly increase the risk of cancer. The decision to add chlorine to drinking water most likely involved',
      choices: [
        'an assessment of trade-offs',
        'the elimination of genetic diseases',
        'the removal of all pathogens from water',
        'the disruption of dynamic equilibrium in ponds',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'Chlorinating water involves a trade-off: the major benefit (preventing deadly waterborne diseases) outweighs the minor risk (a very slight increase in cancer risk from by-products).',
      diveDeep: 'A trade-off is a decision that involves accepting a disadvantage to gain a larger benefit. Water chlorination is a classic public health trade-off: the benefit (virtually eliminating waterborne diseases like cholera, typhoid) is enormous; the cost (slight cancer risk from chlorination by-products) is very small. The decision is based on cost-benefit analysis comparing the risks and benefits. Students should recognize trade-off scenarios: whenever a beneficial technology or practice has some negative side effect, it involves a trade-off. Chlorination does NOT eliminate all pathogens (Cryptosporidium is resistant to chlorine), does not cause genetic diseases, and is not about dynamic equilibrium in ponds.',
    },
    {
      number: 7,
      part: 'A',
      text: 'The diagram below represents a process that can occur when chromosomes are copied in sexually reproducing organisms. One result of this process is',
      choices: [
        'an increase in the number of chromosomes in the cell to double its original number',
        'an increase in the number of new gene combinations that can be passed on to offspring',
        'an elimination of mutations in reproductive cells and zygotes',
        'the formation of new genes that will decrease variation in future generations',
      ],
      topic: 'Cell Biology',
      correct: 1,
      image: '/images/exams/le-august-2025/q7.png',
      explanation: 'The process shown is crossing over (recombination) during meiosis, which creates new combinations of alleles on chromosomes, increasing genetic variation in offspring.',
      diveDeep: 'Crossing over occurs during prophase I of meiosis, when homologous chromosomes pair up and exchange segments. This shuffles alleles between chromosomes, creating gametes with new combinations of genes that did not exist in either parent. This increases genetic variation in offspring, which is the raw material for natural selection and evolution. Crossing over does NOT: change the chromosome number (that is determined by meiosis itself), eliminate mutations, or form entirely new genes. Students should distinguish sources of genetic variation: crossing over (recombination), independent assortment of chromosomes during meiosis I, and random fertilization.',
    },
    {
      number: 8,
      part: 'A',
      text: 'Scientists initially studying the decline of certain penguin populations in Antarctic regions found that the penguins\' food source, a small animal known as krill, had dropped by 80%. These scientists are now studying the reduction in the number of tiny photosynthetic organisms that are the food source of the krill. The decline of the penguin population was a direct effect of the disruption of a',
      choices: [
        'parasitic relationship',
        'biosphere',
        'food chain',
        'mechanism of evolution',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'The decline in photosynthetic organisms → reduction in krill → decline in penguins describes a disruption in a food chain, where energy flows from producers to consumers.',
      diveDeep: 'A food chain shows the feeding relationships and energy flow between organisms: phytoplankton (producers) → krill (primary consumers) → penguins (secondary consumers). Disruption at any level cascades through the chain. This is also an example of a trophic cascade — when a change at one level affects multiple other levels. A food web is more complex (multiple food chains interconnected). Students should be able to identify feeding relationships: producer (makes own food via photosynthesis), primary consumer (eats producers), secondary consumer (eats primary consumers). The key word in the answer is "chain" — this is a linear energy transfer sequence, not a parasitic or evolutionary relationship.',
    },
    {
      number: 9,
      part: 'A',
      text: 'The diagram below represents a process that occurs during the development of human body cells. Nerve Muscle Skin Fertilized egg Which statement is correct regarding these cells?',
      choices: [
        'The fertilized egg and other types of cells all have the same DNA.',
        'The fertilized egg contains half the genetic information of the other types of cells.',
        'Each cell contains only the genetic information necessary for its particular function.',
        'The body cells undergo mitosis and the fertilized egg undergoes meiosis.',
      ],
      topic: 'Human Body',
      correct: 0,
      image: '/images/exams/le-august-2025/q9.png',
      explanation: 'Every cell in the human body (except gametes) contains the same complete set of DNA as the original fertilized egg — different cells express different genes, but they all have the same genetic information.',
      diveDeep: 'Cell differentiation produces specialized cells (nerve, muscle, skin) from the original fertilized egg through mitosis. During this process, every cell receives a complete copy of the organism\'s DNA — no DNA is lost or gained. Differentiated cells look and function differently because different genes are expressed (turned on or off), not because they have different genes. The fertilized egg (zygote) has the FULL diploid (2n) chromosome number — it does not have half the information of body cells. Body cells undergo mitosis (for growth/repair); only specialized cells (in gonads) undergo meiosis to produce gametes. Students must understand the distinction between differential gene expression and differential gene content.',
    },
    {
      number: 10,
      part: 'A',
      text: 'Which situation would most likely lead to increased diversity in a species?',
      choices: [
        'A population of birds with high variation migrates to a group of islands with different environmental conditions.',
        'Selective breeding is used to develop a species that is only able to live in very specific environmental conditions.',
        'An ecosystem containing few species experiences many centuries of stable climatic conditions.',
        'Asexual reproduction is used to produce more plants of a certain species.',
      ],
      topic: 'Evolution',
      correct: 0,
      explanation: 'A genetically diverse population migrating to multiple different environments (isolated islands) creates conditions for adaptive radiation — different populations adapt to different local conditions, increasing diversity.',
      diveDeep: 'Increased species/genetic diversity results from: genetic variation in the founding population + different selective pressures in isolated environments. This scenario describes adaptive radiation — one ancestral species diversifying into multiple distinct forms as isolated populations adapt to different niches (Darwin\'s finches are the classic example). Selective breeding REDUCES diversity by selecting for specific traits. Stable climatic conditions over long periods favor stasis, not diversification. Asexual reproduction produces genetically identical clones, reducing genetic variation. Students should connect: genetic variation + geographic isolation + different selection pressures = speciation and increased diversity.',
    },
    {
      number: 11,
      part: 'A',
      text: 'Some allergies are inherited. Allergic reactions are often much less severe in adults who were exposed to the allergen (the substance causing the reaction) during infancy. What does this show about some inherited traits?',
      choices: [
        'The effect of allergens can never be predicted.',
        'Developing allergies requires genes from both parents.',
        'Allergies are always caused by DNA.',
        'Gene expression can be influenced by environmental conditions.',
      ],
      topic: 'Genetics',
      correct: 3,
      image: '/images/exams/le-august-2025/q11.png',
      explanation: 'Early allergen exposure during infancy modifies how the inherited allergy gene is expressed later in life, demonstrating that environmental conditions (timing of allergen exposure) can influence gene expression.',
      diveDeep: 'This is an example of gene-environment interaction — the genotype (inherited predisposition to allergy) interacts with the environment (early allergen exposure) to produce a modified phenotype (milder allergic reaction). This concept, sometimes called epigenetics or phenotypic plasticity, shows that having a gene does not determine the outcome with certainty — the environment can modify how genes are expressed. Students should know: genotype × environment = phenotype. This appears frequently on the Living Environment Regents because it challenges the simple idea that genes directly and deterministically control traits. Examples: height (genes + nutrition), skin color (genes + sun exposure), and allergies (genes + environmental exposure).',
    },
    {
      number: 12,
      part: 'A',
      text: 'A tall building is built on an empty lot. The new building blocks the sunlight on nearby streets for most of the day. Trees and plants grow more slowly or die off because the building has interfered with a',
      choices: [
        'removal of water from the atmosphere',
        'production of finite resources',
        'recycling of solar energy',
        'process that produces organic compounds',
      ],
      topic: 'General',
      correct: 3,
      image: '/images/exams/le-august-2025/q12.png',
      explanation: 'Sunlight is required for photosynthesis, the process by which plants use light energy to produce organic compounds (glucose) from CO₂ and water; blocking sunlight disrupts this fundamental process.',
      diveDeep: 'Photosynthesis: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. This process produces organic compounds (glucose/carbohydrates) from inorganic raw materials, using solar energy. Without sunlight, photosynthesis cannot occur, and plants starve. Solar energy is not "recycled" — it enters the ecosystem through photosynthesis and exits as heat; energy flows through ecosystems, it does not cycle (unlike matter). Water is removed from the atmosphere through precipitation and used in photosynthesis, but blocking sunlight primarily prevents the process that produces organic compounds. Students should know photosynthesis as the entry point of energy into virtually all ecosystems.',
    },
    {
      number: 13,
      part: 'A',
      text: 'The Madagascar rose periwinkle, a species of rainforest flower that was used to treat cancer, is now endangered in its native habitat due to deforestation. Continuing the destruction of rainforests is likely to have a negative impact on future medical discoveries because it could cause a decrease in the',
      choices: [
        'growing season for rainforest species',
        'biodiversity of the rainforest ecosystem',
        'land available to cultivate new plants',
        'amount of carbon dioxide in the atmosphere',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Deforestation reduces biodiversity by destroying habitats and causing extinctions; since many medicines come from unique plant species, loss of biodiversity threatens future medical discoveries.',
      diveDeep: 'Biodiversity provides an enormous "genetic library" of potentially useful compounds. Approximately 25% of modern pharmaceuticals come from plant-derived compounds discovered from studying rainforest species. When species go extinct due to deforestation, those unique chemical compounds — which might have cured diseases — are lost forever. This is a strong economic and medical argument for biodiversity conservation. Students should connect biodiversity loss to practical human consequences beyond just ecological impacts. The Madagascar periwinkle produces vincristine and vinblastine, used to treat childhood leukemia and Hodgkin\'s disease. CO₂ increases (not decreases) with deforestation.',
    },
    {
      number: 14,
      part: 'A',
      text: 'The letters in the diagram below indicate some parts of a cell. B C D A Which structure provides the energy needed for protein synthesis?',
      choices: [
        'A',
        'C',
        'B',
        'D',
      ],
      topic: 'Cell Biology',
      correct: 0,
      image: '/images/exams/le-august-2025/q14.png',
      explanation: 'Structure A is the mitochondrion, which produces ATP (cellular energy) through cellular respiration; this energy is required for the synthesis of proteins at ribosomes.',
      diveDeep: 'Cellular energy (ATP) is produced primarily by mitochondria through aerobic cellular respiration: glucose + oxygen → CO₂ + water + ATP. Protein synthesis (translation) occurs at ribosomes and requires ATP energy to form peptide bonds and move the ribosome along mRNA. Without mitochondrial energy production, protein synthesis cannot proceed. The other major cell structures: nucleus (contains DNA, site of transcription); ribosomes (site of translation/protein synthesis — they build proteins but need energy FROM mitochondria); vacuoles (storage). Students should know the key organelles, their functions, and how they interact. On diagrams, identify mitochondria by their double-membrane folded structure (cristae).',
    },
    {
      number: 15,
      part: 'A',
      text: 'One reason why some organisms, such as insects, evolve much faster than others is because they',
      choices: [
        'undergo physical changes during development',
        'have very short reproductive cycles',
        'are sometimes exposed to predators that cause mutations',
        'produce offspring only by asexual reproduction',
      ],
      topic: 'Cell Biology',
      correct: 1,
      image: '/images/exams/le-august-2025/q15.png',
      explanation: 'Organisms with short reproductive cycles (like insects) go through many more generations per year, so evolution (change in allele frequencies through natural selection) occurs faster because there are more opportunities for selection to act.',
      diveDeep: 'Evolution occurs through changes in allele frequencies across generations. The more generations per unit time, the faster evolution can proceed. Insects may complete dozens of generations per year; mammals might complete one or less. This is why antibiotic resistance evolves rapidly in bacteria (millions of generations per year) and why insects quickly develop resistance to pesticides. Physical changes during development (metamorphosis) are not inherited and do not drive evolution. Predators create selection pressure but do NOT cause mutations — they select among existing mutations. Asexual reproduction actually reduces genetic variation and can slow evolution.',
    },
    {
      number: 16,
      part: 'A',
      text: 'The diagram below represents a metabolic process involving amino acids represented by AA. AA AA AA AA AA AA AA AA Where in a cell would this process most likely take place?',
      choices: [
        'ribosome',
        'chloroplast',
        'mitochondrion',
        'vacuole',
      ],
      topic: 'Cell Biology',
      correct: 0,
      image: '/images/exams/le-august-2025/q16.png',
      explanation: 'Ribosomes are the cellular organelles where amino acids are assembled (linked by peptide bonds) into polypeptide chains (proteins) during the process of translation.',
      diveDeep: 'The central dogma of molecular biology: DNA (nucleus) → mRNA (transcription) → protein (translation at ribosomes). Ribosomes are the molecular machines that read mRNA sequences and assemble amino acids in the correct order to form proteins. This process (translation) uses energy from ATP (produced by mitochondria). Chloroplasts perform photosynthesis (in plant cells). Mitochondria perform cellular respiration. Vacuoles store materials (water, waste, food). Protein synthesis (joining amino acids) = ribosome. Students should know: where is each process carried out? Photosynthesis → chloroplast; respiration → mitochondria; protein synthesis → ribosome; DNA replication/transcription → nucleus.',
    },
    {
      number: 17,
      part: 'A',
      text: 'Fossil fuels are considered nonrenewable because',
      choices: [
        'oil and coal are being used at an increasing rate',
        'people are becoming more interested in buying energy-efficient vehicles',
        'oil and coal are no longer being formed at a significant rate',
        'Earth\'s supply of nuclear fuels is finite',
      ],
      topic: 'Evolution',
      correct: 2,
      image: '/images/exams/le-august-2025/q17.png',
      explanation: 'Fossil fuels are considered nonrenewable because they formed over millions of years from ancient organic matter and are not being replenished at any significant rate relative to the rate of human consumption.',
      diveDeep: 'Nonrenewable resources are depleted faster than they can be regenerated. Fossil fuels (coal, oil, natural gas) took millions of years to form from compressed organic matter. While technically fossil fuels are still forming today, the formation rate is essentially zero on human timescales — we are consuming millions of years\' worth of stored energy in just centuries. The rate of use increasing (choice A) makes depletion faster, but the fundamental reason for nonrenewability is the formation rate disparity. Nuclear fuel (choice D) is separate from fossil fuels. Students should clearly understand the definition of nonrenewable: consumed faster than formed, regardless of how much is left.',
    },
    {
      number: 18,
      part: 'A',
      text: 'The male emperor penguin cares for his unhatched egg for a long period of time by resting it upon his feet and against his body. This behavior in the male penguins most likely developed over time because the behavior',
      choices: [
        'attracted female penguins for mating',
        'increased the rate of natural selection',
        'increased reproductive success',
        'led to increased predation',
      ],
      topic: 'Reproduction',
      correct: 2,
      explanation: 'Behaviors that increase reproductive success — ensuring offspring survive to reproduce — are naturally selected for over time; male brooding behavior protects eggs from Antarctica\'s extreme cold, dramatically increasing chick survival.',
      diveDeep: 'Natural selection favors any trait (physical or behavioral) that increases an individual\'s reproductive success (survival and reproduction of viable offspring). In Antarctica\'s extreme cold, penguin eggs would quickly freeze without the parent\'s body heat. The brooding behavior allows the egg to survive and hatch, directly increasing the number of offspring that survive. Over many generations, individuals with stronger brooding instincts had more surviving offspring, spreading this behavior through the population. This is an example of behavioral evolution through natural selection. Students should connect behavior to reproductive success and understand that evolution acts on any heritable trait that affects survival or reproduction.',
    },
    {
      number: 19,
      part: 'A',
      text: 'Many advertisements warn pregnant women of the dangers of exposure to certain risk factors because these factors may',
      choices: [
        'cause mutations in the ovary of the mother and thus change the genetic makeup of the developing fetus',
        'cause mutations in the blood cells of the mother and thus change the genetic makeup of the fetus',
        'cause changes in the stomach cells of the mother, which would result in a clone of her fetus',
        'cause organs in the fetus to develop abnormally',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'Environmental risk factors (alcohol, drugs, certain medications, radiation) can directly affect fetal cells during critical periods of organ development, causing developmental abnormalities.',
      diveDeep: 'Environmental teratogens (substances that cause birth defects) act directly on the developing fetus by crossing the placenta and disrupting fetal cell development. They do NOT change the mother\'s genetic information or the fetus\'s DNA sequence — they disrupt developmental processes. Examples: thalidomide caused limb defects; alcohol causes fetal alcohol syndrome; rubella virus causes heart defects. Mutations in the mother\'s somatic cells (blood cells, stomach cells) are not inherited by the fetus — only mutations in egg cells would be heritable. Students must understand: somatic mutations are NOT passed to offspring; only germ cell mutations are heritable. Environmental factors during pregnancy affect development, not inheritance.',
    },
    {
      number: 20,
      part: 'A',
      text: 'When a colony of bacteria was exposed to a particular antibiotic, some of the bacteria survived while others did not. Which concept is supported by this example?',
      choices: [
        'Biotic factors in the environment influence gene expression.',
        'Favorable mutations occur as a result of environmental changes.',
        'Overproduction limits genetic variation.',
        'Some variations in a population have an adaptive value.',
      ],
      topic: 'Ecology',
      correct: 3,
      image: '/images/exams/le-august-2025/q20.png',
      explanation: 'Some bacteria in the population already had genetic variations (resistance mutations) that gave them an adaptive advantage — they survived the antibiotic while others died, demonstrating that some variations have adaptive value.',
      diveDeep: 'Antibiotic resistance evolution is the clearest real-world demonstration of natural selection: (1) variation exists in the population (some bacteria randomly had resistance mutations before exposure); (2) antibiotic = selection pressure; (3) bacteria with resistance survive and reproduce (selection for the favorable variation); (4) resistance spreads through the population. The key misconception addressed in choice B: mutations do NOT occur in response to the environment — they are random and pre-existing. The antibiotic selects among pre-existing variations; it does not create new mutations. Students must clearly understand: natural selection acts on existing variation, it does not direct mutation.',
    },
    {
      number: 21,
      part: 'A',
      text: 'When uncooked meat is tenderized using pineapple juice, specific organic molecules in the meat are broken down. This reaction occurs because the pineapple juice most likely contains',
      choices: [
        'antibodies that preserve the meat',
        'hormones that influence cell division',
        'enzymes that alter the structure of proteins',
        'sugars that metabolize starches',
      ],
      topic: 'General',
      correct: 2,
      image: '/images/exams/le-august-2025/q21.png',
      explanation: 'Pineapple juice contains bromelain, a protease enzyme that breaks down the protein molecules in meat, making it tender by disrupting the protein structures that give meat its toughness.',
      diveDeep: 'Enzymes are biological catalysts — proteins that speed up specific chemical reactions without being consumed. Bromelain (from pineapple) and papain (from papaya) are proteases — enzymes that break down proteins by hydrolyzing peptide bonds. This specific enzyme-substrate interaction explains meat tenderizing: the tough connective tissue proteins (collagen, myosin) are broken down by the enzyme. Enzymes work because their active site has a specific shape that fits the substrate (lock-and-key model). Antibodies recognize foreign proteins; they do not digest them in this way. Hormones signal cells; they do not digest proteins. Students should identify enzyme-catalyzed reactions by looking for specific breakdown of biological molecules.',
    },
    {
      number: 22,
      part: 'A',
      text: 'One factor that might threaten global stability and alter the equilibrium in an ecosystem is increasing',
      choices: [
        'the rate of reforestation',
        'biodiversity',
        'recycling',
        'the rate of climate change',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'Increasing the rate of climate change disrupts established ecosystems by shifting temperature and precipitation patterns faster than species can adapt, threatening the stability of ecosystems worldwide.',
      diveDeep: 'Ecosystems maintain a dynamic equilibrium through checks and balances among species. Rapid climate change can exceed the ability of species to adapt or migrate, leading to population crashes, extinctions, and food web disruptions. Reforestation, biodiversity, and recycling all generally enhance ecosystem stability and resilience. Climate change causes: habitat loss (coral bleaching, glacier melt, permafrost thaw), range shifts, phenological mismatches (e.g., insects hatching before plant flowers), and increased extreme weather events. Students should identify factors that increase vs. decrease ecosystem stability. Generally: more biodiversity = more stability; more pollution/climate change/habitat destruction = less stability.',
    },
    {
      number: 23,
      part: 'A',
      text: 'Which group of organisms would be at the greatest risk of extinction if they were infected by a deadly virus?',
      choices: [
        'a small population of a bird species found only on Martha\'s Vineyard island',
        'a population of squirrels living in Los Angeles, California',
        'all pigeons living in parks in Florida',
        'all the rabbits living in Kinderhook, New York',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'A small population of a bird species found only on one isolated island (Martha\'s Vineyard) is at the greatest risk because small population size, limited geographic range, and genetic uniformity all contribute to extinction vulnerability.',
      diveDeep: 'Extinction risk factors include: (1) small population size — less genetic diversity, fewer individuals to survive stochastic events; (2) restricted geographic range — a single disaster (virus, hurricane) can eliminate the entire population; (3) low genetic diversity — limited variation means fewer individuals may have resistance to a new pathogen. The Martha\'s Vineyard bird scores high on all three risk factors. Squirrels in LA are widely distributed; Florida pigeons are a widespread species; Kinderhook rabbits are a local population of a widespread species. Island species (like Hawaiian honeycreepers or Galapagos tortoises) are among the most extinction-prone. Students should know the factors that increase extinction risk.',
    },
    {
      number: 24,
      part: 'A',
      text: 'When a person gets a tattoo and the needle used is contaminated with a pathogen, how does the human immune system respond?',
      choices: [
        'It produces hormones.',
        'It digests white blood cells.',
        'It produces more white blood cells.',
        'It digests antibiotics.',
      ],
      topic: 'Human Body',
      correct: 2,
      explanation: 'When a pathogen enters the body, the immune system responds by producing more white blood cells (leukocytes), which attack and destroy the invading pathogen through phagocytosis and antibody production.',
      diveDeep: 'The immune response involves multiple components: white blood cells (leukocytes) including B-cells (produce antibodies), T-cells (kill infected cells), and phagocytes (engulf and destroy pathogens). When a pathogen enters through a contaminated tattoo needle, the immune system detects foreign antigens and mounts a response: increased production of white blood cells, activation of phagocytes, and antibody production. Hormones (like epinephrine) are produced by endocrine glands for different purposes (stress response). Antibiotics are medications — the body does not produce or digest them. Students should know the key immune system players: antibodies (fight specific antigens), white blood cells (general and specific defense), and the inflammatory response.',
    },
  ],
}
