// Living Environment Regents — August 2021
export default {
  id: 'le-august-2021',
  subject: 'living-environment',
  year: 2021,
  session: 'August',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'Which statement about enzymes is correct?',
      choices: [
        'Enzymes are consumed during chemical reactions and must be replaced.',
        'Enzymes lower the activation energy needed for a reaction to proceed.',
        'Enzymes work best at very high temperatures and low pH.',
        'Each enzyme can catalyze any type of chemical reaction in a cell.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Enzymes are biological catalysts that lower activation energy, allowing reactions to proceed faster without being used up. They are highly specific — each enzyme catalyzes only one type of reaction.',
      diveDeep: 'Enzymes work by binding substrates at their active site, forming an enzyme-substrate complex. This binding strains chemical bonds in the substrate, lowering the activation energy needed for the reaction. Because enzymes are not consumed or permanently altered, a single enzyme molecule can catalyze thousands of reactions per second. Enzyme specificity arises from the precise 3D shape of the active site — only substrates with a complementary shape fit (the induced fit model). Factors such as temperature, pH, and inhibitors affect enzyme activity by altering this 3D shape.',
    },
    {
      number: 2, part: 'A',
      text: 'A food chain in a pond ecosystem is: algae → water fleas → small fish → large fish. Which organisms in this food chain are producers?',
      choices: [
        'water fleas',
        'algae',
        'small fish',
        'large fish',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Algae are producers (autotrophs) because they carry out photosynthesis to make their own organic molecules from sunlight, CO₂, and water. All other organisms in the chain are consumers.',
      diveDeep: 'Producers form the base of every food chain and food web. In aquatic ecosystems, algae and other phytoplankton are the primary producers, fixing solar energy through photosynthesis. All consumers ultimately depend on this fixed energy. Energy is lost at each trophic level (approximately 90% per level), which is why producers must be extremely abundant relative to top predators. Algae are also responsible for producing a significant portion of Earth\'s atmospheric oxygen through photosynthesis.',
    },
    {
      number: 3, part: 'A',
      text: 'In humans, the large intestine absorbs water from undigested food, and the kidneys filter blood to remove waste. Both of these functions contribute to',
      choices: [
        'the production of energy through cellular respiration',
        'maintaining homeostasis by regulating water and waste levels in the body',
        'the immune response to bacterial infections',
        'the production of new blood cells for circulation',
      ],
      topic: 'Human Body',
      correct: 1,
      explanation: 'Both water absorption (large intestine) and waste removal (kidneys) are mechanisms that regulate the internal environment of the body, maintaining the water and solute balance needed for homeostasis.',
      diveDeep: 'Homeostasis requires coordinated activity of multiple organ systems. The kidneys are central to osmoregulation — filtering about 180 liters of blood plasma per day and producing urine by selectively reabsorbing water, glucose, and ions while excreting waste products such as urea. The large intestine reclaims water from digestive waste to prevent dehydration. Both processes are regulated by hormones: ADH (antidiuretic hormone) increases water reabsorption by kidneys during dehydration, and aldosterone regulates sodium and water balance.',
    },
    {
      number: 4, part: 'A',
      text: 'Which statement best explains why a child may have a different combination of traits than either of their parents?',
      choices: [
        'Children inherit traits from their environment rather than from their parents.',
        'Meiosis and fertilization produce unique combinations of alleles in each offspring.',
        'Children always inherit the dominant trait from each parent.',
        'Traits are randomly assigned to offspring during fertilization.',
      ],
      topic: 'Genetics',
      correct: 1,
      explanation: 'During meiosis, crossing over and independent assortment shuffle alleles, and fertilization combines one unique gamete from each parent, producing offspring with novel allele combinations not seen in either parent.',
      diveDeep: 'Genetic variation in sexually reproducing organisms arises from three sources: (1) crossing over during prophase I of meiosis shuffles alleles between homologous chromosomes; (2) independent assortment during meiosis I randomly distributes maternal and paternal chromosomes to gametes (2²³ combinations in humans); (3) random fertilization combines one of millions of possible gametes from each parent. This immense variation means that no two offspring (except identical twins) are genetically identical, providing the raw material for natural selection and evolution.',
    },
    {
      number: 5, part: 'A',
      text: 'An organism\'s niche refers to its',
      choices: [
        'physical location in the ecosystem',
        'role and activities in the ecosystem, including what it eats and how it interacts with other species',
        'ability to survive in different environments',
        'genetic makeup that determines its traits',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'An organism\'s niche is its functional role in the ecosystem — encompassing what it eats, when it is active, how it interacts with other species, and what environmental conditions it requires. It is more than just where it lives (its habitat).',
      diveDeep: 'G. Evelyn Hutchinson defined the niche as an n-dimensional hypervolume: the set of all biotic and abiotic conditions under which an organism can survive and reproduce. The fundamental niche is the full range of conditions an organism could theoretically occupy; the realized niche is the actual range, constrained by competition and predation. No two species can occupy exactly the same niche indefinitely (competitive exclusion principle); species partition resources through niche differentiation to coexist. The concept of niche is central to understanding competition, predator-prey relationships, and community structure.',
    },
    {
      number: 6, part: 'A',
      text: 'A researcher finds that the bones of a bird\'s wing are similar in arrangement to the bones in a human arm and a dolphin\'s flipper. This similarity in structure suggests that',
      choices: [
        'birds, humans, and dolphins all use their limbs for the same purpose',
        'birds, humans, and dolphins share a common ancestor',
        'the similarity is a coincidence with no evolutionary significance',
        'all vertebrates evolved from dolphins',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Homologous structures — body parts with the same underlying bone arrangement inherited from a common ancestor but used for different functions — are strong evidence of evolutionary relationships. Birds, humans, and dolphins all descend from a common vertebrate ancestor.',
      diveDeep: 'Homologous structures are defined by their underlying anatomical plan (bone arrangement, embryonic origin), not their function. The pentadactyl limb (five-digit limb structure) is found across all tetrapods and is inherited from a common Devonian ancestor. Contrast with analogous structures (convergent evolution) — similar function but different evolutionary origin (e.g., bird wings and insect wings). Molecular evidence (DNA and protein sequences) confirms relationships suggested by homologous structures and provides quantitative measures of evolutionary divergence time.',
    },
    {
      number: 7, part: 'A',
      text: 'Which event would most likely lead to an increase in the biodiversity of an ecosystem?',
      choices: [
        'the introduction of a highly competitive invasive species',
        'the restoration of a wetland that had been drained for development',
        'the application of an herbicide that kills most plant species',
        'the removal of all predator species from the ecosystem',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Restoring a wetland creates diverse habitats (open water, marsh, meadow) that support a wide variety of species. The other choices all reduce biodiversity by eliminating species or enabling one organism to dominate.',
      diveDeep: 'Wetland restoration is one of the most effective tools for increasing regional biodiversity. Wetlands are among the most species-rich biomes — they provide breeding habitat for amphibians, nesting areas for waterfowl, feeding grounds for migratory birds, nurseries for fish, and diverse plant communities. Wetlands also provide ecosystem services: water filtration, flood control, and carbon storage. Drainage for agriculture has destroyed over half of the world\'s wetlands historically, making restoration critical for reversing biodiversity loss.',
    },
    {
      number: 8, part: 'A',
      text: 'During DNA replication, the sequence of bases in the new DNA strand is determined by',
      choices: [
        'the sequence of bases in the original (template) DNA strand',
        'the type of enzyme that carries out replication',
        'the number of chromosomes in the cell',
        'random chance, producing variation in the new strand',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'DNA replication follows the base-pairing rules (A–T, G–C): each base on the template strand specifies its complementary base in the new strand, ensuring accurate copying of the genetic information.',
      diveDeep: 'DNA replication is semiconservative: each new DNA molecule consists of one original strand and one newly synthesized strand. The enzyme DNA polymerase reads the template strand in the 3′→5′ direction and synthesizes the new strand in the 5′→3′ direction, adding complementary nucleotides. The leading strand is synthesized continuously; the lagging strand is synthesized in short Okazaki fragments joined by DNA ligase. Replication fidelity is extremely high (one error per 10⁹–10¹⁰ bases) due to proofreading activity of DNA polymerase.',
    },
    {
      number: 9, part: 'A',
      text: 'In 2019, the World Health Organization identified antibiotic resistance as one of the top ten threats to global health. Which human behavior has most directly contributed to the development of antibiotic resistance?',
      choices: [
        'using antibiotics to treat viral infections such as the flu',
        'completing the full course of antibiotics when prescribed',
        'washing hands frequently to prevent the spread of bacteria',
        'using vaccines to prevent bacterial infections',
      ],
      topic: 'Evolution',
      correct: 0,
      explanation: 'Antibiotics do not kill viruses; using them for viral infections unnecessarily exposes bacterial populations to antibiotics, selecting for resistant strains without any therapeutic benefit.',
      diveDeep: 'Antibiotic resistance evolves through natural selection: bacteria with random mutations that confer resistance survive antibiotic exposure and reproduce, while sensitive bacteria are killed. Misuse of antibiotics (treating viral infections, not completing courses, over-use in agriculture) accelerates this process. When antibiotics are used for viral infections, they kill beneficial bacteria in the body while selecting for resistance in any bacteria present, with no effect on the virus. The WHO estimates that antimicrobial resistance could cause 10 million deaths per year by 2050 if current trends continue.',
    },
    {
      number: 10, part: 'A',
      text: 'Which statement about mutations is correct?',
      choices: [
        'All mutations are harmful and decrease the survival of an organism.',
        'Mutations always improve the fitness of an organism in its environment.',
        'Mutations can be harmful, neutral, or beneficial depending on the environment.',
        'Mutations cannot be inherited by offspring.',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'Most mutations are neutral (no effect on fitness), some are harmful (reduce survival or reproduction), and a few are beneficial in specific environments. The effect of a mutation depends on the environmental context.',
      diveDeep: 'Mutations are random changes in DNA sequence — they are not directed by environmental needs. Types include point mutations (single base changes: silent, missense, nonsense), insertions, deletions, and chromosomal rearrangements. Most mutations in non-coding regions or that produce synonymous codons are neutral. Harmful mutations reduce fitness; beneficial mutations increase it in a specific environment (e.g., sickle-cell trait provides malaria resistance in endemic regions). Only mutations in germ cells (eggs and sperm) are heritable; somatic (body cell) mutations affect only the individual.',
    },
    {
      number: 11, part: 'A',
      text: 'The release of industrial pollutants into a river can cause the death of fish in that river. This is because pollutants can change the',
      choices: [
        'genetic makeup of fish, making them unable to reproduce',
        'abiotic factors in the river, making them unsuitable for the fish',
        'biotic factors in the river, increasing competition among fish',
        'rate of photosynthesis, causing fish to grow too quickly',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Industrial pollutants change abiotic factors such as water pH, oxygen levels, temperature, and chemical composition, making the physical environment unsuitable for fish survival.',
      diveDeep: 'Abiotic factors (non-living components) include temperature, pH, dissolved oxygen, salinity, light, and chemical composition. Pollutants can alter these in multiple ways: acidic runoff lowers pH; eutrophication from nutrient pollution (algal blooms) depletes dissolved oxygen; heavy metals and organic chemicals are directly toxic. Fish have narrow tolerance ranges for many abiotic factors — small changes outside these ranges impair respiration, osmoregulation, and reproduction. Biological oxygen demand (BOD) is a measure of how much oxygen is consumed by decomposers breaking down organic pollutants, and high BOD can suffocate fish.',
    },
    {
      number: 12, part: 'A',
      text: 'Which process transfers energy from organic molecules to ATP, which cells can use directly?',
      choices: [
        'photosynthesis',
        'transcription',
        'cellular respiration',
        'active transport',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Cellular respiration breaks down glucose and other organic molecules in a series of reactions, harvesting the energy stored in their chemical bonds and transferring it to ATP, the cell\'s primary energy currency.',
      diveDeep: 'Aerobic cellular respiration occurs in three stages: glycolysis (cytoplasm, produces 2 ATP per glucose), the Krebs cycle (mitochondrial matrix, produces 2 ATP + NADH + FADH₂ per glucose), and the electron transport chain/oxidative phosphorylation (inner mitochondrial membrane, produces ~32–34 ATP per glucose using the proton gradient to drive ATP synthase). The overall equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~36 ATP. Without oxygen (anaerobic conditions), fermentation regenerates NAD⁺ to keep glycolysis running, producing only 2 ATP.',
    },
    {
      number: 13, part: 'A',
      text: 'A plant that grows toward light is demonstrating',
      choices: [
        'negative feedback',
        'an instinctive behavior',
        'a tropism — a growth response to an environmental stimulus',
        'natural selection',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Phototropism is a plant\'s directional growth response to light — cells on the shaded side elongate more, bending the shoot toward the light source. Tropisms are directed growth responses to environmental stimuli.',
      diveDeep: 'Plant tropisms are mediated by hormones. In phototropism, the hormone auxin (IAA) is redistributed to the shaded side of the shoot tip, causing those cells to elongate more than cells on the lit side, bending the shoot toward light. Other tropisms include gravitropism (roots grow down, shoots grow up in response to gravity) and thigmotropism (growth response to touch, e.g., climbing vines). These responses are adaptive: growing toward light maximizes photosynthesis, while roots growing downward maximizes water and nutrient absorption.',
    },
    {
      number: 14, part: 'A',
      text: 'Biodiversity in an ecosystem contributes to its stability because',
      choices: [
        'each species performs a unique role, and the loss of one species can affect many others',
        'more species means less competition, which reduces predation',
        'higher biodiversity means fewer pathogens and diseases in the ecosystem',
        'biodiversity increases the amount of energy available in the ecosystem',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'High biodiversity means many species fill different ecological roles; when one is lost, others may compensate (redundancy), and the complex web of interactions buffers the ecosystem against collapse.',
      diveDeep: 'Ecological stability has two components: resistance (ability to withstand disturbance) and resilience (ability to recover after disturbance). Both are generally enhanced by biodiversity. Functional redundancy — multiple species performing similar ecological roles — provides insurance against species loss. Complex food webs with many connections are more stable because predators have alternative prey and producers have diverse consumers. Research in grassland ecosystems (e.g., Cedar Creek, Minnesota) shows that more diverse plots produce more biomass, use resources more efficiently, and recover more quickly from drought.',
    },
    {
      number: 15, part: 'A',
      text: 'The body temperature of a healthy adult human remains at approximately 37°C. When the temperature rises, mechanisms such as sweating and blood vessel dilation reduce it back to normal. This is an example of',
      choices: [
        'positive feedback — the body increases the deviation from normal',
        'negative feedback — the body detects a change and acts to reverse it',
        'active transport — the body uses energy to move heat out of cells',
        'ecological succession — the body gradually adapts to higher temperatures',
      ],
      topic: 'Human Body',
      correct: 1,
      explanation: 'Negative feedback is when a system detects a deviation from the set point and initiates a corrective response to reverse that deviation. Sweating and vasodilation cool the body, returning temperature to normal — a classic negative feedback loop.',
      diveDeep: 'Thermoregulation in humans is controlled by the hypothalamus, which acts as the body\'s thermostat. When body temperature rises: sweat glands produce sweat (evaporative cooling) and blood vessels in the skin dilate (vasodilation, releasing heat). When temperature falls: shivering generates heat through muscle contractions and blood vessels constrict (vasoconstriction, conserving heat). Contrast with positive feedback, which amplifies a change (e.g., oxytocin during childbirth: contractions trigger more oxytocin release → stronger contractions). Negative feedback is the dominant mechanism maintaining homeostasis in most physiological systems.',
    },
    {
      number: 16, part: 'A',
      text: 'Which statement best explains why organisms in higher trophic levels of a food chain generally have smaller population sizes than those at lower trophic levels?',
      choices: [
        'Higher-level organisms reproduce more slowly than lower-level organisms.',
        'Less energy is available at higher trophic levels because energy is lost at each level.',
        'Higher-level organisms require more territory and therefore have smaller populations.',
        'Predators at higher trophic levels keep their own populations small through competition.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Approximately 90% of energy is lost as heat at each trophic level transfer; with progressively less energy available at higher levels, fewer individuals can be supported at those levels.',
      diveDeep: 'The 10% rule means that a food chain starting with 10,000 kcal of plant biomass can support only ~1,000 kcal of herbivore biomass, ~100 kcal of primary carnivore biomass, and ~10 kcal of secondary carnivore biomass. This energetic constraint explains why energy pyramids always taper toward the apex and why top predators are necessarily rare. It also explains why human diets that include lower trophic levels (plant-based) can support more people per unit land area than diets centered on top carnivores.',
    },
    {
      number: 17, part: 'A',
      text: 'Scientists have used cloning technology to clone endangered species. A potential risk of this technology is that',
      choices: [
        'cloned animals have different DNA than the original animal',
        'cloned animals cannot reproduce sexually',
        'a cloned population with little genetic diversity could be wiped out by a single disease',
        'cloning produces animals that age twice as fast as naturally born animals',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'A cloned population derived from a single individual has very low genetic diversity; if a disease or environmental change affects one individual, it will likely affect all, risking total population extinction.',
      diveDeep: 'Genetic diversity within a population is essential for survival as a species. A population of genetically identical clones lacks variation in disease resistance, immune function, and environmental tolerance. A single novel pathogen could sweep through the entire population because all individuals have the same (or very similar) immune genes. This is exemplified by monoculture agriculture: the Irish Potato Famine was partly caused by a lack of genetic diversity in the potato crop, allowing a single pathogen (Phytophthora infestans) to destroy nearly the entire harvest. Conservation genetics emphasizes maintaining genetic diversity to ensure long-term population survival.',
    },
    {
      number: 18, part: 'A',
      text: 'Which combination of processes most directly removes carbon dioxide from the atmosphere?',
      choices: [
        'cellular respiration and decomposition',
        'photosynthesis and absorption by ocean water',
        'volcanic eruptions and burning of forests',
        'transpiration and evaporation',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Photosynthesis by plants, algae, and cyanobacteria incorporates CO₂ into organic molecules. Ocean water also dissolves CO₂, forming carbonic acid. Both processes are major carbon sinks that remove CO₂ from the atmosphere.',
      diveDeep: 'The global carbon cycle involves both sources (processes that release CO₂: respiration, decomposition, combustion, volcanic activity) and sinks (processes that remove CO₂: photosynthesis, ocean dissolution, weathering of silicate rocks). Terrestrial plants and phytoplankton absorb approximately 120 Gt of carbon per year through photosynthesis. Oceans absorb approximately 26% of human CO₂ emissions through dissolution. However, ocean CO₂ absorption has consequences: dissolved CO₂ forms carbonic acid, lowering ocean pH (ocean acidification), which threatens shell-forming organisms.',
    },
    {
      number: 19, part: 'A',
      text: 'The nucleus of a cell contains chromosomes made of DNA. The chromosomes contain genes, which are specific segments of DNA. Genes provide instructions for the synthesis of',
      choices: [
        'carbohydrates that store energy for cell processes',
        'lipids that form the phospholipid bilayer of cell membranes',
        'proteins that carry out cell functions',
        'nucleotides that make up new DNA molecules',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'The central dogma of molecular biology states that genes (DNA sequences) are transcribed into mRNA and then translated into proteins. Proteins are the primary functional molecules that carry out virtually all cell activities.',
      diveDeep: 'The human genome contains approximately 20,000–25,000 protein-coding genes. These genes direct the synthesis of structural proteins (collagen, keratin), enzymes (catalyzing metabolic reactions), transport proteins (hemoglobin, membrane channels), regulatory proteins (transcription factors, hormones), and immune proteins (antibodies). The same DNA is present in every cell of the body, but differential gene expression — controlled by transcription factors, epigenetic modifications, and signaling molecules — determines what proteins each cell type produces, creating the diversity of cell types from neurons to muscle cells to white blood cells.',
    },
    {
      number: 20, part: 'A',
      text: 'A scientist discovers a new species of fish in a deep ocean trench. This fish produces light using a process that does not require oxygen. This most likely means the fish',
      choices: [
        'carries out photosynthesis to produce the light',
        'carries out a form of fermentation or anaerobic respiration to produce the light',
        'absorbs light from the surface and stores it for later use',
        'uses oxygen from the water around it during normal cellular respiration',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Deep ocean trenches are anoxic (no oxygen) environments; a fish living there would need to extract energy from organic molecules through anaerobic pathways (fermentation or anaerobic respiration) to power bioluminescence.',
      diveDeep: 'Bioluminescence in deep-sea organisms (anglerfish, some bacteria, jellyfish) is produced by luciferase enzymes that oxidize luciferin compounds, releasing light. In the deep ocean (below 200 m), there is no sunlight and often very little oxygen. Organisms adapted to these environments may use anaerobic respiration or fermentation pathways. Fermentation regenerates NAD⁺ by using pyruvate (from glycolysis) as an electron acceptor, producing lactic acid or ethanol. This yields only 2 ATP per glucose vs. ~36 ATP from aerobic respiration, but functions without oxygen.',
    },
    {
      number: 21, part: 'A',
      text: 'In a population of rabbits, most have brown fur but a few have white fur. A new predator (a hawk) moves into the area and hunts rabbits in a grassy, brown field. Over several generations, the proportion of brown rabbits increases significantly. This change is best explained by',
      choices: [
        'the rabbits with white fur intentionally changed their fur color to avoid predators',
        'the hawk hunted white rabbits preferentially because they were easier to see, reducing the white rabbit population',
        'natural selection against brown rabbits because they were harder for the hawk to see',
        'a mutation that changed white fur genes to brown fur genes in the white rabbit population',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'White rabbits are more visible on brown grass and are preferentially predated by hawks; they survive and reproduce less, so the white fur allele decreases in frequency over generations — a textbook example of natural selection.',
      diveDeep: 'This scenario illustrates directional selection: selection pressure favors one extreme of the phenotypic range (brown fur) over the other (white fur). Key points: (1) fur color variation already existed in the population before the hawk arrived; (2) the hawk did not cause mutations — it simply acted as a selective agent; (3) the change is gradual over many generations as white rabbits leave fewer offspring; (4) brown fur is adaptive in this environment, not in all environments (white fur would be advantageous in snowy conditions). This is analogous to the peppered moth case study in industrial England.',
    },
    {
      number: 22, part: 'A',
      text: 'The process by which segments of DNA are used as a template to produce messenger RNA is called',
      choices: [
        'replication',
        'translation',
        'transcription',
        'mutation',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Transcription is the process by which RNA polymerase reads a DNA template strand and synthesizes a complementary mRNA molecule, which then carries the genetic information to ribosomes for protein synthesis.',
      diveDeep: 'Transcription occurs in the nucleus in eukaryotes and in the cytoplasm in prokaryotes. RNA polymerase binds to the promoter region of a gene and unwinds the DNA double helix. It synthesizes mRNA in the 5′→3′ direction using one DNA strand (the template/antisense strand) as a guide, following A–U (adenine–uracil) and G–C base-pairing rules (note: RNA uses uracil instead of thymine). In eukaryotes, the primary mRNA transcript (pre-mRNA) is processed before leaving the nucleus: a 5′ cap and poly-A tail are added, and introns are spliced out. The mature mRNA then directs protein synthesis at ribosomes.',
    },
    {
      number: 23, part: 'A',
      text: 'The use of pesticides in agriculture can harm non-target organisms such as birds that eat insects. This illustrates that',
      choices: [
        'pesticides should always be banned from agricultural use',
        'technological decisions can have broad environmental consequences',
        'birds should not live near agricultural areas',
        'non-target organisms are always more sensitive to pesticides than target organisms',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'This illustrates that technological interventions (pesticide use) often have unintended consequences that extend beyond the target organism, affecting other species and the broader ecosystem.',
      diveDeep: 'The concept of trade-offs in technology applies here: pesticides increase crop yields (benefit) but kill beneficial insects, contaminate water, and harm non-target species (costs). Bioaccumulation and biomagnification amplify pesticide effects up the food chain — a phenomenon dramatically illustrated by DDT\'s impact on bald eagles. Today\'s Integrated Pest Management (IPM) strategies attempt to minimize pesticide use by combining biological control, habitat manipulation, resistant crop varieties, and targeted application, reducing broad environmental impacts while maintaining crop protection.',
    },
    {
      number: 24, part: 'A',
      text: 'Stem cells are cells that have not yet differentiated and can develop into many different cell types. Which characteristic of stem cells makes them potentially useful for treating diseases?',
      choices: [
        'Stem cells divide by meiosis to produce genetically diverse daughter cells.',
        'Stem cells can be directed to become specific cell types to replace damaged cells.',
        'Stem cells produce antibodies that fight all types of diseases.',
        'Stem cells live much longer than differentiated cells.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Stem cells are pluripotent or multipotent — they can be guided by specific growth factors to differentiate into specialized cell types (neurons, heart cells, pancreatic cells) to replace cells lost to disease or injury.',
      diveDeep: 'Stem cells are classified by potency: totipotent (fertilized egg, can form any cell type), pluripotent (embryonic stem cells, can form nearly any cell type), multipotent (adult stem cells, can form several related cell types). Induced pluripotent stem cells (iPSCs), created by reprogramming adult cells with transcription factors, avoid the ethical issues of embryonic stem cells. Therapeutic applications include treating leukemia (bone marrow transplants), Parkinson\'s disease (replacing dopamine neurons), and type 1 diabetes (replacing insulin-producing beta cells). Challenges include preventing immune rejection and controlling differentiation to the desired cell type.',
    },
    {
      number: 25, part: 'A',
      text: 'A population of lizards lives on a small island. A hurricane kills 90% of the population. The survivors have a different allele frequency than the original population. This change in allele frequency due to a random event is called',
      choices: [
        'gene flow',
        'natural selection',
        'genetic drift',
        'mutation',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'Genetic drift is a random change in allele frequencies in a population, not driven by natural selection. The bottleneck effect — a sudden reduction in population size — is one way genetic drift occurs, as demonstrated in this scenario.',
      diveDeep: 'Genetic drift has the greatest effect in small populations, where chance events can dramatically alter allele frequencies. Two specific types: (1) Bottleneck effect — a catastrophic event reduces population size, and the surviving allele frequencies may not represent the original population; (2) Founder effect — a small group establishes a new population, carrying only a subset of the original genetic diversity. Genetic drift can cause rare alleles to disappear or become fixed (100% frequency) entirely by chance, independent of whether they are beneficial or harmful. The cheetah\'s extremely low genetic diversity is attributed to a historical population bottleneck.',
    },
    {
      number: 26, part: 'A',
      text: 'The development of drug-resistant tuberculosis (TB) is a major global health concern. Drug-resistant TB develops because',
      choices: [
        'the TB bacteria intentionally mutate to avoid being killed by drugs',
        'patients who do not complete their antibiotic treatment allow resistant bacteria to survive and reproduce',
        'antibiotics cause the TB bacteria to mutate and become stronger',
        'TB bacteria can share resistance genes with other types of bacteria',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'When patients stop antibiotic treatment early (often because they feel better), the most resistant bacteria — which take longer to kill — survive and reproduce, eventually becoming the dominant strain.',
      diveDeep: 'TB treatment requires 6–9 months of multi-drug antibiotic therapy. Non-adherence is the primary driver of drug resistance. Sub-lethal antibiotic exposure is particularly dangerous: it kills susceptible bacteria but leaves partially resistant ones, selecting for higher resistance with each treatment cycle. Multidrug-resistant TB (MDR-TB) is resistant to the two most effective first-line drugs (isoniazid and rifampicin); extensively drug-resistant TB (XDR-TB) is resistant to most available drugs. WHO\'s Directly Observed Treatment (DOT) strategy requires healthcare workers to watch patients take each dose, significantly reducing resistance development.',
    },
    {
      number: 27, part: 'A',
      text: 'Which statement best explains the importance of decomposers in an ecosystem?',
      choices: [
        'Decomposers produce oxygen that other organisms use for cellular respiration.',
        'Decomposers return nutrients from dead organisms to the environment, making them available to producers.',
        'Decomposers convert atmospheric nitrogen into a form that plants can use for growth.',
        'Decomposers reduce biodiversity by eliminating dead organisms from the ecosystem.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Decomposers (bacteria and fungi) break down dead organic matter and release mineral nutrients (nitrogen, phosphorus, etc.) back into the soil and water, completing nutrient cycles and making them available for producers again.',
      diveDeep: 'Without decomposers, nutrient cycles would cease: carbon, nitrogen, phosphorus, and other elements would remain locked in dead organic matter rather than cycling back to producers. Decomposers secrete extracellular enzymes that break complex organic molecules (proteins, cellulose, lignin) into simpler compounds (amino acids, sugars) that are then absorbed. Nitrogen mineralization (conversion of organic nitrogen to ammonia) by decomposers is a critical step in the nitrogen cycle. The diversity of decomposer communities — including bacteria, fungi, and detritivores — determines decomposition rates and nutrient availability in ecosystems.',
    },
    {
      number: 28, part: 'A',
      text: 'A scientist wants to determine whether a newly developed drug can reduce the symptoms of a disease. She divides 200 patients into two groups: one receives the drug and one receives a placebo. She measures symptom severity in both groups after 4 weeks. Why is the placebo group important?',
      choices: [
        'to test the safety of the placebo for use in future experiments',
        'to serve as a control group that allows comparison against the drug group',
        'to ensure that all 200 patients receive some form of treatment',
        'to determine the optimal dose of the drug for treating the disease',
      ],
      topic: 'Human Body',
      correct: 1,
      explanation: 'The placebo group is the control group — it shows how patients perform without the drug, providing a baseline for comparison. Without a control, it is impossible to know whether any improvement was due to the drug or natural recovery.',
      diveDeep: 'Well-designed clinical trials use double-blind, placebo-controlled designs: neither patients nor researchers know who receives the drug or placebo (double-blind), preventing bias in both the psychological response (placebo effect) and data interpretation. The placebo effect — real physiological improvement due to the belief of being treated — can be substantial (sometimes 30–40% symptom reduction). By comparing drug vs. placebo groups, scientists can isolate the drug\'s specific biological effect. Statistical analysis determines whether the difference between groups is larger than expected by chance alone.',
    },
    {
      number: 29, part: 'A',
      text: 'Scientists have found evidence that all living organisms on Earth share similar genetic code (the same codons code for the same amino acids). This most likely indicates that',
      choices: [
        'all organisms use the same amino acids to make all the same proteins',
        'all life on Earth descended from a common ancestor',
        'the genetic code evolved independently in each species',
        'different species cannot have different DNA sequences',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'A universal genetic code is most parsimoniously explained by a single common ancestor from which all life descended and inherited the same coding system. Independent evolution of the same complex code would be extraordinarily improbable.',
      diveDeep: 'The universality of the genetic code is one of the strongest pieces of evidence for universal common ancestry. The code maps 64 possible codons (combinations of 3 bases) to 20 amino acids plus 3 stop codons. This exact mapping is essentially the same in bacteria, fungi, plants, and animals, implying the code was established very early in the history of life and passed to all descendants. A few minor exceptions exist (e.g., mitochondria use slightly different codons), representing rare evolutionary divergence from the ancestral code. This universality is also what makes genetic engineering possible — a human gene can be expressed in bacteria.',
    },
    {
      number: 30, part: 'A',
      text: 'The loss of tropical rainforest has many environmental consequences. Which consequence would most directly affect the global carbon cycle?',
      choices: [
        'decreased rainfall in tropical regions due to reduced transpiration',
        'increased atmospheric CO₂ due to loss of photosynthetic organisms and decomposition of vegetation',
        'increased biodiversity in agricultural areas that replace the forests',
        'decreased soil fertility due to removal of root systems',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Tropical forests are enormous carbon sinks; their destruction releases stored carbon as CO₂ (from burning and decomposition) and removes photosynthetic capacity that would otherwise absorb CO₂, directly disrupting the global carbon cycle.',
      diveDeep: 'Tropical forests store approximately 460 Gt of carbon in their vegetation and soil — more than all the carbon currently in the atmosphere. Deforestation contributes approximately 10–15% of global greenhouse gas emissions. When forests are cleared by burning, carbon stored in biomass is immediately released as CO₂. Even when vegetation decomposes slowly, it releases CO₂ over years to decades. Reforestation and preventing deforestation (REDD+ programs under the UN Framework Convention on Climate Change) are recognized as cost-effective strategies for climate change mitigation.',
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A graph shows the results of an experiment testing the effect of different concentrations of a plant hormone (auxin) on the growth of plant roots and stems. At low concentrations, both roots and stems show increased growth. At high concentrations, stem growth continues to increase, but root growth decreases below the control level.',
      text: 'Based on the graph, which statement correctly describes the relationship between auxin concentration and root growth?',
      choices: [
        'Root growth increases proportionally with increasing auxin concentrations.',
        'Root growth is inhibited at high auxin concentrations.',
        'Roots are not affected by auxin at any concentration.',
        'Root growth is greater than stem growth at all auxin concentrations.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'The graph shows that while low auxin concentrations promote root growth, high concentrations inhibit it — roots are more sensitive to auxin than stems, so what promotes stem growth actually suppresses root growth.',
      diveDeep: 'This differential sensitivity of roots and stems to auxin concentration is a classic concept in plant biology. Stems require higher auxin concentrations for optimal growth than roots do. The same concentration that maximally stimulates stem elongation may inhibit root elongation. This phenomenon underlies the use of synthetic auxins as selective herbicides: at high concentrations, auxin-like compounds cause uncontrolled, abnormal growth and death in plants. Understanding dose-response curves is an important scientific skill — both in biology and in pharmacology.',
    },
    {
      number: 32, part: 'B-1',
      context: 'A graph shows the effect of auxin concentration on growth of plant roots and stems.',
      text: 'Based on the graph, which auxin concentration would promote the greatest stem growth while minimally inhibiting root growth?',
      choices: [
        'a very high concentration that maximizes stem growth',
        'a low concentration that has a small positive effect on both roots and stems',
        'a medium concentration that strongly promotes stem growth and only slightly inhibits roots',
        'zero concentration, using no auxin at all',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'A low concentration benefits both roots and stems with minimal inhibitory effect on roots, representing the best balance between promoting stem growth and avoiding root suppression.',
      diveDeep: 'Reading and interpreting graphs is a critical scientific skill assessed on the Living Environment Regents. This question requires comparing two curves simultaneously and identifying an optimal point — a common type of quantitative reasoning. In plant biology, the differential dose-response of roots vs. stems to auxin explains why shoots grow toward light (phototropism) even as roots may be unaffected or grow in the opposite direction. Agricultural use of auxins (as herbicides and rooting hormones) depends on careful calibration of dose to achieve desired effects without unintended damage.',
    },
    {
      number: 33, part: 'B-1',
      context: 'A diagram shows a model of the cell cycle, with phases labeled G1, S, G2, and M (mitosis). The diagram shows the relative amount of time each phase takes.',
      text: 'Based on the diagram, what happens during the S phase of the cell cycle?',
      choices: [
        'The cell divides into two daughter cells.',
        'DNA is replicated so each daughter cell will receive a complete set of chromosomes.',
        'The cell grows and prepares for division.',
        'Chromosomes line up in the middle of the cell.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'The S (synthesis) phase is when the entire genome is replicated, producing two identical copies of every chromosome so that each daughter cell receives a complete set during cell division.',
      diveDeep: 'The cell cycle is tightly regulated to ensure accurate DNA replication and chromosome segregation. S phase is the longest phase of interphase; in human cells, it takes about 6–8 hours. After S phase, the cell enters G2 (gap 2), during which it checks for replication errors and prepares for mitosis. The G1/S checkpoint (restriction point) is the cell\'s main decision point: if conditions are favorable and DNA is intact, the cell commits to replication. The tumor suppressor protein p53 plays a critical role at this checkpoint — mutations in p53 are found in about half of all human cancers.',
    },
    {
      number: 34, part: 'B-1',
      context: 'A bar graph shows the number of different species found in four different soil samples taken from fields with different farming practices: conventional farming, organic farming, no-till farming, and abandoned/natural field.',
      text: 'Based on the bar graph, which farming practice is associated with the greatest biodiversity in the soil?',
      choices: [
        'conventional farming',
        'organic farming',
        'no-till farming',
        'abandoned/natural field',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'An abandoned/natural field, undisturbed by farming practices, has the most diverse soil ecosystem because it has not been disrupted by plowing, pesticides, or synthetic fertilizers that reduce soil biodiversity.',
      diveDeep: 'Soil biodiversity is crucial for ecosystem function — decomposition, nutrient cycling, and plant health all depend on diverse soil communities of bacteria, fungi, nematodes, earthworms, and arthropods. Conventional farming practices (tillage, synthetic pesticides and fertilizers) disrupt these communities. No-till farming preserves more soil structure and biodiversity than conventional tillage. Organic farming avoids synthetic pesticides and fertilizers, supporting greater soil health. Natural/abandoned fields benefit from decades or centuries of undisturbed soil development. Sustainable agriculture is increasingly focused on soil health as a foundation for long-term productivity.',
    },
    {
      number: 35, part: 'B-1',
      text: 'Researchers have found that many species of birds have been declining in population over the past 50 years in North America. The scientists conclude that the most important factor is habitat loss. Which evidence would best support this conclusion?',
      choices: [
        'Bird species that are widespread habitat generalists have declined most sharply.',
        'Bird species that depend on specific, shrinking habitats have declined most sharply.',
        'All bird species, regardless of habitat preference, have declined at the same rate.',
        'Bird species that migrate to Central America show less decline than non-migratory species.',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'If habitat loss is the cause, species that depend on specific habitats that are being destroyed would show the greatest declines, while habitat generalists would be less affected — this pattern would directly support the hypothesis.',
      diveDeep: 'Scientific reasoning requires identifying evidence that specifically supports or falsifies a hypothesis. Habitat specialists (species with narrow niche requirements) are more vulnerable to habitat loss than generalists because they cannot easily switch to alternative habitats. Studies of North American breeding birds (Christmas Bird Count, Breeding Bird Survey data) confirm that grassland and forest-interior specialists have declined most sharply, while habitat generalists (crows, starlings, house sparrows) have remained stable or increased. This evidence pattern strongly supports habitat loss as the primary driver of bird population declines.',
    },
    {
      number: 36, part: 'B-1',
      text: 'A student sets up an experiment to test the effect of light intensity on the rate of photosynthesis in aquatic plants. The student places plants under lights of different brightness and counts the number of oxygen bubbles produced per minute. The student should use which variable as the dependent variable?',
      choices: [
        'the brightness of the light source',
        'the type of aquatic plant used',
        'the number of oxygen bubbles produced per minute',
        'the temperature of the water',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'The dependent variable is what the experimenter measures in response to changes in the independent variable. Here, oxygen bubbles per minute (a measure of photosynthesis rate) changes in response to light intensity (the independent variable).',
      diveDeep: 'Experimental design terminology: independent variable (the factor deliberately changed by the experimenter — light intensity), dependent variable (the factor measured as an outcome — oxygen production), and controlled variables (factors kept constant — plant type, temperature, CO₂ concentration, water chemistry). Elodea (aquarium plant) is commonly used for this experiment because its oxygen bubbles are easily visible and countable. The rate of photosynthesis can also be measured by changes in CO₂ concentration, mass gain, or glucose production. Light intensity, CO₂ concentration, and temperature are the three main limiting factors for photosynthesis.',
    },
    {
      number: 37, part: 'B-1',
      context: 'A table shows data on the nitrogen content of soil samples taken from different areas of a field, along with the types of plants growing in each area. Areas with leguminous plants (such as clover) have higher nitrogen content than areas with non-leguminous plants.',
      text: 'Based on the data in the table, which statement best explains why areas with leguminous plants have higher soil nitrogen levels?',
      choices: [
        'Leguminous plants produce nitrogen from carbon dioxide during photosynthesis.',
        'Leguminous plants host bacteria in their roots that convert atmospheric nitrogen into usable forms.',
        'Leguminous plants absorb more nitrogen from the soil than other plants.',
        'Leguminous plants decompose faster than other plants, releasing their nitrogen into the soil.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Legumes form symbiotic relationships with nitrogen-fixing bacteria (Rhizobium) in root nodules; these bacteria convert atmospheric N₂ into ammonia (NH₃), increasing the plant-available nitrogen in the surrounding soil.',
      diveDeep: 'Biological nitrogen fixation is a critical part of the nitrogen cycle. Rhizobium bacteria infect legume roots and form nodules where they carry out nitrogen fixation using the enzyme nitrogenase, which requires significant ATP. In return, the plant provides the bacteria with carbohydrates from photosynthesis — a mutualistic relationship. Fixed nitrogen improves soil fertility, which is why legume crops (soybeans, clover, alfalfa) are used in crop rotation to restore nitrogen-depleted soils. This reduces the need for synthetic nitrogen fertilizers, which are energy-intensive to produce (Haber-Bosch process) and contribute to water pollution through runoff.',
    },
    {
      number: 38, part: 'B-1',
      context: 'A diagram shows the structure of DNA, with the double helix, sugar-phosphate backbone, and nitrogenous bases (adenine, thymine, guanine, cytosine) labeled.',
      text: 'Based on the diagram, which statement correctly describes the base-pairing rules for DNA?',
      choices: [
        'Adenine pairs with cytosine, and guanine pairs with thymine.',
        'Adenine pairs with guanine, and cytosine pairs with thymine.',
        'Adenine pairs with thymine, and guanine pairs with cytosine.',
        'All four bases pair equally with each other.',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'The base-pairing rules (Chargaff\'s rules) state that adenine (A) always pairs with thymine (T) and guanine (G) always pairs with cytosine (C). These are complementary base pairs held together by hydrogen bonds.',
      diveDeep: 'Chargaff\'s rules (A=T and G=C in amount) were a crucial clue that led Watson and Crick to the double helix structure. A–T pairs are held by 2 hydrogen bonds; G–C pairs by 3 hydrogen bonds. This means DNA with higher G–C content has a higher melting temperature (Tm). In RNA, uracil (U) replaces thymine, so the pairing is A–U. These base-pairing rules govern both DNA replication (template-directed synthesis) and transcription (DNA→RNA). In PCR and gel electrophoresis-based diagnostics, synthetic primers are designed to be complementary to specific DNA sequences, exploiting these rules.',
    },
    {
      number: 39, part: 'B-1',
      text: 'Scientists have found evidence that a mass extinction event 65 million years ago wiped out the non-avian dinosaurs and many other species. After this extinction event, the diversity of mammal species increased dramatically. This pattern suggests that',
      choices: [
        'mass extinctions always lead to increased biodiversity in the long term',
        'the extinction of dominant species can open ecological niches for other species to diversify into',
        'mammals caused the extinction of the dinosaurs through competition',
        'evolution always produces more species after an extinction event',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'When dominant species (non-avian dinosaurs) are removed by extinction, previously occupied ecological niches become available; other groups (early mammals) radiate into these niches, producing an adaptive radiation of new species.',
      diveDeep: 'The Cretaceous-Paleogene (K-Pg) mass extinction (caused by a large asteroid impact 66 million years ago combined with volcanic activity) eliminated approximately 75% of all species, including all non-avian dinosaurs. Mammals, which were small, nocturnal insectivores during the Mesozoic, diversified dramatically in the Paleogene into the diverse forms seen today (whales, bats, elephants, primates). This adaptive radiation — rapid diversification into available ecological niches — illustrates that extinction events can drive subsequent bursts of evolutionary diversification, though this is not guaranteed and depends on the availability of niches and surviving lineages.',
    },
    {
      number: 40, part: 'B-1',
      context: 'A graph shows the concentration of a hormone in the blood over a 24-hour period. The concentration fluctuates, rising and falling in a regular pattern. When the concentration rises above a certain threshold, a gland decreases its production of the hormone. When the concentration falls below a threshold, production increases.',
      text: 'The pattern shown in the graph is an example of',
      choices: [
        'positive feedback — the body amplifies the hormone signal',
        'active transport — the body moves the hormone against its concentration gradient',
        'negative feedback — the body regulates hormone levels by reversing deviations from normal',
        'ecological succession — hormone levels change in response to environmental conditions',
      ],
      topic: 'Human Body',
      correct: 2,
      explanation: 'The described pattern — where high levels trigger decreased production and low levels trigger increased production — is the classic negative feedback loop that maintains hormone levels within a normal range.',
      diveDeep: 'Hormonal negative feedback is central to endocrine regulation. Examples: (1) the hypothalamus–pituitary–thyroid axis: low thyroid hormone triggers TSH release, which stimulates more thyroid hormone; high thyroid hormone inhibits TSH. (2) Insulin–glucagon regulation of blood glucose. (3) Cortisol regulation by ACTH and CRH. These multi-step hormonal feedback loops are sometimes called axes and involve hierarchical control with the hypothalamus at the top. Disruptions in negative feedback (e.g., in Cushing\'s disease, cortisol fails to inhibit ACTH) result in hormone excess disorders.',
    },
    {
      number: 41, part: 'B-1',
      text: 'A student observes that placing a red blood cell in a very salty solution causes it to shrink, while placing it in a very dilute solution causes it to swell. This is because',
      choices: [
        'salt enters the cell when it is placed in salty water, causing it to shrink',
        'water moves out of the cell into the salty solution by osmosis, and water moves into the cell from the dilute solution by osmosis',
        'the cell membrane breaks down in salty water, allowing water to escape',
        'the red blood cell actively pumps salt out when placed in salty water',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Osmosis is the diffusion of water across a semipermeable membrane from an area of high water concentration (low solute) to low water concentration (high solute). In salty solution, water leaves the cell; in dilute solution, water enters.',
      diveDeep: 'Osmosis depends on the relative solute concentrations: hypertonic solution (higher solute than cell) → water moves out → cell shrinks (crenation in red blood cells); hypotonic solution (lower solute than cell) → water moves in → cell swells and may lyse; isotonic solution (equal solute) → no net water movement. The driving force is water potential. Red blood cells are particularly sensitive because they lack a cell wall to prevent bursting. Intravenous (IV) fluids must be isotonic (0.9% NaCl, "normal saline") to prevent red blood cell damage.',
    },
    {
      number: 42, part: 'B-1',
      text: 'Scientists studying Darwin\'s finches in the Galápagos Islands found that during a drought, seeds became scarcer and only large, hard seeds were available. Birds with larger beaks survived and reproduced. The next generation of birds had, on average, larger beaks. This is an example of',
      choices: [
        'the finches choosing to develop larger beaks to crack the available seeds',
        'natural selection acting on existing variation in the population',
        'genetic engineering changing the beak size of the finches',
        'a mutation caused by the drought that produced larger beaks',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Natural selection acted on pre-existing beak size variation: birds with larger beaks could eat the available large seeds and survived; those with smaller beaks could not and died before reproducing, increasing the average beak size in the next generation.',
      diveDeep: 'The Grants\' 40+ year study of Galápagos finches is the most comprehensive real-time documentation of natural selection in action. During the 1977 drought, beak depth increased by an average of 0.5 mm in one generation — a measurable, rapid evolutionary change. Key points: (1) the variation in beak size was genetic and heritable; (2) the drought was an environmental selective pressure, not a cause of new mutations; (3) the birds did not "choose" to change — individuals with existing advantageous traits survived; (4) the change was reversed when rains returned and small seeds became available again. This demonstrates that natural selection is reversible and environment-dependent.',
    },
    {
      number: 43, part: 'B-1',
      text: 'Scientists have observed that the use of the pesticide DDT nearly caused the extinction of the bald eagle in the mid-20th century. DDT caused eagles\' eggshells to become thin and break before the chicks could hatch. This illustrates that',
      choices: [
        'all pesticides should be banned to protect wildlife',
        'technology can have unintended consequences for non-target organisms and ecosystems',
        'bald eagles are particularly sensitive to all environmental toxins',
        'DDT was effective at protecting crops and should continue to be used',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'DDT was introduced to control insect pests but had unintended consequences for non-target species at higher trophic levels through biomagnification, nearly causing eagle extinction — illustrating that technological interventions can have unpredicted ecological effects.',
      diveDeep: 'DDT biomagnification is a classic case study in environmental toxicology. DDT is fat-soluble and not easily metabolized, so it accumulates in fatty tissues. As it moves up the food chain (plankton → small fish → large fish → eagles), its concentration increases by a factor of roughly 10 at each level (biomagnification). In eagles, DDE (a DDT metabolite) inhibited calcium deposition in eggshells, causing them to crack under the weight of incubating parents. Eagle populations fell to fewer than 500 nesting pairs in the contiguous U.S. by the early 1960s. DDT was banned in the U.S. in 1972 (largely due to Rachel Carson\'s "Silent Spring"), and eagle populations recovered to over 9,000 pairs by the 2000s.',
    },
  ],
}
