// Living Environment Regents — August 2024
export default {
  id: 'le-august-2024',
  subject: 'living-environment',
  year: 2024,
  session: 'August',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'The human body maintains a balanced internal environment. In order to accomplish this,',
      choices: [
        'organelles work independently',
        'all cells have the same shape and function',
        'insulin is produced when protein levels are low',
        'stimuli are detected, and actions are taken',
      ],
      topic: 'Cell Biology',
      correct: 3,
    },
    {
      number: 2, part: 'A',
      text: 'Wolves are important predators in some ecosystems. If wolves are removed from their environment, the ecosystem is in danger of becoming unstable due to',
      choices: [
        'a reduction of autotrophs when the number of herbivores is not being kept in check by the wolves',
        'a decrease in the number of herbivores because they will not be able to reach carrying capacity',
        'an increase in the biodiversity of the remaining animal and plant species',
        'some species of herbivores taking over the niche the wolves occupied',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 3, part: 'A',
      text: 'Which statement best explains how deforestation that is the result of forest fires can contribute to global warming?',
      choices: [
        'Burning the trees adds smoke to the atmosphere and blocks sunlight.',
        'Burning the trees adds carbon dioxide to the atmosphere.',
        'Deforestation removes trees that produce carbon dioxide through the process of photosynthesis.',
        'Deforestation immediately increases ecosystem stability needed in the burned area.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 4, part: 'A',
      text: 'For centuries, humans have built dams along rivers to redirect water for power, irrigation, and transportation. Dams can prevent migrating fish from swimming upstream to reproduce and can also disrupt the flow of sediments and nutrients. Communities are starting to eliminate some dams, and the health of the river ecosystems is being restored. This best illustrates that',
      choices: [
        'technological advances often involve environmental trade-offs',
        'when humans modify their environment it always has effects that cannot be reversed',
        'industrialization has had a positive effect on the health of river ecosystems',
        'the construction of dams affected abiotic factors in the river but not biotic factors',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 5, part: 'A',
      text: 'In humans, lactose is broken down into glucose and galactose in the presence of a particular enzyme. It is most likely that the enzyme that breaks down lactose',
      choices: [
        'breaks down several other types of food in the stomach',
        'is involved in other reactions when the temperature and pH are ideal',
        'helps in the synthesis of complex sugars during autotrophic nutrition',
        'is not involved in other types of reactions because enzymes are specific',
      ],
      topic: 'Human Body',
      correct: 3,
    },
    {
      number: 6, part: 'A',
      text: 'The Tdap vaccine can protect adolescents and adults from tetanus, diphtheria, and pertussis. Another vaccine, Td, protects against tetanus and diphtheria, but not pertussis. Td does not protect against pertussis because the',
      choices: [
        'Tdap vaccine is given to treat pertussis',
        'Td vaccine does not contain the antibodies from pertussis to fight the bacteria',
        'Tdap vaccine contains a small amount of the bacteria that causes pertussis',
        'Td vaccine does not stimulate the immune system of people to recognize pertussis antigens',
      ],
      topic: 'Human Body',
      correct: 3,
    },
    {
      number: 7, part: 'A',
      text: 'Pelagic red crabs living on the ocean floor have been found to eat small bits of plastic. When they are consumed, these small creatures are passing the plastics along the food chain to predators, including fish consumed by humans. This is of concern because it',
      choices: [
        'decreases plastic recycling by primary consumers',
        'increases the risk of harmful substances in our food supply',
        'decreases the producers in the ecosystem',
        'increases the biodiversity of the ocean',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 8, part: 'A',
      text: 'Duckweed is a small plant that grows on the surface of still bodies of water. Over a nine-week period, scientists monitored the growth of duckweed in three ditches on the same farm. The number of duckweed plants increased rapidly during weeks one and two. After two weeks, each ditch was completely covered and remained covered for the remaining seven weeks. A valid conclusion based on the data collected is that',
      choices: [
        'animals that eat duckweed have the greatest effect on duckweed population size',
        'duckweed populations die off after completing a two-week life cycle in the ditch',
        'only changes in temperature affect duckweed population size',
        'the size of the duckweed population is kept stable by limited resources in the ditch',
      ],
      topic: 'Ecology',
      correct: 3,
      image: '/images/exams/le-august-2024/q8.png',
    },
    {
      number: 9, part: 'A',
      text: 'Which statement explains why the organisms in some ecosystems, such as rainforests, deserts, and oceans, are different from each other?',
      choices: [
        'The living organisms in each ecosystem have different needs and produce the physical conditions that they require.',
        'Each ecosystem contains different types of living organisms that change each of the physical conditions present there.',
        'They all have the same physical conditions present, but the living organisms use them in different ways.',
        'Each ecosystem contains different physical conditions that determine the type of living organisms present there.',
      ],
      topic: 'Ecology',
      correct: 3,
    },
    {
      number: 10, part: 'A',
      text: 'Some green plants secrete acids that dissolve rock, which makes it possible for the plants to absorb phosphorus needed for healthy plant growth. In addition to phosphorus, plants require many other substances. Which substances are required for the production of carbohydrates in green plants?',
      choices: [
        'oxygen and nitrogen',
        'carbon and glucose',
        'carbon dioxide and water',
        'hydrogen and starch',
      ],
      topic: 'Human Body',
      correct: 2,
    },
    {
      number: 11, part: 'A',
      text: 'Which statement about competition in ecosystems is correct?',
      choices: [
        'Organisms compete most when they occupy different niches and resources are plentiful.',
        'Individuals need not compete, because resources such as water and food are always plentiful in ecosystems.',
        'Organisms that compete successfully will survive, reproduce, and pass their traits on to their offspring.',
        'Competition usually results in the extinction of a species, ensuring the survival of other species.',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 12, part: 'A',
      text: 'Human body systems interact with each other. The results of one body system functioning normally include: muscle cells receive oxygen, nerve cells receive glucose, lungs get rid of carbon dioxide, and some gland cells send chemical signals to organs. Which body system most directly enables all these functions to occur?',
      choices: [
        'circulatory system',
        'excretory system',
        'digestive system',
        'immune system',
      ],
      topic: 'Human Body',
      correct: 0,
    },
    {
      number: 13, part: 'A',
      text: 'The Himalayan rabbit lives in the cold Tibetan mountains. It typically has white fur on its body and black fur on its outer extremities. A scientist shaved a patch of white fur off the back of a Himalayan rabbit and applied an ice pack to the area for 30 minutes. The fur in the shaved area grew in black. The best explanation for why black fur grew in the shaved area is that',
      choices: [
        'the food the rabbit ate during the experiment influenced fur color',
        'the fur in the newly shaved area was younger than the white fur on the rest of the body',
        'the ice pack caused a mutation in the genes that regulate fur color',
        'warm and cold temperatures activate different genes for fur color',
      ],
      topic: 'Genetics',
      correct: 3,
    },
    {
      number: 14, part: 'A',
      text: 'Researchers have identified a mutually beneficial relationship between some plant species and specific fungi. The fungi increase the nutrient uptake for these plants, and the plants provide nutrition to the fungi. In order for this relationship to occur, the plant must produce a particular protein. Scientists hope to enable plants that normally do not interact with these fungi to obtain the benefits. In order to make this possible, which process would scientists most likely use?',
      choices: [
        'Treat the plants with chemical fertilizers to stimulate their growth.',
        'Provide the fungi with the same molecular bases that are found in plant protein.',
        'Identify the gene that codes for the protein and introduce it into plant cells by genetic engineering.',
        'Selectively breed a new type of fungus that does not require the nutrients that the plants provide.',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 15, part: 'A',
      text: 'Milkweeds are plants that produce toxic, bitter-tasting chemicals. Some insects have developed the ability to safely feed on milkweed and accumulate the toxin in their bodies, causing them to taste bitter to predators. As a result, most animals avoid eating these insects. A possible explanation for this relationship is that',
      choices: [
        'eating a toxic plant increases the ability of these insects to survive and reproduce',
        'milkweed populations are controlled by many insects',
        'the milkweed benefits from the insects that can tolerate the toxin they produce',
        'eventually the insects will become immune to the toxin',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 16, part: 'A',
      text: 'Which type of cell engulfs pathogens and marks them for killing?',
      choices: [
        'red blood cell',
        'white blood cell',
        'nerve cell',
        'muscle cell',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 17, part: 'A',
      text: 'A diagram shows a hierarchy of biological organization. Which choice correctly labels and defines the box labeled X in the hierarchy (between cells and organs)?',
      choices: [
        'cell: the basic structural, functional, and biological unit',
        'organ: a group of tissues with a common function',
        'tissue: a group of cells with a similar structure and function',
        'organ system: a collection of organs with a common function',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-august-2024/q17.png',
    },
    {
      number: 18, part: 'A',
      context: 'A graph titled "Cumulative Vertebrate Species Extinction" shows the percentage of mammal, bird, and other vertebrate species that have gone extinct from 1500–2014. The percentage increases dramatically from 1850 to 2014, with mammals showing the steepest rise.',
      text: 'Concern is rising that mass extinctions of many species may increase. Based on the graph showing rising extinction rates from 1850 to 2014, this loss of different species is a concern because it may',
      choices: [
        'lead to an increase in diversity in the ecosystem',
        'impact the energy flow and food supply within an ecosystem',
        'produce increased nonrenewable resources',
        'provide additional sources of potential medicines',
      ],
      topic: 'Evolution',
      correct: 1,
      image: '/images/exams/le-august-2024/q18.png',
    },
    {
      number: 19, part: 'A',
      text: 'The American Museum of Natural History has an Ecosystem Sphere — a huge sealed glass globe assembled in 1999 with populations of algae, bacteria, and little shrimp sealed with water and air inside. It is kept in a well-lit area. Although the sphere has never been opened, groups of each kind of organism are still alive inside it. The most likely reason is because the populations have',
      choices: [
        'remained in separate areas of the sphere and do not interact',
        'adapted so that they do not require food',
        'a constant source of energy because they cannot recycle gases and materials',
        'a constant source of energy and recycle gases and materials',
      ],
      topic: 'Ecology',
      correct: 3,
    },
    {
      number: 20, part: 'A',
      text: 'Ebola is a deadly viral disease. Researchers are testing a vaccine on people who have not yet been infected by Ebola but live in high-risk areas. The vaccine must be given to the subjects before exposure to Ebola because',
      choices: [
        'the vaccine will mutate the virus when a person gets infected',
        'if a subject is infected with Ebola, it will destroy the vaccine',
        'vaccines stimulate the subject\'s immune system to react to future exposure to the virus',
        'vaccines are only effective for a few days, so the patient must get the vaccine before exposure',
      ],
      topic: 'Human Body',
      correct: 2,
    },
    {
      number: 21, part: 'A',
      text: 'A relatively large number of antibodies in a blood sample would most likely indicate that there is',
      choices: [
        'an infection in the body',
        'a mutation in the lung',
        'a deficiency of carbon dioxide in the circulatory system',
        'an insufficient amount of a specific vitamin in the diet',
      ],
      topic: 'Human Body',
      correct: 0,
    },
    {
      number: 22, part: 'A',
      text: 'Ultraviolet light can alter the DNA segments of genes in the skin cells of an individual. Which statement best describes a direct result of these alterations?',
      choices: [
        'Any cells produced from the altered skin cells will have the same alterations.',
        'All the offspring of the individual will have the same skin cell alterations.',
        'These alterations will spread to all the other cells in the body.',
        'The sex cells of the individual will have the same alterations.',
      ],
      topic: 'Genetics',
      correct: 0,
    },
    {
      number: 23, part: 'A',
      text: 'The energy required to assemble proteins and fats is directly supplied to body cells from',
      choices: [
        'all the colors of visible light',
        'molecules of ATP contained within the cells',
        'all the DNA found in sex cells',
        'molecules of carbon dioxide produced by chloroplasts',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 24, part: 'A',
      text: 'There are over 200 different cell types in the human body. Each type of cell is specialized to carry out a particular function, but they all developed from the same single cell. This is because each type of cell',
      choices: [
        'contains different genes than the other types of cells',
        'destroys the genes found in the other types of cells',
        'expresses some genes not expressed in the other cell types',
        'lacks the genes found in the other cell types',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 25, part: 'A',
      text: 'Coral reefs are vital components of marine ecosystems. Some coral reefs in the Pacific Ocean are heavily polluted with plastic objects that provide surfaces where disease-causing microbes are able to grow. If the amount of plastic present on coral reefs continues to increase, it is likely that the',
      choices: [
        'coral will adapt to the presence of the plastic and thrive',
        'microbes will adapt to living directly on the coral',
        'algae that live on the reef will begin to decompose the dying coral',
        'species dependent on the coral will be negatively impacted',
      ],
      topic: 'Evolution',
      correct: 3,
    },
    {
      number: 26, part: 'A',
      text: 'Enzymes, antibodies, and receptor molecules all have different functions. However, they are alike in that they',
      choices: [
        'all are involved in cellular respiration',
        'have a shape that is specific to their function',
        'are classified as carbohydrates',
        'are important in animals but not plants',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 27, part: 'A',
      text: 'Australian quolls are endangered mammals. Scientists identified a gene that some quolls possess that makes them avoid eating poisonous cane toads. By selectively breeding quolls with the "toad-avoiding gene" with other quolls who lack the gene, scientists found all hybrid offspring inherited the survival gene. Before the survival gene could be passed on to any offspring, the genetic material present in the parent with the "toad-avoiding gene" would have to be',
      choices: [
        'mutated to become a different gene',
        'accurately replicated',
        'genetically engineered',
        'changed through recombination',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 28, part: 'A',
      text: 'Scientists have cloned many animals, such as cows, sheep, and chickens, from a single cell. Which natural process is most similar to these cloning techniques?',
      choices: [
        'asexual reproduction',
        'genetic recombination',
        'chromosome mutations',
        'gamete production',
      ],
      topic: 'Genetics',
      correct: 0,
    },
    {
      number: 29, part: 'A',
      text: 'Within a sexually reproducing species, the correct chromosome number is maintained by',
      choices: [
        'halving the chromosome number in gamete production, followed by fertilization',
        'doubling the chromosome number in gamete production, followed by fertilization',
        'halving the chromosome number during mitosis, followed by differentiation',
        'doubling the chromosome number during mitosis, followed by differentiation',
      ],
      topic: 'Reproduction',
      correct: 0,
    },
    {
      number: 30, part: 'A',
      text: 'The ability of sea otters to find food can be reduced because the environment where they search for food is often dark and murky. It has been recently discovered that the surface of otters\' paws are able to quickly detect a difference of one-quarter of a millimeter when comparing the size of objects, including food sources. The special characteristics of the otters\' paws can be described as',
      choices: [
        'a variation that eliminates the need for other senses otters normally possess',
        'a variation that is unlikely to be passed on to offspring because it is not a genetic trait',
        'an adaptation that could provide an advantage over the other organisms that they compete with for food',
        'an adaptation that is most likely the result of a mutation in body cells of the ancestors of the otter',
      ],
      topic: 'Genetics',
      correct: 2,
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A graph titled "The Effect of Temperature on Catalase Activity" shows relative catalase activity rising from 0°C to a peak around 35°C, then dropping sharply above 35°C.',
      text: 'Catalase is an enzyme produced by organisms that breaks down hydrogen peroxide, releasing oxygen and water. Based on the graph showing catalase activity at different temperatures, which statement best explains the decrease in activity of catalase after 35°C?',
      choices: [
        'The structure of the enzyme changes, which slows down the reaction.',
        'There is no hydrogen peroxide left for the activity to continue, so it stops.',
        'The raw materials permanently bind to the catalase, preventing the reaction.',
        'The reaction is no longer needed for survival of the individual.',
      ],
      topic: 'Human Body',
      correct: 0,
      image: '/images/exams/le-august-2024/q31.png',
    },
    {
      number: 32, part: 'B-1',
      context: 'A chart shows four cells (A, B, C, D) and which structures each contains. Cell A has: cell membrane, cell wall, chloroplasts, DNA, nucleus. Cell B has: cell membrane, DNA, nucleus. Cell C has: cell membrane, cell wall, DNA (no nucleus). Cell D has: cell membrane, DNA, nucleus.',
      text: 'Using a microscope, a student observed four different types of cells and recorded which structures were present (cell membrane, cell wall, chloroplasts, DNA, nucleus). Which of the cells he viewed were most likely from heterotrophs?',
      choices: [
        'A and C',
        'B and D',
        'C and B',
        'D and C',
      ],
      topic: 'Cell Biology',
      correct: 3,
      image: '/images/exams/le-august-2024/q32.png',
    },
    {
      number: 33, part: 'B-1',
      context: 'A coleus plant leaf has chloroplast-rich (green) areas on the edges and chloroplast-lacking areas in the middle. After exposure to sunlight and addition of starch indicator, the green (chloroplast-rich) areas turned blue-black, while the non-green middle areas did not.',
      text: 'A student exposed a coleus leaf (with chloroplast-rich edges and chloroplast-lacking middle) to sunlight, then added starch indicator to the entire leaf. The edges turned blue-black; the middle did not. Which statement is a valid claim, supported by evidence from this experiment?',
      choices: [
        'Chloroplasts are necessary for the production of starch indicator.',
        'Starch indicator causes leaves to produce oxygen.',
        'Chloroplasts are necessary for the production of starch.',
        'Water is necessary for the production of starch.',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 34, part: 'B-1',
      text: 'Breathing vapors produced by e-cigarettes has caused respiratory problems, including coughing, shortness of breath, difficulty breathing, and even some deaths. Medical experts are warning the public and discouraging the use of these devices. The medical issues associated with vaping are an example of',
      choices: [
        'organ malfunctions caused by personal behaviors',
        'feedback response maintaining homeostasis',
        'inherited disorders resulting from inhaling vapors',
        'the effects of infectious parasites carried by the vapors',
      ],
      topic: 'Human Body',
      correct: 0,
    },
    {
      number: 35, part: 'B-1',
      context: 'A chart shows organisms and their energy sources: grasses (sunlight), leopard frog (insects, algae), carp (plants, insect larvae), heron (carp, frogs, salamanders), turtle (fish, plants, tadpoles, insects).',
      text: 'Based on the chart listing organisms and their energy sources in a New York ecosystem, when constructing an energy pyramid of this ecosystem, which of these organisms would be placed at the top of the pyramid?',
      choices: [
        'grasses',
        'carp',
        'heron',
        'leopard frog',
      ],
      topic: 'Ecology',
      correct: 2,
      image: '/images/exams/le-august-2024/q35.png',
    },
    {
      number: 36, part: 'B-1',
      context: 'A graph titled "Corn Yield as Affected by Planting Date" shows % of maximum yield on the y-axis vs. planting date on the x-axis. Yield is near 100% for plantings in late April/early May, then drops steadily. By June 1, yield is approximately 80% of maximum.',
      text: 'An unusually cool and wet spring prevented certain farmers from planting corn at the usual time (May 1), delaying planting until June 1. Based on the graph of corn yield by planting date, what is the most likely impact of the delayed planting on the production of corn?',
      choices: [
        'Corn yield will remain at 100% because higher temperatures in June will make plants grow faster.',
        'The corn yield may be reduced by about 20% because of the delay in planting.',
        'Corn yield may be reduced by about 80% because of the delayed planting.',
        'Crops planted on June 1 will have the same yield as those planted on April 1.',
      ],
      topic: 'General Review',
      correct: 1,
      image: '/images/exams/le-august-2024/q36.png',
    },
    {
      number: 37, part: 'B-1',
      context: 'A table titled "Beetle Biodiversity" shows the number of individuals of each species (A–E) in four habitats. Habitat W: C=32, D=54 (2 species). Habitat X: A=2, B=6, C=10, D=22, E=8 (5 species). Habitat Y: C=120 (1 species). Habitat Z: A=40, C=40, E=40 (3 species).',
      text: 'An ecologist counted the number of individuals of each beetle species (A–E) she observed in four different habitats. Based on the data table showing species counts per habitat, which of these habitats displays the most biodiversity of beetle species?',
      choices: [
        'Habitat W',
        'Habitat X',
        'Habitat Y',
        'Habitat Z',
      ],
      topic: 'Evolution',
      correct: 1,
      image: '/images/exams/le-august-2024/q37.png',
    },
    {
      number: 38, part: 'B-1',
      text: 'Hummingbirds, with their long beaks and tongues, are attracted to long, tubular flowers with a lot of nectar. When a hummingbird consumes the nectar from a flower, pollen sticks to the hummingbird and is transferred when the hummingbird feeds from other flowers. This relationship between the flowers and hummingbirds is a result of',
      choices: [
        'changes in hummingbirds and flowers in response to their needs',
        'inheritance of characteristics acquired during their lifetime',
        'natural selection of beneficial variations',
        'the environment modifying gene expression',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 39, part: 'B-1',
      text: 'Kittens from the same litter all have different fur colors and patterns. One possible reason that they all have different fur colors and patterns is that',
      choices: [
        'different kittens inherited more chromosomes from one parent than the other',
        'there was a random resorting of genes during gamete formation in each parent',
        'because there were so many, they did not receive the same amount of nutrients from the mother',
        'there were pH differences depending on where in the uterus each kitten developed',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 40, part: 'B-1',
      context: 'A study placed heated panels on the Antarctic Ocean floor 50 feet below the surface. Some panels were 1°C warmer, others 2°C warmer, and some unheated (control). Over 9 months, 1°C warming caused one invertebrate species to grow rapidly and become dominant, replacing multiple other species. Results on 2°C panels were less consistent.',
      text: 'Based on this experiment studying the effect of temperature increase on an Antarctic Ocean ecosystem, one result of the future warming of the Antarctic Ocean could be',
      choices: [
        'an increase in the stability of the Antarctic ecosystem',
        'the disruption of existing Antarctic marine food webs',
        'marine organisms evolving more rapidly in order to compete for resources',
        'the need to import predators to eat the tiny invertebrates',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 41, part: 'B-1',
      context: 'A study placed heated panels on the Antarctic Ocean floor 50 feet below the surface. Some panels were 1°C warmer, others 2°C warmer, and some unheated (control). Over 9 months, 1°C warming caused one invertebrate species to grow rapidly and become dominant, replacing multiple other species. Results on 2°C panels were less consistent.',
      text: 'A possible explanation for the differences observed on the panels (control, +1°C, and +2°C) is that',
      choices: [
        'the growth of organisms is dependent on the abiotic factors present in the environment',
        'on the warmer panels, organisms reached carrying capacity more rapidly and completely died out',
        'on the control panels, wastes built up, poisoning some of the organisms growing there',
        'on the warmer panels, there were fewer decomposers present to recycle available energy',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 42, part: 'B-1',
      context: 'A study placed heated panels on the Antarctic Ocean floor 50 feet below the surface. Some panels were 1°C warmer, others 2°C warmer, and some unheated (control). Over 9 months, 1°C warming caused one invertebrate species to grow rapidly and become dominant, replacing multiple other species. Results on 2°C panels were less consistent.',
      text: 'These test panels provided scientists with information about',
      choices: [
        'how ecological niches influence the rate of mutation',
        'the effect of environmental change on the biodiversity of the Antarctic Ocean',
        'the variety of producer/consumer relationships in the Antarctic Ocean',
        'how the stability of an ecosystem is affected by competition and disease',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 43, part: 'B-1',
      context: 'The kakapo is a small, flightless parrot with a small population on four islands off New Zealand. Scientists observed that when food is plentiful, more male offspring survive. An illustration shows: when food is scarce, sons are weak and unable to compete for mates; when food is plentiful, sons may be healthy, strong, and able to mate with many females.',
      text: 'Scientists are concerned the kakapo may become extinct. They observed that when food is plentiful, more male offspring survive. If scientists were going to test this hypothesis, the best way would be to select a test group and develop a research plan that includes collecting data when',
      choices: [
        'all of the kakapos are fed a reduced amount of food',
        'all of the kakapos are fed an unlimited amount of food',
        'the kakapo test group is divided in half, and one-half is fed unlimited food and the other a reduced amount of food',
        'the entire test group of kakapos is fed one type of food for one month and a different type of food for the second month',
      ],
      topic: 'Genetics',
      correct: 2,
    },
  ],
}
