// Living Environment Regents — June 2018
export default {
  id: 'li-jun-2018',
  subject: 'living-environment',
  year: 2018,
  session: 'June',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'Producers are generally found at the beginning of a food chain. Which statement best explains why this is true?',
      choices: ['Producers are usually smaller in size than consumers.', 'Producers do not rely on other organisms for food.', 'There are always more consumers than producers in food chains.', 'Consumers are always more complex organisms than producers.'],
      topic: 'Ecology', correct: 1,
      image: '/images/exams/le-june-2018/q1.png',
      explanation: 'Producers (autotrophs) make their own food through photosynthesis, relying on sunlight rather than other organisms; this independence from other organisms places them at the start of all food chains.',
      diveDeep: 'Producers convert inorganic materials (CO₂, water, minerals) into organic compounds using light energy — a process that requires no other organism. All other organisms (consumers) ultimately depend on producers for their energy. Producers are not always smaller than consumers; giant trees are producers. There are actually more producers than consumers at the base of the energy pyramid. Consumers vary in complexity from insects to mammals. The key defining feature of producers is autotrophy — self-feeding through photosynthesis or chemosynthesis.'
    },
    {
      number: 2, part: 'A',
      text: 'A lion cub resembles its parents because it inherits genes that produce',
      choices: ['DNA identical to all of the DNA found in both parents', 'proteins identical to all of the proteins found in both parents', 'ATP identical to some of the ATP found in each parent', 'enzymes identical to some of the enzymes found in each parent'],
      topic: 'Genetics', correct: 3,
      image: '/images/exams/le-june-2018/q2.png',
      explanation: 'Inherited genes code for specific proteins — including enzymes — that determine physical traits; the cub inherits genes from both parents, so some of its enzymes (proteins) match those of its parents.',
      diveDeep: 'Genes are segments of DNA that encode the instructions to build specific proteins. When a cub inherits genes from its parents, those genes direct the production of proteins that determine coat color, body structure, and other traits. The cub\'s DNA is NOT identical to either parent\'s DNA — it is a unique combination from both. ATP is an energy molecule produced by all cells; it is not inherited. The word "some" in the enzyme answer is key — the cub inherits some genes from each parent, so it produces some enzymes identical to each parent, not all of them.'
    },
    {
      number: 3, part: 'A',
      text: 'If body temperature is too high, some blood vessels increase in size and sweat glands will excrete sweat, resulting in a lower body temperature. These changes are an example of',
      choices: ['a learned behavior', 'feedback mechanisms', 'an inherited disorder', 'genetic mutations'],
      topic: 'Human Body', correct: 1,
      image: '/images/exams/le-june-2018/q3.png',
      explanation: 'The body detects high temperature (stimulus), responds with vasodilation and sweating to cool down, and returns to normal — this is a classic negative feedback homeostatic mechanism.',
      diveDeep: 'Feedback mechanisms are regulatory processes in which the output (lower body temperature) feeds back to reduce the original stimulus (overheating). This is specifically negative feedback, the primary mechanism of homeostasis in living organisms. Learned behaviors are acquired through experience and training, not automatic physiological responses. Inherited disorders involve genetic abnormalities, not normal physiological responses. Genetic mutations are changes in DNA, not homeostatic responses. Vasodilation (widening blood vessels near skin) and sweating are two key cooling mechanisms in humans.'
    },
    {
      number: 4, part: 'A',
      text: 'A farmer grows beans that he sells to local markets. Over a period of 40 years, the farmer has identified the plants that produced the most beans and only used those beans to produce new plants. This procedure is part of the process of',
      choices: ['selective breeding', 'replication', 'genetic engineering', 'cloning'],
      topic: 'General', correct: 0,
      explanation: 'Selectively choosing plants with the most desirable traits (highest bean production) and breeding only those is the definition of selective breeding (artificial selection).',
      diveDeep: 'Selective breeding, or artificial selection, is the human-guided process of allowing only organisms with desirable traits to reproduce. Over many generations, this concentrates the alleles for those traits in the population. It is similar to natural selection but directed by human preferences rather than environmental pressures. Selective breeding has produced all domesticated crops and livestock over thousands of years. Genetic engineering directly manipulates DNA in a laboratory. Cloning produces genetically identical copies. Replication is DNA copying. The 40-year timeframe illustrates that selective breeding is a gradual, multigenerational process.'
    },
    {
      number: 5, part: 'A',
      text: 'Although we rely on coal, oil, and natural gas to produce energy, some environmental scientists have proposed that we use less fossil fuel. One reason to support this proposal is to',
      choices: ['enable us to preserve rain forests in tropical areas', 'help us to reduce the production of carbon dioxide gas', 'allow us to decrease the use of fertilizers on crops', 'encourage us to end research on wind and water power sources'],
      topic: 'Evolution', correct: 1,
      image: '/images/exams/le-june-2018/q5.png',
      explanation: 'Burning fossil fuels is the primary source of CO₂ emissions, a major greenhouse gas contributing to global warming; reducing fossil fuel use directly reduces CO₂ production.',
      diveDeep: 'Fossil fuels are composed of ancient carbon stored underground. Burning them releases CO₂ that had been sequestered for millions of years, rapidly increasing atmospheric CO₂ concentrations. This enhanced greenhouse effect traps more solar radiation and warms the planet. Reducing fossil fuel consumption is one of the most direct ways to slow climate change. Rain forest preservation is a separate (though related) conservation issue. Fertilizer use and wind/water power research are unrelated to fossil fuel combustion. CO₂ as the primary greenhouse gas and fossil fuels as its main source is a central LE environmental topic.'
    },
    {
      number: 6, part: 'A',
      text: 'The diagram represents relationships in an ecosystem: Hawks, Mountain lions, Snakes, Field mice, Rabbits, Elk, Trees, Shrubs, Grasses. What is the primary source of energy in this environment?',
      choices: ['cellular respiration in the plants', 'energy from minerals in the soil', 'fossil fuels', 'solar energy'],
      topic: 'Ecology', correct: 3,
      image: '/images/exams/le-june-2018/q6.png',
      explanation: 'The sun (solar energy) is the ultimate primary source of energy for virtually all ecosystems; plants capture sunlight through photosynthesis and pass that energy through the food web.',
      diveDeep: 'In almost all ecosystems, the flow of energy begins with solar energy captured by autotrophs (producers) via photosynthesis. This energy is stored as chemical energy in organic molecules (glucose) and transferred through the food web. Cellular respiration in plants releases stored energy for the plant\'s own use — it does not add new energy to the system. Minerals provide nutrients (matter) but not energy. Fossil fuels are not part of natural ecosystem energy flow. Only a few deep-sea hydrothermal vent ecosystems use chemical energy (chemosynthesis) rather than solar energy as their primary energy source.'
    },
    {
      number: 7, part: 'A',
      text: 'Research has shown that treadmill training increases the number of certain energy-releasing structures in the brain cells of rats. The cellular structures referred to in this study are most likely',
      choices: ['mitochondria', 'vacuoles', 'nuclei', 'ribosomes'],
      topic: 'General', correct: 0,
      explanation: 'Mitochondria are the organelles that release energy from nutrients through cellular respiration; increased exercise increases the demand for energy, stimulating cells to produce more mitochondria.',
      diveDeep: 'Mitochondria carry out aerobic cellular respiration: glucose + O₂ → CO₂ + H₂O + ATP. More mitochondria mean more ATP production capacity. Treadmill exercise increases metabolic demands in neurons (brain cells), prompting mitochondrial biogenesis (production of new mitochondria). This is a real phenomenon: exercise increases mitochondrial density in muscle and brain cells, improving energy efficiency. Vacuoles store materials but do not release energy. Nuclei contain DNA. Ribosomes synthesize proteins. Connecting the description "energy-releasing structures" to mitochondria is a direct application of organelle function knowledge.', image: '/images/exams/le-june-2018/q7.png' },
    {
      number: 8, part: 'A',
      text: 'Which process must first take place in order for the proteins in foods to be used by body cells?',
      choices: ['digestion', 'synthesis', 'storage', 'excretion'],
      topic: 'General', correct: 0,
      explanation: 'Proteins in food must first be broken down (digested) into their amino acid building blocks before cells can absorb and use them to build their own proteins.',
      diveDeep: 'Digestion is the process of mechanically and chemically breaking down large food molecules into smaller, absorbable units. Proteins are broken down into amino acids by proteases (protein-digesting enzymes) in the stomach and small intestine. These amino acids are then absorbed into the bloodstream and transported to cells, where they are used for protein synthesis or energy. Synthesis means building up molecules and would come after digestion. Storage and excretion are processes that follow digestion. Without digestion, the intact food protein molecules are too large to pass through the intestinal wall and enter the blood.'
    },
    {
      number: 9, part: 'A',
      text: 'Which statement is characteristic of reproduction in humans?',
      choices: ['The reproductive cells of males and females differ in chromosome number.', 'Males and females produce gametes in the ovaries.', 'Males and females produce the same number of gametes.', 'The reproductive cycles of males and females are regulated by hormones.'],
      topic: 'Reproduction', correct: 3,
      image: '/images/exams/le-june-2018/q9.png',
      explanation: 'Both male and female reproductive cycles — spermatogenesis, ovulation, and the menstrual cycle — are regulated by hormones such as FSH, LH, testosterone, and estrogen.',
      diveDeep: 'The hypothalamus and pituitary gland release hormones (GnRH, FSH, LH) that regulate the gonads (testes and ovaries). In females, these hormones control the menstrual cycle and ovulation. In males, they regulate sperm production and testosterone secretion. Both male and female gametes (sperm and eggs) are haploid (n = 23 chromosomes in humans) — they do NOT differ in chromosome number. Only females produce gametes in ovaries; males produce sperm in testes. Females produce approximately one egg per month; males produce millions of sperm daily — they produce vastly different numbers. Hormonal regulation of reproduction is a key LE human biology concept.'
    },
    {
      number: 10, part: 'A',
      text: 'Which row in the chart represents the most likely changes in the atmosphere due to widespread deforestation?',
      choices: ['', '', '', ''],
      topic: 'General', correct: 2,
      image: '/images/exams/le-june-2018/q10.png',
      explanation: 'Deforestation removes trees that absorb CO₂ through photosynthesis and release O₂; without trees, CO₂ concentration in the atmosphere increases and O₂ concentration decreases.',
      diveDeep: 'Forests act as carbon sinks, absorbing CO₂ from the atmosphere during photosynthesis and storing carbon in wood and soil. When forests are cleared (especially by burning), stored carbon is released as CO₂ and the ongoing CO₂ absorption capacity is lost. This means atmospheric CO₂ increases. Simultaneously, less O₂ is released because photosynthesis is reduced. Deforestation is a major contributor to greenhouse gas emissions and climate change. This is a direct application of the photosynthesis equation: CO₂ + H₂O → glucose + O₂ — removing trees means less CO₂ is consumed and less O₂ is produced.'
    },
    {
      number: 11, part: 'A',
      text: 'The chart represents some of the events that occur during the cycling of nutrients in an ecosystem. X converts organic wastes into compounds usable by autotrophs. Which organisms would most appropriately complete the chart when written in the circle at X?',
      choices: ['producers', 'carnivores', 'herbivores', 'decomposers'],
      topic: 'Cell Biology', correct: 3,
      explanation: 'Decomposers (bacteria and fungi) break down organic waste and dead matter into inorganic nutrients that producers (autotrophs) can absorb and use.',
      diveDeep: 'Decomposers play a critical role in nutrient cycling by converting complex organic molecules (dead organisms, wastes) into simple inorganic compounds like nitrates, phosphates, and CO₂. These inorganic compounds are then taken up by autotrophs (plants, algae) and used to build new organic molecules. Without decomposers, dead organic matter would accumulate and nutrients would become unavailable to producers. Producers make their own food and do not convert waste. Carnivores and herbivores consume organisms but do not efficiently break organic waste into forms usable by autotrophs. Decomposers close the loop of nutrient cycling.', image: '/images/exams/le-june-2018/q11.png' },
    {
      number: 12, part: 'A',
      text: 'The diagram represents the formation of a cancerous growth. Time shows: Skin cells → (time) → Blood vessel → Cancerous growth. Which statement best explains the events represented in this diagram?',
      choices: ['A gene mutation caused the cells to become muscle cells.', 'The growth resulted from the introduction of a vaccine.', 'A gene mutation caused abnormal mitotic cell division.', 'The growth resulted from uncontrolled meiotic cell division.'],
      topic: 'Human Body', correct: 2,
      image: '/images/exams/le-june-2018/q12.png',
      explanation: 'Cancer occurs when mutations in genes that control the cell cycle cause cells to undergo uncontrolled mitotic division, forming a tumor (cancerous growth).',
      diveDeep: 'Normal cell division (mitosis) is tightly regulated by genes that control when cells divide and when they stop. Mutations in these regulatory genes (tumor suppressor genes or proto-oncogenes) can cause cells to divide uncontrollably, forming a mass of cells called a tumor. If the tumor invades surrounding tissue or spreads through blood vessels, it is malignant (cancerous). Meiosis produces gametes and only occurs in reproductive tissue — cancer is caused by abnormal mitosis. Vaccines stimulate the immune system and do not cause cell division. Cancer is fundamentally a disease of altered gene expression and uncontrolled cell division.'
    },
    {
      number: 13, part: 'A',
      text: 'A standard laboratory technique used to produce a new plant is represented in the diagram: One leaf cell removed → Cells grown in a laboratory → Cell division → Cell specialization → New tomato plant. This technique is best identified as',
      choices: ['gene alteration', 'selective breeding', 'replication', 'cloning'],
      topic: 'Cell Biology', correct: 3,
      image: '/images/exams/le-june-2018/q13.png',
      explanation: 'Starting with a single cell from an existing plant and growing it into a complete new plant via cell division and differentiation is cloning — the new plant is genetically identical to the original.',
      diveDeep: 'Plant cloning via tissue culture (somatic embryogenesis or organogenesis) exploits the totipotency of plant cells — their ability to develop into any cell type or a whole organism. A single differentiated leaf cell is de-differentiated in culture and then re-differentiated into a whole plant. The resulting plant is genetically identical to the donor. Gene alteration involves changing the DNA sequence. Selective breeding requires breeding two individuals over generations. DNA replication is the copying of DNA within a cell. Plant cloning is widely used in agriculture to mass-produce genetically identical crop plants with desirable traits.'
    },
    {
      number: 14, part: 'A',
      text: 'An example of competition between members of two different species is',
      choices: ['mold growing on a dead tree that has fallen in the forest', 'purple loosestrife plants growing in the same wet areas as cattail plants', 'a coyote feeding on the remains of a deer that died of starvation', 'two male turkeys displaying mating behaviors to attract a female turkey'],
      topic: 'Evolution', correct: 1,
      explanation: 'Purple loosestrife (an invasive plant) and cattail (a native plant) competing for the same wetland habitat is interspecific competition — competition between two different species.',
      diveDeep: 'Interspecific competition occurs when individuals of different species compete for the same limited resources (food, space, water, light). In contrast, intraspecific competition occurs among members of the same species. Two male turkeys competing for a female are intraspecific. Mold on a dead tree is decomposition, not competition. A coyote eating a dead deer is scavenging. Purple loosestrife is an invasive species that outcompetes native wetland plants like cattails for space, light, and nutrients — a textbook example of interspecific competition that harms native ecosystems.'
    },
    {
      number: 15, part: 'A',
      text: 'Which statement best explains why different body cells of the same individual look and function differently?',
      choices: ['Each cell contains different genes.', 'Different genes are activated in different kinds of cells.', 'Cells are able to change to adapt to their surroundings.', 'Half of the genes in the cells came from the mother and half from the father.'],
      topic: 'General', correct: 1,
      image: '/images/exams/le-june-2018/q15.png',
      explanation: 'All body cells contain the same complete DNA, but different genes are switched on or off in different cell types through gene expression regulation — this selective expression creates specialized cell types.',
      diveDeep: 'Differentiation — the process by which genetically identical cells develop different structures and functions — is controlled by gene expression. Chemical signals during development activate specific transcription factors that turn on certain genes and turn off others in each cell type. A muscle cell and a nerve cell have the same DNA but express different sets of genes, producing different proteins. Cells do not contain different genes (except for mutations); all somatic cells have the same genome. Cells do not "adapt" by changing their DNA. The maternal/paternal gene distribution is the same in all body cells. Gene expression regulation is the key to cellular differentiation.'
    },
    {
      number: 16, part: 'A',
      text: 'A diagram of the female reproductive system is shown. Identify the structure within which the egg cell is normally fertilized.',
      choices: ['A', 'C', 'B', 'D'],
      topic: 'Cell Biology', correct: 1,
      image: '/images/exams/le-june-2018/q16.png',
      explanation: 'Fertilization normally occurs in the fallopian tube (oviduct), where the sperm travels to meet the egg shortly after ovulation; structure C in the diagram represents the fallopian tube.',
      diveDeep: 'After ovulation, the egg is swept into the fallopian tube (oviduct) by cilia. Sperm that enter the female reproductive tract travel up through the uterus into the fallopian tube, where fertilization typically occurs. The resulting zygote then travels down the tube and implants in the uterine wall (endometrium) about 6–10 days later. Fertilization in the uterus or ovary is abnormal and can be dangerous (ectopic pregnancy). Understanding the sequence of events in human reproduction — ovulation, fertilization, implantation, development — is a key LE reproductive biology topic.'
    },
    {
      number: 17, part: 'A',
      text: 'The amoeba, a single-celled organism, reproduces asexually. Variations in an amoeba would most commonly occur through',
      choices: ['differentiation during development', 'the fusion of gametes', 'random mutations', 'recombination during fertilization'],
      topic: 'Cell Biology', correct: 2,
      explanation: 'Because amoebas reproduce asexually (no genetic recombination from two parents), the only source of genetic variation is random mutations in their DNA.',
      diveDeep: 'Asexual reproduction produces genetically identical offspring. Without meiosis, crossing-over, or fertilization, there is no mechanism for recombining genetic material from two parents. The only way variation can arise in asexually reproducing organisms is through random mutation — random errors in DNA replication or damage from environmental factors. Differentiation is a developmental process, not a source of genetic variation. Gamete fusion and recombination during fertilization are processes exclusive to sexual reproduction. This is why asexual organisms tend to be less genetically diverse than sexually reproducing ones.'
    },
    {
      number: 18, part: 'A',
      text: 'The development of organs and tissues from a zygote includes',
      choices: ['mitosis and differentiation', 'mitosis and gamete production', 'meiosis and gamete production', 'meiosis and fertilization'],
      topic: 'Reproduction', correct: 0,
      explanation: 'A zygote develops into an embryo through repeated mitotic divisions (increasing cell number) and differentiation (cells specializing into different tissue and organ types).',
      diveDeep: 'Embryonic development proceeds through cleavage (rapid mitotic divisions), gastrulation (formation of germ layers), and organogenesis (development of organs through differentiation). Mitosis ensures that all cells retain the full genome while increasing cell number. Differentiation is driven by gene expression changes: different sets of genes are activated in different cell lineages, causing cells to develop into muscle, nerve, epithelial, and other specialized types. Meiosis produces gametes and does not occur in developing embryonic tissues. Gamete production occurs in the gonads of a mature organism, not during embryonic development from a zygote.'
    },
    {
      number: 19, part: 'A',
      text: 'In the 1920s, over 25 million acres of the American southern plains were stripped of prairie grasses to provide more land for farmers to grow wheat. The prairie grasses had served to hold the soil in place and prevent erosion. In the early 1930s, a series of severe dust storms eroded topsoil from more than 13 million acres of the southern plains and dumped it as tons of dust particles over many cities in the Northeast. Farmland was destroyed and people were sickened from "dust pneumonia." This occurrence illustrates that',
      choices: ['farmers should never clear land to grow crops as it always creates problems', 'once an ecosystem has been altered, it can not be restored to normal', 'the farmers deliberately altered the equilibrium of the cities in the Northeast', 'when humans alter ecosystems, serious consequences may result'],
      topic: 'General', correct: 3,
      explanation: 'The Dust Bowl illustrates that large-scale human alteration of ecosystems — removing native vegetation — can have devastating unintended consequences for both the environment and human health.',
      diveDeep: 'The Dust Bowl of the 1930s was one of the worst ecological and agricultural disasters in American history. Removing deep-rooted prairie grasses exposed the soil to wind erosion. Without root systems to hold the soil, topsoil was carried away in massive dust storms. This caused widespread crop failure, economic hardship, and respiratory illness. The event does NOT mean farmers should never farm — many land use changes are managed sustainably. Ecosystems can often be restored with effort. The farmers did not intend to harm distant cities. The key lesson is that human activities can have far-reaching, unintended ecological consequences.'
    },
    {
      number: 20, part: 'A',
      text: 'The Cornell University News Service reported, "The sugar maple is the most economically valuable tree in the eastern United States because of its high-priced lumber, syrup and tourist-attracting fall colors." The effects of acid rain now threaten the survival of these trees. This threat is the result of a human activity that has',
      choices: ['introduced a foreign species by accident', 'stabilized a forest ecosystem through technology', 'weakened an ecosystem through pollution', 'weakened a species by direct harvesting'],
      topic: 'Evolution', correct: 2,
      explanation: 'Acid rain is caused by burning fossil fuels, which releases sulfur and nitrogen oxides that react with water vapor to form acids; this pollution weakens the sugar maple ecosystem by acidifying soil and water.',
      diveDeep: 'Acid rain forms when SO₂ and NOₓ — released by burning coal, oil, and vehicle exhaust — react with atmospheric water to form sulfuric and nitric acids. Acid rain lowers soil pH, leaching essential nutrients and releasing toxic aluminum ions. Sugar maples are particularly sensitive to acidified soil; they show reduced growth, leaf damage, and increased mortality in affected areas. This is pollution weakening an ecosystem — not an introduced species, not harvesting, not stabilization. Acid rain is a classic example of how industrial pollution can have widespread and geographically distant ecological effects.'
    },
    {
      number: 21, part: 'A',
      text: 'The human male reproductive system is adapted for the production of',
      choices: ['sperm and the delivery of these cells for internal fertilization', 'gametes that transport food to the egg', 'zygotes and the development of these cells into a fetus', 'hormones that stimulate placenta formation in the male'],
      topic: 'Reproduction', correct: 0,
      explanation: 'The male reproductive system produces sperm (male gametes) and delivers them into the female reproductive tract for internal fertilization.',
      diveDeep: 'The male reproductive system includes the testes (sperm production and testosterone secretion), epididymis (sperm maturation and storage), vas deferens (sperm transport), seminal vesicles and prostate (fluid production), and penis (sperm delivery). Internal fertilization — within the female\'s body — is characteristic of humans and most other terrestrial vertebrates. Gametes do not transport food to the egg; nutrients for the embryo come from the mother via the placenta. Zygotes form after fertilization and develop in the female uterus, not in the male. Males do not form placentas; that structure is only present in females during pregnancy.'
    },
    {
      number: 22, part: 'A',
      text: 'The diagram represents an important biological technique scientists rely on to produce replacement hormones: Human cell DNA → specific section of human DNA → inserted into bacterial DNA → bacterial cell produces hormone. Which two processes are required for the technique to successfully produce hormones?',
      choices: ['replication of DNA in bacterial cells and cell division', 'replication of DNA in bacterial cells and gamete formation', 'meiosis and development', 'mitosis and fertilization'],
      topic: 'Cell Biology', correct: 0,
      image: '/images/exams/le-june-2018/q22.png',
      explanation: 'Once recombinant DNA is inserted into bacteria, the bacteria must replicate their DNA and divide (mitosis/binary fission) to multiply and produce large quantities of the hormone.',
      diveDeep: 'Recombinant DNA technology involves inserting a human gene (e.g., the insulin gene) into a bacterial plasmid using restriction enzymes and DNA ligase. The modified bacteria then replicate their DNA (including the inserted gene) and divide by binary fission, producing colonies of hormone-secreting bacteria. Each cell division produces new bacteria containing the human gene, all capable of making the hormone. Gamete formation (meiosis) is not involved — bacteria reproduce asexually. This technology is used to produce human insulin, growth hormone, and other therapeutic proteins in large quantities. DNA replication and cell division are the two essential processes for scaling up production.'
    },
    {
      number: 23, part: 'A',
      text: 'The diagram summarizes some of the steps in the development of humans: sperm + egg → A (zygote) → B (embryo) → C (fetus) → D (newborn). All the genetic information needed for the organism to develop is first present at',
      choices: ['A', 'C', 'B', 'D'],
      topic: 'Cell Biology', correct: 0,
      image: '/images/exams/le-june-2018/q23.png',
      explanation: 'All the genetic information (the full genome) is first present at fertilization in the zygote (stage A), formed by the union of sperm and egg.',
      diveDeep: 'At fertilization, the sperm (haploid, n = 23) and egg (haploid, n = 23) fuse to form a zygote (diploid, 2n = 46). This single cell contains the complete genetic blueprint — all the DNA from both parents — needed to direct the development of the entire organism. Every subsequent cell in the developing embryo, fetus, and adult carries this same complete genetic information. No new genetic information is added after fertilization (barring mutations). The zygote is therefore the first cell to contain the full set of instructions. Understanding fertilization as the point of complete genetic assembly is a key LE reproductive biology concept.'
    },
    {
      number: 24, part: 'A',
      text: 'Five different living organisms are represented: Flowering plant, Mosquito larva, Frog, Green heron, Aquatic plant. Which statement about the organisms represented above is correct?',
      choices: ['All of the organisms are autotrophs.', 'Only the flowering plant, green heron, and aquatic plant carry out photosynthesis.', 'Only the frog and green heron can maintain homeostasis.', 'All of the organisms pass on traits through reproduction.'],
      topic: 'Cell Biology', correct: 3,
      image: '/images/exams/le-june-2018/q24.png',
      explanation: 'All living organisms — plants, animals, insects, and amphibians alike — pass on traits to offspring through reproduction, whether sexual or asexual.',
      diveDeep: 'Reproduction and heredity are universal characteristics of all living things. Whether an organism reproduces sexually (frogs, herons) or asexually, it passes genetic information to offspring. Not all organisms are autotrophs — mosquito larvae, frogs, and herons are all heterotrophs (consumers). Only the flowering plant and aquatic plant carry out photosynthesis; herons are animals and cannot photosynthesize. All organisms with cells can maintain homeostasis — it is not exclusive to vertebrates. The universal nature of heredity (passing traits through reproduction) is a fundamental principle of biology and evolution.'
    },
    { number: 25, part: 'A', text: 'During embryonic development, cells with the same DNA differentiate into nerve, muscle, and skin cells. Which statement best explains how this occurs?', choices: ['Each cell type contains a different DNA sequence.', 'Different genes are activated in each cell type.', 'Cells change their DNA to match their function.', 'Only stem cells contain all the genes needed for differentiation.'], topic: 'Cell Biology', correct: 1, explanation: 'All body cells contain identical DNA, but differentiation occurs because different genes are switched on (activated) and others are silenced in each cell type, producing different proteins that determine cell structure and function.', diveDeep: 'Gene expression is regulated by transcription factors and chemical signals during development. A nerve cell activates genes for ion channels and neurotransmitter synthesis while silencing muscle-specific genes; a muscle cell does the reverse. The DNA sequence is the same in every somatic cell (barring mutations). Cells do not alter their DNA to match their function. Stem cells do contain a full genome, but so does every differentiated cell — the difference is in which genes are expressed. Cellular differentiation is the foundation of multicellular development and explains how a single zygote gives rise to the hundreds of cell types in the human body.', image: '/images/exams/le-june-2018/q25.png' },
    { number: 26, part: 'A', text: 'Which statement is part of the cell theory?', choices: ['All cells are identical in structure and function.', 'Only eukaryotic organisms are made of cells.', 'All cells come from pre-existing cells.', 'Cells can arise spontaneously from non-living matter.'], topic: 'Cell Biology', correct: 2, explanation: 'The cell theory has three core principles: all living things are made of cells, the cell is the basic unit of life, and all cells come from pre-existing cells (biogenesis).', diveDeep: 'The cell theory, developed by Schleiden, Schwann, and Virchow in the 19th century, is one of the foundational principles of biology. "All cells come from pre-existing cells" (Virchow\'s contribution) disproved the older idea of spontaneous generation. Cells are not all identical — they range from prokaryotes to highly specialized eukaryotic types. Both prokaryotes and eukaryotes are made of cells. The idea that cells arise spontaneously from non-living matter was disproven by Pasteur\'s experiments. The cell theory applies to all living organisms without exception.' },
    { number: 27, part: 'A', text: 'A scientist studying evolutionary relationships among organisms constructs a branching diagram based on shared DNA sequences. This diagram is best described as', choices: ['a Punnett square', 'an energy pyramid', 'a phylogenetic tree', 'a food web'], topic: 'Evolution', correct: 2, explanation: 'Phylogenetic trees (cladograms) are branching diagrams that show evolutionary relationships among organisms based on shared characteristics or DNA sequence similarities.', diveDeep: 'Phylogenetics is the study of evolutionary history and relationships. A phylogenetic tree represents how different species diverged from common ancestors over time. Branches that share more recent common ancestors are more closely related. DNA sequence analysis provides molecular evidence for these relationships — the more similar the DNA sequences, the more recently two species diverged. Punnett squares predict genetic inheritance ratios. Energy pyramids show energy flow through trophic levels. Food webs show feeding relationships in an ecosystem. Phylogenetic trees are constructed using shared derived characteristics (synapomorphies) or molecular data.' },
    { number: 28, part: 'A', text: 'A person is exposed to a new bacterial pathogen and recovers. If exposed to the same pathogen years later, the immune response is faster and stronger. This is because', choices: ['the body produces more white blood cells during the second infection', 'memory cells from the first exposure quickly produce specific antibodies', 'the pathogen mutates and becomes weaker with each infection', 'the liver destroys the pathogen before the immune system responds'], topic: 'Human Body', correct: 1, explanation: 'After the first exposure, the immune system produces memory B cells that persist for years; upon re-exposure to the same antigen, these memory cells rapidly proliferate and produce large amounts of specific antibodies, creating a faster, stronger secondary immune response.', diveDeep: 'The first encounter with a pathogen (primary immune response) takes days to produce enough antibodies to clear the infection. During this time, B cells differentiate into plasma cells (antibody-producing) and long-lived memory B cells. When the same antigen is encountered again, memory cells rapidly divide and differentiate, producing antibodies within hours — the secondary (anamnestic) immune response. This principle underlies vaccination: exposing the immune system to an antigen (dead or weakened pathogen) creates memory cells without causing disease. The pathogen does not weaken between exposures. The liver does not destroy pathogens in this manner. White blood cell numbers increase, but the key mechanism is immunological memory.' },
    { number: 29, part: 'A', text: 'A pesticide sprayed on crops enters the soil and waterways. Tiny organisms absorb the pesticide, small fish eat many of these organisms, and large fish eat many small fish. Which statement best describes the concentration of the pesticide in these organisms?', choices: ['Pesticide concentration is highest in the tiny organisms at the base of the food chain.', 'Pesticide concentration is the same in all organisms because it came from one source.', 'Pesticide concentration increases at higher trophic levels through biomagnification.', 'Pesticide concentration decreases in larger organisms because they can detoxify it faster.'], topic: 'Ecology', correct: 2, explanation: 'Biomagnification is the process by which persistent pollutants (like DDT or heavy metals) become increasingly concentrated at higher trophic levels, because each consumer accumulates the toxins from all the organisms it eats.', diveDeep: 'Biomagnification occurs because many toxic chemicals (fat-soluble pesticides, mercury, PCBs) are not excreted efficiently and accumulate in fatty tissues. A small fish eats thousands of contaminated plankton, concentrating all their toxin load. A large fish eats thousands of small fish, concentrating the toxin even further. Top predators (eagles, sharks, humans) can have pesticide concentrations millions of times higher than the water. The classic example is DDT, which caused eggshell thinning in bald eagles. Concentration is LOWEST in producers and HIGHEST in top predators. All organisms receive the same source but accumulate different amounts based on trophic position.' },
    { number: 30, part: 'A', text: 'During meiosis, genes on different chromosomes are distributed into gametes independently of one another. This is known as', choices: ['crossing-over', 'the law of independent assortment', 'the law of dominance', 'genetic linkage'], topic: 'Genetics', correct: 1, explanation: 'Mendel\'s law of independent assortment states that genes located on different (non-homologous) chromosomes are distributed to gametes independently during meiosis, increasing genetic variation in offspring.', diveDeep: 'Independent assortment occurs during meiosis I, when homologous chromosome pairs line up at the cell\'s equator and separate randomly. Since humans have 23 pairs of chromosomes, there are 2²³ (over 8 million) possible combinations of chromosomes in gametes from independent assortment alone — before accounting for crossing-over. This law applies to genes on different chromosomes; genes on the same chromosome tend to be inherited together (genetic linkage) unless crossing-over separates them. The law of dominance describes how dominant alleles mask recessive ones in heterozygotes. Independent assortment, crossing-over, and random fertilization together produce the enormous genetic diversity seen in sexually reproducing organisms.', image: '/images/exams/le-june-2018/q30.png' },
    { number: 31, part: 'B-1', text: 'The diagram shows the phospholipid bilayer of a cell membrane with embedded proteins. Which molecules can pass directly through the lipid bilayer without using protein channels?', choices: ['Glucose and sodium ions', 'Large polar molecules and ions', 'Small nonpolar molecules such as O₂ and CO₂', 'Water molecules and charged particles'], topic: 'Cell Biology', correct: 2, image: '/images/exams/le-june-2018/q31.png', explanation: 'Small, nonpolar (hydrophobic) molecules like O₂ and CO₂ can dissolve directly in the lipid bilayer and diffuse through it without needing protein channels, because the interior of the bilayer is hydrophobic.', diveDeep: 'The phospholipid bilayer has a hydrophobic (water-repelling) interior composed of fatty acid tails. Nonpolar, uncharged molecules (O₂, CO₂, steroid hormones) are also hydrophobic and can dissolve in this region, passing through by simple diffusion along their concentration gradient. Polar molecules (glucose, amino acids) and ions (Na⁺, K⁺, Cl⁻) cannot cross the hydrophobic interior and require specialized transport proteins (channels or carriers). Water is a small polar molecule that crosses mainly through aquaporin protein channels, though it can cross slowly by simple diffusion. The selective permeability of the cell membrane is crucial for maintaining internal homeostasis.' },
    { number: 32, part: 'B-1', text: 'A graph shows dissolved oxygen levels in a lake are lowest in summer and highest in winter. Which organisms would be most stressed by the low summer oxygen levels?', choices: ['Anaerobic bacteria that do not need oxygen', 'Aquatic plants that produce oxygen through photosynthesis', 'Fish and other aerobic aquatic organisms that require dissolved oxygen for respiration', 'Decomposers that break down organic matter on the lake bottom'], topic: 'Ecology', correct: 2, image: '/images/exams/le-june-2018/context_32_32.png', explanation: 'Fish and other aerobic aquatic animals depend on dissolved oxygen (DO) for cellular respiration; when DO levels drop in summer (warm water holds less gas), aerobic organisms are physiologically stressed and may die.', diveDeep: 'Dissolved oxygen decreases in summer because warm water holds less dissolved gas than cold water (Henry\'s Law). Additionally, decomposer bacteria are more active in warm water, consuming oxygen. Fish extract dissolved O₂ from water through their gills for aerobic respiration. When DO drops below about 5 mg/L, many fish species show stress; below 2 mg/L is lethal for most. Anaerobic bacteria thrive in low-oxygen conditions and are not stressed. Aquatic plants produce O₂ through photosynthesis and can acquire CO₂ for their own use. Decomposers actually contribute to low DO by consuming it. Summer hypoxia (low DO) is a serious ecological problem in many lakes, especially those with excess nutrients (eutrophication).' },
    { number: 33, part: 'B-1', text: 'A Punnett square shows the cross BbRr × BbRr. What fraction of offspring will be homozygous recessive for both traits (bbrr)?', choices: ['1/4', '1/8', '1/16', '3/16'], topic: 'Genetics', correct: 2, explanation: 'In a dihybrid cross BbRr × BbRr, the probability of being homozygous recessive for one trait is 1/4; for both traits independently, it is 1/4 × 1/4 = 1/16.', diveDeep: 'Using the product rule: P(bb) = 1/4 and P(rr) = 1/4 for each trait in a Bb × Bb cross. Since the two genes are on different chromosomes (independent assortment), P(bbrr) = P(bb) × P(rr) = 1/4 × 1/4 = 1/16. A full 4×4 Punnett square for BbRr × BbRr yields 16 possible combinations: 9 B_R_ : 3 B_rr : 3 bbR_ : 1 bbrr — the classic 9:3:3:1 ratio. The 1 in 16 fraction corresponds to the homozygous recessive genotype for both traits. Understanding the product rule for independent events is faster than drawing a 16-square Punnett square and is an important test-taking skill.', image: '/images/exams/le-june-2018/q33.png' },
    { number: 34, part: 'B-1', text: 'A diagram shows a marine food web where an oil spill causes a sharp decline in algae (producers). Why do consumer populations also decline after the producers decline?', choices: ['Consumers absorb oil directly from the water through their skin.', 'Consumers depend on producers as their original source of energy; less producer biomass means less energy for consumers.', 'The oil spill raises water temperature, killing consumers directly.', 'Consumers compete with producers for the same nutrients.'], topic: 'Ecology', correct: 1, image: '/images/exams/le-june-2018/q34.png', explanation: 'All consumer organisms ultimately depend on producers (autotrophs) for energy; when producer populations decline, less energy enters the food web, and consumer populations at all levels decline as a consequence.', diveDeep: 'Energy flows through an ecosystem in one direction: from producers (who capture solar energy via photosynthesis) to primary consumers to secondary consumers and so on. Each trophic level depends on the one below it for its energy supply. When algae (producers) are killed by an oil spill, the entire energy base of the food web is reduced. Primary consumers (zooplankton, small fish) starve; their predators then also decline. This cascade of effects through a food web is called a trophic cascade. Oil spills also cause direct toxicity to animals, but the fundamental ecological mechanism here is the dependence of consumers on producers for energy flow. This illustrates why protecting producers is critical for ecosystem health.' },
    { number: 35, part: 'B-1', text: 'A diagram shows the location of endocrine glands in the human body. Which gland is called the "master gland" because it regulates many other endocrine glands?', choices: ['Thyroid gland', 'Adrenal gland', 'Pancreas', 'Pituitary gland'], topic: 'Human Body', correct: 3, image: '/images/exams/le-june-2018/q35.png', explanation: 'The pituitary gland, located at the base of the brain, is called the master gland because it secretes hormones that regulate the activity of the thyroid, adrenal glands, gonads, and other endocrine glands.', diveDeep: 'The pituitary gland has two lobes — anterior and posterior — and secretes over eight major hormones. The anterior pituitary produces TSH (stimulates thyroid), ACTH (stimulates adrenal cortex), FSH and LH (stimulate gonads), GH (growth hormone), and others. The posterior pituitary releases ADH (water reabsorption) and oxytocin (uterine contractions and milk ejection). The pituitary itself is regulated by the hypothalamus via releasing and inhibiting hormones, creating a three-tier regulatory hierarchy. The thyroid regulates metabolism. The adrenal glands respond to stress. The pancreas regulates blood glucose. None of these have the broad regulatory influence over other glands that the pituitary has.' },
    { number: 36, part: 'B-1', text: 'A graph shows the frequency of an allele in a population increasing steadily over 20 generations. What is the most likely explanation for this change in allele frequency?', choices: ['The allele appeared through genetic engineering.', 'Random genetic drift eliminated competing alleles.', 'Natural selection is favoring this allele because it provides a survival or reproductive advantage.', 'Mutation rates increased in the population over time.'], topic: 'Evolution', correct: 2, image: '/images/exams/le-june-2018/q36.png', explanation: 'A steady increase in allele frequency over many generations is the hallmark of natural selection — the allele must be providing its carriers with a survival or reproductive advantage, causing it to be passed on more frequently.', diveDeep: 'Natural selection acts on heritable variation: individuals with alleles that improve survival or reproduction leave more offspring, passing those alleles to the next generation at higher frequencies. Over many generations, this systematic directional change in allele frequency is called directional selection. Genetic drift is a random process more likely to cause fluctuating, unpredictable changes in allele frequency (especially in small populations), not a steady directional increase. Genetic engineering is a human technology, not a natural population process. Mutation introduces new alleles but does not by itself cause them to increase steadily. The graph pattern — steady increase over many generations — specifically indicates systematic selection, not chance.' },
    { number: 37, part: 'B-1', text: 'A diagram shows a plant cell in a hypertonic solution where the cell membrane has pulled away from the cell wall (plasmolysis). What process caused the cell membrane to pull away from the cell wall?', choices: ['Active transport pumped water into the cell against its concentration gradient.', 'Osmosis — water moved out of the cell toward the higher solute concentration outside.', 'The cell wall contracted in response to high salt concentration.', 'Diffusion of solutes into the cell increased internal pressure.'], topic: 'Cell Biology', correct: 1, image: '/images/exams/le-june-2018/q37.png', explanation: 'Plasmolysis occurs when a plant cell is placed in a hypertonic (high solute) solution; water leaves the cell by osmosis (moving toward higher solute concentration), causing the cell membrane to shrink and pull away from the rigid cell wall.', diveDeep: 'Osmosis is the diffusion of water across a selectively permeable membrane from a region of lower solute concentration (higher water concentration) to a region of higher solute concentration (lower water concentration). In a hypertonic solution, the outside has more solutes than the inside of the cell. Water moves outward by osmosis, causing the cytoplasm to shrink (plasmolysis). The cell wall is rigid and does not contract with the membrane, so a gap appears between the membrane and wall. The reverse — cells taking up water in a hypotonic solution — causes turgor pressure, which helps plants maintain their structure. Plasmolysis can be reversed by placing the cell in a hypotonic solution (deplasmolysis).' },
    { number: 38, part: 'B-1', text: 'A scientist divides fruit flies into two groups — one kept at 20°C and one at 30°C. After several generations, genetic differences appear between the two groups. What evolutionary process is most likely occurring?', choices: ['Artificial selection — the scientist is choosing which flies to breed.', 'Natural selection — different temperatures create different selection pressures, favoring different alleles in each group.', 'Mutation — higher temperature causes more DNA mutations.', 'Gene flow — flies are moving between the two groups and mixing genes.'], topic: 'Evolution', correct: 1, explanation: 'Different temperature environments create different selection pressures on the two populations; alleles that improve survival and reproduction at 20°C differ from those favored at 30°C, causing the two populations to diverge genetically over generations through natural selection.', diveDeep: 'Environmental conditions act as selective pressures that favor certain phenotypes (and their underlying genotypes) over others. At 30°C, enzymes that function better at higher temperatures may confer a fitness advantage; at 20°C, different enzyme variants may be favored. Over generations, the allele frequencies in the two groups diverge as each adapts to its temperature. Artificial selection requires human-directed breeding choices — the scientist is only setting temperature conditions, not choosing which flies reproduce. Mutations occur, but a steady directional genetic change requires selection pressure, not just increased mutation rate. Gene flow would reduce genetic differences between groups, not increase them. This experiment is analogous to allopatric speciation in nature.' },
    { number: 39, part: 'B-1', text: 'A diagram shows the human lymphatic system including lymph nodes, lymph vessels, spleen, and thymus. What is the primary function of the lymph nodes?', choices: ['Produce red blood cells for oxygen transport', 'Filter lymph fluid and contain immune cells that detect and destroy pathogens', 'Regulate the concentration of hormones in the blood', 'Absorb nutrients from digested food'], topic: 'Human Body', correct: 1, image: '/images/exams/le-june-2018/q39.png', explanation: 'Lymph nodes are small, bean-shaped structures that filter lymph fluid and house lymphocytes (white blood cells) that identify and destroy pathogens, abnormal cells, and foreign particles.', diveDeep: 'The lymphatic system collects excess interstitial fluid (tissue fluid) as lymph and returns it to the bloodstream. As lymph travels through lymph nodes, it is filtered: macrophages engulf debris and pathogens, while B and T lymphocytes respond to any antigens detected. Lymph nodes swell when fighting infection (swollen glands) because lymphocytes are rapidly multiplying. The spleen filters blood (not lymph) and removes old red blood cells. The thymus is where T cells mature. Red blood cells are produced in red bone marrow, not lymph nodes. Hormones are regulated by endocrine glands. Nutrient absorption occurs in the small intestine. Lymph nodes are critical checkpoints in the immune defense network.' },
    { number: 40, part: 'B-1', text: 'A table shows species counts in five habitats before and after a deforestation event — all habitats show significant species loss. What is the most significant ecological consequence of this habitat loss?', choices: ['Increased rate of photosynthesis in remaining plants', 'Decreased biodiversity and increased species extinction rates', 'Greater soil fertility due to decomposition of fallen trees', 'More sunlight reaching the ground, benefiting shade-tolerant plants'], topic: 'Ecology', correct: 1, explanation: 'Habitat loss is the leading cause of biodiversity loss worldwide; when habitats are destroyed, the species that depend on them lose their food, shelter, and breeding sites, leading to population decline and extinction.', diveDeep: 'Biodiversity — the variety of species in an ecosystem — is directly tied to habitat availability. Deforestation removes the habitat on which forest species depend for food, shelter, nesting, and other requirements. Smaller, fragmented habitats support fewer species and smaller populations that are more vulnerable to extinction from chance events (edge effects, disease, inbreeding). Globally, habitat destruction is the primary driver of the current mass extinction event, with deforestation of tropical rainforests being particularly significant because these biomes harbor the greatest biodiversity. While decomposition may temporarily release nutrients, and light levels do increase, neither benefit compensates for the massive loss of species. Biodiversity loss reduces ecosystem resilience and the services ecosystems provide.' },
    { number: 41, part: 'B-1', text: 'A diagram shows the stages of cellular respiration: glycolysis → pyruvate oxidation → Krebs cycle → electron transport chain. Where does glycolysis occur in the cell?', choices: ['Inner mitochondrial membrane', 'Mitochondrial matrix', 'Nucleus', 'Cytoplasm'], topic: 'Cell Biology', correct: 3, image: '/images/exams/le-june-2018/q41.png', explanation: 'Glycolysis occurs in the cytoplasm (cytosol) of the cell and does not require mitochondria; it is the first stage of cellular respiration and is present in virtually all living organisms, including those without mitochondria.', diveDeep: 'Glycolysis (from Greek: "glucose splitting") is the breakdown of one glucose molecule into two pyruvate molecules in the cytoplasm. It produces a small net gain of 2 ATP and 2 NADH. Because it occurs in the cytoplasm, glycolysis can proceed even in anaerobic conditions (without oxygen) — this is the basis of fermentation. Pyruvate then enters the mitochondria (if oxygen is available): pyruvate oxidation and the Krebs cycle occur in the mitochondrial matrix, and the electron transport chain occurs on the inner mitochondrial membrane. The location of glycolysis in the cytoplasm explains why anaerobic organisms (yeast, bacteria) can still carry out this step. The evolutionary origin of glycolysis predates mitochondria, reflecting its ancient importance.' },
    { number: 42, part: 'B-1', text: 'A researcher uses PCR (polymerase chain reaction) to amplify a specific gene from a small blood sample before analyzing the DNA. Why is PCR necessary before analysis?', choices: ['PCR repairs damaged sections of the DNA in the blood sample.', 'PCR separates DNA strands by blood type for more accurate analysis.', 'The original sample contains too little DNA; PCR produces millions of copies of the target sequence for analysis.', 'PCR converts RNA in the sample into DNA for sequencing.'], topic: 'Genetics', correct: 2, explanation: 'PCR amplifies (copies) a specific DNA sequence exponentially; a tiny starting sample (even from a single cell) can be amplified to billions of copies, providing enough DNA for gel electrophoresis, sequencing, or other analyses.', diveDeep: 'PCR mimics DNA replication in vitro. It uses heat to denature (separate) double-stranded DNA, then primers (short DNA sequences complementary to the target) bind to each strand, and a heat-stable DNA polymerase (Taq polymerase) extends new strands. Each cycle doubles the amount of target DNA; after 30 cycles, the original target sequence has been amplified over a billion times. PCR does not repair DNA, separate by blood type, or convert RNA to DNA (that is reverse transcription/RT-PCR, a separate technique). PCR is essential in forensic DNA analysis, disease diagnosis, genetic testing, and research — it allows analysis of samples too small for direct study, including ancient DNA from fossils.', image: '/images/exams/le-june-2018/context_42_43.png' },
    { number: 43, part: 'B-1', text: 'A graph comparing deforestation rates and species extinction rates in tropical countries shows that as deforestation increases, extinction rates also increase. What type of relationship is shown by this data?', choices: ['Negative correlation — as one variable increases, the other decreases', 'No correlation — the two variables are independent', 'Positive correlation — as one variable increases, the other also increases', 'Inverse relationship — deforestation causes extinction to decrease over time'], topic: 'Ecology', correct: 2, image: '/images/exams/le-june-2018/context_42_43.png', explanation: 'A positive correlation means that two variables increase together; as deforestation rate increases, the species extinction rate also increases, indicating that habitat loss drives extinction.', diveDeep: 'Correlation describes the direction and strength of a statistical relationship between two variables. A positive (direct) correlation means both variables change in the same direction. In this case, data from tropical countries consistently show that regions with higher deforestation rates have higher species extinction rates — supporting the scientific consensus that habitat destruction is the leading driver of biodiversity loss. Correlation does not by itself prove causation, but combined with ecological knowledge about habitat requirements, the causal mechanism is well supported: fewer trees = less habitat = fewer species. A negative correlation would mean extinction decreases as deforestation increases (incorrect). No correlation would mean the variables are unrelated (incorrect). This graph-reading skill — identifying correlation type — is frequently tested on the Living Environment Regents.' },
  ]
}
