// Living Environment Regents — June 2017
export default {
  id: 'li-jun-2017',
  subject: 'living-environment',
  year: 2017,
  session: 'June',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'An example of recycling is',
      choices: ['using a paper cup instead of a mug', 'turning off the lights when leaving a room', 'using plastic from a soda bottle to make a certain type of clothing', 'using two paper towels rather than five to clean up a spill'],
      topic: 'General', correct: 2,
      explanation: 'Recycling means taking a used material and reprocessing it into a new product; converting soda bottle plastic into clothing fabric is a direct example of recycling.',
      diveDeep: 'Recycling involves collecting used materials, processing them, and manufacturing them into new products, reducing the need to extract new raw materials. Turning off lights is conservation (reducing energy use). Using fewer paper towels is reduction (using less). Using a paper cup instead of a mug actually generates more waste. The three R\'s in environmental science — Reduce, Reuse, Recycle — are a hierarchy: reducing consumption is best, reusing next, and recycling last. Recognizing these distinctions is part of LE environmental literacy.'
    },
    {
      number: 2, part: 'A',
      text: 'One characteristic of a stable ecosystem is',
      choices: ['a high number of predators', 'an interdependence of organisms', 'a lack of biodiversity', 'an increase in human interference'],
      topic: 'Ecology', correct: 1,
      explanation: 'Stable ecosystems are characterized by complex interdependencies among organisms — multiple food chains, symbiotic relationships, and nutrient cycles — that create resilience against change.',
      diveDeep: 'Ecosystem stability results from biodiversity and the web of interdependencies among species. A high number of predators alone does not ensure stability (it could indicate imbalance). Lack of biodiversity makes an ecosystem fragile, not stable. Human interference often disrupts stability. Interdependence means species rely on each other and on abiotic factors in ways that buffer the system against change. The more species and relationships present, the more pathways exist for energy and materials to flow, providing redundancy and resilience.'
    },
    {
      number: 3, part: 'A',
      text: 'According to scientists, ocean waves could be a source of energy. Devices are being designed to capture the energy from waves and supply electricity to coastal areas. A direct benefit of utilizing this technology to produce energy would be the',
      choices: ['destruction of habitats near the devices', 'decreased use of nonrenewable resources', 'release of gases needed for photosynthesis', 'increased use of finite resources'],
      topic: 'General', correct: 1,
      explanation: 'Wave energy is renewable; using it to generate electricity reduces reliance on nonrenewable fossil fuels like coal and oil, conserving those finite resources.',
      diveDeep: 'Renewable energy sources — solar, wind, wave, and geothermal — do not deplete finite resources and produce little to no greenhouse gas emissions. Ocean waves are driven by wind, which is ultimately powered by the sun. Habitat destruction near devices would be a trade-off or negative consequence, not a benefit. Photosynthesis requires CO₂ and light, not gases released by wave energy. Finite resources (fossil fuels) are what we want to use less of, not more. The shift from nonrenewable to renewable energy is a central environmental science theme in LE.'
    },
    {
      number: 4, part: 'A',
      text: 'The emerald ash borer is an insect that is thought to have been accidentally brought to the United States from China in shipping containers. It attacks ash trees, eventually killing the trees, destroying an important part of the ecosystem. The presence of the emerald ash borer in the United States can be used as an example of how humans have',
      choices: ['purposely introduced an insect to correct a problem in an ecosystem', 'used an insect to remove one insect species and replace it with another', 'worked to increase the biodiversity in a particular area', 'altered the equilibrium in an ecosystem by introducing a new species'],
      topic: 'Ecology', correct: 3,
      explanation: 'The accidental introduction of the emerald ash borer disrupted the equilibrium of native ecosystems by introducing a species that the native ash trees had no defenses against.',
      diveDeep: 'Ecological equilibrium is the balance of populations and interactions in a stable ecosystem. Introducing an invasive species — even accidentally — can disrupt this balance because the new organism has no natural predators in its new environment, allowing its population to grow unchecked. The emerald ash borer has killed hundreds of millions of ash trees across North America. It was not introduced intentionally or to solve an ecological problem. The introduction reduced biodiversity by destroying a key tree species. Invasive species are a major driver of biodiversity loss worldwide.'
    },
    {
      number: 5, part: 'A',
      text: 'Which graph best shows the changes in global human population and natural resource use over the past 500 years?',
      choices: ['', '', '', ''],
      topic: 'General', correct: 2,
      image: '/images/exams/le-june-2017/q5.png',
      explanation: 'Both human population and natural resource use have increased exponentially over the past 500 years, especially accelerating with the Industrial Revolution; the correct graph shows both curves rising steeply together.',
      diveDeep: 'Human population grew slowly for most of history but began accelerating in the 18th century with advances in agriculture, medicine, and sanitation. Resource use tracks closely with population growth and industrialization, as more people require more food, energy, and materials. An exponential growth pattern — a J-shaped curve — best describes both trends. Understanding the relationship between human population growth and resource depletion is a core LE environmental topic. Graphs showing both population and resource use rising steeply together reflect the reality of the last two centuries.'
    },
    {
      number: 6, part: 'A',
      text: 'The burning of fossil fuels has harmed the environment by',
      choices: ['decreasing acid rain in the northeast United States', 'adding carbon dioxide to the atmosphere', 'increasing biodiversity in the lakes and ponds of the Adirondacks', 'depleting the ozone shield directly over western New York State'],
      topic: 'Evolution', correct: 1,
      explanation: 'Burning fossil fuels releases CO₂, a greenhouse gas, into the atmosphere, contributing to global warming and climate change.',
      diveDeep: 'Fossil fuels (coal, oil, natural gas) are composed of ancient organic carbon. Burning them releases CO₂ that had been sequestered for millions of years, increasing atmospheric CO₂ concentrations. This enhanced greenhouse effect traps more heat, leading to global warming. Burning fossil fuels also releases sulfur and nitrogen oxides, which form acid rain — acid rain INCREASES in affected areas, not decreases. The ozone shield is damaged primarily by chlorofluorocarbons (CFCs), not CO₂. Acid rain harms lakes and reduces biodiversity; it does not increase it. CO₂ and fossil fuel combustion are central to LE environmental science.'
    },
    {
      number: 7, part: 'A',
      text: 'Which method of collecting data would provide the most accurate information about how an ecosystem is being affected by human development?',
      choices: ['The people in the neighborhood record the number of birds they see in the area both before and after the construction of a new building.', 'Deer in the area are identified before construction so that scientists can see where they go after the building is finished.', 'More trees are planted in the area around the construction site to allow the animals a new place to live.', 'The population size is recorded for each species present in the construction area before and after the building is completed.'],
      topic: 'Ecology', correct: 3,
      explanation: 'Recording population sizes for all species before and after construction provides systematic, quantitative, comparable data across the entire ecosystem — the most scientifically rigorous approach.',
      diveDeep: 'Good scientific data collection requires objectivity, standardization, and coverage of the full scope of the question. Measuring population sizes for all species before and after construction provides a complete picture of ecosystem change. Neighbor observations are subjective and limited to birds. Tracking only deer focuses on a single species. Planting trees is a mitigation action, not a data collection method. The key experimental design principle here is measuring relevant variables (species populations) before and after an intervention (construction), using quantitative methods. This is a scientific method application question.'
    },
    {
      number: 8, part: 'A',
      text: 'Natural selection produces changes most quickly in',
      choices: ['species with short reproductive cycles', 'individual pathogens killed by antibiotics', 'complex multicellular organisms', 'individuals that produce a small number of offspring'],
      topic: 'Evolution', correct: 0,
      explanation: 'Species that reproduce quickly (short generation times) produce more generations per unit time, allowing natural selection to act more rapidly and drive faster evolutionary change.',
      diveDeep: 'The rate of evolution by natural selection depends on how quickly generations turn over. Bacteria with 20-minute reproductive cycles can evolve antibiotic resistance in hours to days. Elephants, which reproduce every decade, evolve much more slowly. Individual pathogens killed by antibiotics are dead; they do not evolve. Complex multicellular organisms generally have long reproductive cycles. A small number of offspring slows the spread of new advantageous traits through a population. This explains why microbes (bacteria, viruses) are such rapid evolvers and why antibiotic/antiviral resistance is such a pressing concern.'
    },
    {
      number: 9, part: 'A',
      text: 'As a result of habitat destruction, the size of the Florida panther population has been drastically reduced. It is estimated that there are only 100 to 160 Florida panthers in the wild. Which statement best explains why the Florida panther population may not continue to evolve?',
      choices: ['There is no longer a chance of mutations occurring in the population.', 'There is a lack of competition for limited environmental resources.', 'There is no longer a chance of a trait providing a reproductive advantage to the population.', 'There is a lack of genetic variation for selection to act upon.'],
      topic: 'Ecology', correct: 3,
      explanation: 'With so few individuals, the Florida panther population has very limited genetic diversity; without variation, natural selection has nothing to act on and evolution stalls.',
      diveDeep: 'A very small population experiences genetic bottleneck and inbreeding, which drastically reduces genetic variation. Evolution requires heritable variation — without it, natural selection cannot favor some individuals over others, and the population\'s genetic makeup cannot change. Mutations still occur in small populations, but at a very low rate that may be insufficient to provide meaningful variation. Inbreeding also increases the expression of harmful recessive alleles, threatening population health. Conservation biologists often introduce individuals from other populations to increase genetic diversity — a practice called genetic rescue.'
    },
    {
      number: 10, part: 'A',
      text: 'Which level of the pyramid is correctly paired with the type of organism that would most likely be found at that level in an ecosystem? Level A (bottom), Level B, Level C, Level D (top)',
      choices: ['Level A – producers', 'Level B – carnivores', 'Level C – herbivores', 'Level D – decomposers'],
      topic: 'Cell Biology', correct: 0,
      explanation: 'In an energy pyramid, producers (plants) form the base (Level A) because they capture the most energy from the sun; each higher level contains less energy as it is lost as heat.',
      diveDeep: 'An energy or ecological pyramid shows that producers (autotrophs) occupy the bottom level and are the most numerous and energy-rich. Herbivores (primary consumers) occupy the next level, followed by carnivores (secondary and tertiary consumers) at higher levels. Decomposers break down organic matter from all levels and are sometimes shown separately. Approximately 10% of energy is transferred from one trophic level to the next; the rest is lost as heat. The wide base of producers is necessary to support the smaller number of consumers above. Decomposers are NOT at the top of the pyramid.', image: '/images/exams/le-june-2017/q10.png' },
    {
      number: 11, part: 'A',
      text: 'Which statement best describes what is most likely to occur if an animal population grows larger than the carrying capacity of its environment?',
      choices: ['The birth rate will increase.', 'Both the birth rate and death rate will decrease.', 'The death rate will increase.', 'Neither the birth rate nor the death rate will decrease.'],
      topic: 'Ecology', correct: 2,
      explanation: 'When a population exceeds carrying capacity, resources become scarce, leading to increased competition, starvation, and disease, which raises the death rate until the population falls back to or below carrying capacity.',
      diveDeep: 'Carrying capacity (K) is the maximum sustainable population size given available resources. When a population overshoots K, resources per individual decrease — there is not enough food, water, or space for all individuals. Increased competition and resource scarcity raise mortality (death rate increases) and may also reduce reproductive success (birth rate may decrease). The population then declines back toward K, a process described by the logistic growth model. Birth rate does not increase when resources are scarce. Understanding population dynamics around carrying capacity is a fundamental LE ecology concept.'
    },
    {
      number: 12, part: 'A',
      text: 'Many biotic factors affect individuals in a population. An example of an organism being directly affected by a biotic factor is',
      choices: ['a squirrel cannot find a mate', 'a flood washes away a maple tree', 'a plant is in a dark room', 'a chipmunk finds a rock pile to use for a home'],
      topic: 'Cell Biology', correct: 0,
      explanation: 'A biotic factor is a living component of the environment; not finding a mate involves another organism (another squirrel), making it a biotic factor affecting the squirrel.',
      diveDeep: 'Biotic factors include all living organisms and their interactions — predation, competition, symbiosis, and mating. Abiotic factors are non-living physical or chemical components: light, temperature, water, minerals. A flood (water) is abiotic. A dark room lacks light (abiotic). A rock pile is an abiotic physical feature. Not finding a mate directly involves the absence of another living organism, making it biotic. Distinguishing between biotic and abiotic factors is a foundational LE ecology concept and appears regularly on the Regents.'
    },
    {
      number: 13, part: 'A',
      text: 'When people receive organ transplants, they often need to take medications that decrease immune responses because',
      choices: ['transplanted organs contain antigens that can trigger white blood cell activity', 'hormones present in replacement organs prevent the synthesis of antibiotics', 'transplanted organs produce their own antibiotics', 'antigens present in these organs attack antibodies already present in the blood'],
      topic: 'Human Body', correct: 0,
      explanation: 'Foreign organs carry surface proteins (antigens) that the recipient\'s immune system recognizes as non-self, triggering white blood cells to attack and reject the transplant.',
      diveDeep: 'Every person\'s cells have unique surface proteins (MHC molecules) that function as antigens. When an organ from a different person is transplanted, the recipient\'s immune system recognizes these foreign antigens and mounts an immune response — organ rejection. Immunosuppressant drugs reduce this response to allow the transplanted organ to survive. Antibiotics are produced by microorganisms (not organs) and fight bacterial infections. Antigens do not attack antibodies; it is the other way around — antibodies bind to antigens. Transplant medicine represents a practical application of immune response knowledge.'
    },
    {
      number: 14, part: 'A',
      text: 'Which structures regulate water loss and gas exchange in the leaves of plants?',
      choices: ['vacuoles', 'guard cells', 'chloroplasts', 'mitochondria'],
      topic: 'General', correct: 1,
      explanation: 'Guard cells surround the stomata (tiny pores) on leaf surfaces; by changing shape, they open or close the stomata to regulate water loss (transpiration) and gas exchange (CO₂ in, O₂ out).',
      diveDeep: 'Guard cells are specialized kidney-shaped cells that flank each stoma. When they are turgid (full of water), they bow outward and the stoma opens, allowing CO₂ to enter and O₂ and water vapor to exit. When they lose water and become flaccid, they close the stoma, conserving water. This mechanism allows plants to balance photosynthesis needs (requires CO₂) with water conservation. Chloroplasts carry out photosynthesis. Mitochondria produce ATP. Vacuoles store water and other materials. Guard cells represent a homeostatic mechanism in plants.'
    },
    {
      number: 15, part: 'A',
      text: 'Which life process carried out by a green plant is represented in the diagram? Energy released, Carbon Dioxide + Water → Life Process → Oxygen + Food',
      choices: ['respiration', 'digestion', 'photosynthesis', 'replication'],
      topic: 'General', correct: 2,
      explanation: 'The diagram shows carbon dioxide and water being combined using energy (sunlight) to produce oxygen and food (glucose) — this is the equation for photosynthesis.',
      diveDeep: 'Photosynthesis: CO₂ + H₂O + light energy → glucose + O₂. This process occurs in chloroplasts using chlorophyll to capture light energy. It is an anabolic process (building up complex molecules from simpler ones). Respiration is the reverse — it breaks down glucose to release energy (CO₂ and H₂O are produced, not consumed). Digestion breaks down food molecules. Replication copies DNA. Recognizing the reactants and products of photosynthesis versus respiration is one of the most tested concepts on the LE Regents.', image: '/images/exams/le-june-2017/q15.png' },
    {
      number: 16, part: 'A',
      text: 'Scientists are developing a malaria vaccine that would most likely contain',
      choices: ['weakened drugs used to treat the symptoms of malaria', 'white blood cells from the malaria-infected individuals', 'a weakened form of the malaria-causing organism', 'antibodies made from the malaria-causing organism'],
      topic: 'Human Body', correct: 2,
      explanation: 'Vaccines work by exposing the immune system to a weakened, inactivated, or partial form of a pathogen so it can produce memory cells without causing the disease.',
      diveDeep: 'The principle of vaccination is to prime the immune system by introducing antigens in a form that does not cause disease. This can be done with weakened (attenuated) or killed pathogens, or with specific proteins (antigens) from the pathogen\'s surface. Memory B cells formed during this response enable a rapid antibody response upon future exposure. The malaria-causing organism is a protozoan (Plasmodium); a weakened form would contain its antigens and stimulate immunity. Antibodies are the immune response product, not the vaccine ingredient. Drugs treat symptoms but do not build immunity.'
    },
    {
      number: 17, part: 'A',
      text: 'Proteins, starch, and DNA are similar in that they are all',
      choices: ['organic compounds', 'parts of genes', 'made of amino acids', 'made of simple sugars'],
      topic: 'Cell Biology', correct: 0,
      explanation: 'Proteins, starch, and DNA are all organic compounds — large carbon-containing molecules found in living organisms.',
      diveDeep: 'Organic compounds are defined as molecules containing carbon-hydrogen bonds, typically produced by living organisms. The major classes of biological macromolecules are all organic: proteins (made of amino acids), carbohydrates including starch (made of simple sugars like glucose), lipids (fats and oils), and nucleic acids including DNA and RNA (made of nucleotides). None of these three molecules are "parts of genes" (that is only DNA). Amino acids are the building blocks of proteins only. Simple sugars build carbohydrates. Knowing the building blocks of each macromolecule type is a key LE biochemistry fact.'
    },
    {
      number: 18, part: 'A',
      text: 'In response to an increasing blood glucose level, the human body will normally',
      choices: ['store the glucose in cell nuclei', 'release a hormone that lowers the blood glucose', 'produce a hormone that destroys the glucose', 'use the excess glucose to make proteins'],
      topic: 'Cell Biology', correct: 1,
      explanation: 'The pancreas releases insulin in response to rising blood glucose; insulin signals cells to take up glucose and stimulates the liver to convert it to glycogen for storage, lowering blood sugar back to normal.',
      diveDeep: 'Blood glucose regulation is a classic example of negative feedback homeostasis. When blood glucose rises (e.g., after eating), beta cells in the pancreas secrete insulin. Insulin promotes glucose uptake by cells and glycogen synthesis in the liver, lowering blood glucose. When glucose falls too low, alpha cells secrete glucagon, which promotes glycogen breakdown and glucose release. Glucose is stored as glycogen in liver and muscle cells, not in the nucleus. Hormones regulate but do not "destroy" glucose. Blood glucose cannot be converted directly to proteins. Diabetes involves disruption of this feedback mechanism.'
    },
    {
      number: 19, part: 'A',
      text: 'A kitten was born with black fur and green eyes. The fur and eye color of its parents are shown in the chart: Father — striped fur, green eyes; Mother — black fur, yellow eyes. Which statement helps explain why the kitten has black fur?',
      choices: ['Chromosomes present on the genes code for the characteristics of its fur.', 'Genetic mutations always cause the fur color and eye color to change.', 'Offspring receive genetic information from both parents.', 'Gene expression is changed in every generation, resulting in evolution.'],
      topic: 'General', correct: 2,
      image: '/images/exams/le-june-2017/q19.png',
      explanation: 'The kitten inherited the gene for black fur from its mother; offspring receive one set of chromosomes from each parent, so traits can come from either parent.',
      diveDeep: 'Inheritance follows Mendelian principles: offspring receive one allele for each gene from each parent. The black fur allele from the mother was expressed in the kitten. The striped pattern from the father was not expressed, suggesting the black fur allele may be dominant. Chromosomes carry genes, not the other way around — genes are ON chromosomes. Mutations do not always occur; gene inheritance follows predictable patterns. Evolution occurs across populations over generations, not in individual kittens. The key concept here is that offspring traits can be traced to genes inherited from either parent.'
    },
    {
      number: 20, part: 'A',
      text: 'Scientists have been investigating a way to recreate extinct species. Which technique would use DNA from an extinct species to recreate an organism of the species?',
      choices: ['natural selection', 'cloning', 'differentiation', 'selective breeding'],
      topic: 'Cell Biology', correct: 1,
      explanation: 'Cloning uses the DNA from an organism (even an extinct one) to produce a genetically identical organism; scientists could insert the extinct species\' DNA into an enucleated egg cell.',
      diveDeep: 'Somatic cell nuclear transfer (SCNT) — the technique used to clone Dolly the sheep — involves removing the nucleus from an egg cell and replacing it with the nucleus from a somatic cell of the organism to be cloned. If ancient DNA (from preserved specimens like frozen mammoths) could be recovered and inserted, theoretically an extinct organism could be recreated. Natural selection is an evolutionary mechanism, not a reproductive technique. Differentiation is the developmental process by which cells specialize. Selective breeding requires living individuals to breed. Cloning is the only technique listed that could reproduce a genetically identical organism from preserved DNA.', image: '/images/exams/le-june-2017/q20.png' },
    {
      number: 21, part: 'A',
      text: 'The sequence that best illustrates the flow of energy through an ecosystem is',
      choices: ['sunlight → plant → wolf → rabbit', 'plant → sunlight → rabbit → wolf', 'sunlight → plant → rabbit → wolf', 'wolf → rabbit → plant → sunlight'],
      topic: 'Genetics', correct: 2,
      explanation: 'Energy flows from the sun to producers (plants), then to primary consumers (rabbits, herbivores), then to secondary consumers (wolves, carnivores); this matches sunlight → plant → rabbit → wolf.',
      diveDeep: 'In a food chain, energy flows in one direction: from the sun to producers via photosynthesis, then from producers to herbivores, and from herbivores to carnivores. At each step, approximately 90% of energy is lost as heat, which is why food chains typically have no more than 4–5 levels. Sunlight is always the first link — it is the primary energy source for nearly all ecosystems. Wolves do not eat plants directly; they are apex predators that eat prey animals like rabbits. Constructing and interpreting food chains is a fundamental LE ecology skill.'
    },
    {
      number: 22, part: 'A',
      text: 'Which cellular change in an organism could be inherited by the next generation?',
      choices: ['a change in the ribosomes in the pancreas of a squirrel', 'the deletion of a single DNA base in a sperm cell of a trout', 'a decrease in the size of a vacuole in a rose leaf cell', 'the transfer of a piece of a chromosome in the skin cell of a raccoon'],
      topic: 'Cell Biology', correct: 1,
      explanation: 'Only changes in reproductive (germ-line) cells — like a mutation in a sperm cell — can be passed to offspring; somatic cell changes die with the individual.',
      diveDeep: 'For a genetic change to be heritable, it must occur in a gamete (egg or sperm) or in a cell that will develop into a gamete (germ-line cell). A deletion in a sperm cell of a trout is exactly this type of change — it will be inherited by any offspring produced by that sperm. Changes in pancreatic cells, leaf cells, or skin cells affect only that individual organism and are lost when those cells die. This is a fundamental principle of heredity and explains why acquired characteristics (like muscles from exercise) cannot be genetically inherited by offspring.'
    },
    {
      number: 23, part: 'A',
      text: 'A chemical was added to hand sanitizers and dish detergents to kill bacteria. Certain species of bacteria are no longer killed by this chemical. One likely reason for the decreased effectiveness of this chemical is that these bacteria have',
      choices: ['slower metabolic rates', 'a mutation for resistance', 'been selectively bred for survival', 'an adaptation to a different niche'],
      topic: 'Evolution', correct: 1,
      explanation: 'Bacteria that survived exposure to the chemical had a random mutation conferring resistance; natural selection then favored these resistant bacteria, increasing their frequency in the population.',
      diveDeep: 'This is another real-world example of natural selection and the evolution of resistance. The chemical acted as a selective pressure: susceptible bacteria were killed while those with random resistance mutations survived and reproduced. Over time, the resistant strain became dominant. Bacteria are not selectively bred by humans — that process is artificial selection, not natural. Metabolic rate changes would not specifically confer resistance. Adapting to a different niche means moving to a new ecological role, not resisting a chemical. The emergence of triclosan-resistant bacteria is a genuine public health concern.'
    },
    {
      number: 24, part: 'A',
      text: 'The hemlock woolly adelgid is an invasive insect species that is destroying native hemlock trees in New York State. These insects can upset natural ecosystems because they',
      choices: ['provide food for native bird species', 'can carry diseases that can be spread to pets', 'increase biodiversity in New York State forests', 'disrupt habitats that native species depend upon'],
      topic: 'Evolution', correct: 3,
      explanation: 'By killing hemlock trees, the adelgid destroys the habitat and food sources that native species (birds, mammals, insects) depend on, reducing biodiversity and destabilizing the ecosystem.',
      diveDeep: 'Hemlock forests provide specific habitat for many species — nesting sites, food, shade, and stream temperature regulation. Destroying them disrupts these niches and food webs. Invasive species, by definition, harm the ecosystems they invade. While they may provide some food for generalist species, the net effect is nearly always negative for native biodiversity. An invasive species does not increase biodiversity; it typically reduces it by outcompeting or destroying native species. Disease transmission to pets is not the primary ecological concern here. Understanding invasive species impacts is a key LE ecology and human impact topic.'
    },
    { number: 25, part: 'A', text: 'DNA replication results in', choices: ['two new DNA molecules, each with two new strands', 'two DNA molecules, each with one original strand and one new strand', 'one DNA molecule with two original strands and one DNA molecule with two new strands', 'four new single-stranded DNA molecules'], topic: 'Cell Biology', correct: 1, explanation: 'DNA replication is semiconservative — each of the two resulting molecules contains one original (template) strand and one newly synthesized strand.', diveDeep: 'During the S phase of interphase, the double helix is unwound and each strand serves as a template for a new complementary strand. Because each daughter molecule retains one parental strand, the process is called semiconservative replication. This was demonstrated by Meselson and Stahl in 1958 using nitrogen isotope labeling. The result is two identical double-stranded DNA molecules — one for each daughter cell after cell division. Accurate replication ensures that genetic information is faithfully passed from parent cell to daughter cells.' },
    { number: 26, part: 'A', text: 'Biodiversity refers to', choices: ['the number of individuals in a single species', 'the variety of genes, species, and ecosystems in a region', 'the total biomass of all producers in an ecosystem', 'the rate of speciation in a given habitat'], topic: 'Ecology', correct: 1, explanation: 'Biodiversity encompasses three levels: genetic diversity (variation within a species), species diversity (the number of different species), and ecosystem diversity (variety of habitats and communities).', diveDeep: 'High biodiversity makes ecosystems more stable and resilient. Genetic diversity allows populations to adapt to changing conditions. Species diversity provides redundancy in ecosystem functions (multiple species can perform similar roles). Ecosystem diversity ensures a variety of habitats and ecological processes. Biodiversity loss — driven by habitat destruction, invasive species, pollution, overexploitation, and climate change — is one of the most serious environmental crises of our time. Protecting biodiversity is a central theme in LE and is crucial for ecosystem services that benefit humans.', image: '/images/exams/le-june-2017/q26.png' },
    { number: 27, part: 'A', text: 'Which statement best describes cloning?', choices: ['Cloning produces organisms with twice the genetic information of the parent.', 'Cloning combines genetic material from two parents to produce offspring.', 'Cloning produces genetically identical organisms from a single parent.', 'Cloning only occurs naturally in vertebrate animals.'], topic: 'Genetics', correct: 2, explanation: 'Cloning produces organisms that are genetically identical to the original organism; it is a form of asexual reproduction using DNA from a single parent.', diveDeep: 'Natural cloning occurs when identical twins form from the same fertilized egg, or when organisms like bacteria, plants, and simple animals reproduce asexually. Artificial cloning in agriculture involves cuttings, grafting, or somatic cell nuclear transfer (SCNT). In SCNT, the nucleus of a somatic cell replaces the nucleus of an enucleated egg, and the resulting embryo is implanted in a surrogate. Clones are genetically identical but may differ in appearance due to environmental factors (epigenetics). Concerns about artificial cloning include reduced genetic diversity in populations and potential health issues in cloned animals.', image: '/images/exams/le-june-2017/q27.png' },
    { number: 28, part: 'A', text: 'Which statement best describes the role of the nervous system in maintaining homeostasis?', choices: ['The nervous system produces hormones that travel through the blood to target organs.', 'The nervous system coordinates rapid responses by transmitting electrical signals to and from the brain.', 'The nervous system breaks down nutrients for energy to maintain body temperature.', 'The nervous system filters waste products from the blood to maintain chemical balance.'], topic: 'Human Body', correct: 1, explanation: 'The nervous system maintains homeostasis by detecting changes in internal and external environments and transmitting rapid electrical signals to coordinate appropriate responses.', diveDeep: 'The human nervous system has two main divisions: the central nervous system (CNS — brain and spinal cord) and the peripheral nervous system (PNS — nerves throughout the body). Sensory neurons carry signals to the CNS; motor neurons carry signals from the CNS to muscles and glands. The brain integrates information and directs responses. Producing hormones is the role of the endocrine system. Breaking down nutrients is the role of the digestive system. Filtering blood is the role of the kidneys. The nervous system and endocrine system often work together to maintain homeostasis, but the nervous system acts faster.' },
    { number: 29, part: 'A', text: 'The wings of a bird and the wings of an insect are considered analogous structures because they', choices: ['are composed of the same bones arranged differently', 'evolved from the same ancestral structure', 'perform the same function but have different underlying anatomy', 'indicate the two species share a recent common ancestor'], topic: 'Evolution', correct: 2, explanation: 'Analogous structures perform the same function (flight) but evolved independently in unrelated lineages and have completely different underlying anatomy — this is convergent evolution, not shared ancestry.', diveDeep: 'Analogous structures arise through convergent evolution — when different lineages independently evolve similar adaptations to similar environmental pressures. Bird wings have hollow bones, feathers, and a forelimb skeleton; insect wings are thin membranes supported by veins. They look and function similarly but are not built from the same developmental blueprint. This is in contrast to homologous structures (like the forelimbs of vertebrates), which share the same anatomical blueprint because they evolved from a common ancestor. Convergent evolution is evidence that natural selection produces similar solutions to similar problems in different lineages.' },
    { number: 30, part: 'A', text: 'Abiotic factors such as temperature and water availability influence where organisms can live because', choices: ['organisms compete directly with abiotic factors for resources', 'organisms are adapted to survive within specific ranges of abiotic conditions', 'abiotic factors only affect producers, not consumers', 'organisms can always migrate to avoid unfavorable abiotic conditions'], topic: 'Ecology', correct: 1, explanation: 'Through natural selection, organisms become adapted to survive within the specific range of abiotic conditions in their native habitat; outside that range, they cannot survive or reproduce.', diveDeep: 'Every species has a range of tolerance for abiotic factors — the zone of optimal performance and the limits beyond which the organism cannot survive. Temperature, sunlight, water, soil pH, salinity, and oxygen levels all constrain where species can live. These abiotic factors shape the distribution of biomes (tropical rainforest, desert, tundra) and aquatic zones. Adaptations — physiological, behavioral, and structural — allow organisms to live within these ranges. Competition occurs between organisms (biotic), not between organisms and abiotic factors. Migration is possible for some animals but not all organisms, and not always fast enough in the face of rapid change.' },
    { number: 31, part: 'B-1', text: 'The diagram shows a marine food web: phytoplankton → zooplankton → small fish → large fish → sharks. What is the role of phytoplankton in this ecosystem?', choices: ['They are decomposers that recycle nutrients from dead organisms.', 'They are consumers that feed on zooplankton.', 'They are producers that capture solar energy through photosynthesis.', 'They are apex predators that regulate the entire food web.'], topic: 'Ecology', correct: 2, image: '/images/exams/le-june-2017/q31.png', explanation: 'Phytoplankton are photosynthetic microorganisms that form the base of marine food webs; they capture solar energy and convert it to organic matter, making them producers.', diveDeep: 'Phytoplankton are microscopic algae and cyanobacteria that perform roughly half of all photosynthesis on Earth, producing about 50% of the planet\'s oxygen. As the base of the marine food web, they support virtually all ocean life. Zooplankton feed on phytoplankton and are in turn eaten by small fish, larger fish, and marine mammals. The arrow in a food web points from prey to predator (showing the direction of energy flow). Decomposers (bacteria and fungi) break down dead organic matter but are not phytoplankton. Understanding trophic structure and energy flow in marine ecosystems is a core LE topic.' },
    { number: 32, part: 'B-1', text: 'A graph shows enzyme reaction rate increasing with substrate concentration, then leveling off into a plateau. What does the plateau in the curve indicate?', choices: ['The enzyme has been permanently denatured by excess substrate.', 'All enzyme active sites are occupied and the reaction rate cannot increase further.', 'The substrate has run out and the reaction has stopped.', 'The pH is too high for the enzyme to function at high substrate concentrations.'], topic: 'Cell Biology', correct: 1, image: '/images/exams/le-june-2017/q32.png', explanation: 'The plateau indicates enzyme saturation — at high substrate concentrations, all enzyme active sites are continuously occupied, so adding more substrate cannot increase the reaction rate.', diveDeep: 'Enzymes are biological catalysts with specific active sites where substrates bind. At low substrate concentrations, reaction rate increases because more substrate molecules are available to occupy the active sites. As substrate concentration rises, active sites become increasingly occupied until all are engaged — the enzyme is saturated. The plateau (Vmax) represents the maximum reaction rate for a given enzyme concentration. To increase Vmax, more enzyme must be added. Enzymes are not destroyed by excess substrate. This hyperbolic (Michaelis-Menten) curve is a classic graph in enzyme kinetics and a frequent LE data analysis question.' },
    { number: 33, part: 'B-1', text: 'A karyotype shows three copies of chromosome 21 instead of the normal two. During which process does the nondisjunction occur that produces this condition?', choices: ['mitosis in somatic cells after fertilization', 'meiosis — failure of chromosome 21 homologs to separate', 'DNA replication during the S phase', 'translation of chromosome 21 genes'], topic: 'Genetics', correct: 1, image: '/images/exams/le-june-2017/q33.png', explanation: 'Trisomy 21 (Down syndrome) results from nondisjunction during meiosis — chromosome 21 homologs fail to separate, producing a gamete with two copies of chromosome 21 that then fuses with a normal gamete.', diveDeep: 'Nondisjunction is the failure of homologous chromosomes (in meiosis I) or sister chromatids (in meiosis II or mitosis) to separate properly during cell division. When it occurs in meiosis, the resulting gamete has an abnormal chromosome number. If a gamete with two chromosome 21s (n+1) is fertilized by a normal gamete, the resulting zygote has 47 chromosomes (trisomy 21). Down syndrome features include intellectual disability, characteristic facial features, and increased risk of heart defects. Nondisjunction risk increases with maternal age. Karyotype analysis — examining chromosome number and structure — is used to diagnose chromosomal disorders.' },
    { number: 34, part: 'B-1', text: 'A graph shows two population growth curves: a J-shaped exponential curve and an S-shaped logistic curve. What factor causes logistic growth to level off at the carrying capacity?', choices: ['A sudden increase in birth rate among the population', 'Environmental resistance — limited resources, predation, and competition', 'A genetic mutation that reduces reproductive rate', 'An increase in the rate of immigration into the population'], topic: 'Ecology', correct: 1, explanation: 'Logistic growth levels off because of environmental resistance — the combined limiting effects of food and space shortages, predation, disease, and competition that slow population growth as it approaches carrying capacity.', diveDeep: 'Exponential growth (J-curve) occurs when resources are unlimited. Logistic growth (S-curve) occurs in real ecosystems where resources are finite. As a population grows, intraspecific competition for food, water, shelter, and mates intensifies; predation and disease increase; and birth rate falls while death rate rises. The point where these factors balance is the carrying capacity (K). Environmental resistance is the collective term for all the density-dependent factors that limit population growth. Carrying capacity is not fixed — it can change if resource availability changes. This model is fundamental to understanding population ecology in LE.' },
    { number: 35, part: 'B-1', text: 'A diagram shows translation — a ribosome moving along mRNA, tRNA molecules bringing amino acids, and a polypeptide chain forming. What role do codons play in translation?', choices: ['Codons carry amino acids to the ribosome during protein synthesis.', 'Codons are the sites on the ribosome where peptide bonds form.', 'Each codon (three-base mRNA sequence) specifies a particular amino acid.', 'Codons unwind the DNA double helix to allow mRNA synthesis.'], topic: 'Cell Biology', correct: 2, image: '/images/exams/le-june-2017/q35.png', explanation: 'A codon is a three-nucleotide sequence on mRNA; each codon specifies a particular amino acid (or a start/stop signal), and the sequence of codons determines the sequence of amino acids in the protein.', diveDeep: 'The genetic code is a set of rules by which codons are translated into amino acids. There are 64 possible codons (4³ combinations of 4 bases in triplets) encoding 20 amino acids plus start and stop signals — the code is redundant (multiple codons can specify the same amino acid). tRNA molecules carry amino acids and have anticodons complementary to mRNA codons. The ribosome moves along mRNA, matching tRNA anticodons to mRNA codons and catalyzing peptide bond formation between amino acids. Carrying amino acids is the role of tRNA, not codons. Ribosomes form peptide bonds. DNA unwinding is part of transcription, not translation.' },
    { number: 36, part: 'B-1', text: 'A data table shows that after a first vaccination, a small antibody response is produced. After a second vaccination (booster), a much larger and faster antibody response occurs. What type of cells are responsible for this enhanced response after the second vaccination?', choices: ['Neutrophils that destroy pathogens by phagocytosis', 'Memory B cells formed during the first vaccination', 'Stem cells that rapidly differentiate into antibody-producing cells', 'T cells that directly attack infected cells'], topic: 'Human Body', correct: 1, explanation: 'Memory B cells are produced during the primary immune response (first vaccination) and persist long-term; upon re-exposure, they rapidly proliferate and produce large amounts of antibodies — the secondary immune response.', diveDeep: 'The first exposure to an antigen (primary immune response) takes 1–2 weeks to produce significant antibody levels and generates memory B cells and memory T cells. The second exposure (secondary immune response) triggers these memory cells to rapidly divide and produce large quantities of antibodies in 1–3 days — much faster and stronger than the primary response. This immunological memory is the basis of all vaccines. Neutrophils are innate immune cells (non-specific). Stem cells are undifferentiated precursors. Cytotoxic T cells kill infected cells directly but are not the primary source of antibodies. Memory B cells differentiate into plasma cells that secrete antibodies.', image: '/images/exams/le-june-2017/q36.png' },
    { number: 37, part: 'B-1', text: 'A diagram shows the forelimbs of a human (arm/hand), whale (flipper), bat (wing), and horse (leg) — all containing the same basic bones arranged differently. What does this structural similarity indicate?', choices: ['These organisms perform the same function with their forelimbs.', 'These organisms evolved in the same type of environment.', 'These organisms share a common ancestor from which the basic forelimb structure was inherited.', 'These organisms underwent convergent evolution independently.'], topic: 'Evolution', correct: 2, image: '/images/exams/le-june-2017/context_37_39.png', explanation: 'Homologous structures — the same bones present in different arrangements across species — indicate shared ancestry; the basic forelimb plan was inherited from a common ancestor and modified for different functions over time.', diveDeep: 'The vertebrate forelimb (humerus, radius, ulna, carpals, metacarpals, phalanges) is a classic example of homologous structures. Despite being used for grasping (humans), swimming (whales), flying (bats), and running (horses), they share the same underlying skeletal architecture. This is evidence of descent with modification from a common tetrapod ancestor. The functions are completely different — this rules out convergent evolution (which would produce analogous, not homologous, structures). Homology at the anatomical level is supported by molecular homology (similar DNA sequences) in these same groups. Comparative anatomy is one of several lines of evidence for evolution.' },
    { number: 38, part: 'B-1', text: 'A student placed three groups of plants under red light, blue light, and no light for 2 weeks to test the effect of light color on plant growth. What is the independent variable in this experiment?', choices: ['The height of the plants after 2 weeks', 'The type of plant used in each group', 'The wavelength (color) of light each group received', 'The amount of water given to each plant'], topic: 'Cell Biology', correct: 2, explanation: 'The independent variable is the factor deliberately changed by the experimenter — in this case, the color (wavelength) of light each group of plants received.', diveDeep: 'In a controlled experiment, the independent variable is what the scientist manipulates. The dependent variable is what is measured (plant growth/height). All other variables (type of plant, amount of water, temperature, soil) must be kept constant (controlled variables) to ensure a valid comparison. Here, the student deliberately changed only the light color, making it the independent variable. Plant height or mass after 2 weeks would be the dependent variable. Good experimental design requires one independent variable to identify cause-and-effect relationships. Understanding experimental design — identifying variables and controls — is tested in LE lab-based questions (Part B-1 and B-2).', image: '/images/exams/le-june-2017/context_37_39.png' },
    { number: 39, part: 'B-1', text: 'A graph shows that oxygen production by aquatic plants increases as light intensity increases. Why does oxygen production increase with light intensity?', choices: ['Greater light intensity raises water temperature, speeding up all chemical reactions in the plant.', 'Higher light intensity provides more energy for photosynthesis, allowing more glucose and oxygen to be produced.', 'Increased light intensity causes more water molecules to enter the plant through osmosis.', 'More light kills algae competing with the plants, allowing plants to grow faster.'], topic: 'Cell Biology', correct: 1, image: '/images/exams/le-june-2017/context_37_39.png', explanation: 'Light provides the energy for the light-dependent reactions of photosynthesis; greater light intensity means more photons are available to drive these reactions, producing more ATP, NADPH, and ultimately more glucose and oxygen.', diveDeep: 'In the light-dependent reactions, chlorophyll absorbs photons and uses that energy to split water molecules (photolysis), releasing O₂ as a byproduct and generating ATP and NADPH. More light = more photons absorbed = more water split = more O₂ released. Oxygen production rate is a proxy for photosynthesis rate. However, at very high light intensities, the rate plateaus — other factors (CO₂ concentration, enzyme availability) become limiting. Temperature does affect reaction rates, but this is not the primary reason for the O₂ increase shown. Measuring O₂ production is a standard LE lab technique to quantify photosynthesis.' },
    { number: 40, part: 'B-1', text: 'A diagram shows genetic drift in a small island population over 10 generations — a rare allele becomes dominant purely by chance. What condition makes a population most vulnerable to genetic drift?', choices: ['Large population size with high genetic diversity', 'Small population size where random changes in allele frequency have a large effect', 'High mutation rate introducing many new alleles', 'Strong directional selection favoring a particular phenotype'], topic: 'Evolution', correct: 1, image: '/images/exams/le-june-2017/context_40_41.png', explanation: 'Genetic drift — random changes in allele frequency — has the greatest impact in small populations, where chance events can dramatically alter which alleles are passed to the next generation.', diveDeep: 'In a large population, random events average out and allele frequencies stay relatively stable (Hardy-Weinberg equilibrium). In a small population, the random survival or death of even a few individuals can cause large shifts in allele frequencies purely by chance — not because of natural selection. Two special cases of genetic drift are the founder effect (a small group establishes a new population) and the bottleneck effect (a population is severely reduced in size). Genetic drift can fix harmful alleles, eliminate beneficial ones, and reduce genetic diversity regardless of fitness. It is especially important in conservation biology when managing small, endangered populations.' },
    { number: 41, part: 'B-1', text: 'A diagram shows the human liver and its functions. What is the primary function of bile produced by the liver?', choices: ['To chemically digest proteins into amino acids in the stomach', 'To emulsify fats — breaking large fat droplets into smaller ones for lipase digestion', 'To neutralize stomach acid before food enters the large intestine', 'To absorb glucose directly from the small intestine into the bloodstream'], topic: 'Human Body', correct: 1, image: '/images/exams/le-june-2017/context_40_41.png', explanation: 'Bile emulsifies fats — it acts like a detergent to break large fat globules into smaller droplets, increasing the surface area for lipase enzymes to digest them.', diveDeep: 'The liver produces bile, which is stored in the gallbladder and released into the small intestine when fatty food enters. Bile salts (amphiphilic molecules) surround fat droplets and break them into micelles — tiny droplets with much greater surface area. This emulsification dramatically increases the efficiency of fat digestion by pancreatic lipase, which can only work on the surface of fat droplets. Bile does not chemically digest fats — that is the job of lipase. Proteins are digested by proteases (pepsin in the stomach, trypsin in the small intestine). Stomach acid (HCl) is partly neutralized by sodium bicarbonate from the pancreas, not bile. The liver also performs detoxification, glycogen storage, and synthesis of plasma proteins.' },
    { number: 42, part: 'B-1', text: 'A scientist inserts the human insulin gene into bacterial DNA so that bacteria produce human insulin. What enzyme is used to cut DNA at specific sequences to create recombinant DNA?', choices: ['DNA polymerase', 'RNA polymerase', 'Restriction enzymes', 'Ligase'], topic: 'Genetics', correct: 2, explanation: 'Restriction enzymes (restriction endonucleases) are molecular scissors that cut DNA at specific recognition sequences, creating fragments with complementary sticky ends that can be joined to form recombinant DNA.', diveDeep: 'Recombinant DNA technology involves cutting DNA from two sources with the same restriction enzyme (producing compatible sticky ends), then joining the fragments with DNA ligase. The resulting recombinant DNA can be inserted into a vector (plasmid) and introduced into a host cell (bacteria, yeast) that then expresses the inserted gene. Human insulin produced by bacteria (using the gene encoding human insulin) was the first recombinant pharmaceutical, approved in 1982. DNA polymerase synthesizes new DNA strands during replication. RNA polymerase synthesizes RNA during transcription. Ligase joins DNA fragments but does not cut them. Knowing the tools of genetic engineering is a tested LE biotechnology topic.', image: '/images/exams/le-june-2017/q42.png' },
    { number: 43, part: 'B-1', text: 'A graph shows wolf and elk populations in Yellowstone National Park after wolf reintroduction in 1995 — elk populations declined while wolf populations increased. What type of ecological interaction does this graph illustrate?', choices: ['Mutualism — both species benefit from the interaction', 'Commensalism — wolves benefit while elk are unaffected', 'Predator-prey relationship — wolves hunt elk, controlling elk population size', 'Competition — wolves and elk compete for the same food resources'], topic: 'Ecology', correct: 2, image: '/images/exams/le-june-2017/q43.png', explanation: 'The inverse relationship between wolf and elk populations — wolves increase as they prey on elk, causing elk to decline — is the classic predator-prey dynamic.', diveDeep: 'When wolves were reintroduced to Yellowstone in 1995, elk populations declined not only from direct predation but also from a "landscape of fear" — elk avoided grazing in areas where they were vulnerable, allowing riparian vegetation to recover. This triggered a trophic cascade: more willows and aspens → more beavers → more ponds → more biodiversity. Predator-prey relationships are characterized by one organism (predator) consuming another (prey). Classic predator-prey cycles (Lotka-Volterra model) show oscillating populations. Mutualism benefits both species. Commensalism benefits one, is neutral to the other. Competition is between organisms seeking the same limited resource. The Yellowstone wolf reintroduction is a landmark conservation case study.' },
  ]
}
