// Living Environment Regents — August 2025
export default {
  id: 'li-aug-2025',
  subject: 'living-environment',
  year: 2025,
  session: 'August',
  totalMinutes: 180,
  questions: [
    {
      number: 1,
      part: 'A',
      text: 'Which mechanism is used to maintain a stable internal environment in humans?',
      choices: [
        'use of guard cells to control water loss and gas exchange',
        'destruction of the immune system by the AIDS virus',
        'increased perspiration during periods of intense activity',
        'an allergic reaction to pollen from cats',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Increased perspiration during intense activity is an example of homeostasis — the body increases sweating to release heat and maintain a stable internal temperature.',
      diveDeep: 'Homeostasis is the maintenance of a stable internal environment despite external changes. The human body uses feedback mechanisms to regulate temperature, blood sugar, water balance, and many other variables. Sweating is a negative feedback response to overheating: temperature rises → sweat glands activated → evaporation cools the body → temperature drops back to normal. Guard cells (choice A) are a plant structure. AIDS destroys the immune system (choice B) — this is an example of the body failing to maintain homeostasis, not maintaining it. Allergic reactions (choice D) are misdirected immune responses, not homeostatic mechanisms. Students should recognize homeostatic examples vs. disruptions.',
    },
    {
      number: 2,
      part: 'A',
      text: 'Industrial processes often release lead and copper compounds into waterways, which could then have adverse effects on human health. Previously, methods to remove these compounds were expensive and often produced toxins themselves. Researchers have now found that minced banana peels are able to quickly absorb lead and copper from river water. In addition, banana peels are non-toxic and inexpensive. The use of the banana peels in this case is probably a',
      choices: [
        'poor use of resources, because it introduces a new organism into the ecosystem',
        'trade-off, because the more toxic methods might still be used',
        'simple proposal, which will increase the costs of cleaning up the waterways',
        'good use of resources, which can help to restore a natural ecosystem',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'Using banana peels is a good use of resources because they are inexpensive, non-toxic, and effective at removing harmful pollutants, helping to restore a cleaner, healthier ecosystem.',
      diveDeep: 'This question tests environmental decision-making and the concept of trade-offs. A trade-off involves accepting some negative consequence in exchange for a benefit. Using banana peels eliminates the trade-off of toxic removal methods — it is inexpensive AND non-toxic AND effective. Introducing banana peels (already a natural product) is not introducing a new organism to the ecosystem; they are organic matter. Students should evaluate each choice against the information given: the passage states banana peels are inexpensive (not costly) and non-toxic (no negative trade-off), making "good use of resources" the clear best answer.',
    },
    {
      number: 3,
      part: 'A',
      text: 'Which abiotic factor would most directly limit the size of a gray squirrel population?',
      choices: [
        'variety of food sources',
        'number of predators',
        'availability of water in the forest',
        'amount of nitrogen in the atmosphere',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Water is an abiotic (non-living) factor, and its availability directly limits population size because all organisms require water for survival, metabolism, and reproduction.',
      diveDeep: 'Abiotic factors are non-living environmental components: water, temperature, light, soil minerals, pH, and atmospheric gases. Biotic factors are living components: predators, prey, competitors, parasites, and food sources. The question specifically asks for an ABIOTIC factor. Food variety and predator numbers are biotic factors. Nitrogen in the atmosphere (~78%) is essentially unlimited and not a direct limiting factor for animals. Water availability, temperature, and light are the most commonly tested abiotic limiting factors on the Living Environment Regents. Students must distinguish clearly between biotic and abiotic factors — this distinction appears on nearly every exam.',
    },
    {
      number: 4,
      part: 'A',
      text: 'Human chromosomes differ from the chromosomes of fruit flies in that human chromosomes',
      choices: [
        'are made from only four kinds of bases',
        'contain only 46 genes',
        'may be involved in both mitosis and meiosis',
        'have different sequences of bases',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'All organisms use DNA made of the same four bases (A, T, G, C), but the specific sequences of bases differ between species, giving each species its unique genetic information.',
      diveDeep: 'DNA is universal across all living organisms — the same four nucleotide bases (adenine, thymine, guanine, cytosine) are used, and the same genetic code translates codons to amino acids. The differences between species arise from the specific sequences of these bases. All chromosomes in dividing cells (in species that reproduce sexually) can be involved in mitosis (body cells) and meiosis (reproductive cells). Humans have 46 chromosomes with approximately 20,000–25,000 genes — not just 46 genes. Students should remember: DNA structure and bases are universal; DNA sequence is species/individual-specific.',
    },
    {
      number: 5,
      part: 'A',
      text: 'One major benefit of the use of water power is that it',
      choices: [
        'does not produce a significant amount of carbon dioxide as a waste product',
        'increases the production of oxygen in the atmosphere',
        'has no impact on the rivers that are used',
        'increases the recycling of nutrients',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'Hydroelectric power generates electricity without combustion, so it does not release significant amounts of carbon dioxide (a greenhouse gas), unlike fossil fuel power plants.',
      diveDeep: 'Hydroelectric power uses the kinetic energy of flowing water to turn turbines and generate electricity. Unlike fossil fuels, it does not produce CO₂ or other combustion byproducts during operation. However, it is NOT without environmental impact — dams can disrupt river ecosystems, block fish migration, flood upstream habitats, and alter downstream water flow and temperature. So choice C (no impact on rivers) is incorrect. Water power does not directly affect atmospheric oxygen production or nutrient cycling. Students should evaluate renewable energy sources for their actual benefits AND limitations when answering Regents questions.',
    },
    {
      number: 6,
      part: 'A',
      text: 'Adding chlorine to drinking water in many modern cities has been credited with reducing outbreaks of diseases, such as cholera. Some scientists claim that adding chlorine may result in by-products in the water that may very slightly increase the risk of cancer. The decision to add chlorine to drinking water most likely involved',
      choices: [
        'an assessment of trade-offs',
        'the elimination of genetic diseases',
        'the removal of all pathogens from water',
        'the disruption of dynamic equilibrium in ponds',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'Chlorinating water involves a trade-off: the major benefit (preventing deadly waterborne diseases) outweighs the minor risk (a very slight increase in cancer risk from by-products).',
      diveDeep: 'A trade-off is a decision that involves accepting a disadvantage to gain a larger benefit. Water chlorination is a classic public health trade-off: the benefit (virtually eliminating waterborne diseases like cholera, typhoid) is enormous; the cost (slight cancer risk from chlorination by-products) is very small. The decision is based on cost-benefit analysis comparing the risks and benefits. Students should recognize trade-off scenarios: whenever a beneficial technology or practice has some negative side effect, it involves a trade-off. Chlorination does NOT eliminate all pathogens (Cryptosporidium is resistant to chlorine), does not cause genetic diseases, and is not about dynamic equilibrium in ponds.',
    },
    {
      number: 7,
      part: 'A',
      text: 'The diagram below represents a process that can occur when chromosomes are copied in sexually reproducing organisms. One result of this process is',
      choices: [
        'an increase in the number of chromosomes in the cell to double its original number',
        'an increase in the number of new gene combinations that can be passed on to offspring',
        'an elimination of mutations in reproductive cells and zygotes',
        'the formation of new genes that will decrease variation in future generations',
      ],
      topic: 'Cell Biology',
      correct: 1,
      image: '/images/exams/le-august-2025/q7.png',
      explanation: 'The process shown is crossing over (recombination) during meiosis, which creates new combinations of alleles on chromosomes, increasing genetic variation in offspring.',
      diveDeep: 'Crossing over occurs during prophase I of meiosis, when homologous chromosomes pair up and exchange segments. This shuffles alleles between chromosomes, creating gametes with new combinations of genes that did not exist in either parent. This increases genetic variation in offspring, which is the raw material for natural selection and evolution. Crossing over does NOT: change the chromosome number (that is determined by meiosis itself), eliminate mutations, or form entirely new genes. Students should distinguish sources of genetic variation: crossing over (recombination), independent assortment of chromosomes during meiosis I, and random fertilization.',
    },
    {
      number: 8,
      part: 'A',
      text: 'Scientists initially studying the decline of certain penguin populations in Antarctic regions found that the penguins\' food source, a small animal known as krill, had dropped by 80%. These scientists are now studying the reduction in the number of tiny photosynthetic organisms that are the food source of the krill. The decline of the penguin population was a direct effect of the disruption of a',
      choices: [
        'parasitic relationship',
        'biosphere',
        'food chain',
        'mechanism of evolution',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'The decline in photosynthetic organisms → reduction in krill → decline in penguins describes a disruption in a food chain, where energy flows from producers to consumers.',
      diveDeep: 'A food chain shows the feeding relationships and energy flow between organisms: phytoplankton (producers) → krill (primary consumers) → penguins (secondary consumers). Disruption at any level cascades through the chain. This is also an example of a trophic cascade — when a change at one level affects multiple other levels. A food web is more complex (multiple food chains interconnected). Students should be able to identify feeding relationships: producer (makes own food via photosynthesis), primary consumer (eats producers), secondary consumer (eats primary consumers). The key word in the answer is "chain" — this is a linear energy transfer sequence, not a parasitic or evolutionary relationship.',
    },
    {
      number: 9,
      part: 'A',
      text: 'The diagram below represents a process that occurs during the development of human body cells. Nerve Muscle Skin Fertilized egg Which statement is correct regarding these cells?',
      choices: [
        'The fertilized egg and other types of cells all have the same DNA.',
        'The fertilized egg contains half the genetic information of the other types of cells.',
        'Each cell contains only the genetic information necessary for its particular function.',
        'The body cells undergo mitosis and the fertilized egg undergoes meiosis.',
      ],
      topic: 'Human Body',
      correct: 0,
      image: '/images/exams/le-august-2025/q9.png',
      explanation: 'Every cell in the human body (except gametes) contains the same complete set of DNA as the original fertilized egg — different cells express different genes, but they all have the same genetic information.',
      diveDeep: 'Cell differentiation produces specialized cells (nerve, muscle, skin) from the original fertilized egg through mitosis. During this process, every cell receives a complete copy of the organism\'s DNA — no DNA is lost or gained. Differentiated cells look and function differently because different genes are expressed (turned on or off), not because they have different genes. The fertilized egg (zygote) has the FULL diploid (2n) chromosome number — it does not have half the information of body cells. Body cells undergo mitosis (for growth/repair); only specialized cells (in gonads) undergo meiosis to produce gametes. Students must understand the distinction between differential gene expression and differential gene content.',
    },
    {
      number: 10,
      part: 'A',
      text: 'Which situation would most likely lead to increased diversity in a species?',
      choices: [
        'A population of birds with high variation migrates to a group of islands with different environmental conditions.',
        'Selective breeding is used to develop a species that is only able to live in very specific environmental conditions.',
        'An ecosystem containing few species experiences many centuries of stable climatic conditions.',
        'Asexual reproduction is used to produce more plants of a certain species.',
      ],
      topic: 'Evolution',
      correct: 0,
      explanation: 'A genetically diverse population migrating to multiple different environments (isolated islands) creates conditions for adaptive radiation — different populations adapt to different local conditions, increasing diversity.',
      diveDeep: 'Increased species/genetic diversity results from: genetic variation in the founding population + different selective pressures in isolated environments. This scenario describes adaptive radiation — one ancestral species diversifying into multiple distinct forms as isolated populations adapt to different niches (Darwin\'s finches are the classic example). Selective breeding REDUCES diversity by selecting for specific traits. Stable climatic conditions over long periods favor stasis, not diversification. Asexual reproduction produces genetically identical clones, reducing genetic variation. Students should connect: genetic variation + geographic isolation + different selection pressures = speciation and increased diversity.',
    },
    {
      number: 11,
      part: 'A',
      text: 'Some allergies are inherited. Allergic reactions are often much less severe in adults who were exposed to the allergen (the substance causing the reaction) during infancy. What does this show about some inherited traits?',
      choices: [
        'The effect of allergens can never be predicted.',
        'Developing allergies requires genes from both parents.',
        'Allergies are always caused by DNA.',
        'Gene expression can be influenced by environmental conditions.',
      ],
      topic: 'Genetics',
      correct: 3,
      explanation: 'Early allergen exposure during infancy modifies how the inherited allergy gene is expressed later in life, demonstrating that environmental conditions (timing of allergen exposure) can influence gene expression.',
      diveDeep: 'This is an example of gene-environment interaction — the genotype (inherited predisposition to allergy) interacts with the environment (early allergen exposure) to produce a modified phenotype (milder allergic reaction). This concept, sometimes called epigenetics or phenotypic plasticity, shows that having a gene does not determine the outcome with certainty — the environment can modify how genes are expressed. Students should know: genotype × environment = phenotype. This appears frequently on the Living Environment Regents because it challenges the simple idea that genes directly and deterministically control traits. Examples: height (genes + nutrition), skin color (genes + sun exposure), and allergies (genes + environmental exposure).',
    },
    {
      number: 12,
      part: 'A',
      text: 'A tall building is built on an empty lot. The new building blocks the sunlight on nearby streets for most of the day. Trees and plants grow more slowly or die off because the building has interfered with a',
      choices: [
        'removal of water from the atmosphere',
        'production of finite resources',
        'recycling of solar energy',
        'process that produces organic compounds',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'Sunlight is required for photosynthesis, the process by which plants use light energy to produce organic compounds (glucose) from CO₂ and water; blocking sunlight disrupts this fundamental process.',
      diveDeep: 'Photosynthesis: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. This process produces organic compounds (glucose/carbohydrates) from inorganic raw materials, using solar energy. Without sunlight, photosynthesis cannot occur, and plants starve. Solar energy is not "recycled" — it enters the ecosystem through photosynthesis and exits as heat; energy flows through ecosystems, it does not cycle (unlike matter). Water is removed from the atmosphere through precipitation and used in photosynthesis, but blocking sunlight primarily prevents the process that produces organic compounds. Students should know photosynthesis as the entry point of energy into virtually all ecosystems.',
    },
    {
      number: 13,
      part: 'A',
      text: 'The Madagascar rose periwinkle, a species of rainforest flower that was used to treat cancer, is now endangered in its native habitat due to deforestation. Continuing the destruction of rainforests is likely to have a negative impact on future medical discoveries because it could cause a decrease in the',
      choices: [
        'growing season for rainforest species',
        'biodiversity of the rainforest ecosystem',
        'land available to cultivate new plants',
        'amount of carbon dioxide in the atmosphere',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Deforestation reduces biodiversity by destroying habitats and causing extinctions; since many medicines come from unique plant species, loss of biodiversity threatens future medical discoveries.',
      diveDeep: 'Biodiversity provides an enormous "genetic library" of potentially useful compounds. Approximately 25% of modern pharmaceuticals come from plant-derived compounds discovered from studying rainforest species. When species go extinct due to deforestation, those unique chemical compounds — which might have cured diseases — are lost forever. This is a strong economic and medical argument for biodiversity conservation. Students should connect biodiversity loss to practical human consequences beyond just ecological impacts. The Madagascar periwinkle produces vincristine and vinblastine, used to treat childhood leukemia and Hodgkin\'s disease. CO₂ increases (not decreases) with deforestation.',
    },
    {
      number: 14,
      part: 'A',
      text: 'The letters in the diagram below indicate some parts of a cell. B C D A Which structure provides the energy needed for protein synthesis?',
      choices: [
        'A',
        'C',
        'B',
        'D',
      ],
      topic: 'Cell Biology',
      correct: 0,
      image: '/images/exams/le-august-2025/q14.png',
      explanation: 'Structure A is the mitochondrion, which produces ATP (cellular energy) through cellular respiration; this energy is required for the synthesis of proteins at ribosomes.',
      diveDeep: 'Cellular energy (ATP) is produced primarily by mitochondria through aerobic cellular respiration: glucose + oxygen → CO₂ + water + ATP. Protein synthesis (translation) occurs at ribosomes and requires ATP energy to form peptide bonds and move the ribosome along mRNA. Without mitochondrial energy production, protein synthesis cannot proceed. The other major cell structures: nucleus (contains DNA, site of transcription); ribosomes (site of translation/protein synthesis — they build proteins but need energy FROM mitochondria); vacuoles (storage). Students should know the key organelles, their functions, and how they interact. On diagrams, identify mitochondria by their double-membrane folded structure (cristae).',
    },
    {
      number: 15,
      part: 'A',
      text: 'One reason why some organisms, such as insects, evolve much faster than others is because they',
      choices: [
        'undergo physical changes during development',
        'have very short reproductive cycles',
        'are sometimes exposed to predators that cause mutations',
        'produce offspring only by asexual reproduction',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Organisms with short reproductive cycles (like insects) go through many more generations per year, so evolution (change in allele frequencies through natural selection) occurs faster because there are more opportunities for selection to act.',
      diveDeep: 'Evolution occurs through changes in allele frequencies across generations. The more generations per unit time, the faster evolution can proceed. Insects may complete dozens of generations per year; mammals might complete one or less. This is why antibiotic resistance evolves rapidly in bacteria (millions of generations per year) and why insects quickly develop resistance to pesticides. Physical changes during development (metamorphosis) are not inherited and do not drive evolution. Predators create selection pressure but do NOT cause mutations — they select among existing mutations. Asexual reproduction actually reduces genetic variation and can slow evolution.',
    },
    {
      number: 16,
      part: 'A',
      text: 'The diagram below represents a metabolic process involving amino acids represented by AA. AA AA AA AA AA AA AA AA Where in a cell would this process most likely take place?',
      choices: [
        'ribosome',
        'chloroplast',
        'mitochondrion',
        'vacuole',
      ],
      topic: 'Cell Biology',
      correct: 0,
      image: '/images/exams/le-august-2025/q16.png',
      explanation: 'Ribosomes are the cellular organelles where amino acids are assembled (linked by peptide bonds) into polypeptide chains (proteins) during the process of translation.',
      diveDeep: 'The central dogma of molecular biology: DNA (nucleus) → mRNA (transcription) → protein (translation at ribosomes). Ribosomes are the molecular machines that read mRNA sequences and assemble amino acids in the correct order to form proteins. This process (translation) uses energy from ATP (produced by mitochondria). Chloroplasts perform photosynthesis (in plant cells). Mitochondria perform cellular respiration. Vacuoles store materials (water, waste, food). Protein synthesis (joining amino acids) = ribosome. Students should know: where is each process carried out? Photosynthesis → chloroplast; respiration → mitochondria; protein synthesis → ribosome; DNA replication/transcription → nucleus.',
    },
    {
      number: 17,
      part: 'A',
      text: 'Fossil fuels are considered nonrenewable because',
      choices: [
        'oil and coal are being used at an increasing rate',
        'people are becoming more interested in buying energy-efficient vehicles',
        'oil and coal are no longer being formed at a significant rate',
        'Earth\'s supply of nuclear fuels is finite',
      ],
      topic: 'Evolution',
      correct: 2,
      explanation: 'Fossil fuels are considered nonrenewable because they formed over millions of years from ancient organic matter and are not being replenished at any significant rate relative to the rate of human consumption.',
      diveDeep: 'Nonrenewable resources are depleted faster than they can be regenerated. Fossil fuels (coal, oil, natural gas) took millions of years to form from compressed organic matter. While technically fossil fuels are still forming today, the formation rate is essentially zero on human timescales — we are consuming millions of years\' worth of stored energy in just centuries. The rate of use increasing (choice A) makes depletion faster, but the fundamental reason for nonrenewability is the formation rate disparity. Nuclear fuel (choice D) is separate from fossil fuels. Students should clearly understand the definition of nonrenewable: consumed faster than formed, regardless of how much is left.',
    },
    {
      number: 18,
      part: 'A',
      text: 'The male emperor penguin cares for his unhatched egg for a long period of time by resting it upon his feet and against his body. This behavior in the male penguins most likely developed over time because the behavior',
      choices: [
        'attracted female penguins for mating',
        'increased the rate of natural selection',
        'increased reproductive success',
        'led to increased predation',
      ],
      topic: 'Reproduction',
      correct: 2,
      explanation: 'Behaviors that increase reproductive success — ensuring offspring survive to reproduce — are naturally selected for over time; male brooding behavior protects eggs from Antarctica\'s extreme cold, dramatically increasing chick survival.',
      diveDeep: 'Natural selection favors any trait (physical or behavioral) that increases an individual\'s reproductive success (survival and reproduction of viable offspring). In Antarctica\'s extreme cold, penguin eggs would quickly freeze without the parent\'s body heat. The brooding behavior allows the egg to survive and hatch, directly increasing the number of offspring that survive. Over many generations, individuals with stronger brooding instincts had more surviving offspring, spreading this behavior through the population. This is an example of behavioral evolution through natural selection. Students should connect behavior to reproductive success and understand that evolution acts on any heritable trait that affects survival or reproduction.',
    },
    {
      number: 19,
      part: 'A',
      text: 'Many advertisements warn pregnant women of the dangers of exposure to certain risk factors because these factors may',
      choices: [
        'cause mutations in the ovary of the mother and thus change the genetic makeup of the developing fetus',
        'cause mutations in the blood cells of the mother and thus change the genetic makeup of the fetus',
        'cause changes in the stomach cells of the mother, which would result in a clone of her fetus',
        'cause organs in the fetus to develop abnormally',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'Environmental risk factors (alcohol, drugs, certain medications, radiation) can directly affect fetal cells during critical periods of organ development, causing developmental abnormalities.',
      diveDeep: 'Environmental teratogens (substances that cause birth defects) act directly on the developing fetus by crossing the placenta and disrupting fetal cell development. They do NOT change the mother\'s genetic information or the fetus\'s DNA sequence — they disrupt developmental processes. Examples: thalidomide caused limb defects; alcohol causes fetal alcohol syndrome; rubella virus causes heart defects. Mutations in the mother\'s somatic cells (blood cells, stomach cells) are not inherited by the fetus — only mutations in egg cells would be heritable. Students must understand: somatic mutations are NOT passed to offspring; only germ cell mutations are heritable. Environmental factors during pregnancy affect development, not inheritance.',
    },
    {
      number: 20,
      part: 'A',
      text: 'When a colony of bacteria was exposed to a particular antibiotic, some of the bacteria survived while others did not. Which concept is supported by this example?',
      choices: [
        'Biotic factors in the environment influence gene expression.',
        'Favorable mutations occur as a result of environmental changes.',
        'Overproduction limits genetic variation.',
        'Some variations in a population have an adaptive value.',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'Some bacteria in the population already had genetic variations (resistance mutations) that gave them an adaptive advantage — they survived the antibiotic while others died, demonstrating that some variations have adaptive value.',
      diveDeep: 'Antibiotic resistance evolution is the clearest real-world demonstration of natural selection: (1) variation exists in the population (some bacteria randomly had resistance mutations before exposure); (2) antibiotic = selection pressure; (3) bacteria with resistance survive and reproduce (selection for the favorable variation); (4) resistance spreads through the population. The key misconception addressed in choice B: mutations do NOT occur in response to the environment — they are random and pre-existing. The antibiotic selects among pre-existing variations; it does not create new mutations. Students must clearly understand: natural selection acts on existing variation, it does not direct mutation.',
    },
    {
      number: 21,
      part: 'A',
      text: 'When uncooked meat is tenderized using pineapple juice, specific organic molecules in the meat are broken down. This reaction occurs because the pineapple juice most likely contains',
      choices: [
        'antibodies that preserve the meat',
        'hormones that influence cell division',
        'enzymes that alter the structure of proteins',
        'sugars that metabolize starches',
      ],
      topic: 'General',
      correct: 2,
      image: '/images/exams/le-august-2025/q21.png',
      explanation: 'Pineapple juice contains bromelain, a protease enzyme that breaks down the protein molecules in meat, making it tender by disrupting the protein structures that give meat its toughness.',
      diveDeep: 'Enzymes are biological catalysts — proteins that speed up specific chemical reactions without being consumed. Bromelain (from pineapple) and papain (from papaya) are proteases — enzymes that break down proteins by hydrolyzing peptide bonds. This specific enzyme-substrate interaction explains meat tenderizing: the tough connective tissue proteins (collagen, myosin) are broken down by the enzyme. Enzymes work because their active site has a specific shape that fits the substrate (lock-and-key model). Antibodies recognize foreign proteins; they do not digest them in this way. Hormones signal cells; they do not digest proteins. Students should identify enzyme-catalyzed reactions by looking for specific breakdown of biological molecules.',
    },
    {
      number: 22,
      part: 'A',
      text: 'One factor that might threaten global stability and alter the equilibrium in an ecosystem is increasing',
      choices: [
        'the rate of reforestation',
        'biodiversity',
        'recycling',
        'the rate of climate change',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'Increasing the rate of climate change disrupts established ecosystems by shifting temperature and precipitation patterns faster than species can adapt, threatening the stability of ecosystems worldwide.',
      diveDeep: 'Ecosystems maintain a dynamic equilibrium through checks and balances among species. Rapid climate change can exceed the ability of species to adapt or migrate, leading to population crashes, extinctions, and food web disruptions. Reforestation, biodiversity, and recycling all generally enhance ecosystem stability and resilience. Climate change causes: habitat loss (coral bleaching, glacier melt, permafrost thaw), range shifts, phenological mismatches (e.g., insects hatching before plant flowers), and increased extreme weather events. Students should identify factors that increase vs. decrease ecosystem stability. Generally: more biodiversity = more stability; more pollution/climate change/habitat destruction = less stability.',
    },
    {
      number: 23,
      part: 'A',
      text: 'Which group of organisms would be at the greatest risk of extinction if they were infected by a deadly virus?',
      choices: [
        'a small population of a bird species found only on Martha\'s Vineyard island',
        'a population of squirrels living in Los Angeles, California',
        'all pigeons living in parks in Florida',
        'all the rabbits living in Kinderhook, New York',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'A small population of a bird species found only on one isolated island (Martha\'s Vineyard) is at the greatest risk because small population size, limited geographic range, and genetic uniformity all contribute to extinction vulnerability.',
      diveDeep: 'Extinction risk factors include: (1) small population size — less genetic diversity, fewer individuals to survive stochastic events; (2) restricted geographic range — a single disaster (virus, hurricane) can eliminate the entire population; (3) low genetic diversity — limited variation means fewer individuals may have resistance to a new pathogen. The Martha\'s Vineyard bird scores high on all three risk factors. Squirrels in LA are widely distributed; Florida pigeons are a widespread species; Kinderhook rabbits are a local population of a widespread species. Island species (like Hawaiian honeycreepers or Galapagos tortoises) are among the most extinction-prone. Students should know the factors that increase extinction risk.',
    },
    {
      number: 24,
      part: 'A',
      text: 'When a person gets a tattoo and the needle used is contaminated with a pathogen, how does the human immune system respond?',
      choices: [
        'It produces hormones.',
        'It digests white blood cells.',
        'It produces more white blood cells.',
        'It digests antibiotics.',
      ],
      topic: 'Human Body',
      correct: 2,
      explanation: 'When a pathogen enters the body, the immune system responds by producing more white blood cells (leukocytes), which attack and destroy the invading pathogen through phagocytosis and antibody production.',
      diveDeep: 'The immune response involves multiple components: white blood cells (leukocytes) including B-cells (produce antibodies), T-cells (kill infected cells), and phagocytes (engulf and destroy pathogens). When a pathogen enters through a contaminated tattoo needle, the immune system detects foreign antigens and mounts a response: increased production of white blood cells, activation of phagocytes, and antibody production. Hormones (like epinephrine) are produced by endocrine glands for different purposes (stress response). Antibiotics are medications — the body does not produce or digest them. Students should know the key immune system players: antibodies (fight specific antigens), white blood cells (general and specific defense), and the inflammatory response.',
    },
    { number: 25, part: 'A', text: 'A mutation occurs in a skin cell of an organism. Which statement best describes how this mutation will affect future generations?', choices: ['It will be passed directly to all offspring of the organism.', 'It will not be passed to offspring because it occurred in a somatic cell.', 'It will change the DNA of the gametes produced by the organism.', 'It will increase the survival of all offspring.'], topic: 'Genetics', correct: 1, explanation: 'Mutations in somatic (body) cells such as skin cells are not heritable — they affect only that individual and are not passed to offspring. Only mutations in gametes (egg or sperm) can be inherited.', diveDeep: 'Somatic mutations occur in non-reproductive body cells and affect only the individual organism — they may cause cancer if they disrupt cell cycle control, but they cannot be passed to offspring. Germline mutations occur in cells that give rise to gametes (eggs and sperm) and CAN be inherited by offspring. This distinction is fundamental in genetics: inheritance requires transmission through gametes. Mutations themselves may be beneficial (improved function), harmful (nonfunctional protein), or neutral (no change in protein or phenotype). Students should always ask: in which cell type did the mutation occur? Body cell = not heritable; gamete cell = heritable.' },
    { number: 26, part: 'A', text: 'During intense exercise, muscle cells sometimes switch to fermentation when oxygen becomes limited. What is one product of fermentation in human muscle cells?', choices: ['carbon dioxide and water', 'oxygen and glucose', 'lactic acid', 'ethanol and carbon dioxide'], topic: 'Cell Biology', correct: 2, explanation: 'In human muscle cells, fermentation (anaerobic respiration) produces lactic acid as a byproduct when oxygen is insufficient, allowing the cell to continue producing ATP without oxygen.', diveDeep: 'Fermentation is an anaerobic process that regenerates NAD⁺ from NADH, allowing glycolysis to continue producing small amounts of ATP when oxygen is unavailable. In muscle cells: glucose → pyruvate (glycolysis, 2 ATP) → lactic acid (fermentation). In yeast: glucose → pyruvate → ethanol + CO₂ (alcoholic fermentation). Lactic acid buildup causes the "burn" sensation in muscles during intense exercise. Aerobic respiration (with oxygen) is far more efficient: up to 36–38 ATP per glucose molecule versus 2 ATP from glycolysis alone. Students should know both types of fermentation and where each occurs, as well as the energy yield difference between aerobic and anaerobic respiration.' },
    { number: 27, part: 'A', text: 'A person receives a flu vaccine. Several weeks later, the person is exposed to the influenza virus but does not get sick. Which statement best explains why the vaccine provided protection?', choices: ['The vaccine destroyed all viruses in the body permanently.', 'The vaccine caused the body to produce antibodies specific to the flu antigen.', 'The vaccine replaced white blood cells with stronger immune cells.', 'The vaccine introduced a fully active virus that killed other pathogens.'], topic: 'Human Body', correct: 1, explanation: 'Vaccines contain weakened or killed pathogens (or their antigens) that stimulate the immune system to produce specific antibodies and memory cells without causing disease, providing protection against future exposure.', diveDeep: 'Vaccination works through immunological memory: the first exposure to an antigen (via vaccine) triggers a primary immune response — B-cells produce antibodies and memory B-cells are formed. On second exposure to the real pathogen, memory B-cells rapidly produce large amounts of the specific antibody, neutralizing the pathogen before it can cause disease (secondary immune response). Antibodies are proteins with a specific shape that binds only to a particular antigen (lock-and-key specificity). Vaccines do not permanently destroy all viruses, replace immune cells, or use fully active dangerous viruses. Students should understand both the mechanism and the purpose of vaccination, and be able to explain the concept of immunological memory.' },
    { number: 28, part: 'A', text: 'In a grassland ecosystem, grass is eaten by grasshoppers, grasshoppers are eaten by frogs, and frogs are eaten by hawks. If 10,000 kilocalories of energy are available at the grass level, approximately how many kilocalories are available to the hawks?', choices: ['10 kcal', '100 kcal', '1,000 kcal', '5,000 kcal'], topic: 'Ecology', correct: 0, explanation: 'Using the 10% energy transfer rule: grass (10,000 kcal) → grasshoppers (1,000 kcal) → frogs (100 kcal) → hawks (10 kcal). Only about 10% of energy is transferred between each trophic level.', diveDeep: 'The 10% rule (ecological efficiency) states that only approximately 10% of the energy at one trophic level is available to the next. The other 90% is lost as heat (from cellular respiration), used for the organism\'s own metabolism, or not digested. Energy flow: producers → primary consumers → secondary consumers → tertiary consumers. Matter (atoms/molecules) cycles through ecosystems; energy flows in one direction and is continuously lost as heat. This is why food chains are rarely longer than 4–5 levels — too little energy remains at higher levels. Students should be able to calculate energy at any trophic level using the 10% rule and understand why energy decreases but matter cycles.' },
    { number: 29, part: 'A', text: 'In a population of beetles, some individuals are green and some are brown. Birds can easily see and eat green beetles resting on brown tree bark. After many generations, the beetle population is mostly brown. Which process best explains this change?', choices: ['genetic engineering', 'natural selection', 'selective breeding', 'asexual reproduction'], topic: 'Evolution', correct: 1, explanation: 'Natural selection explains the change: brown beetles have a survival advantage on brown bark (camouflage), so they survive and reproduce more, passing the brown trait to offspring; over generations brown becomes more frequent.', diveDeep: 'The four conditions for natural selection: (1) variation exists in the population (green and brown beetles); (2) variation is heritable (color is genetically controlled); (3) more offspring are produced than can survive (competition); (4) some variants survive and reproduce better (brown beetles survive bird predation better). Result: favorable alleles (brown) increase in frequency over generations — this is evolution. Genetic engineering involves deliberate manipulation of DNA in a lab. Selective breeding is human-controlled reproduction. Asexual reproduction produces identical clones and reduces variation. Natural selection is the core mechanism of evolution — students must be able to identify it and describe each step.' },
    { number: 30, part: 'A', text: 'A fertilized egg cell divides and eventually develops into a complete organism with many different cell types — nerve cells, muscle cells, and skin cells. All these cells contain the same DNA, yet they perform different functions. Which process is responsible for this difference in function?', choices: ['mutation of genes in each cell type', 'loss of chromosomes during cell division', 'differential gene expression during development', 'replication of different genes in each cell'], topic: 'Cell Biology', correct: 2, explanation: 'All body cells contain the same complete DNA, but cell differentiation occurs because different genes are expressed (switched on or off) in different cell types in response to chemical signals during development.', diveDeep: 'Cell differentiation is controlled by differential gene expression — the same genome contains the instructions for all cell types, but only the relevant subset of genes is expressed in each cell type. For example, muscle cells express genes for actin and myosin (contractile proteins) but not insulin; pancreatic beta cells express the insulin gene but not contractile protein genes. Regulatory proteins (transcription factors) control which genes are activated or silenced in response to the cell\'s position, neighboring cells, and chemical gradients during development. Students should clearly understand: same DNA in all cells → different gene expression → different proteins → different cell structures and functions. This is differential gene expression, NOT mutation or chromosome loss.' },
    { number: 31, part: 'B-1', text: 'The diagram shows a cell undergoing meiosis, producing cells with half the original chromosome number. What is the primary purpose of meiosis in sexually reproducing organisms?', choices: ['to repair damaged DNA in body cells', 'to produce gametes with half the chromosome number', 'to increase the chromosome number for growth', 'to create identical copies of somatic cells'], topic: 'Cell Biology', correct: 1, image: '/images/exams/le-august-2025/context_31_31.png', explanation: 'Meiosis produces haploid gametes (egg and sperm) with half the chromosome number of the parent cell. When two gametes fuse during fertilization, the normal diploid chromosome number is restored in the offspring.', diveDeep: 'Meiosis is a specialized cell division that reduces the chromosome number by half (diploid 2n → haploid n) and introduces genetic variation through crossing over and independent assortment. The two divisions of meiosis: Meiosis I separates homologous chromosome pairs (reducing 2n to n); Meiosis II separates sister chromatids (like mitosis). Result: 4 haploid cells from one diploid parent cell. In humans: meiosis in testes produces sperm (23 chromosomes each); meiosis in ovaries produces eggs (23 chromosomes each); fertilization restores 46 chromosomes. Without meiosis, chromosome number would double every generation. Students should contrast meiosis (gamete production, 4 haploid cells, genetic variation) with mitosis (growth/repair, 2 diploid cells, identical copies).' },
    { number: 32, part: 'B-1', text: 'A graph shows enzyme activity at different pH levels. The enzyme functions best at pH 7 and activity drops sharply at pH 2. What best explains why enzyme activity decreases at pH 2?', choices: ['There is not enough substrate available at low pH.', 'The enzyme molecule gains more energy at low pH.', 'The acidic conditions alter the shape of the enzyme\'s active site.', 'Low pH increases the temperature of the reaction.'], topic: 'Cell Biology', correct: 2, explanation: 'Extreme pH (like pH 2) disrupts the hydrogen bonds and ionic interactions that maintain the enzyme\'s three-dimensional shape, denaturing the active site so it can no longer bind substrate.', diveDeep: 'Enzymes are proteins whose function depends entirely on their three-dimensional shape, especially the active site (the region that binds the substrate). pH extremes disrupt the weak chemical bonds (hydrogen bonds, ionic interactions) that hold the protein in its functional shape — this process is called denaturation. A denatured enzyme has an altered active site that can no longer fit the substrate, stopping the reaction. Each enzyme has an optimal pH: pepsin (stomach enzyme) works best at pH 2; salivary amylase at pH 7; trypsin (small intestine) at pH 8. The graph shows this as a bell curve with a peak at the optimal pH. Students should explain pH effects on enzymes in terms of shape change (denaturation), not in terms of substrate availability or temperature.' },
    { number: 33, part: 'B-1', text: 'A pond food web shows: algae → small fish → large fish → heron. If large fish are removed from this ecosystem by overfishing, what is the most likely immediate effect on the small fish population?', choices: ['Small fish population will decrease because they have no food.', 'Small fish population will increase because predation pressure is removed.', 'Small fish population will remain the same because of homeostasis.', 'Small fish population will decrease because herons will eat more small fish.'], topic: 'Ecology', correct: 1, image: '/images/exams/le-august-2025/q33.png', explanation: 'With large fish (a predator) removed, small fish face less predation and their population will increase. This is a trophic cascade effect — removing one level affects the levels above and below it.', diveDeep: 'Trophic cascades occur when changes at one trophic level ripple through the food web. Removing large fish (predators of small fish) releases small fish from predation pressure — small fish population increases (predator release). More small fish then consume more algae, potentially causing algae population to decrease. This indirect effect on algae through two trophic levels is the cascade. Real-world example: removal of wolves from Yellowstone caused deer populations to increase, which then overgrazed vegetation. Students should trace the indirect effects through a food web: removing a predator → prey increases → prey\'s prey decreases. Remember: removing a species never leaves everything unchanged.' },
    { number: 34, part: 'B-1', text: 'A Punnett square shows a cross between two heterozygous parents (Bb × Bb) for a trait where B (brown fur) is dominant over b (white fur). What fraction of the offspring will show the recessive (white fur) phenotype?', choices: ['1/4', '1/2', '3/4', '0'], topic: 'Genetics', correct: 0, explanation: 'The Bb × Bb cross produces offspring in a 1 BB : 2 Bb : 1 bb ratio. Only the bb genotype expresses the recessive phenotype (white fur), which is 1 out of 4 offspring = 1/4.', diveDeep: 'Punnett square for Bb × Bb: gametes from each parent are B and b. The 4 possible offspring combinations: BB, Bb, Bb, bb. Phenotype ratio: 3 brown (BB or Bb, having at least one dominant B allele) : 1 white (bb, no dominant allele). Genotype ratio: 1 BB : 2 Bb : 1 bb. The recessive phenotype is expressed ONLY in the homozygous recessive (bb) genotype — 1/4 of offspring. Key concept: a dominant allele masks the recessive allele in heterozygotes (Bb looks like BB). Students must be able to: set up a Punnett square, determine possible gametes, fill in offspring genotypes, and calculate phenotype and genotype ratios. This is one of the most tested Regents genetics skills.' },
    { number: 35, part: 'B-1', text: 'The diagram shows the nitrogen cycle in an ecosystem. Which process converts atmospheric nitrogen (N₂) into a form that plants can absorb and use?', choices: ['decomposition by fungi', 'photosynthesis by plants', 'nitrogen fixation by bacteria', 'denitrification by soil bacteria'], topic: 'Ecology', correct: 2, explanation: 'Nitrogen fixation is performed by specialized bacteria (such as Rhizobium in legume root nodules) that convert atmospheric N₂ gas into ammonia (NH₃) or nitrates (NO₃⁻), forms that plants can absorb through their roots.', diveDeep: 'The nitrogen cycle: (1) Nitrogen fixation — bacteria convert N₂ → NH₃ (ammonia); (2) Nitrification — bacteria convert NH₃ → NO₂⁻ → NO₃⁻ (nitrates, usable by plants); (3) Assimilation — plants absorb nitrates to make proteins and nucleic acids; (4) Decomposition — decomposers break down organic nitrogen back to ammonia; (5) Denitrification — bacteria convert nitrates back to N₂ gas. Plants CANNOT directly use atmospheric N₂ — they need it converted to ammonia or nitrates first. Nitrogen-fixing bacteria include free-living (Azotobacter) and symbiotic forms (Rhizobium in legume nodules). Students should trace nitrogen through each stage and identify the organisms responsible.' },
    { number: 36, part: 'B-1', text: 'Two species of finches on the same island have very different beak shapes — one has a thick, crushing beak for eating seeds, and the other has a long, thin beak for probing flowers for insects. DNA analysis shows they share a common ancestor. This pattern of evolution is an example of', choices: ['convergent evolution, where unrelated species develop similar traits', 'adaptive radiation, where one ancestral species diversifies into multiple forms', 'artificial selection, where humans bred finches for specific traits', 'genetic drift, where random events changed allele frequencies'], topic: 'Evolution', correct: 1, explanation: 'Adaptive radiation (divergent evolution) occurs when one ancestral species diversifies into multiple species adapted to different ecological niches — the different beak shapes evolved to exploit different food sources from a common ancestor.', diveDeep: 'Adaptive radiation is the rapid diversification of one ancestral lineage into many forms, each adapted to a different ecological niche. Darwin\'s finches of the Galápagos are the classic example: one ancestral finch species colonized the islands and diversified into ~14 species with beaks adapted to different foods (seeds, insects, cactus, etc.). Evidence for common ancestry: DNA similarity, similar skeletal structure, similar developmental patterns. Convergent evolution is the opposite — unrelated species independently evolve similar traits (e.g., dolphin fins and fish fins). Artificial selection involves human choice, not natural selection. Genetic drift involves random changes, not adaptive ones. Students should distinguish adaptive radiation (one → many, from common ancestor) from convergent evolution (many → similar form, independent).' },
    { number: 37, part: 'B-1', text: 'Agricultural runoff containing high levels of phosphates and nitrates enters a lake. This causes a rapid growth of algae (algal bloom). When the algae die and decompose, what happens to the oxygen levels in the lake?', choices: ['Oxygen levels increase because algae release oxygen during decomposition.', 'Oxygen levels remain unchanged because decomposition is a slow process.', 'Oxygen levels decrease because decomposers consume oxygen to break down the dead algae.', 'Oxygen levels increase because nutrients from decomposition replace oxygen.'], topic: 'Ecology', correct: 2, explanation: 'When decomposers (bacteria) break down dead algae, they consume large amounts of dissolved oxygen through aerobic respiration, causing oxygen levels in the water to plummet — a process called eutrophication-driven hypoxia.', diveDeep: 'Eutrophication is the process by which excess nutrients (phosphates, nitrates from fertilizers, sewage) enrich a water body, leading to: (1) excessive algae growth (algal bloom); (2) algae block sunlight, killing underwater plants; (3) algae die and sink; (4) decomposing bacteria multiply and consume dissolved O₂ through aerobic respiration; (5) oxygen depletion (hypoxia) kills fish and other aquatic animals — creating a "dead zone." This is a major environmental problem in many lakes, rivers, and coastal zones (e.g., Gulf of Mexico dead zone from Mississippi River runoff). Students should trace the eutrophication sequence and identify the role of decomposers in oxygen depletion.' },
    { number: 38, part: 'B-1', text: 'A graph shows a population of deer in a forest growing rapidly over 20 years, then crashing dramatically during a severe multi-year drought, then slowly recovering. What type of limiting factor caused the population crash?', choices: ['biotic, density-dependent factor such as increased predation', 'abiotic, density-independent factor such as drought', 'biotic, density-dependent factor such as disease', 'abiotic, density-dependent factor such as competition for water'], topic: 'Ecology', correct: 1, image: '/images/exams/le-august-2025/q38.png', explanation: 'A drought is an abiotic (non-living) environmental factor that affects populations regardless of their density — it is a density-independent limiting factor that can cause sudden population crashes.', diveDeep: 'Limiting factors regulate population size. Density-independent factors affect populations regardless of size: weather events, drought, fire, floods, temperature extremes. They can cause sudden, dramatic population crashes. Density-dependent factors have greater effect when population density is high: predation (more prey = more predators), disease (denser population = faster spread), food competition, and space competition. The graph showing: rapid growth (good conditions) → crash (drought = density-independent) → recovery illustrates how abiotic factors can override density-dependent controls. Density-independent factors are often responsible for population crashes even in large populations. Students should be able to identify whether a factor is biotic/abiotic and density-dependent/independent from descriptions or graphs.' },
    { number: 39, part: 'B-1', text: 'A diagram of the human digestive system shows the path of food from the mouth through various organs. In which organ does the majority of chemical digestion and nutrient absorption take place?', choices: ['stomach', 'large intestine', 'small intestine', 'esophagus'], topic: 'Human Body', correct: 2, explanation: 'The small intestine is the primary site of both chemical digestion (using enzymes from the pancreas and intestinal walls) and nutrient absorption (through finger-like villi that greatly increase surface area).', diveDeep: 'The digestive system processes food through mechanical and chemical digestion. Key organs and their roles: Mouth — mechanical chewing + salivary amylase (starts starch digestion); Esophagus — transport only (peristalsis); Stomach — mechanical churning + pepsin (begins protein digestion) + HCl (pH ~2); Small intestine — MOST digestion and absorption: pancreatic enzymes (protease, lipase, amylase) + bile (from liver, emulsifies fats) + intestinal enzymes; nutrients absorbed through villi (finger-like projections) into blood; Large intestine — water absorption, formation of feces. The small intestine\'s enormous surface area (villi + microvilli = ~200 m² in humans) maximizes absorption efficiency. Students must know the function of each digestive organ.' },
    { number: 40, part: 'B-1', text: 'A scientist injects 20 mice with a disease-causing bacterium. Before the injection, 10 mice received a vaccine against the bacteria; these 10 mice survive. The other 10 mice received no vaccine and all die from the infection. What do the unvaccinated mice represent in this experiment?', choices: ['the experimental group being tested for vaccine effectiveness', 'the control group used for comparison with the vaccinated group', 'the independent variable of the experiment', 'a second experimental group testing a different vaccine'], topic: 'Human Body', correct: 1, explanation: 'The unvaccinated mice serve as the control group — they receive the same bacterial injection but without the vaccine, providing a baseline to compare against the experimental (vaccinated) group.', diveDeep: 'Scientific experimental design requires a control group to isolate the effect of the independent variable. In this experiment: Independent variable = vaccine (present or absent); Dependent variable = survival/death; Experimental group = vaccinated mice; Control group = unvaccinated mice (same treatment except for the vaccine). Without the control group, scientists could not determine whether the vaccine caused the survival — perhaps the mice would have survived anyway. The control group establishes the baseline outcome (what happens WITHOUT the treatment). Students should be able to identify: independent variable (what is changed), dependent variable (what is measured), control group (no treatment), and experimental group (receives treatment). This is a foundational lab skills question on every Living Environment Regents exam.' },
    { number: 41, part: 'B-1', text: 'The diagram shows glucose molecules moving across a cell membrane from an area of high concentration (outside) to an area of low concentration (inside) through protein channels, without the cell using any energy. What transport process is this?', choices: ['active transport', 'facilitated diffusion', 'endocytosis', 'osmosis'], topic: 'Cell Biology', correct: 1, image: '/images/exams/le-august-2025/q41.png', explanation: 'Facilitated diffusion is passive transport in which molecules move down their concentration gradient (high to low) through specific protein channels embedded in the membrane, without requiring any cellular energy (ATP).', diveDeep: 'Cell membrane transport types: (1) Simple diffusion — small nonpolar molecules (O₂, CO₂) pass directly through the lipid bilayer, high → low concentration, no energy, no protein needed; (2) Facilitated diffusion — larger or polar molecules (glucose, ions) move high → low concentration through specific protein channels, no energy required; (3) Osmosis — water moves high water concentration (low solute) to low water concentration (high solute) through aquaporin channels, no energy; (4) Active transport — molecules move LOW → HIGH concentration (against gradient) through protein pumps, requires ATP energy (e.g., sodium-potassium pump). The key distinction: does movement go WITH the gradient (passive, no ATP) or AGAINST it (active, needs ATP)? Students must identify all four transport types from descriptions or diagrams.' },
    { number: 42, part: 'B-1', text: 'A scientist sequences the DNA of an unknown organism and compares it to four known species. The results show: Species A — 3% different, Species B — 12% different, Species C — 28% different, Species D — 45% different. Which conclusion is best supported by this data?', choices: ['The unknown organism and Species D share the most recent common ancestor.', 'The unknown organism and Species A are most closely related evolutionarily.', 'Species C and Species D are more closely related to each other than to the unknown organism.', 'DNA sequence comparison is not valid evidence for evolutionary relationships.'], topic: 'Evolution', correct: 1, explanation: 'Species A has only 3% DNA difference from the unknown organism — the smallest difference — indicating the most recent common ancestor and the closest evolutionary relationship.', diveDeep: 'Molecular evidence for evolution: DNA and protein (amino acid) sequences can be compared across species to determine evolutionary relationships. The more similar the sequences, the more recently two species shared a common ancestor (less time for mutations to accumulate). This molecular clock approach complements anatomical, embryological, and fossil evidence. Less DNA difference = more closely related = more recent common ancestor. The data here shows: unknown and Species A (3% different) → most closely related; unknown and Species D (45% different) → most distantly related. DNA sequence comparison is now the most powerful and objective tool for determining evolutionary relationships, supporting and refining the classification of life. Students should interpret molecular data tables to draw evolutionary conclusions.' },
    { number: 43, part: 'B-1', text: 'A graph shows the number of bird species on islands of different sizes. Islands with larger land areas consistently support more bird species than smaller islands. Which ecological concept does this relationship best illustrate?', choices: ['Larger islands have more predators that drive speciation.', 'Greater habitat area supports greater biodiversity.', 'Smaller islands have more resources per species.', 'Island size determines the rate of mutation in bird populations.'], topic: 'Ecology', correct: 1, image: '/images/exams/le-august-2025/context_42_43.png', explanation: 'The species-area relationship demonstrates that larger areas contain more diverse habitats and can support larger populations of more species — a fundamental principle of island biogeography and conservation biology.', diveDeep: 'The species-area relationship (a key principle of island biogeography) states that the number of species increases with island/habitat area, following an approximate power law: S = cA^z, where S = species, A = area, c and z are constants. Reasons: larger islands have more diverse habitats (more ecological niches), support larger individual populations (reducing extinction risk), and are colonized by more species. This has direct applications to conservation: habitat fragmentation (cutting large forests into small patches) reduces biodiversity similarly to making islands smaller. Protected area size is therefore critical. Larger areas do not necessarily have more predators as the primary cause; resources per species typically decrease with more species competing. Students should recognize the species-area relationship and its conservation implications.' },
  ],
}
