// Living Environment Regents — August 2017
export default {
  id: 'li-aug-2017',
  subject: 'living-environment',
  year: 2017,
  session: 'August',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'A fruit fly is classified as a consumer rather than as a producer because it is unable to',
      choices: [
        'reproduce asexually',
        'synthesize its own food',
        'release energy stored in organic molecules',
        'remove wastes from its body',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Consumers (heterotrophs) cannot synthesize organic molecules from inorganic sources — they must obtain energy by eating other organisms. Producers (autotrophs) can make their own food via photosynthesis or chemosynthesis.',
      diveDeep: 'The producer/consumer distinction rests on autotrophy vs. heterotrophy. Autotrophs use light or chemical energy to fix inorganic carbon (CO₂) into organic molecules. Heterotrophs must ingest pre-formed organic molecules. Fruit flies, like all animals, lack the chloroplasts and enzymatic pathways needed for photosynthesis. This is a foundational ecology concept: energy enters ecosystems primarily through producers and flows to consumers at each trophic level.',
    },
    {
      number: 2, part: 'A',
      text: 'Which change is an example of maintaining dynamic equilibrium?',
      choices: [
        'A plant wilts when more water is lost from the leaves than is absorbed by the roots.',
        'A plant turns yellow when light levels are very low.',
        'Insulin is released when glucose levels in the blood are high.',
        'A person sweats when the environmental temperature is low.',
      ],
      topic: 'Human Body',
      correct: 2,
      explanation: 'Insulin release in response to high blood glucose is a classic negative-feedback mechanism that restores blood sugar to its set point, demonstrating dynamic equilibrium. The other choices describe disruptions or abnormal responses, not corrective ones.',
      diveDeep: 'Dynamic equilibrium means the body constantly monitors internal conditions and responds to keep them within a normal range — not a static state, but an active, ongoing process. Insulin lowers blood glucose by promoting cellular uptake and glycogen storage; when glucose drops to normal, insulin secretion decreases. This negative-feedback loop is the hallmark of homeostasis. Contrast with positive feedback (e.g., childbirth contractions), which amplifies a change rather than reversing it.',
    },
    {
      number: 3, part: 'A',
      text: 'Organisms contain compounds such as proteins, starches, and fats. The chemical bonds in these compounds can be a source of',
      choices: [
        'amino acids',
        'energy',
        'simple sugars',
        'enzymes',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Chemical bonds in organic molecules store potential energy; when broken during cellular respiration, that energy is released and captured as ATP. The other choices are components of specific macromolecules, not what is universally released from bond breakage.',
      diveDeep: 'All macromolecules — carbohydrates, lipids, and proteins — can be oxidized to release energy. Cellular respiration breaks these molecules down systematically (glycolysis → Krebs cycle → electron transport chain), harvesting the energy in chemical bonds as ATP. The total energy available depends on the type of bond and the degree of oxidation of carbon atoms. Fats yield more ATP per gram than carbohydrates because their carbon atoms are more reduced (more C–H bonds).',
    },
    {
      number: 4, part: 'A',
      text: 'Phosphorus is necessary for the growth of healthy plants. Scientists are developing plants that can grow in phosphorus-poor soil. Some of these new varieties, produced in a lab, make extra copies of a protein that helps them obtain more phosphorus from the soil. The process being used to develop these new varieties is most likely',
      choices: [
        'paper chromatography',
        'natural selection',
        'direct harvesting',
        'genetic engineering',
      ],
      topic: 'Genetics',
      correct: 3,
      explanation: 'Creating organisms that produce extra copies of a specific protein by deliberate manipulation in a laboratory is genetic engineering. Natural selection occurs without human intervention, and paper chromatography is a separation technique, not a breeding method.',
      diveDeep: 'Genetic engineering involves directly altering an organism\'s genome — inserting, deleting, or amplifying genes. In this case, scientists likely upregulated a gene for a phosphate-transporter protein or introduced additional copies of it. Modern techniques such as CRISPR/Cas9 and transgenic methods allow precise control over gene expression. This differs from selective breeding, which relies on naturally occurring variation, by allowing scientists to introduce or amplify traits that may not exist in the original population.',
    },
    {
      number: 5, part: 'A',
      text: 'Which life function is not necessary for an individual organism to stay alive?',
      choices: [
        'nutrition',
        'regulation',
        'reproduction',
        'excretion',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Reproduction is essential for the survival of the species but not for the survival of an individual organism. An individual can live its entire life without reproducing. Nutrition, regulation, and excretion are all required to keep an individual alive.',
      diveDeep: 'The life functions required by individual organisms include nutrition (obtaining energy), transport, respiration, excretion (removing metabolic wastes), regulation (maintaining homeostasis), and growth. Reproduction ensures the survival of the species across generations but is not needed for an individual\'s moment-to-moment survival. This distinction is important in understanding evolutionary biology: natural selection acts on reproductive success, yet an organism that cannot reproduce can still function metabolically.',
    },
    {
      number: 6, part: 'A',
      text: 'Lobsters prey on sea hares, which are marine animals. The lobsters find their prey through a sense of smell. The sea hares defend themselves by squirting ink at the lobster. The ink sticks to the lobster, interfering with its sense of smell. The most likely reason the sea hare can escape is because the sea hare ink',
      choices: [
        'pushes the sea hare away rapidly as the ink is expelled',
        'blocks a receptor on certain cells in the lobster',
        'causes the lobster to change its prey',
        'prevents movement of the lobster',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'The ink interferes with the lobster\'s sense of smell by physically blocking olfactory receptor cells, preventing the chemical signal from being received. This disrupts the predator\'s ability to locate prey rather than harming it or repelling it mechanically.',
      diveDeep: 'Chemoreception — detection of chemical signals — relies on molecules binding to specific receptor proteins on sensory cells. When ink coats the lobster\'s olfactory receptors, the binding sites are blocked, so the chemicals released by the sea hare can no longer trigger a nerve impulse. This is an example of a behavioral and chemical defense adaptation shaped by natural selection. The sea hare\'s ink is an example of a defensive secretion analogous to how some cephalopods use ink to confuse predators.',
    },
    {
      number: 7, part: 'A',
      text: 'Which statement is an accurate description of genes?',
      choices: [
        'Proteins are made of genes and code for DNA.',
        'Genes are made of proteins that code for nitrogen bases.',
        'DNA is made of carbohydrates that code for genes.',
        'Genes are made of DNA and code for proteins.',
      ],
      topic: 'Genetics',
      correct: 3,
      explanation: 'Genes are specific sequences of DNA nucleotides that encode instructions for building proteins. The central dogma of molecular biology is: DNA → RNA → Protein.',
      diveDeep: 'A gene is a segment of DNA whose base sequence specifies the amino acid sequence of a protein through the processes of transcription (DNA → mRNA) and translation (mRNA → protein). Proteins perform virtually all cellular functions — catalyzing reactions, providing structure, regulating gene expression, and more. Understanding this DNA → protein relationship is fundamental: mutations in DNA alter the protein produced, which can change the phenotype of the organism.',
    },
    {
      number: 8, part: 'A',
      text: 'The bobolink is a small blackbird that nests in fields of tall grass. It breeds in the summer across much of southern Canada and the northern United States. It migrates long distances, wintering in southern South America. The numbers of these birds are declining due to disruption of the areas where they live. In order to save these birds from extinction, the best course of action would be to',
      choices: [
        'prevent the birds from migrating to South America',
        'encourage farmers to let their hay fields undergo succession',
        'work to protect bobolink habitats in South and North America',
        'capture all the bobolinks and keep them safe in zoos',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Since the species relies on habitats in both North and South America during its life cycle, protecting habitats at both ends of the migration route is the most comprehensive and sustainable solution. Preventing migration or relying on captivity does not address the root cause of habitat loss.',
      diveDeep: 'Migratory species require suitable habitats at multiple points along their route, making them especially vulnerable to habitat disruption. Conservation strategies must be range-wide: protecting only breeding or only wintering grounds leaves the species vulnerable during the other phase. The Migratory Bird Treaty Act and international agreements recognize this principle. Succession in hay fields would provide tall-grass nesting habitat, but comprehensive habitat protection across both Americas is more effective than any single-location effort.',
    },
    {
      number: 9, part: 'A',
      text: 'A child with cystic fibrosis has an altered protein in his cells that stops chloride ions from leaving the cells. This protein most likely affects the functioning of',
      choices: [
        'cell membranes',
        'mitochondria',
        'nuclei',
        'ribosomes',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'The transport of ions like chloride in and out of cells is controlled by channel proteins embedded in the cell membrane. An altered channel protein that fails to move chloride ions is a membrane function problem.',
      diveDeep: 'Cystic fibrosis is caused by mutations in the CFTR gene, which encodes a chloride ion channel in the cell membrane. When this channel is non-functional, chloride ions accumulate inside cells, drawing in water and causing thick, sticky mucus to build up in the lungs and other organs. This is a classic example of how a single gene mutation can alter a membrane protein and disrupt homeostasis throughout the body. The cell membrane\'s role in selective permeability is therefore central to understanding this disease.',
    },
    {
      number: 10, image: '/images/exams/le-august-2017/q10.png', part: 'A',
      text: 'Which row in the chart below shows a direct relationship that can exist between two living organisms?',
      choices: [
        'producer – carnivore',
        'predator – prey',
        'parasite – prey',
        'carnivore – host',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'A predator–prey relationship is a direct ecological interaction between two organisms in which one kills and consumes the other. "Parasite–prey" and "carnivore–host" are not standard ecological pairings, and a producer is not directly consumed by a carnivore in most food chains.',
      diveDeep: 'Ecological interactions between organisms are classified by how each partner is affected: (+/−) for predation and parasitism, (+/+) for mutualism, (−/−) for competition, and (+/0) for commensalism. Predator–prey interactions are (+/−): the predator benefits while the prey is harmed. These interactions drive co-evolution — prey evolve defenses, predators evolve counter-adaptations. They also regulate population sizes and maintain ecosystem structure through trophic dynamics.',
    },
    {
      number: 11, part: 'A',
      text: 'Scientists have studied the return of plant life on Mount St. Helens ever since the volcano erupted in 1980. Wildflowers began colonizing the area, followed by shrubs and small trees. Scientists predict that it will likely take hundreds of years before the area returns to a forest dominated by fir and hemlock trees. These changes are an example of',
      choices: [
        'humans degrading an ecosystem by removing wildflowers',
        'the loss of genetic variation in a plant species',
        'the growth of a forest through ecological succession',
        'the biological evolution of wildflowers, shrubs, and trees',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'The sequential replacement of one plant community by another over time after a disturbance is ecological succession. Starting from bare rock or disrupted land and progressing toward a climax community is a defining feature of succession.',
      diveDeep: 'Primary succession begins on bare, lifeless substrate (e.g., volcanic rock) where there is no soil. Pioneer species such as mosses and lichens break down rock and build up organic matter, allowing wildflowers and then shrubs to colonize. Each community modifies the environment in ways that favor the next stage. Secondary succession occurs where soil already exists after a disturbance. The climax community (fir-hemlock forest at Mount St. Helens) represents a relatively stable endpoint, though it can still change over geological timescales.',
    },
    {
      number: 12, part: 'A',
      text: 'The most likely result of completely removing carbon dioxide from the environment of a plant is that sugar production will',
      choices: [
        'continue at the same rate',
        'increase and oxygen production will also increase',
        'increase and oxygen production will stay the same',
        'decrease and eventually stop',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'Carbon dioxide is a required raw material (reactant) for photosynthesis. Without CO₂, the Calvin cycle cannot proceed and glucose synthesis will halt entirely.',
      diveDeep: 'Photosynthesis has two stages: the light-dependent reactions (which split water and produce ATP, NADPH, and O₂) and the Calvin cycle (which uses CO₂, ATP, and NADPH to synthesize glucose). CO₂ is the carbon source fixed into organic molecules. Without it, the Calvin cycle stops, and ATP and NADPH accumulate unused; the light reactions may continue briefly but will also slow as products back up. This highlights CO₂ as a limiting factor for photosynthesis and explains why elevated CO₂ can increase plant growth under optimal conditions.',
    },
    {
      number: 13, part: 'A',
      text: 'Before a new shopping center can be built on previously undeveloped land, the builders must submit a proposal to the local government for approval. Which statement identifies an environmental concern associated with the development of the shopping center?',
      choices: [
        'Building the center would decrease resources needed by local organisms.',
        'The new shopping center would increase competition with already existing businesses.',
        'Building the center would decrease the amount of pollution in the area.',
        'The new shopping center would increase the biodiversity of the area.',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'Construction on undeveloped land destroys natural habitat, removing food sources, shelter, and other resources that local organisms depend on. This is a direct negative environmental impact. The other choices are either economically focused or factually incorrect.',
      diveDeep: 'Urban and suburban development reduces available habitat, a leading cause of biodiversity loss worldwide. When natural land is converted to impervious surfaces (pavement, rooftops), several environmental consequences follow: runoff increases (causing flooding and water pollution), soil is compacted (reducing infiltration and plant growth), and native plant communities are replaced by non-native landscaping. Environmental impact assessments are required to evaluate these trade-offs before development is approved, illustrating the interaction between human technology, society, and the natural environment.',
    },
    {
      number: 14, part: 'A',
      text: 'Homeowners have been encouraged to learn how to identify invasive plants and to remove them if they find them. The most likely reason for removing invasive plants is to',
      choices: [
        'allow only one type of native plant to grow',
        'preserve biodiversity',
        'eliminate unfamiliar food sources',
        'increase the rate of ecological succession',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Invasive plants typically outcompete native species, reducing the variety of plant species in an area and consequently harming the animals that depend on native plants. Removing invasives restores natural biodiversity.',
      diveDeep: 'Invasive species are non-native organisms that spread aggressively and cause ecological or economic harm. They often lack natural predators in the new environment, giving them a competitive advantage. By monopolizing light, water, and nutrients, invasive plants can eliminate entire native plant communities, collapsing food webs that evolved around those native species. Efforts to remove invasives (mechanical, chemical, or biological control) aim to restore the native community structure and the biodiversity that comes with it.',
    },
    {
      number: 15, image: '/images/exams/le-august-2017/q15.png', part: 'A',
      text: 'Which row in the chart below correctly pairs a human activity with its impact on the environment?',
      choices: [
        'decrease in the use of pesticides — erosion of rock in the soil',
        'increase in housing developments — improvement in air quality',
        'increase in human population — reduction in water usage',
        'decrease in recycling — reduction in amount of available resources',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'Less recycling means more raw materials must be extracted from the environment, depleting natural resources faster and increasing landfill waste. The other pairings describe effects that are inconsistent with or opposite to the expected environmental impact.',
      diveDeep: 'Recycling extends the life of materials, reducing the need for virgin resource extraction (mining, logging, drilling) and the energy costs of processing raw materials. When recycling decreases, landfill space is consumed faster, pollutants may leach into groundwater, and the pace of resource depletion accelerates. Human population growth amplifies these effects: more people generate more waste and consume more resources. Understanding the cumulative impact of individual behaviors on resource availability is a key component of environmental literacy.',
    },
    {
      number: 16, part: 'A',
      text: 'A procedure used in the field of biotechnology uses enzymes to cut bacterial DNA and insert a gene for human insulin into a bacterial cell. This bacterial cell can now be used to produce',
      choices: [
        'the bacterial gene for insulin that can be inserted into humans',
        'human genes for enzymes that can be inserted into humans',
        'insulin that can be used by humans',
        'enzymes necessary to treat human diseases',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'When the human insulin gene is inserted into a bacterial cell, the bacteria use their own cellular machinery to read that gene and produce human insulin protein, which can then be harvested for medical use.',
      diveDeep: 'This procedure describes recombinant DNA technology. Restriction enzymes cut the DNA at specific sequences, creating "sticky ends" that allow the human insulin gene to be ligated into a bacterial plasmid (vector). The recombinant plasmid is then introduced into bacteria, which replicate and express the human gene. This is how the insulin used to treat diabetes has been manufactured since the early 1980s, replacing insulin extracted from pigs and cattle. The genetic code is universal, so a human gene can be read by bacterial ribosomes to produce the same protein.',
    },
    {
      number: 17, image: '/images/exams/le-august-2017/q17.png', part: 'A',
      text: 'A graph represents the number of brown and green beetles collected in a particular ecosystem over time. The number of green beetles declines while brown beetles increase. The change observed in the numbers of green and brown beetles in the population is most likely due to',
      choices: [
        'natural selection',
        'gene manipulation',
        'selective breeding',
        'a common ancestor',
      ],
      topic: 'Evolution',
      correct: 0,
      explanation: 'A directional shift in the frequency of color variants over time in response to environmental conditions (such as predation pressure) is the definition of natural selection acting on heritable variation.',
      diveDeep: 'Natural selection requires three conditions: heritable variation exists in the population (brown and green coat colors), some variants have higher reproductive success in the given environment (brown beetles are better camouflaged), and those variants pass their advantageous traits to offspring. Over generations, the advantageous variant (brown) increases in frequency. This is industrial melanism on a smaller scale — the same process that drove the famous Peppered Moth changes in England during the Industrial Revolution.',
    },
    {
      number: 18, part: 'A',
      text: 'A reproductive system is represented in the diagram. Which structure is correctly paired with its reproductive function?',
      choices: [
        'A – pathway of gametes',
        'B – synthesis of progesterone',
        'C – production of sperm',
        'D – regulation of homeostasis',
      ],
      topic: 'Reproduction',
      correct: 0,
      image: '/images/exams/le-august-2017/q18.png',
      explanation: 'Structure A (the Fallopian tube) serves as the pathway through which the egg (gamete) travels from the ovary to the uterus. The other pairings incorrectly assign functions to the labeled structures.',
      diveDeep: 'In the human female reproductive system, the ovary produces eggs and sex hormones (estrogen and progesterone), the Fallopian tubes (oviducts) serve as the gamete pathway and site of fertilization, the uterus houses the developing embryo, and the cervix is the lower opening of the uterus. Understanding the function of each structure helps explain how disruptions (blockages, hormonal imbalances) can affect reproduction. Progesterone is synthesized by the corpus luteum in the ovary after ovulation, not by the Fallopian tube.',
    },
    {
      number: 19, part: 'A',
      text: 'For centuries, humans have used resources from coastal areas and open ocean waters. An example of an activity that would promote the conservation of coastal areas and ocean resources is',
      choices: [
        'harvesting large numbers of different fish species',
        'allowing all-terrain vehicles access to beach areas',
        'creating protected zones of natural grasses and shrubs in beach areas',
        'encouraging the construction of factories along the ocean shoreline',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Creating protected zones preserves native vegetation that stabilizes shorelines, provides wildlife habitat, and filters runoff. The other options all represent activities that degrade coastal ecosystems.',
      diveDeep: 'Coastal ecosystems — beaches, dunes, salt marshes, and estuaries — are among the most productive and ecologically important biomes on Earth. They serve as nursery grounds for many fish species, protect inland areas from storm surges, and filter nutrient runoff from land. Human activities such as vehicle traffic, construction, and overharvesting disrupt these functions. Protected buffer zones (such as those established under the Coastal Zone Management Act in the U.S.) represent a conservation strategy that balances human use with ecosystem preservation.',
    },
    {
      number: 20, part: 'A',
      text: 'Which activity would eventually result in a stable ecosystem?',
      choices: [
        'deforestation in an area to increase space for the species living there',
        'mowing a large field so it can be used for recreation',
        'allowing native plants to grow undisturbed in an abandoned field',
        'spraying pesticides on a field at the end of each growing season',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Allowing native plants to grow undisturbed initiates ecological succession, eventually leading to a stable climax community. Repeated disturbances (mowing, pesticides, deforestation) prevent succession from progressing toward stability.',
      diveDeep: 'A stable (climax) ecosystem results from undisturbed succession over time. In an abandoned field in the northeastern U.S., for example, grasses and wildflowers give way to shrubs, then pioneer trees, and eventually a mature forest. Each successional stage modifies the abiotic environment (soil depth, shade, moisture) to support the next stage. Human interventions that repeatedly set back succession (mowing, pesticides) maintain earlier successional stages and reduce biodiversity. Rewilding — allowing abandoned land to undergo natural succession — is an increasingly recognized conservation strategy.',
    },
    {
      number: 21, part: 'A',
      text: 'Some states require shoppers to pay a deposit on certain beverage containers made of plastic and glass. When shoppers return the containers, their deposits are returned to them. How is this system intended to help the environment?',
      choices: [
        'It encourages people to buy products that do not have a deposit.',
        'It reduces the amount of money shoppers actually spend.',
        'It reduces the amount of plastics and glass put into landfills.',
        'It forces manufacturers to reduce air pollution when they are making the containers.',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Bottle deposit programs incentivize consumers to return containers for recycling or reuse, directly reducing the volume of plastic and glass waste entering landfills and the environment.',
      diveDeep: 'Container deposit legislation (bottle bills) is a market-based environmental policy tool. By creating a financial incentive for return, these programs achieve very high recycling rates — often 80–95% for covered containers, compared to 30–50% for curbside recycling programs without deposits. This reduces landfill volume, decreases litter, conserves raw materials (sand for glass, petroleum for plastic), and cuts greenhouse gas emissions from manufacturing new containers. It illustrates how economic incentives can align individual behavior with environmental goals.',
    },
    {
      number: 22, image: '/images/exams/le-august-2017/q22.png', part: 'A',
      text: 'A diagram represents a food web with levels 1 through 4. Which level contains organisms that carry out autotrophic nutrition?',
      choices: [
        '1',
        '3',
        '2',
        '4',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'Level 1 (the base of the food web) contains producers — organisms that carry out autotrophic nutrition by manufacturing their own food through photosynthesis or chemosynthesis.',
      diveDeep: 'In any food web or energy pyramid, producers (autotrophs) occupy the base. They convert solar energy into chemical energy stored in organic molecules. All consumers (heterotrophs) at higher levels depend ultimately on the energy fixed by producers. Because approximately 90% of energy is lost as heat at each trophic level, energy pyramids always narrow from base to apex. Recognizing producers as the foundation of all food webs is essential for understanding energy flow and ecosystem productivity.',
    },
    {
      number: 23, part: 'A',
      text: 'Mad cow disease is a fatal disease that destroys brain tissue. Researchers have found that a prion protein, which is an abnormally constructed molecule, is responsible. Which statement best describes the characteristics a protein must have to function correctly?',
      choices: [
        'A protein is a long chain of amino acids folded into a specific shape.',
        'A protein is a long chain of simple sugars folded into a specific shape.',
        'A protein is made of amino acids synthesized into a short, circular chain.',
        'A protein is made of simple sugars synthesized into a short, circular chain.',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'Proteins are polymers of amino acids, and their specific three-dimensional shape (determined by the sequence of amino acids) is essential for their function. Prions are proteins with an abnormal shape that causes dysfunction.',
      diveDeep: 'The structure-function relationship of proteins is fundamental to biology. The primary structure (amino acid sequence) dictates how the chain folds into secondary structures (α-helices and β-sheets), then into tertiary (overall 3D shape) and quaternary structures. This final shape determines the protein\'s active site and therefore its function. Prions are misfolded versions of a normal brain protein (PrP); the misfolded form is infectious because it can induce the normal form to adopt the wrong shape, leading to aggregation and cell death — a dramatic example of how shape determines function.',
    },
    {
      number: 24, image: '/images/exams/le-august-2017/q24.png', part: 'A',
      text: 'A diagram represents the net movement of a specific kind of molecule across a living cell membrane from side A (high concentration) to side B (low concentration). The movement of molecules from side A to side B is an example of the process of',
      choices: [
        'active transport',
        'chromatography',
        'cellular respiration',
        'diffusion',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'Movement of molecules from an area of high concentration to low concentration across a membrane, without the use of energy, is diffusion. Active transport would require energy and move against the concentration gradient.',
      diveDeep: 'Diffusion is driven by the random kinetic motion of molecules: they naturally spread from regions of higher concentration to lower concentration until equilibrium is reached. When this occurs across a semipermeable membrane, it is called passive transport. Specific types include simple diffusion (small, non-polar molecules) and facilitated diffusion (larger or polar molecules aided by channel or carrier proteins, but still moving down their gradient). Active transport uses ATP to move molecules against their concentration gradient — for example, the sodium–potassium pump maintains the resting potential of neurons.',
    },
    {
      number: 25, part: 'A',
      text: 'Several companies now offer DNA "banking services," where DNA is extracted from a pet and stored so that a "replacement pet" might be produced using cloning techniques when the original pet dies. Which statement best explains why the replacement pets produced in this way might not look or act like the original?',
      choices: [
        'Cloning changes the DNA of the organism, producing a different genetic code.',
        'Cloning always causes mutations that change the traits of the new organism.',
        'Gene expression can be influenced by environment and developmental conditions, so identical DNA does not guarantee identical traits.',
        'The cloned animal will inherit traits from its surrogate mother, changing its genetic makeup.',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'A clone has the same DNA as the original, but phenotype (appearance and behavior) is shaped by both genes and environment during development. Different prenatal environments, life experiences, and epigenetic factors produce different outcomes even from identical DNA.',
      diveDeep: 'The nature vs. nurture debate is illustrated perfectly by cloning. Identical DNA does not guarantee identical phenotype because: (1) epigenetic modifications (DNA methylation, histone modifications) affect which genes are expressed; (2) the uterine environment of the surrogate mother differs from the original; (3) post-natal experiences (diet, social interactions, learning) shape behavior and physiology. The famous case of cloned cats shows coat color differences due to random X-chromosome inactivation, demonstrating that even genetically identical animals develop differently.',
    },
    {
      number: 26, part: 'A',
      text: 'A new antibiotic is used to treat a bacterial infection in a patient. After several weeks, the infection returns and does not respond to the same antibiotic. Which explanation best accounts for this change?',
      choices: [
        'The bacteria mutated in response to the presence of the antibiotic.',
        'Bacteria that had random mutations giving resistance survived, reproduced, and became the dominant strain.',
        'The patient\'s immune system destroyed the antibiotic before it could work.',
        'The antibiotic caused the bacteria to evolve new structures for defense.',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Natural selection explains antibiotic resistance: random mutations in some bacteria provided resistance before the antibiotic was introduced; those bacteria survived and reproduced while sensitive ones were killed, leading to a resistant population.',
      diveDeep: 'Antibiotic resistance is one of the most important public health challenges of the 21st century. Resistance evolves by natural selection, not by directed mutation. Key concepts: bacteria populations contain random genetic variation; antibiotics act as selective agents killing susceptible individuals; resistant variants survive and reproduce; resistance genes spread through vertical transmission (cell division) and horizontal gene transfer (plasmid exchange between bacteria). Incomplete antibiotic courses accelerate this process by exposing bacteria to sub-lethal doses that select for partial resistance.',
    },
    {
      number: 27, image: '/images/exams/le-august-2017/q27.png', part: 'A',
      text: 'The diagram below represents what happens when a substance produced by one gland travels to another area of the body and affects the functioning of an organ there. This is most likely showing the role of',
      choices: [
        'an enzyme in digestion',
        'a hormone in chemical communication',
        'an antibody in immune defense',
        'a neurotransmitter in nerve signal transmission',
      ],
      topic: 'Human Body',
      correct: 1,
      explanation: 'Hormones are chemical messengers produced by endocrine glands that travel through the bloodstream to target organs and alter their activity. This is the defining description of hormonal (endocrine) communication.',
      diveDeep: 'The endocrine system coordinates long-range communication through hormones. Unlike neurotransmitters (fast, localized), hormones act more slowly but have widespread effects. Hormones bind to specific receptors on target cells — either on the membrane (protein/peptide hormones) or inside the cell (steroid hormones). Examples include insulin (pancreas → liver/muscle), thyroid hormone (thyroid → metabolic tissues), and adrenaline (adrenal gland → heart and muscles). Negative feedback loops regulate hormone levels, maintaining homeostasis.',
    },
    {
      number: 28, part: 'A',
      text: 'Which statement best describes the process of meiosis and its significance?',
      choices: [
        'Meiosis produces two genetically identical daughter cells used for growth and repair.',
        'Meiosis produces four genetically unique cells with half the chromosome number, enabling sexual reproduction.',
        'Meiosis produces cells with the same chromosome number as the parent cell.',
        'Meiosis occurs in all body cells to replace damaged or worn-out cells.',
      ],
      topic: 'Reproduction',
      correct: 1,
      explanation: 'Meiosis is the specialized cell division that produces four haploid (half the normal chromosome number) gametes, each genetically unique due to crossing over and independent assortment. This is essential for sexual reproduction.',
      diveDeep: 'Meiosis consists of two divisions (Meiosis I and II) and produces four haploid cells from one diploid parent cell. Genetic diversity is generated by: (1) crossing over (recombination) during prophase I, which shuffles alleles between homologous chromosomes; (2) independent assortment of homologs, which produces 2²³ possible chromosome combinations in humans. When gametes from two parents unite at fertilization, the resulting zygote has a unique combination of alleles. This genetic variation is the raw material for natural selection and evolution.',
    },
    {
      number: 29, part: 'A',
      text: 'A scientist proposes that two different species of salamanders living in the same habitat are actually the same species based on morphological similarities. Which additional evidence would best support this hypothesis?',
      choices: [
        'The two salamanders have the same coloration.',
        'The two salamanders are able to interbreed and produce fertile offspring.',
        'The two salamanders eat the same food.',
        'The two salamanders live in the same geographic area.',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'The biological species concept defines a species as a group of organisms that can interbreed and produce fertile offspring. Successfully producing fertile offspring is the strongest evidence that two organisms belong to the same species.',
      diveDeep: 'Ernst Mayr\'s biological species concept is the most widely used definition of a species: a group whose members can interbreed and produce viable, fertile offspring under natural conditions. Morphological similarities alone can be misleading — some distinct species look nearly identical (cryptic species), while some species show great morphological variation. Genetic analysis and interbreeding experiments are the gold standard for determining species boundaries. Note that the concept has limitations for asexually reproducing organisms and fossils, for which other species concepts (morphological, phylogenetic) are used.',
    },
    {
      number: 30, part: 'A',
      text: 'The diagram below shows a cross section of a leaf. Chloroplasts are concentrated in the upper layers of the leaf cells. Which statement best explains why this arrangement is an advantage for the plant?',
      choices: [
        'Light can more easily reach chloroplasts in the upper layers, increasing the rate of photosynthesis.',
        'Chloroplasts in upper cells allow the plant to absorb more water from the soil.',
        'Chloroplasts in upper cells help the plant release carbon dioxide more efficiently.',
        'Chloroplasts in upper cells help the plant store more starch in its roots.',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'Chloroplasts in the upper (palisade) layers are exposed to maximum sunlight before it is absorbed or scattered by deeper tissue layers, increasing the efficiency of light capture for photosynthesis.',
      diveDeep: 'Leaf anatomy is highly adapted for photosynthesis. The palisade mesophyll layer, directly below the upper epidermis, contains tightly packed, chloroplast-rich cells that absorb the most light. The spongy mesophyll below it has more air spaces, facilitating CO₂ diffusion from the stomata to chloroplasts. The upper epidermis is transparent and often coated with cuticle to minimize water loss while allowing light through. This layered arrangement maximizes photosynthetic efficiency while balancing water conservation — a trade-off managed through stomatal opening and closing.',
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A graph shows the population size of a prey species (rabbits) and a predator species (foxes) over a 20-year period. The populations cycle: when rabbits increase, foxes increase shortly after; when rabbits decline, foxes decline.',
      text: 'Based on the graph, what most likely causes the fox population to decrease after the rabbit population decreases?',
      choices: [
        'Foxes migrate away when rabbit populations decline.',
        'The reduced rabbit food supply leads to starvation and decreased fox reproduction.',
        'Foxes begin competing with rabbits and are driven out of the habitat.',
        'Disease spreads among foxes when they gather in large numbers.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'When prey (rabbits) decline, predators (foxes) have less food available, causing increased starvation and reduced reproductive success, which decreases the predator population.',
      diveDeep: 'Predator–prey cycles are a classic example of population regulation. The Lotka–Volterra equations mathematically model these oscillations: prey population growth is limited by predation, and predator growth is limited by prey availability. Key points: (1) the predator population peak lags behind the prey peak; (2) the cycle is self-sustaining as long as neither population goes extinct; (3) in real ecosystems, multiple factors (disease, other prey species, vegetation cycles) complicate the pure two-species model. The Canadian lynx–snowshoe hare cycle is the textbook example of this phenomenon.',
    },
    {
      number: 32, part: 'B-1',
      context: 'A diagram shows the flow of energy through a food chain: Grass → Grasshoppers → Frogs → Hawks. The amount of energy (in kcal/m²/yr) at each level is shown.',
      text: 'Based on the diagram, which statement best explains why the hawk population must have a very large area of grass to support itself?',
      choices: [
        'Hawks require grass for nesting materials.',
        'Energy is lost at each trophic level, so the hawk needs a very large producer base to provide enough energy.',
        'Hawks compete with grasshoppers for grass, requiring more area.',
        'Grass produces toxins that hawks must avoid, requiring more habitat area.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Only about 10% of energy is transferred to the next trophic level; the rest is lost as heat. By the time energy reaches the hawk (4th level), only about 0.1% of the original grass energy remains, requiring a vast producer base.',
      diveDeep: 'The 10% rule of energy transfer means that at each trophic level, roughly 90% of energy is lost through metabolic heat, movement, and incomplete digestion. Starting with 10,000 kcal of grass energy: grasshoppers receive ~1,000 kcal, frogs ~100 kcal, hawks ~10 kcal. This is why energy pyramids are wide at the base and narrow at the apex, and why top predators need large territories. It also explains why food chains rarely exceed 4–5 levels — there is simply too little energy left to support additional levels.',
    },
    {
      number: 33, part: 'B-1',
      context: 'A diagram shows four stages of mitosis: prophase, metaphase, anaphase, and telophase.',
      text: 'During which phase of mitosis do chromosomes line up along the center (equator) of the cell?',
      choices: [
        'Prophase — chromosomes condense',
        'Metaphase — chromosomes align at the cell\'s equator',
        'Anaphase — chromosomes are pulled to opposite poles',
        'Telophase — nuclear envelopes reform',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'During metaphase, spindle fibers attach to chromosomes at the centromere and pull them to align precisely at the metaphase plate (center of the cell), ensuring each daughter cell receives one copy of each chromosome.',
      diveDeep: 'Mitosis has four main phases: prophase (chromosomes condense, spindle forms), metaphase (chromosomes align at metaphase plate, kinetochore fibers attached), anaphase (sister chromatids pulled to opposite poles), and telophase (nuclear envelopes reform, chromosomes decondense). Metaphase is the stage used in karyotyping because chromosomes are maximally condensed and individually identifiable. Errors in chromosome alignment during metaphase can lead to non-disjunction, producing daughter cells with the wrong chromosome number (aneuploidy), which can cause conditions such as Down syndrome.',
    },
    {
      number: 34, part: 'B-1',
      context: 'A table shows enzyme activity (measured as product formed per minute) at different pH levels: pH 2, 4, 6, 7, 8, 10, and 12. Activity is highest at pH 7 and decreases at both lower and higher pH values.',
      text: 'Based on the data, which statement best describes the effect of pH on enzyme activity?',
      choices: [
        'Enzyme activity increases as pH increases from 2 to 12.',
        'Enzyme activity is highest at pH 7 and decreases at pH values above or below 7.',
        'Enzyme activity is not affected by pH changes.',
        'Enzyme activity is highest at the most acidic pH tested.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      image: '/images/exams/le-august-2017/q34.png',
      explanation: 'The data show a bell-curve relationship: enzyme activity peaks at the optimal pH (here, pH 7) and decreases at pH values that deviate from this optimum, because extreme pH disrupts the enzyme\'s three-dimensional shape.',
      diveDeep: 'Enzymes function best at their optimal pH because the ionic environment at that pH maintains the precise 3D shape of the active site. Deviations in pH alter the charges on amino acid side chains, disrupting ionic bonds, hydrogen bonds, and the overall tertiary structure — a process called denaturation if severe. Different enzymes have different optimal pH values based on their natural environment: pepsin (stomach protease) works best at pH 2, while pancreatic enzymes work best at pH 7–8. This is an important concept for experimental design in biology labs.',
    },
    {
      number: 35, part: 'B-1',
      context: 'A graph shows the results of a population study of two species of Paramecium grown separately and together in the same test tube. When grown alone, both populations increase. When grown together, one species\' population rises while the other declines to zero.',
      text: 'Based on the graph, what conclusion can be drawn about the two species when grown together?',
      choices: [
        'Both species benefit from being grown together.',
        'The two species compete for the same resources, and one outcompetes the other.',
        'The two species help each other by providing nutrients the other needs.',
        'One species parasitizes the other, causing it to decline.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'When two species occupy the same niche and use the same resources, the competitive exclusion principle predicts that one will outcompete the other to extinction in that habitat — exactly what the graph shows.',
      diveDeep: 'Gause\'s competitive exclusion principle states that two species that occupy exactly the same ecological niche cannot coexist indefinitely — one will always outcompete the other and drive it to local extinction. This is demonstrated by classic Paramecium experiments: P. aurelia and P. caudatum both eat bacteria but at different efficiencies; when cultured together, P. aurelia consistently outcompetes P. caudatum. Coexistence is possible when species occupy different niches (resource partitioning), allowing both to avoid direct competition.',
    },
    {
      number: 36, part: 'B-1',
      context: 'A diagram shows the nitrogen cycle, with arrows representing the flow of nitrogen between the atmosphere, soil, plants, animals, and decomposers.',
      text: 'Based on the diagram, which organisms are responsible for converting atmospheric nitrogen (N₂) into a form that plants can absorb?',
      choices: [
        'decomposers (fungi and bacteria) that break down dead organisms',
        'nitrogen-fixing bacteria that convert N₂ into ammonia (NH₃)',
        'plants that absorb nitrogen directly from the atmosphere',
        'animals that excrete nitrogen in urine',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2017/context_36_37.png',
      explanation: 'Nitrogen-fixing bacteria (such as Rhizobium in legume root nodules and free-living Azotobacter) carry out the only biologically significant conversion of N₂ gas into ammonia, making nitrogen available for plant uptake.',
      diveDeep: 'The nitrogen cycle is essential for life because nitrogen is a component of amino acids (proteins) and nucleic acids (DNA, RNA). Although N₂ makes up 78% of the atmosphere, most organisms cannot use it directly because the N≡N triple bond is extremely strong. Nitrogen-fixing bacteria use the enzyme nitrogenase to break this bond and combine nitrogen with hydrogen to form NH₃ (ammonia). Nitrification bacteria then convert ammonia to nitrite and nitrate, which plants can absorb through roots. Denitrifying bacteria complete the cycle by returning N₂ to the atmosphere.',
    },
    {
      number: 37, part: 'B-1',
      context: 'A data table shows the number of species of birds found on islands of different sizes at different distances from the mainland.',
      text: 'Based on the data, which factor is most strongly associated with greater bird species diversity on an island?',
      choices: [
        'greater distance from the mainland',
        'smaller island area',
        'larger island area and closer proximity to the mainland',
        'smaller island area and greater distance from the mainland',
      ],
      topic: 'Evolution',
      correct: 2,
      image: '/images/exams/le-august-2017/context_36_37.png',
      explanation: 'Island biogeography theory predicts that larger islands support more species (more habitats, resources) and islands closer to the mainland have higher immigration rates — both factors increase species diversity.',
      diveDeep: 'MacArthur and Wilson\'s theory of island biogeography (1967) explains species diversity on islands as an equilibrium between immigration (arrival of new species) and extinction (local loss of species). Immigration rate decreases with distance from the mainland (harder for organisms to cross larger water gaps) and increases with island size. Extinction rate decreases with island size (more habitat means more resources and viable population sizes). The intersection of these two rates determines the equilibrium species number. This theory has important applications in conservation biology: habitat fragments behave like islands, and larger, better-connected reserves support higher biodiversity.',
    },
    {
      number: 38, part: 'B-1',
      context: 'A diagram shows the structure of a plant cell with organelles labeled A (chloroplast), B (cell wall), C (vacuole), and D (mitochondrion).',
      text: 'Which labeled structure in the diagram would NOT be found in an animal cell?',
      choices: [
        'D — mitochondrion',
        'A — chloroplast',
        'A and B — chloroplast and cell wall',
        'C — vacuole',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-august-2017/context_38_39.png',
      explanation: 'Animal cells lack both chloroplasts (used for photosynthesis) and cell walls (cellulose structural support). Both structures are unique to plant cells among the major eukaryotic cell types.',
      diveDeep: 'Key differences between plant and animal cells: Plant cells have chloroplasts (photosynthesis), a rigid cell wall (cellulose), a large central vacuole (storage, turgor pressure), and plasmodesmata (channels between cells). Animal cells lack these but have centrioles (cell division in animals), lysosomes, and other structures. Both cell types have mitochondria, ribosomes, endoplasmic reticulum, Golgi apparatus, and a nucleus. Understanding these differences is important for questions involving cell identification, osmosis (turgor vs. cell lysis), and metabolic capabilities.',
    },
    {
      number: 39, part: 'B-1',
      context: 'A graph shows the relative amounts of DNA in a cell over time, with peaks and drops corresponding to different phases of the cell cycle.',
      text: 'Based on the graph, at which point does the amount of DNA in the cell double?',
      choices: [
        'During G1, before DNA replication begins',
        'During the S phase, when DNA replication occurs',
        'During mitosis, when chromosomes separate',
        'During cytokinesis, when the cell divides into two',
      ],
      topic: 'Cell Biology',
      correct: 1,
      image: '/images/exams/le-august-2017/context_38_39.png',
      explanation: 'DNA replication (synthesis phase, or S phase) is when the cell copies its entire genome, doubling the amount of DNA before cell division. This ensures each daughter cell receives a complete set of chromosomes.',
      diveDeep: 'The cell cycle consists of interphase (G1 → S → G2) and the mitotic phase (M). During S phase, each chromosome is replicated to form two sister chromatids joined at the centromere. After replication, the cell has twice the normal DNA content (4N in a diploid organism after S phase). The checkpoints at G1/S and G2/M ensure that DNA replication is complete and error-free before the cell proceeds to division. Mutations in checkpoint genes (such as p53) can allow damaged DNA to be replicated and passed to daughter cells, contributing to cancer.',
    },
    {
      number: 40, part: 'B-1',
      context: 'A diagram shows a human karyotype — photographs of all 46 chromosomes arranged in homologous pairs. One karyotype shows a normal arrangement; another shows three copies of chromosome 21.',
      text: 'Based on the karyotype, what condition results from having three copies of chromosome 21?',
      choices: [
        'Turner syndrome — caused by missing a sex chromosome',
        'Down syndrome — caused by trisomy 21 (three copies of chromosome 21)',
        'Klinefelter syndrome — caused by an extra X chromosome in males',
        'Cystic fibrosis — caused by a recessive allele on chromosome 7',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-august-2017/q40.png',
      explanation: 'Trisomy 21 — having three copies of chromosome 21 — causes Down syndrome, which is characterized by intellectual disability and distinctive physical features. It results from non-disjunction during meiosis.',
      diveDeep: 'Non-disjunction during meiosis I or II results in gametes with an extra or missing chromosome. If a gamete with two copies of chromosome 21 is fertilized by a normal gamete, the resulting zygote has trisomy 21. Down syndrome is the most common chromosomal abnormality in live-born humans, occurring in about 1 in 700 births. Risk increases with maternal age because older eggs are more likely to have chromosome-segregation errors. Karyotyping (arranging chromosomes by size and banding pattern) can detect trisomy and other chromosomal abnormalities prenatally.',
    },

    // Part B-2 / C — Written
    {
      number: 41, part: 'B-2',
      type: 'written',
      text: 'Explain how the structure of a cell membrane allows it to regulate what enters and exits the cell.',
      topic: 'Cell Biology',
      modelAnswer: 'The cell membrane is a phospholipid bilayer with the hydrophilic (water-loving) heads facing outward (toward water) and the hydrophobic (water-fearing) tails facing inward, away from water. This arrangement creates a selectively permeable barrier. Small, nonpolar molecules (like O₂ and CO₂) can diffuse directly through the lipid bilayer. Larger or charged molecules (like glucose, ions, and proteins) require protein channels or carrier proteins embedded in the membrane to cross. Some proteins act as pumps that use ATP (active transport) to move substances against their concentration gradient. This selective control over what enters and exits allows the cell to maintain homeostasis by keeping internal conditions stable.',
      explanation: 'The phospholipid bilayer structure and embedded membrane proteins together create selective permeability, allowing the cell to control its internal environment.',
      diveDeep: 'The fluid mosaic model (Singer and Nicolson, 1972) describes the cell membrane as a dynamic, two-dimensional fluid with proteins "floating" in a lipid bilayer. Membrane proteins serve diverse functions: channels (facilitate diffusion), carriers (conformational change transports molecules), pumps (active transport using ATP), receptors (signal transduction), and glycoproteins (cell recognition). Cholesterol molecules inserted between phospholipid tails regulate membrane fluidity — increasing fluidity at low temperatures and decreasing it at high temperatures. This temperature regulation of fluidity is important for organisms living in environments with variable temperatures.',
    },
    {
      number: 42, part: 'B-2',
      type: 'written',
      text: 'A student claims that removing wolves from Yellowstone National Park would benefit the ecosystem by protecting elk populations. Evaluate this claim using your knowledge of food webs and ecosystem stability.',
      topic: 'Ecology',
      modelAnswer: 'The student\'s claim is incorrect. Wolves are a keystone predator in Yellowstone — their presence regulates elk populations. Without wolves, elk populations would increase dramatically, overgrazing vegetation such as willows and aspens along riverbanks. This loss of vegetation would cause riverbank erosion, destroy beaver habitat (beavers need willows), and reduce songbird populations that nest in willows. The "trophic cascade" initiated by wolf removal would destabilize the entire ecosystem. When wolves were reintroduced to Yellowstone in 1995, vegetation recovered, rivers became more stable, and biodiversity increased — demonstrating that removing a keystone predator does not benefit the ecosystem but instead destabilizes it.',
      explanation: 'Removing a keystone predator triggers a trophic cascade that destabilizes the ecosystem through overgrazing and loss of vegetation, harming many species besides the prey.',
      diveDeep: 'A trophic cascade occurs when changes at one trophic level ripple through the food web to affect multiple other levels. In Yellowstone, the wolf → elk → vegetation cascade is well-documented: wolf reintroduction (1995) reduced elk overgrazing, allowed riparian willows and aspens to recover, increased beaver populations (dam-building stabilized streams), improved habitat for songbirds and fish, and reduced soil erosion. This is a classic example of a top-down trophic cascade. The concept of keystone species — originally proposed by Robert Paine — recognizes that some species have a disproportionately large effect on ecosystem structure relative to their biomass.',
    },
    {
      number: 43, part: 'B-2',
      type: 'written',
      text: 'Describe how genetic information is transferred from a cell\'s DNA to a protein. Include the names of the processes and where each occurs in the cell.',
      topic: 'Genetics',
      modelAnswer: 'The transfer of genetic information from DNA to protein occurs in two steps, following the central dogma of molecular biology. First, transcription occurs in the nucleus: the enzyme RNA polymerase binds to the promoter region of a gene and unwinds the DNA double helix. One strand of DNA serves as a template, and complementary mRNA (messenger RNA) nucleotides are assembled. The resulting mRNA molecule carries the genetic code from the gene. The mRNA then exits the nucleus through nuclear pores and travels to the cytoplasm. Second, translation occurs at ribosomes in the cytoplasm: ribosomes read the mRNA sequence in groups of three bases called codons. Each codon specifies one amino acid. Transfer RNA (tRNA) molecules bring the correct amino acids to the ribosome, matching their anticodons to the mRNA codons. Amino acids are joined by peptide bonds to form a growing polypeptide chain, which folds into a functional protein.',
      explanation: 'DNA is transcribed into mRNA in the nucleus, and the mRNA is then translated into a protein at ribosomes in the cytoplasm — two distinct processes in two distinct cellular locations.',
      diveDeep: 'The central dogma (DNA → RNA → Protein) underpins all of molecular biology. Key details: RNA polymerase synthesizes mRNA in the 5\'→3\' direction using the 3\'→5\' template strand. In eukaryotes, the pre-mRNA is processed: a 5\' cap and poly-A tail are added, and introns (non-coding sequences) are spliced out, leaving only exons. The mature mRNA exits the nucleus. At the ribosome, initiation begins at the start codon (AUG, methionine), elongation adds amino acids, and termination occurs at a stop codon (UAA, UAG, or UGA). The 64 possible codons (4³) encode 20 amino acids, meaning the code is degenerate (multiple codons per amino acid), which buffers against the effects of some mutations.',
    },
    {
      number: 44, part: 'B-2',
      type: 'written',
      text: 'Explain how the process of natural selection can lead to the evolution of a new species over time. Use a specific example in your answer.',
      topic: 'Evolution',
      modelAnswer: 'Natural selection leads to evolution when certain inherited traits increase an organism\'s reproductive success in a given environment. Over many generations, these advantageous traits become more common in the population. If a population becomes geographically isolated — for example, when a group of finches colonizes a new island — the two groups experience different environmental conditions and different selection pressures. On the new island, finches with beaks suited to the available seeds (perhaps large, hard seeds) survive and reproduce more successfully. Over thousands of generations, the isolated population accumulates genetic differences through mutation and selection until the two populations become so different that they can no longer interbreed — at this point, they are classified as separate species (speciation). Darwin\'s finches on the Galápagos Islands are a classic example: a single ancestral finch species colonized multiple islands and diverged into 15 species with different beak shapes adapted to different food sources.',
      explanation: 'Natural selection acting on isolated populations with different environments gradually accumulates genetic differences over generations until the populations can no longer interbreed, producing new species.',
      diveDeep: 'Allopatric speciation (speciation via geographic isolation) is the most common mode of speciation. The process: (1) geographic barrier separates a population; (2) mutation and genetic drift produce random genetic differences; (3) natural selection adapts each subpopulation to its local environment; (4) over time, reproductive isolation mechanisms develop (different mating seasons, behaviors, or incompatible gametes); (5) if the populations were to come into contact again, they could no longer interbreed — they are now separate species. Sympatric speciation (without geographic isolation) also occurs, typically through polyploidy in plants or behavioral isolation. The overall rate of evolutionary change is debated — gradualism predicts slow, continuous change, while punctuated equilibrium proposes rapid changes followed by long periods of stasis.',
    },
    {
      number: 45, part: 'C',
      type: 'written',
      text: 'Design an experiment to determine whether a specific enzyme is affected by changes in temperature. Include the hypothesis, procedure, controls, variables, and how results would be analyzed.',
      topic: 'Cell Biology',
      modelAnswer: 'Hypothesis: Enzyme activity will be highest at body temperature (37°C) and will decrease at temperatures significantly above or below this optimum. Procedure: Prepare solutions of the enzyme (e.g., catalase from potato) and its substrate (e.g., hydrogen peroxide, H₂O₂) at the same concentration. Set up five identical test tubes, each containing the same amount of enzyme and substrate. Place each tube in a water bath at a different temperature: 10°C, 20°C, 37°C, 50°C, and 70°C. Allow the tubes to equilibrate for 5 minutes before combining enzyme and substrate. Measure enzyme activity by recording the rate of oxygen bubble production (using a floating disc method or by collecting gas) for 3 minutes. Record results for each temperature. Controls: Use a control tube with no enzyme (enzyme replaced with water) at each temperature to ensure that the substrate alone does not react. Variables: Independent variable — temperature; Dependent variable — rate of enzyme activity (bubbles/min or mL of O₂ collected); Controlled variables — enzyme concentration, substrate concentration, pH, volume of solution. Analysis: Graph enzyme activity vs. temperature. The temperature producing the highest activity is the enzyme\'s optimum temperature. Activity should decrease above the optimum (denaturation) and below it (reduced molecular kinetic energy).',
      explanation: 'A controlled experiment varies only temperature while keeping all other factors constant, allowing a cause-and-effect conclusion about temperature\'s effect on enzyme activity.',
      diveDeep: 'Experimental design in biology requires careful attention to variables and controls. A well-designed enzyme experiment distinguishes between reduced activity at low temperature (reversible — enzyme is slowed but not damaged) and reduced activity at high temperature (often irreversible — denaturation permanently alters the enzyme\'s 3D shape). The Arrhenius equation describes the relationship between temperature and reaction rate: for every 10°C increase, reaction rate approximately doubles (Q₁₀ = 2) until the denaturation temperature is approached. Enzyme kinetics are also described by the Michaelis–Menten model, which defines Km (substrate concentration at half-maximum velocity) and Vmax (maximum velocity), useful parameters for comparing enzyme efficiency.',
    },
    {
      number: 46, part: 'C',
      type: 'written',
      text: 'Humans have significantly increased the concentration of carbon dioxide in the atmosphere through burning fossil fuels and deforestation. Discuss two environmental consequences of this increase and suggest one action that could help address this problem.',
      topic: 'Ecology',
      modelAnswer: 'Two major environmental consequences of increased atmospheric CO₂ are: (1) Global warming / climate change: CO₂ is a greenhouse gas that absorbs and re-emits infrared radiation from Earth\'s surface, trapping heat in the atmosphere (the greenhouse effect). This causes rising average global temperatures, which disrupts weather patterns, causes glaciers and polar ice to melt (raising sea levels), shifts the geographic ranges of species, and increases the frequency of extreme weather events such as droughts and hurricanes. (2) Ocean acidification: approximately 30% of atmospheric CO₂ dissolves in ocean water, reacting with water to form carbonic acid (CO₂ + H₂O → H₂CO₃), which then dissociates to lower ocean pH. More acidic oceans dissolve the calcium carbonate shells and skeletons of corals, mollusks, and other marine organisms, threatening marine ecosystems and the fisheries that depend on them. One action that could help: Transitioning from fossil fuels to renewable energy sources (solar, wind, hydroelectric, geothermal) would reduce CO₂ emissions at their source. Reforestation programs also help by increasing the number of photosynthetic organisms that remove CO₂ from the atmosphere.',
      explanation: 'Elevated atmospheric CO₂ drives global climate change through the greenhouse effect and causes ocean acidification, both of which threaten biodiversity and human well-being.',
      diveDeep: 'The carbon cycle is being disrupted by human activities at a rate far faster than natural processes can buffer. Pre-industrial atmospheric CO₂ was approximately 280 ppm; as of 2023, it exceeds 420 ppm — a 50% increase. The IPCC (Intergovernmental Panel on Climate Change) projects that without significant emissions reductions, global average temperatures will rise 1.5–4°C by 2100. Ocean pH has already dropped from 8.2 to 8.1 since industrialization — a 26% increase in hydrogen ion concentration. The Paris Agreement (2015) committed signatory nations to limiting warming to 1.5–2°C above pre-industrial levels. Carbon capture technologies, along with renewable energy transitions, are key strategies in climate mitigation.',
    },
    {
      number: 47, part: 'C',
      type: 'written',
      text: 'Explain why biodiversity is important for the stability of an ecosystem. Give two specific reasons.',
      topic: 'Ecology',
      modelAnswer: 'Biodiversity — the variety of species in an ecosystem — is crucial for stability for the following reasons: (1) Redundancy and resilience: When multiple species perform similar ecological functions (e.g., multiple species of pollinators), the loss of one species does not eliminate that function entirely. Other species can partially compensate, maintaining ecosystem processes such as pollination, decomposition, and nutrient cycling. This functional redundancy makes biodiverse ecosystems more resilient to disturbances. (2) Food web complexity: A biodiverse ecosystem has a more complex food web with many interconnections. If one prey species declines, predators can switch to alternative prey, preventing population crashes. A simple food web with few species is more vulnerable — the loss of one species can cause a cascade of extinctions. Example: In monoculture agriculture (very low biodiversity), a single disease or pest can devastate the entire crop, whereas a diverse natural ecosystem is buffered against such losses.',
      explanation: 'Biodiversity provides redundancy (multiple species can perform the same function) and food web complexity (multiple food pathways), both of which increase ecosystem resilience to disturbances.',
      diveDeep: 'Ecologists measure biodiversity in several ways: species richness (number of species), species evenness (relative abundance of species), and genetic diversity within species. The relationship between biodiversity and ecosystem stability has been extensively studied; experiments such as the BIODEPTH project in Europe showed that higher plant diversity consistently produces more biomass, better resource use, and greater resistance to drought. The insurance hypothesis proposes that biodiversity acts like a financial portfolio: more diverse systems are less likely to fail entirely because different species respond differently to the same disturbance. Keystone species disproportionately affect ecosystem structure; their loss can trigger dramatic changes even in biodiverse systems.',
    },
    {
      number: 48, part: 'C',
      type: 'written',
      text: 'A new genetically engineered crop has been developed that is resistant to a common herbicide. Discuss one potential benefit and one potential risk of introducing this crop into the environment.',
      topic: 'Genetics',
      modelAnswer: 'Benefit: The herbicide-resistant crop allows farmers to apply the herbicide directly to fields to kill weeds without harming the crop. This can increase crop yields, reduce labor and fuel costs associated with mechanical weeding, and potentially decrease soil erosion caused by tillage. Farmers can use no-till farming methods, which preserve soil structure and reduce carbon emissions from soil disturbance. Risk: A significant environmental risk is the transfer of the herbicide-resistance gene to wild relatives of the crop through cross-pollination (gene flow). If wild plants acquire herbicide resistance, they could become "superweeds" that are difficult or impossible to control with that herbicide. This could lead to increased use of more toxic herbicides and greater environmental damage. Additionally, the development of herbicide-resistant crops may accelerate the evolution of resistant weed populations through natural selection, as the most tolerant weeds survive to reproduce. There are also concerns about reduction in biodiversity if the herbicide kills broad-spectrum plant species outside the intended field.',
      explanation: 'Herbicide-resistant GMO crops increase yield efficiency but carry the risk of creating herbicide-resistant weeds through gene transfer to wild plant populations.',
      diveDeep: 'Genetically modified organisms (GMOs) in agriculture represent one of the most debated topics at the intersection of science, technology, and society. Herbicide-tolerant crops (most commonly Roundup Ready® crops engineered for glyphosate resistance) now cover hundreds of millions of acres worldwide. The risk of transgene escape is real: pollen from GM crops can fertilize wild relatives, potentially conferring herbicide resistance. Documented cases of herbicide-resistant weeds have emerged in fields that extensively used glyphosate. Regulatory frameworks such as the EPA and USDA oversight in the U.S. require risk assessments before commercial release, but long-term ecological consequences remain difficult to fully predict. This topic illustrates the importance of evaluating trade-offs in technological decision-making.',
    },
    {
      number: 49, part: 'C',
      type: 'written',
      text: 'Explain the role of decomposers in an ecosystem and describe what would happen to the ecosystem if all decomposers were removed.',
      topic: 'Ecology',
      modelAnswer: 'Decomposers — primarily bacteria and fungi — break down dead organic matter (dead organisms, fallen leaves, animal waste) into simple inorganic molecules such as carbon dioxide, water, and mineral nutrients. This process is called decomposition. By returning nutrients to the soil and atmosphere, decomposers make those nutrients available again for uptake by producers (plants), completing the cycling of matter through the ecosystem. If all decomposers were removed: (1) Dead organisms and organic waste would accumulate without being broken down, covering the land and water. (2) Nutrients locked in dead organic matter would no longer be recycled into the soil, making them unavailable to plants. (3) Plant growth would slow dramatically as mineral nutrients (nitrogen, phosphorus, etc.) became depleted. (4) The entire food web would collapse as producer populations crashed due to nutrient deficiency. (5) Atmospheric CO₂ would decrease as carbon remained locked in organic material rather than being released during decomposition.',
      explanation: 'Decomposers recycle nutrients from dead matter back into the ecosystem; without them, nutrient cycles would halt, producers would be starved of essential minerals, and ecosystems would collapse.',
      diveDeep: 'Decomposition is carried out by a community of detritivores (e.g., earthworms, isopods) that fragment organic material and decomposers (bacteria and fungi) that chemically break it down. The rate of decomposition depends on temperature, moisture, oxygen availability, and the chemical composition of the material (lignin-rich material decomposes slowly; nitrogen-rich material decomposes quickly). Decomposers are responsible for all biogeochemical cycling: the carbon cycle, nitrogen cycle, phosphorus cycle, and sulfur cycle all depend on decomposition to release nutrients from dead organic matter. Without decomposition, nutrients would accumulate in the bodies of dead organisms and eventually all living matter would consist of the small amount of nutrients initially available in the environment.',
    },
    {
      number: 50, part: 'C',
      type: 'written',
      text: 'Vaccines are an important tool for preventing infectious disease. Explain how a vaccine works using your knowledge of the immune system.',
      topic: 'Human Body',
      modelAnswer: 'A vaccine works by stimulating the immune system to develop immunity against a pathogen (disease-causing organism) without causing the actual disease. A vaccine contains weakened or killed pathogens, or specific proteins (antigens) from the pathogen\'s surface. When the vaccine is administered, the immune system recognizes the antigens as foreign and mounts an immune response: white blood cells (B lymphocytes) produce antibodies — proteins that are specifically shaped to bind to those antigens and neutralize the pathogen. Crucially, the immune system also produces memory cells — long-lived lymphocytes that "remember" the specific antigen. If the person is later exposed to the actual pathogen, the memory cells recognize it immediately and trigger a rapid, strong immune response that destroys the pathogen before it can cause significant illness. This secondary immune response is faster and stronger than the first because memory cells eliminate the delay needed to produce new antibodies. Herd immunity occurs when a large enough proportion of the population is vaccinated, limiting the spread of the disease even to unvaccinated individuals.',
      explanation: 'Vaccines expose the immune system to harmless antigens, stimulating antibody production and memory cell formation so that future exposure to the real pathogen triggers a rapid, protective immune response.',
      diveDeep: 'The immune response has two main arms: the innate immune system (fast, non-specific) and the adaptive immune system (slower but specific and long-lasting). Vaccines work through the adaptive immune system. B cells produce antigen-specific antibodies; T cells coordinate the response and destroy infected cells. The primary immune response (first exposure) takes 1–2 weeks to reach peak antibody levels. Memory B and T cells persist for years or decades. The secondary immune response (second exposure or vaccination boost) occurs within 1–3 days and produces 10–100 times more antibodies. Different vaccine platforms (live-attenuated, inactivated, subunit, mRNA) all achieve this goal by different mechanisms. mRNA vaccines (e.g., COVID-19 vaccines) deliver mRNA encoding the antigen, which is translated by the body\'s own cells to produce the antigen that triggers immunity.',
    },
  ],
}
