// Living Environment Regents — August 2019
export default {
  id: 'le-august-2019',
  subject: 'living-environment',
  year: 2019,
  session: 'August',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'Which statement best describes the relationship between DNA and proteins?',
      choices: [
        'Proteins serve as templates for the synthesis of DNA molecules.',
        'DNA contains coded instructions that direct the synthesis of proteins.',
        'DNA is produced as a result of protein synthesis.',
        'Proteins carry genetic information from parent to offspring.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 2, part: 'A',
      text: 'Mitosis is the process by which',
      choices: [
        'a cell divides to produce two cells with half the chromosome number',
        'gametes are formed for sexual reproduction',
        'a cell divides to produce two genetically identical cells',
        'genetic material is transferred between organisms',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 3, part: 'A',
      text: 'In a freshwater pond ecosystem, large bass eat smaller bluegill fish, which eat water insects, which eat algae. If a disease kills most of the bluegill fish, the most likely immediate result would be',
      choices: [
        'a decrease in the bass population and an increase in the water insect population',
        'an increase in the bass population and a decrease in the water insect population',
        'no change in the bass or water insect populations',
        'an increase in the algae population and a decrease in the bass population',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 4, part: 'A',
      text: 'The human immune system produces proteins that recognize and bind to specific antigens on the surface of pathogens. These proteins are called',
      choices: [
        'hormones',
        'antibodies',
        'enzymes',
        'vitamins',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 5, part: 'A',
      text: 'An increase in the atmospheric concentration of CO₂ is linked to an increase in average global temperatures. Which human activity is the primary cause of the rise in atmospheric CO₂?',
      choices: [
        'increased agricultural production to feed the growing human population',
        'burning of fossil fuels for energy',
        'the use of nuclear energy to generate electricity',
        'the introduction of invasive species to new ecosystems',
      ],
      topic: 'General',
      correct: 1,
    },
    {
      number: 6, part: 'A',
      text: 'A species of bird eats insects that live on a particular type of flower. The bird has a curved beak that allows it to reach insects inside the flower. This adaptation is most likely the result of',
      choices: [
        'the birds intentionally developing curved beaks to reach food more easily',
        'natural selection favoring birds with curved beaks that could access food more effectively',
        'artificial selection by humans who bred birds with curved beaks',
        'a mutation caused by the bird\'s diet of flower insects',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 7, part: 'A',
      text: 'In an ecosystem, the amount of energy stored in producers is always greater than the energy stored in primary consumers, which is always greater than the energy in secondary consumers. This pattern exists because',
      choices: [
        'producers reproduce more quickly than consumers',
        'energy is lost as heat during cellular respiration at each trophic level',
        'predators always eat more food than producers produce',
        'consumers are less efficient at using energy than producers',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 8, part: 'A',
      text: 'Recombinant DNA technology allows scientists to combine DNA from two different organisms. One application of this technology is the production of human insulin by bacteria. This is beneficial because',
      choices: [
        'it allows insulin to be produced in large quantities without animal sources',
        'it produces insulin that is slightly different from human insulin and therefore safer',
        'it eliminates the need for diabetic patients to take insulin',
        'it allows the bacteria to produce insulin that prevents diabetes in future generations',
      ],
      topic: 'Cell Biology',
      correct: 0,
    },
    {
      number: 9, part: 'A',
      text: 'Which statement best describes the role of autotrophs in an ecosystem?',
      choices: [
        'They break down organic matter and return nutrients to the ecosystem.',
        'They convert inorganic molecules into organic molecules using light or chemical energy.',
        'They consume producers and transfer energy to higher trophic levels.',
        'They regulate the populations of all other organisms in the ecosystem.',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 10, part: 'A',
      text: 'Which statement correctly describes how vaccines protect individuals from disease?',
      choices: [
        'Vaccines kill all pathogens that enter the body.',
        'Vaccines contain antibodies that directly neutralize specific pathogens.',
        'Vaccines stimulate the immune system to produce antibodies and memory cells against a specific pathogen.',
        'Vaccines prevent pathogens from entering the body through skin and mucous membranes.',
      ],
      topic: 'Human Body',
      correct: 2,
    },
    {
      number: 11, part: 'A',
      text: 'A mutation in a gene that codes for an enzyme may affect the function of an organism. Which statement best explains why?',
      choices: [
        'The mutation changes the nucleotide sequence of the gene, which may change the amino acid sequence and shape of the enzyme.',
        'The mutation destroys the enzyme directly by breaking chemical bonds.',
        'The mutation causes the nucleus to stop producing all enzymes.',
        'The mutation spreads to all cells in the organism and prevents all protein synthesis.',
      ],
      topic: 'Cell Biology',
      correct: 0,
    },
    {
      number: 12, part: 'A',
      text: 'The interdependence of organisms in an ecosystem can be disrupted by the extinction of a species. Which situation illustrates this concept?',
      choices: [
        'Two competing species of squirrels live in the same forest and eat similar foods.',
        'The extinction of a specific bee species leads to the decline of the plant species it pollinates, which then affects animals that depend on that plant.',
        'A predator species migrates to a new ecosystem and competes with existing predators.',
        'An increase in the human population leads to more pollution in a local river.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 13, part: 'A',
      text: 'In humans, traits such as height and skin color are influenced by multiple genes and environmental factors. These traits are called',
      choices: [
        'dominant traits',
        'recessive traits',
        'sex-linked traits',
        'polygenic traits',
      ],
      topic: 'Human Body',
      correct: 3,
    },
    {
      number: 14, part: 'A',
      text: 'The human nervous system and endocrine system both function in communication within the body. The key difference between these two systems is that',
      choices: [
        'the nervous system uses chemical signals while the endocrine system uses electrical signals',
        'the nervous system uses electrical signals for rapid responses while the endocrine system uses hormones for slower, longer-lasting responses',
        'the endocrine system controls voluntary movements while the nervous system controls involuntary responses',
        'the endocrine system is faster than the nervous system',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 15, part: 'A',
      text: 'Which statement best describes the process of cellular respiration?',
      choices: [
        'Plants use sunlight to convert carbon dioxide and water into glucose and oxygen.',
        'Organisms break down organic molecules to release energy in the form of ATP.',
        'Organisms produce organic molecules from inorganic compounds using chemical energy.',
        'Cells divide to produce new cells for growth and repair.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 16, part: 'A',
      text: 'Coral bleaching occurs when water temperatures rise, causing corals to expel the symbiotic algae that live in their tissues. The algae provide the coral with nutrients through photosynthesis. When the algae are expelled, the coral turns white and often dies. This situation demonstrates that',
      choices: [
        'corals can survive without algae as long as they find other food sources',
        'the relationship between coral and algae is a parasitic one harmful to the coral',
        'disruption of mutualistic relationships due to environmental change can threaten the survival of both partners',
        'algae are harmful to corals at normal water temperatures',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 17, part: 'A',
      text: 'Scientists have found that organisms that share more recent common ancestors tend to have more similar DNA sequences. This evidence supports the theory of evolution because it indicates',
      choices: [
        'all organisms have identical DNA sequences because they share a common ancestor',
        'organisms that are more closely related have had less time to accumulate genetic differences',
        'DNA sequences become more similar over evolutionary time',
        'organisms evolve faster when they share more similar DNA sequences',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 18, part: 'A',
      text: 'A student compares two different types of cells under a microscope. Cell A has a cell wall, chloroplasts, and a large central vacuole. Cell B lacks these structures. Cell A is most likely from a',
      choices: [
        'bacterium',
        'animal',
        'fungus',
        'plant',
      ],
      topic: 'Cell Biology',
      correct: 3,
    },
    {
      number: 19, part: 'A',
      text: 'The gray wolf was reintroduced into Yellowstone National Park in 1995 after being absent for 70 years. After the wolves returned, elk populations decreased and moved more frequently. Riverside vegetation recovered, providing habitat for beavers, whose dams created ponds that benefited many other species. This series of changes is an example of',
      choices: [
        'competition between wolves and elk for the same resources',
        'a trophic cascade — the effects of a top predator rippling through an entire ecosystem',
        'artificial selection by park managers who chose the most desirable traits',
        'the direct extinction of many plant species by wolves',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 20, part: 'A',
      text: 'Genetic disorders can be caused by mutations that alter the structure or function of a protein. Sickle cell anemia is caused by a single amino acid change in hemoglobin. This example shows that',
      choices: [
        'all mutations are harmful and cause serious diseases',
        'even a small change in a gene can significantly alter the structure and function of a protein',
        'hemoglobin is the most important protein in the human body',
        'mutations can only occur in red blood cells',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 21, part: 'A',
      text: 'Scientists have found evidence that some dinosaur species were warm-blooded, similar to modern birds and mammals. This discovery changed the previously accepted view that all dinosaurs were cold-blooded. This is an example of how',
      choices: [
        'scientific knowledge is absolute and never changes once established',
        'scientists should reject all previous research and start over when new evidence is found',
        'scientific understanding changes when new evidence requires a revision of existing explanations',
        'the scientific method is unreliable because scientists often change their minds',
      ],
      topic: 'Evolution',
      correct: 2,
    },
    {
      number: 22, part: 'A',
      text: 'In a population of rabbits, fur color is determined by two alleles: B (brown, dominant) and b (white, recessive). If two brown rabbits that are both heterozygous (Bb) mate, what percentage of their offspring are expected to have white fur?',
      choices: [
        '0%',
        '25%',
        '50%',
        '75%',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 23, part: 'A',
      text: 'Scientists studying the Amazon rainforest have found that when small areas of forest are cleared, the surrounding forest shows higher levels of stress (measured by changes in leaf color and plant moisture). This observation suggests that',
      choices: [
        'the clearing of small areas has no significant effect on the surrounding forest',
        'forests act as integrated systems, and damage to one area can affect surrounding areas',
        'stressed trees grow faster than healthy trees and quickly fill the cleared area',
        'the Amazon rainforest is too large to be significantly affected by small clearings',
      ],
      topic: 'General',
      correct: 1,
    },
    {
      number: 24, part: 'A',
      text: 'The endocrine system communicates through hormones that are released into the bloodstream. Hormones affect only cells that have the appropriate',
      choices: [
        'enzymes to break down the hormone',
        'receptor proteins that specifically bind to the hormone',
        'mitochondria to produce energy for the hormone to work',
        'ribosomes to translate the hormone into a protein',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 25, part: 'A',
      text: 'The development of a fertilized egg into a multicellular organism requires',
      choices: [
        'only mitosis, which produces cells with different functions',
        'mitosis for cell division and differentiation for the development of specialized cell types',
        'only meiosis to produce all the cells needed for growth',
        'the mutation of genes in each new cell to produce specialization',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 26, part: 'A',
      text: 'Which human activity would most directly help preserve biodiversity in a region?',
      choices: [
        'introducing fast-growing invasive plant species to replace native vegetation',
        'establishing protected areas and wildlife corridors to maintain natural habitats',
        'using pesticides to control insect populations in agricultural areas',
        'draining wetlands to create farmland and housing developments',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 27, part: 'A',
      text: 'CRISPR/Cas9 is a gene-editing tool that allows scientists to cut and modify specific sequences of DNA in living cells. This technology could be used to',
      choices: [
        'produce genetically modified organisms that contain entirely new, synthetic chromosomes',
        'correct genetic mutations that cause diseases or improve crop resistance to disease',
        'clone entire organisms without the use of reproductive cells',
        'replace all chromosomes in a cell with chromosomes from another species',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 28, part: 'A',
      text: 'Which statement best explains why the process of meiosis is important for sexual reproduction?',
      choices: [
        'Meiosis ensures that each cell in the body receives the correct number of chromosomes.',
        'Meiosis produces gametes with half the chromosome number of the parent cell, so that fertilization restores the full chromosome number.',
        'Meiosis produces cells that are genetically identical to the parent cell.',
        'Meiosis allows organisms to reproduce without a partner.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 29, part: 'A',
      text: 'Scientists have found that the concentration of carbon dioxide in the atmosphere has increased from approximately 280 ppm (parts per million) before the Industrial Revolution to over 410 ppm today. This increase is most closely associated with',
      choices: [
        'increased volcanic activity releasing CO₂ from underground sources',
        'the burning of fossil fuels and deforestation',
        'increased photosynthesis by plants due to higher nutrient availability',
        'the release of CO₂ from the ocean as ocean temperatures fall',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 30, part: 'A',
      text: 'A population of bacteria is exposed to a new antibiotic. Most of the bacteria are killed, but a few survive. The surviving bacteria reproduce, and after many generations, the population is resistant to the antibiotic. This process is an example of',
      choices: [
        'artificial selection — humans chose which bacteria to allow to survive',
        'Lamarckian evolution — bacteria developed resistance because they needed to survive',
        'natural selection — bacteria with random mutations for resistance survived and passed resistance to offspring',
        'genetic engineering — the antibiotic caused targeted mutations in the bacterial DNA',
      ],
      topic: 'Ecology',
      correct: 2,
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'Scientists placed identical samples of pond water in three beakers. Beaker A received 12 hours of light per day, Beaker B received 6 hours of light per day, and Beaker C received no light. After 2 weeks, they measured the oxygen content in each beaker.',
      text: 'What is the dependent variable in this experiment?',
      choices: [
        'the number of hours of light each beaker received',
        'the amount of oxygen in each beaker at the end of the experiment',
        'the source of pond water used in each beaker',
        'the temperature at which the experiment was conducted',
      ],
      topic: 'General Review',
      correct: 1,
    },
    {
      number: 32, part: 'B-1',
      context: 'Scientists placed identical pond water samples in beakers receiving 12 hours, 6 hours, and no light per day. After 2 weeks, they measured oxygen levels. Results showed that beakers with more light had significantly more oxygen.',
      text: 'Which conclusion is best supported by these results?',
      choices: [
        'The amount of light has no effect on the oxygen content of pond water.',
        'Greater light exposure increases the rate of photosynthesis, producing more oxygen in the water.',
        'Oxygen in pond water comes from the breakdown of water molecules during cellular respiration.',
        'Beaker C has the highest oxygen level because organisms are not using oxygen to photosynthesize.',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 33, part: 'B-1',
      context: 'A graph shows the population sizes of rabbits and foxes in a meadow over 20 years. When the rabbit population increases, the fox population follows. When rabbit populations decrease, fox populations also decrease with a slight time delay.',
      text: 'Based on the graph, which statement best describes the relationship between rabbits and foxes?',
      choices: [
        'Rabbits are the predators and foxes are the prey in this relationship.',
        'Changes in the rabbit population influence changes in the fox population with a time delay.',
        'The rabbit and fox populations change independently of each other.',
        'The fox population changes occur before changes in the rabbit population.',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2019/q33.png',
    },
    {
      number: 34, part: 'B-1',
      context: 'A graph shows rabbit and fox populations in a meadow over 20 years. When rabbits are abundant, foxes increase. When rabbits are scarce, foxes decrease.',
      text: 'According to the graph, what most likely happens to the fox population when the rabbit population reaches its peak?',
      choices: [
        'The fox population immediately decreases because competition increases.',
        'The fox population begins to increase as food availability increases.',
        'The fox population remains unchanged because foxes eat other prey as well.',
        'The fox population increases before the rabbit population peaks.',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2019/q34.png',
    },
    {
      number: 35, part: 'B-1',
      text: 'Scientists studying coastal erosion found that areas where sea otters live have more kelp (large seaweed), which stabilizes sediments and protects the coastline. Sea otters eat sea urchins, which eat kelp. Without otters, sea urchin populations increase and kelp disappears. This illustrates that',
      choices: [
        'sea otters and kelp are in competition for space in the ocean',
        'the presence of a predator (sea otter) can indirectly protect a habitat by controlling the populations of organisms that would otherwise destroy it',
        'sea urchins are the most important species in coastal ecosystems',
        'removing sea otters has no significant effect on coastal erosion',
      ],
      topic: 'General',
      correct: 1,
    },
    {
      number: 36, part: 'B-1',
      text: 'A scientist discovers a new species of beetle in a rainforest. She wants to determine its evolutionary relationships with other beetle species. Which type of evidence would be most useful for this purpose?',
      choices: [
        'the geographic location where the new species was found',
        'the size and color of the beetle',
        'the DNA sequence of the new species compared to known beetle species',
        'the type of food the beetle eats',
      ],
      topic: 'Evolution',
      correct: 2,
    },
    {
      number: 37, part: 'B-1',
      context: 'A diagram shows the human immune response. When a pathogen enters the body, white blood cells detect the foreign antigens and produce antibodies that bind to the pathogen, marking it for destruction.',
      text: 'Based on the diagram, antibodies are effective against a pathogen because they',
      choices: [
        'kill all pathogens by destroying their cell walls',
        'are specific for the antigens on a particular pathogen, allowing the immune system to identify and destroy it',
        'prevent all future infections by destroying all pathogens in the body',
        'absorb nutrients from pathogens, starving them',
      ],
      topic: 'Human Body',
      correct: 1,
      image: '/images/exams/le-august-2019/q37.png',
    },
    {
      number: 38, part: 'B-1',
      context: 'A diagram shows the immune response, including memory cells that remain in the body after an infection.',
      text: 'Based on the diagram, which statement best explains why a person who has had chicken pox is usually immune to it for life?',
      choices: [
        'The chicken pox virus mutates and is no longer recognized by the immune system.',
        'Memory cells remain in the body after the initial infection and allow for a faster immune response if the same pathogen is encountered again.',
        'The body permanently produces large amounts of antibodies against chicken pox.',
        'The immune system destroys all pathogens before they can cause a second infection.',
      ],
      topic: 'Human Body',
      correct: 1,
      image: '/images/exams/le-august-2019/q38.png',
    },
    {
      number: 39, part: 'B-1',
      text: 'A team of scientists found that a species of frog in Panama was dying from a fungal disease. They captured some healthy frogs, treated them with antifungal drugs, and raised them in captivity away from the disease. They plan to reintroduce the frogs to the wild once a solution to the fungal disease is found. This strategy is an example of',
      choices: [
        'natural selection — the scientists are allowing only the fittest frogs to survive',
        'artificial selection — the scientists are breeding frogs with disease resistance',
        'captive breeding and conservation to prevent extinction of a threatened species',
        'cloning to produce large numbers of disease-resistant frogs',
      ],
      topic: 'Evolution',
      correct: 2,
    },
    {
      number: 40, part: 'B-1',
      context: 'A pedigree shows three generations of a family. In generation I, both parents are unaffected. In generation II, one son has the trait and one daughter does not. In generation III, the affected son has two children — one with the trait and one without.',
      text: 'Based on the pedigree, which conclusion is best supported?',
      choices: [
        'The trait is dominant because it skipped a generation.',
        'The trait is recessive because unaffected parents can have an affected child.',
        'The trait is sex-linked because only males are affected.',
        'The trait is caused by a new mutation in generation II.',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-august-2019/q40.png',
    },
    {
      number: 41, part: 'B-1',
      text: 'Scientists studying soil samples from different areas found that soil from a healthy forest ecosystem had many more species of bacteria and fungi than soil from a farm field. Which statement best explains this observation?',
      choices: [
        'Forests have less nutrient-rich soil than farms, limiting bacterial growth.',
        'The greater variety of dead plant material in the forest provides more diverse food sources for soil microorganisms.',
        'Farm fields contain antibiotics that kill most bacteria and fungi.',
        'Forest soil is more acidic than farm soil, which promotes microbial diversity.',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 42, part: 'B-1',
      text: 'A mutation in a gene occurs in the liver cells of an adult organism. This mutation will most likely',
      choices: [
        'be passed to the organism\'s offspring through sexual reproduction',
        'affect only the liver cells and the cells they produce through mitosis',
        'spread to all cells in the organism through the bloodstream',
        'cause the organism\'s offspring to have the same mutation',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 43, part: 'B-1',
      text: 'Wetlands provide many ecosystem services, including water filtration, flood control, and habitat for numerous species. As humans drain wetlands for development, these services are lost. Scientists argue that the economic value of these services is much greater than the value of the land for development. This illustrates that',
      choices: [
        'economic considerations should always take priority over environmental conservation',
        'the destruction of natural ecosystems can have significant economic consequences that are often underestimated',
        'wetlands are too difficult to restore once they have been drained for development',
        'human development always benefits the environment in the long run',
      ],
      topic: 'Evolution',
      correct: 1,
    },
  ],
}
