// Living Environment Regents — August 2024
export default {
  id: 'le-august-2024',
  subject: 'living-environment',
  year: 2024,
  session: 'August',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'The human body maintains a balanced internal environment. In order to accomplish this,',
      choices: [
        'organelles work independently',
        'all cells have the same shape and function',
        'insulin is produced when protein levels are low',
        'stimuli are detected, and actions are taken',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'Homeostasis is maintained through feedback mechanisms in which stimuli (changes in the internal environment) are detected by receptors and responses are initiated to restore balance. This stimulus-response cycle is the foundation of homeostatic regulation.',
      diveDeep: 'Homeostasis relies on negative feedback loops: a stimulus is detected, a signal is sent, and an effector responds to counteract the change. For example, when blood glucose rises, the pancreas detects this stimulus and secretes insulin to lower it. A common mistake is confusing homeostasis with a static state — it is actually a dynamic equilibrium. Organelles cooperate, not independently, and cells are specialized (not identical), so those choices are wrong. The insulin clue in choice C is a trap: insulin responds to high glucose, not low protein.',
    },
    {
      number: 2, part: 'A',
      text: 'Wolves are important predators in some ecosystems. If wolves are removed from their environment, the ecosystem is in danger of becoming unstable due to',
      choices: [
        'a reduction of autotrophs when the number of herbivores is not being kept in check by the wolves',
        'a decrease in the number of herbivores because they will not be able to reach carrying capacity',
        'an increase in the biodiversity of the remaining animal and plant species',
        'some species of herbivores taking over the niche the wolves occupied',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'Without wolves (apex predators), herbivore populations grow unchecked, overgrazing producers (autotrophs) and reducing plant biomass, which destabilizes the ecosystem. This is a classic trophic cascade effect.',
      diveDeep: 'Trophic cascades demonstrate how the removal of a top predator ripples through all trophic levels. The Yellowstone wolf reintroduction is a real-world example: wolf removal led to deer overpopulation, which decimated vegetation along riverbanks. Students often incorrectly choose that herbivores will decrease without wolves — in fact, without predation pressure, herbivore populations increase. Biodiversity typically decreases, not increases, when an apex predator is removed. Herbivores cannot occupy the wolves\' exact niche because they are different functional groups.',
    },
    {
      number: 3, part: 'A',
      text: 'Which statement best explains how deforestation that is the result of forest fires can contribute to global warming?',
      choices: [
        'Burning the trees adds smoke to the atmosphere and blocks sunlight.',
        'Burning the trees adds carbon dioxide to the atmosphere.',
        'Deforestation removes trees that produce carbon dioxide through the process of photosynthesis.',
        'Deforestation immediately increases ecosystem stability needed in the burned area.',
      ],
      topic: 'General',
      correct: 1,
      explanation: 'When trees burn, the carbon stored in their biomass is rapidly oxidized and released as carbon dioxide, a greenhouse gas that contributes to global warming. This adds to atmospheric CO₂ levels and enhances the greenhouse effect.',
      diveDeep: 'Trees act as carbon sinks, removing CO₂ from the atmosphere through photosynthesis and storing it in wood, leaves, and roots. Fire reverses this: stored carbon is rapidly converted back to CO₂. Choice C is a trap because trees perform photosynthesis (they consume CO₂, not produce it). Smoke blocking sunlight (choice A) is a short-term cooling effect, not warming. Students should remember that deforestation both releases carbon AND reduces future carbon uptake, making it doubly harmful for climate.',
    },
    {
      number: 4, part: 'A',
      text: 'For centuries, humans have built dams along rivers to redirect water for power, irrigation, and transportation. Dams can prevent migrating fish from swimming upstream to reproduce and can also disrupt the flow of sediments and nutrients. Communities are starting to eliminate some dams, and the health of the river ecosystems is being restored. This best illustrates that',
      choices: [
        'technological advances often involve environmental trade-offs',
        'when humans modify their environment it always has effects that cannot be reversed',
        'industrialization has had a positive effect on the health of river ecosystems',
        'the construction of dams affected abiotic factors in the river but not biotic factors',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'Dams provide human benefits (power, irrigation) but disrupt ecosystems — this demonstrates that technology often requires trading one benefit for an environmental cost. The restoration of rivers after dam removal shows these trade-offs can sometimes be reversed.',
      diveDeep: 'Environmental trade-offs are a recurring Regents theme: human technology solves some problems while creating others. Choice B is wrong because the passage itself states that restoration is occurring, proving effects CAN be reversed. Choice C is wrong because the passage specifically describes negative ecological effects. Choice D is wrong because the dams affected both abiotic factors (water flow, sediment) and biotic factors (fish migration, reproduction). When evaluating such scenarios, identify all stakeholders — human needs versus ecosystem health.',
    },
    {
      number: 5, part: 'A',
      text: 'In humans, lactose is broken down into glucose and galactose in the presence of a particular enzyme. It is most likely that the enzyme that breaks down lactose',
      choices: [
        'breaks down several other types of food in the stomach',
        'is involved in other reactions when the temperature and pH are ideal',
        'helps in the synthesis of complex sugars during autotrophic nutrition',
        'is not involved in other types of reactions because enzymes are specific',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'Enzymes are highly specific — each enzyme has a uniquely shaped active site that fits only one substrate (or a small group of closely related substrates). Lactase only catalyzes lactose hydrolysis, not other reactions.',
      diveDeep: 'Enzyme specificity arises from the three-dimensional shape of the active site, which is complementary to the substrate\'s shape — often called the "lock-and-key" model (or the more accurate induced-fit model). A common mistake is thinking enzymes can work on multiple unrelated substrates. Choice B is tempting because temperature and pH do affect enzyme activity, but even under ideal conditions, lactase will only act on lactose. Humans are not autotrophs, so choice C is immediately wrong. Specificity is one of the most fundamental enzyme properties tested on this exam.',
    },
    {
      number: 6, part: 'A',
      text: 'The Tdap vaccine can protect adolescents and adults from tetanus, diphtheria, and pertussis. Another vaccine, Td, protects against tetanus and diphtheria, but not pertussis. Td does not protect against pertussis because the',
      choices: [
        'Tdap vaccine is given to treat pertussis',
        'Td vaccine does not contain the antibodies from pertussis to fight the bacteria',
        'Tdap vaccine contains a small amount of the bacteria that causes pertussis',
        'Td vaccine does not stimulate the immune system of people to recognize pertussis antigens',
      ],
      topic: 'Human Body',
      correct: 3,
      explanation: 'Vaccines work by exposing the immune system to antigens (not antibodies) so it can build memory. The Td vaccine lacks pertussis antigens and therefore does not train the immune system to recognize or fight pertussis.',
      diveDeep: 'Vaccines contain antigens (weakened pathogens, inactivated toxins, or pathogen proteins) — NOT pre-made antibodies. They stimulate the body to produce its own antibodies and memory B-cells. Choice B is a common misconception: vaccines do not supply antibodies, they trigger the body\'s own immune response. Choice A is wrong because vaccines prevent infection rather than treat it. Understanding the difference between active immunity (vaccine-induced, long-lasting) and passive immunity (antibodies transferred, short-term) is critical for this topic on the Regents.',
    },
    {
      number: 7, part: 'A',
      text: 'Pelagic red crabs living on the ocean floor have been found to eat small bits of plastic. When they are consumed, these small creatures are passing the plastics along the food chain to predators, including fish consumed by humans. This is of concern because it',
      choices: [
        'decreases plastic recycling by primary consumers',
        'increases the risk of harmful substances in our food supply',
        'decreases the producers in the ecosystem',
        'increases the biodiversity of the ocean',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Plastics and their associated toxins bioaccumulate as they move up the food chain (biomagnification), so predators — including humans who eat fish — accumulate higher concentrations of harmful substances, threatening food safety.',
      diveDeep: 'Biomagnification occurs when non-biodegradable substances (such as plastics, DDT, and mercury) become more concentrated at each trophic level because top predators consume many prey organisms over a lifetime. Even small amounts of plastic at the base of the food chain can reach dangerous levels in apex predators. This is distinct from bioaccumulation (buildup within a single organism). Plastic does not increase biodiversity (choice D) — it harms it. Plastics are not a resource that can be "recycled" through consumption (choice A). Students should connect this concept to real-world examples like mercury in tuna.',
    },
    {
      number: 8, part: 'A',
      context: 'A graph titled "Cumulative Vertebrate Species Extinction" shows the percentage of mammal, bird, and other vertebrate species that have gone extinct from 1500–2014. The percentage increases dramatically from 1850 to 2014, with mammals showing the steepest rise.',
      text: 'Duckweed is a small plant that grows on the surface of still bodies of water. Over a nine-week period, scientists monitored the growth of duckweed in three ditches on the same farm. The number of duckweed plants increased rapidly during weeks one and two. After two weeks, each ditch was completely covered and remained covered for the remaining seven weeks. A valid conclusion based on the data collected is that',
      choices: [
        'animals that eat duckweed have the greatest effect on duckweed population size',
        'duckweed populations die off after completing a two-week life cycle in the ditch',
        'only changes in temperature affect duckweed population size',
        'the size of the duckweed population is kept stable by limited resources in the ditch',
      ],
      topic: 'General',
      correct: 3,
      image: '/images/exams/le-august-2024/q8.png',
      explanation: 'After the ditches became fully covered, the duckweed population stopped growing and remained stable — this plateau indicates that limiting resources (space, nutrients, light) prevented further population growth, consistent with carrying capacity.',
      diveDeep: 'Carrying capacity (K) is the maximum population size an environment can sustain given available resources. Once a population reaches K, growth slows and stabilizes. The S-shaped (logistic) growth curve shows rapid growth when resources are abundant, then leveling off at carrying capacity. Students often confuse the conclusion that can be drawn with speculation: the data shows stabilization due to limited resources, but does NOT mention predators, temperature, or life cycles, so those choices are not supported. Always base conclusions only on the given evidence.',
    },
    {
      number: 9, part: 'A',
      text: 'Which statement explains why the organisms in some ecosystems, such as rainforests, deserts, and oceans, are different from each other?',
      choices: [
        'The living organisms in each ecosystem have different needs and produce the physical conditions that they require.',
        'Each ecosystem contains different types of living organisms that change each of the physical conditions present there.',
        'They all have the same physical conditions present, but the living organisms use them in different ways.',
        'Each ecosystem contains different physical conditions that determine the type of living organisms present there.',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'Abiotic (physical) factors such as temperature, humidity, sunlight, and soil type determine which organisms can survive in an ecosystem — the environment shapes which species are present, not the other way around.',
      diveDeep: 'Abiotic factors act as environmental filters that select for organisms with appropriate adaptations. Rainforests have high rainfall, warmth, and light; deserts have extreme heat and aridity; oceans have salinity and pressure — each set of abiotic conditions supports a unique community. Choice A reverses the causation (organisms do not create their environment). Choice B is partially true (organisms do modify their environment somewhat) but does not explain why organisms differ in the first place. Students should memorize that abiotic factors include temperature, water, light, pH, and salinity.',
    },
    {
      number: 10, part: 'A',
      text: 'Some green plants secrete acids that dissolve rock, which makes it possible for the plants to absorb phosphorus needed for healthy plant growth. In addition to phosphorus, plants require many other substances. Which substances are required for the production of carbohydrates in green plants?',
      choices: [
        'oxygen and nitrogen',
        'carbon and glucose',
        'carbon dioxide and water',
        'hydrogen and starch',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Photosynthesis uses carbon dioxide (CO₂) and water (H₂O) as raw materials, along with light energy, to produce glucose (a carbohydrate) and oxygen. These are the essential inputs for carbohydrate synthesis.',
      diveDeep: 'The photosynthesis equation is: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. The carbon backbone of all carbohydrates comes from CO₂ fixation; hydrogen atoms come from water splitting. Choice B lists products/intermediates rather than raw materials. Choice D lists starch as an input — but starch is actually the stored product of photosynthesis. Students sometimes confuse cellular respiration inputs (glucose + oxygen) with photosynthesis inputs. Remembering "plants breathe in CO₂ and drink water to make sugar" is a helpful mnemonic.',
    },
    {
      number: 11, part: 'A',
      text: 'Which statement about competition in ecosystems is correct?',
      choices: [
        'Organisms compete most when they occupy different niches and resources are plentiful.',
        'Individuals need not compete, because resources such as water and food are always plentiful in ecosystems.',
        'Organisms that compete successfully will survive, reproduce, and pass their traits on to their offspring.',
        'Competition usually results in the extinction of a species, ensuring the survival of other species.',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Successful competition leads to survival and reproduction, which passes advantageous traits to offspring — this is the mechanism of natural selection as described by Darwin.',
      diveDeep: 'Competition is most intense between organisms occupying the same niche (not different niches, as choice A wrongly states). Resources are never unlimited — they are always finite, making competition inevitable (disproving choice B). Competition rarely causes complete extinction; more often, one species shifts its niche in a process called competitive exclusion or character displacement. Choice C directly connects competition to Darwin\'s survival of the fittest and natural selection, which is the core concept here. Students should remember that natural selection acts on heritable traits, so only genetic variations can be passed on.',
    },
    {
      number: 12, part: 'A',
      text: 'Human body systems interact with each other. The results of one body system functioning normally include: muscle cells receive oxygen, nerve cells receive glucose, lungs get rid of carbon dioxide, and some gland cells send chemical signals to organs. Which body system most directly enables all these functions to occur?',
      choices: [
        'circulatory system',
        'excretory system',
        'digestive system',
        'immune system',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'The circulatory system transports oxygen, glucose, hormones, and waste products (like CO₂) throughout the body, directly enabling delivery to and from all cells and organs mentioned in the question.',
      diveDeep: 'The circulatory system (heart, blood vessels, blood) is the body\'s distribution network. Blood carries oxygen from lungs to cells, glucose from the digestive system to cells, CO₂ from cells to lungs for exhalation, and hormones from glands to target organs. The excretory system removes nitrogenous waste but does not transport nutrients. The digestive system breaks down food but does not distribute it to cells — that\'s the circulatory system\'s job. Students often confuse the excretory and circulatory systems; remember that circulation distributes while excretion eliminates.',
    },
    {
      number: 13, part: 'A',
      text: 'The Himalayan rabbit lives in the cold Tibetan mountains. It typically has white fur on its body and black fur on its outer extremities. A scientist shaved a patch of white fur off the back of a Himalayan rabbit and applied an ice pack to the area for 30 minutes. The fur in the shaved area grew in black. The best explanation for why black fur grew in the shaved area is that',
      choices: [
        'the food the rabbit ate during the experiment influenced fur color',
        'the fur in the newly shaved area was younger than the white fur on the rest of the body',
        'the ice pack caused a mutation in the genes that regulate fur color',
        'warm and cold temperatures activate different genes for fur color',
      ],
      topic: 'General',
      correct: 3,
      explanation: 'The Himalayan rabbit\'s fur color is controlled by temperature-sensitive gene expression: cold temperatures activate the pigment gene (producing black fur), while warm body temperatures suppress it. Cooling the back caused the black pigment gene to be expressed.',
      diveDeep: 'This experiment demonstrates that gene expression can be influenced by environmental factors without changing the underlying DNA sequence — a concept related to epigenetics. The rabbit has both genes for black and white fur in every cell; temperature determines which gene is expressed. Choice C is wrong because an ice pack does not cause mutations; it only changes temperature temporarily. This is a classic example used to illustrate that genotype (the genes present) does not always equal phenotype (the visible trait) — environment can alter which genes are expressed. Students should distinguish between mutations (permanent DNA changes) and changes in gene expression (reversible).',
    },
    {
      number: 14, part: 'A',
      text: 'Researchers have identified a mutually beneficial relationship between some plant species and specific fungi. The fungi increase the nutrient uptake for these plants, and the plants provide nutrition to the fungi. In order for this relationship to occur, the plant must produce a particular protein. Scientists hope to enable plants that normally do not interact with these fungi to obtain the benefits. In order to make this possible, which process would scientists most likely use?',
      choices: [
        'Treat the plants with chemical fertilizers to stimulate their growth.',
        'Provide the fungi with the same molecular bases that are found in plant protein.',
        'Identify the gene that codes for the protein and introduce it into plant cells by genetic engineering.',
        'Selectively breed a new type of fungus that does not require the nutrients that the plants provide.',
      ],
      topic: 'Evolution',
      correct: 2,
      explanation: 'Genetic engineering allows scientists to identify a specific gene responsible for a desired protein and insert it into another organism\'s cells, enabling that organism to express the new trait — in this case, producing the protein needed for the fungal symbiosis.',
      diveDeep: 'Genetic engineering (recombinant DNA technology) involves isolating a gene, often using restriction enzymes, and inserting it into a host organism via a vector (such as a plasmid). This is distinct from selective breeding, which works with existing genetic variation over multiple generations. Chemical fertilizers (choice A) add nutrients externally but cannot make a plant produce a new protein. Providing molecular bases to fungi (choice B) does not change the plant\'s genetics. Students should know the steps of genetic engineering: identify gene → isolate gene → insert into host → express new protein.',
    },
    {
      number: 15, part: 'A',
      text: 'Milkweeds are plants that produce toxic, bitter-tasting chemicals. Some insects have developed the ability to safely feed on milkweed and accumulate the toxin in their bodies, causing them to taste bitter to predators. As a result, most animals avoid eating these insects. A possible explanation for this relationship is that',
      choices: [
        'eating a toxic plant increases the ability of these insects to survive and reproduce',
        'milkweed populations are controlled by many insects',
        'the milkweed benefits from the insects that can tolerate the toxin they produce',
        'eventually the insects will become immune to the toxin',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'Insects that can tolerate and accumulate milkweed toxins are protected from predation, giving them a survival advantage that increases their reproductive success — this is an adaptation shaped by natural selection.',
      diveDeep: 'The monarch butterfly-milkweed relationship is the classic real-world example of this concept: monarchs sequester cardiac glycosides from milkweed, making themselves toxic to birds. This is an evolutionary advantage gained through natural selection — insects with the ability to tolerate the toxin survived longer and reproduced more. Choice C is incorrect because the passage does not indicate a benefit to the milkweed from this relationship. Choice D is partially true in an evolutionary sense but over many generations, not the lifespan of individual insects. The key term is "survival and reproduction," which ties directly to natural selection.',
    },
    {
      number: 16, part: 'A',
      text: 'Which type of cell engulfs pathogens and marks them for killing?',
      choices: [
        'red blood cell',
        'white blood cell',
        'nerve cell',
        'muscle cell',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'White blood cells (leukocytes), particularly phagocytes such as macrophages and neutrophils, engulf pathogens through phagocytosis and display antigen fragments to activate the adaptive immune response.',
      diveDeep: 'The immune system has two main arms: the innate (non-specific) response involving phagocytes, and the adaptive (specific) response involving B-cells and T-cells. Phagocytes engulf pathogens and can present antigens to T-helper cells, linking the innate and adaptive responses. Red blood cells carry oxygen but have no immune function. Nerve cells transmit signals, and muscle cells produce movement. A common exam trap is confusing which cells produce antibodies (B-cells/plasma cells) versus which cells engulf pathogens (phagocytes/macrophages).',
    },
    {
      number: 17, part: 'A',
      text: 'A diagram shows a hierarchy of biological organization. Which choice correctly labels and defines the box labeled X in the hierarchy (between cells and organs)?',
      choices: [
        'cell: the basic structural, functional, and biological unit',
        'organ: a group of tissues with a common function',
        'tissue: a group of cells with a similar structure and function',
        'organ system: a collection of organs with a common function',
      ],
      topic: 'General',
      correct: 2,
      image: '/images/exams/le-august-2024/q17.png',
      explanation: 'In the biological hierarchy, tissues are positioned between cells and organs. A tissue is defined as a group of similar cells that work together to perform a specific function, such as muscle tissue or epithelial tissue.',
      diveDeep: 'The levels of biological organization in order are: atoms → molecules → organelles → cells → tissues → organs → organ systems → organism → population → community → ecosystem → biosphere. Between cells and organs lies the tissue level. The four main tissue types in animals are epithelial, connective, muscle, and nervous. Students sometimes confuse the order of tissue and organ — remember that multiple tissues combine to form an organ (e.g., the heart contains muscle tissue, connective tissue, and epithelial tissue). Memorizing the hierarchy from cell to organism is essential for this exam.',
    },
    {
      number: 18, part: 'A',
      context: 'A graph titled "Cumulative Vertebrate Species Extinction" shows the percentage of mammal, bird, and other vertebrate species that have gone extinct from 1500–2014. The percentage increases dramatically from 1850 to 2014, with mammals showing the steepest rise.',
      text: 'Concern is rising that mass extinctions of many species may increase. Based on the graph showing rising extinction rates from 1850 to 2014, this loss of different species is a concern because it may',
      choices: [
        'lead to an increase in diversity in the ecosystem',
        'impact the energy flow and food supply within an ecosystem',
        'produce increased nonrenewable resources',
        'provide additional sources of potential medicines',
      ],
      topic: 'Evolution',
      correct: 1,
      image: '/images/exams/le-august-2024/q18.png',
      explanation: 'When species go extinct, food webs are disrupted — the loss of producers, consumers, or decomposers affects energy flow through the ecosystem and can threaten food availability for remaining organisms, including humans.',
      diveDeep: 'Biodiversity is essential for ecosystem stability and function. Each species plays a role in energy transfer; losing key species (keystone species) can collapse food webs. Mass extinction reduces genetic diversity, limiting options for adaptation. Choice A is wrong — extinction decreases diversity, it does not increase it. Choice C is wrong — extinction of species does not create nonrenewable resources. Choice D is also a benefit of biodiversity preservation but is not directly related to energy flow and food supply, which is the most immediate and direct ecological consequence of species loss.',
    },
    {
      number: 19, part: 'A',
      text: 'The American Museum of Natural History has an Ecosystem Sphere — a huge sealed glass globe assembled in 1999 with populations of algae, bacteria, and little shrimp sealed with water and air inside. It is kept in a well-lit area. Although the sphere has never been opened, groups of each kind of organism are still alive inside it. The most likely reason is because the populations have',
      choices: [
        'remained in separate areas of the sphere and do not interact',
        'adapted so that they do not require food',
        'a constant source of energy because they cannot recycle gases and materials',
        'a constant source of energy and recycle gases and materials',
      ],
      topic: 'Cell Biology',
      correct: 3,
      explanation: 'The organisms survive because light provides a constant energy input (enabling algae to photosynthesize), and the different organisms recycle materials — algae produce oxygen and organic matter used by shrimp, bacteria decompose waste, cycling nutrients continuously.',
      diveDeep: 'This is a model closed ecological system. Two requirements for life to persist are energy flow and matter cycling. Light passes through the glass, giving algae energy to photosynthesize (energy input). Bacteria decompose dead organisms, recycling carbon, nitrogen, and other nutrients back into the system. Shrimp eat algae and produce CO₂, which algae use for photosynthesis. This creates a balanced cycle. Choice C is the opposite of the correct answer — matter IS recycled in this system. Students should understand the difference between energy (which flows one way and must be continually supplied) and matter (which is recycled within ecosystems).',
    },
    {
      number: 20, part: 'A',
      text: 'Ebola is a deadly viral disease. Researchers are testing a vaccine on people who have not yet been infected by Ebola but live in high-risk areas. The vaccine must be given to the subjects before exposure to Ebola because',
      choices: [
        'the vaccine will mutate the virus when a person gets infected',
        'if a subject is infected with Ebola, it will destroy the vaccine',
        'vaccines stimulate the subject\'s immune system to react to future exposure to the virus',
        'vaccines are only effective for a few days, so the patient must get the vaccine before exposure',
      ],
      topic: 'Human Body',
      correct: 2,
      explanation: 'Vaccines work by introducing antigens that prime the immune system to produce memory cells and antibodies. This preparation must happen before exposure so that the immune system can mount a rapid, effective response when the actual pathogen is encountered.',
      diveDeep: 'Vaccination is an example of active artificial immunity: the immune system is stimulated to produce its own antibodies and long-lived memory B-cells and T-cells without the person getting sick. When the actual pathogen is encountered later, the secondary immune response is faster and more powerful than the primary response. Vaccines do not mutate viruses (choice A) or get destroyed by infections (choice B). Most vaccines provide years to lifetime protection, disproving choice D. Students should understand primary vs. secondary immune response: the first exposure creates memory cells; the second exposure triggers a much faster response.',
    },
    {
      number: 21, part: 'A',
      text: 'A relatively large number of antibodies in a blood sample would most likely indicate that there is',
      choices: [
        'an infection in the body',
        'a mutation in the lung',
        'a deficiency of carbon dioxide in the circulatory system',
        'an insufficient amount of a specific vitamin in the diet',
      ],
      topic: 'Human Body',
      correct: 0,
      explanation: 'Antibodies are proteins produced by B-cells (plasma cells) in response to antigens from pathogens. A large number of antibodies indicates that the immune system has been activated, most likely in response to a current or recent infection.',
      diveDeep: 'Antibodies (immunoglobulins) are Y-shaped proteins with antigen-binding sites that are specific to a particular antigen. High antibody levels can indicate active infection, recent infection (memory response), vaccination, or autoimmune disease. Lung mutations (choice B) do not trigger systemic antibody production unless they expose new antigens. CO₂ levels (choice C) are unrelated to antibody production. Vitamin deficiency (choice D) may weaken immunity overall but does not cause a surge in antibodies. On the Regents, connecting elevated antibodies to immune response/infection is a key concept.',
    },
    {
      number: 22, part: 'A',
      text: 'Ultraviolet light can alter the DNA segments of genes in the skin cells of an individual. Which statement best describes a direct result of these alterations?',
      choices: [
        'Any cells produced from the altered skin cells will have the same alterations.',
        'All the offspring of the individual will have the same skin cell alterations.',
        'These alterations will spread to all the other cells in the body.',
        'The sex cells of the individual will have the same alterations.',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'When a skin cell\'s DNA is altered by UV light and that cell divides (mitosis), the mutation is copied into all daughter cells. The mutation stays within the somatic (body) cell lineage derived from that original altered cell.',
      diveDeep: 'Somatic mutations affect only body cells, not gametes, so they cannot be inherited by offspring (disproving choices B and D). Mutations do not spread laterally to neighboring cells — only daughter cells produced by mitosis from the mutated cell carry the change (disproving choice C). This is why skin cancer affects only certain patches of skin: only the daughter cells of the originally mutated cell carry the cancer-causing mutation. UV-induced mutations in p53 or other tumor-suppressor genes are the main cause of melanoma. Students must distinguish somatic mutations (non-heritable, affect individual) from germline mutations (heritable, affect offspring).',
    },
    {
      number: 23, part: 'A',
      text: 'The energy required to assemble proteins and fats is directly supplied to body cells from',
      choices: [
        'all the colors of visible light',
        'molecules of ATP contained within the cells',
        'all the DNA found in sex cells',
        'molecules of carbon dioxide produced by chloroplasts',
      ],
      topic: 'General',
      correct: 1,
      explanation: 'ATP (adenosine triphosphate) is the universal energy currency of cells. It directly powers all cellular processes, including the biosynthesis (assembly) of macromolecules like proteins and fats.',
      diveDeep: 'ATP stores energy in its high-energy phosphate bonds. When ATP is hydrolyzed to ADP + phosphate, energy is released for cellular work (anabolic reactions like protein synthesis, active transport, muscle contraction). Cells produce ATP through cellular respiration (primarily in mitochondria). Light energy cannot be directly used by animal cells — it must first be converted to chemical energy by photosynthesis. DNA does not supply energy; it stores genetic information. Chloroplasts are found in plant cells, not animal body cells, so choice D is wrong. ATP → ADP + energy is one of the most fundamental reactions to know for this exam.',
    },
    {
      number: 24, part: 'A',
      text: 'There are over 200 different cell types in the human body. Each type of cell is specialized to carry out a particular function, but they all developed from the same single cell. This is because each type of cell',
      choices: [
        'contains different genes than the other types of cells',
        'destroys the genes found in the other types of cells',
        'expresses some genes not expressed in the other cell types',
        'lacks the genes found in the other cell types',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'All cells in the body contain the same complete set of genes (derived from the original zygote through mitosis), but each cell type expresses only the specific subset of genes needed for its specialized function — this is called differential gene expression.',
      diveDeep: 'Cell differentiation is the process by which a single fertilized egg (zygote) produces hundreds of specialized cell types. Every somatic cell carries the entire genome (about 20,000–25,000 genes in humans), but only a fraction of those genes are actively transcribed in any given cell type. For example, pancreatic beta cells express the insulin gene while neurons express neurotransmitter receptor genes. Choices A, B, and D all incorrectly suggest cells have different or missing genes — this is wrong because mitosis produces genetically identical cells. Epigenetic factors (methylation, histone modification) control which genes are turned on or off during development.',
    },
    {
      number: 25, part: 'A',
      text: 'Coral reefs are vital components of marine ecosystems. Some coral reefs in the Pacific Ocean are heavily polluted with plastic objects that provide surfaces where disease-causing microbes are able to grow. If the amount of plastic present on coral reefs continues to increase, it is likely that the',
      choices: [
        'coral will adapt to the presence of the plastic and thrive',
        'microbes will adapt to living directly on the coral',
        'algae that live on the reef will begin to decompose the dying coral',
        'species dependent on the coral will be negatively impacted',
      ],
      topic: 'Ecology',
      correct: 3,
      explanation: 'Coral reefs support enormous biodiversity; if plastic pollution increases microbial disease on coral, the reef ecosystem deteriorates, and all species that depend on it for food, shelter, and reproduction will be negatively affected.',
      diveDeep: 'Coral reefs are biodiversity hotspots — about 25% of all marine species depend on them despite covering less than 1% of the ocean floor. Coral bleaching (from temperature stress) and disease (from pathogens) are leading causes of reef decline. Choice A is wrong because evolution/adaptation takes thousands of generations — coral cannot rapidly adapt to sudden pollution. Choice B may eventually be true but does not address what happens to reef-dependent species. Choice C is wrong — algae decomposing coral suggests collapse of the ecosystem, which is too extreme an immediate conclusion. The safest ecological prediction is that dependent species will be harmed.',
    },
    {
      number: 26, part: 'A',
      text: 'Enzymes, antibodies, and receptor molecules all have different functions. However, they are alike in that they',
      choices: [
        'all are involved in cellular respiration',
        'have a shape that is specific to their function',
        'are classified as carbohydrates',
        'are important in animals but not plants',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Enzymes, antibodies, and receptor molecules are all proteins whose three-dimensional shape is critical to their specific function — enzymes fit their substrates, antibodies bind specific antigens, and receptors recognize specific signaling molecules.',
      diveDeep: 'Shape specificity is the unifying principle of protein function. This concept applies across biology: enzyme active sites are shaped for specific substrates (lock-and-key model); antibody binding sites are shaped to match specific antigens; hormone receptors on cell membranes are shaped to recognize specific hormones. All three are proteins (not carbohydrates, disproving choice C). Plants also have enzymes and receptors, disproving choice D. Not all of these are involved in cellular respiration (choice A). The key concept: protein shape determines function, and changes in shape (from pH, temperature, or mutations) alter function.',
    },
    {
      number: 27, part: 'A',
      text: 'Australian quolls are endangered mammals. Scientists identified a gene that some quolls possess that makes them avoid eating poisonous cane toads. By selectively breeding quolls with the "toad-avoiding gene" with other quolls who lack the gene, scientists found all hybrid offspring inherited the survival gene. Before the survival gene could be passed on to any offspring, the genetic material present in the parent with the "toad-avoiding gene" would have to be',
      choices: [
        'mutated to become a different gene',
        'accurately replicated',
        'genetically engineered',
        'changed through recombination',
      ],
      topic: 'Genetics',
      correct: 1,
      explanation: 'Before any cell can divide (and before reproduction), DNA must be accurately replicated so that each daughter cell (or gamete) receives a complete copy of the genetic information, including the toad-avoiding gene.',
      diveDeep: 'DNA replication is the process by which the double helix is unwound and each strand serves as a template for a new complementary strand, producing two identical copies. This occurs during the S phase of the cell cycle. Accurate replication is critical for inheritance — if the gene were mutated (choice A), the correct sequence would not be passed on. Genetic engineering (choice C) is a human intervention, not a natural prerequisite for reproduction. Recombination (choice D) rearranges genes during meiosis but does not replicate them. The order is: replicate DNA → meiosis → gamete formation → fertilization → gene passed to offspring.',
    },
    {
      number: 28, part: 'A',
      text: 'Scientists have cloned many animals, such as cows, sheep, and chickens, from a single cell. Which natural process is most similar to these cloning techniques?',
      choices: [
        'asexual reproduction',
        'genetic recombination',
        'chromosome mutations',
        'gamete production',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'Cloning produces genetically identical offspring from a single cell without sexual reproduction, just as asexual reproduction (binary fission, budding, vegetative propagation) produces offspring that are genetically identical to the parent.',
      diveDeep: 'In cloning, the nucleus of a somatic cell is inserted into an enucleated egg, which then develops into an organism with the same genome as the donor. This mirrors asexual reproduction, where all offspring are genetically identical to the parent (clones). Genetic recombination (choice B) produces genetic diversity — the opposite of cloning. Chromosome mutations (choice C) alter the genome. Gamete production (choice D) involves meiosis and produces haploid cells with genetic variation. Students should know examples of natural asexual reproduction: binary fission (bacteria), budding (yeast), vegetative propagation (plants), and parthenogenesis (some animals).',
    },
    {
      number: 29, part: 'A',
      text: 'Within a sexually reproducing species, the correct chromosome number is maintained by',
      choices: [
        'halving the chromosome number in gamete production, followed by fertilization',
        'doubling the chromosome number in gamete production, followed by fertilization',
        'halving the chromosome number during mitosis, followed by differentiation',
        'doubling the chromosome number during mitosis, followed by differentiation',
      ],
      topic: 'Cell Biology',
      correct: 0,
      explanation: 'Meiosis halves the chromosome number from diploid (2n) to haploid (n) in gametes; fertilization then restores the diploid (2n) number when two haploid gametes fuse. This cycle maintains the species\' characteristic chromosome count.',
      diveDeep: 'In humans, diploid cells have 46 chromosomes (2n=46). Meiosis produces haploid gametes with 23 chromosomes (n=23). When sperm (23) and egg (23) unite at fertilization, the resulting zygote has 46 chromosomes. If gametes were not haploid, each generation would double the chromosome number, making life impossible. Mitosis maintains chromosome number within an organism but does NOT reduce it. Choice B (doubling in gamete production) would catastrophically increase chromosome number each generation. Meiosis is essential for sexual reproduction; mitosis is for growth and repair.',
    },
    {
      number: 30, part: 'A',
      text: 'The ability of sea otters to find food can be reduced because the environment where they search for food is often dark and murky. It has been recently discovered that the surface of otters\' paws are able to quickly detect a difference of one-quarter of a millimeter when comparing the size of objects, including food sources. The special characteristics of the otters\' paws can be described as',
      choices: [
        'a variation that eliminates the need for other senses otters normally possess',
        'a variation that is unlikely to be passed on to offspring because it is not a genetic trait',
        'an adaptation that could provide an advantage over the other organisms that they compete with for food',
        'an adaptation that is most likely the result of a mutation in body cells of the ancestors of the otter',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'The highly sensitive paws of sea otters are an adaptation — a heritable trait shaped by natural selection that improves the otters\' ability to locate food in dark water, giving them a competitive advantage over organisms without this ability.',
      diveDeep: 'An adaptation is a heritable trait that increases an organism\'s fitness (survival and reproduction) in its environment. Over many generations, otters with more sensitive paws were better at finding food, survived longer, and reproduced more, passing the trait to offspring. Choice A is wrong — the adaptation supplements, not replaces, other senses. Choice B is wrong because adaptations are genetic traits by definition. Choice D is wrong because adaptations arise from mutations in germline (reproductive) cells of ancestors, not body (somatic) cells. Students should always distinguish between individual variation (not heritable if not genetic) and true adaptations (heritable, shaped by natural selection).',
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A graph titled "The Effect of Temperature on Catalase Activity" shows relative catalase activity rising from 0°C to a peak around 35°C, then dropping sharply above 35°C.',
      text: 'Catalase is an enzyme produced by organisms that breaks down hydrogen peroxide, releasing oxygen and water. Based on the graph showing catalase activity at different temperatures, which statement best explains the decrease in activity of catalase after 35°C?',
      choices: [
        'The structure of the enzyme changes, which slows down the reaction.',
        'There is no hydrogen peroxide left for the activity to continue, so it stops.',
        'The raw materials permanently bind to the catalase, preventing the reaction.',
        'The reaction is no longer needed for survival of the individual.',
      ],
      topic: 'Human Body',
      correct: 0,
      image: '/images/exams/le-august-2024/q31.png',
      explanation: 'Above the optimal temperature, the enzyme denatures — its three-dimensional shape is disrupted by excess thermal energy, altering the active site so it can no longer bind the substrate effectively, reducing catalytic activity.',
      diveDeep: 'Denaturation is the irreversible unfolding of a protein\'s tertiary structure due to excess heat (or extreme pH). Hydrogen bonds, ionic bonds, and hydrophobic interactions that maintain the enzyme\'s shape are broken. Since the active site is defined by shape, a denatured enzyme cannot bind its substrate. This is why high fevers are dangerous — body enzymes begin to denature above ~40°C. Choice B is wrong because the experiment controls for substrate availability. Choice C is incorrect; substrates do not permanently bind to catalase under normal conditions. Students should memorize: too cold = too slow (not enough kinetic energy); too hot = denaturation (shape destroyed).',
    },
    {
      number: 32, part: 'B-1',
      context: 'A chart shows four cells (A, B, C, D) and which structures each contains. Cell A has: cell membrane, cell wall, chloroplasts, DNA, nucleus. Cell B has: cell membrane, DNA, nucleus. Cell C has: cell membrane, cell wall, DNA (no nucleus). Cell D has: cell membrane, DNA, nucleus.',
      text: 'Using a microscope, a student observed four different types of cells and recorded which structures were present (cell membrane, cell wall, chloroplasts, DNA, nucleus). Which of the cells he viewed were most likely from heterotrophs?',
      choices: [
        'A and C',
        'B and D',
        'C and B',
        'D and C',
      ],
      topic: 'Cell Biology',
      correct: 3,
      image: '/images/exams/le-august-2024/q32.png',
      explanation: 'Heterotrophs cannot make their own food and lack chloroplasts. Cell D (no cell wall, no chloroplasts, has nucleus — animal cell) and Cell C (cell wall, no chloroplasts, no nucleus — prokaryote/bacterium) are both heterotrophs.',
      diveDeep: 'Autotrophs (plants, algae, some bacteria) have chloroplasts or chlorophyll to make food via photosynthesis. Heterotrophs (animals, fungi, most bacteria) must consume organic matter. Cell A has chloroplasts → autotroph (plant). Cell B has no cell wall and no chloroplasts → animal cell (heterotroph). Cell C has a cell wall but no nucleus → prokaryote (bacterium, which is typically heterotrophic). Cell D has no cell wall, no chloroplasts → animal cell (heterotroph). The answer "D and C" corresponds to choice index 3. Students should memorize the cell comparison chart: plant cells have cell walls + chloroplasts; animal cells lack both; prokaryotes have cell walls but no nucleus.',
    },
    {
      number: 33, part: 'B-1',
      context: 'A coleus plant leaf has chloroplast-rich (green) areas on the edges and chloroplast-lacking areas in the middle. After exposure to sunlight and addition of starch indicator, the green (chloroplast-rich) areas turned blue-black, while the non-green middle areas did not.',
      text: 'A student exposed a coleus leaf (with chloroplast-rich edges and chloroplast-lacking middle) to sunlight, then added starch indicator to the entire leaf. The edges turned blue-black; the middle did not. Which statement is a valid claim, supported by evidence from this experiment?',
      choices: [
        'Chloroplasts are necessary for the production of starch indicator.',
        'Starch indicator causes leaves to produce oxygen.',
        'Chloroplasts are necessary for the production of starch.',
        'Water is necessary for the production of starch.',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'The blue-black color of iodine starch indicator appeared only where chloroplasts were present (the green edges), directly supporting the conclusion that chloroplasts are required for starch production via photosynthesis.',
      diveDeep: 'This is a classic experimental design using a variegated leaf as a natural control. The variable is presence/absence of chloroplasts; the test is starch production (detected by iodine). Blue-black = starch present; yellow-brown = no starch. The experiment tests only one variable (chloroplasts) while all other conditions (sunlight, water, temperature) are constant. Choice A is wrong — starch indicator is not produced by plants; it is added by the experimenter. Choice B reverses cause and effect. Choice D cannot be concluded because water was not the variable being tested. Students should practice identifying the independent variable, dependent variable, and control in every experiment question.',
    },
    {
      number: 34, part: 'B-1',
      text: 'Breathing vapors produced by e-cigarettes has caused respiratory problems, including coughing, shortness of breath, difficulty breathing, and even some deaths. Medical experts are warning the public and discouraging the use of these devices. The medical issues associated with vaping are an example of',
      choices: [
        'organ malfunctions caused by personal behaviors',
        'feedback response maintaining homeostasis',
        'inherited disorders resulting from inhaling vapors',
        'the effects of infectious parasites carried by the vapors',
      ],
      topic: 'General',
      correct: 0,
      explanation: 'Vaping is a personal behavior choice that introduces harmful chemicals into the respiratory system, causing damage to lung tissue — this is an organ malfunction directly caused by an individual\'s behavior rather than genetics, infection, or homeostatic feedback.',
      diveDeep: 'The Regents frequently tests the concept that personal behavior choices affect health and organ function. Vaping introduces aerosol chemicals (including heavy metals, volatile organic compounds, and nicotine) into the lungs, causing inflammation and tissue damage. This is not a homeostatic feedback response (choice B), which would be the body trying to correct an imbalance. Vaping-related illnesses are not inherited (choice C) — they develop during a person\'s lifetime due to behavior. Vapors do not carry parasites (choice D). Students should connect this to the broader theme that lifestyle choices (diet, exercise, substance use) directly impact organ health.',
    },
    {
      number: 35, part: 'B-1',
      context: 'A chart shows organisms and their energy sources: grasses (sunlight), leopard frog (insects, algae), carp (plants, insect larvae), heron (carp, frogs, salamanders), turtle (fish, plants, tadpoles, insects).',
      text: 'Based on the chart listing organisms and their energy sources in a New York ecosystem, when constructing an energy pyramid of this ecosystem, which of these organisms would be placed at the top of the pyramid?',
      choices: [
        'grasses',
        'carp',
        'heron',
        'leopard frog',
      ],
      topic: 'Ecology',
      correct: 2,
      image: '/images/exams/le-august-2024/q35.png',
      explanation: 'The heron occupies the highest trophic level because it eats carp, frogs, and salamanders — all of which are themselves consumers. In an energy pyramid, the apex predator (highest-order consumer) is placed at the top.',
      diveDeep: 'Energy pyramids show that energy decreases at each trophic level because about 90% is lost as heat. Producers (grasses, algae) are at the base; primary consumers (herbivores) are next; secondary and tertiary consumers are above. The heron eats carp (which eats plants/insect larvae) and frogs (which eat insects/algae), placing it at the tertiary or quaternary consumer level — the top. Grasses are producers at the base. Carp and frogs are mid-level consumers. The turtle also eats multiple trophic levels but only eats fish and plants — the heron eats higher-level consumers. Students should trace each organism\'s food sources to determine trophic level.',
    },
    {
      number: 36, part: 'B-1',
      context: 'A graph titled "Corn Yield as Affected by Planting Date" shows % of maximum yield on the y-axis vs. planting date on the x-axis. Yield is near 100% for plantings in late April/early May, then drops steadily. By June 1, yield is approximately 80% of maximum.',
      text: 'An unusually cool and wet spring prevented certain farmers from planting corn at the usual time (May 1), delaying planting until June 1. Based on the graph of corn yield by planting date, what is the most likely impact of the delayed planting on the production of corn?',
      choices: [
        'Corn yield will remain at 100% because higher temperatures in June will make plants grow faster.',
        'The corn yield may be reduced by about 20% because of the delay in planting.',
        'Corn yield may be reduced by about 80% because of the delayed planting.',
        'Crops planted on June 1 will have the same yield as those planted on April 1.',
      ],
      topic: 'General Review',
      correct: 1,
      image: '/images/exams/le-august-2024/q36.png',
      explanation: 'According to the graph, yield at June 1 planting is approximately 80% of maximum, meaning it is reduced by about 20% compared to optimal planting in late April/early May.',
      diveDeep: 'Graph-reading questions require students to identify the exact value at the given point (June 1) and calculate the difference from the maximum (100%). If the June 1 value is ~80%, then the reduction is 100% − 80% = 20%. Choice C confuses the yield remaining (80%) with the reduction (20%). Choice A is incorrect because the graph clearly shows yield decreases with later planting. Choice D is wrong because April 1 planting (too early/cold) also shows reduced yield. Students should always read graph axes carefully: the y-axis shows percentage of maximum yield, not absolute yield values.',
    },
    {
      number: 37, part: 'B-1',
      context: 'A table titled "Beetle Biodiversity" shows the number of individuals of each species (A–E) in four habitats. Habitat W: C=32, D=54 (2 species). Habitat X: A=2, B=6, C=10, D=22, E=8 (5 species). Habitat Y: C=120 (1 species). Habitat Z: A=40, C=40, E=40 (3 species).',
      text: 'An ecologist counted the number of individuals of each beetle species (A–E) she observed in four different habitats. Based on the data table showing species counts per habitat, which of these habitats displays the most biodiversity of beetle species?',
      choices: [
        'Habitat W',
        'Habitat X',
        'Habitat Y',
        'Habitat Z',
      ],
      topic: 'Evolution',
      correct: 1,
      image: '/images/exams/le-august-2024/q37.png',
      explanation: 'Habitat X has the greatest number of different beetle species (A, B, C, D, E — all 5 species), making it the most biodiverse regardless of the total number of individuals in each habitat.',
      diveDeep: 'Biodiversity refers to the variety of species in an area, not the total number of individuals. Habitat X has 5 species, Habitat W has 2, Habitat Y has 1, and Habitat Z has 3. Even though Habitat Y has 120 individuals, they are all the same species (very low biodiversity). Students commonly confuse biodiversity (species richness) with population size (number of individuals). A habitat with many individuals of one species is NOT more biodiverse than one with fewer individuals of multiple species. Higher biodiversity generally leads to more stable ecosystems because more species fill different niches.',
    },
    {
      number: 38, part: 'B-1',
      text: 'Hummingbirds, with their long beaks and tongues, are attracted to long, tubular flowers with a lot of nectar. When a hummingbird consumes the nectar from a flower, pollen sticks to the hummingbird and is transferred when the hummingbird feeds from other flowers. This relationship between the flowers and hummingbirds is a result of',
      choices: [
        'changes in hummingbirds and flowers in response to their needs',
        'inheritance of characteristics acquired during their lifetime',
        'natural selection of beneficial variations',
        'the environment modifying gene expression',
      ],
      topic: 'General',
      correct: 2,
      explanation: 'The mutual adaptations of hummingbirds (long beaks) and tubular flowers (matching shape, abundant nectar) evolved through natural selection: variations in beak length and flower shape that improved nectar access/pollination were selected for over generations.',
      diveDeep: 'This is an example of coevolution — two species evolving in response to selective pressures from each other. Hummingbirds with longer beaks could access more nectar → better survival/reproduction → long beaks became more common. Flowers with shapes matching hummingbird beaks got more pollinated → more reproduction → tubular shape became more common. Choice A implies organisms change intentionally to meet needs — this is Lamarckism, which is incorrect. Choice B (inheritance of acquired characteristics) is also Lamarckian and has been disproven. Choice D (environmental gene expression) is a different mechanism. Natural selection acting on random heritable variations is Darwin\'s correct explanation.',
    },
    {
      number: 39, part: 'B-1',
      text: 'Kittens from the same litter all have different fur colors and patterns. One possible reason that they all have different fur colors and patterns is that',
      choices: [
        'different kittens inherited more chromosomes from one parent than the other',
        'there was a random resorting of genes during gamete formation in each parent',
        'because there were so many, they did not receive the same amount of nutrients from the mother',
        'there were pH differences depending on where in the uterus each kitten developed',
      ],
      topic: 'General',
      correct: 1,
      explanation: 'During meiosis, homologous chromosomes are randomly sorted into gametes (independent assortment) and crossing-over occurs, producing gametes with unique gene combinations — this explains why siblings from the same parents have different traits.',
      diveDeep: 'Two mechanisms during meiosis generate genetic variation: (1) independent assortment — homologous chromosome pairs align randomly at the metaphase plate, producing 2²³ = ~8 million possible gamete combinations in humans; and (2) crossing-over (recombination) — exchange of DNA segments between homologous chromosomes creates novel allele combinations. Each kitten in a litter comes from a different sperm-egg combination, each with unique gene assortments. Choice A is wrong — each kitten gets exactly 50% of chromosomes from each parent (that\'s how meiosis works). Nutrition (C) and uterine pH (D) might affect development but not genetically-determined traits like fur color patterns.',
    },
    {
      number: 40, part: 'B-1',
      context: 'A study placed heated panels on the Antarctic Ocean floor 50 feet below the surface. Some panels were 1°C warmer, others 2°C warmer, and some unheated (control). Over 9 months, 1°C warming caused one invertebrate species to grow rapidly and become dominant, replacing multiple other species. Results on 2°C panels were less consistent.',
      text: 'Based on this experiment studying the effect of temperature increase on an Antarctic Ocean ecosystem, one result of the future warming of the Antarctic Ocean could be',
      choices: [
        'an increase in the stability of the Antarctic ecosystem',
        'the disruption of existing Antarctic marine food webs',
        'marine organisms evolving more rapidly in order to compete for resources',
        'the need to import predators to eat the tiny invertebrates',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'When one species dominates and others are displaced due to warming, biodiversity decreases and food webs are disrupted — species that depended on the displaced organisms for food or habitat lose those resources, destabilizing the entire food web.',
      diveDeep: 'Climate change and ocean warming are major threats to marine biodiversity. When temperature shifts cause one species to outcompete others, it is called competitive exclusion, and it reduces species diversity. With fewer species, food webs become simpler and more vulnerable to collapse. Choice A (increased stability) is the opposite of what the data shows. Choice C is incorrect — evolution occurs over many generations, not during the 9-month experiment; organisms cannot evolve "more rapidly" on demand. Choice D is speculative and not supported by the experimental data. When analyzing ecology experiments, focus on ecosystem-level consequences of species changes.',
    },
    {
      number: 41, part: 'B-1',
      context: 'A study placed heated panels on the Antarctic Ocean floor 50 feet below the surface. Some panels were 1°C warmer, others 2°C warmer, and some unheated (control). Over 9 months, 1°C warming caused one invertebrate species to grow rapidly and become dominant, replacing multiple other species. Results on 2°C panels were less consistent.',
      text: 'A possible explanation for the differences observed on the panels (control, +1°C, and +2°C) is that',
      choices: [
        'the growth of organisms is dependent on the abiotic factors present in the environment',
        'on the warmer panels, organisms reached carrying capacity more rapidly and completely died out',
        'on the control panels, wastes built up, poisoning some of the organisms growing there',
        'on the warmer panels, there were fewer decomposers present to recycle available energy',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'The different outcomes on different temperature panels directly demonstrate that temperature (an abiotic factor) influences organism growth rates and community composition — confirming that abiotic factors shape which organisms thrive.',
      diveDeep: 'Abiotic factors (temperature, salinity, pH, light, pressure) are non-living physical/chemical components of an environment that determine what can live there. This experiment is designed to isolate temperature as the independent variable. The fact that +1°C and +2°C panels showed different community compositions than the control proves temperature drives community structure. Choice B is incorrect — the dominant species grew rapidly on +1°C panels but did not die out. Choice C is speculation not supported by the data. Choice D (energy recycling by decomposers) is not mentioned in the context. Students should connect abiotic factor changes to community-level responses.',
    },
    {
      number: 42, part: 'B-1',
      context: 'A study placed heated panels on the Antarctic Ocean floor 50 feet below the surface. Some panels were 1°C warmer, others 2°C warmer, and some unheated (control). Over 9 months, 1°C warming caused one invertebrate species to grow rapidly and become dominant, replacing multiple other species. Results on 2°C panels were less consistent.',
      text: 'These test panels provided scientists with information about',
      choices: [
        'how ecological niches influence the rate of mutation',
        'the effect of environmental change on the biodiversity of the Antarctic Ocean',
        'the variety of producer/consumer relationships in the Antarctic Ocean',
        'how the stability of an ecosystem is affected by competition and disease',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'The experiment directly measured how temperature changes (an environmental change) affected which species survived and dominated on the panels, providing data about how warming affects the biodiversity of Antarctic marine communities.',
      diveDeep: 'This question tests the ability to identify what an experiment actually measures. The independent variable is temperature (environmental change); the dependent variable is species diversity and community composition (biodiversity). The panels functioned as model ecosystems representing different climate scenarios. Mutations (choice A) were not measured. Producer/consumer relationships (choice C) were not directly studied — the focus was on invertebrate community composition. Disease and competition (choice D) were not the experimental variables. When asked "what did this experiment tell scientists about," match the experimental design to the measured outcome.',
    },
    {
      number: 43, part: 'B-1',
      context: 'The kakapo is a small, flightless parrot with a small population on four islands off New Zealand. Scientists observed that when food is plentiful, more male offspring survive. An illustration shows: when food is scarce, sons are weak and unable to compete for mates; when food is plentiful, sons may be healthy, strong, and able to mate with many females.',
      text: 'Scientists are concerned the kakapo may become extinct. They observed that when food is plentiful, more male offspring survive. If scientists were going to test this hypothesis, the best way would be to select a test group and develop a research plan that includes collecting data when',
      choices: [
        'all of the kakapos are fed a reduced amount of food',
        'all of the kakapos are fed an unlimited amount of food',
        'the kakapo test group is divided in half, and one-half is fed unlimited food and the other a reduced amount of food',
        'the entire test group of kakapos is fed one type of food for one month and a different type of food for the second month',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'A valid experiment requires a control group (limited food) and an experimental group (unlimited food) tested simultaneously, allowing comparison between conditions to determine whether food abundance actually causes more male offspring to survive.',
      diveDeep: 'Good experimental design requires: (1) one independent variable changed at a time, (2) a control group for comparison, and (3) all other variables kept constant. Splitting the group in half with one fed unlimited food and the other reduced food creates the experimental and control conditions needed to test the hypothesis. Choice A (all fed reduced food) and choice B (all fed unlimited food) lack a comparison group — you cannot determine cause and effect without a control. Choice D changes the food type, not the food quantity, and tests the same animals sequentially (not simultaneously), introducing confounding variables. Students should always ask: "Does the experiment have a proper control and test one variable at a time?"',
    },
  ],
}
