// Living Environment Regents — August 2022
export default {
  id: 'le-august-2022',
  subject: 'living-environment',
  year: 2022,
  session: 'August',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'Which process is responsible for the growth and repair of body tissues in multicellular organisms?',
      choices: [
        'meiosis',
        'mitosis',
        'fertilization',
        'mutation',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Mitosis produces two genetically identical daughter cells from one parent cell, enabling organisms to grow by increasing cell number and to repair damaged tissues by replacing lost or injured cells.',
      diveDeep: 'Mitosis maintains the diploid chromosome number (2n) in all somatic (body) cells. The process has four phases: prophase (chromosomes condense, spindle forms), metaphase (chromosomes align at cell equator), anaphase (sister chromatids pulled to poles), and telophase (nuclear envelopes reform), followed by cytokinesis (cytoplasm division). The result is two genetically identical diploid daughter cells. Meiosis, by contrast, produces genetically diverse haploid (n) gametes for sexual reproduction — not for growth or repair. Uncontrolled mitosis is the basis of cancer.',
    },
    {
      number: 2, part: 'A',
      text: 'In an ecosystem, energy flows from the Sun to producers and then to consumers. At each step in this energy transfer, most of the energy is',
      choices: [
        'stored in the bodies of organisms at the next trophic level',
        'lost as heat to the environment',
        'converted to chemical energy in the atmosphere',
        'recycled back to the producers',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Only approximately 10% of energy at each trophic level is transferred to the next; the remaining ~90% is released as metabolic heat through cellular respiration, movement, and other metabolic processes.',
      diveDeep: 'The 10% rule of energy transfer (ecological efficiency) explains why energy pyramids narrow at each level. Energy is not recycled — unlike matter (which cycles through biogeochemical cycles), energy flows in one direction through the ecosystem and is ultimately lost as heat. This is why ecosystems require a continuous input of solar energy to maintain themselves. The low efficiency of energy transfer explains why there are typically only 4–5 trophic levels in any food chain and why top predators need large territories to obtain sufficient energy.',
    },
    {
      number: 3, part: 'A',
      text: 'Identical twins develop from a single fertilized egg that splits into two cells. These twins have identical DNA, yet they may have different fingerprints. This difference is most likely due to',
      choices: [
        'mutations in the DNA of one twin that occurred after the split',
        'differences in the environments of each twin during development',
        'the twins inheriting different chromosomes from their parents',
        'the twins using different genes to control development',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Fingerprint development is influenced by random physical pressures in the womb during fetal development — even with identical DNA, different micro-environmental conditions during growth produce different fingerprint patterns.',
      diveDeep: 'This scenario illustrates that genotype (DNA sequence) does not entirely determine phenotype (observable traits). Environmental influences during development — temperature, nutrition, physical stresses, positional differences in the womb — affect gene expression and developmental outcomes even in genetically identical individuals. Epigenetics (heritable changes in gene expression without DNA sequence changes) also plays a role; identical twins become epigenetically more different as they age. The fingerprint example is commonly used to show that even highly heritable traits involve developmental plasticity.',
    },
    {
      number: 4, part: 'A',
      text: 'The sequence of amino acids in a protein is determined by the',
      choices: [
        'shape of the ribosome that produces the protein',
        'sequence of bases in the DNA gene for that protein',
        'type of lipid molecules surrounding the cell',
        'number of mitochondria in the cell',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Each three-base codon in the DNA (transcribed into mRNA) specifies one amino acid; the linear sequence of codons in the gene therefore directly determines the sequence of amino acids in the resulting protein.',
      diveDeep: 'The central dogma: DNA → mRNA → protein. The genetic code is the set of rules by which nucleotide triplets (codons) are translated into amino acids. The code is nearly universal across all life. With 4 bases and codons of 3 bases, there are 4³ = 64 possible codons encoding 20 amino acids (plus 3 stop codons) — the code is degenerate (multiple codons per amino acid). The amino acid sequence (primary structure) determines how the protein folds into its 3D shape (secondary → tertiary → quaternary structure), which in turn determines its function.',
    },
    {
      number: 5, part: 'A',
      text: 'A symbiotic relationship in which one organism benefits and the other is neither harmed nor helped is called',
      choices: [
        'mutualism',
        'commensalism',
        'parasitism',
        'predation',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Commensalism is a symbiotic relationship where one organism benefits (+) and the other is unaffected (0). An example is a barnacle attaching to a whale — the barnacle benefits from transportation to food-rich water, while the whale is unaffected.',
      diveDeep: 'Symbiotic relationships are classified by the effect on each partner: mutualism (+/+, both benefit), commensalism (+/0, one benefits, other unaffected), and parasitism (+/−, one benefits, other harmed). True commensalism is rare — on close examination, most apparent commensal relationships are actually mildly mutualistic or mildly parasitic. Examples include cattle egrets feeding on insects disturbed by grazing cattle (egret benefits, cattle minimally affected), orchids growing on tree branches for light access (orchid benefits, tree largely unaffected), and certain fish that follow sharks to eat scraps.',
    },
    {
      number: 6, part: 'A',
      text: 'The extinction of a keystone species in an ecosystem would most likely result in',
      choices: [
        'increased stability because fewer species compete for the same resources',
        'a dramatic change in the structure and function of the ecosystem',
        'rapid recovery of the ecosystem due to the resilience of other species',
        'no significant change because other species would immediately fill the niche',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'A keystone species has a disproportionately large effect on ecosystem structure relative to its biomass; its loss triggers cascading changes (trophic cascades) that dramatically alter community composition and function.',
      diveDeep: 'The concept of keystone species was introduced by Robert Paine based on his experiments with sea stars (Pisaster ochraceus) in Pacific intertidal zones. When sea stars were removed, mussels (their primary prey) overgrew the entire intertidal area, eliminating most other species and dramatically reducing biodiversity. Classic keystone examples include wolves in Yellowstone (control elk, maintaining riparian vegetation), sea otters (control sea urchins, maintaining kelp forests), and fig trees in tropical forests (year-round fruit supports many species during dry periods). The keystone concept underscores that ecological importance is not always proportional to biomass.',
    },
    {
      number: 7, part: 'A',
      text: 'An organism that feeds on dead organic matter and breaks it down into simpler substances is called a',
      choices: [
        'producer',
        'primary consumer',
        'decomposer',
        'carnivore',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Decomposers (primarily bacteria and fungi) obtain energy by breaking down dead organisms and organic waste into simpler inorganic compounds, completing nutrient cycles and making nutrients available to producers again.',
      diveDeep: 'Decomposers are sometimes called saprotrophic organisms or saprobes — they secrete digestive enzymes externally and then absorb the resulting small molecules. This differs from detritivores (earthworms, pill bugs), which ingest dead material and physically fragment it, making more surface area available for decomposers. Without decomposers, nutrient cycles would stop: carbon, nitrogen, phosphorus, and other essential elements would remain locked in dead organic matter rather than cycling back to producers. Decomposers are thus essential links in every biogeochemical cycle.',
    },
    {
      number: 8, part: 'A',
      text: 'Which cell organelle is most directly involved in the production of proteins?',
      choices: [
        'mitochondria',
        'ribosome',
        'vacuole',
        'cell membrane',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Ribosomes are the sites of protein synthesis (translation) — they read mRNA codons and assemble amino acids into polypeptide chains according to the genetic instructions.',
      diveDeep: 'Ribosomes are complex molecular machines composed of ribosomal RNA (rRNA) and proteins, forming two subunits (large and small). They can be free in the cytoplasm (making proteins for use inside the cell) or attached to the rough endoplasmic reticulum (making proteins for secretion or membrane insertion). During translation: the small subunit binds mRNA, tRNA molecules bring amino acids, and the large subunit catalyzes peptide bond formation between amino acids. A single mRNA can be translated simultaneously by multiple ribosomes (polyribosomes/polysomes), greatly increasing protein production efficiency.',
    },
    {
      number: 9, part: 'A',
      text: 'Humans have intentionally bred dogs for specific traits such as size, coat color, and temperament. This process is an example of',
      choices: [
        'natural selection',
        'genetic mutation',
        'artificial selection',
        'sexual reproduction',
      ],
      topic: 'Genetics',
      correct: 2,
      explanation: 'Artificial selection (selective breeding) is when humans intentionally choose which individuals reproduce based on desired traits, directing evolution toward human-selected outcomes rather than survival of the fittest.',
      diveDeep: 'Artificial selection was used by Darwin as evidence that selection can rapidly change populations — if humans can produce dramatic changes in a few hundred years of dog breeding, natural selection over millions of years can produce even more dramatic changes. All modern dog breeds descended from wolves through thousands of years of artificial selection. Artificial selection has also produced domesticated crops (wild mustard → broccoli, kale, cabbage, Brussels sprouts through selection for different traits), livestock, and laboratory model organisms. The genetic diversity created by artificial selection is now studied to understand the genetics of complex traits.',
    },
    {
      number: 10, part: 'A',
      text: 'Antibiotics are drugs that kill bacteria. Some bacteria have developed resistance to antibiotics. The development of antibiotic resistance in a bacterial population is an example of',
      choices: [
        'Lamarckian evolution — bacteria developed resistance because they needed to survive',
        'natural selection — bacteria with random mutations survived and passed resistance to offspring',
        'genetic engineering — scientists modified bacterial DNA to produce resistant strains',
        'selective breeding — humans chose resistant bacteria for reproduction',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Antibiotic resistance evolves through natural selection: random mutations in bacteria pre-existed before antibiotic exposure; antibiotics selectively kill susceptible bacteria while resistant ones survive and reproduce, increasing resistance frequency in the population.',
      diveDeep: 'This is one of the most important real-world examples of evolution by natural selection. Key misunderstanding to avoid: bacteria do not "develop" resistance because they "need" to — this is Lamarckian thinking (inheritance of acquired characteristics, now disproven). Instead, resistance mutations arise randomly and continuously; antibiotics act as a selective filter. Resistance genes can also spread through horizontal gene transfer (conjugation) between bacteria that are not parent-offspring. The speed of bacterial evolution is extraordinary due to short generation times (as fast as 20 minutes) and large population sizes, making resistance a rapidly evolving public health crisis.',
    },
    {
      number: 11, part: 'A',
      text: 'Which statement best describes the function of mitochondria in a cell?',
      choices: [
        'They produce proteins for use in and outside the cell.',
        'They carry out cellular respiration to produce ATP for cell activities.',
        'They contain the DNA that controls all cell activities.',
        'They regulate what enters and exits the cell.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'Mitochondria are the primary sites of aerobic cellular respiration, where glucose is broken down and the energy released is used to synthesize ATP — the universal energy currency of cells.',
      diveDeep: 'Mitochondria are called the "powerhouses of the cell." They have a double membrane: a smooth outer membrane and a highly folded inner membrane (cristae) that increases surface area for the electron transport chain. The mitochondrial matrix (interior) contains enzymes for the Krebs cycle. Mitochondria have their own DNA (circular, like bacteria) and ribosomes, supporting the endosymbiotic theory — they evolved from ancient bacteria engulfed by early eukaryotic cells. Cells with high energy demands (heart muscle, liver, sperm cells) contain hundreds to thousands of mitochondria.',
    },
    {
      number: 12, part: 'A',
      text: 'The relationship between flowering plants and the bees that pollinate them is an example of',
      choices: [
        'parasitism — the bee benefits while the plant is harmed',
        'competition — both species compete for the same resources',
        'mutualism — both species benefit from the relationship',
        'commensalism — the bee benefits while the plant is unaffected',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Both the bee and the flowering plant benefit: the bee gains nectar and pollen as food, and the plant benefits from pollination (transfer of pollen enabling fertilization and seed production), making this a mutualistic relationship.',
      diveDeep: 'Plant–pollinator relationships are classic examples of co-evolution — both partners evolve in response to each other. Flower shapes, colors, and scents evolved to attract specific pollinators; pollinators evolved body shapes and behaviors to access flowers efficiently. Bees have pollen baskets (corbiculae) on their hind legs for collecting pollen, and many plants have evolved to be visited by specific bee species. The global importance of this mutualism cannot be overstated: approximately 75% of flowering plant species depend on animal pollinators, and pollinators support an estimated $235 billion in global food production annually.',
    },
    {
      number: 13, part: 'A',
      text: 'Which statement best explains why the offspring produced by sexual reproduction are genetically different from each parent?',
      choices: [
        'Sexual reproduction does not involve DNA; offspring develop new genetic information.',
        'The offspring receive a unique combination of alleles from both parents through gametes.',
        'Sexual reproduction causes mutations that produce new genetic information.',
        'Gametes from each parent contain the same genetic information.',
      ],
      topic: 'Genetics',
      correct: 1,
      explanation: 'During meiosis, crossing over and independent assortment create genetically unique gametes; fertilization combines one gamete from each parent, producing offspring with an allele combination unlike either parent.',
      diveDeep: 'Sexual reproduction generates genetic diversity through three mechanisms: (1) crossing over during prophase I (recombination between homologous chromosomes creates new allele combinations); (2) independent assortment during meiosis I (23 pairs of chromosomes sort independently, creating 2²³ ≈ 8 million possible gamete types in humans); (3) random fertilization (any sperm can fertilize any egg, producing approximately 70 trillion possible genotypes). This variation provides the raw material for natural selection and evolutionary adaptation. The evolutionary advantage of sexual reproduction — despite its energetic costs — is thought to be this generation of variation.',
    },
    {
      number: 14, part: 'A',
      text: 'When the concentration of glucose in the blood rises after a meal, the pancreas releases insulin. Insulin causes cells to take up glucose, lowering blood glucose levels. This is an example of',
      choices: [
        'active transport across the cell membrane',
        'a negative feedback mechanism that maintains homeostasis',
        'a positive feedback mechanism that amplifies the response',
        'the immune response to foreign substances in the blood',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'High blood glucose triggers insulin release, which causes cells to absorb glucose (lowering blood glucose) — this reversal of the deviation from normal is the defining characteristic of negative feedback maintaining homeostasis.',
      diveDeep: 'Blood glucose regulation is one of the most important homeostatic mechanisms in the body. After a meal, blood glucose rises → pancreatic beta cells secrete insulin → cells (especially liver, muscle, adipose) take up glucose → blood glucose falls back to normal → insulin secretion decreases. Glucagon (secreted by alpha cells) works oppositely: when blood glucose drops, glucagon stimulates glycogen breakdown in the liver, releasing glucose. Type 1 diabetes = beta cells destroyed (no insulin); Type 2 = cells become insulin-resistant. Both result in chronically high blood glucose (hyperglycemia) with serious complications.',
    },
    {
      number: 15, part: 'A',
      text: 'Two species of squirrels live in the same forest and eat the same types of nuts. These two species are most likely engaged in',
      choices: [
        'mutualism',
        'competition',
        'predation',
        'parasitism',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'When two species use the same limited resource (nuts) in the same habitat, they compete for it. This interspecific competition can reduce the fitness of both species.',
      diveDeep: 'Competition is a −/− interaction: both competing species are harmed by the presence of the other because they must share limited resources. Interspecific competition between similar species tends to drive niche differentiation over evolutionary time — a process called character displacement. The competitive exclusion principle (Gause\'s principle) states that two species with identical niches cannot coexist indefinitely; one will out-compete the other. Real species coexist by partitioning resources: for example, two squirrel species might use different parts of the tree, be active at different times, or prefer different nut sizes.',
    },
    {
      number: 16, part: 'A',
      text: 'In humans, the structure of red blood cells makes them well suited for carrying oxygen. Red blood cells lack a nucleus, giving them more room for hemoglobin. The shape and function of red blood cells is most directly determined by',
      choices: [
        'the oxygen level in the blood',
        'the activity of specific genes in red blood cell precursors',
        'the temperature of the blood',
        'the hormones produced by the kidneys',
      ],
      topic: 'Human Body',
      correct: 1,
      explanation: 'The structural features of red blood cells (biconcave shape, no nucleus, abundant hemoglobin) are determined by the genes expressed during their differentiation from stem cells in bone marrow — gene activity controls cell structure and function.',
      diveDeep: 'Red blood cell (RBC) development (erythropoiesis) occurs in red bone marrow. As precursor cells mature into RBCs, they progressively lose organelles, including the nucleus and mitochondria, which maximizes space for hemoglobin (~270 million molecules per RBC). The biconcave shape increases surface area-to-volume ratio for efficient O₂ exchange. The hormone erythropoietin (EPO), produced by the kidneys in response to low O₂, stimulates RBC production. Sickle-cell disease results from a single point mutation in the hemoglobin gene, altering the protein\'s shape under low O₂ conditions — a direct demonstration of how gene sequence determines cell function.',
    },
    {
      number: 17, part: 'A',
      text: 'What is the primary reason why the burning of fossil fuels is a concern for the environment?',
      choices: [
        'It depletes the supply of fossil fuels, which are needed for photosynthesis.',
        'It releases large amounts of carbon dioxide, contributing to the greenhouse effect.',
        'It produces oxygen that reacts with water to form acid rain.',
        'It cools the atmosphere by releasing heat from combustion.',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Burning fossil fuels releases CO₂ stored over millions of years back into the atmosphere rapidly, intensifying the greenhouse effect and driving global climate change.',
      diveDeep: 'Fossil fuels (coal, oil, natural gas) are the compressed, transformed remains of ancient organisms — stored solar energy in chemical form. Burning them releases CO₂ at a rate approximately 100 times faster than natural processes can absorb it. CO₂ is a greenhouse gas: it absorbs infrared radiation re-emitted from Earth\'s surface and re-emits it in all directions, trapping heat in the lower atmosphere (the greenhouse effect). Since industrialization, atmospheric CO₂ has risen from ~280 ppm to over 420 ppm, driving an average global temperature increase of approximately 1.2°C and disrupting climate patterns worldwide.',
    },
    {
      number: 18, part: 'A',
      text: 'The CRISPR/Cas9 system allows scientists to precisely edit genes in living organisms. This technology could be used to',
      choices: [
        'create organisms that are genetically identical to existing species',
        'correct genetic mutations that cause diseases',
        'increase the rate of natural selection in wild populations',
        'produce new species without the need for reproduction',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'CRISPR/Cas9 can precisely cut DNA at specific sequences, allowing scientists to delete, repair, or replace mutated gene sequences responsible for genetic diseases.',
      diveDeep: 'CRISPR/Cas9 uses a guide RNA (gRNA) to direct the Cas9 enzyme to a specific DNA sequence, where it makes a double-strand cut. The cell\'s own DNA repair machinery then repairs the cut — either by non-homologous end joining (NHEJ, which often disrupts the gene) or by homology-directed repair (HDR, which can insert a corrected sequence). Therapeutic applications include sickle-cell disease correction (clinical trials ongoing), inherited blindness treatment, and cancer immunotherapy (editing T cells to target tumors). Ethical concerns focus on germline editing (changes passed to future generations) and equity of access to these powerful technologies.',
    },
    {
      number: 19, part: 'A',
      text: 'Which situation would most likely lead to an increase in the biodiversity of an ecosystem?',
      choices: [
        'introduction of a predator that eliminates all competitors',
        'restoration of a wetland habitat that was previously drained for agriculture',
        'application of pesticides that kill all insects in the area',
        'planting of a single crop species in a previously wild area',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Restoring a wetland recreates diverse microhabitats that support a wide variety of species, directly increasing biodiversity. The other choices reduce biodiversity by eliminating species or simplifying habitats.',
      diveDeep: 'Wetlands are among the most ecologically productive and biodiverse ecosystems on Earth, supporting disproportionate numbers of species relative to their area. Restoration involves re-establishing hydrology (water flow patterns), replanting native vegetation, and allowing natural succession to proceed. Restored wetlands often recover significant biodiversity within a few years, though full recovery to pre-disturbance levels may take decades. The 1989 U.S. federal policy of "no net loss of wetlands" and efforts under the Clean Water Act recognize the critical ecological services provided by wetlands.',
    },
    {
      number: 20, part: 'A',
      text: 'A student compares two cells under a microscope. Cell A has a cell wall, large central vacuole, and chloroplasts. Cell B lacks these structures. Cell A is most likely from a',
      choices: [
        'bacterium',
        'plant',
        'fungus',
        'animal',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'The combination of a cellulose cell wall, large central vacuole (for turgor pressure), and chloroplasts (for photosynthesis) is unique to plant cells among eukaryotic cell types.',
      diveDeep: 'Cell type identification from structural features: Plant cells have a rigid cellulose cell wall, large central vacuole (occupying up to 90% of cell volume), and chloroplasts (in photosynthetic cells). Animal cells lack these but have centrioles and lysosomes. Fungal cells have cell walls made of chitin (not cellulose) but lack chloroplasts. Bacterial cells (prokaryotes) have cell walls (peptidoglycan) but lack membrane-bound organelles, a true nucleus, and the large central vacuole. Knowing these characteristic structures allows identification of cell type from micrograph images — a common Regents question type.',
    },
    {
      number: 21, part: 'A',
      text: 'The development of antibiotic resistance in bacteria is similar to the development of pesticide resistance in insects. Both examples illustrate that',
      choices: [
        'organisms can intentionally change their genetic makeup to survive threats',
        'natural selection acts on variation in populations to produce adapted individuals',
        'all organisms will eventually become resistant to any chemical used against them',
        'genetic engineering can rapidly produce resistant populations of organisms',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'In both cases, pre-existing random genetic variation in the population allowed some individuals to survive chemical exposure; these survivors reproduced, increasing the frequency of resistance alleles — this is natural selection in action.',
      diveDeep: 'Both antibiotic resistance and pesticide resistance are textbook examples of evolution by natural selection in real time. The parallel mechanisms: random mutations pre-exist in the population → chemical exposure selects for resistant individuals → resistant survivors reproduce → resistance alleles increase in frequency over generations. Neither bacteria nor insects "choose" to become resistant; the variation was already present. This is why rotating different classes of antibiotics or pesticides (before resistance to each becomes widespread) can slow resistance evolution — it reduces consistent directional selection pressure.',
    },
    {
      number: 22, part: 'A',
      text: 'Which process produces the most ATP for use in cell activities?',
      choices: [
        'photosynthesis',
        'fermentation',
        'aerobic cellular respiration',
        'transcription',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Aerobic cellular respiration produces approximately 36–38 ATP per glucose molecule through glycolysis, the Krebs cycle, and the electron transport chain — far more than the 2 ATP from fermentation or glycolysis alone.',
      diveDeep: 'ATP yield comparison: fermentation (anaerobic) = 2 ATP per glucose; aerobic respiration = ~36–38 ATP per glucose. The electron transport chain (ETC) accounts for most of this yield: NADH and FADH₂ from glycolysis and the Krebs cycle donate electrons to the ETC, driving proton pumping across the inner mitochondrial membrane. The resulting proton gradient drives ATP synthase (chemiosmosis), producing ~32–34 ATP. Photosynthesis produces ATP and NADPH used to fix CO₂, but net ATP production for cellular work is lower than from respiration. Transcription uses ATP but does not produce it.',
    },
    {
      number: 23, part: 'A',
      text: 'The human immune system responds to an infection by producing proteins that recognize and bind to specific molecules on the surface of pathogens. These proteins are called',
      choices: [
        'antigens',
        'antibodies',
        'hormones',
        'enzymes',
      ],
      topic: 'Human Body',
      correct: 1,
      explanation: 'Antibodies are Y-shaped proteins produced by B lymphocytes that bind specifically to antigens (foreign molecules) on pathogens, marking them for destruction by other immune cells.',
      diveDeep: 'The immune system\'s specificity comes from the variable regions of antibodies, which bind to specific antigen shapes (epitopes) with high affinity. Each B cell produces antibodies with a unique variable region; the immune system generates millions of different antibody types. When a B cell encounters its specific antigen, it proliferates and differentiates into plasma cells (antibody factories) and memory B cells (long-term immunity). Antigens are the foreign molecules that trigger the immune response; antibodies are the response. Vaccines work by exposing the immune system to antigens without causing disease, stimulating memory cell production.',
    },
    {
      number: 24, part: 'A',
      text: 'Which statement best describes the relationship between genes and traits?',
      choices: [
        'Each gene controls the expression of all traits in an organism.',
        'Genes provide instructions for making proteins that determine traits.',
        'Traits are passed to offspring through the environment, not through genes.',
        'All traits in an organism are determined by a single gene.',
      ],
      topic: 'Genetics',
      correct: 1,
      explanation: 'Genes encode proteins, and proteins (enzymes, structural proteins, signaling molecules) carry out cellular functions that produce observable traits. The path from gene to trait runs through protein synthesis.',
      diveDeep: 'The gene–protein–trait relationship is more complex than a simple one-to-one correspondence. Many traits are polygenic (controlled by multiple genes, e.g., height, skin color), and many genes are pleiotropic (one gene affects multiple traits, e.g., the gene causing sickle-cell disease also affects bone structure). Environmental factors modulate gene expression (epigenetics). Most traits are the result of complex interactions between many gene products and environmental influences. Understanding gene-trait relationships is fundamental to genetics, medicine (disease genes), and agriculture (crop improvement).',
    },
    {
      number: 25, part: 'A',
      text: 'The geographic isolation of a population can lead to speciation because',
      choices: [
        'isolated populations experience the same environmental pressures as the original population',
        'geographic barriers allow gene flow between isolated populations',
        'isolated populations accumulate different genetic changes over time, making interbreeding impossible',
        'geographic isolation increases the mutation rate in isolated populations',
      ],
      topic: 'Evolution',
      correct: 2,
      explanation: 'Geographic isolation prevents gene flow (exchange of alleles) between populations; each evolves independently under different selection pressures and by random genetic drift, accumulating genetic differences until they become reproductively incompatible — separate species.',
      diveDeep: 'Allopatric speciation (via geographic isolation) is the most common mode of speciation. The process requires: (1) physical barrier separates populations (mountain range, water body, desert); (2) gene flow ceases, allowing populations to diverge independently; (3) different selection pressures and/or genetic drift accumulate divergent changes; (4) reproductive isolating mechanisms evolve (different mating times, behaviors, gamete incompatibility); (5) if barriers are removed, populations no longer interbreed. Speciation time varies enormously — thousands to millions of years. Galápagos finches speciated in approximately 1–2 million years after colonizing isolated islands.',
    },
    {
      number: 26, part: 'A',
      text: 'Lichens are organisms composed of a fungus and a photosynthetic alga living in a close association. The alga provides the fungus with food through photosynthesis, and the fungus provides the alga with water and protection. This relationship is an example of',
      choices: [
        'parasitism',
        'mutualism',
        'competition',
        'predation',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Both the fungus and alga benefit from the association (alga gains protection and water; fungus gains photosynthetically produced food) — the definition of mutualism (+/+).',
      diveDeep: 'Lichens are a remarkable example of mutualism so intimate that the two organisms are considered a single entity. The fungal partner (mycobiont) forms most of the lichen body, providing structure, absorbing water and minerals, and protecting the alga from desiccation and UV radiation. The algal or cyanobacterial partner (photobiont) provides carbohydrates through photosynthesis. Some lichens also fix nitrogen (if the photobiont is a cyanobacterium). Lichens are pioneer species that colonize bare rock, contributing to soil formation. Their sensitivity to air pollution makes them useful bioindicators of air quality.',
    },
    {
      number: 27, part: 'A',
      text: 'Which activity would best help maintain biodiversity in a region?',
      choices: [
        'clearing forests and replacing them with a single crop plant',
        'draining wetlands to create farmland',
        'establishing wildlife corridors between fragmented habitats',
        'introducing invasive species to control pest populations',
      ],
      topic: 'Ecology',
      correct: 2,
      explanation: 'Wildlife corridors connect fragmented habitat patches, allowing animals to move between them, maintain gene flow between populations, and recover from local disturbances — all of which maintain biodiversity at the landscape level.',
      diveDeep: 'Habitat fragmentation — the breaking up of continuous habitat into isolated patches — is a major driver of biodiversity loss. Isolated populations in small patches face: reduced genetic diversity (inbreeding), local extinction from chance events (stochastic effects), inability to recolonize after disturbance, and reduced access to seasonal resources. Wildlife corridors (strips of habitat connecting patches) mitigate these effects by allowing movement and gene flow. Examples include the Yellowstone to Yukon conservation initiative and underpasses/overpasses built for wildlife crossing under highways. Conservation planning increasingly incorporates corridor design as a core strategy.',
    },
    {
      number: 28, part: 'A',
      text: 'In humans, type 1 diabetes is an autoimmune disease in which the immune system mistakenly destroys the insulin-producing cells of the pancreas. Which statement best explains why this is harmful?',
      choices: [
        'Without insulin, blood glucose levels cannot be regulated, leading to dangerously high blood sugar.',
        'Without insulin, the pancreas produces too much glucagon, causing blood sugar to drop too low.',
        'Without insulin, the body cannot absorb amino acids for protein synthesis.',
        'Without insulin, the liver cannot store glycogen, causing immediate energy loss.',
      ],
      topic: 'Human Body',
      correct: 0,
      explanation: 'Insulin is required for cells to take up glucose from the blood; without it, blood glucose accumulates to dangerously high levels (hyperglycemia), damaging blood vessels, nerves, and organs over time.',
      diveDeep: 'Type 1 diabetes results from autoimmune destruction of pancreatic beta cells, eliminating insulin production. Without insulin, glucose cannot enter most cells (muscle, liver, adipose) because they require insulin-dependent glucose transporters (GLUT4). Blood glucose rises to 300–500+ mg/dL (normal: 70–100 mg/dL). Cells are effectively starving despite high blood glucose, so they switch to metabolizing fats, producing ketone bodies. Accumulated ketones lower blood pH (diabetic ketoacidosis), a life-threatening emergency. Long-term hyperglycemia damages blood vessels (retinopathy → blindness, nephropathy → kidney failure, neuropathy → nerve damage). Treatment requires exogenous insulin replacement.',
    },
    {
      number: 29, part: 'A',
      text: 'A scientist discovers two species of birds that look very similar but do not interbreed with each other. Comparing the DNA sequences of these two species would be useful for',
      choices: [
        'determining how closely related the two species are',
        'predicting future evolutionary changes in each species',
        'showing that the two species evolved from completely different ancestors',
        'proving that the birds will eventually interbreed',
      ],
      topic: 'Evolution',
      correct: 0,
      explanation: 'DNA sequence comparisons reveal the degree of genetic similarity between species — more similar sequences indicate more recent common ancestry, while greater divergence indicates longer separation. This is the basis of molecular phylogenetics.',
      diveDeep: 'Molecular phylogenetics uses DNA, RNA, or protein sequence comparisons to reconstruct evolutionary relationships. The principle: species that share a more recent common ancestor will have more similar DNA sequences because they have had less time to accumulate mutations independently. Techniques include DNA hybridization, gene sequence alignments, and whole-genome comparisons. Molecular data has resolved many evolutionary relationships that morphology alone could not, and sometimes overturned traditional classifications. Cytochrome c, ribosomal RNA, and mitochondrial DNA are commonly used molecular markers for phylogenetic analysis.',
    },
    {
      number: 30, part: 'A',
      text: 'In photosynthesis, plants use carbon dioxide, water, and light energy to produce',
      choices: [
        'ATP and carbon dioxide',
        'glucose and oxygen',
        'nitrogen and glucose',
        'water and ATP',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'The overall equation for photosynthesis is: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ (glucose) + 6O₂. Glucose stores the captured light energy, and oxygen is released as a byproduct.',
      diveDeep: 'Photosynthesis has two stages: the light-dependent reactions (in the thylakoid membranes) split water using light energy, releasing O₂ and producing ATP and NADPH; the Calvin cycle (in the stroma) uses ATP and NADPH to fix CO₂ into glucose via the enzyme RuBisCO. The glucose produced is used for cellular energy (cellular respiration), structural compounds (cellulose), and storage (starch). The oxygen released is the source of essentially all atmospheric O₂. Earth\'s oxygen-rich atmosphere is entirely a product of billions of years of photosynthesis by cyanobacteria, algae, and plants.',
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A graph shows the population sizes of predator (lynx) and prey (snowshoe hare) species over a 90-year period. The graph shows regular cycles: when hare populations increase, lynx populations increase shortly after; when hare populations decline, lynx populations also decline.',
      text: 'Based on the graph, which statement best describes the relationship between the lynx and snowshoe hare populations?',
      choices: [
        'The lynx population drives changes in the hare population, with lynx increasing first.',
        'The hare population drives changes in the lynx population, with hares increasing first.',
        'Both populations increase and decrease at exactly the same time.',
        'The two populations are not related and change independently.',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2022/q31.png',
      explanation: 'The hare population peaks first, then the lynx population peaks shortly after — indicating that hare abundance drives lynx abundance (more food → more lynx reproduction), not the other way around.',
      diveDeep: 'The lynx–hare cycle is the most famous example of predator–prey population dynamics, documented using fur-trapping records from the Hudson\'s Bay Company since the 1840s. The ~10-year cycle results from: (1) hare population increases → more food for lynx → lynx population increases; (2) increased predation by more lynx → hare population declines; (3) less food → lynx population declines; (4) reduced predation → hare population recovers. Research has shown the cycle is not purely driven by predation — vegetation cycles (overgrazing leads to reduced food quality) and stress physiology also play roles, making this a more complex multi-factor interaction than simple Lotka–Volterra models.',
    },
    {
      number: 32, part: 'B-1',
      context: 'A graph shows regular cycles between lynx and snowshoe hare populations over 90 years.',
      text: 'According to the graph, what most likely happens to the lynx population when the hare population reaches its lowest point?',
      choices: [
        'The lynx population increases rapidly due to less competition for food.',
        'The lynx population begins to decline due to reduced food supply.',
        'The lynx population remains stable because lynx can switch to other prey.',
        'The lynx population is not affected because lynx are apex predators.',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-august-2022/q32.png',
      explanation: 'When hares reach their lowest numbers, lynx — which depend primarily on hares for food — suffer food scarcity, leading to decreased reproduction and increased mortality, causing the lynx population to decline.',
      diveDeep: 'This question tests graph interpretation and understanding of ecological cause-and-effect. The lynx population peak typically lags behind the hare peak by 1–2 years: as hares decline, lynx initially continue reproducing on the remaining hares, then food shortage catches up and lynx numbers fall. The lag time is a key feature of predator–prey models. Lynx specialization on snowshoe hares (~70–90% of diet) makes them particularly vulnerable to hare population crashes compared to more generalist predators that could switch to alternative prey.',
    },
    {
      number: 33, part: 'B-1',
      context: 'A diagram shows the human digestive system with labels on various organs.',
      text: 'In which organ does the majority of nutrient absorption occur?',
      choices: [
        'stomach',
        'large intestine',
        'small intestine',
        'esophagus',
      ],
      topic: 'Human Body',
      correct: 2,
      image: '/images/exams/le-august-2022/q33.png',
      explanation: 'The small intestine is the primary site of chemical digestion and nutrient absorption, with its villi and microvilli dramatically increasing surface area for absorbing amino acids, fatty acids, sugars, vitamins, and minerals.',
      diveDeep: 'The small intestine (approximately 6–7 meters long) is highly adapted for absorption through three structural adaptations that increase surface area 600-fold compared to a smooth tube: circular folds (plicae circulares), villi (finger-like projections of the intestinal lining), and microvilli (brush border on each epithelial cell). Each villus contains capillaries (for absorbing amino acids, sugars, water-soluble vitamins) and a lacteal (lymph vessel, for absorbing fats). Digestive enzymes from the pancreas and bile from the liver/gallbladder enter the small intestine to complete chemical digestion. The large intestine primarily absorbs water and electrolytes from undigested material.',
    },
    {
      number: 34, part: 'B-1',
      context: 'A diagram shows a DNA molecule being used as a template for mRNA synthesis, followed by the mRNA being used to produce a protein at a ribosome.',
      text: 'The process by which mRNA is produced from a DNA template is called',
      choices: [
        'translation',
        'replication',
        'transcription',
        'mutation',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-august-2022/q34.png',
      explanation: 'Transcription is the process of using a DNA template to synthesize a complementary mRNA molecule; the term comes from "transcribing" genetic information from DNA into RNA language.',
      diveDeep: 'The central dogma of molecular biology distinguishes three processes: replication (DNA → DNA, copying the genome for cell division), transcription (DNA → RNA, making an mRNA copy of a gene), and translation (RNA → Protein, reading the mRNA to assemble amino acids into a protein). A common mistake is confusing transcription and translation — remember: transcription = creating the mRNA transcript; translation = reading the mRNA to "translate" codons into amino acids. In eukaryotes, transcription occurs in the nucleus; translation occurs at ribosomes in the cytoplasm.',
    },
    {
      number: 35, part: 'B-1',
      text: 'A researcher wants to determine if a new fertilizer increases the growth rate of tomato plants. She grows 30 plants with the new fertilizer and 30 plants without. All other growing conditions are kept identical. After 8 weeks, she measures the height of each plant. What is the purpose of the 30 plants grown without fertilizer?',
      choices: [
        'They serve as the experimental group to test the effect of fertilizer.',
        'They serve as the control group to compare against the fertilizer group.',
        'They provide extra data that will be averaged with the fertilizer group.',
        'They are used to determine the optimal amount of fertilizer to use.',
      ],
      topic: 'Cell Biology',
      correct: 1,
      explanation: 'The plants without fertilizer are the control group — they represent the "normal" or baseline condition against which the effect of the fertilizer can be measured, allowing the researcher to determine if any growth difference is due to the fertilizer.',
      diveDeep: 'Experimental design requires a control group to isolate the effect of the independent variable (fertilizer). Without a control, any observed growth could be attributed to other factors (lighting, watering, soil quality, time of year). By keeping all conditions identical except for fertilizer application, the researcher can attribute any growth difference between groups to the fertilizer. Using 30 plants per group (rather than 1 or 2) increases the reliability of the results by reducing the effect of random individual variation. A larger sample size reduces the probability that observed differences are due to chance alone.',
    },
    {
      number: 36, part: 'B-1',
      text: 'A population of moths lives in an area where tree bark is light gray. Most moths are light gray and blend into the bark, while a few are dark. After industrial pollution turns the tree bark dark, which change in the moth population is most likely to occur over many generations?',
      choices: [
        'All light-colored moths will change their color to dark to survive.',
        'The frequency of dark-colored moths will increase as they are better camouflaged.',
        'The frequency of light-colored moths will increase as they are better camouflaged.',
        'No change will occur because moth color is not affected by the environment.',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'After bark darkens, dark moths are better camouflaged from predators; they survive and reproduce more successfully, increasing the frequency of the dark allele in the population over generations — directional natural selection.',
      diveDeep: 'This is the industrial melanism scenario, modeled after the famous peppered moth (Biston betularia) case in England. Before industrialization: light moths blended with lichen-covered bark; dark moths were rare (highly visible to bird predators). After soot from factories darkened bark and killed lichens: dark moths became better camouflaged; light moths became more visible and were preferentially eaten. By the 1950s, dark moths comprised up to 98% of some industrial populations. After the Clean Air Acts reduced pollution and bark lightened again, light moths recovered in frequency — one of the best documented examples of observable evolution in response to environmental change.',
    },
    {
      number: 37, part: 'B-1',
      context: 'A diagram shows a generalized cell with various organelles labeled A through E.',
      text: 'Which labeled organelle in the diagram is responsible for releasing energy from glucose molecules through cellular respiration?',
      choices: [
        'A — cell membrane',
        'B — nucleus',
        'C — mitochondria',
        'D — ribosome',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-august-2022/q37.png',
      explanation: 'Mitochondria are the sites of aerobic cellular respiration — they house the Krebs cycle enzymes in the matrix and the electron transport chain on the inner membrane, where most ATP is produced from glucose breakdown.',
      diveDeep: 'Mitochondrial structure is highly adapted for its function: the outer membrane is smooth and permeable to small molecules; the inner membrane is highly folded into cristae, greatly increasing the surface area available for the electron transport chain proteins and ATP synthase. Pyruvate (from glycolysis in the cytoplasm) enters the mitochondrial matrix and is oxidized in the Krebs cycle. NADH and FADH₂ donate electrons to the electron transport chain, generating a proton gradient that drives ATP synthase. This process (chemiosmosis) accounts for approximately 90% of ATP production in aerobic respiration.',
    },
    {
      number: 38, part: 'B-1',
      context: 'A diagram shows a generalized cell with various organelles labeled A through E.',
      text: 'In which labeled organelle does protein synthesis take place?',
      choices: [
        'A — cell membrane',
        'B — nucleus',
        'C — mitochondria',
        'D — ribosome',
      ],
      topic: 'Cell Biology',
      correct: 3,
      image: '/images/exams/le-august-2022/q38.png',
      explanation: 'Ribosomes are the molecular machines that carry out translation — reading mRNA codons and assembling amino acids into polypeptide chains, thereby synthesizing proteins.',
      diveDeep: 'Ribosomes are the site of protein synthesis in all cells, both prokaryotic and eukaryotic. Eukaryotic ribosomes (80S, composed of 40S + 60S subunits) are slightly larger than prokaryotic ones (70S, 30S + 50S) — a difference exploited by many antibiotics that specifically inhibit bacterial ribosomes without harming eukaryotic ones (e.g., streptomycin, erythromycin). Free ribosomes in the cytoplasm make proteins for use inside the cell; ribosomes bound to the rough ER make proteins destined for secretion or membrane insertion. Ribosomal RNA (rRNA) has catalytic activity — it is the actual enzyme (ribozyme) that forms peptide bonds, with proteins playing a structural and regulatory role.',
    },
    {
      number: 39, part: 'B-1',
      text: 'A student reads that a new species of beetle was discovered in a rainforest. The article states that scientists expect this beetle may be extinct before it is fully studied. The most likely reason for this concern is',
      choices: [
        'the beetle population is growing rapidly and competing with other species',
        'habitat destruction in rainforests is occurring faster than species can be catalogued',
        'the beetle is a parasitic species that will be eliminated by its host species',
        'all beetle species eventually go extinct because they cannot adapt to change',
      ],
      topic: 'Ecology',
      correct: 1,
      explanation: 'Rainforest destruction (primarily deforestation for agriculture and logging) occurs at rates far exceeding the pace at which scientists can discover and describe species, meaning many species go extinct before science even learns of their existence.',
      diveDeep: 'Tropical rainforests cover less than 7% of Earth\'s land surface but contain approximately 50–75% of all known species. Deforestation rates average several million hectares per year globally. Biologists estimate that 0.01–0.1% of all species go extinct every year (a rate 100–1000 times higher than the background extinction rate), with the vast majority being undescribed invertebrates and plants in tropical forests. This "biodiversity crisis" or "sixth mass extinction" is driven primarily by habitat loss, followed by invasive species, overexploitation, pollution, and climate change.',
    },
    {
      number: 40, part: 'B-1',
      context: 'A pedigree chart shows three generations of a family and the inheritance of a trait. In the chart, some individuals are shaded (affected) and others are not shaded (unaffected).',
      text: 'Based on the pedigree, if two unaffected parents have an affected child, the trait is most likely',
      choices: [
        'dominant, because both parents must have the trait to pass it on',
        'recessive, because both parents must carry the recessive allele without showing the trait',
        'sex-linked, because only males can be affected by the trait',
        'caused by a new mutation not inherited from either parent',
      ],
      topic: 'Genetics',
      correct: 1,
      explanation: 'When two unaffected (phenotypically normal) parents produce an affected child, it indicates both parents are carriers of a recessive allele (Aa × Aa → 1/4 aa affected offspring) — the defining pattern of autosomal recessive inheritance.',
      diveDeep: 'Pedigree analysis rules: (1) If unaffected parents produce an affected child → trait is recessive (parents are carriers). (2) If trait appears in every generation → likely dominant. (3) If trait appears more often in males, especially when inherited from carrier mothers → likely X-linked recessive. In the described scenario, unaffected parents (Aa) × (Aa) produce affected child (aa) with 25% probability per pregnancy. Classic autosomal recessive diseases include cystic fibrosis, sickle-cell disease, phenylketonuria (PKU), and Tay-Sachs disease. Carrier testing is important for couples with family histories of these conditions.',
    },
    {
      number: 41, part: 'B-1',
      text: 'Which process describes the movement of water molecules from an area of high water concentration to an area of low water concentration through a semipermeable membrane?',
      choices: [
        'active transport',
        'endocytosis',
        'osmosis',
        'facilitated diffusion',
      ],
      topic: 'Cell Biology',
      correct: 2,
      explanation: 'Osmosis is the specific term for the passive diffusion of water molecules through a selectively permeable membrane from a region of higher water concentration (lower solute concentration) to lower water concentration (higher solute concentration).',
      diveDeep: 'Osmosis is driven by water potential — water moves from regions of higher water potential (lower solute concentration, hypotonic) to lower water potential (higher solute concentration, hypertonic). In cells, osmosis determines cell volume: animal cells in hypertonic solution lose water and shrink (crenation); in hypotonic solution, they gain water and may lyse. Plant cells in hypotonic solution gain water, creating turgor pressure against the cell wall — this maintains plant rigidity. The concept of water potential is important in understanding transpiration in plants (water moving from soil through roots and out of leaves) and in medical contexts (IV fluid tonicity).',
    },
    {
      number: 42, part: 'B-1',
      text: 'In ecosystems, the total amount of energy available decreases at each trophic level. This means that',
      choices: [
        'producer populations must be larger than consumer populations',
        'carnivores always have more energy available than herbivores',
        'energy flows in a cycle through the ecosystem',
        'decomposers have access to more energy than producers',
      ],
      topic: 'Ecology',
      correct: 0,
      explanation: 'Because only ~10% of energy transfers to each successive trophic level, a much larger biomass of producers is needed to support any given biomass of consumers — producer populations are therefore always larger (in total biomass) than consumer populations.',
      diveDeep: 'Energy pyramids illustrate the quantitative relationships between trophic levels. A typical grassland ecosystem might have 10,000 kcal/m²/yr of plant productivity, supporting ~1,000 kcal of herbivores and ~100 kcal of carnivores. Energy does not cycle — unlike matter, which cycles through biogeochemical cycles (carbon cycle, nitrogen cycle, etc.), energy enters ecosystems as solar radiation, flows through the food web, and exits as heat. This is the second law of thermodynamics applied to ecology: energy is not lost, but it becomes unavailable for biological work (entropy increases) at each transfer.',
    },
    {
      number: 43, part: 'B-1',
      text: 'Scientists studying evolution often use the concept of homologous structures — body parts that have the same basic structure but are used for different functions in different species. Homologous structures are evidence of evolution because they suggest that',
      choices: [
        'all species have identical functions for all body parts',
        'different species with similar structures share a common ancestor',
        'structures that serve different functions cannot be related',
        'evolution always produces the same structures in different species',
      ],
      topic: 'Evolution',
      correct: 1,
      explanation: 'Homologous structures share the same underlying anatomy because they were inherited from a common ancestor — the structures were modified by evolution for different uses, but the basic plan reflects shared heritage.',
      diveDeep: 'Homologous structures provide anatomical evidence for evolution. The pentadactyl limb (five-digit limb) is homologous across all tetrapods — the same set of bones (humerus, radius, ulna, carpals, phalanges) is adapted for flying (bird), swimming (whale), running (horse), climbing (human hand), and digging (mole). Developmental biology confirms homology: all these limbs develop from the same embryonic tissue using the same Hox genes. Vestigial structures (like the human appendix or pelvic bones in whales) are degenerate homologous structures that have lost their original function. Molecular homology (similar DNA/protein sequences) provides additional evidence.',
    },
  ],
}
