// Living Environment Regents — June 2022
export default {
  id: 'le-june-2022',
  subject: 'living-environment',
  year: 2022,
  session: 'June',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'The cell membrane regulates what enters and exits the cell. Which statement best describes one function of the cell membrane?',
      choices: [
        'It synthesizes proteins needed for cell processes.',
        'It controls which substances move into and out of the cell.',
        'It stores the genetic information that controls cell activities.',
        'It produces ATP for all cell activities.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 2, part: 'A',
      text: 'A scientist studying a population of wolves in Yellowstone National Park found that when wolves were reintroduced, the elk population declined, vegetation grew back in river areas, and songbird populations increased. This best illustrates that',
      choices: [
        'top predators have no effect on the populations of other organisms',
        'the removal of one species from a food web can lead to ecosystem collapse',
        'predators play a key role in maintaining ecosystem stability',
        'elk are the most important species in Yellowstone\'s ecosystem',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 3, part: 'A',
      text: 'When a person receives a flu vaccination, they are injected with weakened or inactivated flu viruses. The purpose of the vaccine is to',
      choices: [
        'destroy all viruses that enter the body before they can cause disease',
        'stimulate the immune system to produce antibodies against the flu virus',
        'provide the body with antibodies produced by another person',
        'prevent the flu virus from entering the body in the future',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 4, part: 'A',
      text: 'The process by which plants convert light energy into chemical energy stored in glucose is',
      choices: [
        'cellular respiration',
        'fermentation',
        'photosynthesis',
        'transpiration',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 5, part: 'A',
      text: 'In sexually reproducing organisms, offspring receive half of their genetic information from each parent. This is made possible by',
      choices: [
        'mitosis producing cells with the same number of chromosomes as the parent cell',
        'meiosis producing gametes with half the chromosome number of the parent cell',
        'the random mutation of chromosomes during cell division',
        'crossing over during mitosis, which produces genetic variation',
      ],
      topic: 'Reproduction',
      correct: 1,
    },
    {
      number: 6, part: 'A',
      text: 'In tropical rainforests, many different species of plants and animals live in close proximity. The high biodiversity of these ecosystems is important because',
      choices: [
        'more species means more competition, which reduces population sizes',
        'high biodiversity increases the stability and resilience of the ecosystem',
        'biodiversity causes ecosystems to be more vulnerable to disease',
        'all species must live in the same habitat to ensure survival',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 7, part: 'A',
      text: 'Which statement correctly describes the relationship between DNA and proteins?',
      choices: [
        'Proteins are used as a template to make DNA molecules.',
        'DNA contains the coded instructions for the production of proteins.',
        'Proteins carry the genetic information that is passed from parents to offspring.',
        'DNA is produced as a result of protein synthesis.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 8, part: 'A',
      text: 'A trait controlled by a dominant allele will be expressed in an individual who is',
      choices: [
        'homozygous recessive only',
        'homozygous dominant only',
        'either homozygous dominant or heterozygous',
        'heterozygous only',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 9, part: 'A',
      text: 'The beak shapes of Darwin\'s finches are different on different Galápagos Islands. This diversity of beak shapes is best explained by',
      choices: [
        'the finches intentionally changed their beak shapes to find food',
        'natural selection favoring different beak shapes on islands with different food sources',
        'each island having a different chemical composition that altered the finches\' DNA',
        'all finches originally had the same beak shape but moved to different islands',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 10, part: 'A',
      text: 'In humans, the nervous system and the endocrine system both function to',
      choices: [
        'produce gametes for sexual reproduction',
        'coordinate and regulate body activities',
        'break down food molecules for use by cells',
        'remove waste products from the bloodstream',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 11, part: 'A',
      text: 'A change in the base sequence of DNA that results in the production of a different amino acid in a protein is called a',
      choices: [
        'mutation',
        'replication',
        'transcription',
        'translation',
      ],
      topic: 'Cell Biology',
      correct: 0,
    },
    {
      number: 12, part: 'A',
      text: 'The process of ecological succession describes how',
      choices: [
        'organisms compete for food in a stable ecosystem',
        'one community of organisms gradually replaces another over time',
        'predators regulate the population sizes of prey species',
        'nutrients cycle through the biotic and abiotic components of an ecosystem',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 13, part: 'A',
      text: 'Which statement best describes what occurs during mitosis?',
      choices: [
        'One cell divides to form four genetically different daughter cells.',
        'One cell divides to form two genetically identical daughter cells.',
        'Two cells fuse to form one cell with twice the genetic information.',
        'Chromosomes are reduced to half the normal number to form gametes.',
      ],
      topic: 'Reproduction',
      correct: 1,
    },
    {
      number: 14, part: 'A',
      text: 'An enzyme speeds up a chemical reaction by',
      choices: [
        'providing energy for the reaction',
        'lowering the activation energy needed for the reaction to occur',
        'changing the products of the reaction into reactants',
        'increasing the temperature of the reaction environment',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 15, part: 'A',
      text: 'Homeostasis in an organism refers to the ability to',
      choices: [
        'reproduce rapidly when resources are abundant',
        'maintain a stable internal environment despite external changes',
        'evolve rapidly in response to environmental pressures',
        'produce offspring that are genetically identical to the parent',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 16, part: 'A',
      text: 'When humans clear forests for agriculture, they often cause soil erosion. This is because',
      choices: [
        'agricultural crops produce chemicals that break down soil',
        'tree roots hold soil in place, and removing trees allows soil to wash away',
        'agriculture increases the amount of carbon dioxide in the atmosphere',
        'clearing forests eliminates decomposers that maintain soil fertility',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 17, part: 'A',
      text: 'The transfer of genetic information from parent to offspring through gametes is the basis of',
      choices: [
        'ecological succession',
        'heredity',
        'homeostasis',
        'natural selection',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 18, part: 'A',
      text: 'In a marine ecosystem, phytoplankton form the base of most food chains. If a pollutant killed most of the phytoplankton, the most likely consequence would be',
      choices: [
        'an increase in the populations of all marine animals',
        'a rapid recovery of phytoplankton due to increased nutrients',
        'a collapse of most food chains and a decrease in all marine animal populations',
        'no significant effect because marine animals can use other food sources',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 19, part: 'A',
      text: 'Cloning produces offspring that are genetically identical to the parent organism. One potential risk of cloning many individuals of the same species is that',
      choices: [
        'cloned individuals live longer than naturally born individuals',
        'all cloned individuals would be susceptible to the same diseases',
        'cloned individuals cannot reproduce sexually',
        'cloning always produces offspring with harmful mutations',
      ],
      topic: 'Reproduction',
      correct: 1,
    },
    {
      number: 20, part: 'A',
      text: 'Scientists have compared the bone structures of the front limbs of humans, cats, whales, and bats. These similarities suggest that',
      choices: [
        'these organisms perform the same functions with their front limbs',
        'these organisms share a common ancestor',
        'these organisms evolved completely independently',
        'the similarities are due to similar environments, not common ancestry',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 21, part: 'A',
      text: 'In the carbon cycle, cellular respiration and decomposition both contribute to the cycle by',
      choices: [
        'removing carbon dioxide from the atmosphere',
        'releasing carbon dioxide into the atmosphere',
        'converting carbon dioxide into organic compounds',
        'storing carbon in long-term deposits in the soil',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 22, part: 'A',
      text: 'Which situation would provide evidence that a behavior in an organism is instinctive rather than learned?',
      choices: [
        'A dog performs a trick after receiving training from its owner.',
        'A newborn bird performs a complex nest-building behavior without prior experience.',
        'A rat learns to navigate a maze through trial and error.',
        'A chimpanzee learns to use tools by observing other chimpanzees.',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 23, part: 'A',
      text: 'Which statement best describes the role of decomposers in an ecosystem?',
      choices: [
        'They produce organic compounds from inorganic molecules using sunlight.',
        'They break down dead organisms and return nutrients to the environment.',
        'They consume producers and transfer energy to higher trophic levels.',
        'They convert atmospheric nitrogen into a form usable by plants.',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 24, part: 'A',
      text: 'Which organelle is found in plant cells but not in animal cells?',
      choices: [
        'mitochondria',
        'nucleus',
        'chloroplast',
        'ribosome',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 25, part: 'A',
      text: 'Genetic engineering has been used to insert a human insulin gene into bacteria. This application of genetic engineering is beneficial because it',
      choices: [
        'produces insulin that is chemically different from human insulin',
        'allows for the large-scale production of human insulin without harvesting it from humans',
        'eliminates the need for insulin in diabetic patients',
        'permanently cures all forms of diabetes by correcting the genetic defect',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 26, part: 'A',
      text: 'A population of white rabbits is introduced onto an island where the ground is dark brown. Hawks on the island eat rabbits. Over several generations, brown-furred rabbits become more common. This change is an example of',
      choices: [
        'genetic engineering',
        'selective breeding by humans',
        'natural selection',
        'Lamarckian inheritance',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 27, part: 'A',
      text: 'The kidneys play an important role in homeostasis by',
      choices: [
        'producing hormones that regulate blood sugar levels',
        'filtering blood and removing waste products',
        'producing antibodies to fight infection',
        'breaking down food into nutrients for absorption',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 28, part: 'A',
      text: 'Organisms that produce their own food from inorganic substances using light or chemical energy are called',
      choices: [
        'heterotrophs',
        'decomposers',
        'autotrophs',
        'consumers',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 29, part: 'A',
      text: 'A scientist discovers a new organism at a deep ocean vent that obtains energy from chemical reactions involving hydrogen sulfide, not from sunlight. This organism is best classified as',
      choices: [
        'a heterotroph that feeds on dead organisms',
        'an autotroph that uses chemical energy',
        'a parasite that lives off a host organism',
        'a decomposer that breaks down organic matter',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 30, part: 'A',
      text: 'An invasive species introduced into a new ecosystem often causes problems because the invasive species',
      choices: [
        'always carries diseases that infect native species',
        'typically lacks natural predators in the new ecosystem and may outcompete native species',
        'cannot survive outside of its native ecosystem',
        'immediately forms mutualistic relationships with native species',
      ],
      topic: 'Ecology',
      correct: 1,
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'Scientists studied the effects of ocean acidification on the development of sea urchin larvae. They raised sea urchin larvae in water at pH 8.1 (normal), pH 7.9 (slightly acidic), and pH 7.7 (more acidic). They measured the length of the skeletal rods of the larvae after 48 hours.',
      text: 'Based on this experimental setup, what is the independent variable?',
      choices: [
        'the length of the skeletal rods of the larvae',
        'the pH level of the ocean water',
        'the species of sea urchin used in the experiment',
        'the 48-hour time period for the experiment',
      ],
      topic: 'General Review',
      correct: 1,
    },
    {
      number: 32, part: 'B-1',
      context: 'Scientists studied the effects of ocean acidification on sea urchin larvae. Results showed that larvae in pH 7.7 water had significantly shorter skeletal rods than those in pH 8.1 water.',
      text: 'Based on these results, which conclusion is most valid?',
      choices: [
        'Ocean acidification has no effect on the development of sea urchin larvae.',
        'Ocean acidification negatively affects the development of sea urchin skeletal structures.',
        'Sea urchins cannot survive in ocean water with a pH below 8.0.',
        'Skeletal rod length is determined solely by the genetic makeup of the sea urchin.',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 33, part: 'B-1',
      context: 'A graph shows the growth of a bacterial population over time. Initially the population grows slowly, then very rapidly, then levels off at a maximum size.',
      text: 'Based on the graph, at which point in time is the bacterial population growing at the fastest rate?',
      choices: [
        'at the beginning, when the population is very small',
        'in the middle, during the period of rapid, exponential growth',
        'at the end, when the population has reached its maximum size',
        'growth is constant throughout the entire period shown',
      ],
      topic: 'Ecology',
      correct: 1,
      image: '/images/exams/le-june-2022/q33.png',
    },
    {
      number: 34, part: 'B-1',
      context: 'A diagram shows the levels of hormones during the human female reproductive cycle over 28 days. Hormone A peaks around day 14, and Hormone B rises after day 14.',
      text: 'Based on the hormone diagram, which statement correctly describes the relationship between Hormone A and ovulation?',
      choices: [
        'Hormone A prevents ovulation by blocking egg development.',
        'The peak of Hormone A corresponds with the release of an egg (ovulation).',
        'Hormone A is only produced after ovulation has occurred.',
        'Hormone A remains at a constant level throughout the reproductive cycle.',
      ],
      topic: 'Reproduction',
      correct: 1,
      image: '/images/exams/le-june-2022/q34.png',
    },
    {
      number: 35, part: 'B-1',
      text: 'A student tested whether vitamin C affects the rate of growth of yeast. She added different amounts of vitamin C to test tubes with yeast and sugar water and measured gas produced. Which aspect of this experiment is the dependent variable?',
      choices: [
        'the amount of yeast in each test tube',
        'the amount of vitamin C added to each tube',
        'the amount of gas produced by the yeast',
        'the temperature at which the experiment was conducted',
      ],
      topic: 'General Review',
      correct: 2,
    },
    {
      number: 36, part: 'B-1',
      text: 'In areas of Africa where malaria is common, individuals who carry one copy of the sickle cell allele have a survival advantage because',
      choices: [
        'carriers cannot contract malaria under any circumstances',
        'carriers produce twice as much normal hemoglobin as non-carriers',
        'the sickle cell allele provides some protection against malaria while not causing severe anemia',
        'all individuals in malaria-affected areas eventually develop resistance to the disease',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 37, part: 'B-1',
      context: 'A diagram shows a DNA double helix being separated into two single strands, each of which serves as a template for a new strand. The result is two identical DNA double helices.',
      text: 'The process shown in the diagram is called DNA replication. This process is important because it ensures that',
      choices: [
        'mutations are corrected before cell division occurs',
        'each daughter cell receives a complete copy of the genetic information',
        'new genetic information is created for each cell generation',
        'the number of chromosomes is reduced during cell division',
      ],
      topic: 'Cell Biology',
      correct: 1,
      image: '/images/exams/le-june-2022/q37.png',
    },
    {
      number: 38, part: 'B-1',
      context: 'A chart compares the amino acid sequences of a specific protein in five different species. Species A and B share 98% of the same amino acids, while Species C shares only 60% with Species A.',
      text: 'Based on the amino acid sequence data, which conclusion is best supported?',
      choices: [
        'Species A and C are more closely related than Species A and B.',
        'Species A and B are more closely related to each other than either is to Species C.',
        'All five species evolved from the same ancestor at the same time.',
        'Amino acid sequences are not a reliable indicator of evolutionary relationships.',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 39, part: 'B-1',
      text: 'Many organisms that live in cold environments have a higher proportion of unsaturated fats in their cell membranes than organisms in warm environments. This adaptation most likely helps because unsaturated fats',
      choices: [
        'provide more energy per molecule than saturated fats',
        'remain fluid at lower temperatures, maintaining membrane flexibility',
        'are more easily broken down for cellular respiration in cold conditions',
        'are produced more efficiently in cold environments',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 40, part: 'B-1',
      context: 'A data table shows the number of bird species observed in four different forest habitats: Habitat A (old-growth forest) 47 species, Habitat B (managed forest) 23 species, Habitat C (clear-cut forest) 8 species, Habitat D (young regrowth forest) 19 species.',
      text: 'Based on the data in the table, which habitat has the greatest biodiversity?',
      choices: [
        'Habitat B',
        'Habitat C',
        'Habitat D',
        'Habitat A',
      ],
      topic: 'Ecology',
      correct: 3,
    },
    {
      number: 41, part: 'B-1',
      text: 'A student wants to observe cells dividing. Which type of tissue would be the best choice to observe mitosis?',
      choices: [
        'leaf cells from a mature tree',
        'root tip cells from a growing onion plant',
        'muscle cells from an adult frog',
        'red blood cells from a human',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 42, part: 'B-1',
      text: 'Which human activity contributes most directly to the greenhouse effect and global climate change?',
      choices: [
        'recycling paper and plastic products',
        'using public transportation instead of driving',
        'burning fossil fuels for energy',
        'planting trees in urban areas',
      ],
      topic: 'Ecology',
      correct: 2,
    },
    {
      number: 43, part: 'B-1',
      text: 'A population of white rabbits is introduced onto an island where the ground is dark brown. Over several generations, brown-furred rabbits become more common. Which explanation best accounts for this change?',
      choices: [
        'White rabbits became aware they were visible on dark ground and started producing brown offspring.',
        'All white rabbits developed brown fur due to exposure to the brown soil over their lifetimes.',
        'Hawks preferentially hunted white rabbits because they were more visible, so brown rabbits survived and reproduced more.',
        'Brown rabbits migrated from another island and outcompeted the white rabbits.',
      ],
      topic: 'Genetics',
      correct: 2,
    },
  ],
}
