// Living Environment Regents — June 2019
export default {
  id: 'le-june-2019',
  subject: 'living-environment',
  year: 2019,
  session: 'June',
  totalMinutes: 85,
  questions: [
    // Part A
    {
      number: 1, part: 'A',
      text: 'The human genome contains approximately 20,000 to 25,000 genes. These genes are composed of segments of',
      choices: [
        'amino acids that code for specific proteins',
        'carbohydrates that regulate cell metabolism',
        'DNA that code for specific traits',
        'ribosomes that produce proteins',
      ],
      topic: 'General',
      correct: 2,
    },
    {
      number: 2, part: 'A',
      text: 'The body maintains stable internal conditions, such as temperature and blood glucose levels, through a process called',
      choices: [
        'evolution',
        'ecological succession',
        'homeostasis',
        'differentiation',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 3, part: 'A',
      text: 'Which statement correctly identifies the role of decomposers in an ecosystem?',
      choices: [
        'They convert light energy into chemical energy through photosynthesis.',
        'They break down organic matter and return nutrients to the environment.',
        'They consume producers and transfer energy to higher trophic levels.',
        'They regulate the size of predator populations through competition.',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 4, part: 'A',
      text: 'Scientists have discovered that some bacteria can transfer genetic material to other bacteria of the same species. This mechanism can contribute to the rapid spread of antibiotic resistance because',
      choices: [
        'bacteria that receive the genetic material can immediately develop new mutations',
        'the transferred genetic material can include genes for antibiotic resistance',
        'the receiving bacteria become more likely to encounter antibiotic drugs',
        'the transfer of genetic material always results in more harmful bacteria',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 5, part: 'A',
      text: 'The disappearance of an entire species is called extinction. Which factor is most responsible for the current high rate of species extinction worldwide?',
      choices: [
        'volcanic eruptions and other natural disasters',
        'mutations that reduce fitness in wild populations',
        'habitat destruction caused by human activities',
        'competition between closely related species',
      ],
      topic: 'Evolution',
      correct: 2,
    },
    {
      number: 6, part: 'A',
      text: 'In a meadow ecosystem, the energy available at each trophic level decreases from producers to top predators. This is because',
      choices: [
        'energy is lost as heat during cellular respiration at each trophic level',
        'predators convert more energy to biomass than producers',
        'energy flows in a cycle and some returns to producers',
        'each organism at a higher trophic level requires less energy to survive',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 7, part: 'A',
      text: 'Scientists have observed that new species often arise when a population becomes geographically isolated from the rest of the species. Which explanation best accounts for this observation?',
      choices: [
        'Geographic isolation prevents organisms from obtaining enough food and water to survive.',
        'Isolated populations experience different environmental pressures and accumulate different genetic changes over time.',
        'Geographic barriers prevent mutations from occurring in isolated populations.',
        'Isolated populations always interbreed with neighboring species.',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 8, part: 'A',
      text: 'Which process produces four genetically unique cells from one parent cell?',
      choices: [
        'mitosis',
        'meiosis',
        'cellular respiration',
        'transcription',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 9, part: 'A',
      text: 'A blood test reveals that a patient\'s immune system is attacking healthy cells in the pancreas, destroying the cells that produce insulin. This is an example of',
      choices: [
        'a viral infection that causes cells to malfunction',
        'an autoimmune disorder in which the immune system attacks the body\'s own cells',
        'the normal immune response to a bacterial infection',
        'a genetic disorder caused by a mutation in the insulin gene',
      ],
      topic: 'Human Body',
      correct: 1,
    },
    {
      number: 10, part: 'A',
      text: 'Which statement best explains why evolution occurs in populations rather than in individual organisms?',
      choices: [
        'Individuals can change their traits during their lifetime to become more adapted.',
        'Evolution requires the passing of genetic changes to offspring over many generations.',
        'Individual organisms are too small for natural selection to act upon.',
        'Evolution only occurs in large populations with many competing species.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 11, part: 'A',
      text: 'Photosynthesis occurs in the chloroplasts of plant cells. Which substances are used as raw materials in photosynthesis?',
      choices: [
        'glucose and oxygen',
        'carbon dioxide and water',
        'ATP and carbon dioxide',
        'oxygen and water',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 12, part: 'A',
      text: 'A group of scientists studying an ecosystem in Africa found that when lions were present, the wildebeest population moved frequently and did not overgraze any single area. When lions were removed, wildebeest grazed in the same areas, causing the vegetation to decline. This illustrates that',
      choices: [
        'lions are the only species that can prevent overgrazing',
        'top predators can indirectly affect plant communities through their influence on prey behavior',
        'wildebeest are the most important species in the African ecosystem',
        'removing predators always improves ecosystem productivity',
      ],
      topic: 'Ecology',
      correct: 1,
    },
    {
      number: 13, part: 'A',
      text: 'An organism\'s phenotype is determined by',
      choices: [
        'its genotype alone',
        'its environment alone',
        'both its genotype and its environment',
        'random chance, with no influence from genetics or environment',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 14, part: 'A',
      text: 'Which statement best describes a characteristic of all living organisms?',
      choices: [
        'They all have cells with a nucleus.',
        'They all reproduce sexually.',
        'They all carry out metabolic processes to obtain and use energy.',
        'They all contain chlorophyll for photosynthesis.',
      ],
      topic: 'Cell Biology',
      correct: 2,
    },
    {
      number: 15, part: 'A',
      text: 'The tundra biome has very low biodiversity compared to a tropical rainforest. The primary reason for this is that',
      choices: [
        'tundra ecosystems have been destroyed by human activities',
        'the harsh climate of the tundra limits the number of species that can survive there',
        'tundra organisms are too competitive to allow other species to thrive',
        'tundra ecosystems lack the abiotic factors needed for most organisms',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 16, part: 'A',
      text: 'Gene therapy involves inserting functional genes into cells to treat genetic diseases. Which technique is most likely used to insert new genes into cells?',
      choices: [
        'selective breeding — mating individuals with the desired trait',
        'recombinant DNA technology — using vectors to deliver new genes into cells',
        'cloning — producing genetically identical individuals',
        'karyotyping — examining chromosomes to identify genetic disorders',
      ],
      topic: 'Genetics',
      correct: 1,
    },
    {
      number: 17, part: 'A',
      text: 'Which statement best describes the concept of biological evolution?',
      choices: [
        'Individual organisms change their traits during their lifetime to become better adapted.',
        'Populations accumulate genetic changes over many generations, sometimes leading to new species.',
        'Evolution is directed toward producing more complex or more intelligent organisms.',
        'Evolution always produces organisms that are better adapted to their environment.',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 18, part: 'A',
      text: 'An invasive species can disrupt an ecosystem because it often',
      choices: [
        'provides new food sources that support more predators in the ecosystem',
        'lacks natural predators in the new environment and may outcompete native species',
        'reduces the carrying capacity of the ecosystem for all organisms',
        'interbreeds with native species, causing a loss of genetic diversity',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 19, part: 'A',
      text: 'In photosynthesis, plants use carbon dioxide, water, and light energy to produce glucose and oxygen. In cellular respiration, organisms use glucose and oxygen to produce carbon dioxide, water, and ATP. Which statement describes the relationship between these two processes?',
      choices: [
        'They are unrelated processes that occur in different organisms.',
        'The products of photosynthesis are the reactants of cellular respiration, and vice versa.',
        'Both processes produce ATP and release carbon dioxide.',
        'Photosynthesis occurs in all cells, while cellular respiration occurs only in plant cells.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 20, part: 'A',
      text: 'The rate of deforestation in tropical regions is a major environmental concern. Which consequence of deforestation would most directly affect the global climate?',
      choices: [
        'decreased soil erosion in deforested areas',
        'increased absorption of carbon dioxide from the atmosphere',
        'increased release of carbon dioxide stored in trees',
        'decreased habitat for soil-dwelling organisms',
      ],
      topic: 'Genetics',
      correct: 2,
    },
    {
      number: 21, part: 'A',
      text: 'Which statement about cancer is correct?',
      choices: [
        'Cancer results from uncontrolled cell division caused by mutations in genes that regulate the cell cycle.',
        'Cancer is caused exclusively by viral infections that alter cell function.',
        'Cancer is always inherited and passed from parent to offspring.',
        'Cancer results from the failure of cells to undergo mitosis.',
      ],
      topic: 'General',
      correct: 0,
    },
    {
      number: 22, part: 'A',
      text: 'A new species of plant is discovered. Scientists find that it can survive in both full sun and deep shade by adjusting the number and size of its chloroplasts. This ability to adjust to different environmental conditions is an example of',
      choices: [
        'natural selection',
        'phenotypic plasticity',
        'genetic mutation',
        'ecological succession',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 23, part: 'A',
      text: 'Which pair of organisms has a mutualistic relationship?',
      choices: [
        'a tapeworm living in a dog\'s intestine, feeding on digested food',
        'clownfish living among the stinging tentacles of a sea anemone, both benefiting from the relationship',
        'a hawk hunting and eating field mice',
        'two species of birds competing for nesting sites in the same tree',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 24, part: 'A',
      text: 'In an experiment, students tested the effect of temperature on the rate of enzyme activity. At 37°C, the enzyme was most active. At 60°C, the enzyme had no activity. The loss of enzyme activity at 60°C most likely occurred because',
      choices: [
        'the enzyme was destroyed by the heat and completely removed from the solution',
        'the high temperature caused the enzyme\'s shape to change, preventing it from binding to its substrate',
        'the high temperature caused the substrate to be destroyed, leaving no molecules for the enzyme to act on',
        'the enzyme used up all of its activation energy and could no longer function',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 25, part: 'A',
      text: 'A student wants to demonstrate that plants release oxygen during photosynthesis. Which experimental setup would best allow the student to observe this?',
      choices: [
        'Place a plant in a dark room and measure the amount of CO₂ in the air.',
        'Place an aquatic plant in bright light and collect and measure the oxygen bubbles it produces.',
        'Measure the temperature of soil around plants at different times of day.',
        'Observe the height of plants grown in different light conditions over 4 weeks.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 26, part: 'A',
      text: 'Many species of plants in the Amazon rainforest have never been studied by scientists. The rapid deforestation of the Amazon is concerning because',
      choices: [
        'scientists will run out of subjects to study',
        'undiscovered species may contain compounds useful for medicines that will be lost forever',
        'the plants are needed to provide oxygen only for people living near the Amazon',
        'deforestation increases the number of plant species by exposing more soil',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 27, part: 'A',
      text: 'Epigenetics is the study of heritable changes in gene expression that do not involve changes to the DNA sequence. Epigenetic changes can be caused by environmental factors such as diet, stress, and toxins. Which statement best summarizes the significance of epigenetics?',
      choices: [
        'The environment has no effect on how genes are expressed.',
        'Environmental factors can alter gene expression in ways that may be passed to offspring.',
        'All traits are determined solely by the DNA sequence in genes.',
        'Epigenetic changes always improve an organism\'s ability to survive.',
      ],
      topic: 'Cell Biology',
      correct: 1,
    },
    {
      number: 28, part: 'A',
      text: 'The human digestive system breaks down large food molecules into smaller molecules that can be absorbed into the bloodstream. Which sequence correctly represents the pathway of a glucose molecule from a piece of bread to a muscle cell?',
      choices: [
        'mouth → stomach → small intestine → bloodstream → muscle cell',
        'mouth → large intestine → small intestine → bloodstream → muscle cell',
        'mouth → stomach → large intestine → bloodstream → muscle cell',
        'mouth → small intestine → stomach → bloodstream → muscle cell',
      ],
      topic: 'Cell Biology',
      correct: 0,
    },
    {
      number: 29, part: 'A',
      text: 'Scientists have found that some species of bats carry viruses that can be transmitted to humans and cause serious diseases. This is an example of',
      choices: [
        'a mutualistic relationship between bats and humans',
        'a zoonotic disease — a disease that can spread from animals to humans',
        'an autoimmune disorder caused by bat viruses',
        'a genetic mutation that makes humans susceptible to bat viruses',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 30, part: 'A',
      text: 'Which statement about the fossil record as evidence for evolution is correct?',
      choices: [
        'The fossil record shows that all species have existed unchanged since the beginning of life on Earth.',
        'The fossil record provides evidence that species have changed over time and that many species have gone extinct.',
        'The fossil record is an unreliable source of evidence because it contains many errors.',
        'The fossil record shows that evolution always produces more complex organisms over time.',
      ],
      topic: 'Evolution',
      correct: 1,
    },

    // Part B-1
    {
      number: 31, part: 'B-1',
      context: 'A diagram shows the results of gel electrophoresis comparing the DNA fragments of three different species of finches. The pattern of bands shows that Species A and B have many bands in common, while Species C has a very different band pattern from both A and B.',
      text: 'Based on the gel electrophoresis results, which conclusion about these three finch species is best supported?',
      choices: [
        'Species A and C are more closely related than Species A and B.',
        'Species A and B are more closely related to each other than either is to Species C.',
        'All three species are equally related to each other.',
        'The gel electrophoresis results cannot be used to determine evolutionary relationships.',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-june-2019/q31.png',
    },
    {
      number: 32, part: 'B-1',
      context: 'A diagram shows gel electrophoresis results for three finch species. Species A and B share many DNA fragments, while Species C has a distinct pattern.',
      text: 'The similarity in DNA fragments between Species A and B most likely indicates that they',
      choices: [
        'live in the same habitat and therefore have developed the same traits',
        'are more closely related and share a more recent common ancestor',
        'produce the same proteins for the same functions',
        'cannot interbreed due to their different band patterns',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-june-2019/q32.png',
    },
    {
      number: 33, part: 'B-1',
      context: 'A bar graph shows the average beak depth (in mm) of medium ground finches in the Galápagos Islands in 1976 and 1977. In 1977, a drought occurred that killed most small, soft seeds and left mainly large, hard seeds. The 1977 bars show beaks that are significantly deeper than in 1976.',
      text: 'Based on the bar graph, what most likely happened to the medium ground finch population during the 1977 drought?',
      choices: [
        'All finches with small beaks developed larger beaks to crack the hard seeds.',
        'Finches with larger, deeper beaks were better able to crack hard seeds and were more likely to survive.',
        'The drought caused mutations that increased beak depth in all finches.',
        'Finches migrated from other islands, bringing larger beaks to the population.',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-june-2019/q33.png',
    },
    {
      number: 34, part: 'B-1',
      context: 'A bar graph shows average beak depth of Galápagos finches in 1976 and 1977, following a drought. Beak depth increased significantly in 1977.',
      text: 'The change in average beak depth observed between 1976 and 1977 is an example of',
      choices: [
        'artificial selection by humans who removed finches with small beaks',
        'natural selection favoring finches with deeper beaks during the drought',
        'a genetic mutation that increased beak depth in all surviving finches',
        'phenotypic plasticity — all surviving finches grew deeper beaks during the drought',
      ],
      topic: 'Genetics',
      correct: 1,
      image: '/images/exams/le-june-2019/q34.png',
    },
    {
      number: 35, part: 'B-1',
      text: 'A student is designing an experiment to determine if the amount of sunlight affects the growth of tomato plants. The student will grow plants under different light conditions and measure their height after 6 weeks. Which statement identifies a potential problem with this experimental design if the student uses only one plant per light condition?',
      choices: [
        'One plant per condition is sufficient to show clear differences in plant height.',
        'Using only one plant per condition makes it impossible to calculate an average or determine if results are repeatable.',
        'The student should use more types of plants to improve the results.',
        'The student should measure leaf area instead of height to get better data.',
      ],
      topic: 'General',
      correct: 1,
    },
    {
      number: 36, part: 'B-1',
      text: 'Scientists have discovered that in some ecosystems, removing a top predator causes a "trophic cascade" — a chain of effects that ripples down through the food web. Which example best illustrates a trophic cascade?',
      choices: [
        'The removal of wolves allows elk populations to increase, causing overgrazing of riverside vegetation, which leads to erosion and changes in river flow.',
        'The removal of wolves causes the deer population to decrease because wolves and deer compete for the same food.',
        'The removal of wolves improves the health of the entire ecosystem because wolves spread disease.',
        'The removal of wolves has no effect on other species because there are other predators in the ecosystem.',
      ],
      topic: 'Ecology',
      correct: 0,
    },
    {
      number: 37, part: 'B-1',
      context: 'A diagram shows the structure of a cell membrane with a phospholipid bilayer, embedded proteins, and receptor molecules. Arrows show different molecules interacting with the membrane.',
      text: 'Based on the diagram, which type of molecule would most easily cross the cell membrane without requiring any transport proteins?',
      choices: [
        'large protein molecules',
        'charged ions such as sodium and potassium',
        'small, nonpolar (fat-soluble) molecules',
        'glucose molecules',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-june-2019/q37.png',
    },
    {
      number: 38, part: 'B-1',
      context: 'A diagram of a cell membrane shows receptor proteins, phospholipid bilayer, and channel proteins.',
      text: 'Based on the diagram, which process describes the binding of a hormone molecule to a receptor protein on the cell membrane?',
      choices: [
        'osmosis — the hormone moves from high to low concentration',
        'active transport — the hormone uses energy to bind to the receptor',
        'a signal transduction event — the hormone-receptor interaction triggers a response inside the cell',
        'diffusion — the hormone passes through the phospholipid bilayer',
      ],
      topic: 'Cell Biology',
      correct: 2,
      image: '/images/exams/le-june-2019/q38.png',
    },
    {
      number: 39, part: 'B-1',
      text: 'A student examines two different ecosystems. Ecosystem A has 50 different species, while Ecosystem B has only 10 species. If a new disease kills 5 species in each ecosystem, which ecosystem would likely be more resilient and why?',
      choices: [
        'Ecosystem B, because it has fewer species to lose',
        'Ecosystem A, because its greater biodiversity means other species can fill the roles of those lost',
        'Both ecosystems would be equally affected by the loss of 5 species',
        'Ecosystem B, because fewer species means less competition and faster recovery',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 40, part: 'B-1',
      context: 'A diagram shows the stages of meiosis, with labels showing how chromosomes are distributed during meiosis I and meiosis II.',
      text: 'Based on the diagram of meiosis, how many cells are produced at the end of meiosis, and what is the chromosome number of each cell compared to the original cell?',
      choices: [
        'two cells, each with the same chromosome number as the original cell',
        'four cells, each with half the chromosome number of the original cell',
        'two cells, each with half the chromosome number of the original cell',
        'four cells, each with twice the chromosome number of the original cell',
      ],
      topic: 'Reproduction',
      correct: 1,
      image: '/images/exams/le-june-2019/q40.png',
    },
    {
      number: 41, part: 'B-1',
      text: 'A researcher is testing the effect of a new drug on the growth of cancer cells. She grows cancer cells in four different petri dishes and adds different doses of the drug to each dish. After 48 hours, she counts the number of cancer cells in each dish. Which step is most important to ensure that her results are valid?',
      choices: [
        'She should test the drug only on mice before testing it on human cells.',
        'She should include a control dish that receives no drug to compare against the treated dishes.',
        'She should use the same type of cancer cells from different patients in each dish.',
        'She should repeat the experiment at least 100 times before drawing any conclusions.',
      ],
      topic: 'General',
      correct: 1,
    },
    {
      number: 42, part: 'B-1',
      text: 'Global climate change is expected to cause shifts in the geographic ranges of many species. For example, as temperatures warm, some insect species are expanding their ranges toward the poles or to higher altitudes. This may affect other species because',
      choices: [
        'insects cannot survive in cold climates and will all go extinct',
        'insects that move into new areas may compete with or feed on native species, disrupting existing food webs',
        'the expansion of insect ranges will have no effect on other species',
        'insects that move to new areas will evolve into new species within a few years',
      ],
      topic: 'Evolution',
      correct: 1,
    },
    {
      number: 43, part: 'B-1',
      text: 'The introduction of the emerald ash borer beetle from Asia into North America has killed hundreds of millions of ash trees. Ash trees play an important role in forest ecosystems by providing food and habitat for many other species. The loss of ash trees most likely results in',
      choices: [
        'increased biodiversity as other tree species fill the space',
        'a decrease in the populations of species that depend on ash trees for food and shelter',
        'no significant change because other tree species quickly fill the vacant niche',
        'an increase in the emerald ash borer population that eventually leads to its own extinction',
      ],
      topic: 'Evolution',
      correct: 1,
    },
  ],
}
