// Chemistry Regents — August 2018
export default {
  id: 'chem-aug-2018',
  subject: 'chemistry',
  year: 2018,
  session: 'August',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'According to the wave-mechanical model, an orbital is defined as the most probable location of', choices: ['a proton', 'a neutron', 'a positron', 'an electron'], topic: 'Atomic Structure', correct: 3 },
    { number: 2, part: 'A', text: 'The part of an atom that has an overall positive charge is called', choices: ['an electron', 'the nucleus', 'the first shell', 'the valence shell'], topic: 'Atomic Structure', correct: 1 },
    { number: 3, part: 'A', text: 'Which subatomic particles each have a mass of approximately + u?', choices: ['proton and electron', 'proton and neutron', 'neutron and electron', 'neutron and positron'], topic: 'Atomic Structure', correct: 1 },
    { number: 4, part: 'A', text: 'The discovery of the electron as a subatomic particle was a result of', choices: ['collision theory', 'kinetic molecular theory', 'the gold-foil experiment', 'experiments with cathode ray tubes'], topic: 'Atomic Structure', correct: 3 },
    { number: 5, part: 'A', text: 'The elements on the Periodic Table of the Elements are arranged in order of increasing', choices: ['atomic mass', 'formula mass', 'atomic number', 'oxidation number'], topic: 'Periodic Table', correct: 2 },
    { number: 6, part: 'A', text: 'Which element is classified as a metalloid?', choices: ['Te', 'S', 'Hg', 'I'], topic: 'Periodic Table', correct: 0 },
    { number: 7, part: 'A', text: 'At STP, O²(g) and O³(g) are two forms of the same element that have', choices: ['the same molecular structure and the same properties', 'the same molecular structure and different properties', 'different molecular structures and the same properties', 'different molecular structures and different properties'], topic: 'Periodic Table', correct: 3 },
    { number: 8, part: 'A', text: 'Which substance can be broken down by chemical means?', choices: ['ammonia', 'aluminum', 'antimony', 'argon'], topic: 'Matter & Energy', correct: 0 },
    { number: 9, part: 'A', text: 'Which statement describes H2O(ℓ) and H2O²(ℓ)?', choices: ['Both are compounds that have the same properties.', 'Both are compounds that have different properties.', 'Both are mixtures that have the same properties.', 'Both are mixtures that have different properties.'], topic: 'General', correct: 1 },
    { number: 10, part: 'A', text: 'Which two terms represent major categories of compounds?', choices: ['ionic and nuclear', 'ionic and molecular', 'empirical and nuclear', 'empirical and molecular'], topic: 'General', correct: 1 },
    { number: 11, part: 'A', text: 'Which formula represents an asymmetrical molecule?', choices: ['CH4', 'CO²', 'N²', 'NH³ P.S./Chem.–Aug. ’18'], topic: 'General', correct: 3 },
    { number: 12, part: 'A', text: 'Which statement describes the energy changes that occur as bonds are broken and formed during a chemical reaction?', choices: ['Energy is absorbed when bonds are both broken and formed.', 'Energy is released when bonds are both broken and formed.', 'Energy is absorbed when bonds are broken, and energy is released when bonds are formed.', 'Energy is released when bonds are broken, and energy is absorbed when bonds are formed.'], topic: 'Redox & Electrochemistry', correct: 2 },
    { number: 13, part: 'A', text: 'A solid sample of copper is an excellent conductor of electric current. Which type of chemical bonds are in the sample?', choices: ['ionic bonds', 'metallic bonds', 'nonpolar covalent bonds', 'polar covalent bonds'], topic: 'General', correct: 1 },
    { number: 14, part: 'A', text: 'Which list includes three forms of energy?', choices: ['thermal, nuclear, electronegativity', 'thermal, chemical, electromagnetic', 'temperature, nuclear, electromagnetic', 'temperature, chemical, electronegativity'], topic: 'General', correct: 1 },
    { number: 15, part: 'A', text: 'Based on Table S, an atom of which element has the strongest attraction for electrons in a chemical bond?', choices: ['chlorine', 'nitrogen', 'oxygen', 'selenium'], topic: 'Atomic Structure', correct: 2 },
    { number: 16, part: 'A', text: 'At which temperature and pressure would a sample of helium behave most like an ideal gas?', choices: ['75 K and 500. kPa', '150. K and 500. kPa', '300. K and 50. kPa', '600. K and 50. kPa'], topic: 'Matter & Energy', correct: 3 },
    { number: 17, part: 'A', text: 'A cube of iron at 20.°C is placed in contact with a cube of copper at 60.°C. Which statement describes the initial flow of heat between the cubes?', choices: ['Heat flows from the copper cube to the iron cube.', 'Heat flows from the iron cube to the copper cube.', 'Heat flows in both directions between the cubes.', 'Heat does not flow between the cubes.'], topic: 'Matter & Energy', correct: 0 },
    { number: 18, part: 'A', text: 'Which sample at STP has the same number of atoms as 18 liters of Ne(g) at STP?', choices: ['18 moles of Ar(g)', '18 liters of Ar(g)', '18 grams of H2O(g)', '18 milliliters of H2O(g)'], topic: 'Matter & Energy', correct: 1 },
    { number: 19, part: 'A', text: 'Compared to H2S, the higher boiling point of H2O is due to the', choices: ['greater molecular size of water', 'stronger hydrogen bonding in water', 'higher molarity of water', 'larger gram-formula mass of water'], topic: 'Matter & Energy', correct: 1 },
    { number: 20, part: 'A', text: 'In terms of entropy and energy, systems in nature tend to undergo changes toward', choices: ['lower entropy and lower energy', 'lower entropy and higher energy', 'higher entropy and lower energy', 'higher entropy and higher energy'], topic: 'Matter & Energy', correct: 2 },
    { number: 21, part: 'A', text: 'Amines, amides, and amino acids are categories of', choices: ['isomers', 'isotopes', 'organic compounds', 'inorganic compounds'], topic: 'Organic Chemistry', correct: 2 },
    { number: 22, part: 'A', text: 'A molecule of which compound has a multiple covalent bond?', choices: ['CH4', 'C2H4', 'C3H8', 'C4H10 P.S./Chem.–Aug. ’18'], topic: 'Chemical Bonding', correct: 1 },
    { number: 23, part: 'A', text: 'Which type of reaction produces soap?', choices: ['polymerization', 'combustion', 'fermentation', 'saponification'], topic: 'General', correct: 3 },
    { number: 24, part: 'A', text: 'For a reaction system at equilibrium, LeChatelier’s principle can be used to predict the', choices: ['activation energy for the system', 'type of bonds in the reactants', 'effect of a stress on the system', 'polarity of the product molecules 25 Which value changes when a Cu atom becomes a Cu²+ ion?'], topic: 'Equilibrium & Kinetics', correct: 2 },
  ]
}
