// Chemistry Regents — January 2023
export default {
  id: 'chem-jan-2023',
  subject: 'chemistry',
  year: 2023,
  session: 'January',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'Which conclusion was developed as a result of the gold foil experiment?', choices: ['Atoms are mostly empty space.', 'All atoms are hard, indivisible spheres.', 'Atoms have different volumes.', 'All atoms have the same volume.'], topic: 'General', correct: 0 },
    { number: 2, part: 'A', text: 'Which two particles each have a mass approximately equal to one atomic mass unit?', choices: ['positron and proton', 'positron and electron', 'neutron and electron', 'neutron and proton'], topic: 'Atomic Structure', correct: 3 },
    { number: 3, part: 'A', text: 'An excited potassium atom emits a specifi c amount of energy when one of its electrons moves from', choices: ['the fi rst shell to the fourth shell', 'the second shell to the fourth shell', 'the fourth shell to the fi fth shell', 'the fourth shell to the second shell'], topic: 'Atomic Structure', correct: 3 },
    { number: 4, part: 'A', text: 'Which list of elements includes a metal, a metalloid, and a noble gas?', choices: ['Rb, Cl, Ne', 'Rn, Cl, Ne', 'Sr, Si, Rn', 'Si, Rb, Sr'], topic: 'Periodic Table', correct: 1 },
    { number: 5, part: 'A', text: 'Which element has the lowest density at 298 K and 101.3 kPa?', choices: ['argon', 'nitrogen', 'fl uorine', 'oxygen'], topic: 'General', correct: 2 },
    { number: 6, part: 'A', text: 'Which phrase describes the crystal structure and properties of two different forms of solid carbon called diamond and graphite?', choices: ['same crystal structure and same properties', 'same crystal structure and different proper- ties', 'different crystal structures and different properties', 'different crystal structures and same proper- ties'], topic: 'General', correct: 2 },
    { number: 7, part: 'A', text: 'Which element has chemical properties most similar to sodium?', choices: ['magnesium', 'phosphorus', 'oxygen', 'rubidium'], topic: 'General', correct: 3 },
    { number: 8, part: 'A', text: 'Which substance contains elements chemically combined in a fi xed proportion?', choices: ['manganese', 'silicon', 'methane', 'strontium'], topic: 'General', correct: 1 },
    { number: 9, part: 'A', text: 'Which property can be used to differentiate between a 50.-gram sample of solid potassium nitrate at STP and a 50.-gram sample of solid silver chloride at STP?', choices: ['mass', 'phase', 'temperature', 'solubility'], topic: 'Stoichiometry', correct: 3 },
    { number: 10, part: 'A', text: 'Which type of bond forms when electrons are equally shared between two atoms?', choices: ['a polar covalent bond', 'a nonpolar covalent bond', 'a hydrogen bond', 'an ionic bond Part A Answer all questions in this part. Directions (1–30): For each statement or question, record on your separate answer sheet the number of the word or expression that, of those given, best completes the statement or answers the question. Some questions may require the use of the 2011 Edition Reference Tables for Physical Setting/Chemistry. P.S. Chem.–Jan. ’23'], topic: 'Atomic Structure', correct: 1 },
    { number: 11, part: 'A', text: 'Which statement describes the changes in bonding and energy that occur when a molecule of iodine, I², forms two separate atoms of iodine?', choices: ['A bond is formed as energy is absorbed.', 'A bond is formed as energy is released.', 'A bond is broken as energy is absorbed.', 'A bond is broken as energy is released.'], topic: 'Atomic Structure', correct: 2 },
    { number: 12, part: 'A', text: 'The degree of polarity in the bond between a hydrogen atom and an oxygen atom in a molecule of water can be assessed using the difference in', choices: ['densities', 'electronegativities', 'melting points', 'intermolecular forces'], topic: 'Atomic Structure', correct: 1 },
    { number: 13, part: 'A', text: 'Which substance can not be broken down by a chemical change?', choices: ['ammonia', 'krypton', 'ethanol', 'water'], topic: 'General', correct: 2 },
    { number: 14, part: 'A', text: 'Which sample of matter is a mixture?', choices: ['CO²(g)', 'MgCl²(aq)', 'CCl4( )', 'Sn(s)'], topic: 'General', correct: 2 },
    { number: 15, part: 'A', text: 'Which term is used to express the concentration of an aqueous solution?', choices: ['parts per million', 'pressure at 0°C', 'heat of fusion', 'volume at 0°C'], topic: 'Solutions', correct: 0 },
    { number: 16, part: 'A', text: 'The particles in which sample have the lowest average kinetic energy?', choices: ['50. g of sulfur at 273 K', '40. g of aluminum at 298 K', '30. g of sulfur at 303 K', '−0. g of aluminum at 323 K'], topic: 'General', correct: 0 },
    { number: 17, part: 'A', text: 'Which process represents a chemical change?', choices: ['Iodine sublimes.', 'Water evaporates.', 'An ice cube melts.', 'A candle burns in air.'], topic: 'General', correct: 3 },
    { number: 18, part: 'A', text: 'Which equation represents a physical equilibrium?', choices: ['NaCl(s) H2O Na1(aq) + Cl²(aq)', '2SO²(g) + O²(g) 2SO³(g)', '3O²(g) → 2O³(g)', 'N²( ) N²(g)'], topic: 'Equilibrium & Kinetics', correct: 3 },
    { number: 19, part: 'A', text: 'Systems in nature tend to undergo changes toward', choices: ['higher energy and higher entropy', 'higher energy and lower entropy', 'lower energy and higher entropy', 'lower energy and lower entropy'], topic: 'General', correct: 2 },
    { number: 20, part: 'A', text: 'Which formula represents a hydrocarbon?', choices: ['C2H6', 'C2H5Cl', 'C2H5OH', 'C2H6O'], topic: 'Organic Chemistry', correct: 0 },
    { number: 21, part: 'A', text: 'Which statement describes the bonding in an alkyne molecule?', choices: ['There is at least one carbon-to-carbon double bond.', 'There is at least one carbon-to-carbon triple bond.', 'There is at least one carbon-to-oxygen single bond.', 'There is at least one carbon-to-oxygen double bond.'], topic: 'Chemical Bonding', correct: 1 },
    { number: 22, part: 'A', text: 'Which compound has a functional group that contains two oxygen atoms?', choices: ['1-propanamine', 'methyl propanoate', '2-chloropropane', 'methyl ethyl ether'], topic: 'Atomic Structure', correct: 2 },
    { number: 23, part: 'A', text: 'Which term identifi es a type of organic reaction?', choices: ['deposition', 'polymerization', 'distillation', 'vaporization'], topic: 'Organic Chemistry', correct: 2 },
    { number: 24, part: 'A', text: 'In an electrochemical cell, oxidation occurs at the', choices: ['anode', 'salt bridge', 'cathode', 'switch P.S. Chem.–Jan. ’23 25 Which energy conversion occurs in an operating electrolytic cell?'], topic: 'Redox & Electrochemistry', correct: 0 },
  ]
}
