// Chemistry Regents — January 2017
export default {
  id: 'chem-jan-2017',
  subject: 'chemistry',
  year: 2017,
  session: 'January',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'Which statement describes the location of two types of subatomic particles in a helium atom?', choices: ['Protons and neutrons are located in the nucleus.', 'Protons and neutrons are located outside the nucleus.', 'Protons and electrons are located in the nucleus.', 'Protons and electrons are located outside the nucleus.'], topic: 'Atomic Structure', correct: 0 },
    { number: 2, part: 'A', text: 'An atom that contains six protons, six neutrons, and six electrons has a mass of approximately', choices: ['12 u', '18 u', '12 g', '18 g'], topic: 'Atomic Structure', correct: 0 },
    { number: 3, part: 'A', text: 'Which term identifies the most probable location of an electron in the wave-mechanical model of the atom?', choices: ['anode', 'nucleus', 'orbital', 'cathode'], topic: 'Atomic Structure', correct: 1 },
    { number: 4, part: 'A', text: 'Which element has atoms in the ground state with the greatest number of valence electrons?', choices: ['tin', 'arsenic', 'sulfur', 'fluorine'], topic: 'Atomic Structure', correct: 3 },
    { number: 5, part: 'A', text: 'Which group on the Periodic Table has two elements that exist as gases at STP?', choices: ['Group 1', 'Group 16', 'Group 2', 'Group 17'], topic: 'Periodic Table', correct: 3 },
    { number: 6, part: 'A', text: 'Which list of elements contains a metal, a metalloid, and a nonmetal?', choices: ['Ag, Si, I²', 'K, Cu, Br²', 'Ge, As, Ne', 'S, Cl², Ar'], topic: 'Periodic Table', correct: 0 },
    { number: 7, part: 'A', text: 'What is the charge of the nucleus of a copper atom?', choices: ['1', '29', '2', '64'], topic: 'Atomic Structure', correct: 2 },
    { number: 8, part: 'A', text: 'At STP, O²(g) and O³(g) have different properties because O³(g) has', choices: ['more dense nuclei than in O²(g)', 'more protons per atom than in O²(g)', 'molecules with a different structure than in O²(g)', 'molecules with fewer covalent bonds than in O²(g)'], topic: 'Matter & Energy', correct: 2 },
    { number: 9, part: 'A', text: 'A compound is a substance composed of two or more elements that are', choices: ['physically mixed in a fixed proportion', 'physically mixed in a variable proportion', 'chemically combined in a fixed proportion', 'chemically combined in a variable proportion'], topic: 'Matter & Energy', correct: 2 },
    { number: 10, part: 'A', text: 'Which element has the highest boiling point at standard pressure?', choices: ['Mg', 'Rb', 'Na', 'Sr'], topic: 'Periodic Table', correct: 3 },
    { number: 11, part: 'A', text: 'How many pairs of electrons are shared between the nitrogen atoms in a molecule of N²?', choices: ['5', '3', '2', '6'], topic: 'General', correct: 2 },
    { number: 12, part: 'A', text: 'A molecule must be nonpolar if the molecule', choices: ['is linear', 'is neutral', 'has ionic and covalent bonding', 'has a symmetrical charge distribution P.S./Chem.–Jan. ’17'], topic: 'Chemical Bonding', correct: 3 },
    { number: 13, part: 'A', text: 'Which property is used to determine the degree of polarity between two bonded atoms?', choices: ['density', 'pressure', 'electronegativity', 'temperature'], topic: 'General', correct: 1 },
    { number: 14, part: 'A', text: 'In a chemical reaction, a catalyst provides an alternate reaction pathway that', choices: ['decreases the concentration of the products', 'increases the concentration of the reactants', 'has a lower activation energy', 'has a higher activation energy'], topic: 'Equilibrium & Kinetics', correct: 2 },
    { number: 15, part: 'A', text: 'Which substance can be decomposed by chemical means?', choices: ['cobalt', 'methane', 'krypton', 'zirconium'], topic: 'General', correct: 2 },
    { number: 16, part: 'A', text: 'Which sample of matter represents a mixture?', choices: ['aqueous ammonia', 'liquid mercury', 'gaseous ethane', 'solid iodine'], topic: 'Matter & Energy', correct: 0 },
    { number: 17, part: 'A', text: 'Differences in which property allow the separation of a sample of sand and seawater by filtration?', choices: ['concentration of ions', 'volume of sample', 'mass of sample', 'particle size'], topic: 'General', correct: 3 },
    { number: 18, part: 'A', text: 'Which process is a chemical change?', choices: ['evaporating an alcohol', 'subliming of iodine', 'melting an ice cube', 'rusting of iron'], topic: 'Matter & Energy', correct: 3 },
    { number: 19, part: 'A', text: 'Which term represents an intermolecular force in a sample of water?', choices: ['hydrogen bonding', 'covalent bonding', 'metallic bonding', 'ionic bonding'], topic: 'Chemical Bonding', correct: 0 },
    { number: 20, part: 'A', text: 'Which sample of matter has particles arranged in a crystalline structure?', choices: ['Ne(g)', 'NaCl(aq)', 'Br²(ℓ)', 'CuSO4(s)'], topic: 'General', correct: 3 },
    { number: 21, part: 'A', text: 'Which term is defined as a measure of the randomness of a system?', choices: ['heat', 'pressure', 'entropy', 'temperature'], topic: 'General', correct: 1 },
    { number: 22, part: 'A', text: 'Which formula represents an alkane?', choices: ['C2H²', 'C3H4', 'C2H4', 'C3H8'], topic: 'Organic Chemistry', correct: 3 },
    { number: 23, part: 'A', text: 'Which term represents a chemical reaction?', choices: ['deposition', 'sublimation', 'combustion', 'vaporization'], topic: 'General', correct: 1 },
    { number: 24, part: 'A', text: 'Which type of reaction includes esterification and polymerization?', choices: ['decomposition', 'organic', 'neutralization', 'nuclear 25 In a redox reaction, the total number of electrons lost is'], topic: 'General', correct: 2 },
  ]
}
