// Chemistry Regents — June 2019
export default {
  id: 'chem-june-2019',
  subject: 'chemistry',
  year: 2019,
  session: 'June',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'Which subatomic particle has a negative charge and is found outside the nucleus?', choices: ['proton', 'neutron', 'electron', 'positron'], topic: 'Atomic Structure', correct: 2 },
    { number: 2, part: 'A', text: 'An atom of carbon-14 contains how many neutrons?', choices: ['6', '8', '12', '14'], topic: 'Atomic Structure', correct: 1 },
    { number: 3, part: 'A', text: 'Which notation represents an atom of an isotope of oxygen with 10 neutrons?', choices: ['oxygen-8', 'oxygen-16', 'oxygen-18', 'oxygen-10'], topic: 'Atomic Structure', correct: 2 },
    { number: 4, part: 'A', text: 'The atomic mass of an element is the weighted average of the masses of its naturally occurring', choices: ['isotopes', 'ions', 'isomers', 'allotropes'], topic: 'Atomic Structure', correct: 0 },
    { number: 5, part: 'A', text: 'According to the wave-mechanical model of the atom, electrons are located in', choices: ['circular orbits', 'specific energy levels only', 'regions of probability called orbitals', 'the nucleus'], topic: 'Atomic Structure', correct: 2 },
    { number: 6, part: 'A', text: 'What is the total number of electrons in a ground-state nitrogen atom?', choices: ['3', '5', '7', '14'], topic: 'Atomic Structure', correct: 2 },
    { number: 7, part: 'A', text: 'Which element has the electron configuration 2-8-18-8-2?', choices: ['calcium', 'magnesium', 'strontium', 'tin'], topic: 'Atomic Structure', correct: 0 },
    { number: 8, part: 'A', text: 'As the atomic number increases from Na to Cl, the atomic radius generally', choices: ['increases', 'decreases', 'remains the same', 'first increases then decreases'], topic: 'Periodic Table', correct: 1 },
    { number: 9, part: 'A', text: 'Which element is a liquid at standard temperature and pressure?', choices: ['mercury', 'nitrogen', 'chlorine', 'phosphorus'], topic: 'Periodic Table', correct: 0 },
    { number: 10, part: 'A', text: 'Elements in Group 17 of the Periodic Table are called', choices: ['noble gases', 'alkali metals', 'halogens', 'alkaline earth metals'], topic: 'Periodic Table', correct: 2 },
    { number: 11, part: 'A', text: 'Which element has the greatest electronegativity?', choices: ['cesium', 'fluorine', 'iodine', 'oxygen'], topic: 'Periodic Table', correct: 1 },
    { number: 12, part: 'A', text: 'Which type of chemical bond results from the attraction between positive ions and a sea of mobile electrons?', choices: ['ionic', 'covalent', 'metallic', 'hydrogen'], topic: 'Chemical Bonding', correct: 2 },
    { number: 13, part: 'A', text: 'A molecule of water (H₂O) has a bent shape due to', choices: ['ionic bonding', 'two bonding pairs only', 'two lone pairs on oxygen that repel the bonding pairs', 'three double bonds'], topic: 'Chemical Bonding', correct: 2 },
    { number: 14, part: 'A', text: 'Which compound contains both ionic and covalent bonds?', choices: ['NaCl', 'H₂O', 'NaOH', 'CH₄'], topic: 'Chemical Bonding', correct: 2 },
    { number: 15, part: 'A', text: 'The high boiling point of water compared to H₂S is due to', choices: ['stronger covalent bonds in water', 'hydrogen bonding between water molecules', 'greater molecular mass of water', 'ionic character of water'], topic: 'Chemical Bonding', correct: 1 },
    { number: 16, part: 'A', text: 'Which formula represents a polar molecule?', choices: ['CO₂', 'CCl₄', 'H₂O', 'N₂'], topic: 'Chemical Bonding', correct: 2 },
    { number: 17, part: 'A', text: 'What is the number of bonding pairs of electrons in a molecule of N₂?', choices: ['1', '2', '3', '6'], topic: 'Chemical Bonding', correct: 2 },
    { number: 18, part: 'A', text: 'A sample of matter that has a definite volume but takes the shape of its container is classified as a', choices: ['solid', 'liquid', 'gas', 'plasma'], topic: 'Matter & Energy', correct: 1 },
    { number: 19, part: 'A', text: 'At STP, which gas has a density closest to the density of air?', choices: ['hydrogen', 'helium', 'argon', 'neon'], topic: 'Matter & Energy', correct: 2 },
    { number: 20, part: 'A', text: 'Which change of phase is exothermic?', choices: ['melting', 'vaporization', 'sublimation', 'condensation'], topic: 'Matter & Energy', correct: 3 },
    { number: 21, part: 'A', text: 'A solution is saturated when', choices: ['solute and solvent are the same substance', 'no more solute can dissolve at that temperature', 'the solute is a solid', 'the solution has a high concentration'], topic: 'Matter & Energy', correct: 1 },
    { number: 22, part: 'A', text: 'Adding a catalyst to a chemical reaction increases the reaction rate by', choices: ['increasing the activation energy', 'decreasing the activation energy', 'changing the products of the reaction', 'increasing the temperature of the reaction'], topic: 'Matter & Energy', correct: 1 },
    { number: 23, part: 'A', text: 'An Arrhenius acid is a substance that, when dissolved in water, releases', choices: ['hydroxide ions', 'hydrogen ions', 'electrons', 'oxide ions'], topic: 'Matter & Energy', correct: 1 },
    { number: 24, part: 'A', text: 'What is the pH of a neutral solution at 25°C?', choices: ['0', '7', '14', '1'], topic: 'Matter & Energy', correct: 1 },
    { number: 25, part: 'A', text: 'Which salt would be produced when HCl reacts with NaOH in a neutralization reaction?', choices: ['NaCl', 'NaHCO₃', 'Na₂SO₄', 'Na₂CO₃'], topic: 'Matter & Energy', correct: 0 },
    { number: 26, part: 'A', text: 'In a redox reaction, the substance that loses electrons is', choices: ['reduced', 'oxidized', 'neutralized', 'hydrolyzed'], topic: 'Matter & Energy', correct: 1 },
    { number: 27, part: 'A', text: 'In a voltaic cell, oxidation occurs at the', choices: ['cathode', 'anode', 'salt bridge', 'electrolyte'], topic: 'Matter & Energy', correct: 1 },
    { number: 28, part: 'A', text: 'Le Chatelier\'s principle states that when a stress is placed on a system at equilibrium, the system will', choices: ['stop the reaction', 'shift to relieve the stress', 'increase the temperature', 'decrease the concentration of all species'], topic: 'Matter & Energy', correct: 1 },
    { number: 29, part: 'A', text: 'Which organic compound is an alcohol?', choices: ['CH₃CHO', 'CH₃OH', 'CH₃COOH', 'CH₃OCH₃'], topic: 'Organic Chemistry', correct: 1 },
    { number: 30, part: 'A', text: 'Which type of organic reaction involves the addition of a monomer unit to a growing chain to form a large polymer?', choices: ['substitution', 'addition polymerization', 'fermentation', 'saponification'], topic: 'Organic Chemistry', correct: 1 },
    // Part B-1
    { number: 31, part: 'B-1', text: 'A sample of radioactive isotope has a half-life of 10 years. How much of a 80g sample remains after 30 years?', choices: ['40 g', '20 g', '10 g', '5 g'], topic: 'Atomic Structure', correct: 2 },
    { number: 32, part: 'B-1', text: 'Nuclear fission differs from nuclear fusion in that fission involves', choices: ['combining small nuclei', 'splitting heavy nuclei', 'emitting beta particles', 'absorbing neutrons'], topic: 'Atomic Structure', correct: 1 },
    { number: 33, part: 'B-1', text: 'Which type of nuclear decay involves the release of a high-energy electromagnetic radiation?', choices: ['alpha decay', 'beta decay', 'gamma decay', 'positron emission'], topic: 'Atomic Structure', correct: 2 },
    { number: 34, part: 'B-1', text: 'Which particle has approximately the same mass as a proton?', choices: ['electron', 'neutron', 'positron', 'alpha particle'], topic: 'Atomic Structure', correct: 1 },
    { number: 35, part: 'B-1', text: 'As elements in Period 3 are considered from left to right, the first ionization energy generally', choices: ['decreases', 'increases', 'remains the same', 'first decreases then increases'], topic: 'Periodic Table', correct: 1 },
    { number: 36, part: 'B-1', text: 'Which element is more reactive in chemical reactions — Na or K?', choices: ['Na, because it has a smaller atomic radius', 'K, because it more easily loses its valence electron', 'Na, because it has fewer energy levels', 'K, because it has more protons'], topic: 'Periodic Table', correct: 1 },
    { number: 37, part: 'B-1', text: 'The solubility of a gas in a liquid increases when the', choices: ['temperature increases and pressure decreases', 'temperature decreases and pressure increases', 'temperature increases and pressure increases', 'temperature decreases and pressure decreases'], topic: 'Matter & Energy', correct: 1 },
    { number: 38, part: 'B-1', text: 'What is the molarity of a solution containing 4.0 mol of solute dissolved in 2.0 L of solution?', choices: ['0.5 M', '2.0 M', '6.0 M', '8.0 M'], topic: 'Matter & Energy', correct: 1 },
    { number: 39, part: 'B-1', text: 'Which 0.1 M aqueous solution has the lowest pH?', choices: ['HF', 'HCl', 'NaOH', 'NaCl'], topic: 'Matter & Energy', correct: 1 },
    { number: 40, part: 'B-1', text: 'In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, the zinc is', choices: ['the oxidizing agent', 'the reducing agent', 'reduced', 'a catalyst'], topic: 'Matter & Energy', correct: 1 },
    { number: 41, part: 'B-1', text: 'Which statement describes an exothermic reaction?', choices: ['The products have more potential energy than the reactants', 'The reactants have more potential energy than the products', 'The reaction requires a continuous input of energy', 'The activation energy equals the heat of reaction'], topic: 'Matter & Energy', correct: 1 },
    { number: 42, part: 'B-1', text: 'For the equilibrium: N₂ + 3H₂ ⇌ 2NH₃ + heat, increasing temperature shifts the equilibrium toward', choices: ['more NH₃ production', 'more N₂ and H₂ production', 'no change', 'complete conversion to NH₃'], topic: 'Matter & Energy', correct: 1 },
    { number: 43, part: 'B-1', text: 'Which organic compound contains a carboxyl functional group (–COOH)?', choices: ['ethanol', 'ethanoic acid', 'diethyl ether', 'acetaldehyde'], topic: 'Organic Chemistry', correct: 1 },
    { number: 44, part: 'B-1', text: 'What type of isomers have the same molecular formula but different structural arrangements?', choices: ['isotopes', 'structural isomers', 'allotropes', 'enantiomers'], topic: 'Organic Chemistry', correct: 1 },
    { number: 45, part: 'B-1', text: 'Which process produces a new substance with different chemical properties?', choices: ['dissolving salt in water', 'melting ice', 'burning wood', 'boiling water'], topic: 'Matter & Energy', correct: 2 },
    { number: 46, part: 'B-1', text: 'The gram formula mass of Ca(OH)₂ is', choices: ['57 g/mol', '58 g/mol', '74 g/mol', '76 g/mol'], topic: 'Matter & Energy', correct: 2 },
    { number: 47, part: 'B-1', text: 'What volume does 1 mole of an ideal gas occupy at STP?', choices: ['1.0 L', '22.4 L', '273 L', '11.2 L'], topic: 'Matter & Energy', correct: 1 },
    { number: 48, part: 'B-1', text: 'Which reaction is a double replacement reaction?', choices: ['2H₂ + O₂ → 2H₂O', 'Zn + 2HCl → ZnCl₂ + H₂', 'AgNO₃ + NaCl → AgCl + NaNO₃', 'CaCO₃ → CaO + CO₂'], topic: 'Matter & Energy', correct: 2 },
    { number: 49, part: 'B-1', text: 'Which property increases as you move down a group in the Periodic Table?', choices: ['electronegativity', 'ionization energy', 'atomic radius', 'nuclear charge'], topic: 'Periodic Table', correct: 2 },
    { number: 50, part: 'B-1', text: 'The empirical formula of a compound is the formula showing the', choices: ['actual number of each type of atom in a molecule', 'simplest whole-number ratio of atoms in the compound', 'three-dimensional structure of the molecule', 'number of bonds between atoms'], topic: 'Matter & Energy', correct: 1 },
  ],
}
