// Physics Regents — June 2023
export default {
  id: 'phys-jun-2023',
  subject: 'physics',
  year: 2023,
  session: 'June',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 0 },
    { number: 2, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 0 },
    { number: 3, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 1 },
    { number: 10, part: 'A', text: 'To lift a heavy block off the floor, a student pulls with force F on a rope that passes over a pulley, as shown in the diagram below. F Which pair of vectors represents the perpendicular components of the force the student exerts on the rope? ( 4 ) ( 2 ) ( 1 ) ( 3 )', choices: ['', '', '', ''], topic: 'Forces & Newton', correct: 1, image: '/images/exams/phys-june-2023/q10.png' },
    { number: 11, part: 'A', text: 'Which graph best represents the relationship between the mass of an object and its distance from Earth’s surface? ( 2 ) Mass Distance ( 4 ) Mass Distance ( 1 ) Mass Distance ( 3 ) Mass Distance P.S./Physics–June ’23', choices: ['', '', '', ''], topic: 'Kinematics', correct: 0 },
    { number: 12, part: 'A', text: 'A compass is placed near a strong bar magnet as represented in the diagram below. N S Bar magnet Compass Which diagram best represents the direction of the compass needle? ( 1 ) S N ( 3 ) ( 4 ) S N N S ( 2 ) S N', choices: ['', '', '', ''], topic: 'Magnetism', correct: 2, image: '/images/exams/phys-june-2023/q12.png' },
    { number: 13, part: 'A', text: 'As Earth orbits the Sun in its elliptical orbit, the gravitational force between the Sun and Earth is', choices: ['always attractive', 'attractive as the Sun and Earth get closer together and repulsive as the Sun and Earth get farther apart', 'repulsive as the Sun and Earth get closer together and attractive as the Sun and Earth get farther apart', 'always repulsive'], topic: 'Forces & Newton', correct: 0 },
    { number: 14, part: 'A', text: 'Which unit is used to measure the work per unit charge required to move a charge in an electric field?', choices: ['ampere', 'volt', 'coulomb', 'watt'], topic: 'Energy & Work', correct: 2 },
    { number: 15, part: 'A', text: 'The diagram below shows a negatively charged sphere and a point, P, located within the electric field produced by the charge on the sphere. Sphere – D P B C A The direction of the electric field at point P is toward point', choices: ['A', 'C', 'B', 'D'], topic: 'Electricity', correct: 3, image: '/images/exams/phys-june-2023/q15.png' },
    { number: 16, part: 'A', text: 'Two point charges, q1 and q², are initially a distance, d, apart. Which change will cause the greatest increase in the electrostatic force between the two point charges, q1 and q²?', choices: ['double q1', 'double d', 'halve q²', 'halve d'], topic: 'Kinematics', correct: 3 },
    { number: 17, part: 'A', text: 'The diagram below represents two identical conducting spheres. A + + + + + – – – – – B + + + + + – – – – – Which statement could be the correct explanation for the charge distribution on the spheres?', choices: ['A small positively charged object is located between sphere A and sphere B.', 'A small negatively charged object is located between sphere A and sphere B.', 'A small positively charged object is located to the right of sphere B.', 'A small negatively charged object is located to the right of sphere B. P.S./Physics–June ’23'], topic: 'General', correct: 1, image: '/images/exams/phys-june-2023/q17.png' },
    { number: 18, part: 'A', text: 'The diagram below represents a circuit containing a battery, two operating lamps, A and B, and four closed switches, S1, S², S³, and S4. Lamp A Lamp B S1 S² S³ S4 Which switch, when opened, causes both lamps to turn off?', choices: ['S1', 'S³', 'S²', 'S4'], topic: 'Electricity', correct: 0, image: '/images/exams/phys-june-2023/q18.png' },
    { number: 19, part: 'A', text: 'What is the resistance of a 100.-watt bulb when operating a potential difference of 120. volts?', choices: ['1.20 W', '120. W', '100. W', '144 W'], topic: 'Energy & Work', correct: 3 },
    { number: 20, part: 'A', text: 'The interaction that is most responsible for binding three quarks together in a proton is the', choices: ['strong force', 'weak force', 'electromagnetic force', 'gravitational force'], topic: 'General', correct: 0, image: '/images/exams/phys-june-2023/q20.png' },
    { number: 21, part: 'A', text: 'One example of a force doing work is the force exerted by', choices: ['Earth on a high diver falling toward a pool from a platform above', 'a hook on an engine held stationary above a car', 'a frictionless horizontal air hockey table on a puck moving across the table at a constant velocity', 'a weightlifter on a barbell he holds motionless over his head'], topic: 'Forces & Newton', correct: 0 },
    { number: 22, part: 'A', text: 'A ball falls freely from a rooftop to the street below. The ball starts from rest with 20. joules of gravitational potential energy with respect to the street. The total mechanical energy of the ball just before it hits the street is', choices: ['0 J', '10. J', '5.0 J', '−0. J'], topic: 'Energy & Work', correct: 3, image: '/images/exams/phys-june-2023/q22.png' },
    { number: 23, part: 'A', text: 'Which statement describes the gravitational potential energy (PE), kinetic energy (KE), and internal (thermal) energy (Q), of a wooden crate as it is pushed across a level classroom floor at constant speed?', choices: ['The PE decreases, KE remains the same, and Q decreases.', 'The PE increases, KE increases, and Q decreases.', 'The PE remains the same, KE decreases, and Q increases.', 'The PE remains the same, KE remains the same, and Q increases.'], topic: 'Kinematics', correct: 3 },
    { number: 24, part: 'A', text: 'The oscillation of electrons up and down a metal antenna produces waves. These waves are', choices: ['mechanical and longitudinal', 'mechanical and transverse', 'electromagnetic and transverse', 'electromagnetic and longitudinal 25'], topic: 'General', correct: 2, image: '/images/exams/phys-june-2023/q24.png' },
  ]
}
