// Physics Regents — June 2017
export default {
  id: 'phys-jun-2017',
  subject: 'physics',
  year: 2017,
  session: 'June',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'A unit used for a vector quantity is', choices: ['watt', 'kilogram', 'newton', 'second'], topic: 'Forces & Newton', correct: 1 },
    { number: 2, part: 'A', text: 'A displacement vector with a magnitude of 20. meters could have perpendicular components with magnitudes of', choices: ['10. m and 10. m', '12 m and 16 m', '12 m and 8.0 m', '16 m and 8.0 m'], topic: 'Kinematics', correct: 2, image: '/images/exams/phys-june-2017/q2.png' },
    { number: 3, part: 'A', text: 'A hiker travels 1.0 kilometer south, turns and travels 3.0 kilometers west, and then turns and travels 3.0 kilometers north. What is the total distance traveled by the hiker?', choices: ['3.2 km', '5.0 km', '3.6 km', '7.0 km'], topic: 'Kinematics', correct: 3, image: '/images/exams/phys-june-2017/q3.png' },
    { number: 4, part: 'A', text: 'A car with an initial velocity of 16.0 meters per second east slows uniformly to 6.0 meters per second east in 4.0 seconds. What is the acceleration of the car during this 4.0-second interval?', choices: ['2.5 m/s² west', '4.0 m/s² west', '2.5 m/s² east', '4.0 m/s² east'], topic: 'Kinematics', correct: 0 },
    { number: 5, part: 'A', text: 'On the surface of planet X, a body with a mass of 10. kilograms weighs 40. newtons. The magnitude of the acceleration due to gravity on the surface of planet X is', choices: ['4.0 × 103 m/s²', '9.8 m/s²', '4.0 × 102 m/s²', '4.0 m/s²'], topic: 'Kinematics', correct: 3 },
    { number: 6, part: 'A', text: 'A car traveling in a straight line at an initial speed of 8.0 meters per second accelerates uniformly to a speed of 14 meters per second over a distance of 44 meters. What is the magnitude of the acceleration of the car?', choices: ['0.41 m/s²', '3.0 m/s²', '1.5 m/s²', '2.2 m/s²'], topic: 'Kinematics', correct: 1 },
    { number: 7, part: 'A', text: 'An object starts from rest and falls freely for 40. meters near the surface of planet P. If the time of fall is 4.0 seconds, what is the magnitude of the acceleration due to gravity on planet P?', choices: ['0 m/s²', '5.0 m/s²', '1.3 m/s²', '10. m/s²'], topic: 'Kinematics', correct: 2 },
    { number: 8, part: 'A', text: 'If a block is in equilibrium, the magnitude of the block’s acceleration is', choices: ['zero', 'decreasing', 'increasing', 'constant, but not zero'], topic: 'Kinematics', correct: 0, image: '/images/exams/phys-june-2017/q8.png' },
    { number: 9, part: 'A', text: 'The diagram below shows a light ray striking a plane mirror. What is the angle of reflection?', choices: ['30.°', '90.°', '60.°', '120.°'], topic: 'Light & Optics', correct: 1, image: '/images/exams/phys-june-2017/q9.png' },
    { number: 10, part: 'A', text: 'An electric field exerts an electrostatic force of magnitude 1.5 × 10−14 newton on an electron within the field. What is the magnitude of the electric field strength at the location of the electron?', choices: ['2.4 × 10−33 N/C', '9.4 × 104 N/C', '1.1 × 10−5 N/C', '1.6 × 1016 N/C '], topic: 'Forces & Newton', correct: 2 },
    { number: 11, part: 'A', text: 'A 7.0-kilogram cart, A, and a 3.0-kilogram cart, B, are initially held together at rest on a horizontal, frictionless surface. When a compressed spring attached to one of the carts is released, the carts are pushed apart. After the spring is released, the speed of cart B is 6.0 meters per second, as represented in the diagram below. What is the speed of cart A after the spring is released?', choices: ['14 m/s', '3.0 m/s', '6.0 m/s', '2.6 m/s'], topic: 'Kinematics', correct: 3, image: '/images/exams/phys-june-2017/q11.png' },
    { number: 12, part: 'A', text: 'An electron in a magnetic field travels at constant speed in the circular path represented in the diagram below. Which arrow represents the direction of the net force acting on the electron when the electron is at position A?', choices: ['', '', '', ''], topic: 'Kinematics', correct: 2 },
    { number: 13, part: 'A', text: 'The potential difference between two points, A and B, in an electric field is 2.00 volts. The energy required to move a charge of 8.00 × 10−19 coulomb from point A to point B is', choices: ['4.00 × 10−19 J', '6.25 × 1017 J', '1.60 × 10−18 J', '2.50 × 1018 J'], topic: 'Electricity', correct: 1 },
    { number: 14, part: 'A', text: 'Which statement describes the gravitational force and the electrostatic force between two charged particles?', choices: ['The gravitational force may be either attractive or repulsive, whereas the electrostatic force must be attractive.', 'The gravitational force must be attractive, whereas the electrostatic force may be either attractive or repulsive.', 'Both forces may be either attractive or repulsive.', 'Both forces must be attractive.'], topic: 'Forces & Newton', correct: 1, image: '/images/exams/phys-june-2017/q14.png' },
    { number: 15, part: 'A', text: 'An electrostatic force exists between two +3.20 × 10−19-coulomb point charges separated by a distance of 0.030 meter. As the distance between the two point charges is decreased, the electrostatic force of', choices: ['attraction between the two charges decreases', 'attraction between the two charges increases', 'repulsion between the two charges decreases', 'repulsion between the two charges increases'], topic: 'Kinematics', correct: 3 },
    { number: 16, part: 'A', text: 'What is the energy of the photon emitted when an electron in a mercury atom drops from energy level f to energy level b?', choices: ['8.42 eV', '3.06 eV', '5.74 eV', '2.68 eV'], topic: 'Light & Optics', correct: 2, image: '/images/exams/phys-june-2017/q16.png' },
    { number: 17, part: 'A', text: 'An observer counts 4 complete water waves passing by the end of a dock every 10. seconds. What is the frequency of the waves?', choices: ['0.40 Hz', '40. Hz', '2.5 Hz', '4.0 Hz'], topic: 'Waves & Sound', correct: 0 },
    { number: 18, part: 'A', text: 'Copper is a metal commonly used for electrical wiring in houses. Which metal conducts electricity better than copper at 20°C?', choices: ['aluminum', 'nichrome', 'gold', 'silver     A Path of electron   
    !"#$'], topic: 'General', correct: 3 },
    { number: 19, part: 'A', text: 'A motor does 20. joules of work on a block, accelerating the block vertically upward. Neglecting friction, if the gravitational potential energy of the block increases by 15 joules, its kinetic energy', choices: ['decreases by = J', 'decreases by 35 J', 'increases by = J', 'increases by 35 J'], topic: 'Kinematics', correct: 1 },
    { number: 20, part: 'A', text: 'When only one lightbulb blows out, an entire string of decorative lights goes out. The lights in this string must be connected in', choices: ['parallel with one current pathway', 'parallel with multiple current pathways', 'series with one current pathway', 'series with multiple current pathways'], topic: 'General', correct: 2 },
    { number: 21, part: 'A', text: 'An electric toaster is rated 1200 watts at 120 volts. What is the total electrical energy used to operate the toaster for 30. seconds?', choices: ['1.8 × 103 J', '1.8 × 104 J', '3.6 × 103 J', '3.6 × 104 J'], topic: 'General', correct: 3 },
    { number: 22, part: 'A', text: 'What is the rate at which work is done in lifting a 35-kilogram object vertically at a constant speed of 5.0 meters per second?', choices: ['1700 W', '180 W', '340 W', '7.0 W'], topic: 'Kinematics', correct: 0, image: '/images/exams/phys-june-2017/q22.png' },
    { number: 23, part: 'A', text: 'When a wave travels through a medium, the wave transfers', choices: ['mass, only', 'energy, only', 'both mass and energy', 'neither mass nor energy'], topic: 'Waves & Sound', correct: 1 },
    { number: 24, part: 'A', text: 'Glass may shatter when exposed to sound of a particular frequency. This phenomenon is an example of', choices: ['refraction', 'resonance', 'diffraction', 'the Doppler effect 25 Which waves require a material medium for transmission?'], topic: 'Waves & Sound', correct: 2 },
  ]
}
