// Algebra 2 Regents — August 2019 (Part I: Multiple Choice)
export default {
  id: 'a2-aug-2019',
  subject: 'algebra-2',
  year: 2019,
  session: 'August',
  totalMinutes: 180,
  questions: [
    { number: 1,  part: 'A', text: 'The polynomial p(x) = 6x³ − 7x² − 1 is divided by (x − 1). What is the remainder?', choices: ['0', '−1', '−2', '1'], topic: 'Polynomial Functions', correct: 2 },
    { number: 2,  part: 'A', text: 'What is the simplified form of ⁵√(32x¹⁰)?', choices: ['2x²', '2x⁵', '4x²', '8x²'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 3,  part: 'A', text: 'Solve: log(2x + 1) = 2', choices: ['x = 10', 'x = 49', 'x = 99/2', 'x = 50'], topic: 'Exponential & Logarithmic Functions', correct: 2 },
    { number: 4,  part: 'A', text: 'Which function has a period of π?', choices: ['f(x) = sin(2x)', 'f(x) = cos(x)', 'f(x) = tan(x/2)', 'f(x) = sin(x/2)'], topic: 'Trigonometric Functions', correct: 0 },
    { number: 5,  part: 'A', text: 'Which best describes the sampling method of assigning numbers to all members of a population and using a random number generator to select participants?', choices: ['Stratified sampling', 'Cluster sampling', 'Systematic sampling', 'Simple random sampling'], topic: 'Statistics & Probability', correct: 3 },
    { number: 6,  part: 'A', text: 'What is the product (4 − i)(4 + i)?', choices: ['17', '15', '16 − i²', '16 + 1'], topic: 'Complex Numbers', correct: 0 },
    { number: 7,  part: 'A', text: 'Which polynomial is divisible by (x + 4)?', choices: ['x³ + 3x² − 4x − 12', 'x³ + 4x² − x − 4', 'x³ − 64', 'x² + 4x − 4'], topic: 'Polynomial Functions', correct: 1 },
    { number: 8,  part: 'A', text: 'What is the simplified form of (9 − x²)/(x − 3)?', choices: ['−(x + 3)', 'x + 3', '−x + 3', 'x − 3'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 9,  part: 'A', text: 'Which property is used when writing log(x³) as 3 log(x)?', choices: ['Product property', 'Power property', 'Quotient property', 'Change of base'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 10, part: 'A', text: 'What is the value of cos(π/6)?', choices: ['1/2', '√2/2', '√3/2', '1'], topic: 'Trigonometric Functions', correct: 2 },
    { number: 11, part: 'A', text: 'In a class, the grades on an exam are 65, 70, 75, 80, 85, 90, 95. What is the median?', choices: ['80', '75', '85', '82.1'], topic: 'Statistics & Probability', correct: 0 },
    { number: 12, part: 'A', text: 'What is the value of (2i)³?', choices: ['8i', '−8i', '6i', '8'], topic: 'Complex Numbers', correct: 1 },
    { number: 13, part: 'A', text: 'Which polynomial has roots at x = 0 and x = ±√3?', choices: ['x³ − 3x', 'x³ + 3x', 'x³ − 9x', 'x(x − 3)²'], topic: 'Polynomial Functions', correct: 0 },
    { number: 14, part: 'A', text: 'Simplify: √(48) / √(3)', choices: ['4', '16', '4√3', '√16'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 15, part: 'A', text: 'Solve: 4^x = 8', choices: ['x = 2', 'x = 3/2', 'x = 1/2', 'x = 3'], topic: 'Exponential & Logarithmic Functions', correct: 1 },
    { number: 16, part: 'A', text: 'What is the vertical asymptote of y = tan(x)?', choices: ['x = π', 'x = π/2', 'x = 0', 'x = 2π'], topic: 'Trigonometric Functions', correct: 1 },
    { number: 17, part: 'A', text: 'A bag contains 5 red and 3 blue chips. Two chips are selected with replacement. What is the probability both are red?', choices: ['25/64', '5/16', '10/56', '5/8'], topic: 'Statistics & Probability', correct: 0 },
    { number: 18, part: 'A', text: 'Simplify: (3 + 4i)(3 − 4i) + 2i', choices: ['25 + 2i', '7 + 2i', '25 − 2i', '9 + 2i'], topic: 'Complex Numbers', correct: 0 },
    { number: 19, part: 'A', text: 'Which is equivalent to f(x) = −2x³ + 6x for large positive values of x?', choices: ['f(x) → +∞', 'f(x) → −∞', 'f(x) → 0', 'f(x) → 6'], topic: 'Polynomial Functions', correct: 1 },
    { number: 20, part: 'A', text: 'Simplify: (x − 2)/(x² − 4) + 1/(x + 2)', choices: ['2/(x + 2)', '1/(x − 2)', '(x − 1)/(x² − 4)', '2/(x² − 4)'], topic: 'Rational & Radical Expressions', correct: 0 },
    { number: 21, part: 'A', text: 'The expression log₃(81) − log₃(9) is equivalent to', choices: ['log₃(72)', 'log₃(9)', '2', '1'], topic: 'Exponential & Logarithmic Functions', correct: 2 },
    { number: 22, part: 'A', text: 'A Ferris wheel with radius 40 feet completes one revolution in 4 minutes. Which equation models the height h above the center after t minutes?', choices: ['h = 40 sin(π/2 · t)', 'h = 40 cos(πt)', 'h = 40 sin(πt/2)', 'h = 40 sin(2πt)'], topic: 'Trigonometric Functions', correct: 2 },
    { number: 23, part: 'A', text: 'The complex number 2 − 3i has modulus', choices: ['√13', '√5', '5', '√11'], topic: 'Complex Numbers', correct: 0 },
    { number: 24, part: 'A', text: 'A sample of 100 people shows 45 prefer brand A. Which is the best estimate for the population proportion?', choices: ['0.55', '0.45', '45', '4.5'], topic: 'Statistics & Probability', correct: 1 },
  ]
}
