// Algebra 2 Regents — January 2026
export default {
  id: 'a2-jan-2026',
  subject: 'algebra-2',
  year: 2026,
  session: 'January',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: 'credit. All answers should be written in pen, except for graphs and drawings, which should be done in pencil. 37 Xander and Yvette are each practicing for their road tests. Xander decides to drive for 15 minutes the first day and plans to increase the amount of time he spends driving by five minutes each day leading up to the day of his test. Yvette decides to drive for 10 minutes the first day, and she plans to increase the amount of time she spends driving by 15% each day leading up to the day of her test. State whose plan for the amount of time driving per day can be modeled by an arithmetic sequence, and whose plan can be modeled by a geometric sequence. Explain your reasoning. Write an equation for xn that represents the amount of time spent driving on the nth day for Xander’s plan and an equation for yn that represents the amount of time spent driving on the nth day for Yvette’s plan. Who will spend more time driving on the 19th day of practicing? Justify your answer. Scrap Graph Paper — this sheet will not be scored. Tear Here Tear Here Scrap Graph Paper — this sheet will not be scored. Tear Here Tear Here Algebra II – Jan. ’26 High School Math Reference Sheet + inch = 2.54 centimeters + meter = 39.37 inches + mile = 5280 feet + mile = 1760 yards + mile = 1.609 kilometers + kilometer = 0.62 mile + pound = 16 ounces + pound = 0.454 kilogram + kilogram = 2.2 pounds + ton = 2000 pounds + cup = 8 fluid ounces + pint = − cups + quart = − pints + gallon = 4 quarts + gallon = 3.785 liters + liter = 0.264 gallon + liter = 1000 cubic centimeters Triangle A = 1_', choices: ['', '', '', ''], topic: 'Exponential & Logarithmic', correct: 3 },
    { number: 2, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 3 },
    { number: 3, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 2 },
    { number: 10, part: 'A', text: 'Consider the system of equations below. (x + 1)² + (y − 4)² = 9 x = − The x-value and y-value of the solution of the system are', choices: ['one rational and one imaginary', 'both rational', 'one rational and one irrational', 'both irrational'], topic: 'Systems & Inequalities', correct: 1 },
    { number: 11, part: 'A', text: 'Which expressions are equivalent to 36x4 − 9x²? I. x²(6x + 3)(6x − 3) III. 9(2x² + x)(2x² − x) II. 36(x² − 1 2)(x² + 1 2) IV. 36x²(x − 1 2)(x + 1 2)', choices: ['I and II, only', 'I, II, and III, only', 'I and III, only', 'I, III, and IV, only'], topic: 'General', correct: 3 },
    { number: 12, part: 'A', text: 'A deposit of $1250 is made into a savings account that earns 1.86% annual interest. The amount in this account at any time, t, in years, is modeled by A(t) = 1250(1.0186)t. Which expression best models the equivalent monthly growth of the account?', choices: ['1250(0.001550)t', '1250(1.001537)12t', '1250(0.001550) t 12', '1250(1.001537) t 12 Algebra II – Jan. ’26'], topic: 'Exponential & Logarithmic', correct: 2 },
    { number: 13, part: 'A', text: 'Which graph represents a function that has a remainder of zero when divided by (x − 4)? (3)', choices: ['y y x x', '', 'y y x x', ''], topic: 'Polynomial Functions', correct: 0, image: '/images/exams/alg2-january-2026/q13.png' },
    { number: 14, part: 'A', text: 'Given a . 0, which expression is equivalent to a 3 a a² 5·?', choices: ['a − 13', 'a 4 15', 'a 7 30', 'a 7 3 Algebra II – Jan. ’26'], topic: 'General', correct: 1 },
    { number: 15, part: 'A', text: 'Which function could represent the sketch below, where a, b, c, and d are all greater than zero? f(x) x b c − 2a d', choices: ['f (x) = 2(x + a)(cx + b)(x − d)²', 'f (x) = 2(x + a)(bx + c)(2x − d)', 'f (x) = 2(x − a)(cx − b)(x + d)²', 'f (x) = 2(x − a)(bx − c)(2x + d)'], topic: 'Functions', correct: 0, image: '/images/exams/alg2-january-2026/q15.png' },
    { number: 16, part: 'A', text: 'Before leaving for summer vacation, 447 students at a high school were asked whether or not they had a job for the summer. The results of the survey, broken down by the students’ averages, are shown in the table below. Below 70% 70%–79% 80%–89% 90%–100% Has a Job 35 73 78 52 Does Not Have a Job 42 62 70 35 The probability that a student has a job, given that the student’s average is between 90% and 100%, rounded to the nearest hundredth, is', choices: ['0.11', '0.59', '0.12', '0.60 Algebra II – Jan. ’26'], topic: 'Statistics & Probability', correct: 3, image: '/images/exams/alg2-january-2026/q16.png' },
    { number: 17, part: 'A', text: 'The expression 3x³ − 4x² − 17x + 6 3x − 1 , where x ? 1 3 , is equivalent to', choices: ['(x + 3)(x − 2)', '(x − 3)(x − 2)', '(x − 3)(x + 2)', 'x² − x 2 6 + 12 3x − 1'], topic: 'General', correct: 1 },
    { number: 18, part: 'A', text: 'Three students put their first steps to solve the equation x² − 4x = 9 on the board at school. x² − 4x = 9 x − 2x = 3 Max x² − 4x x² − 4x + 4 = 9 + 4 = 9 Gus x(x − 4) = 9 x = 9 x − 4 = 9 Rosie Correct steps are shown for', choices: ['Max, only', 'Max and Rosie, only', 'Gus, only', 'Gus and Rosie, only'], topic: 'General', correct: 1 },
    { number: 19, part: 'A', text: 'The average depreciation rate of a laptop is approximately 33.3% each year. If Garrett purchased a new laptop for $700, which recursive formula represents the value of his laptop n years after it was purchased?', choices: ['a0 = 700', 'an = 700(0.667)n − 1', 'a0 = 700', 'an = 700(0.333)n − 1'], topic: 'General', correct: 0 },
    { number: 20, part: 'A', text: 'Given that the directrix of a parabola is y = 7 and its focus is 6 units vertically away from it, the vertex of this parabola could be the point', choices: ['(5,13)', '(3,10)', '(2,1)', '(4,6)'], topic: 'General', correct: 2 },
    { number: 21, part: 'A', text: 'How many values of x satisfy the equation x x − 1 = 2|2x − 3| 1 5?', choices: ['1', '3', '2', '0'], topic: 'General', correct: 2 },
    { number: 22, part: 'A', text: 'The tangent of an angle in standard position that terminates in Quadrant II is − 6 . What is the cosine of this angle?', choices: ['1 6', '2 + 37', '2 7', '1 − 7 Algebra II – Jan. ’26'], topic: 'Trigonometric Functions', correct: 3 },
    { number: 23, part: 'A', text: 'Miranda joins a gym and pays an annual membership of $400. Due to rising costs, the gym operator has told her the membership will increase 8% each year after the first year. How much will Miranda have paid in total, to the nearest dollar, if she is a member for 6 years?', choices: ['635', '−934', '−592', '4320'], topic: 'Trigonometric Functions', correct: 2 },
    { number: 24, part: 'A', text: 'Ms. Miles observed slides of bacteria under a microscope. She found that over a specific amount of time, t, in hours, the population was growing. She graphed the results of the population, p(t), in thousands, of the bacteria over time on the graph below. p(t) t 1 − 1 (0.25,4.76) (0.75,6.72) (1.5,11.31) Assuming exponential growth, which statement is true?', choices: ['The population can be modeled by p(t) = 2', 't.', 'The population can be modeled by p(t) = 3.92 t + 3.78.', 'The population approximately doubled every hour.'], topic: 'Exponential & Logarithmic', correct: 2, image: '/images/exams/alg2-january-2026/q24.png' },
  ]
}
