// Algebra 2 Regents — January 2024
export default {
  id: 'a2-jan-2024',
  subject: 'algebra-2',
  year: 2024,
  session: 'January',
  totalMinutes: 180,
  questions: [
    { number: 1, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 2 },
    { number: 2, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 1 },
    { number: 3, part: 'A', text: 'y 7 3?', choices: ['P = 3 210x4y7', 'P = 210xy² xy 3', 'P = 70xy² xy 3', 'P = 210xy² 3 x3y5 14'], topic: 'General', correct: 1 },
    { number: 4, part: 'A', text: '', choices: ['', '', '', ''], topic: 'General', correct: 2 },
    { number: 10, part: 'A', text: 'The seventh term of the geometric sequence 6, 3 22 , 6 2 , 3 24 … is', choices: ['6 6', '6 8', '3 26', '3 28'], topic: 'Sequences & Series', correct: 2 },
    { number: 11, part: 'A', text: 'A company wishes to determine the cooking time for one pound of spaghetti. The company’s technicians cooked one pound of spaghetti and recorded the time needed for the spaghetti to be ready to eat. Repeating this process 35 times resulted in an approximately normal distribution, with a mean of 9.82 minutes and a standard deviation of 1.4 minutes. In which interval should the middle 95% of cooking times fall?', choices: ['(8.42, 11.22)', '(9.35, 10.29)', '(7.02, 12.62)', '(6.82, 11.32) Algebra II – Jan. ’24'], topic: 'Statistics & Probability', correct: 1 },
    { number: 12, part: 'A', text: 'Given f(x) = 2x² + 7x − 15 and g(x) = 3 − 2x, what is f(x) g(x) for all defined values?', choices: ['2x − 5', 'x − 5', '2x + 5', 'x + 5'], topic: 'General', correct: 0 },
    { number: 13, part: 'A', text: 'Which equation is equivalent to P = 210x 4 3 y 7 3?', choices: ['P = 3 210x4y7', 'P = 210xy² xy 3', 'P = 70xy² xy 3', 'P = 210xy² 3 x3y5'], topic: 'General', correct: 2 },
    { number: 14, part: 'A', text: 'The average cost of a gallon of milk in the United States between the years of 1995 and 2018 can be modeled by the equation P(t) = 20.0004t³ + 0.0114t² − 0.0150t + 2.6602, where P(t) represents the cost, in dollars, and t is time in years since January 1995. During this time period, in what year did P(t) reach its maximum?', choices: ['1995', '−014', '−013', '−018 Algebra II – Jan. ’24'], topic: 'Trigonometric Functions', correct: 1 },
    { number: 15, part: 'A', text: 'The temperature, F, in degrees Fahrenheit, after t hours of a roast put into an oven is given by the equation F = 325 − 185e20.4t. What was the temperature of the roast when it was put into the oven?', choices: ['325', '185', '−00', '140'], topic: 'Polynomial Functions', correct: 3 },
    { number: 16, part: 'A', text: 'The roots of the equation 0 = x² + 6x + 10 in simplest a + bi form are', choices: ['−3 6 2i', '−3 6 i', '−6 6 i', '−3 6 i 2'], topic: 'General', correct: 2 },
    { number: 17, part: 'A', text: 'Which equation does not represent an identity?', choices: ['x² − y² = (x + y)(x − y)', '(x − y)² = (x − y)(x − y)', '(x + y)² = x² + 2xy + y²', '(x + y)³ = x³ + 3xy + y³ Algebra II – Jan. ’24'], topic: 'General', correct: 3 },
    { number: 18, part: 'A', text: 'Two surveys were conducted to estimate the proportion of teens who use social media at least once per day. 100 Samples of = Teens 100 Samples of 50 Teens 0 Mean = 0.732 SD = 0.207 0 10 20 30 40 50 0.20 Proportion of Teens Who Use Social Media At Least Once Per Day 0.40 0.60 0.80 + 0.54 Mean = 0.742 SD = 0.057 0 10 20 30 0.60 0.66 Proportion of Teens Who Use Social Media At Least Once Per Day 0.72 0.78 0.84 0.90 0.96 Frequency Frequency Based on these results, it was determined that approximately 75% of teens use social media at least once per day. What is the best explanation of the difference in the results between the two surveys?', choices: ['The smaller sample size of five teens resulted in a smaller margin of error and should provide a more accurate estimate.', 'The smaller sample size of five teens resulted in a bigger margin of error and should provide a more accurate estimate.', 'The larger sample size of 50 teens resulted in a smaller margin of error and should provide a more accurate estimate.', 'The larger sample size of 50 teens resulted in a bigger margin of error and should provide a more accurate estimate.'], topic: 'Statistics & Probability', correct: 2, image: '/images/exams/alg2-january-2024/q18.png' },
    { number: 19, part: 'A', text: 'Given f(x) = x³ − 3 and f 21(x) = 3 x − 3b, the value of b is', choices: ['1', '3', '−1', '−3 Algebra II – Jan. ’24'], topic: 'General', correct: 1 },
    { number: 20, part: 'A', text: 'Robert is buying a car that costs $22,000. After a down payment of $4000, he borrows the remainder from a bank, a six year loan at 6.24% annual interest rate. The following formula can be used to calculate his monthly loan payment. R = (P)(i) 1 − (1 + i)2t R = monthly payment P = loan amount i = monthly interest rate t = time, in months Robert’s monthly payment will be', choices: ['$298.31', '$307.35', '$300.36', '$367.10'], topic: 'Trigonometric Functions', correct: 1 },
    { number: 21, part: 'A', text: 'Given tan q = − 3 4 where 2 π , q , p, what is the value of sec q?', choices: ['2 3 5', '5 4', '2 = 3', '3 5'], topic: 'Trigonometric Functions', correct: 0 },
    { number: 22, part: 'A', text: 'To solve the equation x + 7 1 = 7 x − 7 4 x x − 7 3x + 7, Joan’s first step is to multiply both sides by the least common denominator. Which statement is true?', choices: ['−14 is an extraneous solution.', '7 and 27 are extraneous solutions.', '7 is an extraneous solution.', 'There are no extraneous solutions. Algebra II – Jan. ’24'], topic: 'General', correct: 2 },
    { number: 23, part: 'A', text: 'Beginning July 1, 2019, Michelle deposited $250 into an account that yields 0.15% each month. She continued to make $250 deposits into this account on the first of each month for 3 years. Which expression represents the amount of money that was in the account after her last deposit was made on June 1, 2022?', choices: ['−50(1.0015)³', '−50 − 250(1.0015)³ 1 − 1.0015', '−50(1.0015)36', '−50 − 250(1.0015)36 1 − 1.0015'], topic: 'General', correct: 3 },
    { number: 24, part: 'A', text: 'A study of the red tailed hawk population in a given area shows the population, H(t), can be represented by the function H(t) = 50(1.19)t where t represents the number of years since the study began. In terms of the monthly rate of growth, the population can be best approximated by the function', choices: ['H(t) = 50(1.015)12t', 'H(t) = 50(1.19)12t', 'H(t) = 50(1.15) t 12', 'H(t) = 50(1.19) t 12 Algebra II – Jan. ’24'], topic: 'Trigonometric Functions', correct: 0 },
  ]
}
