// Algebra 2 Regents — June 2024
export default {
  "id": "a2-jun-2024",
  "subject": "algebra-2",
  "year": 2024,
  "session": "June",
  "totalMinutes": 180,
  "questions": [
    {
      "number": 1,
      "part": "A",
      "text": "Which expression is equivalent to (x² − 3x + 4) − (2x² + 5x − 1)?",
      "choices": [
        "−x² − 8x + 5",
        "−x² + 2x + 3",
        "x² − 8x + 5",
        "3x² + 2x + 3"
      ],
      "correct": 0,
      "topic": "Polynomial Functions",
      "explanation": "Distribute the negative sign: x² − 3x + 4 − 2x² − 5x + 1 = −x² − 8x + 5.",
      "diveDeep": "Subtracting polynomials requires distributing the negative across every term in the second polynomial, not just the first. A very common trap is forgetting to change the sign of the +1, which becomes +1 (since −(−1) = +1). Combine like terms by matching degrees: x² with x², x with x, constants with constants. Always rewrite the subtraction as adding the opposite before combining to avoid sign errors.",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 2,
      "part": "A",
      "text": "What are the zeros of the function f(x) = (x + 3)(x − 2)(x + 1)?",
      "choices": [
        "3, −2, 1",
        "−3, 2, −1",
        "−3, −2, −1",
        "3, 2, 1"
      ],
      "correct": 1,
      "topic": "Polynomial Functions",
      "explanation": "Setting each factor equal to zero gives x = −3, x = 2, and x = −1, which are the zeros.",
      "diveDeep": "The zeros of a factored polynomial come directly from the Zero Product Property: if a product equals zero, at least one factor is zero. The classic trap is sign confusion — the factor (x + 3) gives the zero x = −3, not +3, because you solve x + 3 = 0. A zero is the x-value where f(x) = 0, which is also where the graph crosses the x-axis. The factored form is the fastest route to zeros, so prefer factoring over expanding.",
      "subTopic": "Polynomial Graphs, Zeros & Conics",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 3,
      "part": "A",
      "text": "The expression i^45 is equivalent to",
      "choices": [
        "1",
        "−1",
        "i",
        "−i"
      ],
      "correct": 2,
      "topic": "Complex Numbers",
      "explanation": "Powers of i cycle every 4; since 45 ÷ 4 leaves remainder 1, i^45 = i^1 = i.",
      "diveDeep": "The imaginary unit follows the cycle i, −1, −i, 1, repeating every four powers. To evaluate any power of i, divide the exponent by 4 and use only the remainder: remainder 0 → 1, 1 → i, 2 → −1, 3 → −i. A common mistake is forgetting that i² = −1 and i⁴ = 1, which anchor the entire cycle. This same modular reasoning applies to simplifying any high power of i quickly.",
      "subTopic": "Complex Operations",
      "difficulty": 2,
      "difficultyRationale": "Basic application of the cyclic powers of i.",
      "isComplexSimplification": true
    },
    {
      "number": 4,
      "part": "A",
      "text": "Which expression is equivalent to √(−50)?",
      "choices": [
        "5i√2",
        "−5√2",
        "5√2",
        "25i√2"
      ],
      "correct": 0,
      "topic": "Complex Numbers",
      "explanation": "Factor out −1 and the perfect square: √(−50) = √(25·2·−1) = 5√2·i = 5i√2.",
      "diveDeep": "A negative under a square root introduces the imaginary unit i, since √(−1) = i. Separate the radical into the perfect-square factor, the remaining radical, and i. The trap here is leaving i under the radical or omitting it entirely and giving a real answer. Always pull out the largest perfect square (25 from 50) so the remaining radical (√2) is fully simplified.",
      "subTopic": "Complex Operations",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question.",
      "isComplexSimplification": true
    },
    {
      "number": 5,
      "part": "A",
      "text": "The solution set of the equation √(x + 6) = x is",
      "choices": [
        "{−2, 3}",
        "{3}",
        "{−2}",
        "{ }"
      ],
      "correct": 1,
      "topic": "Radical Equations",
      "explanation": "Squaring gives x + 6 = x², so x² − x − 6 = 0, x = 3 or x = −2; checking, only x = 3 satisfies the original equation.",
      "diveDeep": "Radical equations must always be checked for extraneous solutions because squaring both sides can introduce roots that do not satisfy the original equation. Here x = −2 fails because √(−2 + 6) = 2, not −2 (a principal square root is never negative). The reliable procedure is: isolate the radical, square both sides, solve the resulting polynomial, then substitute every candidate back into the original. Discarding the extraneous root is the most-tested step.",
      "subTopic": "Radical Expressions & Equations",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 6,
      "part": "A",
      "text": "When factored completely, the expression x³ + 2x² − 9x − 18 is equivalent to",
      "choices": [
        "(x² − 9)(x + 2)",
        "(x + 3)(x − 3)(x + 2)",
        "(x + 3)(x − 3)(x − 2)",
        "(x − 3)²(x + 2)"
      ],
      "correct": 1,
      "topic": "Polynomial Functions",
      "explanation": "Factor by grouping: x²(x + 2) − 9(x + 2) = (x² − 9)(x + 2) = (x + 3)(x − 3)(x + 2).",
      "diveDeep": "Factoring by grouping works when a four-term polynomial splits into two pairs that share a common binomial factor. After grouping you must continue factoring any difference of squares, since \"factored completely\" means no factor can be broken down further. The trap is stopping at (x² − 9)(x + 2), which is not complete because x² − 9 = (x + 3)(x − 3). Always check each factor for further factoring patterns.",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 7,
      "part": "A",
      "text": "The graph of y = log₂(x) is transformed to produce the graph of y = log₂(x − 3) + 1. Which describes the transformation?",
      "choices": [
        "right 3, up 1",
        "left 3, up 1",
        "right 3, down 1",
        "left 3, down 1"
      ],
      "correct": 0,
      "topic": "Exponential & Logarithmic",
      "explanation": "Subtracting 3 inside the function shifts right 3, and adding 1 outside shifts up 1.",
      "diveDeep": "For function transformations, changes inside the argument affect x horizontally and act opposite to their sign, while changes outside affect y vertically in the same direction as their sign. The persistent trap is reading (x − 3) as a shift left because of the minus sign; horizontal shifts are always counterintuitive. Confirm by noting that the input that makes the log argument equal 1 moves from x = 1 to x = 4. This logic applies identically to all parent-function transformations.",
      "skill": "graphing",
      "subTopic": "Logarithms",
      "difficulty": 3,
      "difficultyRationale": "Standard exponential equation solving using logarithms."
    },
    {
      "number": 8,
      "part": "A",
      "text": "Which equation represents a parabola with a focus of (0, 2) and a directrix of y = −2?",
      "choices": [
        "x² = 8y",
        "y² = 8x",
        "x² = 4y",
        "y² = 4x"
      ],
      "correct": 0,
      "topic": "Conic Sections",
      "explanation": "With vertex at the origin and p = 2 (distance from vertex to focus), x² = 4py = 8y.",
      "diveDeep": "A parabola is the set of points equidistant from the focus and directrix; the vertex lies halfway between them, here at the origin. The standard form x² = 4py opens vertically, with p being the signed distance from vertex to focus. The common error is confusing the coefficient 4p with p alone — since p = 2, 4p = 8. When the focus is above and the directrix below, the parabola opens upward, confirming the x² form.",
      "subTopic": "Polynomial Graphs, Zeros & Conics",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 9,
      "part": "A",
      "text": "What is the period of the function f(θ) = 3 sin(2θ) + 1?",
      "choices": [
        "π",
        "2π",
        "3",
        "1"
      ],
      "correct": 0,
      "topic": "Trigonometric Functions",
      "explanation": "The period of sine is 2π divided by the coefficient of θ: 2π ÷ 2 = π.",
      "diveDeep": "For a sinusoid in the form a·sin(bθ) + d, the period equals 2π/|b|, where b controls horizontal stretch or compression. The amplitude (a = 3) and vertical shift (d = 1) do not affect the period, which is a frequent distractor. A larger b compresses the graph and shortens the period. Always isolate the coefficient of the variable inside the trig function — not the leading coefficient — to compute the period.",
      "skill": "graphing",
      "subTopic": "Trig Graphs",
      "difficulty": 2,
      "difficultyRationale": "Basic identification of trigonometric properties."
    },
    {
      "number": 10,
      "part": "A",
      "text": "The solutions to the equation 3x² − 4x + 2 = 0 are",
      "choices": [
        "(2 ± i√2)/3",
        "(−2 ± i√2)/3",
        "(2 ± √2)/3",
        "(4 ± i√2)/3"
      ],
      "correct": 0,
      "topic": "Complex Numbers",
      "explanation": "Using the quadratic formula, x = (4 ± √(16 − 24))/6 = (4 ± √(−8))/6 = (2 ± i√2)/3.",
      "diveDeep": "When the discriminant b² − 4ac is negative, the quadratic has two complex-conjugate solutions. Here 16 − 24 = −8 introduces √(−8) = 2i√2, and dividing every term by the common factor 2 simplifies (4 ± 2i√2)/6 to (2 ± i√2)/3. The two most common errors are mishandling the negative under the radical and failing to reduce the fraction fully. Always simplify the radical and the fraction before selecting an answer.",
      "subTopic": "Complex Operations",
      "difficulty": 2,
      "difficultyRationale": "Basic complex number arithmetic and simplification.",
      "isComplexSimplification": true
    },
    {
      "number": 11,
      "part": "A",
      "text": "A culture of 1000 bacteria triples every 10 hours. Which expression models the number of bacteria in the sample after t hours?",
      "choices": [
        "1000(3)^(10t)",
        "1000(3)^(t/10)",
        "1000(10)^(3t)",
        "1000(t/10)^3"
      ],
      "correct": 1,
      "topic": "Exponential & Logarithmic",
      "explanation": "The base 3 represents tripling, and the exponent t/10 counts how many 10-hour tripling periods have passed.",
      "diveDeep": "Exponential growth follows the form A = A₀·b^(t/p), where b is the growth factor per period and p is the length of that period. \"Triples\" sets the base to 3, and \"every 10 hours\" means the exponent must be t/10 so that each 10 hours adds exactly one tripling. The classic trap is putting the period in the wrong place — using 10t would triple the bacteria far too fast. Sanity-check by plugging t = 10: 1000·3^1 = 3000, exactly tripled.",
      "skill": "modeling",
      "subTopic": "Exponential Models",
      "difficulty": 3,
      "difficultyRationale": "Standard exponential equation solving using logarithms."
    },
    {
      "number": 12,
      "part": "A",
      "text": "An initial investment of $5000 in an account earns 3.5% annual interest. Which function correctly represents a recursive model of the investment after n years?",
      "choices": [
        "aₙ = 5000(1.035)ⁿ",
        "aₙ = 5000 + 0.035n",
        "a₀ = 5000; aₙ = aₙ₋₁(1.035)",
        "a₀ = 5000; aₙ = aₙ₋₁ + 0.035"
      ],
      "correct": 2,
      "topic": "Sequences & Series",
      "explanation": "A recursive model defines the first term and builds each term from the previous one by multiplying by the growth factor 1.035.",
      "diveDeep": "A recursive formula has two parts: an initial value and a rule expressing each term in terms of the one before it. Compound interest multiplies the prior balance by (1 + r), so the recursive rule must use aₙ₋₁ · 1.035, not an explicit closed form with n in the exponent. The trap is choosing aₙ = 5000(1.035)ⁿ, which is the explicit (closed) form, not recursive. Also reject the additive options, since 3.5% is a rate of growth, not a fixed dollar amount per year.",
      "skill": "modeling",
      "subTopic": "Sequences",
      "difficulty": 2,
      "difficultyRationale": "Basic sequence parameter determination."
    },
    {
      "number": 13,
      "part": "A",
      "text": "Which expression is equivalent to (2x y²)³ · x² y?",
      "choices": [
        "8x⁵y⁷",
        "6x⁵y⁷",
        "8x⁵y⁶",
        "2x⁵y⁷"
      ],
      "correct": 0,
      "topic": "Polynomial Functions",
      "explanation": "Cube each factor: 2³x³y⁶ = 8x³y⁶, then multiply by x²y to get 8x⁵y⁷.",
      "diveDeep": "When raising a product to a power, the exponent distributes to every factor including the numerical coefficient, so 2³ = 8, not 6. Then apply the product rule, adding exponents on like bases: x³·x² = x⁵ and y⁶·y¹ = y⁷. The most common error is forgetting to cube the coefficient or only cubing one variable. Work the power-of-a-power step fully before multiplying the additional monomial.",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 14,
      "part": "A",
      "text": "Which statements must be true about the polynomial function k(x) = 2x³ − 11x² − 12x + 9? I. (x − 3) is a factor of k(x). II. k(0) = 9. III. k(x) divided by (x − 1) has a remainder of 5.",
      "choices": [
        "II, only",
        "II and III",
        "I and II",
        "I, II, and III"
      ],
      "correct": 0,
      "topic": "Polynomial Functions",
      "explanation": "k(0) = 9 (statement II) is true; k(3) ≠ 0 so (x − 3) is not a factor, and k(1) = −12 ≠ 5, so only II holds.",
      "diveDeep": "The Remainder Theorem says dividing k(x) by (x − a) leaves a remainder of k(a), and the Factor Theorem says (x − a) is a factor exactly when k(a) = 0. Evaluate each claim by substitution: k(0) = 9 confirms II instantly (it is just the constant term). For I, k(3) = 54 − 99 − 36 + 9 = −72 ≠ 0, so (x − 3) is not a factor. For III, k(1) = 2 − 11 − 12 + 9 = −12, not 5. Substituting the right value is faster and less error-prone than long division.",
      "skill": "procedure",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 15,
      "part": "A",
      "text": "To prepare for lacrosse tryouts, Kole is increasing the time he spends at the gym. This week he spends 150 minutes there and plans to increase this amount by 2% each week. The time, in minutes, t weeks from now is A(t) = 150(1.02)^t. In terms of a daily growth rate, the time Kole plans to spend can best be modeled by",
      "choices": [
        "A(t) = 150(1.14869)^(t/7)",
        "A(t) = 150(1.00283)^(t/7)",
        "A(t) = 150(1.14869)^(7t)",
        "A(t) = 150(1.00283)^(7t)"
      ],
      "correct": 3,
      "topic": "Exponential & Logarithmic",
      "explanation": "Since one week has 7 days, 1.02 = (daily factor)^7, so the daily factor is 1.02^(1/7) ≈ 1.00283, with exponent 7t to count days.",
      "diveDeep": "To rescale an exponential model from one time unit to another, rewrite the base so the exponent measures the new unit. Because 7 days equal one week, the weekly factor 1.02 equals the daily factor raised to the 7th power, giving daily factor = 1.02^(1/7) ≈ 1.00283. The exponent then becomes 7t because there are 7 days per week. The trap is pairing the daily base with t/7 or keeping the weekly base; verify by checking that at t = 1 week the model still returns 150(1.02).",
      "subTopic": "Exponential Models",
      "difficulty": 3,
      "difficultyRationale": "Standard exponential equation solving using logarithms."
    },
    {
      "number": 16,
      "part": "A",
      "text": "Mr. Zachary posts review assignments on the Betamath website for his students. On his last test, 49% of his students used Betamath and passed. Overall, 68% of his students used Betamath. Approximately what percentage of Mr. Zachary's students passed, given that they used Betamath?",
      "choices": [
        "19%",
        "33%",
        "49%",
        "72%"
      ],
      "correct": 3,
      "topic": "Statistics & Probability",
      "explanation": "Conditional probability P(pass | used) = P(passed and used) ÷ P(used) = 0.49 ÷ 0.68 ≈ 0.72, or 72%.",
      "diveDeep": "Conditional probability asks for the chance of one event given that another has occurred, computed as P(A and B) ÷ P(B). The given condition (used Betamath, 68%) becomes the denominator, and the joint event (used and passed, 49%) is the numerator. A frequent trap is subtracting the percentages or using 49% directly as the answer, ignoring the conditioning. Identify the \"given\" event first — that always anchors the denominator.",
      "subTopic": "Data Analysis",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 17,
      "part": "A",
      "text": "Given sin θ = 7/25 and θ terminates in Quadrant II, what is the value of tan θ?",
      "choices": [
        "−7/24",
        "−4/7",
        "7/24",
        "24/7"
      ],
      "correct": 0,
      "topic": "Trigonometric Functions",
      "explanation": "Using the Pythagorean identity, cos θ = −24/25 in Quadrant II, so tan θ = sin θ / cos θ = (7/25)/(−24/25) = −7/24.",
      "diveDeep": "In Quadrant II, sine is positive but cosine and tangent are negative (recall \"All Students Take Calculus\" for sign rules by quadrant). Find the missing leg with the Pythagorean relationship: with opposite 7 and hypotenuse 25, the adjacent side is 24, made negative in QII. Tangent is the ratio of sine to cosine, so the result is −7/24. The biggest trap is forgetting the quadrant sign and reporting a positive tangent.",
      "skill": "modeling",
      "subTopic": "Unit Circle & Radians",
      "difficulty": 3,
      "difficultyRationale": "Standard trigonometric ratio or function application."
    },
    {
      "number": 18,
      "part": "A",
      "text": "A family-owned grocery store employs 49 people whose ages are approximately normally distributed with a mean of 36 years and a standard deviation of 6.2 years. Ryan, newly hired, is 30 years old. How many employees would you expect to be younger than Ryan?",
      "choices": [
        "17",
        "41",
        "7",
        "8"
      ],
      "correct": 3,
      "topic": "Statistics & Probability",
      "explanation": "z = (30 − 36)/6.2 ≈ −0.97, giving about 16.6% below; 0.166 × 49 ≈ 8 people.",
      "diveDeep": "For normal-distribution problems, convert the raw value to a z-score using z = (x − μ)/σ, then use the normal cumulative area to find the proportion below it. Here z ≈ −0.97 corresponds to roughly 16.6% of the distribution, and multiplying by the population of 49 yields about 8 people. The trap is reporting the percentage rather than the count, or forgetting to round to a whole number of people. Always multiply the proportion by the total to get an expected count.",
      "subTopic": "Normal Distribution",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 19,
      "part": "A",
      "text": "For the function d(x) = ∛(x) + 2, the inverse function d⁻¹(x) equals",
      "choices": [
        "∛(x) + 2",
        "−∛(x) + 2",
        "(x + 2)³",
        "(x − 2)³"
      ],
      "correct": 3,
      "topic": "Functions",
      "explanation": "Swap x and y: x = ∛(y) + 2, then solve y = (x − 2)³.",
      "diveDeep": "To find an inverse, swap x and y and solve for the new y, which undoes the original operations in reverse order. Here d(x) takes a cube root then adds 2, so the inverse subtracts 2 then cubes: (x − 2)³. The trap is cubing before subtracting or forgetting to invert the order of operations. Verify by composing d(d⁻¹(x)) and checking it returns x.",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 20,
      "part": "A",
      "text": "Given f(x) = x⁴ + x³ − 3x² + 9x − 108 and f(3) = 0, which values satisfy f(x) = 0?",
      "choices": [
        "−4, 3 only",
        "±3i, −4, 3",
        "−3, 4 only",
        "±3i, 3, 4"
      ],
      "correct": 1,
      "topic": "Polynomial Functions",
      "explanation": "Dividing by (x − 3) gives x³ + 4x² + 9x + 36 = (x + 4)(x² + 9), whose zeros are −4 and ±3i, so all roots are ±3i, −4, 3.",
      "diveDeep": "A degree-4 polynomial has exactly four roots counting complex ones (Fundamental Theorem of Algebra). Knowing f(3) = 0 lets you factor out (x − 3) by synthetic division, reducing to a cubic that factors by grouping into (x + 4)(x² + 9). The factor x² + 9 yields complex roots x = ±3i, which test-takers often discard by mistake. Always account for complex conjugate pairs; a quartic with only two real roots must have two complex ones.",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 21,
      "part": "A",
      "text": "The profit function p(x) is found by subtracting the cost function c(x) from the revenue function r(x). Which function represents the cost function given p(x) = 15x² + 600x + 60 and r(x) = 20.4x² + 130x + 1200?",
      "choices": [
        "c(x) = 14.6x² + 470x − 1140",
        "c(x) = 14.6x² + 730x − 1260",
        "c(x) = 5.4x² − 470x + 1140",
        "c(x) = 5.4x² + 730x − 1260"
      ],
      "correct": 2,
      "topic": "Functions",
      "explanation": "Since p = r − c, then c = r − p = (20.4 − 15)x² + (130 − 600)x + (1200 − 60) = 5.4x² − 470x + 1140.",
      "diveDeep": "Profit equals revenue minus cost, so the cost function is recovered by rearranging to c(x) = r(x) − p(x). Subtract term by term, matching like degrees and carefully distributing the negative across all of p(x). The trap is reversing the subtraction (computing p − r) or mishandling the decimal coefficient 20.4 − 15 = 5.4. Line up the polynomials by degree before subtracting to keep terms aligned.",
      "skill": "modeling",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 22,
      "part": "A",
      "text": "What is the remainder when 4x³ − 3x + 3 is divided by x − 2?",
      "choices": [
        "−23",
        "13",
        "−7",
        "29"
      ],
      "correct": 3,
      "topic": "Polynomial Functions",
      "explanation": "By the Remainder Theorem, substitute x = 2: 4(8) − 3(2) + 3 = 32 − 6 + 3 = 29.",
      "diveDeep": "The Remainder Theorem states that the remainder of dividing a polynomial by (x − a) equals the polynomial evaluated at a, making substitution far faster than long division. Set x − 2 = 0 to find a = 2, then plug in carefully, watching the missing x² term (its coefficient is 0). The common error is using x = −2 instead of +2, or dropping the constant term. When only the remainder is needed, never bother with full division.",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 23,
      "part": "A",
      "text": "The parabola with equation 12(y + 1) = (x − 4)² has",
      "choices": [
        "a vertex at (4, 2)",
        "a focus at (4, 2)",
        "a directrix y = −4",
        "four units between the focus and vertex"
      ],
      "correct": 1,
      "topic": "Conic Sections",
      "explanation": "In form (x − 4)² = 12(y + 1), vertex is (4, −1) and 4p = 12 so p = 3; the focus is 3 units above the vertex at (4, 2).",
      "diveDeep": "Rewrite the parabola in standard form (x − h)² = 4p(y − k) to read off the vertex (h, k) and the focal distance p, where 4p is the coefficient of the (y − k) term. Here vertex (4, −1) and 4p = 12 give p = 3, placing the focus at (4, −1 + 3) = (4, 2) and the directrix at y = −1 − 3 = −4. The trap is misreading the vertex sign from (y + 1) or confusing 4p with p. The distance from vertex to focus is p = 3, not 4.",
      "subTopic": "Polynomial Graphs, Zeros & Conics",
      "difficulty": 3,
      "difficultyRationale": "Standard Regents Algebra 2 multiple-choice question."
    },
    {
      "number": 24,
      "part": "A",
      "text": "Jay is training for a bike race over fifteen weeks. At the end of the first week he has ridden ten miles, and he plans to increase his weekly distance by nine percent each week. Approximately how many miles total will he have ridden from the beginning of his training to the end of the fifteenth week?",
      "choices": [
        "10.989",
        "163.5",
        "293.4",
        "−93.609"
      ],
      "correct": 2,
      "topic": "Sequences & Series",
      "explanation": "This is a geometric series with a₁ = 10, r = 1.09, n = 15; Sₙ = 10(1 − 1.09¹⁵)/(1 − 1.09) ≈ 293.4 miles.",
      "diveDeep": "The total of repeated percentage-growth quantities is a geometric series, summed with Sₙ = a₁(1 − rⁿ)/(1 − r). Increasing by 9% sets the common ratio r = 1.09, the first term a₁ = 10, and n = 15 terms. The trap is computing only the 15th term (about 32.6 miles) instead of the cumulative sum, or using arithmetic-series logic. Identify whether the question asks for a single term or a running total before choosing the formula.",
      "subTopic": "Sequences",
      "difficulty": 2,
      "difficultyRationale": "Basic sequence parameter determination."
    },
    {
      "number": 25,
      "part": "B",
      "type": "written",
      "text": "Solve the equation 2x² − 5x + 4 = 0 for all values of x, expressing answers in simplest a + bi form.",
      "maxPoints": 2,
      "topic": "Complex Numbers",
      "modelAnswer": "Using the quadratic formula with a = 2, b = −5, c = 4: x = (5 ± √(25 − 32))/4 = (5 ± √(−7))/4 = (5 ± i√7)/4. So x = 5/4 + (√7/4)i and x = 5/4 − (√7/4)i.",
      "explanation": "The discriminant 25 − 32 = −7 is negative, producing complex-conjugate roots of the form a ± bi.",
      "diveDeep": "When a quadratic cannot factor over the reals, the quadratic formula handles all cases including complex roots. A negative discriminant signals two complex solutions that are conjugates of one another. Write √(−7) as i√7, then separate the real part 5/4 from the imaginary part (√7/4)i so the answer is in proper a + bi form. The most common point loss is leaving the answer as an undivided fraction or omitting i.",
      "skill": "procedure",
      "subTopic": "Complex Operations",
      "difficulty": 2,
      "difficultyRationale": "Basic complex number arithmetic and simplification.",
      "isComplexSimplification": true
    },
    {
      "number": 26,
      "part": "B",
      "type": "written",
      "text": "Determine algebraically the smallest value of n such that the sum of the first n terms of the geometric series 3 + 6 + 12 + ... exceeds 3000.",
      "maxPoints": 2,
      "topic": "Sequences & Series",
      "modelAnswer": "The series is geometric with a₁ = 3 and r = 2, so Sₙ = 3(2ⁿ − 1)/(2 − 1) = 3(2ⁿ − 1). Set 3(2ⁿ − 1) > 3000, so 2ⁿ − 1 > 1000, 2ⁿ > 1001, n > log₂(1001) ≈ 9.97. The smallest integer is n = 10.",
      "explanation": "The geometric sum formula gives 3(2ⁿ − 1); solving the inequality with logarithms yields n ≈ 9.97, so n = 10.",
      "diveDeep": "Use the geometric series sum Sₙ = a₁(rⁿ − 1)/(r − 1) and set it greater than the threshold to form an exponential inequality. Solve by isolating the power and applying a logarithm: n > log₂(1001). Because n must be a whole number of terms, round up to the next integer even though 9.97 is close to 10. The trap is rounding down or forgetting that \"exceeds\" requires a strict inequality.",
      "subTopic": "Series",
      "difficulty": 2,
      "difficultyRationale": "Basic sequence parameter determination."
    },
    {
      "number": 27,
      "part": "B",
      "type": "written",
      "text": "The height, in feet, of a Ferris wheel car above the ground after t seconds is modeled by h(t) = 25 sin((π/15)(t − 7.5)) + 30. State the maximum height of the car and the number of seconds it takes to complete one full revolution.",
      "maxPoints": 2,
      "topic": "Trigonometric Functions",
      "modelAnswer": "The amplitude is 25 and the midline is 30, so the maximum height is 30 + 25 = 55 feet. The period is 2π ÷ (π/15) = 2π · (15/π) = 30 seconds, so one full revolution takes 30 seconds.",
      "explanation": "Maximum equals midline plus amplitude (30 + 25 = 55), and the period equals 2π divided by the coefficient π/15, giving 30 seconds.",
      "diveDeep": "A sinusoidal model a·sin(b(t − c)) + d has amplitude |a|, midline d, maximum d + |a|, minimum d − |a|, and period 2π/|b|. The maximum is reached when the sine equals 1, adding the full amplitude to the midline. The period describes one complete cycle — one revolution of the wheel — and depends only on b, not on the amplitude or phase shift. A common error is dividing by the wrong quantity or forgetting to add the midline to the amplitude for the maximum.",
      "skill": "modeling",
      "subTopic": "Unit Circle & Radians",
      "difficulty": 3,
      "difficultyRationale": "Standard trigonometric ratio or function application."
    },
    {
      "number": 28,
      "part": "B",
      "type": "written",
      "text": "Algebraically determine the values of x that satisfy the equation (x + 2)/(x − 3) = 4/(x − 1).",
      "maxPoints": 2,
      "topic": "Rational Functions",
      "modelAnswer": "Cross-multiply: (x + 2)(x − 1) = 4(x − 3). Expand: x² + x − 2 = 4x − 12. So x² − 3x + 10 = 0. The discriminant is 9 − 40 = −31 < 0, so there are no real solutions. (If complex are allowed: x = (3 ± i√31)/2.)",
      "explanation": "Cross-multiplying yields x² − 3x + 10 = 0, whose negative discriminant means no real solutions exist.",
      "diveDeep": "Rational equations are solved by cross-multiplying (or clearing denominators) and then solving the resulting polynomial, while excluding any value that makes a denominator zero (x ≠ 3, x ≠ 1 here). After simplifying to a quadratic, check the discriminant: a negative value (here −31) means no real roots. The trap is overlooking restricted values or assuming a quadratic always has real solutions. Always state restrictions and test the discriminant before concluding.",
      "subTopic": "Rational Expressions & Equations",
      "difficulty": 3,
      "difficultyRationale": "Standard Part II open-ended question requiring multi-step math steps."
    },
    {
      "number": 29,
      "part": "B",
      "type": "written",
      "text": "Over the course of a year, the average monthly temperature in a city can be modeled by a cosine function. Explain why a sinusoidal function is an appropriate model for this data, and identify what real-world quantity the period of the function represents.",
      "maxPoints": 2,
      "topic": "Trigonometric Functions",
      "modelAnswer": "A sinusoidal function is appropriate because monthly temperatures rise and fall in a smooth, repeating pattern that cycles once each year, just as sine and cosine repeat at regular intervals. The period of the function represents the length of one full temperature cycle — twelve months, or one year.",
      "explanation": "Temperatures repeat predictably each year, matching the periodic behavior of sinusoids; the period corresponds to one complete yearly cycle of 12 months.",
      "diveDeep": "Sinusoidal models fit any phenomenon that oscillates smoothly between a maximum and minimum and repeats over equal intervals, such as seasonal temperature, tides, or daylight hours. The period is the real-world length of one complete cycle, here one calendar year. A strong answer connects the math feature (periodicity) to the context (annual seasons) explicitly. The common shortfall is describing the graph without tying the period to a concrete real-world duration.",
      "skill": "reasoning",
      "subTopic": "Trig Graphs",
      "difficulty": 2,
      "difficultyRationale": "Basic identification of trigonometric properties."
    },
    {
      "number": 30,
      "part": "B",
      "type": "written",
      "text": "Solve for x: log₃(x) + log₃(x − 6) = 3. Show your work and state any rejected values.",
      "maxPoints": 2,
      "topic": "Exponential & Logarithmic",
      "modelAnswer": "Combine logs: log₃(x(x − 6)) = 3, so x(x − 6) = 3³ = 27. Then x² − 6x − 27 = 0, which factors as (x − 9)(x + 3) = 0, giving x = 9 or x = −3. Since logarithm arguments must be positive, x = −3 is rejected (x − 6 would be negative). The solution is x = 9.",
      "explanation": "Combining logs and rewriting in exponential form gives x² − 6x − 27 = 0; only x = 9 keeps both arguments positive.",
      "diveDeep": "Use the product rule log_b(M) + log_b(N) = log_b(MN) to combine logs, then convert to exponential form to remove the logarithm. The resulting quadratic may produce extraneous solutions because logarithms are only defined for positive arguments. Always check each candidate against the domain restriction x > 6 here; x = −3 fails and must be rejected. Forgetting the domain check is the single most common point loss on log equations.",
      "skill": "procedure",
      "subTopic": "Logarithms",
      "difficulty": 3,
      "difficultyRationale": "Standard exponential equation solving using logarithms."
    },
    {
      "number": 31,
      "part": "B",
      "type": "written",
      "text": "A biologist models a population of fish with the function P(t) = 5000/(1 + 4e^(−0.3t)), where t is in years. Determine the carrying capacity of the population and explain what the carrying capacity means in this context.",
      "maxPoints": 2,
      "topic": "Exponential & Logarithmic",
      "modelAnswer": "As t increases without bound, e^(−0.3t) approaches 0, so P(t) approaches 5000/(1 + 0) = 5000. The carrying capacity is 5000 fish. This means the population grows over time but levels off, approaching a maximum sustainable size of 5000 fish that the environment can support.",
      "explanation": "As t → ∞ the exponential term vanishes, leaving P → 5000, the maximum population the environment sustains.",
      "diveDeep": "A logistic function P(t) = L/(1 + ae^(−kt)) describes growth that slows as it nears an upper limit L, the carrying capacity. The carrying capacity is found by letting t grow large so the exponential term decays to zero, leaving the numerator. Contextually it is the maximum population an environment can sustain long-term, not the starting value. A frequent error is reporting the initial population P(0) = 1000 instead of the limiting value.",
      "skill": "reasoning",
      "subTopic": "Exponential Models",
      "difficulty": 3,
      "difficultyRationale": "Standard exponential equation solving using logarithms."
    },
    {
      "number": 32,
      "part": "B",
      "type": "written",
      "text": "Solve algebraically for x: 6/(x + 5) + 1/(x − 2) = 8/(x² + 3x − 10). Note: x² + 3x − 10 = (x + 5)(x − 2)",
      "maxPoints": 2,
      "topic": "Rational Functions",
      "modelAnswer": "Factor the denominator on the right: x² + 3x − 10 = (x + 5)(x − 2). Multiply every term by (x + 5)(x − 2): 6(x − 2) + 1(x + 5) = 8. Expand: 6x − 12 + x + 5 = 8, so 7x − 7 = 8, giving 7x = 15, x = 15/7. Check that x = 15/7 does not make either denominator zero (x ≠ −5 and x ≠ 2, which it does not), so x = 15/7.",
      "explanation": "Multiplying through by the common denominator (x + 5)(x − 2) clears all fractions and yields the linear equation 7x − 7 = 8, so x = 15/7.",
      "diveDeep": "When all denominators share a common factored form, multiply every term by the LCD to clear the fractions in one step. The hint that x² + 3x − 10 = (x + 5)(x − 2) signals that the right-side denominator is already the LCD, making multiplication straightforward. Always state and check the excluded values (x ≠ −5, x ≠ 2) after solving; if a solution equals an excluded value it must be discarded as extraneous. Here x = 15/7 is valid, so no rejection is needed.",
      "skill": "procedure",
      "subTopic": "Rational Expressions & Equations",
      "difficulty": 3,
      "difficultyRationale": "Standard Part II open-ended question requiring multi-step math steps."
    },
    {
      "number": 33,
      "part": "C",
      "type": "written",
      "text": "Solve the following system of equations algebraically: y = x² − 2x − 3 and y = 2x − 3. State all solutions as ordered pairs.",
      "maxPoints": 4,
      "topic": "Polynomial Functions",
      "modelAnswer": "Set the expressions equal: x² − 2x − 3 = 2x − 3. Then x² − 4x = 0, so x(x − 4) = 0, giving x = 0 or x = 4. For x = 0: y = 2(0) − 3 = −3, so (0, −3). For x = 4: y = 2(4) − 3 = 5, so (4, 5). The solutions are (0, −3) and (4, 5).",
      "explanation": "Substituting the linear equation into the quadratic gives x² − 4x = 0, yielding x = 0 and x = 4 with their corresponding y-values.",
      "diveDeep": "Solve a quadratic-linear system by substitution: replace y in one equation with the expression from the other, then solve the resulting quadratic. Each x-value must be paired with its y-value to form an ordered pair — solving for x alone earns only partial credit. The number of solutions reflects how many times the line meets the parabola (here two intersection points). Always substitute back into the simpler equation to find y accurately.",
      "skill": "procedure",
      "subTopic": "Polynomial Operations & Factoring",
      "difficulty": 3,
      "difficultyRationale": "Standard algebraic solution of a linear-quadratic system."
    },
    {
      "number": 34,
      "part": "C",
      "type": "written",
      "text": "The number of subscribers to a streaming service, in thousands, is recorded each year. After 2 years there were 80 thousand subscribers, and after 5 years there were 270 thousand. Assuming exponential growth of the form S(t) = a·bᵗ, determine a and b to the nearest hundredth, and predict the number of subscribers after 8 years.",
      "maxPoints": 4,
      "topic": "Exponential & Logarithmic",
      "modelAnswer": "From S(2) = ab² = 80 and S(5) = ab⁵ = 270, divide: b³ = 270/80 = 3.375, so b = ∛3.375 = 1.50. Then a = 80/b² = 80/2.25 ≈ 35.56. So S(t) ≈ 35.56(1.50)ᵗ. After 8 years: S(8) = 35.56(1.50)⁸ ≈ 35.56(25.63) ≈ 911 thousand subscribers.",
      "explanation": "Dividing the two equations isolates b³ = 3.375 so b = 1.50; back-substitution gives a ≈ 35.56, and S(8) ≈ 911 thousand.",
      "diveDeep": "To fit an exponential model from two data points, set up two equations and divide them so the coefficient a cancels, leaving a single equation in b. The difference in exponents (5 − 2 = 3) becomes the root you take to solve for b. After finding b, substitute back into either original equation to find a, then evaluate the model at the requested time. The biggest pitfalls are arithmetic with the fractional exponent and rounding b too early, which compounds error in the final prediction.",
      "skill": "modeling",
      "subTopic": "Exponential Models",
      "difficulty": 4,
      "difficultyRationale": "Part III multi-step mathematical modeling or complex algebraic analysis."
    },
    {
      "number": 35,
      "image": "/images/exams/alg2-june-2024/q35.png",
      "part": "C",
      "type": "written",
      "text": "The table below shows the median house price (in thousands of dollars) in Skaneateles, NY from 2010 to 2018.\n\nYear:  2010  2011  2012  2013  2014  2015  2016  2017  2018\nPrice: 254   232   235   281   290   318   332   365   385\n\n(a) Write the linear regression equation for these data, rounding all values to the nearest dollar. Let x = 0 represent 2010.\n(b) State the average rate of change in median house price from 2010 to 2018 to the nearest dollar per year.\n(c) Explain what this rate of change means as it relates to median house prices in Skaneateles.",
      "maxPoints": 4,
      "topic": "Statistics & Probability",
      "modelAnswer": "(a) Entering the data with x = 0 for 2010 through x = 8 for 2018 and performing linear regression yields approximately y = 17,975x + 231,500 (values rounded to the nearest dollar; calculator output may vary slightly). (b) The slope of the regression line is the average rate of change: approximately $17,975 per year. (c) This means that, on average, the median house price in Skaneateles increased by about $17,975 each year from 2010 to 2018.",
      "explanation": "Linear regression on the nine data points produces a slope of roughly $17,975/year, which is both the regression coefficient and the average rate of change over the interval.",
      "diveDeep": "Linear regression finds the line of best fit by minimizing squared residuals; on the Regents you enter the data into lists and use LinReg(ax+b). The slope of a linear model equals the average rate of change over any interval, so you do not need a separate calculation once the regression is done. Rounding to the nearest dollar means rounding both the slope and intercept to whole numbers. For part (c), always interpret the slope in context — attach the correct units (dollars per year) and reference the specific location and time frame mentioned in the problem.",
      "skill": "reasoning",
      "subTopic": "Data Analysis",
      "difficulty": 4,
      "difficultyRationale": "Part III multi-step mathematical modeling or complex algebraic analysis."
    },
    {
      "number": 36,
      "part": "C",
      "type": "written",
      "text": "A sporting goods manufacturer surveyed 50 randomly chosen customers; 40 said they purchase both game-regulation pucks and lighter training pucks (sample proportion = 40/50 = 0.80). A simulation run 100 times produced approximately normal results with mean = 0.795 and standard deviation = 0.085.\n\n(a) Determine an interval containing the middle 95% of plausible proportions estimating the proportion of all customers who would purchase both types of hockey pucks.\n(b) The company will continue to manufacture both types of pucks if the true proportion of customers who would purchase both is above 0.60. Using the interval from part (a), explain whether or not the company should continue to produce both types of hockey pucks.",
      "maxPoints": 4,
      "topic": "Statistics & Probability",
      "modelAnswer": "(a) For a 95% interval, use mean ± 2(SD): 0.795 − 2(0.085) = 0.795 − 0.170 = 0.625 and 0.795 + 2(0.085) = 0.795 + 0.170 = 0.965. The interval is (0.625, 0.965). (b) The entire interval (0.625, 0.965) lies above 0.60, so all plausible values of the true proportion exceed the threshold. The company should continue to manufacture both types of hockey pucks because the evidence strongly suggests the true proportion of customers who buy both is greater than 0.60.",
      "explanation": "The 95% interval is mean ± 2SD = (0.625, 0.965); since every value in this interval exceeds 0.60, the data support continuing production of both puck types.",
      "diveDeep": "When simulation results are approximately normal, the middle 95% of values falls within two standard deviations of the mean, giving the interval (mean − 2SD, mean + 2SD). This is an empirical 95% confidence interval for the true population proportion. To answer the decision question, check whether the threshold value (0.60) falls inside, below, or above the interval: if the entire interval is above the threshold, there is strong evidence the true proportion exceeds it. A common error is using 1.96 instead of the prescribed 2 for simulation-based intervals, or failing to connect the interval explicitly to the business decision.",
      "skill": "reasoning",
      "subTopic": "Normal Distribution",
      "difficulty": 4,
      "difficultyRationale": "Part III multi-step mathematical modeling or complex algebraic analysis."
    },
    {
      "number": 37,
      "part": "D",
      "type": "written",
      "text": "A medical researcher studies whether a new drug reduces recovery time. In a randomized experiment, the treatment group had a mean recovery time 2.5 days shorter than the control group. Using a simulation of 200 re-randomizations under the null hypothesis of no difference, only 6 of the 200 differences were at least 2.5 days. (a) Estimate the probability that a difference of at least 2.5 days would occur by chance. (b) Based on this, should the researcher conclude the drug is effective? Justify your answer.",
      "maxPoints": 6,
      "topic": "Statistics & Probability",
      "modelAnswer": "(a) The estimated probability is 6/200 = 0.03, or 3%. (b) Because the observed difference of 2.5 days would happen by chance only about 3% of the time under the null hypothesis (well below the common 5% threshold), the result is statistically significant. The researcher has strong evidence that the difference is due to the drug rather than random chance, so it is reasonable to conclude the drug is effective at reducing recovery time.",
      "explanation": "Only 6 of 200 simulated differences reached 2.5 days, giving a probability of 0.03; since this is below 5%, the result is unlikely by chance and supports the drug's effectiveness.",
      "diveDeep": "A randomization (re-randomization) test estimates how often an observed result would occur purely by chance under the null hypothesis of no effect, by repeatedly shuffling group labels. The proportion of simulated outcomes as extreme as the observed one is an empirical p-value; a value below about 5% is conventionally treated as statistically significant evidence against the null. To earn full credit you must both compute the proportion correctly and tie the small probability to a clear, justified conclusion. A common error is concluding effectiveness without referencing the low probability, or vice versa.",
      "skill": "reasoning",
      "subTopic": "Sampling & Studies",
      "difficulty": 5,
      "difficultyRationale": "Part IV constructed-response requiring multi-step modeling and comparison."
    }
  ]
}
