export const LE_TOPIC_KEYWORDS = {
  'Cell Biology': [
    'cell membrane', 'organelle', 'mitochondria', 'nucleus', 'vacuole',
    'ribosome', 'cytoplasm', 'cell wall', 'chloroplast', 'diffusion',
    'osmosis', 'active transport', 'ATP', 'metabolic', 'organelles', 'cells',
    'endoplasmic', 'golgi', 'lysosome', 'selective permeability', 'concentration',
    'membrane', 'transport protein', 'energy', 'photosynthesis', 'cellular respiration',
  ],
  'Genetics': [
    'DNA', 'gene', 'chromosome', 'mutation', 'allele', 'dominant', 'recessive',
    'heredity', 'genetic', 'inherit', 'trait', 'offspring', 'protein synthesis',
    'RNA', 'mRNA', 'codon', 'base sequence', 'nucleotide', 'amino acid',
    'phenotype', 'genotype', 'punnett', 'clone', 'selective breeding',
    'transcription', 'translation', 'base pair', 'double helix', 'plasmid',
    'recombinant', 'biotechnology', 'gel electrophoresis', 'karyotype', 'sex-linked',
  ],
  'Evolution': [
    'evolution', 'natural selection', 'adaptation', 'species', 'fossil',
    'extinction', 'variation', 'fitness', 'ancestor', 'common ancestor',
    'Darwin', 'biodiversity', 'geographic isolation', 'speciation',
    'homologous', 'vestigial', 'divergent', 'convergent evolution', 'selection pressure',
    'gene pool', 'mutation rate', 'reproductive isolation', 'gradualism', 'punctuated',
  ],
  'Ecology': [
    'ecosystem', 'food web', 'food chain', 'population', 'community',
    'biome', 'habitat', 'predator', 'prey', 'decomposer', 'producer',
    'consumer', 'energy pyramid', 'niche', 'succession', 'limiting factor',
    'carrying capacity', 'invasive', 'pollution', 'biodiversity', 'abiotic', 'biotic',
    'symbiosis', 'mutualism', 'parasitism', 'commensalism', 'nutrient cycle',
    'nitrogen cycle', 'carbon cycle', 'water cycle', 'trophic level', 'biomass',
  ],
  'Human Body': [
    'hormone', 'enzyme', 'immune', 'antibody', 'pathogen', 'disease',
    'organ', 'blood', 'digestion', 'respiration', 'nervous system',
    'homeostasis', 'feedback', 'vaccination', 'insulin', 'receptor',
    'kidney', 'liver', 'lung', 'heart', 'brain', 'glucose', 'diabetes',
    'endocrine', 'circulatory', 'digestive', 'excretory', 'lymph',
    'white blood cell', 'red blood cell', 'neuron', 'synapse', 'stimulus',
  ],
  'Reproduction': [
    'reproduction', 'sexual', 'asexual', 'fertilization', 'embryo',
    'development', 'gamete', 'sperm', 'egg', 'mitosis', 'meiosis',
    'cell division', 'zygote', 'fetus', 'differentiation', 'stem cell',
    'binary fission', 'budding', 'regeneration', 'vegetative', 'cloning',
    'chromosome number', 'haploid', 'diploid', 'ovum', 'placenta',
  ],
}

export const ES_TOPIC_KEYWORDS = {
  'Geology': [
    'rock', 'mineral', 'erosion', 'sediment', 'stratum', 'igneous',
    'sedimentary', 'metamorphic', 'crystal', 'weathering', 'deposition',
    'soil', 'bedrock', 'core', 'mantle', 'crust', 'density', 'silicate',
    'granite', 'basalt', 'limestone', 'sandstone', 'shale', 'quartz',
    'hardness', 'cleavage', 'fracture', 'luster', 'streak', 'intrusive', 'extrusive',
  ],
  'Plate Tectonics': [
    'plate', 'tectonic', 'earthquake', 'volcano', 'fault', 'subduction',
    'divergent', 'convergent', 'transform', 'magma', 'seismic', 'Richter',
    'tsunami', 'mid-ocean ridge', 'trench', 'lithosphere', 'mantle',
    'epicenter', 'focus', 'P-wave', 'S-wave', 'hot spot', 'rift zone',
    'seafloor spreading', 'continental drift', 'convection current', 'Pangaea',
  ],
  'Geologic Time': [
    'fossil', 'geologic time', 'era', 'period', 'epoch', 'Paleozoic',
    'Mesozoic', 'Cenozoic', 'radioactive', 'half-life', 'carbon dating',
    'extinction', 'index fossil', 'relative age', 'absolute age', 'strata',
    'Precambrian', 'Cambrian', 'Ordovician', 'Devonian', 'Permian', 'Triassic',
    'Jurassic', 'Cretaceous', 'unconformity', 'superposition', 'correlation',
  ],
  'Meteorology': [
    'weather', 'atmosphere', 'humidity', 'precipitation', 'front',
    'storm', 'temperature', 'pressure', 'wind', 'cloud', 'air mass',
    'barometer', 'anemometer', 'dew point', 'isobar', 'cyclone', 'tornado',
    'cold front', 'warm front', 'occluded', 'stationary front', 'relative humidity',
    'psychrometer', 'sling psychrometer', 'station model', 'visibility', 'fog',
  ],
  'Climate': [
    'climate', 'global warming', 'greenhouse', 'carbon dioxide', 'ice age',
    'biome', 'solar radiation', 'albedo', 'latitude', 'ocean current',
    'El Niño', 'monsoon', 'drought', 'CO2', 'fossil fuel', 'emissions',
    'ozone', 'ultraviolet', 'deforestation', 'climate change', 'sea level',
    'Arctic', 'Antarctic', 'permafrost', 'tundra', 'temperate', 'tropical',
  ],
  'Astronomy': [
    'star', 'planet', 'solar', 'galaxy', 'orbit', 'moon', 'sun', 'comet',
    'meteor', 'telescope', 'light year', 'universe', 'black hole', 'nebula',
    'Milky Way', 'gravity', 'red shift', 'Hertzsprung', 'magnitude', 'eclipse',
    'asteroid', 'luminosity', 'spectral class', 'main sequence', 'red giant',
    'white dwarf', 'supernova', 'neutron star', 'parsec', 'parallax', 'retrograde',
  ],
  'Water Cycle': [
    'water cycle', 'evaporation', 'condensation', 'precipitation', 'runoff',
    'groundwater', 'transpiration', 'aquifer', 'watershed', 'drainage basin',
    'stream', 'river', 'glacier', 'water table', 'permeability',
    'infiltration', 'porosity', 'capillary', 'water vapor', 'humidity',
    'delta', 'meander', 'tributary', 'discharge', 'velocity',
  ],
  'Maps': [
    'topographic', 'latitude', 'longitude', 'contour', 'map', 'elevation',
    'coordinate', 'gradient', 'scale', 'profile', 'isolines', 'degree',
    'UTM', 'Mercator', 'projection', 'isotherm', 'compass', 'bearing',
    'meridian', 'parallel', 'prime meridian', 'equator', 'azimuth',
    'contour interval', 'index contour', 'relief', 'cross-section',
  ],
}
