// Earth Science Regents — August 2018
export default {
  id: 'ea-aug-2018',
  subject: 'earth-science',
  year: 2018,
  session: 'August',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'The diagram below represents a sundial positioned in New York State. During daylight, the shadow cast by the gnomon (pointer) moves across the disc, with the tip of the shadow pointing to the time of day. This motion of the gnomon\'s shadow on the sundial is mainly due to',
      choices: ['Earth\'s rotation', 'Earth\'s revolution', 'the Sun\'s rotation', 'the Sun\'s revolution'],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-august-2018/q1.png',
      explanation: 'Earth rotates on its axis once every 24 hours, causing the Sun to appear to move across the sky from east to west, which moves the gnomon\'s shadow throughout the day.',
      diveDeep: 'Earth\'s rotation (not revolution) is responsible for the daily apparent motion of the Sun. Revolution is the yearly orbit around the Sun and causes seasonal changes, not daily shadow movement. The Sun does rotate on its own axis, but this has no effect on shadows seen from Earth. A common mistake is confusing rotation (daily) with revolution (yearly). Sundials work because Earth\'s rotation rate is nearly constant at 15° per hour.',
    },
    {
      number: 2, part: 'A',
      text: 'The formation of the planet Uranus is estimated to have occurred approximately',
      choices: ['100,000 million years ago', '2.0 billion years ago', '4.6 billion years ago', '13.7 billion years ago'],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'All planets in our solar system formed approximately 4.6 billion years ago from the same solar nebula, a rotating cloud of gas and dust that collapsed under gravity.',
      diveDeep: 'The 4.6 billion year age applies to the entire solar system — the Sun, Earth, and all other planets formed from the same protoplanetary disk. The age 13.7–13.8 billion years refers to the Big Bang (origin of the universe), not the solar system. The age 2.0 billion years has no particular planetary significance. Students often confuse the age of the solar system with the age of the universe; remember: solar system ≈ 4.6 bya, universe ≈ 13.8 bya.',
    },
    {
      number: 3, part: 'A',
      text: 'Compared to the Jovian planets in our solar system, the terrestrial planets have',
      choices: ['less mass and are less dense', 'less mass and are more dense', 'more mass and are less dense', 'more mass and are more dense'],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'Terrestrial planets (Mercury, Venus, Earth, Mars) are composed primarily of rock and metal, giving them higher densities, but they are much smaller and less massive than the gas-giant Jovian planets.',
      diveDeep: 'This is a classic compare-and-contrast question. Jovian planets (Jupiter, Saturn, Uranus, Neptune) are enormous in size and mass but composed mostly of hydrogen and helium gases, making them less dense — Saturn is even less dense than water. Terrestrial planets are rocky and metallic with densities around 4–6 g/cm³, while Jovian planets average 0.7–1.6 g/cm³. A common mistake is assuming bigger means denser; that is not true here. Remember: terrestrial = rocky/dense/small mass; Jovian = gaseous/low density/large mass.',
    },
    {
      number: 4, part: 'A',
      text: 'The diagram below represents the constellation Leo that can be seen by an observer in New York State at midnight during March. Leo is not visible to this observer at midnight during September because',
      choices: ['Leo has rotated on its axis', 'Leo has revolved in its orbit around the Sun', 'Earth has rotated on its axis', 'Earth has revolved in its orbit around the Sun'],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-august-2018/q4.png',
      explanation: 'As Earth orbits the Sun over a year, the nighttime side of Earth faces different parts of the sky in different seasons, making certain constellations visible only in certain months.',
      diveDeep: 'Constellations are not visible year-round because Earth\'s revolution around the Sun shifts our nighttime view. In September, Leo is in the part of the sky that faces toward the Sun during the day, so it cannot be seen at night. Daily rotation causes stars to appear to move across the sky each night, but it doesn\'t explain the seasonal disappearance of constellations. Constellations themselves don\'t orbit the Sun — this is always an incorrect distractor. A useful rule: the constellation you can\'t see is the one in the direction of the Sun.',
    },
    {
      number: 5, part: 'A',
      text: 'An observer in New York City measured the angle of insolation at solar noon each day. During which month did this observer see the noontime angle of insolation increase each day?',
      choices: ['April', 'July', 'September', 'December'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'From the winter solstice (late December) through the summer solstice (late June), the noontime Sun angle increases daily in New York; April falls within this period of increasing Sun angles.',
      diveDeep: 'The noontime angle of insolation increases as the Sun moves higher in the sky from winter to summer solstice. In July, the Sun angle has just passed its maximum and begins decreasing. In September, the angle is decreasing. In December, the angle is near its minimum and just beginning to increase. April is well within the increasing phase (December → June). Students commonly choose July (the hottest month) forgetting that the angle peaks at summer solstice in late June, not in July.',
    },
    {
      number: 6, part: 'A',
      text: 'The Coriolis effect occurs as a result of Earth\'s',
      choices: ['rotation', 'revolution', 'tilted axis', 'magnetic field'],
      topic: 'Meteorology',
      correct: 0,
      explanation: 'The Coriolis effect is caused by Earth\'s rotation, which deflects moving objects (air, water) to the right in the Northern Hemisphere and to the left in the Southern Hemisphere.',
      diveDeep: 'Earth\'s rotation means that different latitudes move at different speeds — the equator moves fastest (about 1670 km/h) while the poles barely move at all. This speed differential causes moving air and water to curve. This is why hurricanes spin counterclockwise in the Northern Hemisphere. Revolution (orbit around the Sun) affects seasons, not wind deflection. Earth\'s tilt causes seasons and changes in Sun angle. A common mistake is attributing the Coriolis effect to Earth\'s tilt; remember it is always rotation.',
    },
    {
      number: 7, part: 'A',
      text: 'During the process of condensation, water vapor',
      choices: ['releases 334 J/g of heat energy', 'releases 2260 J/g of heat energy', 'gains 334 J/g of heat energy', 'gains 2260 J/g of heat energy'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'Condensation is the change from gas (water vapor) to liquid, a process that releases 2260 J/g of latent heat energy to the surroundings.',
      diveDeep: 'The value 334 J/g is associated with melting/freezing (the latent heat of fusion), not condensation/evaporation. Condensation releases energy because the water molecules are losing kinetic energy as they move from a high-energy gas state to a lower-energy liquid state. This released latent heat is what fuels powerful storms like hurricanes. Evaporation, the reverse process, requires 2260 J/g of energy input. Remember: condensation and freezing both release energy; evaporation and melting both require energy.',
    },
    {
      number: 8, part: 'A',
      text: 'Infiltration is generally greater than runoff where the land has a',
      choices: ['gentle slope and permeable soil', 'gentle slope and impermeable bedrock', 'steep slope and permeable soil', 'steep slope and impermeable bedrock'],
      topic: 'Water Cycle',
      correct: 0,
      explanation: 'A gentle slope slows water movement, giving it time to infiltrate, and permeable soil has pore spaces that allow water to soak in rather than run off the surface.',
      diveDeep: 'Both slope angle and soil permeability affect the infiltration-to-runoff ratio. Steep slopes give water little time to infiltrate before gravity pulls it downhill as runoff. Impermeable material (clay, bedrock) prevents water from soaking in at all. Gentle slopes and permeable soils together maximize infiltration. This combination is why forested hillsides with sandy soils have much lower flood risks than paved urban areas. Students often focus on only one factor; both must favor infiltration for it to exceed runoff.',
    },
    {
      number: 9, part: 'A',
      text: 'Nearly 90% of the water vapor that enters Earth\'s atmosphere comes from the evaporation of Earth\'s surface waters. Most of the remaining 10% is water vapor that enters the atmosphere through',
      choices: ['precipitation from clouds', 'transpiration from plants', 'condensation within the troposphere', 'melting of polar ice caps'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'Transpiration is the process by which plants release water vapor through their leaves, accounting for most of the remaining approximately 10% of atmospheric water vapor beyond ocean evaporation.',
      diveDeep: 'The combined process of evaporation from water bodies plus transpiration from plants is called evapotranspiration. Precipitation adds water to the surface but does not put vapor into the atmosphere — it removes it. Condensation converts vapor into liquid droplets; it also removes vapor. Melting polar ice adds liquid water to the ocean, contributing slightly to evaporation, but it is not a direct source of atmospheric water vapor. Plants play a crucial and underappreciated role in the water cycle.',
    },
    {
      number: 10, part: 'A',
      text: 'What is the relative humidity if the dry-bulb temperature is 26°C and the wet-bulb temperature is 18°C?',
      choices: ['13%', '33%', '45%', '51%'],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'Using the ESRT Relative Humidity table with a dry-bulb of 26°C and a wet-bulb depression of 8°C (26 − 18 = 8), the relative humidity is approximately 45%.',
      diveDeep: 'The wet-bulb depression is calculated by subtracting the wet-bulb from the dry-bulb temperature: 26 − 18 = 8°C. Use this depression value and the dry-bulb temperature as row/column coordinates in the ESRT\'s Relative Humidity table. A larger depression means drier air (lower RH). When dry-bulb equals wet-bulb, RH = 100% (saturation). Students who subtract incorrectly or use the wrong ESRT table will choose wrong answers. Always double-check which table to use: Relative Humidity vs. Dewpoint Temperature.',
    },
    {
      number: 11, part: 'A',
      text: 'Most of the long-wave energy radiated from Earth and lost to space on a cloudless night is',
      choices: ['ultraviolet', 'infrared', 'visible light', 'gamma rays'],
      topic: 'General',
      correct: 1,
      explanation: 'Earth\'s surface, which is much cooler than the Sun, radiates energy primarily as infrared (long-wave) radiation, most of which escapes to space on cloudless nights.',
      diveDeep: 'Electromagnetic radiation wavelength is determined by the temperature of the radiating body — cooler objects emit longer wavelengths. The Sun (~5500°C) emits mostly short-wave visible and UV radiation. Earth (~15°C average) emits long-wave infrared. Greenhouse gases in the atmosphere absorb some of this infrared, trapping heat. On cloudless nights, more of this infrared escapes to space, causing temperatures to drop more than on cloudy nights (clouds act as a blanket). Students often confuse incoming (solar, shortwave) with outgoing (Earth, longwave) radiation.',
    },
    {
      number: 12, part: 'A',
      text: 'In addition to carbon dioxide, two other major greenhouse gases in Earth\'s atmosphere are',
      choices: ['oxygen and nitrogen', 'oxygen and methane', 'water vapor and nitrogen', 'water vapor and methane'],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'Water vapor and methane are both significant greenhouse gases that, along with CO₂, absorb and re-emit long-wave infrared radiation, trapping heat in the atmosphere.',
      diveDeep: 'Nitrogen (N₂) and oxygen (O₂) together make up 99% of the atmosphere but are NOT greenhouse gases — they are transparent to infrared radiation. Greenhouse gases must have molecular structures that can vibrate when absorbing infrared, which requires asymmetric molecules. Water vapor is actually the most abundant and powerful greenhouse gas on Earth. Methane (CH₄) is about 25 times more potent per molecule than CO₂ over a 100-year period. Eliminating nitrogen and oxygen from the choices is a key test-taking strategy here.',
    },
    {
      number: 13, part: 'A',
      text: 'The arrows in the diagram below represent the movement of air over a mountain. Clouds are forming on the windward side of this mountain because the air is',
      choices: ['expanding and cooling to the dewpoint', 'expanding and warming to the dewpoint', 'compressing and cooling to the dewpoint', 'compressing and warming to the dewpoint'],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-august-2018/q13.png',
      explanation: 'As air rises on the windward side of a mountain it expands (decreasing pressure), causing adiabatic cooling; when the air cools to the dewpoint, water vapor condenses and clouds form.',
      diveDeep: 'This is the orographic lifting process. Rising air expands because atmospheric pressure decreases with altitude — expansion requires energy, so the air cools (adiabatic cooling). Cooling continues until the air temperature reaches the dewpoint, at which point relative humidity reaches 100% and condensation occurs forming clouds. On the leeward (downwind) side, air descends and compresses, warming up and evaporating clouds — the rain shadow effect. "Expanding" is the key word here because pressure decreases with altitude. Compression and warming describe the leeward side.',
    },
    {
      number: 14, part: 'A',
      text: 'The graph below shows the average monthly amount of insolation received throughout a year at four locations (A, B, C, and D) on Earth. Which line on the graph best represents the average monthly insolation received at the equator?',
      choices: ['A', 'B', 'C', 'D'],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-august-2018/q14.png',
      explanation: 'The equator receives relatively consistent insolation throughout the year with two slight peaks near the equinoxes (when the Sun is directly overhead), making it the most uniform line on the graph.',
      diveDeep: 'At the equator, the Sun is never far from directly overhead, so insolation variation throughout the year is small — two peaks occur near the equinoxes when the overhead noon Sun is exactly at the equator. Higher latitudes show much more variation (very low in winter, higher in summer). Polar regions can receive zero insolation during their winter months. On such a graph, the most nearly flat, consistently high line represents the equator. A common mistake is choosing the line with the highest peak — that would be a location like a high-latitude area during its long summer days.',
    },
    {
      number: 15, part: 'A',
      text: 'Earth\'s polar regions have cold, dry climates because the Sun\'s rays are at a',
      choices: ['low angle, and upper atmospheric air is sinking', 'low angle, and upper atmospheric air is rising', 'high angle, and lower atmospheric air is sinking', 'high angle, and lower atmospheric air is rising'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'Low-angle solar rays spread energy over a larger area, reducing heating intensity; sinking polar air creates high pressure that suppresses precipitation, resulting in cold, dry conditions.',
      diveDeep: 'Two factors combine to make polar climates cold and dry. First, the low Sun angle means solar energy is spread over a larger surface area, delivering less energy per square meter. Second, in the polar circulation cell, upper atmosphere air sinks at the poles, creating high pressure. Sinking air warms by compression, reduces relative humidity, and suppresses cloud formation and precipitation — hence the dry conditions. Antarctica, despite being covered in ice, is technically a desert by precipitation. Students often overlook the air pressure/circulation component of this question.',
    },
    {
      number: 16, part: 'A',
      text: 'Atmospheric transparency will increase when',
      choices: ['volcanic eruptions occur', 'fog is produced', 'insolation is reflected by clouds', 'precipitation removes dust particles from the air'],
      topic: 'General',
      correct: 3,
      explanation: 'Precipitation washes aerosols, dust, and pollutants out of the atmosphere (a process called wet deposition), reducing scattering and absorption of sunlight, thereby increasing atmospheric transparency.',
      diveDeep: 'Atmospheric transparency describes how much incoming solar radiation can pass through the atmosphere without being absorbed or scattered. Particles such as dust, smoke, volcanic ash, and aerosols all reduce transparency. Rain and snow effectively scrub these particles from the air. Volcanic eruptions inject sulfur dioxide and ash that dramatically reduce transparency, lowering global temperatures temporarily. Fog and clouds reduce transparency locally. A clean atmosphere after a rainstorm often produces very vivid, blue skies — that is increased transparency in action.',
    },
    {
      number: 17, part: 'A',
      text: 'The existence of which group of organisms spans the shortest geologic time?',
      choices: ['birds', 'humans', 'dinosaurs', 'placoderm fish'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Humans (genus Homo) first appeared approximately 2–3 million years ago, giving them the shortest existence compared to birds (~150 mya), dinosaurs (~230–66 mya), and placoderm fish (~430–360 mya).',
      diveDeep: 'Using the ESRT\'s Geologic History of New York State chart, you can compare the time spans of different organisms. Placoderm fish existed roughly from the Silurian to the end of the Devonian (~430–360 mya) — about 70 million years. Dinosaurs spanned the Mesozoic (~230–66 mya) — about 165 million years. Birds evolved from theropod dinosaurs around 150 mya and still exist today. Humans have a geologic time span of only about 2 million years, by far the shortest listed. This is often a surprising result — students expect dinosaurs to have the shortest span.',
    },
    {
      number: 18, part: 'A',
      text: 'Which New York State geologic event occurred most recently?',
      choices: ['Taconian orogeny', 'Grenville orogeny', 'formation of the Catskill delta', 'dome-like uplift of the Adirondack region'],
      topic: 'Geology',
      correct: 3,
      explanation: 'The dome-like uplift of the Adirondack region is ongoing and began most recently, while the Grenville orogeny (~1.1 bya), Taconian orogeny (~460 mya), and Catskill delta formation (~375 mya) all occurred much earlier.',
      diveDeep: 'Using the ESRT\'s Geologic History of New York State: Grenville orogeny ~1100 mya, Taconian orogeny ~460 mya, Catskill delta formation ~375 mya (Devonian), and the Adirondack uplift is a relatively recent and continuing process that began in the Cenozoic. The Adirondacks are geologically young mountains despite being composed of ancient Precambrian rock — the uplift is recent even though the rock is old. Students often confuse the age of the rock with the age of the mountain-building event.',
    },
    {
      number: 19, part: 'A',
      text: 'The only dinosaur fossils found in New York State are footprints found on 210-million-year-old bedrock. In which New York State landscape region were these dinosaur fossils found?',
      choices: ['Tug Hill Plateau', 'Newark Lowlands', 'Allegheny Plateau', 'Adirondack Mountains'],
      topic: 'Geology',
      correct: 1,
      explanation: 'The Newark Lowlands in southeastern New York State contain Triassic-age (~210 mya) sedimentary rocks — the same age as these dinosaur footprints — making it the only region with the correct bedrock age.',
      diveDeep: 'The Newark Lowlands contains Triassic and Jurassic sedimentary rocks deposited in rift basins as Pangaea was breaking apart. These are the youngest surface sedimentary rocks in New York State. The Adirondacks have ancient Precambrian metamorphic rock. The Allegheny Plateau has mostly Devonian sedimentary rock. The Tug Hill Plateau has Ordovician and Silurian rocks. Knowing the age of bedrock in each NYS landscape region (from the ESRT) allows you to determine which region could preserve 210-million-year-old dinosaur tracks.',
    },
    {
      number: 20, part: 'A',
      text: 'The first P-wave of an earthquake travels 5600 kilometers from the epicenter and arrives at a seismic station at 10:05 a.m. At what time did this earthquake occur?',
      choices: ['9:49 a.m.', '9:56 a.m.', '10:02 a.m.', '10:14 a.m.'],
      topic: 'Geology',
      correct: 1,
      explanation: 'The ESRT shows that a P-wave traveling 5600 km takes approximately 9 minutes; subtracting 9 minutes from 10:05 a.m. gives an origin time of 9:56 a.m.',
      diveDeep: 'Using the ESRT\'s Earthquake P-wave and S-wave Travel Time graph, find 5600 km on the horizontal axis and read across to the P-wave curve to determine the travel time (~9 minutes). Subtract that from the arrival time to find the earthquake\'s origin time. This is a straightforward ESRT reading question but students must be precise in reading the graph. Practice reading travel time graphs at various distances — they are commonly tested. Also note that S-waves traveling the same distance would take about 16 minutes.',
    },
    {
      number: 21, part: 'A',
      text: 'The photograph below shows a New York State index fossil. What is the best classification of this fossil, and during which geologic time period did the organism that produced this fossil exist?',
      choices: ['Classification: Coral, Geologic time period: Permian', 'Classification: Coral, Geologic time period: Ordovician', 'Classification: Trilobite, Geologic time period: Permian', 'Classification: Trilobite, Geologic time period: Ordovician'],
      topic: 'Geology',
      correct: 3,
      explanation: 'Trilobites are a major New York State index fossil group and were common from the Cambrian through the Devonian, with many species used to identify Ordovician rock layers.',
      diveDeep: 'Index fossils must be (1) from organisms that lived over a wide geographic area, (2) existed for a short geologic time period, and (3) are abundant and easy to identify. Trilobites were widespread arthropods that are excellent index fossils for Paleozoic rocks, especially the Ordovician. Corals are also index fossils for certain periods but are typically colonial structures. The Permian is when trilobites went extinct, so a trilobite fossil as an index for the Permian doesn\'t make sense — they would be too rare by then. Using the ESRT\'s Geologic History chart is essential for placing fossils in their correct time periods.', image: '/images/exams/es-august-2018/q21.png' },
    {
      number: 22, part: 'A',
      text: 'As a quartz pebble is transported by a stream, the pebble will become more rounded as a result of',
      choices: ['dissolving as water is running over the rock', 'abrasion by colliding with other rocks', 'deposition in well-sorted layers', 'resistance to weathering and erosion'],
      topic: 'Water Cycle',
      correct: 1,
      explanation: 'Abrasion occurs when rocks collide with each other during transport, wearing away sharp edges and corners to produce progressively rounder, smoother pebbles.',
      diveDeep: 'Quartz is very resistant to chemical weathering (dissolution) because it is composed of SiO₂ and barely dissolves in water. Abrasion is a mechanical weathering process that physically grinds and smooths rock surfaces. The longer and farther a pebble travels, the more rounded it becomes. Deposition in sorted layers happens after transport, not during. Resistance to weathering means the pebble stays intact longer but doesn\'t explain rounding. The degree of rounding is actually used by geologists to estimate how far and long a sediment was transported.',
    },
    {
      number: 23, part: 'A',
      text: 'Which three minerals are most likely used in the construction of a house?',
      choices: ['graphite, pyrite, and halite', 'garnet, galena, and sulfur', 'talc, amphibole, and fluorite', 'selenite gypsum, dolomite, and muscovite mica'],
      topic: 'Geology',
      correct: 3,
      explanation: 'Selenite gypsum is used in drywall (plasterboard), dolomite is used as a building stone and aggregate, and muscovite mica is used as an electrical insulator and in certain construction materials.',
      diveDeep: 'This question tests knowledge of mineral economic uses from the ESRT. Graphite is used in pencils and lubricants; pyrite has no major construction use; halite is table salt. Garnet is used as an abrasive; galena is a lead ore; sulfur is used in chemicals. Talc is used in cosmetics and powder; amphibole can be a source of asbestos. Gypsum in its selenite form is the key mineral in drywall, the most common interior wall material in modern homes. Knowing the industrial uses of minerals listed in the ESRT is essential for this question type.',
    },
    {
      number: 24, part: 'A',
      text: 'The topographic map below shows a portion of a volcanic island in the Pacific Ocean. Elevations are shown in feet. Locations A and B are 2.5 miles apart. What is the approximate gradient from point A to point B on the island?',
      choices: ['1000 ft/mi', '1250 ft/mi', '3000 ft/mi', '2500 ft/mi'],
      topic: 'Maps',
      correct: 0,
      image: '/images/exams/es-august-2018/q24.png',
      explanation: 'Gradient = change in elevation ÷ horizontal distance. If the elevation change is approximately 2500 feet over 2.5 miles, then gradient = 2500 ÷ 2.5 = 1000 ft/mi.',
      diveDeep: 'The gradient formula is: Gradient = (change in field value) ÷ (distance). On a topographic map, the field value is elevation. Read the elevations at points A and B from the contour lines, subtract to get the change, then divide by the map distance (converted to real distance using the scale). Steep gradients indicate fast-moving streams and more erosion. This calculation is a standard skill on the Earth Science Regents. Double-check by making sure units are consistent (feet per mile) before finalizing your answer.',
    },
    {
      number: 25, part: 'A',
      text: 'Which two rocks usually consist of only one mineral, but may contain additional minerals?',
      choices: ['dunite and quartzite', 'granite and gabbro', 'sandstone and conglomerate', 'shale and limestone'],
      topic: 'Geology',
      correct: 0,
      explanation: 'Dunite is composed almost entirely of olivine, and quartzite is composed almost entirely of quartz; both are typically monomineralic (one mineral) but may contain minor amounts of other minerals.',
      diveDeep: 'Dunite is an ultramafic igneous rock found in the deep mantle, composed of >90% olivine. Quartzite is a metamorphic rock derived from sandstone, composed of >90% quartz. Granite and gabbro are both polymineralic (multiple minerals). Sandstone and conglomerate are sedimentary rocks that typically contain multiple minerals. Shale contains clay minerals, quartz, and others. The ESRT rock tables show mineral compositions. When a rock is labeled as composed of "one mineral," it is often dunite or quartzite on Regents exams.',
    },
    {
      number: 26, part: 'A',
      text: 'Which type of plate boundary would most likely produce mountains, metamorphic rocks, and igneous intrusions?',
      choices: ['a divergent oceanic-oceanic boundary', 'a divergent continental-continental boundary', 'a convergent continental-continental boundary', 'a transform continental-continental boundary'],
      topic: 'Plate Tectonics',
      correct: 2,
      explanation: 'At convergent continental-continental boundaries, neither plate subducts, so both are crumpled upward forming mountain ranges with intense heat and pressure creating metamorphic rocks and igneous intrusions.',
      diveDeep: 'The Himalayas are the classic example of a continental-continental convergent boundary (India-Eurasia collision). The immense compression creates fold-and-thrust mountains, regional metamorphism due to heat and pressure, and some igneous intrusions from partial melting. Divergent boundaries create rift valleys and basaltic lava, not mountain ranges. Transform boundaries produce earthquakes along lateral faults (like the San Andreas) but minimal mountain building. Oceanic-continental convergent boundaries produce volcanic arcs and subduction-zone features — a different style of mountain building.',
    },
    {
      number: 27, part: 'A',
      text: 'The rate of decay of radioactive isotopes is constant. What information is needed to determine the absolute age of a rock using radioactive dating?',
      choices: ['the current ratio of parent isotope to daughter isotope in the rock', 'the current ratio of radioactive isotope to stable isotope in the atmosphere', 'the percentage of parent isotope that has decayed over the last 1000 years', 'the percentage of daughter isotope that existed in the rock when it first formed'],
      topic: 'Geology',
      correct: 0,
      explanation: 'By measuring the current ratio of remaining parent isotope to accumulated daughter isotope and knowing the half-life, scientists can calculate how long decay has been occurring and thus the rock\'s absolute age.',
      diveDeep: 'Radioactive dating works because parent isotopes decay at a constant, known rate (half-life). When a rock forms, it contains a certain amount of parent isotope and essentially no daughter isotope. Over time, parent converts to daughter. Measuring the parent-to-daughter ratio today and comparing it to the known starting ratio (100% parent) allows age calculation. For example, if half the parent remains (50:50 ratio), exactly one half-life has passed. Students sometimes confuse the atmospheric ratio method, which is used for carbon-14 dating of organic material, not for dating rocks.', image: '/images/exams/es-august-2018/q27.png' },
    {
      number: 28, part: 'A',
      text: 'The cross section below shows rock layers that have been tilted. According to the principle of original horizontality, these layers were originally',
      choices: ['tilted at the angle shown', 'vertical', 'horizontal', 'folded into arches and troughs'],
      topic: 'Geology',
      correct: 2,
      explanation: 'The principle of original horizontality states that sedimentary rock layers are originally deposited in nearly horizontal (flat) layers; any tilting is the result of later deformation by tectonic forces.',
      diveDeep: 'Nicolaus Steno\'s principle of original horizontality is a foundational concept in geology. Sediments settle out of water under gravity and form flat, horizontal layers at the time of deposition. If we observe tilted or folded layers today, we can infer that some tectonic event disturbed the layers after they formed. This principle, combined with superposition (older layers on the bottom) and crosscutting relationships, allows geologists to reconstruct geologic history. Students sometimes forget that the law describes the original state, not the current state.', image: '/images/exams/es-august-2018/q28.png' },
    {
      number: 29, part: 'A',
      text: 'Which property of water accounts for the fact that bodies of water heat up and cool down more slowly than land surfaces?',
      choices: ['high specific heat', 'high density', 'high transparency', 'high surface tension'],
      topic: 'General',
      correct: 0,
      explanation: 'Water has a high specific heat (4.18 J/g·°C), meaning it requires more energy to raise its temperature than land, so it heats and cools much more slowly.',
      diveDeep: 'Specific heat is the amount of energy needed to raise 1 gram of a substance by 1°C. Water\'s specific heat is about 4 times higher than that of rock/soil. This property moderates coastal climates — areas near large bodies of water have smaller temperature ranges between summer and winter. The Great Lakes moderate temperatures in nearby cities. Continental interiors, far from water, experience extreme temperature swings. This property is why coasts are cooler in summer and warmer in winter than inland areas at the same latitude.', image: '/images/exams/es-august-2018/q29.png' },
    {
      number: 30, part: 'A',
      text: 'Which process is primarily responsible for the formation of metamorphic rock from existing rock?',
      choices: ['melting and solidification', 'weathering, erosion, deposition, compaction, and cementation', 'heat and pressure without melting', 'cooling of magma at the surface'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Metamorphic rocks form when existing rocks are subjected to intense heat and pressure (without melting) that causes mineral recrystallization and textural changes.',
      diveDeep: 'The word "metamorphic" means "changed form." The key distinction is that metamorphism occurs in the solid state — the rock is changed without melting. If the rock melts, it becomes magma, and upon cooling it forms igneous rock. Contact metamorphism occurs near igneous intrusions (heat only); regional metamorphism occurs at convergent plate boundaries (both heat and pressure). Weathering, erosion, compaction, and cementation describe the formation of sedimentary rocks. Students must clearly distinguish between igneous (melting/solidification) and metamorphic (heat/pressure, no melting).',
    },
    {
      number: 31, part: 'A',
      text: 'The diagram below represents a cross section of Earth\'s interior. Which list correctly describes the composition and state of layers A, B, C, and D?',
      choices: [
        'A: rocky, solid; B: rocky, partially molten; C: iron/nickel, liquid; D: iron/nickel, solid',
        'A: rocky, partially molten; B: rocky, solid; C: iron/nickel, solid; D: iron/nickel, liquid',
        'A: iron/nickel, liquid; B: rocky, solid; C: iron/nickel, solid; D: rocky, partially molten',
        'A: rocky, solid; B: iron/nickel, liquid; C: rocky, partially molten; D: iron/nickel, solid',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'From the surface inward: lithosphere (rocky, solid), asthenosphere (rocky, partially molten), outer core (iron/nickel, liquid), and inner core (iron/nickel, solid under extreme pressure).',
      diveDeep: 'Earth\'s interior layers from outside to inside: crust + uppermost mantle = lithosphere (rigid/solid); asthenosphere = partially melted upper mantle that allows plates to move; lower mantle (stiffer mantle) = solid rock under high pressure; outer core = liquid iron-nickel (generates magnetic field by convection); inner core = solid iron-nickel compressed by enormous pressure despite high temperature. The key surprises are that (1) the outer core is liquid but the inner core is solid, and (2) the asthenosphere can flow despite being mostly solid rock. This layer knowledge is frequently tested on the Regents.', image: '/images/exams/es-august-2018/q31.png' },
    {
      number: 32, part: 'A',
      text: 'Which event provided evidence that the continents have moved? Fossils of the same species of land-dwelling reptile were found in',
      choices: [
        'the same types of rock layers in different parts of North America',
        'both South America and Africa',
        'deep-ocean sediments near mid-ocean ridges',
        'Pleistocene glacial deposits in New York State',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'Finding identical land-dwelling reptile fossils on both South America and Africa — continents now separated by the Atlantic Ocean — is strong evidence that these landmasses were once joined and have since drifted apart.',
      diveDeep: 'Continental drift evidence includes: matching fossil species on now-separated continents (especially land-dwellers that couldn\'t cross oceans), matching rock types and mountain ranges that align when continents are reassembled, glacial deposits at tropical latitudes, and the geometric fit of continental coastlines. Land-dwelling reptiles cannot swim across an ocean, so identical fossils on both sides of the Atlantic indicate the continents were once connected. This is one of Wegener\'s original lines of evidence for the theory of plate tectonics. Deep-ocean sediment age patterns support seafloor spreading but not continental drift per se.', image: '/images/exams/es-august-2018/q32.png' },
    {
      number: 33, part: 'A',
      text: 'The ocean floor has been divided into sections by the locations of mid-ocean ridges and deep-ocean trenches. The youngest oceanic bedrock is located',
      choices: [
        'near the mid-ocean ridges',
        'near the deep-ocean trenches',
        'in the center of the ocean basins',
        'at the edges of the continental shelves',
      ],
      topic: 'Plate Tectonics',
      correct: 0,
      explanation: 'New oceanic crust forms continuously at mid-ocean ridges where magma rises and solidifies, so the youngest seafloor is always adjacent to the ridge; older crust moves away toward trenches where it is subducted.',
      diveDeep: 'Seafloor spreading, discovered in the 1960s, explained that mid-ocean ridges are sites of new crust creation. Rock age increases symmetrically moving away from ridges in both directions. The oldest oceanic crust is found near subduction zones (trenches). No oceanic crust older than about 200 million years exists because older crust has been subducted. This age pattern, confirmed by ocean drilling, was crucial evidence for plate tectonic theory. Continental crust, by contrast, can be billions of years old because it is too buoyant to subduct.', image: '/images/exams/es-august-2018/q33.png' },
    {
      number: 34, part: 'A',
      text: 'A student found a rock sample that has the following properties: coarse texture, composed of olivine and pyroxene, dark colored, intrusive igneous. What is this rock?',
      choices: ['basalt', 'pumice', 'gabbro', 'granite'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Gabbro is an intrusive (coarse-grained) mafic igneous rock composed primarily of olivine and pyroxene, giving it a dark color — this matches all described properties.',
      diveDeep: 'Using the ESRT\'s Scheme for Igneous Rock Identification: the composition (olivine, pyroxene) places this rock in the mafic to ultramafic category, and the coarse texture indicates slow cooling deep underground (intrusive/plutonic). Basalt has the same mineral composition but is fine-grained (extrusive/volcanic — rapid cooling). Granite is coarse-grained but felsic (quartz, feldspar). Pumice is vesicular volcanic glass. The ESRT rock chart shows texture (grain size) on the vertical axis and composition on the horizontal axis. Always identify texture first, then composition.', image: '/images/exams/es-august-2018/q34.png' },
    {
      number: 35, part: 'A',
      text: 'What is the approximate latitude and longitude of New York City?',
      choices: ['41° N, 74° W', '41° N, 74° E', '41° S, 74° W', '74° N, 41° W'],
      topic: 'Maps',
      correct: 0,
      explanation: 'New York City is located at approximately 41° North latitude and 74° West longitude, in the northeastern United States.',
      diveDeep: 'New York State generally occupies 40–45°N latitude and 72–80°W longitude. New York City, being in the southeastern corner, is near 41°N, 74°W. Latitudes are measured from the equator (0°) toward the poles (90°). In North America, latitudes are North and longitudes are West. On Regents exams, knowing the approximate coordinates of major New York State cities is important. Polaris altitude equals the latitude of the observer, so an observer in NYC would see Polaris at about 41° above the north horizon.', image: '/images/exams/es-august-2018/q35.png' },
    // Part B-1
    {
      number: 36, part: 'B-1',
      context: 'Base your answers to questions 36 through 38 on the diagram below and on your knowledge of Earth science. The diagram represents a portion of Earth\'s surface showing the locations of four weather stations: Albany (NY), Miami (FL), Denver (CO), and Barrow (AK), with temperature, pressure, and weather data shown for each station using station model symbols.',
      text: 'Which city most likely has the highest dew point temperature?',
      choices: ['Albany, NY', 'Miami, FL', 'Denver, CO', 'Barrow, AK'],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-august-2018/context_36_38.png',
      explanation: 'Miami, Florida, has a tropical marine climate with consistently warm and humid air, resulting in the highest dewpoint temperatures compared to the other cities listed.',
      diveDeep: 'Dewpoint temperature is a measure of the amount of water vapor in the air — higher dewpoint means more moisture. Tropical coastal locations like Miami receive large amounts of evaporated moisture from warm ocean waters. Alaska (Barrow) is extremely cold and dry. Denver is high-elevation and semi-arid. Albany is temperate but less humid than Miami. The station model in the ESRT shows dewpoint as the lower-left number. On hot, humid summer days in New York, dewpoints of 65–70°F make it feel oppressive; Miami regularly exceeds these values.',
    },
    {
      number: 37, part: 'B-1',
      context: 'Base your answers to questions 36 through 38 on the diagram below and on your knowledge of Earth science. The diagram represents a portion of Earth\'s surface showing the locations of four weather stations.',
      text: 'Which city is most likely located within a high-pressure system?',
      choices: ['Albany, NY', 'Miami, FL', 'Denver, CO', 'Barrow, AK'],
      topic: 'Meteorology',
      correct: 2,
      image: '/images/exams/es-august-2018/context_36_38.png',
      explanation: 'Denver, CO, tends to show clear skies and calm conditions associated with high pressure, as dry continental air masses frequently dominate the region.',
      diveDeep: 'High-pressure systems are associated with sinking air, which warms by compression, lowers relative humidity, and suppresses cloud formation. Weather at high-pressure centers is typically clear, calm, and dry. Low-pressure systems have rising air, cooling, condensation, and stormy weather. On a station model, high pressure is indicated by a high barometric pressure reading and clear sky symbol. Denver\'s semi-arid continental interior location makes it prone to high-pressure dominance. The answer would change depending on the specific station model data provided on the exam.',
    },
    {
      number: 38, part: 'B-1',
      context: 'Base your answers to questions 36 through 38 on the diagram below and on your knowledge of Earth science. The diagram represents a portion of Earth\'s surface showing the locations of four weather stations.',
      text: 'Which air mass would most likely produce the weather conditions shown at Miami?',
      choices: ['continental polar (cP)', 'continental tropical (cT)', 'maritime polar (mP)', 'maritime tropical (mT)'],
      topic: 'Meteorology',
      correct: 3,
      image: '/images/exams/es-august-2018/context_36_38.png',
      explanation: 'Maritime tropical (mT) air masses form over warm tropical ocean waters and bring warm, moist conditions — exactly what characterizes Miami\'s warm, humid weather.',
      diveDeep: 'Air mass classification uses two letters: the first describes moisture (m = maritime/moist, c = continental/dry); the second describes temperature (T = tropical/warm, P = polar/cold). mT air masses form over warm oceans in tropical latitudes and are warm and humid. cP air masses form over cold continental land masses and are cold and dry. Florida\'s weather is dominated by the mT air mass from the Gulf of Mexico and Caribbean. When cP air masses push down from Canada in winter, Florida can experience unusual cold snaps. This four-way classification is frequently tested on the Regents.',
    },
    {
      number: 39, part: 'B-1',
      context: 'Base your answers to questions 39 through 41 on the topographic map below and on your knowledge of Earth science. The map shows a region with rivers, hills, and contour lines with 20-foot intervals.',
      text: 'In which general direction does the main river in this region flow?',
      choices: ['northeast', 'northwest', 'southeast', 'southwest'],
      topic: 'Maps',
      correct: 2,
      explanation: 'Rivers flow from higher to lower elevation; on a topographic map, stream flow direction is determined by following the land from higher contour values toward lower contour values.',
      diveDeep: 'A key rule for reading topographic maps is that contour lines form a V-shape (chevron) where they cross streams, and the V points upstream (toward higher elevation). Stream flow is always from high to low elevation. To determine general flow direction on a map, locate the highest elevation (headwaters) and trace the river toward lower elevations. North arrows and labeled elevation values help orient direction. This type of question requires careful contour-line reading and is a regular feature of Part B-1 on the Regents exam.',
    },
    {
      number: 40, part: 'B-1',
      context: 'Base your answers to questions 39 through 41 on the topographic map below and on your knowledge of Earth science. The map shows a region with rivers, hills, and contour lines with 20-foot intervals.',
      text: 'What is the elevation of the highest point on the hill shown on the map?',
      choices: ['between 200 and 220 ft', 'between 220 and 240 ft', 'between 240 and 260 ft', 'between 260 and 280 ft'],
      topic: 'Maps',
      correct: 1,
      image: '/images/exams/es-august-2018/q40.png',
      explanation: 'The summit of a hill on a topographic map lies between the last visible closed contour and the next contour interval above it, so the highest point is between 220 and 240 ft.',
      diveDeep: 'When reading hill summits on topographic maps, remember that the summit elevation is not precisely known from contour lines alone — it lies within the interval above the highest closed contour. If the highest closed contour is 220 ft and the interval is 20 ft, the summit is between 220 and 240 ft. You cannot say it is exactly 220 ft or 240 ft. This type of "between which two values" question is very common on the Regents. Contour interval, the difference in elevation between adjacent lines, must always be identified first.',
    },
    {
      number: 41, part: 'B-1',
      context: 'Base your answers to questions 39 through 41 on the topographic map below and on your knowledge of Earth science. The map shows a region with rivers, hills, and contour lines with 20-foot intervals.',
      text: 'A student walked from point X to point Y on the map. Which profile best represents the change in elevation along this path?',
      choices: ['Profile showing continuous descent', 'Profile showing continuous ascent', 'Profile showing descent then ascent', 'Profile showing ascent then descent'],
      topic: 'Maps',
      correct: 3,
      explanation: 'If the path from X to Y goes up over a hill and back down, the profile would show ascent then descent, creating a dome-shaped curve.',
      diveDeep: 'Constructing an elevation profile (topographic cross section) from a topographic map is a key skill. First, identify the elevation at each contour line crossed by the path. Then plot those elevations on a graph with horizontal distance on the x-axis and elevation on the y-axis. Connect the dots to create the profile shape. Concentric closed contour circles indicate a hill (ascent then descent). A V-shaped pattern at a stream indicates a valley (descent then ascent). This question type requires both map reading and profile interpretation.',
    },
    {
      number: 42, part: 'B-1',
      context: 'Base your answers to questions 42 through 44 on the data table below and on your knowledge of Earth science. The table shows the results of a soil permeability experiment in which water was poured through three soil samples (coarse sand, medium sand, and fine clay) and the volume of water that passed through each sample in 30 seconds was recorded.',
      text: 'Which soil sample had the greatest permeability?',
      choices: ['fine clay', 'medium sand', 'coarse sand', 'All samples had equal permeability'],
      topic: 'Water Cycle',
      correct: 2,
      image: '/images/exams/es-august-2018/context_42_44.png',
      explanation: 'Coarse sand has the largest pore spaces between particles, allowing water to flow through most rapidly, giving it the greatest permeability.',
      diveDeep: 'Permeability describes how quickly water can flow through a material. It depends on the size and connectivity of pore spaces. Coarser particles have larger, more connected pores. Fine clay particles are tiny and pack together tightly, creating very small pores that greatly impede water flow — clay is nearly impermeable. Porosity (total pore volume) and permeability are related but different properties: a material can be porous but not permeable if the pores are disconnected. Sorted sediments (uniform size) generally have higher permeability than unsorted mixtures for the same particle size.',
    },
    {
      number: 43, part: 'B-1',
      context: 'Base your answers to questions 42 through 44 on the data table below and on your knowledge of Earth science. The table shows the results of a soil permeability experiment.',
      text: 'Which soil sample would have the greatest amount of capillarity?',
      choices: ['fine clay', 'medium sand', 'coarse sand', 'All samples had equal capillarity'],
      topic: 'Water Cycle',
      correct: 0,
      image: '/images/exams/es-august-2018/context_42_44.png',
      explanation: 'Fine clay has the smallest pore spaces, and smaller pores produce greater capillary action — water is drawn upward more strongly through narrow passages.',
      diveDeep: 'Capillarity (capillary action) is the ability of water to rise through narrow spaces against gravity due to adhesion (water sticking to surfaces) and surface tension. Narrower tubes and pore spaces produce stronger capillary rise. This is the opposite of permeability: fine-grained sediments have high capillarity but low permeability. Capillarity is important in soil science — it brings water from the water table toward plant roots during dry periods. In the ESRT, the relationship between sediment grain size, permeability, and capillarity is explicitly shown.',
    },
    {
      number: 44, part: 'B-1',
      context: 'Base your answers to questions 42 through 44 on the data table below and on your knowledge of Earth science. The table shows the results of a soil permeability experiment.',
      text: 'Which statement best explains why the fine clay sample allowed the least water to pass through?',
      choices: [
        'Fine clay particles are heavy and sink, blocking pore spaces.',
        'Fine clay particles pack closely together, reducing the size of pore spaces.',
        'Fine clay particles dissolve in water, forming a dense layer.',
        'Fine clay particles are negatively charged, repelling water molecules.',
      ],
      topic: 'Water Cycle',
      correct: 1,
      image: '/images/exams/es-august-2018/context_42_44.png',
      explanation: 'Fine clay particles are extremely small and pack together closely, creating tiny, poorly connected pore spaces that dramatically restrict water flow.',
      diveDeep: 'The relationship between particle size and pore size is fundamental: smaller particles = smaller pores = lower permeability. Clay minerals are platelike and tend to align themselves flat, stacking together with very little pore space between them. Clay does not dissolve in water and is not magnetically charged — those distractors are physically incorrect. This concept explains why clay-rich soils have poor drainage and form impermeable layers that create perched water tables. In agriculture, clay soils retain water but drain slowly, making them challenging to work with.',
    },
    {
      number: 45, part: 'B-1',
      context: 'Base your answers to questions 45 through 47 on the passage and diagram below and on your knowledge of Earth science. The passage describes how earthquake waves are used to study Earth\'s interior. The diagram shows the paths of P-waves and S-waves through Earth.',
      text: 'Which statement best explains why S-waves cannot travel through Earth\'s outer core?',
      choices: [
        'The outer core is too cold for S-waves to travel through.',
        'The outer core is composed of liquid iron and nickel, and S-waves cannot travel through liquids.',
        'The outer core is too dense for S-waves to enter.',
        'The outer core is at the wrong depth for S-waves to reach.',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'S-waves are shear waves that require a solid medium to transmit transverse vibrations; the liquid outer core cannot support shear stress, so S-waves stop at the outer core boundary.',
      diveDeep: 'This is one of the most fundamental facts about seismic waves and Earth\'s interior. P-waves (primary/compressional) travel through both solids and liquids by alternating compression and expansion. S-waves (secondary/shear) can only travel through solids because liquids have no shear strength. When seismologists noticed a "shadow zone" where S-waves were absent on the far side of earthquakes, they concluded that a liquid layer existed inside Earth — the outer core. This was a brilliant example of using wave behavior to infer the state of matter deep inside Earth without ever drilling there.', image: '/images/exams/es-august-2018/context_45_47.png' },
    {
      number: 46, part: 'B-1',
      context: 'Base your answers to questions 45 through 47 on the passage and diagram below and on your knowledge of Earth science. The diagram shows the paths of P-waves and S-waves through Earth.',
      text: 'How do P-waves change as they pass from the mantle into the outer core?',
      choices: [
        'They speed up and curve away from Earth\'s center.',
        'They slow down and curve toward Earth\'s center.',
        'They stop completely and are absorbed.',
        'They speed up and travel in a straight line.',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'P-waves slow down when they enter the denser liquid outer core and refract (bend) toward Earth\'s center, changing their travel path.',
      diveDeep: 'Seismic wave speed depends on the density and elasticity of the material they travel through. When waves cross a boundary between materials of different properties, they refract (change direction), similar to light bending when entering water. In the outer core, the state changes from solid to liquid and the composition changes from silicate rock to iron-nickel — P-waves slow and bend. This refraction creates seismic shadow zones that helped geologists map Earth\'s interior layers. The same principle (Snell\'s Law of refraction) applies to both seismic waves and light.', image: '/images/exams/es-august-2018/context_45_47.png' },
    {
      number: 47, part: 'B-1',
      context: 'Base your answers to questions 45 through 47 on the passage and diagram below and on your knowledge of Earth science. The diagram shows the paths of P-waves and S-waves through Earth.',
      text: 'What is the evidence that Earth\'s inner core is solid?',
      choices: [
        'P-waves disappear when passing through the inner core.',
        'S-waves travel through the inner core.',
        'P-waves speed up when entering the inner core from the liquid outer core.',
        'Both P-waves and S-waves are absorbed at the inner core boundary.',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'P-waves accelerate when they re-enter the solid inner core from the liquid outer core, indicating a transition from liquid to a denser solid material that propagates compressional waves faster.',
      diveDeep: 'The inner core\'s solidity was inferred by Inge Lehmann in 1936. Even though the inner core is extremely hot (~5000°C), the immense pressure at Earth\'s center (~360 GPa) forces iron and nickel into a solid crystalline state. P-waves can travel through both solid and liquid, but their speed changes at the liquid-to-solid boundary. Additionally, some researchers have detected weak S-wave-like signals from the inner core boundary, further suggesting it is solid. The inner core is believed to be a giant iron crystal aligned with Earth\'s rotation axis.', image: '/images/exams/es-august-2018/context_45_47.png' },
    {
      number: 48, part: 'B-1',
      context: 'Base your answers to questions 48 through 50 on the geologic cross section below and on your knowledge of Earth science. The cross section shows sedimentary rock layers A through F, an igneous intrusion G, and a fault line H.',
      text: 'According to the cross section, which geologic event occurred first?',
      choices: [
        'formation of igneous intrusion G',
        'faulting along line H',
        'deposition of rock layer A',
        'deposition of rock layer F',
      ],
      topic: 'Geology',
      correct: 3,
      image: '/images/exams/es-august-2018/context_48_50.png',
      explanation: 'By the law of superposition, the lowest undisturbed sedimentary layer (F) was deposited first, before any of the layers above it or the intrusion and faulting events.',
      diveDeep: 'Relative dating uses several principles to determine the sequence of geologic events: (1) Superposition — lower layers are older; (2) Original horizontality — layers began flat; (3) Crosscutting relationships — intrusions and faults are younger than the rocks they cut through; (4) Inclusions — fragments within a rock are older than the rock containing them. On any cross section, establish the sequence by first identifying the oldest layer (lowest undisturbed), then the sequence of deposition, then any intrusions or faults (which must post-date the rocks they affect). Practice this sequence with multiple cross sections.',
    },
    {
      number: 49, part: 'B-1',
      context: 'Base your answers to questions 48 through 50 on the geologic cross section below and on your knowledge of Earth science. The cross section shows sedimentary rock layers A through F, an igneous intrusion G, and a fault line H.',
      text: 'What evidence in the cross section indicates that the igneous intrusion (G) is younger than rock layer B?',
      choices: [
        'Intrusion G is below rock layer B.',
        'Intrusion G cuts through rock layer B.',
        'Rock layer B contains fossils that are older than G.',
        'Rock layer B is thicker than the intrusion G.',
      ],
      topic: 'Geology',
      correct: 1,
      image: '/images/exams/es-august-2018/context_48_50.png',
      explanation: 'The principle of crosscutting relationships states that any intrusion or fault must be younger than the rocks it cuts through; if G cuts through B, then G formed after B.',
      diveDeep: 'Crosscutting relationships are one of the most reliable tools for relative dating. If magma intrudes (cuts through) existing rock layers, it must have been injected after those layers formed. The intruded layers do not change the intrusion — it is the intrusion that disrupts the layers. Similarly, a fault that cuts across rock layers must have occurred after those layers were deposited. Contact metamorphism zones (baked/altered rock) adjacent to intrusions also indicate younger intrusive events. This principle applies to any feature that physically cuts across or through other features.',
    },
    {
      number: 50, part: 'B-1',
      context: 'Base your answers to questions 48 through 50 on the geologic cross section below and on your knowledge of Earth science. The cross section shows sedimentary rock layers A through F, an igneous intrusion G, and a fault line H.',
      text: 'What type of rock would most likely be found adjacent to the contact zone between igneous intrusion G and sedimentary rock layer C?',
      choices: [
        'granite, because intrusion G is large',
        'quartzite, because layer C is sandstone',
        'metamorphic rock, because of the heat from the intrusion',
        'volcanic rock, because intrusions always produce surface eruptions',
      ],
      topic: 'Geology',
      correct: 2,
      image: '/images/exams/es-august-2018/context_48_50.png',
      explanation: 'Contact metamorphism occurs when heat from a magma intrusion bakes the surrounding rock, changing its mineral structure and creating metamorphic rock in a zone adjacent to the intrusion.',
      diveDeep: 'Contact metamorphism is a localized (small-scale) type of metamorphism caused by heat from an igneous intrusion. The zone of altered rock around an intrusion is called a contact metamorphic aureole. The rock type produced depends on what the surrounding (country) rock was: limestone → marble; shale → hornfels; sandstone → quartzite. Importantly, the intrusion itself is igneous, not metamorphic. The larger the intrusion, the wider the contact metamorphic zone. This is how hornfels forms — one of the few metamorphic rocks produced only by contact (heat alone, not pressure) metamorphism.',
    },
  ],
}
