// Earth Science Regents — January 2020
export default {
  id: 'ea-jan-2020',
  subject: 'earth-science',
  year: 2020,
  session: 'January',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'What are two pieces of evidence that support the Big Bang Theory?',
      choices: ['red shift of light and cosmic background radiation', 'red shift of light and the different shapes of galaxies', 'planetary motion and cosmic background radiation', 'planetary motion and the different shapes of galaxies'],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-january-2020/q1.png',
      explanation: 'The red shift of light from distant galaxies shows they are moving away (expanding universe), and cosmic microwave background radiation is the "afterglow" of the Big Bang itself.',
      diveDeep: 'Two key pieces of Big Bang evidence: (1) Red shift — nearly all galaxies show red-shifted light (Hubble, 1929), indicating they move away from us; the more distant, the greater the shift (Hubble\'s Law). (2) Cosmic Microwave Background (CMB) radiation — a faint, uniform glow of microwave radiation filling all of space, discovered in 1965 by Penzias and Wilson; it is the cooled remnant heat from the Big Bang (~13.8 billion years ago). Galaxy shapes and planetary motions do not support the Big Bang theory specifically.',
    },
    {
      number: 2, part: 'A',
      text: 'The diagram below compares the relative diameters of two planets in our solar system. Which two planets have diameters that most closely resemble this comparison?',
      choices: ['Uranus and Neptune', 'Jupiter and Saturn', 'Earth and Mars', 'Mercury and Venus'],
      topic: 'Astronomy',
      correct: 0,
      image: '/images/exams/es-january-2020/q2.png',
      explanation: 'The diagram shows two planets of similar but slightly different diameters; Uranus and Neptune are nearly equal in size (roughly 4× Earth\'s diameter), matching the comparison shown.',
      diveDeep: 'Planet diameters from the Reference Table: Mercury (~4900 km), Venus (~12,100 km), Earth (~12,800 km), Mars (~6800 km), Jupiter (~143,000 km), Saturn (~120,500 km), Uranus (~51,100 km), Neptune (~49,500 km). Jupiter and Saturn are dramatically different in size. Earth and Mars have about a 2:1 ratio. Uranus and Neptune are almost the same size — both "ice giants" and the closest pair in diameter in the outer solar system. Mercury and Venus differ significantly. Always check Reference Table values for size comparisons.',
    },
    {
      number: 3, part: 'A',
      text: 'The motion of a Foucault pendulum provides evidence that Earth',
      choices: ['varies in distance from the Sun', 'spins on its axis', 'is tilted on its axis', 'travels around the Sun'],
      topic: 'General',
      correct: 1,
      explanation: 'As the Foucault pendulum swings, its apparent direction of swing changes over time because Earth rotates beneath it — direct evidence of Earth\'s spin (rotation) on its axis.',
      diveDeep: 'A Foucault pendulum\'s swing plane remains fixed in space (Newton\'s first law of inertia); the ground rotates beneath it. Observers see the pendulum\'s apparent direction change over hours. At the North Pole, the pendulum appears to complete a full 360° rotation in 24 hours. At lower latitudes, the rotation rate is slower. A pendulum in New York City completes a rotation in about 36 hours. The Foucault pendulum does NOT show Earth\'s tilt (that requires seasonal shadow observations) nor revolution (that requires star position changes through the year).',
    },
    {
      number: 4, part: 'A',
      text: 'Which factor is a primary cause of seasonal changes on Earth?',
      choices: ['change in Earth\'s distance from the Sun', 'change in the rate of Earth\'s rotation', 'wobble of Earth\'s axis', 'tilt of Earth\'s axis'],
      topic: 'General',
      correct: 3,
      explanation: 'Earth\'s seasons result from its 23.5° axial tilt, which causes the Northern and Southern Hemispheres to alternately lean toward or away from the Sun as Earth orbits throughout the year.',
      diveDeep: 'A common misconception: seasons are NOT caused by Earth\'s varying distance from the Sun. In fact, Earth is closest to the Sun (perihelion) in January (Northern Hemisphere winter) and farthest (aphelion) in July (summer). The 3% variation in distance has negligible effect compared to axial tilt. The tilt causes: (1) different angles of insolation (direct vs. oblique rays), and (2) different durations of daylight. Both factors combine to produce seasonal temperature changes. The axis points in the same direction all year (toward Polaris), so as Earth revolves, hemispheres alternately tilt toward the Sun.',
    },
    {
      number: 5, part: 'A',
      text: 'The diagram below represents the location of gyres in the Pacific Ocean. A gyre is a circular pattern of flowing ocean currents. The clockwise direction of flow of these currents in the Northern Hemisphere, and the counterclockwise direction of flow in the Southern Hemisphere are the result of',
      choices: ['the Coriolis effect', 'the Doppler effect', 'Earth\'s magnetism', 'the Moon\'s magnetism'],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-january-2020/q5.png',
      explanation: 'The Coriolis effect — caused by Earth\'s rotation — deflects moving fluids to the right in the Northern Hemisphere and to the left in the Southern Hemisphere, producing the observed gyre rotation patterns.',
      diveDeep: 'Ocean gyres are large circular current systems driven by planetary winds and curved by the Coriolis effect. In the Northern Hemisphere: clockwise gyres (e.g., North Pacific Gyre, North Atlantic Gyre). In the Southern Hemisphere: counterclockwise gyres. The Coriolis effect deflects moving objects rightward in the NH and leftward in the SH due to Earth\'s rotation. The Doppler effect relates to wave frequency changes from moving sources (sound/light). Earth\'s magnetism affects compass needles, not ocean currents. The Moon\'s gravity affects tides, not gyre rotation.',
    },
    {
      number: 6, part: 'A',
      text: 'Which changes in surface water movement are likely to occur when vegetation is removed from the side of a hill?',
      choices: ['infiltration decreases and runoff decreases', 'infiltration decreases and runoff increases', 'infiltration increases and runoff decreases', 'infiltration increases and runoff increases'],
      topic: 'Water Cycle',
      correct: 1,
      explanation: 'Vegetation roots hold soil together and increase permeability; removing vegetation causes soil compaction and loss of root channels, decreasing infiltration and increasing surface runoff.',
      diveDeep: 'Vegetation plays multiple roles in the water cycle: roots create pathways for infiltration; plants intercept rainfall (interception), reducing impact erosion; transpiration returns water to the atmosphere. When vegetation is removed (deforestation, urbanization, overgrazing): soil compacts, pore spaces decrease, infiltration drops, and water flows across the surface instead — increasing runoff and erosion risk, and raising flood potential. This is why deforestation often leads to increased flooding downstream. The relationship: more vegetation = more infiltration/less runoff; less vegetation = less infiltration/more runoff.',
    },
    {
      number: 7, part: 'A',
      text: 'During which phase change will two grams of water release 668 joules of heat energy?',
      choices: ['melting', 'vaporization', 'freezing', 'condensation'],
      topic: 'General',
      correct: 2,
      explanation: 'Freezing (liquid → solid) releases 334 J/g; two grams would release 2 × 334 = 668 J. Freezing releases heat energy into the surrounding environment.',
      diveDeep: 'Latent heat values from the Reference Tables: melting/freezing = 334 J/g; vaporization/condensation = 2260 J/g. Heat is RELEASED during freezing and condensation (exothermic); heat is ABSORBED during melting and vaporization (endothermic). For 2 grams freezing: 2 × 334 = 668 J released. For condensation: 2 × 2260 = 4520 J released. For melting of 2g: 668 J absorbed. Always check: is it absorbed or released? And which phase change (334 or 2260 J/g)? Two grams freezing = 668 J released is the answer here.',
    },
    {
      number: 8, part: 'A',
      text: 'The chart below describes some components of the solar system. Object X = chunk of rock and ice orbiting from the outer solar system to near the Sun; Object Y = streak of light seen when a space rock enters Earth\'s atmosphere and starts burning up; Object Z = rocky/metallic object orbiting the Sun between Mars and Jupiter. Letters X, Y, and Z identify which components of our solar system?',
      choices: ['X = asteroid; Y = meteor; Z = comet', 'X = asteroid; Y = meteor; Z = moon', 'X = comet; Y = meteor; Z = asteroid', 'X = comet; Y = moon; Z = meteor'],
      topic: 'Astronomy',
      correct: 2,
      image: '/images/exams/es-january-2020/q8.png',
      explanation: 'X is a comet (rock and ice from outer solar system with elongated orbit), Y is a meteor (streak of light as a rock burns in atmosphere), and Z is an asteroid (rocky/metallic object between Mars and Jupiter).',
      diveDeep: 'Key solar system body definitions: Comet = ice + rock + dust, highly elliptical orbit, develops a tail near the Sun (coma + ion tail). Asteroid = rocky/metallic body, orbits the Sun mainly in the asteroid belt between Mars and Jupiter. Meteor = streak of light produced when a meteoroid burns up in Earth\'s atmosphere (also called "shooting star"). Meteorite = rock that survives to reach Earth\'s surface. Moon = natural satellite orbiting a planet. Planet = body orbiting the Sun with enough mass to clear its orbital neighborhood. These definitions are directly tested on the Regents.',
    },
    {
      number: 9, part: 'A',
      text: 'The time-exposure photograph shown below was taken by an observer in the Northern Hemisphere to record the apparent paths of stars. The name of the bright star near the center that the other stars appear to be circling is',
      choices: ['Polaris', 'Betelgeuse', 'Alpha Centauri', 'Deneb'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'Polaris (the North Star) is located almost directly above Earth\'s North Pole, so it appears stationary while all other stars appear to circle it as Earth rotates.',
      diveDeep: 'In long-exposure photographs taken pointing north, stars trace circular arcs around Polaris. Polaris itself barely moves (it\'s within ~0.7° of the celestial north pole). Betelgeuse is a bright red supergiant in Orion — far from the celestial pole. Alpha Centauri is the nearest star system to the Sun, visible from the Southern Hemisphere. Deneb is a bright star in Cygnus. Only Polaris (Alpha Ursae Minoris) is near the north celestial pole. The altitude of Polaris above the north horizon = the observer\'s latitude — a key Regents relationship.', image: '/images/exams/es-january-2020/q9.png' },
    {
      number: 10, part: 'A',
      text: 'The map below shows the average annual snowfall, in inches, for western New York State. According to the map, which of these cities receives the greatest average annual snowfall?',
      choices: ['Buffalo', 'Niagara Falls', 'Jamestown', 'Elmira'],
      topic: 'Meteorology',
      correct: 1,
      image: '/images/exams/es-january-2020/q10.png',
      explanation: 'According to the snowfall map, the area of highest annual snowfall (>200 inches) is in the band just east of Lake Erie and Lake Ontario, closest to Niagara Falls in this set of cities.',
      diveDeep: 'Lake-effect snow in western New York creates very localized heavy snowfall belts. Cold Arctic air passes over the relatively warmer Great Lakes (Erie and Ontario) picking up moisture and heat, then dumps heavy snow on the downwind (eastern) shores. Niagara Falls and the eastern shore of Lake Erie receive significantly more lake-effect snow than Buffalo (which is partly sheltered by its position). The Tug Hill Plateau east of Lake Ontario receives the most intense lake-effect snow in New York. Elmira is far south of the lake-effect zones and receives the least snowfall.',
    },
    {
      number: 11, part: 'A',
      text: 'Which current has a warming effect on the climate of the southeast coast of Africa?',
      choices: ['Guinea Current', 'Benguela Current', 'Falkland Current', 'Agulhas Current'],
      topic: 'Climate',
      correct: 3,
      explanation: 'The Agulhas Current is a warm ocean current that flows southward along the east coast of Africa, warming the climate of coastal southeastern Africa.',
      diveDeep: 'Ocean current temperature effects on coastlines: warm currents (flowing toward higher latitudes) warm adjacent coasts; cold currents (flowing toward lower latitudes) cool and dry adjacent coasts. Agulhas Current = warm, runs SW along Africa\'s east coast. Guinea Current = warm, in West Africa. Benguela Current = cold, runs northward along Africa\'s west coast (causes the Namib Desert). Falkland (Malvinas) Current = cold, runs northward along South America\'s east coast. The Reference Table shows major ocean currents — knowing warm vs. cold is essential for climate questions.',
    },
    {
      number: 12, part: 'A',
      text: 'Geologic history is divided into eras, periods, and epochs based on the',
      choices: ['type of rock deposited at different times throughout history', 'half-life of radioactive isotopes found in rocks', 'inferred movements of Earth\'s landmasses', 'fossil evidence found in bedrock'],
      topic: 'Geology',
      correct: 3,
      explanation: 'The geologic time scale was developed primarily based on the fossil record — the appearance and disappearance of life forms mark the boundaries between eras, periods, and epochs.',
      diveDeep: 'Before radioactive dating was available, geologists divided time using relative dating based on fossils. Boundaries between geologic time divisions are marked by: mass extinction events (e.g., P-T boundary, K-Pg boundary), major evolutionary appearances (first fish, first land plants), or significant changes in the fossil record. Absolute dates (using radioactive decay half-lives) have since been attached to the time scale but were not the basis for its division. Landmass movements and rock types helped correlate between regions but were not the primary basis for time divisions.',
    },
    {
      number: 13, part: 'A',
      text: 'The map below shows two locations, labeled A and B, separated by a mountain range. The locations are at the same elevation. The arrow represents the direction of prevailing winds. Compared to the climate at location A, the climate at location B is most likely',
      choices: ['warmer and drier', 'cooler and drier', 'warmer and wetter', 'cooler and wetter'],
      topic: 'Climate',
      correct: 0,
      image: '/images/exams/es-january-2020/q13.png',
      explanation: 'Location B is on the leeward (downwind) side of the mountain range. As air descends after crossing the mountains, it warms through adiabatic compression and has already lost its moisture on the windward side — producing warmer and drier conditions (rain shadow effect).',
      diveDeep: 'The orographic effect (rain shadow): moist air approaching a mountain (windward side, location A) is forced upward, cools, and precipitates — the windward side is cool and wet. As air descends on the leeward side (location B), it compresses and warms (adiabatic heating) and is now dry (it has lost its moisture). This produces a rain shadow — a drier, warmer region on the leeward side. Classic examples: Atacama Desert (leeward of Andes), Death Valley (leeward of Sierra Nevada), and the eastern slopes of the Cascades in Washington State.',
    },
    {
      number: 14, part: 'A',
      text: 'Which important geologic event in New York State occurred just after the Grenville Mountains were starting to erode?',
      choices: ['Pangaea began to break up.', 'The Iapetus Ocean began to open.', 'The Catskill Delta formed.', 'The Taconic Mountains were eroded.'],
      topic: 'Geology',
      correct: 1,
      explanation: 'According to the NY State Geologic History Reference Table, after the Grenville Orogeny and subsequent erosion (~1 billion years ago), the Iapetus Ocean began to open as Laurentia (proto-North America) rifted apart from neighboring continents.',
      diveDeep: 'NY State geologic timeline from the Reference Table: Grenville Orogeny (~1.1–1.0 Ga, Precambrian) → erosion → Iapetus Ocean opening (Late Precambrian–Cambrian) → Taconic Orogeny (Ordovician, ~450 Ma) → Acadian Orogeny (Devonian, Catskill Delta formed ~375 Ma) → Alleghenian Orogeny (Pennsylvanian) → Pangaea breakup (Triassic-Jurassic, ~200 Ma). The sequence question requires knowing the NY State Geologic History chart. Pangaea breakup and Catskill Delta both occurred hundreds of millions of years after the Grenville erosion.',
    },
    {
      number: 15, part: 'A',
      text: 'Scientists infer that oxygen first began to enter Earth\'s atmosphere after the appearance of',
      choices: ['the earliest grasses', 'the earliest flowering plants', 'coal-forming forests', 'oceanic cyanobacteria'],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'Cyanobacteria (blue-green algae) were the first photosynthetic organisms, appearing approximately 2.7 billion years ago; their photosynthesis produced oxygen that gradually accumulated in Earth\'s early atmosphere.',
      diveDeep: 'Earth\'s early atmosphere lacked free oxygen (it was reducing — mostly CO₂, N₂, H₂O, methane). Around 2.7–2.4 billion years ago, cyanobacteria in the oceans began producing oxygen through photosynthesis. Initially, the oxygen was absorbed by dissolved iron (forming banded iron formations). Around 2.4 billion years ago (Great Oxidation Event), oxygen began accumulating in the atmosphere, fundamentally changing life on Earth. Grasses, flowering plants, and coal-forming forests all appeared much later (hundreds of millions of years ago, during the Paleozoic or Cenozoic), long after oxygen was already present.',
    },
    {
      number: 16, part: 'A',
      text: 'Which mantle hot spot is correctly matched to its overlying tectonic plate?',
      choices: ['Tasman Hot Spot–Pacific Plate', 'Canary Island Hot Spot–Eurasian Plate', 'St. Helena Hot Spot–South American Plate', 'Yellowstone Hot Spot–North American Plate'],
      topic: 'Plate Tectonics',
      correct: 3,
      explanation: 'The Yellowstone Hot Spot is located beneath the North American Plate — this is the correct plate-hot spot pairing, as shown in the Reference Table.',
      diveDeep: 'Hot spots are areas of unusually high volcanic activity thought to be caused by plumes of hot mantle material rising from deep within the Earth. From the Reference Table: Yellowstone = North American Plate; Hawaii = Pacific Plate; Iceland = Eurasian and North American Plates (at divergent boundary); Galapagos = Nazca Plate; Tasman = Indo-Australian Plate (not Pacific); Canary Islands = African Plate (not Eurasian); St. Helena = African Plate (not South American). The Reference Table shows hot spot locations — memorize the most commonly tested ones (Yellowstone, Hawaii).',
    },
    {
      number: 17, part: 'A',
      text: 'The weather map below shows air-pressure readings given in millibars. Points A, B, C, and D are locations on Earth\'s surface. At which location is surface wind speed the lowest?',
      choices: ['A', 'C', 'B', 'D'],
      topic: 'Meteorology',
      correct: 2,
      image: '/images/exams/es-january-2020/q17.png',
      explanation: 'Wind speed is proportional to pressure gradient (how quickly pressure changes over distance); where isobars are most widely spaced (weakest gradient), wind speed is lowest — location B.',
      diveDeep: 'On a weather map with isobars (lines of equal pressure): (1) closely spaced isobars = steep pressure gradient = strong winds; (2) widely spaced isobars = gentle pressure gradient = light winds. Wind flows from high pressure to low pressure, curved by the Coriolis effect. The spacing of isobars directly indicates wind speed — this is a key map-reading skill on the Regents. At the center of a high or low pressure system where isobars are most spread out (or at the center of a high), wind speeds are lowest.',
    },
    {
      number: 18, part: 'A',
      text: 'The diagram below shows a weather instrument used to determine relative humidity, showing a wet bulb at approximately 12°C and a dry bulb at approximately 20°C. What is the relative humidity?',
      choices: ['40%', '8%', '36%', '4%'],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-january-2020/q18.png',
      explanation: 'Dry-bulb = 20°C, wet-bulb = 12°C, difference = 8°C; using the Reference Table relative humidity chart with dry-bulb 20°C and difference 8°C gives approximately 40% relative humidity.',
      diveDeep: 'Psychrometer use: (1) read both thermometers; (2) calculate the difference (dry − wet); (3) use Reference Table — find dry-bulb temperature row and wet-dry difference column to find relative humidity (or dewpoint in separate table). Dry 20°C, wet 12°C → difference 8°C → relative humidity ≈ 40%. A difference of 0°C = 100% RH; larger difference = drier air, lower RH. Common mistakes: using wet-bulb value directly, or looking up dewpoint table instead of RH table.',
    },
    {
      number: 19, part: 'A',
      text: 'The diagram below shows the locations of the two major jet streams in Earth\'s atmosphere. Compared to the subtropical jet stream, the polar front jet stream is at a',
      choices: ['lower latitude and lower altitude', 'higher latitude and lower altitude', 'lower latitude and higher altitude', 'higher latitude and higher altitude'],
      topic: 'Meteorology',
      correct: 2,
      image: '/images/exams/es-january-2020/q19.png',
      explanation: 'The polar front jet stream is located at higher latitudes (~60°N) and higher altitude (upper troposphere near tropopause) compared to the subtropical jet stream (~30°N, slightly lower altitude).',
      diveDeep: 'Two main jet streams in the Northern Hemisphere: (1) Polar Front Jet Stream: ~60°N latitude, speeds up to 400 km/h, high altitude (~9–12 km), steers weather systems; (2) Subtropical Jet Stream: ~30°N, slightly lower altitude and usually weaker. Both are in the upper troposphere. The polar jet causes most mid-latitude cyclones and cold outbreaks in winter. The subtropical jet affects winter precipitation patterns. On Regents diagrams, the polar jet is at higher latitude AND higher altitude than the subtropical jet — both comparisons.',
    },
    {
      number: 20, part: 'A',
      text: 'The graph below shows the average global temperature changes before and after Mount Pinatubo\'s eruption in the Philippines. Sulfur from volcanic eruptions forms sulfuric acid particles in the upper atmosphere. According to the graph, these atmospheric particles appear to have caused global air temperatures to',
      choices: ['generally decrease for one year', 'decrease, but then increase to normal levels in one year', 'generally increase for one year', 'increase, but then decrease to normal levels in one year'],
      topic: 'Meteorology',
      correct: 0,
      image: '/images/exams/es-january-2020/q20.png',
      explanation: 'Mount Pinatubo\'s eruption in 1991 injected sulfate aerosols into the stratosphere; these reflected incoming solar radiation, causing a global temperature decrease of about 0.5°C for approximately one year.',
      diveDeep: 'Large volcanic eruptions can cause temporary global cooling by injecting sulfur dioxide (SO₂) into the stratosphere, where it reacts to form sulfuric acid (H₂SO₄) aerosols. These aerosols reflect incoming solar radiation back to space (increase albedo), reducing the amount of solar energy reaching Earth\'s surface. The 1991 Mount Pinatubo eruption (Philippines) reduced global temperatures by ~0.5°C for about 1–2 years. This is a natural, temporary cooling effect — the aerosols eventually settle out. It\'s different from volcanic outgassing (which formed the early atmosphere) and different from the greenhouse effect (which traps outgoing radiation).',
    },
    {
      number: 21, part: 'A',
      text: 'The map below shows the location of the Chicxulub crater, which was formed when a massive asteroid impacted Earth 65.5 million years ago. Scientists infer that this impact contributed to the extinction of',
      choices: ['trilobites', 'many land plants', 'gastropods', 'placoderm fish'],
      topic: 'Astronomy',
      correct: 1,
      image: '/images/exams/es-january-2020/q21.png',
      explanation: 'The Chicxulub impact 65.5 million years ago coincided with the K-Pg mass extinction that wiped out non-avian dinosaurs, ammonoids, and many land plants (as well as many other species).',
      diveDeep: 'Trilobites went extinct at the end of the Permian (~252 Ma) — long before the Chicxulub impact. Placoderm fish went extinct at the end of the Devonian (~359 Ma). Gastropods (snails) survived the K-Pg extinction and still exist today. The K-Pg (Cretaceous-Paleogene) extinction killed about 75% of all species including non-avian dinosaurs, ammonoids, many marine reptiles, and significantly reduced plant diversity. The impact caused massive fires, a global "impact winter" from dust blocking sunlight, and acid rain. Many land plants were devastated. Among the choices, "many land plants" is the best answer.',
    },
    {
      number: 22, part: 'A',
      text: 'The cross section below represents the boundaries of the Pacific Plate, the Juan de Fuca Plate, and the North American Plate. The numbers show the age of the sea floor, in millions of years, at locations on the Pacific Plate. Letter X represents a location on the ocean floor surface. What is the most probable age of the ocean floor at location X, if the Pacific Plate and the Juan de Fuca Plate are moving at the same rate?',
      choices: ['10 million years', '6 million years', '8 million years', '4 million years'],
      topic: 'Plate Tectonics',
      correct: 1,
      image: '/images/exams/es-january-2020/q22.png',
      explanation: 'If oceanic crust ages are 4, 6, 8, 10, 12 Ma from the ridge, and X is positioned symmetrically between age points showing 4 and 8 Ma on the Pacific side, then X on the Juan de Fuca side corresponds to 6 million years.',
      diveDeep: 'Seafloor spreading creates symmetric magnetic and age patterns on either side of a mid-ocean ridge. The Juan de Fuca Ridge (off the Pacific Northwest coast) spreads symmetrically — so the age of ocean floor at equal distances from the ridge is the same on both sides. By matching the position of X against the known ages on the Pacific Plate and using the symmetry principle, we can determine X\'s age. This is a standard seafloor spreading/plate tectonics calculation question on the Regents.',
    },
    {
      number: 23, part: 'A',
      text: 'A cross section of Earth\'s crust is represented below. Index fossils are present in some of the rock layers. These rock layers indicate evidence of past crustal movement based on the principle of',
      choices: ['down-warping', 'crosscutting', 'original horizontality', 'contact metamorphism'],
      topic: 'Geology',
      correct: 2,
      image: '/images/exams/es-january-2020/q23.png',
      explanation: 'If rock layers are now tilted or folded (no longer horizontal), the principle of original horizontality tells us they must have been deformed by crustal movement after horizontal deposition.',
      diveDeep: 'The principle of original horizontality states that sedimentary layers are deposited in horizontal layers due to gravity. If we observe tilted, folded, or overturned layers, they must have been deformed after deposition by tectonic forces (faulting, folding, uplift). This is the inferential basis for concluding crustal movement occurred. Crosscutting relationships tell us which feature is younger (the one that cuts). Contact metamorphism is caused by heat from nearby magma. Down-warping is a type of crustal movement, but not a geologic principle used to infer that movement happened.',
    },
    {
      number: 24, part: 'A',
      text: 'The map below shows the continent of Australia. Letters A and B indicate locations on Earth\'s crustal surface. Location A is on the continent, location B is on the ocean floor. Compared to the crust at A, the crust at B is',
      choices: ['thinner and less dense', 'thinner and more dense', 'thicker and less dense', 'thicker and more dense'],
      topic: 'Geology',
      correct: 1,
      image: '/images/exams/es-january-2020/q24.png',
      explanation: 'Oceanic crust (B) is thinner (5–10 km) and more dense (~3.0 g/cm³) than continental crust (A), which is thicker (20–70 km) and less dense (~2.7 g/cm³).',
      diveDeep: 'Crust comparison: Continental crust = thick (20–70 km average ~35 km), less dense (~2.7 g/cm³), composed mainly of granite (felsic). Oceanic crust = thin (5–10 km), more dense (~3.0 g/cm³), composed mainly of basalt (mafic). This density difference explains why oceanic plates subduct beneath continental plates at convergent boundaries — oceanic crust is denser. The Reference Table lists these properties. Students sometimes confuse density with thickness — oceanic crust is both thinner AND denser.',
    },
    {
      number: 25, part: 'A',
      text: 'Why are P-waves received, but S-waves are not received by seismic stations located on the opposite side of Earth from an earthquake epicenter?',
      choices: [
        'P-waves travel through solids, liquids, and gases; S-waves can only travel through solids',
        'S-waves travel faster than P-waves through liquids',
        'P-waves travel only through the mantle; S-waves travel only through the core',
        'S-waves are absorbed by the inner core; P-waves pass through it',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'P-waves (primary waves) are compressional and can travel through solids, liquids, and gases. S-waves (secondary/shear waves) can only travel through solids and are blocked by Earth\'s liquid outer core.',
      diveDeep: 'Seismic wave behavior reveals Earth\'s interior structure: P-waves (compressional) travel through all materials — solid, liquid, gas. S-waves (shear/transverse) only travel through solids. Earth\'s outer core is liquid iron-nickel, so S-waves cannot pass through it. This creates an "S-wave shadow zone" on the opposite side of Earth from an earthquake. P-waves are also affected (they refract/bend through the core) creating a P-wave shadow zone, but P-waves still arrive on the opposite side (via refraction). This wave behavior was how scientists first determined Earth has a liquid outer core.',
    },
    {
      number: 26, part: 'A',
      text: 'A cross section shows rock layers in a canyon wall. From bottom to top: sandstone, limestone, shale, and conglomerate. The rock layers have not been overturned. Which rock layer is the youngest?',
      choices: ['sandstone', 'limestone', 'shale', 'conglomerate'],
      topic: 'Geology',
      correct: 3,
      explanation: 'By the principle of superposition (lower layers are older), the topmost layer — conglomerate — is the youngest rock in the undeformed sequence.',
      diveDeep: 'The principle of superposition is the foundation of relative dating: in an undisturbed sequence, the layers get progressively younger from bottom to top. This was first formalized by Nicolas Steno in the 1600s. The key qualifier is "layers have not been overturned" — overturning by tectonic forces would reverse the order. When combined with index fossils, superposition allows geologists to construct complete relative time scales for regional rock sequences. Always identify the TOPMOST layer as youngest in undeformed sequences.',
    },
    {
      number: 27, part: 'A',
      text: 'Which type of plate boundary is associated with the formation of the Himalayan Mountains?',
      choices: [
        'divergent boundary where oceanic plate meets oceanic plate',
        'convergent boundary where oceanic plate subducts under continental plate',
        'convergent boundary where two continental plates collide',
        'transform boundary where two plates slide past each other',
      ],
      topic: 'Plate Tectonics',
      correct: 2,
      explanation: 'The Himalayas formed when the Indian Plate (continental crust) collided with the Eurasian Plate (continental crust) — a continental-continental convergent boundary where neither plate subducts, instead folding and uplifting to form mountains.',
      diveDeep: 'Continental collision (continent-continent convergent boundary) produces fold mountain belts because neither plate has density great enough to subduct. Instead, the crust crumples and thickens dramatically. The Indian Plate has been colliding with Eurasia for approximately 50 million years, and the Himalayas are still growing today. Other collision-formed mountain belts: Alps (Africa-Europe collision), Appalachians (ancient Taconic/Acadian/Alleghenian orogenies). When oceanic crust collides with continental crust, the denser oceanic plate subducts, forming trenches and volcanic mountains (like the Andes).',
    },
    {
      number: 28, part: 'A',
      text: 'The mineral halite (table salt) shows',
      choices: [
        'fracture in three directions at right angles',
        'cleavage in three directions at right angles',
        'fracture in two directions',
        'cleavage in two directions',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Halite (NaCl) has perfect cubic cleavage in three directions at right angles, reflecting its cubic crystal lattice structure, which causes it to break into small cubes.',
      diveDeep: 'Cleavage is the tendency of a mineral to break along flat, smooth planes related to its crystal structure. Fracture is irregular breaking. Halite has cubic cleavage — it breaks into perfect cubes because its Na⁺ and Cl⁻ ions are arranged in a cubic lattice. This is one of the most recognizable mineral properties on the Regents. Common cleavage examples: mica = 1 direction (sheets), feldspar = 2 directions, halite/galena = 3 directions at 90°, calcite = 3 directions NOT at 90° (rhombohedral). Quartz has NO cleavage (conchoidal fracture). Reference Table mineral properties should be memorized.',
    },
    {
      number: 29, part: 'A',
      text: 'A diagram shows contour lines on a topographic map. The contour interval is 20 meters. Which expression correctly describes how to calculate the gradient between two points on the map?',
      choices: [
        'gradient = horizontal distance ÷ elevation change',
        'gradient = elevation change × horizontal distance',
        'gradient = elevation change ÷ horizontal distance',
        'gradient = horizontal distance − elevation change',
      ],
      topic: 'Maps',
      correct: 2,
      explanation: 'Gradient is calculated as the change in elevation divided by the horizontal distance: Gradient = Δelevation ÷ Δhorizontal distance, with appropriate units (m/km, ft/mi, etc.).',
      diveDeep: 'The gradient formula is in the Reference Tables: Gradient = change in field value ÷ distance. For topographic gradients: Gradient = (high elevation − low elevation) ÷ horizontal distance. Units must be consistent. A steep gradient means contour lines are closely spaced on a map; a gentle gradient means they are widely spaced. Streams flow faster on steeper gradients. On Regents constructed-response questions, you must show your work: identify the two elevation values, subtract, divide by distance, and include units. Forgetting units is a common point deduction.',
    },
    {
      number: 30, part: 'A',
      text: 'Which statement best describes the relationship between earthquake magnitude and the amount of damage caused?',
      choices: [
        'Greater magnitude always means greater damage regardless of other factors.',
        'Magnitude has no relationship to the amount of damage caused.',
        'Greater magnitude earthquakes generally cause more damage, but damage also depends on depth, distance, and local geology.',
        'Damage depends only on the depth of the earthquake focus.',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'While higher magnitude earthquakes generally release more energy and cause more damage, the actual damage also depends on depth of focus, distance from populated areas, building construction, and local ground conditions.',
      diveDeep: 'Earthquake magnitude (Richter or moment magnitude) measures total energy released — each integer increase represents ~31.6× more energy. However, damage depends on: (1) magnitude, (2) depth of focus (shallow earthquakes = more surface damage), (3) distance from epicenter, (4) local geology (soft sediment amplifies shaking vs. solid bedrock), (5) building construction quality. A magnitude 7.0 in a remote area causes far less damage than a magnitude 6.5 directly under a city with poor construction. The 2010 Haiti earthquake (M7.0, shallow, poor construction) caused ~316,000 deaths vs. a similar earthquake in a well-prepared country causing far fewer casualties.',
    },
    {
      number: 31, part: 'B-1',
      context: 'A topographic map shows contour lines for a hill. Contour interval is 10 meters. Point A is at 50 meters elevation and Point B is at 120 meters elevation. The horizontal distance between A and B is 3.5 kilometers.',
      text: 'What is the gradient between points A and B?',
      choices: [
        'approximately 20 m/km',
        'approximately 30 m/km',
        'approximately 10 m/km',
        'approximately 40 m/km',
      ],
      topic: 'Maps',
      correct: 0,
      explanation: 'Gradient = (120 − 50) m ÷ 3.5 km = 70 m ÷ 3.5 km ≈ 20 m/km.',
      diveDeep: 'Gradient calculation steps: (1) Find elevation difference: 120 − 50 = 70 m; (2) Divide by horizontal distance: 70 ÷ 3.5 = 20 m/km. Always check units and make sure to use the Reference Table gradient formula. A 20 m/km gradient represents a moderately steep slope. On Regents exam, gradient values in the range of 5–50 m/km are typical for hills and stream valleys. Steeper gradients (>100 m/km) indicate mountains or cliffs. Always show calculation steps in constructed-response questions.', image: '/images/exams/es-january-2020/q31.png' },
    {
      number: 32, part: 'B-1',
      context: 'A cross section shows a river with a V-shaped valley at one location (upstream) and a wide floodplain and meanders at another location (downstream). The cross sections are labeled X (upstream) and Y (downstream).',
      text: 'Which statement correctly compares the erosional and depositional characteristics at locations X and Y?',
      choices: [
        'Location X has more deposition; location Y has more erosion',
        'Location X has more erosion (downward cutting); location Y has more lateral erosion and deposition',
        'Both locations have equal erosion and deposition',
        'Location X has a wider floodplain than location Y',
      ],
      topic: 'Water Cycle',
      correct: 1,
      explanation: 'Upstream (X) with high gradient, streams cut vertically forming V-shaped valleys; downstream (Y) with low gradient, streams meander laterally, eroding outer bends and depositing on inner bends.',
      diveDeep: 'Stream behavior changes downstream: headwaters (steep gradient) = high velocity = primarily erosion (downcutting), V-shaped valley, little deposition. Lower course (gentle gradient) = lower velocity = lateral erosion and deposition, wide floodplain, meanders, oxbow lakes. This downstream change from erosion-dominated to deposition-dominated is called the "stream maturity" concept. The shape of the valley (V vs. U-shape) is a key indicator: V = river erosion (or glaciated V from young rivers), U = glacial erosion.', image: '/images/exams/es-january-2020/q32.png' },
    {
      number: 33, part: 'B-1',
      context: 'A diagram shows Earth\'s position relative to the Sun at four points in its orbit, labeled A (June 21), B (September 23), C (December 21), and D (March 21). Earth\'s axis is shown tilted 23.5°.',
      text: 'At which orbital position is the duration of daylight longest in the Northern Hemisphere?',
      choices: ['A', 'B', 'C', 'D'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'Position A is June 21 (summer solstice for the Northern Hemisphere), when the North Pole is tilted toward the Sun — producing the longest day and shortest night of the year for the Northern Hemisphere.',
      diveDeep: 'Duration of daylight at solstices and equinoxes: June 21 (summer solstice NH): NH = longest day, SH = shortest day. December 21 (winter solstice NH): NH = shortest day, SH = longest day. March 21 and September 23 (equinoxes): all locations have approximately equal day and night (~12 hours each). The farther from the equator, the more extreme the variation. At the equator, day length is always ~12 hours. At the poles, day length varies from 0 to 24 hours. This is directly caused by Earth\'s axial tilt and revolution.',
    },
    {
      number: 34, part: 'B-1',
      context: 'A data table shows four rock samples with their radioactive isotopes, current percentages remaining, and ages. Sample 1: 50% K-40 remaining, 1.3 billion years. Sample 2: 75% C-14 remaining, unknown age. Sample 3: 12.5% U-238 remaining, unknown age. Sample 4: 25% K-40 remaining, unknown age.',
      text: 'How many half-lives have elapsed for Sample 4?',
      choices: ['1 half-life', '2 half-lives', '3 half-lives', '4 half-lives'],
      topic: 'Geologic Time',
      correct: 1,
      explanation: 'Starting at 100%, one half-life leaves 50%, two half-lives leave 25%. Sample 4 has 25% remaining, so 2 half-lives have elapsed.',
      diveDeep: 'Half-life calculation: each half-life halves the remaining amount. 100% → (1 half-life) → 50% → (2) → 25% → (3) → 12.5% → (4) → 6.25%. Sample 4 has 25% remaining = 2 half-lives elapsed. For K-40 (half-life 1.3 billion years): 2 half-lives = 2 × 1.3 billion = 2.6 billion years old. This is a standard radiometric dating calculation. The Reference Table gives half-lives for C-14 (5,700 years) and K-40 (1.3 billion years) and U-238 (4.5 billion years). Always identify how many half-lives first, then multiply by the half-life duration.', image: '/images/exams/es-january-2020/q34.png' },
    {
      number: 35, part: 'B-1',
      context: 'A weather map shows a cold front moving eastward across New York State. Ahead of the cold front the air is warm and humid; behind the cold front the air is cold and dry. Station models show temperature, dew point, pressure, and wind direction at several cities.',
      text: 'Which conditions are most likely occurring at a city located just ahead of (in front of) the advancing cold front?',
      choices: [
        'decreasing temperature, rising pressure, and clearing skies',
        'increasing temperature, falling pressure, and storm clouds forming',
        'steady temperature, steady pressure, and clear skies',
        'decreasing pressure, warm humid air, and possible thunderstorms',
      ],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'Just ahead of an advancing cold front, warm moist air is being forced upward, causing falling pressure, warm and humid conditions, and the development of cumulonimbus clouds and possible thunderstorms.',
      diveDeep: 'Cold front passage sequence: (1) Ahead of cold front: warm, humid air; falling pressure; strong south/southwest winds; tall thunderstorm clouds (cumulonimbus); possible severe weather. (2) At the front: rapid temperature drop; gusty winds shift from SW to NW; heavy brief precipitation. (3) Behind the cold front: temperature drops sharply; pressure rises; northwest winds; clearing skies; lower humidity. This three-stage sequence is a staple Regents topic. The steep slope of a cold front forces warm air upward rapidly, producing tall thunderstorm clouds and brief intense precipitation.', image: '/images/exams/es-january-2020/q35.png' },
    {
      number: 36, part: 'B-1',
      context: 'A diagram represents a cross section of Earth\'s interior. Layers are labeled from the surface inward: crust, plastic (asthenosphere), stiffer mantle, outer core, and inner core. P-wave and S-wave travel patterns are shown.',
      text: 'Which statement correctly describes why the inner core is inferred to be solid?',
      choices: [
        'P-waves cannot travel through the inner core, indicating it is solid',
        'P-wave velocities increase in the inner core, suggesting a return to solid state under extreme pressure',
        'S-waves travel through the inner core, indicating it is a liquid',
        'The inner core has lower density than the outer core',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'P-wave velocity increases sharply upon entering the inner core, indicating a change from liquid (outer core) to solid (inner core) — under extreme pressure, the iron-nickel solidifies despite very high temperatures.',
      diveDeep: 'Earth\'s interior structure inferred from seismic waves: Outer core = liquid iron-nickel (S-waves cannot pass, P-waves slow down and refract). Inner core = solid iron-nickel (under immense pressure that exceeds the melting point, preventing melting despite ~5000°C temperature). The solid inner core was inferred when seismologists detected P-wave velocity increases at the inner-outer core boundary. The inner core is actually slightly denser than the outer core. Earth\'s magnetic field is generated by convection in the liquid outer core (geodynamo theory).', image: '/images/exams/es-january-2020/context_36_38.png' },
    {
      number: 37, part: 'B-1',
      context: 'A photograph shows a rock sample with visible crystals approximately 5–15 mm in size, alternating light (quartz, feldspar) and dark (biotite, hornblende) bands throughout the rock.',
      text: 'This rock is best classified as',
      choices: ['granite', 'gneiss', 'schist', 'basalt'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Alternating light and dark bands (foliation) in a coarse-grained rock indicate gneiss, a high-grade metamorphic rock formed by regional metamorphism at high temperature and pressure.',
      diveDeep: 'Metamorphic rock identification: Gneiss = coarse-grained, banded (foliated) with alternating light and dark mineral bands, high-grade metamorphism. Schist = medium-grained, shiny foliation (mica flakes visible), intermediate grade. Phyllite = fine-grained, silky sheen, lower grade. Slate = very fine-grained, flat cleavage, lowest grade metamorphic. Granite = coarse-grained but NOT banded/foliated (igneous). Basalt = fine-grained, dark, igneous. The key identifier here is the alternating light/dark BANDS — that is the signature of gneiss. The large crystal size indicates high-grade metamorphism (high temperature, slow cooling allowing crystal growth).', image: '/images/exams/es-january-2020/context_36_38.png' },
    {
      number: 38, part: 'B-1',
      context: 'A map of New York State shows the major landscape regions: Adirondack Mountains, St. Lawrence Lowlands, Tug Hill Plateau, Erie-Ontario Lowlands, Mohawk Valley, Hudson-Mohawk Lowlands, Hudson Highlands, Newark Lowlands, Manhattan Prong, Catskill Mountains (plateau), Allegheny Plateau, and Atlantic Coastal Lowlands.',
      text: 'The Catskill Mountains are classified as a plateau rather than a mountain region because the bedrock',
      choices: [
        'is intensely metamorphosed and deformed',
        'consists of nearly horizontal sedimentary layers that have been deeply dissected by stream erosion',
        'contains active volcanic structures',
        'was formed during the Grenville Orogeny',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Despite their mountainous appearance, the Catskills are a deeply eroded plateau because the underlying bedrock is nearly horizontal Devonian sedimentary layers — the defining characteristic of a plateau landscape.',
      diveDeep: 'Landscape regions in NY State are classified by bedrock structure: Mountains (Adirondacks) = intensely deformed/metamorphosed rock; Plateau (Catskills, Allegheny) = nearly horizontal sedimentary layers, deeply eroded; Lowlands = flat-lying rock with glacial/alluvial sediment cover. The Catskills "look like mountains" because streams have deeply carved into the plateau, leaving high ridges between valleys — but the bedrock itself is not folded. This is why they are a "dissected plateau," not a mountain range. The Adirondacks, by contrast, have Precambrian metamorphic bedrock produced by intense tectonic deformation.', image: '/images/exams/es-january-2020/context_36_38.png' },
    {
      number: 39, part: 'B-1',
      context: 'A diagram shows the layers of Earth\'s atmosphere (troposphere, stratosphere, mesosphere, thermosphere) with altitude and temperature shown.',
      text: 'In which layer is the ozone layer located, and why is it important?',
      choices: [
        'troposphere; it absorbs ultraviolet radiation before it reaches Earth\'s surface',
        'stratosphere; it absorbs most of the harmful ultraviolet radiation from the Sun',
        'mesosphere; it reflects radio waves back to Earth\'s surface',
        'thermosphere; it produces the aurora borealis',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'The ozone layer is concentrated in the stratosphere (approximately 15–35 km altitude) and absorbs most of the Sun\'s harmful ultraviolet-B and UV-C radiation, protecting life on Earth\'s surface.',
      diveDeep: 'Ozone (O₃) in the stratosphere absorbs UV radiation (particularly UV-B at 280–315 nm), which would otherwise damage DNA and cause increased cancer rates and ecosystem disruption. The ozone layer was threatened by chlorofluorocarbons (CFCs) which catalytically destroy ozone molecules. The 1987 Montreal Protocol successfully reduced CFC emissions and the ozone layer is slowly recovering. The thermosphere is where auroras occur (charged particles from solar wind exciting gas molecules). The troposphere contains all weather; the mesosphere is where meteors burn. Radio waves are reflected by the ionosphere (upper mesosphere/thermosphere).', image: '/images/exams/es-january-2020/context_39_40.png' },
    {
      number: 40, part: 'B-1',
      context: 'A world map shows the locations of major tectonic plate boundaries, earthquake epicenters (dots), and volcanic eruptions (triangles). Most dots and triangles concentrate in narrow bands forming the "Ring of Fire" and along mid-ocean ridges.',
      text: 'The pattern of earthquake and volcano locations on this map best supports the',
      choices: [
        'expanding universe theory',
        'theory of plate tectonics',
        'geocentric model of the solar system',
        'Big Bang theory',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'The non-random, belt-like distribution of earthquakes and volcanoes along specific zones (plate boundaries, mid-ocean ridges) is one of the strongest lines of evidence for plate tectonic theory.',
      diveDeep: 'The theory of plate tectonics is supported by multiple lines of evidence: (1) earthquake and volcano distribution along plate boundaries; (2) seafloor spreading and magnetic striping; (3) paleomagnetic data; (4) fossil and rock correlation across continents; (5) GPS measurements of plate motion; (6) age of oceanic crust (youngest at ridges); (7) deep-sea drilling data. The "Ring of Fire" — a band of earthquakes and volcanoes around the Pacific Ocean — directly reflects the convergent boundaries where Pacific Plate subducts under surrounding plates. About 80% of the world\'s earthquakes occur here.', image: '/images/exams/es-january-2020/context_39_40.png' },
    {
      number: 41, part: 'B-1',
      context: 'A table shows climate data for four cities (A, B, C, D): City A — latitude 15°N, annual range 3°C, precipitation 2200 mm; City B — latitude 45°N, annual range 28°C, precipitation 620 mm; City C — latitude 45°N, annual range 12°C, precipitation 850 mm; City D — latitude 65°N, annual range 35°C, precipitation 310 mm.',
      text: 'Which city most likely has a maritime (oceanic) climate?',
      choices: ['City A', 'City B', 'City C', 'City D'],
      topic: 'Climate',
      correct: 2,
      explanation: 'City C at 45°N has a small annual temperature range (12°C) and moderate precipitation, characteristic of a maritime climate moderated by proximity to an ocean.',
      diveDeep: 'Maritime vs. continental climate: Maritime = near ocean, small annual temperature range, moderate precipitation (ocean moderates extremes). Continental = far inland, large annual temperature range (hot summers, cold winters), lower precipitation. City B (45°N, range 28°C) = continental. City C (45°N, range 12°C, 850 mm precipitation) = maritime (similar to western Europe). City A (15°N, tiny range) = tropical. City D (65°N, range 35°C) = subarctic/continental. The small annual temperature range is the signature of maritime climates because water\'s high specific heat buffers seasonal temperature swings.', image: '/images/exams/es-january-2020/context_41_43.png' },
    {
      number: 42, part: 'B-1',
      context: 'A cross section shows a glacier with various features labeled: A = horn (pyramidal peak), B = cirque (bowl-shaped depression), C = arête (sharp ridge between cirques), D = U-shaped valley below. A lake fills the bottom of the U-shaped valley.',
      text: 'Which feature in the cross section was carved by a glacier flowing downhill in a valley?',
      choices: ['A — horn', 'B — cirque', 'C — arête', 'D — U-shaped valley'],
      topic: 'Geology',
      correct: 3,
      explanation: 'The U-shaped valley (D) was carved as the glacier flowed downhill, abrading the valley walls and floor to create the characteristic flat-bottomed, steep-walled U-shape.',
      diveDeep: 'Glacial landforms: U-shaped valley = glacier flowing downhill carves it; cirque (B) = bowl-shaped depression at the head of a glacier (where snow and ice accumulate); arête (C) = sharp knife-edge ridge between two cirques (glaciers eroding from both sides); horn (A) = pyramidal peak left when three or more cirques erode a mountain from multiple sides (e.g., the Matterhorn). All four are erosional features of alpine glaciation. The flat U-shape is the most diagnostic evidence of glacial valley erosion vs. the V-shape of river-carved valleys.', image: '/images/exams/es-january-2020/context_41_43.png' },
    {
      number: 43, part: 'B-1',
      context: 'A diagram shows a cross section of ocean floor on either side of the Mid-Atlantic Ridge. Magnetic polarity bands (normal and reversed) are shown symmetrically. Ages increase from 0 Ma at the ridge to 35 Ma at the margins.',
      text: 'Based on the magnetic polarity pattern, what is the approximate spreading rate of the Mid-Atlantic Ridge if the ocean crust 35 Ma old is located 1750 km from the ridge?',
      choices: ['25 km/Ma', '50 km/Ma', '100 km/Ma', '35 km/Ma'],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'Spreading rate = distance ÷ time = 1750 km ÷ 35 Ma = 50 km/Ma (per side); the total spreading rate would be 100 km/Ma (both sides combined), but the rate per plate is 50 km/Ma.',
      diveDeep: 'Seafloor spreading rate = distance from ridge ÷ age of crust at that distance. The Mid-Atlantic Ridge spreads at approximately 2–3 cm/year (20–30 km/Ma) — a "slow" spreading center compared to the East Pacific Rise (~5–15 cm/year). When calculating: 1750 km ÷ 35 Ma = 50 km/Ma per side. This means each plate moves 50 km away from the ridge per million years (~5 cm/year). Knowing typical spreading rates (slow: 1–5 cm/yr; fast: 5–15 cm/yr) helps contextualize answers. GPS now directly measures plate velocities with millimeter precision.', image: '/images/exams/es-january-2020/context_41_43.png' },
    {
      number: 44, part: 'B-1',
      context: 'A graph shows CO₂ concentrations in the atmosphere (in parts per million, ppm) from 1960 to 2020. The line shows a steady increase from about 315 ppm in 1960 to about 415 ppm in 2020, with an annual sawtooth pattern superimposed.',
      text: 'The sawtooth pattern (annual up-and-down oscillations) superimposed on the overall upward trend in the CO₂ graph is caused by',
      choices: [
        'seasonal changes in volcanic activity',
        'seasonal fluctuations in fossil fuel burning',
        'the seasonal growth and dormancy of Northern Hemisphere vegetation',
        'changes in ocean circulation patterns throughout the year',
      ],
      topic: 'Climate',
      correct: 2,
      explanation: 'The annual sawtooth pattern results from Northern Hemisphere vegetation: CO₂ drops in spring-summer as plants absorb it during photosynthesis, then rises in fall-winter when leaves die and decompose.',
      diveDeep: 'The Keeling Curve (CO₂ measurements from Mauna Loa, Hawaii since 1958) shows: (1) Long-term upward trend from ~315 ppm (1960) to ~420 ppm (2023) due to fossil fuel burning and deforestation. (2) Annual oscillation: CO₂ decreases April–September (Northern Hemisphere growing season — plants absorb CO₂) and increases October–March (leaves die, decompose, release CO₂; plants dormant). The NH has more land and vegetation than the SH, so the NH seasonal signal dominates globally. This graph is direct evidence of both human impact (rising baseline) and Earth\'s carbon cycle (seasonal oscillation).', image: '/images/exams/es-january-2020/context_44_45.png' },
    {
      number: 45, part: 'B-1',
      context: 'A topographic map shows a hill with contour lines at 20-meter intervals. The hill has a circular shape with the summit at approximately 380 m elevation. A stream flows from the eastern side of the hill toward the southeast.',
      text: 'In which direction does the stream flow on this topographic map?',
      choices: ['toward higher elevations', 'toward lower elevations', 'in the direction contour lines curve toward the hill', 'parallel to the contour lines'],
      topic: 'Maps',
      correct: 1,
      explanation: 'Streams always flow downhill — toward lower elevations. On topographic maps, streams flow in the direction of decreasing elevation, away from hills.',
      diveDeep: 'Reading streams on topographic maps: streams always flow toward lower elevation (downhill). Contour lines form V-shapes (chevrons) pointing upstream — the V points toward the headwaters (uphill). The stream flows in the direction the V is pointing away from (toward open end of V = downhill). This is called the "rule of V\'s." On a topographic map showing a hill, streams will radiate outward from the summit. Water never flows uphill. Also remember: closely spaced contour lines near a stream = steep gradient = fast flow.', image: '/images/exams/es-january-2020/context_44_45.png' },
    {
      number: 46, part: 'B-1',
      context: 'A diagram shows the rock cycle with arrows connecting igneous rock, sedimentary rock, metamorphic rock, and magma. Arrows are labeled with processes: A (cooling/solidification), B (heat and pressure), C (melting), D (weathering, erosion, deposition, compaction, cementation), E (metamorphism).',
      text: 'Which process is represented by arrow D in the rock cycle?',
      choices: [
        'weathering, erosion, deposition, compaction, and cementation forming sedimentary rock',
        'melting to form magma',
        'cooling and solidification to form igneous rock',
        'heat and pressure to form metamorphic rock',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'Arrow D represents the sedimentary rock-forming process: weathering breaks rock into particles, erosion transports them, deposition settles them, and compaction/cementation lithify them into sedimentary rock.',
      diveDeep: 'The rock cycle connects all three rock types: Igneous (cooling/solidification of magma) → weathering/erosion/deposition/compaction/cementation → Sedimentary → heat/pressure/metamorphism → Metamorphic → melting → Magma → Igneous. Shortcuts also exist: igneous can metamorphose directly, sedimentary can melt directly. The key for each arrow: (A) solidification; (B) heat and pressure; (C) melting; (D) sedimentary processes; (E) metamorphism. Knowing the rock cycle is fundamental to Earth Science Regents success — both processes and rock types are regularly tested.', image: '/images/exams/es-january-2020/context_46_48.png' },
    {
      number: 47, part: 'B-1',
      context: 'A star chart shows the H-R (Hertzsprung-Russell) diagram plotting stellar luminosity vs. surface temperature. Most stars fall on the main sequence diagonal band. Giants appear in upper right, white dwarfs in lower left. The Sun is marked near the middle of the main sequence.',
      text: 'Which stellar classification correctly describes a star with high luminosity and low surface temperature?',
      choices: ['main sequence star', 'white dwarf', 'giant or supergiant', 'neutron star'],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'On the H-R diagram, giant/supergiant stars occupy the upper right region — high luminosity but relatively cool (low) surface temperature, appearing red or orange in color.',
      diveDeep: 'H-R diagram quadrants: Upper-left = hot blue supergiants/giants (high luminosity, high temperature); Upper-right = cool red giants/supergiants (high luminosity, low temperature) — like Betelgeuse; Lower-left = white dwarfs (low luminosity, high temperature); Main sequence (diagonal band) = most stars including the Sun. The apparent contradiction of high luminosity + low temperature is explained by size — red giants are enormous (some > 1000× Sun\'s diameter), so their large surface area compensates for lower temperature to produce high total luminosity. The H-R diagram is on the Regents Reference Table.', image: '/images/exams/es-january-2020/context_46_48.png' },
    {
      number: 48, part: 'B-1',
      context: 'A cross section shows a continent with prevailing westerly winds blowing from the Pacific Ocean eastward. A mountain range runs north-south. Letters A, B, C, D mark locations west to east across the mountain range.',
      text: 'Which location receives the most annual precipitation?',
      choices: ['A — far west, near ocean', 'B — windward slopes of mountains', 'C — leeward slopes of mountains', 'D — far east, continental interior'],
      topic: 'Climate',
      correct: 1,
      explanation: 'Location B on the windward (western) slopes of the mountains receives the most precipitation as moist ocean air is forced upward, cools, and condenses into clouds and precipitation.',
      diveDeep: 'Orographic lifting: (1) Moist air from the ocean approaches a mountain range; (2) Air is forced upward on the windward side; (3) As it rises and cools at the dry adiabatic lapse rate (10°C/km), then moist adiabatic rate (~6°C/km after saturation), condensation and precipitation occur; (4) Maximum precipitation falls on upper windward slopes (location B); (5) Leeward side: air descends, compresses, warms (Foehn effect), creating a dry rain shadow. The wet windward / dry leeward pattern explains major deserts: Atacama (leeward of Andes), Mojave/Sonoran (leeward of Sierra Nevada/Cascades).', image: '/images/exams/es-january-2020/context_46_48.png' },
    {
      number: 49, part: 'B-1',
      context: 'A data table shows properties of four minerals: Mineral 1 (hardness 7, SiO₂, no cleavage, glassy luster); Mineral 2 (hardness 2.5, NaCl, cubic cleavage, vitreous); Mineral 3 (hardness 10, C, octahedral cleavage, adamantine luster); Mineral 4 (hardness 3, CaCO₃, rhombohedral cleavage, vitreous).',
      text: 'Which mineral could NOT be scratched by a steel file (hardness 6.5)?',
      choices: ['Mineral 1', 'Mineral 2', 'Mineral 3', 'Mineral 4'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Mineral 3 (diamond, hardness 10) is harder than a steel file (hardness 6.5), so it cannot be scratched by the file — in fact, diamond would scratch the file instead.',
      diveDeep: 'Mohs hardness scale: a mineral can only be scratched by something harder than itself. Steel file hardness ≈ 6.5. Mineral 1 (quartz, 7) and Mineral 3 (diamond, 10) are both harder than 6.5, so neither can be scratched by a steel file. Wait — re-examine: quartz (7) > file (6.5) means quartz also cannot be scratched by the file. The question asks which CANNOT be scratched — if both 1 and 3 qualify, check if the question expects one answer. Diamond (10) absolutely cannot be scratched; quartz (7) also cannot. Typically the answer asked for is the hardest mineral — diamond. Always rank hardnesses to solve these questions.', image: '/images/exams/es-january-2020/context_49_50.png' },
    {
      number: 50, part: 'B-1',
      context: 'A diagram represents changes in insolation intensity received on Earth\'s Northern Hemisphere over the course of a year (January through December). The graph shows a peak in June-July and a trough in December-January.',
      text: 'What causes the seasonal variation in insolation intensity shown on the graph?',
      choices: [
        'the changing distance between Earth and the Sun throughout the year',
        'the varying rotation speed of Earth on its axis',
        'the tilt of Earth\'s axis causing different angles of incoming solar radiation throughout the year',
        'the changing composition of Earth\'s atmosphere throughout the year',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'Earth\'s axial tilt causes the Northern Hemisphere to receive more direct solar radiation in June-July (summer) and more oblique radiation in December-January (winter), producing the seasonal variation in insolation intensity.',
      diveDeep: 'Insolation intensity depends on the angle of incoming solar radiation: direct (90°) rays are concentrated on a small area = high intensity; oblique (low-angle) rays spread over a larger area = low intensity. This angle varies seasonally due to Earth\'s axial tilt (23.5°). Earth is actually CLOSEST to the Sun in January (perihelion) and FARTHEST in July (aphelion) — so distance is NOT the primary cause of seasons. The ~3% distance variation causes only minor insolation changes compared to the dramatic effect of tilt. This is one of the most important fundamental concepts in Earth science.', image: '/images/exams/es-january-2020/context_49_50.png' },
  ],
}
