// Earth Science Regents — June 2021
export default {
  id: 'es-june-2021',
  subject: 'earth-science',
  year: 2021,
  session: 'June',
  totalMinutes: 85,
  questions: [
    {
      number: 1,
      part: 'A',
      text: 'Which diagram best represents the geocentric model of the solar system?',
      choices: [
        'Earth at center with Sun and planets orbiting around it',
        'Sun at center with planets orbiting around it',
        'Moon at center with Earth and Sun orbiting around it',
        'All planets orbiting at equal distances from the Sun',
      ],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'The geocentric model, proposed by Ptolemy, places Earth at the center of the solar system with all other celestial bodies revolving around it.',
      diveDeep: 'The geocentric (Earth-centered) model was the dominant cosmological view from ancient Greece until the 16th century, when Copernicus proposed the heliocentric model. Ptolemy\'s geocentric model used epicycles — small circles within larger circles — to explain the apparent retrograde motion of planets. Evidence that eventually disproved geocentrism included: Galileo\'s observations of Jupiter\'s moons, Venus\'s phases, and later, stellar parallax. Students should know both models and what evidence supports the heliocentric view.',
    },
    {
      number: 2,
      part: 'A',
      text: 'A student observes that the shadow of a vertical pole in New York State at solar noon is shortest on which date?',
      choices: [
        'December 21',
        'March 21',
        'June 21',
        'September 21',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'On June 21 (summer solstice), the Sun reaches its highest altitude in the sky in New York State, so shadows cast at solar noon are shortest.',
      diveDeep: 'Shadow length is inversely related to the Sun\'s altitude angle. The higher the Sun is in the sky, the shorter the shadow. In New York State (mid-latitudes of Northern Hemisphere), the Sun is highest on June 21 (summer solstice) and lowest on December 21 (winter solstice). At solar noon on June 21, the Sun is at its maximum altitude for the year — approximately 70° above the horizon at 43°N latitude. Students should understand the relationship between sun angle, shadow length, and seasons.',
    },
    {
      number: 3,
      part: 'A',
      text: 'What is the best evidence that Earth is spherical in shape?',
      choices: [
        'The Sun appears to rise in the east every day.',
        'Ships disappear bottom-first as they sail over the horizon.',
        'Day and night are equal in length at the equinoxes.',
        'The constellations change with the seasons.',
      ],
      topic: 'General',
      correct: 1,
      explanation: 'Ships disappearing bottom-first over the horizon is direct evidence of Earth\'s curved surface — if Earth were flat, ships would simply get smaller as they moved away.',
      diveDeep: 'Multiple lines of evidence support Earth\'s spherical shape: (1) ships disappearing hull-first over the horizon, (2) Earth\'s circular shadow on the Moon during lunar eclipses, (3) different constellations visible from different latitudes, (4) the altitude of Polaris increases as you travel north, and (5) circumnavigation of Earth. Aristotle first provided evidence for a spherical Earth over 2,000 years ago. Students should know these classic evidences and be able to connect the observation to the conclusion.',
    },
    {
      number: 4,
      part: 'A',
      text: 'Which layer of Earth\'s atmosphere contains most of the weather phenomena that affect people on Earth\'s surface?',
      choices: [
        'stratosphere',
        'mesosphere',
        'troposphere',
        'thermosphere',
      ],
      topic: 'Meteorology',
      correct: 2,
      explanation: 'The troposphere is the lowest layer of the atmosphere, containing the majority of the atmosphere\'s water vapor and air mass; virtually all weather occurs in this layer.',
      diveDeep: 'The troposphere extends from Earth\'s surface to about 12 km altitude. It contains approximately 75–80% of all atmospheric mass and almost all water vapor. Temperature decreases with altitude in the troposphere at the environmental lapse rate (~6.5°C/km). The tropopause marks the boundary between the troposphere and stratosphere. Weather (clouds, precipitation, fronts, storms) is confined to the troposphere. The stratosphere contains the ozone layer; the mesosphere is where meteors burn up; the thermosphere contains the ionosphere. Students should know the layers in order from surface up: troposphere → stratosphere → mesosphere → thermosphere.',
    },
    {
      number: 5,
      part: 'A',
      text: 'The diagram shows four positions of the Moon in its orbit around Earth, labeled 1 through 4. Which position represents a full moon phase?',
      choices: [
        'Position 1 — Moon on the opposite side of Earth from the Sun',
        'Position 2 — Moon between Earth and Sun',
        'Position 3 — Moon at 90° angle to Earth-Sun line (right side)',
        'Position 4 — Moon at 90° angle to Earth-Sun line (left side)',
      ],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'A full moon occurs when the Moon is on the opposite side of Earth from the Sun, so the entire sunlit face of the Moon is visible from Earth.',
      diveDeep: 'Moon phases depend on the relative positions of Earth, Moon, and Sun. Full moon: Moon opposite Sun (fully illuminated from Earth\'s perspective); New moon: Moon between Earth and Sun (dark side facing Earth); First quarter: Moon 90° east of Sun (right half illuminated); Third quarter: Moon 90° west of Sun (left half illuminated). Spring (higher range) tides occur at new and full moon. The Moon\'s orbital period is ~27.3 days (sidereal) but the synodic period (new moon to new moon) is ~29.5 days due to Earth\'s orbital motion. Students must know moon phases from orbital diagrams.',
    },
    {
      number: 6,
      part: 'A',
      text: 'Which property of air changes most directly when air is compressed into a smaller volume?',
      choices: [
        'composition',
        'density',
        'temperature',
        'humidity',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'Compressing air into a smaller volume increases the number of molecules per unit volume, directly increasing air density.',
      diveDeep: 'Density = mass/volume. When air is compressed (volume decreases) while mass stays constant, density increases proportionally. Air composition (N₂, O₂, etc.) does not change with compression. Temperature changes when air is compressed adiabatically (compressed air warms, expanding air cools) — this is the basis for adiabatic lapse rate and explains why descending air warms. Humidity (water vapor content) can change if air is cooled past the dewpoint during expansion. The direct and immediate change upon compression is density. This concept connects to atmospheric pressure: higher pressure = more compressed = denser air.',
    },
    {
      number: 7,
      part: 'A',
      text: 'The dry-bulb temperature at a weather station is 22°C and the dewpoint is 10°C. Which statement best describes the relative humidity at this location?',
      choices: [
        'The relative humidity is 100% because the air is saturated.',
        'The relative humidity is low because the air temperature is much higher than the dewpoint.',
        'The relative humidity is high because there is a large difference between the dry-bulb and dewpoint.',
        'The relative humidity cannot be determined from this information.',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'A large difference between air temperature (22°C) and dewpoint (10°C) indicates the air is far from saturation, meaning relative humidity is low.',
      diveDeep: 'Relative humidity expresses how close air is to saturation. When air temperature equals the dewpoint, relative humidity = 100% (saturated). The larger the difference between air temperature and dewpoint, the lower the relative humidity. With a 12°C difference (22°C − 10°C), the air is far from saturation — relative humidity would be approximately 40–50% (check the Reference Table for precise values). Students should use the Reference Table Relative Humidity chart: find the dry-bulb row and the wet-bulb depression column. The dewpoint can be used with the separate Dewpoint table. A dewpoint near the air temperature means high humidity; a large difference means low humidity.',
    },
    {
      number: 8,
      part: 'A',
      text: 'Which type of front is associated with a long period of light to moderate precipitation over a large area?',
      choices: [
        'cold front',
        'warm front',
        'occluded front',
        'stationary front',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'Warm fronts advance slowly, with warm air gradually rising over the retreating cold air at a gentle slope, producing widespread, long-duration light to moderate precipitation.',
      diveDeep: 'Front characteristics: cold front — steep frontal boundary, fast movement, brief intense precipitation (thunderstorms), rapid temperature drop after passage; warm front — gradual slope, slow movement, widespread light precipitation (stratus clouds, drizzle/rain) over large areas, temperatures rise after passage; stationary front — nearly stationary, prolonged precipitation; occluded front — forms when cold front overtakes warm front, complex precipitation patterns. The gentle slope of a warm front (1:100–1:200 ratio) allows warm air to rise slowly and cool gradually, producing extensive stratiform clouds and precipitation ahead of the surface front. Students should know cloud types and precipitation associated with each front type.',
    },
    {
      number: 9,
      part: 'A',
      text: 'According to the Earth Science Reference Tables, what is the half-life of carbon-14?',
      choices: [
        '5,700 years',
        '1.3 × 10⁹ years',
        '4.5 × 10⁹ years',
        '1.4 × 10¹⁰ years',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'The Reference Tables list the half-life of carbon-14 as approximately 5,700 years, which limits its usefulness for dating materials older than about 50,000 years.',
      diveDeep: 'Carbon-14 dating (radiocarbon dating) is used for organic materials up to ~50,000 years old (about 9 half-lives). After 10 half-lives (~57,000 years), too little C-14 remains for accurate measurement. C-14 forms in the atmosphere when cosmic rays convert N-14 to C-14; living organisms incorporate it; after death, the C-14 decays and the ratio of C-14 to C-12 decreases. The other half-lives: K-40 = 1.3 × 10⁹ years (for older rocks), U-238 = 4.5 × 10⁹ years (for very old rocks). Students should know all radioactive isotopes and their half-lives from the Reference Tables and which materials/time ranges each is appropriate for dating.',
    },
    {
      number: 10,
      part: 'A',
      text: 'A rock sample contains equal amounts of uranium-238 and lead-206 (the decay product of U-238). How old is this rock?',
      choices: [
        '1.0 × 10⁹ years',
        '2.25 × 10⁹ years',
        '4.5 × 10⁹ years',
        '9.0 × 10⁹ years',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'Equal amounts of parent (U-238) and daughter (Pb-206) means exactly one half-life has elapsed; the half-life of U-238 is 4.5 × 10⁹ years, so the rock is 4.5 billion years old.',
      diveDeep: 'When the parent and daughter isotopes are in equal amounts (50% parent, 50% daughter), exactly one half-life has passed. For U-238 (half-life = 4.5 × 10⁹ years), this gives an age of 4.5 billion years. This is approximately the age of Earth! The oldest Earth rocks (~4.4 Ga) and lunar samples (~4.5 Ga) are dated using U-Pb methods. Students should be able to quickly recognize: equal parent/daughter = 1 half-life; 1/4 parent remaining = 2 half-lives; 1/8 parent remaining = 3 half-lives. Always identify the parent isotope and look up its half-life in the Reference Tables.',
    },
    {
      number: 11,
      part: 'A',
      text: 'The diagram shows horizontal rock layers A, B, C, and D, from top to bottom. Layer A is at the surface. Which rock layer is the oldest?',
      choices: [
        'Layer A',
        'Layer B',
        'Layer C',
        'Layer D',
      ],
      topic: 'Geology',
      correct: 3,
      explanation: 'According to the principle of superposition, in undisturbed (non-overturned) horizontal rock layers, the oldest layer is at the bottom — Layer D is the oldest.',
      diveDeep: 'The principle of superposition (Steno, 1669) states that in any undisturbed sequence of rock layers, the oldest rocks are at the bottom and the youngest are at the top, because each new layer is deposited on top of existing layers. This principle applies only to undeformed (non-overturned) sequences. If rocks have been folded or overturned, graded bedding, fossil orientation, or way-up structures must be used to determine original orientation. This is one of the four fundamental principles of relative dating tested on the Regents. Students should automatically apply superposition when given a cross-section with horizontal layers.',
    },
    {
      number: 12,
      part: 'A',
      text: 'A river deposits sediment when it flows into a calm lake. Which sediment particle is deposited closest to the river mouth?',
      choices: [
        'clay (0.001 mm diameter)',
        'silt (0.01 mm diameter)',
        'sand (0.5 mm diameter)',
        'pebble (5 mm diameter)',
      ],
      topic: 'Water Cycle',
      correct: 3,
      explanation: 'When stream velocity decreases at the river mouth, the largest, heaviest particles (pebbles) settle out first, closest to the shore; finer particles are carried farther into the lake.',
      diveDeep: 'Sediment sorting by a stream follows Stokes\' Law: larger, denser particles settle faster. As a river enters a lake or ocean, velocity decreases and the stream can no longer carry its full sediment load. Coarse particles (gravel, pebbles) deposit immediately; sand deposits next; silt farther out; clay may remain in suspension for long distances. This graded sorting creates a characteristic pattern in deltas and offshore deposits. The Reference Table lists sediment particle sizes: boulder (>256 mm), cobble (64–256 mm), pebble (2–64 mm), sand (0.06–2 mm), silt (0.004–0.06 mm), clay (<0.004 mm).',
    },
    {
      number: 13,
      part: 'A',
      text: 'What type of rock is formed directly from magma that cools and solidifies inside Earth\'s crust?',
      choices: [
        'extrusive igneous rock',
        'intrusive igneous rock',
        'clastic sedimentary rock',
        'foliated metamorphic rock',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Intrusive igneous rocks (also called plutonic rocks) form when magma cools slowly deep within Earth\'s crust, allowing large crystals to develop.',
      diveDeep: 'Igneous rocks are classified by cooling rate and crystal size: intrusive (plutonic) — cools slowly underground, produces coarse-grained rocks with large crystals (e.g., granite, gabbro); extrusive (volcanic) — cools rapidly at the surface, produces fine-grained or glassy rocks with small or no crystals (e.g., rhyolite, basalt, obsidian). Slow cooling = more time for crystal growth = larger crystals. Granite is the most common intrusive igneous rock; basalt is the most common extrusive. The texture of igneous rocks is the primary indicator of cooling environment. Students should use the Reference Table\'s igneous rock chart to identify rocks by texture and composition.',
    },
    {
      number: 14,
      part: 'A',
      text: 'The diagram shows a geological cross-section with a diabase sill cutting through horizontal sedimentary rock layers. Which statement about the relative age of the diabase sill is correct?',
      choices: [
        'The diabase sill is older than all the rock layers it cuts through.',
        'The diabase sill is younger than all the rock layers it intrudes into.',
        'The diabase sill is the same age as the rock layers it contacts.',
        'The relative age of the diabase sill cannot be determined.',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'By the principle of cross-cutting relationships, any rock that cuts through or intrudes into another rock must be younger than the rock it intrudes.',
      diveDeep: 'The principle of cross-cutting relationships states that intrusions and faults are younger than the rocks they cut through. A diabase sill is a sheet of intrusive igneous rock injected parallel to existing rock layers — it must have been emplaced after the surrounding sedimentary rocks existed. Additional evidence: contact metamorphism (baked zones) in the sedimentary rock adjacent to the diabase confirms the intrusion was the younger, hotter element. This principle works for any cross-cutting feature: igneous intrusions, faults, dikes, and veins are always younger than what they cross-cut. Students should apply this principle to every cross-section they encounter on the Regents.',
    },
    {
      number: 15,
      part: 'A',
      text: 'Which surface ocean current carries warm water from the tropics along the eastern coast of North America?',
      choices: [
        'California Current',
         'Gulf Stream',
        'Labrador Current',
        'North Pacific Current',
      ],
      topic: 'Climate',
      correct: 1,
      explanation: 'The Gulf Stream is a warm surface current that flows northward from the Gulf of Mexico along the eastern coast of North America, transporting tropical heat to higher latitudes.',
      diveDeep: 'The Gulf Stream is one of the strongest ocean currents on Earth, transporting enormous amounts of heat and influencing the climate of Eastern North America and Western Europe. It is part of the North Atlantic Gyre, a large clockwise circulation driven by trade winds and westerlies. The California Current is a cold current along the western coast of North America (flowing southward); the Labrador Current is a cold current flowing southward along the northeastern coast of North America. Students should know the major ocean currents and their temperature (warm vs. cold) and direction from the Reference Tables.',
    },
    {
      number: 16,
      part: 'A',
      text: 'Which New York State landscape region is composed primarily of Precambrian metamorphic and igneous rocks?',
      choices: [
        'Catskills',
        'Hudson-Mohawk Lowlands',
        'Adirondacks',
        'Erie-Ontario Lowlands',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'The Adirondack Mountains are a dome of ancient Precambrian metamorphic and igneous rocks, including gneiss and anorthosite, which are the oldest surface rocks in New York State.',
      diveDeep: 'The New York State landscape is divided into several distinct physiographic regions based on bedrock type and age (Reference Table maps). The Adirondacks: Precambrian (~1 billion years old) metamorphic/igneous rocks (gneiss, anorthosite), forming a dome structure. The Catskills: Devonian sedimentary rocks (shale, sandstone). The Hudson-Mohawk Lowlands: Ordovician sedimentary rocks. The Erie-Ontario Lowlands: Silurian/Ordovician sedimentary rocks. Students must know the major NY landscape regions, their bedrock ages, and characteristic rock types from the Reference Table geological map of New York State.',
    },
    {
      number: 17,
      part: 'A',
      text: 'An earthquake occurs at 3:00:00 p.m. The P-wave arrives at a seismic station at 3:04:00 p.m. Using the seismic wave travel-time graph, approximately how far is this station from the epicenter?',
      choices: [
        '500 km',
        '1000 km',
        '2000 km',
        '3000 km',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'If the earthquake occurred at 3:00:00 and P-waves arrived at 3:04:00, the P-wave travel time is 4 minutes; using the Reference Table travel-time graph, 4 minutes corresponds to approximately 2000 km distance.',
      diveDeep: 'Seismic wave travel times from the Reference Table: P-waves travel at approximately 5–8 km/s. At 2000 km distance, P-wave travel time is approximately 4 minutes. To use the graph: find the P-wave curve and locate the point corresponding to 4 minutes of travel time — read the distance off the horizontal axis. Students frequently make errors reading the graph scale or confusing P and S wave curves. Practice: for each 1000 km of distance, P-waves take about 2 minutes. Always use the Reference Table rather than calculating from wave speed, as the graph accounts for wave speed changes at depth.',
    },
    {
      number: 18,
      part: 'A',
      text: 'The diagram shows a cross-section of Earth\'s interior layers. Which layer do S-waves fail to pass through, providing evidence that this layer is liquid?',
      choices: [
        'lower mantle',
        'asthenosphere',
        'outer core',
        'inner core',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'S-waves cannot travel through liquids; they do not pass through Earth\'s outer core, providing strong evidence that the outer core is in a liquid (molten) state.',
      diveDeep: 'The discovery that S-waves create a "shadow zone" on the opposite side of Earth from an earthquake — a region that receives no S-waves — led seismologists to infer that Earth has a liquid outer core. P-waves are also affected, but they refract rather than disappear entirely. The outer core is liquid iron-nickel at temperatures of ~4000–5000°C; the inner core is solid iron-nickel (kept solid by enormous pressure despite high temperature). This liquid outer core is also responsible for generating Earth\'s magnetic field through convection (the geodynamo). Students should know: S-waves = solid materials only; P-waves = solids, liquids, and gases.',
    },
    {
      number: 19,
      part: 'A',
      text: 'According to the plate tectonic theory, which process occurs at mid-ocean ridges?',
      choices: [
        'Oceanic crust is subducted into the mantle.',
        'Continental crust collides to form mountain ranges.',
        'New oceanic crust is created as magma solidifies.',
        'Existing crust is compressed and thickened.',
      ],
      topic: 'Plate Tectonics',
      correct: 2,
      explanation: 'Mid-ocean ridges are divergent plate boundaries where magma rises from the mantle, solidifies, and creates new oceanic crust through the process of seafloor spreading.',
      diveDeep: 'Mid-ocean ridges are the longest mountain chain on Earth, stretching over 65,000 km through all ocean basins. At the ridge center, mantle material rises and melts partially, forming basaltic magma that solidifies to create new oceanic crust. As new crust forms, older crust moves away from the ridge symmetrically. Evidence for seafloor spreading: age of ocean floor increases away from ridges; magnetic striping (symmetrical magnetic anomalies); heat flow is highest at ridges. Subduction (crust entering the mantle) occurs at convergent boundaries — the opposite of ridges. Students should clearly distinguish divergent (creating crust) from convergent (destroying crust) boundaries.',
    },
    {
      number: 20,
      part: 'A',
      text: 'Which process results in the chemical weathering of limestone?',
      choices: [
        'Frost action cracks the limestone apart.',
        'Plant roots mechanically break the limestone.',
        'Slightly acidic rainwater dissolves the calcium carbonate in limestone.',
        'Sand carried by wind abrades the limestone surface.',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'Carbon dioxide in the atmosphere dissolves in rainwater to form a weak carbonic acid, which chemically reacts with calcium carbonate in limestone, dissolving it through a process called carbonation.',
      diveDeep: 'Chemical weathering of limestone: CO₂ + H₂O → H₂CO₃ (carbonic acid); then H₂CO₃ + CaCO₃ → Ca²⁺ + 2HCO₃⁻ (dissolved). This creates karst topography — sinkholes, caves, and caverns. Limestone is particularly susceptible because its mineral (calcite) is soluble in weak acid. Frost action, root growth, and abrasion are all mechanical (physical) weathering — they change shape/size without changing chemical composition. Chemical weathering changes the mineral composition. In New York State, carbonate rock landscapes (especially in the Helderberg area) show karst features from this dissolution. Students must distinguish physical from chemical weathering.',
    },
    {
      number: 21,
      part: 'A',
      text: 'Which type of rock commonly forms from the remains of organisms such as shells and marine organisms?',
      choices: [
        'granite',
        'limestone',
        'quartzite',
        'obsidian',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Limestone is a sedimentary rock commonly formed from the accumulation and compaction of marine organism shells and skeletons composed of calcium carbonate (calcite).',
      diveDeep: 'Biochemical/bioclastic sedimentary rocks form from organic remains: limestone (CaCO₃ from shells and marine organisms), coal (compressed plant matter), coquina (fragments of shells), chalk (microscopic shell fragments). Granite is an intrusive igneous rock; quartzite is metamorphic (from sandstone); obsidian is extrusive igneous (volcanic glass). Limestone is extremely common in New York State (especially from Silurian and Devonian marine environments) and underlies many of the lowland regions. The Reference Table rock identification chart categorizes sedimentary rocks by origin: clastic (broken rock fragments), bioclastic (organic fragments), and chemical (precipitated from solution).',
    },
    {
      number: 22,
      part: 'A',
      text: 'New York State glacial deposits known as moraines were formed primarily by',
      choices: [
        'wind deposition',
        'stream deposition',
        'volcanic ash fall',
        'glacial deposition',
      ],
      topic: 'Geology',
      correct: 3,
      explanation: 'Moraines are landforms composed of unsorted glacial till deposited directly by glacial ice, typically forming ridges that mark the maximum advance or retreat positions of a glacier.',
      diveDeep: 'Moraines are characteristic glacial landforms: terminal moraines mark the farthest advance of a glacier; recessional moraines mark temporary halts during retreat; lateral moraines form along the sides of valley glaciers; ground moraines are thin sheets of till. Long Island and Cape Cod are terminal moraines from the Laurentide Ice Sheet. Glacial deposits are unsorted (till) — a mixture of particle sizes from clay to boulders, unlike stream deposits which are sorted by size. Drumlins (elongated hills), kettle lakes, outwash plains, and eskers are other glacial features important in New York State. Students should know common glacial landforms and their formation.',
    },
    {
      number: 23,
      part: 'A',
      text: 'Which process is responsible for the formation of a V-shaped stream valley?',
      choices: [
        'glacial erosion',
        'stream erosion',
        'mass wasting (landslides)',
        'wave erosion',
      ],
      topic: 'Water Cycle',
      correct: 1,
      explanation: 'Streams cut downward into bedrock, forming V-shaped valleys with steep sides, as running water erodes the channel floor more rapidly than the valley walls.',
      diveDeep: 'Valley shapes reflect the dominant erosional agent: V-shaped valleys — formed by streams cutting rapidly downward (downcutting); characteristic of young, actively eroding streams or rivers in steep terrain. U-shaped valleys — formed by glacial erosion; glaciers are much wider than streams and erode the valley walls as well as the floor. Recognizing valley shape is a key skill on the Regents. In New York State: the Hudson River Valley has a broad valley from past glaciation; mountain streams in the Catskills show V-shaped valleys. A V-shape means the stream is still actively eroding; a U-shape means a glacier passed through. Students should connect valley shape to erosional agent.',
    },
    {
      number: 24,
      part: 'A',
      text: 'Which evidence best supports the theory of continental drift?',
      choices: [
        'All continents are surrounded by ocean water.',
        'Matching rock types and fossils are found on opposite sides of the Atlantic Ocean.',
        'Earthquakes occur most frequently in ocean basins.',
        'The Atlantic Ocean has been getting shallower over time.',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'Matching rock formations, mountain chains, and identical fossils found on both sides of the Atlantic (e.g., the same Mesosaurus fossil in South America and Africa) provide compelling evidence that these continents were once joined.',
      diveDeep: 'Alfred Wegener proposed continental drift in 1912 based on multiple lines of evidence: (1) Matching coastlines — especially Africa and South America; (2) Matching rock types and mountain ranges across oceans (Appalachians match Scottish Highlands when continents are joined); (3) Identical fossils (Mesosaurus, Glossopteris) on continents now separated by wide oceans; (4) Glacial evidence — glacial deposits found in tropical Africa suggest former polar position; (5) Paleoclimatic evidence — coal deposits in Antarctica from ancient tropical forests. Students should know all major lines of evidence for continental drift/plate tectonics and what each demonstrates.',
    },
    {
      number: 25,
      part: 'A',
      text: 'The diagram shows stream gradient decreasing from the mountains to the mouth of a river. At which location along the river would the largest boulders most likely be deposited?',
      choices: [
        'At the river mouth where it enters the ocean',
        'In the middle section of the river\'s course',
        'Near the headwaters where gradient is steepest',
        'In the delta where the river spreads out',
      ],
      topic: 'Water Cycle',
      correct: 2,
      explanation: 'The largest boulders require the most energy to transport; near the headwaters where gradient is steepest and velocity is highest, streams can move boulders but quickly deposit them when velocity decreases.',
      diveDeep: 'Stream competence (the largest particle a stream can carry) varies with the stream\'s velocity — competence increases as the sixth power of velocity (the 6th power law). Near steep mountain headwaters, high velocity can transport large boulders, but they are deposited quickly when the gradient decreases. The middle course transports medium-sized particles. Near the mouth/delta, only fine silt and clay are transported and deposited. This downstream sorting (boulders → cobbles → pebbles → sand → silt → clay) is a fundamental concept in fluvial geomorphology. Students should understand the connection between gradient, velocity, particle size, and deposition location.',
    },
    {
      number: 26,
      part: 'A',
      text: 'Which factor most influences the type of metamorphic rock formed from a parent rock?',
      choices: [
        'The age of the parent rock',
        'The color of the parent rock',
        'The temperature and pressure conditions during metamorphism',
        'The distance of the parent rock from the surface',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'The type of metamorphic rock formed depends primarily on the temperature and pressure conditions experienced during metamorphism, which determine which new minerals form and whether the rock becomes foliated.',
      diveDeep: 'Metamorphic rock type is controlled by two main factors: (1) parent rock composition — what minerals are present to recrystallize; and (2) metamorphic conditions — temperature, pressure, and fluids. High temperature + high pressure (regional metamorphism) produces foliated rocks like slate → phyllite → schist → gneiss (in order of increasing grade). High temperature alone (contact metamorphism) produces non-foliated rocks like hornfels, marble, quartzite. The same parent rock (e.g., shale) can produce different metamorphic rocks depending on conditions: low-grade = slate; medium-grade = phyllite; high-grade = schist; very high grade = gneiss. Students should use the Reference Table metamorphic rock chart.',
    },
    {
      number: 27,
      part: 'A',
      text: 'Which characteristic makes a fossil useful as a New York State index fossil?',
      choices: [
        'The organism lived for a very long period of geologic time.',
        'The organism lived during a short, specific period and was found over a wide geographic area.',
        'The fossil is made of durable mineral materials.',
        'The organism lived only in a very specific local environment.',
      ],
      topic: 'Geologic Time',
      correct: 1,
      explanation: 'Index fossils must have lived during a short, well-defined time period and been widespread geographically, so that their presence in rock layers precisely identifies the age of those layers.',
      diveDeep: 'An ideal index fossil has two key characteristics: (1) Short time range — the organism lived for only a brief geologic period, making its presence a precise time indicator; (2) Wide geographic distribution — found over large areas so it can be used to correlate rocks from different locations. New York State index fossils include trilobites, brachiopods, corals, cephalopods, and various other marine organisms, each associated with specific time periods (listed in the Reference Tables). A fossil that lived for hundreds of millions of years (like horseshoe crabs) is not useful as an index fossil because it cannot pinpoint a specific time period. Students must know both criteria.',
    },
    {
      number: 28,
      part: 'A',
      text: 'According to the Reference Tables, which rock has the greatest density?',
      choices: [
        'granite',
        'basalt',
        'pumice',
        'rhyolite',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'Basalt is a mafic igneous rock rich in iron and magnesium minerals; according to the Reference Tables, basalt has a higher density (~3.0 g/cm³) than granite (~2.7 g/cm³) or other felsic rocks.',
      diveDeep: 'Rock density correlates with mineral composition: mafic rocks (rich in iron-magnesium silicates like olivine, pyroxene, amphibole) are denser; felsic rocks (rich in quartz, feldspar, and light minerals) are less dense. From the Reference Tables: basalt ~3.0 g/cm³; gabbro ~3.0 g/cm³; granite ~2.7 g/cm³; rhyolite ~2.7 g/cm³; pumice <1.0–2.0 g/cm³ (porous volcanic glass). Pumice is the least dense rock — it can even float on water! The density difference between oceanic basalt and continental granite is the fundamental reason oceanic plates subduct under continental plates at convergent boundaries.',
    },
    {
      number: 29,
      part: 'A',
      text: 'What is the inferred primary cause of Earth\'s seasons?',
      choices: [
        'The changing distance between Earth and the Sun throughout the year',
        'The tilt of Earth\'s rotational axis as Earth revolves around the Sun',
        'The varying speed of Earth\'s orbital motion',
        'The difference in albedo between land and ocean surfaces',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'Seasons are primarily caused by Earth\'s 23.5° axial tilt, which causes each hemisphere to receive different amounts of solar energy as Earth revolves around the Sun.',
      diveDeep: 'Earth\'s axial tilt causes two effects that produce seasons: (1) Sun angle — when tilted toward the Sun, sunlight strikes more directly (more concentrated energy per unit area); (2) Day length — when tilted toward the Sun, days are longer (more hours of daylight for heating). Both effects combine to make summers hot and winters cold. The distance between Earth and Sun is NOT the cause — Earth is actually slightly closer to the Sun in January (Northern Hemisphere winter) than in July (Northern Hemisphere summer). This is a very common misconception! Earth\'s orbital distance varies only about 3% and has only a minor effect on seasons. Students must reject the "closer to Sun = warmer" misconception.',
    },
    {
      number: 30,
      part: 'A',
      text: 'The diagram shows a weather map of the eastern United States with isobars (lines of equal pressure). Wind near the surface of a Northern Hemisphere low-pressure center flows',
      choices: [
        'outward and clockwise',
        'outward and counterclockwise',
        'inward and clockwise',
        'inward and counterclockwise',
      ],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'In the Northern Hemisphere, air flows inward toward a low-pressure center (convergence) and is deflected counterclockwise by the Coriolis effect, creating a counterclockwise cyclone.',
      diveDeep: 'Northern Hemisphere wind patterns: low-pressure centers (cyclones) — inward and counterclockwise; high-pressure centers (anticyclones) — outward and clockwise. In the Southern Hemisphere, these directions are reversed due to opposite Coriolis deflection. The Coriolis effect deflects moving air to the right in the Northern Hemisphere. This, combined with the pressure gradient force (toward lower pressure) and friction, produces the observed spiral wind pattern. Cyclones (lows) are associated with cloudy, stormy weather; anticyclones (highs) are associated with clear, fair weather. Students should memorize: NH low = counterclockwise inflow; NH high = clockwise outflow.',
    },
    {
      number: 31,
      part: 'A',
      text: 'Which observation provides the best evidence that the universe is expanding?',
      choices: [
        'The cosmic microwave background radiation is uniform.',
        'The spectra of distant galaxies show a red shift.',
        'Stars in distant galaxies are older than nearby stars.',
        'Distant galaxies contain the same elements as nearby stars.',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'The red shift observed in the spectra of distant galaxies indicates they are moving away from us; the farther the galaxy, the greater the red shift, supporting an expanding universe.',
      diveDeep: 'The Doppler effect for light: when a light source moves away from an observer, the wavelength is stretched toward the red (longer wavelength) end of the spectrum — this is red shift. Edwin Hubble discovered in 1929 that almost all galaxies show red shift, and the more distant the galaxy, the greater the red shift. This implies all galaxies are moving away from each other — the universe is expanding. Extrapolating backward, this expansion implies the universe began from a single point — the Big Bang. The cosmic microwave background radiation is also evidence for the Big Bang but specifically for its hot origin, not the current expansion. Students should know: red shift = moving away = expanding universe.',
    },
    {
      number: 32,
      part: 'A',
      text: 'Which best describes the position of the Sun in our Milky Way Galaxy?',
      choices: [
        'At the center of the Milky Way Galaxy',
        'On a spiral arm, approximately 26,000 light-years from the center',
        'Outside the Milky Way Galaxy, orbiting around it',
        'At the edge of the Milky Way Galaxy, in the outermost ring',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'The Sun is located in the Orion Arm (a minor spiral arm) of the Milky Way Galaxy, approximately 26,000 light-years from the galactic center.',
      diveDeep: 'The Milky Way is a barred spiral galaxy containing approximately 200–400 billion stars. The Sun is located in the Orion Arm about halfway between the center and the outer edge (~26,000 light-years from center, in a galaxy ~100,000 light-years in diameter). The Sun orbits the galactic center at about 220 km/s, completing one revolution in about 225 million years (a "galactic year"). From Earth, we see the Milky Way as a band of light across the sky — we are inside the disk looking edge-on through it. Students should know the basic structure of the Milky Way and the Sun\'s approximate location within it.',
    },
    {
      number: 33,
      part: 'A',
      text: 'According to the Hertzsprung-Russell (H-R) diagram, which group of stars is both very bright and very cool?',
      choices: [
        'White dwarfs',
        'Main sequence stars',
        'Giants and supergiants',
        'Neutron stars',
      ],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'Giant and supergiant stars appear in the upper right of the H-R diagram, indicating they are extremely luminous (bright) but relatively cool (orange to red surface temperatures).',
      diveDeep: 'The H-R diagram plots stellar luminosity (y-axis) versus surface temperature (x-axis, right = cool, left = hot). Main regions: main sequence (diagonal band — most stars including the Sun); red giants/supergiants (upper right — cool but large/bright); white dwarfs (lower left — hot but small/dim). A star is bright because of large size, not necessarily high temperature — giants and supergiants are enormous, compensating for lower temperature with greater surface area. Betelgeuse is a classic red supergiant: cool (3,500 K), but so enormous it would engulf Jupiter\'s orbit. Students should be able to locate each stellar group on the H-R diagram.',
    },
    {
      number: 34,
      part: 'A',
      text: 'In which order do the following events occur in the life cycle of a star like the Sun?',
      choices: [
        'Main sequence → nebula → red giant → white dwarf',
        'Nebula → main sequence → red giant → white dwarf',
        'Nebula → red giant → main sequence → white dwarf',
        'Main sequence → red giant → neutron star → black hole',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'A solar-mass star begins as a nebula (gas cloud), enters the main sequence (hydrogen fusion), expands into a red giant (helium fusion), then sheds its outer layers to become a planetary nebula and finally a white dwarf.',
      diveDeep: 'Stellar life cycle for a Sun-like star (low/medium mass): Nebula → protostar → main sequence star (90% of life, H→He fusion) → red giant (H exhausted in core, outer layers expand) → planetary nebula (outer layers ejected) → white dwarf (hot core remnant). High-mass stars follow a different path: main sequence → supergiant → supernova → neutron star or black hole. The Sun will become a red giant in about 5 billion years, eventually engulfing Earth. Students should know both low-mass and high-mass stellar evolution paths and what determines which path a star takes (mass).',
    },
    {
      number: 35,
      part: 'A',
      text: 'Which statement best describes the relationship between topographic contour lines and stream direction on a topographic map?',
      choices: [
        'Contour lines cross streams at right angles, pointing downstream.',
        'Contour lines point upstream (toward higher elevation) when crossing valleys.',
        'Contour lines run parallel to stream channels.',
        'Contour lines always indicate stream positions.',
      ],
      topic: 'Maps',
      correct: 1,
      explanation: 'When contour lines cross a stream valley, they form a V-shape that points upstream (toward the source, uphill), because the valley floor is lower in elevation than the surrounding land.',
      diveDeep: 'This is one of the most important topographic map reading rules on the Regents: contour lines always form a V-shape when crossing a valley, with the V pointing in the upstream direction (toward higher elevation). This allows you to determine stream flow direction: water flows in the opposite direction from which the V points (water flows away from the point of the V). On ridges, contour lines also form V-shapes but pointing downhill. Practice by identifying which way V-shapes point — if they point toward higher elevations, it\'s a valley; if they point toward lower elevations, it\'s a ridge. This skill appears in nearly every Earth Science Regents exam.',
    },
    {
      number: 36,
      part: 'B-1',
      text: 'A cross section shows rock layers with an unconformity. Below the unconformity are tilted metamorphic rocks; above are horizontal sedimentary layers. Which sequence of events created this unconformity, from oldest to most recent?',
      choices: [
        'Deposition → erosion → tilting → deposition of sedimentary layers',
        'Tilting → metamorphism → erosion → deposition of sedimentary layers',
        'Metamorphism → tilting → erosion → deposition of sedimentary layers',
        'Erosion → metamorphism → tilting → deposition of sedimentary layers',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'The metamorphic rocks formed first (oldest), then tectonic forces tilted them, then erosion created a flat surface (the unconformity), then new sediments were deposited horizontally on top.',
      diveDeep: 'An angular unconformity represents a gap in the geologic record — time when rocks were tilted, eroded, and then covered by new horizontal layers. Reading a cross-section with an unconformity requires applying multiple principles: (1) superposition — older below, newer above; (2) cross-cutting relationships; (3) original horizontality — sedimentary layers are deposited flat; if tilted, they were deformed after deposition. The sequence is always: original deposition → tilting/faulting → erosion (creating the unconformity surface) → new deposition. The unconformity surface itself is the erosional surface. Students should practice identifying different types of unconformities: angular, disconformity, and nonconformity.',
    },
    {
      number: 37,
      part: 'B-1',
      text: 'A topographic map shows a hill with concentric contour lines. The contour interval is 20 meters. The innermost closed contour has an elevation of 200 meters and is inside the 180-meter contour. What is the approximate maximum elevation of the hill?',
      choices: [
        'Between 180 and 200 meters',
        'Between 200 and 220 meters',
        'Exactly 200 meters',
        'Greater than 220 meters',
      ],
      topic: 'Maps',
      correct: 1,
      explanation: 'The innermost contour at 200 m means the summit is higher than 200 m; since the next contour would be at 220 m and is not shown (the hill doesn\'t reach it), the summit is between 200 and 220 meters.',
      diveDeep: 'Reading summit elevation from a topographic map: the innermost closed contour tells you the minimum possible summit elevation. The actual summit could be anywhere between that last contour and just below the next contour. If the contour interval is 20 m and the last contour is at 200 m, the summit is somewhere between 200 and 220 m (exclusive). This is a rule students frequently forget — the inner contour gives a minimum, not the exact summit elevation. Students should also know that depression contours (with hachure marks pointing inward) indicate enclosed low points, and their inner contour represents the maximum depth of the depression.',
    },
    {
      number: 38,
      part: 'B-1',
      text: 'The data table shows P-wave and S-wave arrival times at three seismic stations. Using the travel-time graph, which station is closest to the earthquake epicenter?',
      choices: [
        'Station A — P-S time difference of 1 minute 30 seconds',
        'Station B — P-S time difference of 4 minutes',
        'Station C — P-S time difference of 7 minutes',
        'All stations are equidistant from the epicenter',
      ],
      topic: 'Geology',
      correct: 0,
      explanation: 'The smallest P-S wave time difference (1 minute 30 seconds at Station A) indicates the shortest travel distance from the epicenter, making Station A the closest.',
      diveDeep: 'The P-S wave time difference is directly proportional to distance from the earthquake epicenter — the smaller the difference, the closer the station. This is the basis for determining epicenter location: measure P-S time at three stations, convert to distances using the travel-time graph, draw circles around each station with those radii, and the epicenter is where the three circles intersect (triangulation). Students must practice: (1) calculating P-S difference from arrival times; (2) reading the travel-time graph to convert time difference to distance; (3) recognizing that minimum P-S time = minimum distance. Knowing the origin time allows calculation of absolute travel times.',
    },
    {
      number: 39,
      part: 'B-1',
      text: 'A diagram shows the movement of the Hawaiian hotspot chain over the past 70 million years, with volcanic islands becoming progressively older to the northwest. The Big Island is currently over the hotspot. At approximately what rate has the Pacific Plate been moving over the hotspot (in cm/year), if the oldest island in the chain is 70 million years old and is located 7,000 km northwest of the Big Island?',
      choices: [
        '1 cm/year',
        '5 cm/year',
        '10 cm/year',
        '100 cm/year',
      ],
      topic: 'Plate Tectonics',
      correct: 2,
      explanation: '7,000 km = 700,000,000 cm; dividing by 70,000,000 years (70 million years) = 10 cm/year.',
      diveDeep: 'Hotspot chains are "time-stamped" records of plate motion. As the Pacific Plate moves over the stationary Hawaiian hotspot, successive volcanic islands form, creating a chain where older islands are farther from the current hotspot position. Rate = distance/time = 7,000 km / 70 million years = 100 km/million years = 10 cm/year. The Pacific Plate moves northwest at approximately 5–10 cm/year — similar to the rate your fingernails grow! This calculation appears on the Regents and requires unit conversion. Students should know: typical plate movement rates are ~1–15 cm/year. Converting km to cm: 1 km = 100,000 cm.',
    },
    {
      number: 40,
      part: 'B-1',
      text: 'The graph shows the temperature profile of Earth\'s atmosphere from 0 to 80 km altitude. Which atmospheric layer has temperature increasing with altitude?',
      choices: [
        'Troposphere (0–12 km)',
        'Stratosphere (12–50 km)',
        'Mesosphere (50–80 km)',
        'Both the troposphere and mesosphere',
      ],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'Temperature increases with altitude in the stratosphere because ozone in this layer absorbs ultraviolet radiation from the Sun, converting it to heat.',
      diveDeep: 'The atmosphere\'s temperature profile is determined by the dominant energy sources in each layer: Troposphere — temperature decreases with altitude (~6.5°C/km); heated from Earth\'s surface below. Stratosphere — temperature increases with altitude; ozone (O₃) absorbs UV radiation and warms the layer. Mesosphere — temperature decreases with altitude again; sparse gas, little heating source. Thermosphere — temperature increases dramatically; individual gas molecules absorb X-rays and UV but there are so few molecules that the "temperature" is extremely high but little heat is transferred. Students should memorize the temperature trend (decrease/increase/decrease/increase going up) and the reason for each change.',
    },
    {
      number: 41,
      part: 'B-1',
      text: 'The diagram represents Earth\'s position in its orbit and the tilt of its axis on June 21. Which statement correctly describes conditions in the Northern Hemisphere on June 21?',
      choices: [
        'The Northern Hemisphere is tilted away from the Sun and receives the least solar energy.',
        'The Northern Hemisphere is tilted toward the Sun, experiences the longest day, and receives the most direct solar radiation.',
        'Day and night are equal in length throughout the Northern Hemisphere.',
        'The Sun is directly overhead at the equator at solar noon.',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'June 21 is the summer solstice; the Northern Hemisphere is tilted toward the Sun, experiencing the year\'s longest day (most daylight hours) and most direct (highest angle) solar radiation.',
      diveDeep: 'June 21 (summer solstice) conditions in the Northern Hemisphere: (1) Longest day of the year (in NH); (2) Sun is directly overhead at the Tropic of Cancer (23.5°N) at solar noon; (3) Arctic Circle and north experience 24-hour daylight; (4) NH tilted toward Sun = most direct sunlight; (5) Highest solar angle at noon for the year. At the same time in the Southern Hemisphere: shortest day, winter conditions. Equal day/night occurs only at equinoxes (March 21, September 23). Students must know what happens on all four key dates: June 21, December 21, and both equinoxes for both hemispheres.',
    },
    {
      number: 42,
      part: 'B-1',
      text: 'A map of New York State shows the location of a student at Cooperstown, which has an elevation of approximately 400 meters and is located at approximately 42.7°N latitude. At approximately what altitude above the horizon would the student observe Polaris?',
      choices: [
        '41°',
        '42.7°',
        '47.3°',
        '90°',
      ],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'The altitude of Polaris above the horizon equals the observer\'s latitude; at Cooperstown (42.7°N), Polaris would appear approximately 42.7° above the northern horizon.',
      diveDeep: 'The altitude of Polaris = latitude of observer. This direct relationship exists because Polaris is located almost exactly above Earth\'s North Pole — the extension of Earth\'s rotation axis points to Polaris. At the North Pole (90°N), Polaris would be directly overhead (90° altitude); at the equator (0°), Polaris would be on the horizon (0° altitude). Elevation above sea level does not affect the altitude of Polaris significantly — only latitude matters. This is one of the most tested Regents facts in astronomy. Students should know NY city latitudes from the Reference Tables to answer Polaris altitude questions for specific locations.',
    },
    {
      number: 43,
      part: 'B-1',
      text: 'A soil sample collected from a forest in New York State is found to consist of 40% clay, 40% silt, and 20% sand. Using the soil texture triangle from the Reference Tables, what type of soil is this?',
      choices: [
        'sandy loam',
        'silty clay',
        'clay loam',
        'loamy sand',
      ],
      topic: 'Geology',
      correct: 1,
      explanation: 'A soil with 40% clay, 40% silt, and 20% sand plots in the silty clay region of the USDA soil texture triangle.',
      diveDeep: 'The soil texture triangle (sometimes included in earth science courses) classifies soils based on the percentages of sand, silt, and clay. Each corner represents 100% of one particle type. To use the triangle: find the intersection of lines representing the percentages of each component. High clay content = clay or clay loam soils (sticky, poor drainage); high sand content = sandy or loamy sand soils (good drainage, low water retention); balanced mixtures = loam soils (ideal for agriculture). Silt has intermediate particle size and properties. Students should practice reading the triangle by following the three axes simultaneously.',
    },
    {
      number: 44,
      part: 'B-1',
      text: 'The photograph shows bedrock exposed along a New York State roadway. The rock layers are tilted at approximately 30° from the horizontal. Which statement best explains why these originally horizontal rock layers are now tilted?',
      choices: [
        'The rocks were deposited at a 30° angle on an ancient slope.',
        'Erosion removed material from one side, causing the layers to tilt.',
        'Tectonic forces deformed the rock layers after they were deposited horizontally.',
        'The rocks are very old and gravity has caused them to tilt over time.',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'The principle of original horizontality states that sedimentary rocks are deposited in horizontal layers; if they are now tilted, tectonic forces must have deformed them after deposition.',
      diveDeep: 'The principle of original horizontality (Steno, 1669) states that sedimentary rocks are deposited in layers that are nearly horizontal at the time of formation. Therefore, tilted rock layers indicate post-depositional deformation by tectonic forces (compression, tension, or shear). In New York State, tilted and folded rocks are abundant in the Taconic region and Hudson Valley, evidence of the Taconian orogeny (mountain-building event ~440 Ma). Roadcuts often expose these features dramatically. Students should apply original horizontality: if you see tilted sedimentary layers, conclude that tectonic deformation occurred after deposition.',
    },
    {
      number: 45,
      part: 'B-1',
      text: 'A data table shows average monthly temperatures at a coastal city (City A) and an inland city (City B) at the same latitude. City A has a small annual temperature range (18°C); City B has a large annual temperature range (32°C). Which factor best explains this difference?',
      choices: [
        'City A is at a higher elevation than City B.',
        'City A is closer to a large body of water, which moderates temperature.',
        'City B receives more precipitation than City A.',
        'City B is in a different climate zone than City A.',
      ],
      topic: 'Climate',
      correct: 1,
      explanation: 'Large bodies of water have high specific heat and moderate nearby temperatures, reducing the annual temperature range for coastal cities compared to inland cities at the same latitude.',
      diveDeep: 'Water has a high specific heat (~4.18 J/g°C) compared to land (~0.8 J/g°C). This means water heats up and cools down much more slowly than land. Coastal cities are buffered by this thermal mass: summers are cooler and winters are warmer than at inland locations at the same latitude. The difference between marine (oceanic) climate (small temperature range) and continental climate (large temperature range) is a fundamental climate geography concept. New York City (coast) has a smaller annual range than Albany (inland). This question tests whether students can identify the moderating effect of proximity to water. Both cities are at the same latitude, so latitude is not the explanation.',
    },
    {
      number: 46,
      part: 'B-1',
      text: 'The diagram shows ocean floor age data showing the Atlantic Ocean is spreading apart. If the Atlantic Ocean is currently 6000 km wide at one location, and seafloor spreading has been occurring at a rate of 2.5 cm/year on each side of the ridge, how many years ago was the Atlantic Ocean beginning to form at this location?',
      choices: [
        '60 million years ago',
        '120 million years ago',
        '180 million years ago',
        '240 million years ago',
      ],
      topic: 'Plate Tectonics',
      correct: 1,
      explanation: 'Total spreading rate = 2.5 cm/year × 2 sides = 5 cm/year; 6000 km = 600,000,000 cm; 600,000,000 cm ÷ 5 cm/year = 120,000,000 years = 120 million years ago.',
      diveDeep: 'Seafloor spreading calculations: the total widening rate is twice the individual plate rate (both sides spread). Convert distance to cm: 6000 km × 100,000 cm/km = 6 × 10⁸ cm. Total rate = 5 cm/year. Age = distance/rate = 6 × 10⁸ / 5 = 1.2 × 10⁸ years = 120 million years (Cretaceous Period). This matches geologic evidence — the Atlantic began opening about 130–180 Ma when Pangaea broke apart. The key step students miss is doubling the rate because spreading occurs on BOTH sides of the ridge. Practice: always check if the given rate is one-side or total spreading rate.',
    },
    {
      number: 47,
      part: 'B-1',
      text: 'The diagram shows a cross-section of a volcanic island arc system. An oceanic plate is subducting beneath another oceanic plate. Which statement describes what happens to the subducting plate as it descends into the mantle?',
      choices: [
        'It melts completely and the magma rises to form island arc volcanoes.',
        'It is compressed into denser rock and remains in the mantle permanently.',
        'It partially melts as heat and pressure increase, with less dense magma rising to the surface.',
        'It transforms into metamorphic rock that erupts at the surface.',
      ],
      topic: 'Plate Tectonics',
      correct: 2,
      explanation: 'As the oceanic plate subducts, increasing temperature and pressure cause partial melting of the slab and overlying mantle wedge; the less dense magma rises through the overlying plate to form volcanic island arcs.',
      diveDeep: 'At subduction zones, the descending oceanic plate releases water (from hydrated minerals) into the overlying mantle wedge. This water lowers the melting point of mantle rock, causing partial melting (flux melting). The resulting magma is less dense than the surrounding rock, so it rises through the overlying plate to create volcanic island arcs (oceanic-oceanic subduction) or volcanic mountain chains/Andean-type margins (oceanic-continental subduction). The Aleutian Islands (Alaska) and Japan are volcanic island arcs. Students should know the difference between mid-ocean ridge volcanism (decompression melting) and subduction zone volcanism (flux melting from water released from subducting slab).',
    },
    {
      number: 48,
      part: 'B-1',
      text: 'A scientist measures the mineral content of a rock sample and finds it contains approximately 70% quartz, 15% orthoclase feldspar, 10% plagioclase feldspar, and 5% biotite mica. Using the igneous rock classification chart in the Reference Tables, what igneous rock is this sample most likely?',
      choices: [
        'basalt',
        'gabbro',
        'granite',
        'peridotite',
      ],
      topic: 'Geology',
      correct: 2,
      explanation: 'A rock with ~70% quartz and potassium feldspar (orthoclase), with coarse crystals indicating slow cooling, matches the composition and texture of granite in the Reference Tables.',
      diveDeep: 'The Reference Table igneous rock classification chart organizes rocks by mineral composition (felsic to mafic) and texture (intrusive/coarse-grained vs. extrusive/fine-grained). Granite: felsic, coarse-grained (intrusive), high quartz and orthoclase; Rhyolite: same composition but fine-grained (extrusive); Basalt: mafic, fine-grained, low/no quartz, rich in pyroxene and olivine; Gabbro: same composition as basalt but coarse-grained; Peridotite: ultramafic, very high olivine and pyroxene. The high quartz content (70%) and presence of orthoclase feldspar clearly indicate a felsic/granitic composition. Students should practice reading across both axes of the igneous classification chart.',
    },
    {
      number: 49,
      part: 'B-1',
      text: 'A graph shows the mean global temperature anomaly (departure from average) from 1880 to 2020. The data shows a clear upward trend, especially after 1950. Which human activity is most responsible for this trend?',
      choices: [
        'Deforestation reducing albedo of Earth\'s surface',
        'Burning of fossil fuels increasing CO₂ concentrations',
        'Agricultural irrigation altering the hydrologic cycle',
        'Construction of cities creating urban heat islands',
      ],
      topic: 'Climate',
      correct: 1,
      explanation: 'The burning of fossil fuels since the Industrial Revolution has significantly increased atmospheric CO₂, enhancing the greenhouse effect and driving the observed global warming trend.',
      diveDeep: 'Global temperature records show approximately 1.1–1.2°C of warming since the pre-industrial period (before ~1850). The primary driver is the increase in atmospheric CO₂ from ~280 ppm (pre-industrial) to over 420 ppm today, almost entirely due to fossil fuel combustion and deforestation. CO₂ is a greenhouse gas that absorbs outgoing infrared radiation, trapping heat. While deforestation reduces CO₂ absorption and urban heat islands cause local warming, these are not the primary global drivers. Students should distinguish between local/regional effects and global drivers, and know that the scientific consensus attributes modern warming primarily to fossil fuel emissions.',
    },
    {
      number: 50,
      part: 'B-1',
      text: 'The diagram shows the water cycle. Identify the process by which water moves from the ocean to the atmosphere as water vapor, driven primarily by solar energy.',
      choices: [
        'condensation',
        'precipitation',
        'evaporation',
        'infiltration',
      ],
      topic: 'Water Cycle',
      correct: 2,
      explanation: 'Evaporation is the process by which liquid water at the ocean surface absorbs solar energy and changes into water vapor that rises into the atmosphere, initiating the water cycle.',
      diveDeep: 'Evaporation is the primary pathway for water entering the atmosphere from ocean surfaces, driven by solar energy input. Water molecules at the surface gain enough kinetic energy to overcome intermolecular attractions and escape into the gas phase. The energy absorbed in evaporation (latent heat = 2260 J/g) is released later when condensation forms clouds. This energy transfer is what powers tropical storms and hurricanes. The water cycle processes: evaporation → condensation (clouds) → precipitation → infiltration/runoff → returns to ocean. Students should be able to trace water through all stages of the cycle, identify the driving energy source (solar radiation for evaporation, gravity for precipitation and runoff), and explain each process.',
    },
  ],
}
