// Earth Science Regents — June 2018
export default {
  id: 'ea-jun-2018',
  subject: 'earth-science',
  year: 2018,
  session: 'June',
  totalMinutes: 180,
  questions: [
    {
      number: 1, part: 'A',
      text: 'The photographs below show two types of solar eclipses. Letters A and B represent two celestial objects. During a total solar eclipse, one object completely blocks the other. Which two celestial objects are represented by letters A and B?',
      choices: ['A-Moon; B-Sun', 'A-Sun; B-Moon', 'A-Moon; B-Earth', 'A-Sun; B-Earth'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'In a solar eclipse, the Moon (A) passes between Earth and the Sun (B), blocking sunlight. The Moon is the smaller object in front, and the Sun is behind it.',
      diveDeep: 'A solar eclipse occurs at new moon when the Moon\'s shadow falls on Earth. In a total solar eclipse, the umbra (darkest shadow) creates a path of totality where the Moon completely covers the Sun\'s disk. The Moon and Sun appear nearly the same size in our sky because, though the Sun is ~400 times larger, it is ~400 times farther away. A partial solar eclipse occurs when only the penumbra sweeps across an area. Common mistake: confusing solar and lunar eclipses — in a lunar eclipse it is Earth\'s shadow on the Moon.', image: '/images/exams/es-june-2018/q1.png' },
    {
      number: 2, part: 'A',
      text: 'Compared to the terrestrial planets, the Jovian planets',
      choices: ['are less massive', 'are more dense', 'have greater orbital velocities', 'have shorter periods of rotation'],
      topic: 'Astronomy',
      correct: 3,
      explanation: 'Jovian planets (Jupiter, Saturn, Uranus, Neptune) rotate faster on their axes than terrestrial planets, giving them shorter periods of rotation despite their great size.',
      diveDeep: 'Jovian planets are larger, less dense (mostly gas/ice), more massive, and farther from the Sun than terrestrial planets. They rotate very quickly — Jupiter\'s day is only about 10 hours. Their orbital velocities are actually slower than terrestrial planets because they are farther from the Sun (Kepler\'s third law). A common mistake is to confuse rotation period (a day) with revolution period (a year). Jovian planets have longer years but shorter days.',
    },
    {
      number: 3, part: 'A',
      text: 'Which event occurred more than 10 billion years ago?',
      choices: ['Big Bang', 'origin of life on Earth', 'Pangaea begins to break up', 'origin of Earth and its Moon'],
      topic: 'General',
      correct: 0,
      explanation: 'The Big Bang occurred approximately 13.8 billion years ago, which is more than 10 billion years ago. Earth formed about 4.6 billion years ago.',
      diveDeep: 'The Big Bang is the leading cosmological model for the universe\'s origin, occurring ~13.8 billion years ago. Earth and the Moon formed ~4.6 billion years ago from a solar nebula. The earliest life on Earth appeared ~3.5 billion years ago (stromatolites). Pangaea began breaking up ~200 million years ago. Students sometimes confuse the age of the universe (~14 billion years) with the age of Earth (~4.6 billion years). The ESRT lists key geologic events and their ages.',
    },
    {
      number: 4, part: 'A',
      text: 'In 1851, French physicist Leon Foucault used a swinging pendulum to demonstrate that Earth',
      choices: ['is rotating', 'is revolving', 'has a curved surface', 'has a gravitational pull'],
      topic: 'General',
      correct: 0,
      explanation: 'A Foucault pendulum\'s plane of swing appears to rotate over time because Earth rotates beneath it, providing direct evidence of Earth\'s rotation.',
      diveDeep: 'Foucault suspended a heavy pendulum from the ceiling of the Pantheon in Paris. As it swung, the pendulum\'s plane of oscillation appeared to rotate clockwise (in the Northern Hemisphere). In reality, the pendulum maintains its plane in space while Earth rotates underneath it. The rate of apparent rotation depends on latitude — fastest at the poles (one full turn per day) and zero at the equator. The Coriolis effect is related: Earth\'s rotation also deflects winds and ocean currents.',
    },
    {
      number: 5, part: 'A',
      text: 'Approximately how many degrees does Earth travel in its orbit in one month?',
      choices: ['1°', '30°', '15°', '360°'],
      topic: 'Astronomy',
      correct: 1,
      explanation: 'Earth travels 360° in its orbit in one year (12 months), so it travels approximately 360°/12 = 30° per month.',
      diveDeep: 'Earth\'s orbital speed averages about 1° per day (360° ÷ 365 days ≈ 0.986°/day). Over one month (~30 days), that sums to ~30°. Do not confuse this with Earth\'s rotation rate of 15° per hour (360° ÷ 24 hours). The 15°/hour rotation rate is the basis for time zones. The ~1°/day orbital rate means the Sun appears to shift about 1° eastward against the star background each day. This distinction between rotation and revolution rates is frequently tested.',
    },
    {
      number: 6, part: 'A',
      text: 'What is the relative humidity when the dry-bulb temperature is 16°C and the wet-bulb temperature is 10°C?',
      choices: ['6%', '33%', '14%', '45%'],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'With a dry-bulb of 16°C and wet-bulb of 10°C, the difference is 6°C. Using the ESRT Relative Humidity chart, this gives approximately 45% relative humidity.',
      diveDeep: 'Relative humidity is found using the ESRT\'s psychrometric tables. First calculate the wet-bulb depression: dry-bulb minus wet-bulb = 16 − 10 = 6°C. Then find the row for the dry-bulb temperature (16°C) and the column for the depression (6°C). The intersection gives ~45% RH. A common mistake is subtracting in the wrong direction or reading the wrong table. The dewpoint table works similarly but gives the dewpoint temperature instead of percent humidity.',
    },
    {
      number: 7, part: 'A',
      text: 'Boarding up windows would be one emergency action most likely taken to prepare for which natural disaster?',
      choices: ['earthquake', 'flood', 'hurricane', 'tsunami'],
      topic: 'General',
      correct: 2,
      explanation: 'Boarding up windows is a standard preparation for hurricanes to protect against high winds and flying debris, which are the primary hazards of this storm type.',
      diveDeep: 'Hurricanes (also called typhoons or cyclones) produce very high sustained winds, heavy rainfall, and storm surge. Boarding up windows prevents shattering from debris and pressure changes. For earthquakes, the recommended action is "drop, cover, hold on." For floods, moving to higher ground is advised. For tsunamis, evacuation to higher ground is critical. Each natural disaster requires specific preparation strategies, which are commonly tested on the Regents exam.',
    },
    {
      number: 8, part: 'A',
      text: 'Which diagram best represents the general position and direction of flow of the polar front jet stream in the Northern Hemisphere during the winter months?',
      choices: ['Jet stream positioned far north, flowing west to east', 'Jet stream positioned around 40-50°N, flowing west to east with large undulations', 'Jet stream positioned near the equator', 'Jet stream flowing east to west at mid-latitudes'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'During Northern Hemisphere winter, the polar front jet stream shifts southward to around 40–50°N and flows generally west to east with large meanders (undulations).',
      diveDeep: 'The polar front jet stream is a fast-moving band of air at the tropopause (~10 km altitude) near the polar front. It flows from west to east due to Earth\'s rotation. In winter, it dips farther south and meanders more, bringing cold Arctic air into mid-latitudes and steering storm systems. In summer it retreats northward. The subtropical jet stream is found near 30°N/S and is more consistent year-round. Jet streams are critical for weather forecasting because they guide low-pressure systems.', image: '/images/exams/es-june-2018/q8.png' },
    {
      number: 9, part: 'A',
      text: 'The diagram below represents four positions of the Moon labeled A through D as it orbits Earth. Which diagram best represents the sequence of Moon phases as seen by an observer in New York State when the Moon travels from position A to position D in its orbit around Earth?',
      choices: ['New, Waxing Crescent, First Quarter, Waxing Gibbous', 'Full, Waning Gibbous, Third Quarter, Waning Crescent', 'Waxing Crescent, First Quarter, Waxing Gibbous, Full', 'Third Quarter, Waning Crescent, New, Waxing Crescent'],
      topic: 'Astronomy',
      correct: 3,
      image: '/images/exams/es-june-2018/q9.png',
      explanation: 'The sequence of Moon phases depends on the Moon\'s orbital position relative to Earth and the Sun. Moving from position A through D produces the sequence shown in choice 4.',
      diveDeep: 'Moon phases result from the changing angle between the Moon, Earth, and Sun. The complete cycle (synodic month) takes ~29.5 days. New Moon occurs when the Moon is between Earth and the Sun. Full Moon occurs when Earth is between the Moon and Sun. Waxing phases occur as the illuminated portion grows; waning phases as it shrinks. The Moon rises about 50 minutes later each day. A common mistake is thinking phases are caused by Earth\'s shadow — that is only during a lunar eclipse.',
    },
    {
      number: 10, part: 'A',
      text: 'The diagrams below represent spectral lines of hydrogen gas in a laboratory and from a distant star. Compared to the laboratory spectral lines, the lines from the distant star have shifted toward the',
      choices: ['red end of the spectrum, indicating the star\'s movement toward Earth', 'red end of the spectrum, indicating the star\'s movement away from Earth', 'blue end of the spectrum, indicating the star\'s movement toward Earth', 'blue end of the spectrum, indicating the star\'s movement away from Earth'],
      topic: 'Astronomy',
      correct: 1,
      image: '/images/exams/es-june-2018/q10.png',
      explanation: 'A redshift (spectral lines shifted toward longer wavelengths) indicates the light source is moving away from the observer, due to the Doppler effect.',
      diveDeep: 'The Doppler effect causes the wavelength of waves to appear longer (redshifted) when the source moves away, and shorter (blueshifted) when it moves toward the observer. Nearly all distant galaxies show redshift, which is the primary evidence for the expanding universe. The degree of redshift indicates the recession speed — more distant galaxies recede faster (Hubble\'s Law). A blueshift would indicate approach. The Big Bang theory is supported by this universal redshift of distant galaxies.',
    },
    {
      number: 11, part: 'A',
      text: 'How many degrees is Earth\'s rotational axis tilted with respect to a line drawn perpendicular to the plane of Earth\'s orbit?',
      choices: ['15°', '23.5°', '66.5°', '90°'],
      topic: 'Astronomy',
      correct: 1,
      image: '/images/exams/es-june-2018/q11.png',
      explanation: 'Earth\'s axis is tilted 23.5° from the perpendicular to its orbital plane. This tilt is the cause of Earth\'s seasons.',
      diveDeep: 'Earth\'s axial tilt of 23.5° is sometimes called the obliquity of the ecliptic. This tilt means that as Earth orbits the Sun, different hemispheres receive more direct sunlight at different times of year, producing seasons. At the summer solstice in the Northern Hemisphere, the axis points toward the Sun; at the winter solstice, it points away. The complementary angle (90° − 23.5° = 66.5°) is the angle between the axis and the orbital plane. A common mistake is confusing 23.5° with 66.5° or thinking seasons are caused by Earth\'s varying distance from the Sun.',
    },
    {
      number: 12, part: 'A',
      text: 'Which statement best explains why Scorpius is visible in the New York State nighttime sky in July but not in January, while Orion is visible in January but not in July?',
      choices: ['Earth spins on its axis at a constant rate during a 24-hour period.', 'Earth spins on its axis at a variable rate during the year.', 'The nighttime side of Earth is facing different parts of our galaxy as Earth orbits the Sun.', 'The nighttime side of Earth is facing different parts of our galaxy as the stars orbit Earth.'],
      topic: 'Astronomy',
      correct: 2,
      explanation: 'As Earth orbits the Sun, the nighttime side faces different directions in space, so different constellations become visible at different times of year.',
      diveDeep: 'Earth\'s orbit around the Sun causes the nighttime side to face different regions of the galaxy throughout the year. In January, the nighttime side faces toward Orion; six months later it faces away from Orion and toward Scorpius. Stars do not orbit Earth — they are essentially fixed in space relative to our observation timescale. Earth\'s daily rotation causes stars to rise in the east and set in the west each night, while Earth\'s annual revolution determines which constellations are visible each season.', image: '/images/exams/es-june-2018/q12.png' },
    {
      number: 13, part: 'A',
      text: 'Which table correctly shows the interior temperature, melting point, and state of matter of the material located 4000 kilometers below Earth\'s surface?',
      choices: ['Temperature 5700°C, Melting Point 5400°C, State: solid', 'Temperature 5400°C, Melting Point 5700°C, State: solid', 'Temperature 5700°C, Melting Point 5400°C, State: liquid', 'Temperature 5400°C, Melting Point 5700°C, State: liquid'],
      topic: 'General',
      correct: 0,
      image: '/images/exams/es-june-2018/q13.png',
      explanation: 'At 4000 km depth (inner core), the temperature (~5700°C) exceeds the melting point (~5400°C), yet it is solid because of the immense pressure, which raises the melting point.',
      diveDeep: 'Earth\'s inner core is solid iron-nickel despite temperatures exceeding the normal melting point because extreme pressure (~360 GPa) raises the melting point above the actual temperature. The outer core at ~2900–5150 km is liquid (temperature exceeds pressure-adjusted melting point). This is determined from seismic wave behavior — S-waves cannot travel through the liquid outer core but do travel through the solid inner core. A key concept: high pressure increases melting point, so solid rock can exist at temperatures that would normally melt it at surface pressure.',
    },
    {
      number: 14, part: 'A',
      text: 'Which gas is a greenhouse gas that has increased in Earth\'s atmosphere partly as a result of deforestation over the last 100 years?',
      choices: ['ozone', 'nitrogen', 'oxygen', 'carbon dioxide'],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'Carbon dioxide (CO₂) is a major greenhouse gas that has increased due to deforestation (trees absorb CO₂) and burning of fossil fuels.',
      diveDeep: 'Greenhouse gases trap infrared radiation reradiated from Earth\'s surface, warming the atmosphere. CO₂ is the primary human-influenced greenhouse gas. Deforestation removes trees that would otherwise absorb CO₂ through photosynthesis, and burning forests adds CO₂ directly. Other greenhouse gases include methane (CH₄), water vapor (H₂O), and nitrous oxide. Nitrogen and oxygen together make up 99% of the atmosphere but are NOT greenhouse gases because their molecular structure does not absorb infrared radiation. Ozone in the stratosphere protects against UV, not greenhouse warming.',
    },
    {
      number: 15, part: 'A',
      text: 'Which ocean current brings warm water to the southeastern tip of Africa?',
      choices: ['Brazil Current', 'Guinea Current', 'Agulhas Current', 'Benguela Current'],
      topic: 'Climate',
      correct: 2,
      explanation: 'The Agulhas Current is a warm western boundary current that flows southward along the east coast of Africa, bringing warm tropical water to the southeastern tip.',
      diveDeep: 'Ocean currents are driven by wind patterns and are deflected by the Coriolis effect. Warm currents flow from the tropics toward the poles, while cold currents flow from poles toward the equator. The Agulhas Current flows along the east coast of Africa (warm). The Benguela Current flows northward along the west coast of southern Africa (cold). Using the ESRT\'s ocean current map is essential for these questions — warm currents are shown with solid arrows and cold with dashed arrows. Currents strongly influence regional climates.',
    },
    {
      number: 16, part: 'A',
      text: 'Which pie graph is shaded to best represent the approximate percentage of time that humans have existed during Earth\'s entire history?',
      choices: ['A very thin sliver (less than 1%) is shaded', 'About 25% is shaded', 'About 50% is shaded', 'About 10% is shaded'],
      topic: 'General',
      correct: 0,
      image: '/images/exams/es-june-2018/q16.png',
      explanation: 'Humans (Homo sapiens) have existed for only about 200,000 years out of Earth\'s 4.6 billion year history — less than 0.01% of Earth\'s history — so only the tiniest sliver should be shaded.',
      diveDeep: 'Calculating the fraction: 200,000 years ÷ 4,600,000,000 years ≈ 0.0000043, or about 0.00043% of Earth\'s history. On a full 360° pie chart, this represents less than 0.002° of arc — invisible to the naked eye. This concept reinforces the vast scale of geologic time. Even the entire Cenozoic Era (last 66 million years) represents only about 1.4% of Earth\'s history. The ESRT geologic time scale helps visualize these proportions. A common mistake is greatly overestimating how long humans have existed.',
    },
    {
      number: 17, part: 'A',
      text: 'Volcanic ash can be used as a time marker to correlate rock layers because the ash',
      choices: ['is deposited rapidly over a large area', 'represents a buried erosional surface', 'forms intrusive igneous rock', 'cuts across rock layers'],
      topic: 'Geology',
      correct: 0,
      explanation: 'A volcanic ash layer forms nearly simultaneously over a vast area in a geologically instantaneous event, making it an ideal time marker (key bed) for correlation.',
      diveDeep: 'Correlation of rock layers between distant outcrops relies on identifying the same layer in multiple locations. Volcanic ash (tephra) layers are ideal time markers because: (1) they are deposited in essentially a single geologic instant, (2) they spread over enormous areas downwind, and (3) each eruption has a unique chemical composition. Index fossils serve a similar purpose but require organic material. Unconformities (buried erosional surfaces) represent time gaps, not time markers. Intrusive rocks cut across existing layers but cannot be easily correlated over wide areas.',
    },
    {
      number: 18, part: 'A',
      text: 'The diagram below represents a mountain range. Points A and B represent locations on Earth\'s surface, with A on the windward side and B on the leeward side. Compared to the climate of location A, the climate of location B is most likely',
      choices: ['cooler and wetter', 'warmer and wetter', 'cooler and drier', 'warmer and drier'],
      topic: 'Meteorology',
      correct: 3,
      image: '/images/exams/es-june-2018/q18.png',
      explanation: 'Location B is in the rain shadow (leeward side). Air descends and warms adiabatically after losing moisture on the windward side, making the leeward side warmer and drier.',
      diveDeep: 'The orographic effect (mountain effect) causes moist air to rise on the windward side, cool adiabatically, and drop precipitation. By the time air reaches the leeward side (rain shadow), it has lost moisture. As it descends, it compresses and warms at the dry adiabatic lapse rate, making it warmer AND drier than the windward side. Classic examples include the Sierra Nevada (wet west, dry Great Basin east) and the Cascade Range. The leeward side warming results in temperatures that can be higher than at equivalent elevation on the windward side.',
    },
    {
      number: 19, part: 'A',
      text: 'In a conglomerate, pebbles are cemented together with calcite. Compared to the ages of the calcite cement and the conglomerate, the relative age of the pebbles is',
      choices: ['younger than both the calcite cement and the conglomerate', 'younger than the calcite cement, but the same age as the conglomerate', 'older than both the calcite cement and the conglomerate', 'older than the calcite cement, but the same age as the conglomerate'],
      topic: 'Geologic Time',
      correct: 2,
      explanation: 'The pebbles must have existed before they could be incorporated into the conglomerate and cemented by calcite, so pebbles are older than both the cement and the rock.',
      diveDeep: 'The principle of inclusions states that rock fragments (inclusions) within a rock are older than the rock containing them. The pebbles were eroded from pre-existing rock, transported, and then deposited. After deposition, compaction and cementation (by calcite) formed the conglomerate. Therefore the sequence from oldest to youngest is: pebble source rock → pebbles → conglomerate formation → calcite cement fills pores. This is similar to how xenoliths (rock fragments inside igneous rock) must predate the magma that engulfed them.', image: '/images/exams/es-june-2018/q19.png' },
    {
      number: 20, part: 'A',
      text: 'The cross section below represents parts of Earth\'s water cycle. Letters A, B, C, and D represent processes. Which table correctly matches each letter with the process it represents?',
      choices: ['A=Condensation, B=Transpiration, C=Precipitation, D=Evaporation', 'A=Evaporation, B=Precipitation, C=Transpiration, D=Condensation', 'A=Precipitation, B=Transpiration, C=Evaporation, D=Condensation', 'A=Evaporation, B=Transpiration, C=Precipitation, D=Condensation'],
      topic: 'Meteorology',
      correct: 3,
      image: '/images/exams/es-june-2018/q20.png',
      explanation: 'In the water cycle diagram: A is evaporation from the water surface, B is transpiration from plants, C is precipitation from clouds, and D is condensation forming clouds.',
      diveDeep: 'The water cycle processes: evaporation converts liquid water to vapor at the surface; transpiration is water vapor released by plants; together these are evapotranspiration. Condensation occurs when water vapor cools and forms cloud droplets. Precipitation falls as rain, snow, sleet, or hail. Infiltration is water soaking into the ground; runoff flows along the surface. The water table marks the upper boundary of saturated ground. Students often confuse transpiration (plants releasing vapor) with evaporation (direct liquid-to-vapor conversion).',
    },
    {
      number: 21, part: 'A',
      text: 'Which table best shows the relationship between latitude and general climate conditions on Earth?',
      choices: ['90°N=Arid, 60°N=Humid, 30°N=Arid, 0°=Humid, 30°S=Arid, 60°S=Humid, 90°S=Arid', '90°N=Arid, 60°N=Humid, 30°N=Arid, 0°=Humid, 30°S=Humid, 60°S=Arid, 90°S=Humid', '90°N=Humid, 60°N=Arid, 30°N=Humid, 0°=Arid, 30°S=Humid, 60°S=Arid, 90°S=Humid', '90°N=Arid, 60°N=Arid, 30°N=Humid, 0°=Humid, 30°S=Humid, 60°S=Arid, 90°S=Arid'],
      topic: 'Climate',
      correct: 0,
      image: '/images/exams/es-june-2018/q21.png',
      explanation: 'At 0° and 60° N/S, rising air produces humid climates. At 30° N/S and 90° (poles), descending air produces arid conditions.',
      diveDeep: 'Global air circulation cells determine precipitation patterns. At the equator (0°), intense solar heating creates rising air, cooling and dropping heavy rainfall (tropical rainforest). At ~30°N/S, air descends from the Hadley Cell, compresses, and warms — creating the world\'s major deserts (Sahara, Atacama). At ~60°N/S, the polar and Ferrel cells create rising air and humid climates (temperate rainforests). At the poles (~90°), cold descending air creates polar deserts. This pattern explains why New York at 40–45°N is in a humid zone between the subtropical and polar regions.',
    },
    {
      number: 22, part: 'A',
      text: 'Which table shows the most likely process and agent of erosion responsible for producing different-sized, rounded sediment?',
      choices: ['sandblasting; running water', 'abrasion; running water', 'landslide; mass movement', 'deposition; wind'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'Rounded sediment of various sizes is produced by abrasion in running water — particles collide and grind against each other, rounding their edges.',
      diveDeep: 'Abrasion is the mechanical wearing down of sediment particles as they collide during transport. Running water is the most effective agent for producing rounded, smooth particles. The more a particle is transported, the rounder and smaller it becomes. Size sorting also occurs — slower water deposits larger particles first. Glaciers produce angular, poorly sorted sediment because ice does not allow particles to roll and round. Wind produces very well-rounded, frosted sand grains. Wave action on beaches also rounds cobbles and pebbles. The degree of rounding indicates transport distance.', image: '/images/exams/es-june-2018/q22.png' },
    {
      number: 23, part: 'A',
      text: 'The photograph below shows an outcrop with two basaltic intrusions labeled A and B, in a rock unit labeled C. What is the relative age of these three rock units from oldest to youngest?',
      choices: ['B → A → C', 'C → A → B', 'B → C → A', 'C → B → A'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Rock unit C formed first (oldest). Intrusion B cut into C, then intrusion A cut through both B and C, making A the youngest.',
      diveDeep: 'The principle of cross-cutting relationships states that any rock or feature that cuts across another must be younger than what it cuts. Rock unit C is the host rock (oldest). Intrusion B cuts through C (B is younger than C). Intrusion A cuts through both C and B (A is the youngest). This principle applies to faults, dikes, veins, and igneous intrusions. The principle of superposition (in undisturbed layers, lower layers are older) also applies to sedimentary sequences. Combining these principles allows relative dating of complex rock sequences.', image: '/images/exams/es-june-2018/q23.png' },
    {
      number: 24, part: 'A',
      text: 'The world map shows Earth\'s major tectonic plate boundaries. Letters A through D represent four surface locations. Which location is on a major rift valley?',
      choices: ['A', 'C', 'B', 'D'],
      topic: 'Geology',
      correct: 0,
      image: '/images/exams/es-june-2018/q24.png',
      explanation: 'Location A is on a divergent plate boundary where plates pull apart, forming a rift valley. The East African Rift and Mid-Atlantic Ridge are examples.',
      diveDeep: 'Rift valleys form at divergent plate boundaries where tectonic plates pull apart. The crust thins and sinks, creating a long valley flanked by parallel faults (a graben). The East African Rift Valley is an active continental rift. Mid-ocean ridges are submarine rift valleys. Convergent boundaries form trenches and mountains; transform boundaries form faults like the San Andreas. Using the ESRT tectonic plate map, students should identify plate boundaries and know what features form at each type. Volcanic activity is common at rift zones.',
    },
    {
      number: 25, part: 'A',
      text: 'The first P-wave of an earthquake took 11 minutes to travel to a seismic station from the epicenter. What is the seismic station\'s distance to the epicenter, and how long did it take for the first S-wave to travel that distance?',
      choices: ['5500 km; about 19 min', '7000 km; about 19 min', '7000 km; about 16 min', '5500 km; about 16 min'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Using the ESRT travel time chart, a P-wave travel time of 11 minutes corresponds to ~7000 km distance. The S-wave for 7000 km takes about 19 minutes.',
      diveDeep: 'The ESRT provides travel time curves for P-waves and S-waves. P-waves travel faster (~6–8 km/s) than S-waves (~3–5 km/s). At 7000 km, P-waves take ~11 minutes and S-waves ~19 minutes — a difference of ~8 minutes. The greater the P-S time difference, the farther the station is from the epicenter. To locate an epicenter, at least three seismic stations are needed (triangulation). S-waves cannot travel through liquids, which is how we know Earth\'s outer core is liquid. Practice using the ESRT travel time chart for these calculations.',
    },
    {
      number: 26, part: 'A',
      text: 'Which diagram best represents the pattern of seismic waves (P-waves and S-waves) traveling through Earth\'s interior from an earthquake focus?',
      choices: ['P-waves curve through entire Earth; S-waves blocked by outer core', 'P-waves and S-waves both travel in straight lines', 'Both P-waves and S-waves blocked by the mantle', 'S-waves curve; P-waves travel straight'],
      topic: 'Geology',
      correct: 0,
      explanation: 'P-waves curve through the entire Earth due to changes in wave speed with depth but are refracted by the outer core. S-waves cannot pass through the liquid outer core, creating a shadow zone.',
      diveDeep: 'Seismic waves refract (bend) as they travel through Earth because wave speed changes with depth due to changes in density and composition. P-waves (compressional) travel through solids and liquids. S-waves (shear) travel only through solids. The liquid outer core creates a P-wave shadow zone (103°–143° from epicenter) and completely blocks S-waves beyond 103°. This behavior revealed Earth\'s layered interior: crust, mantle, liquid outer core, solid inner core. The boundary between the mantle and core is called the Gutenberg discontinuity.',
    },
    {
      number: 27, part: 'A',
      text: 'Stalactites and stalagmites form in limestone caves primarily through which process?',
      choices: ['mechanical weathering by ice', 'chemical weathering and deposition from groundwater', 'erosion by underground rivers', 'metamorphism of calcite minerals'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Stalactites and stalagmites (speleothems) form when groundwater containing dissolved calcium carbonate drips through cave ceilings and deposits calcite as the water evaporates or loses CO₂.',
      diveDeep: 'Limestone (CaCO₃) is dissolved by slightly acidic groundwater (carbonic acid from CO₂ dissolved in rainwater). This chemical weathering creates caves. As groundwater seeps into the cave, it loses CO₂ to the cave air, causing calcite to precipitate. Stalactites hang from the ceiling; stalagmites grow from the floor; when they meet they form columns. This is an example of chemical deposition — the reverse of chemical weathering. Speleothems can be radioactively dated and provide records of past climate. The process illustrates the carbon cycle in action.',
    },
    {
      number: 28, part: 'A',
      text: 'What is the approximate latitude of an observer in New York State who measures the altitude of Polaris at 44°?',
      choices: ['44°N', '46°N', '23.5°N', '90°N'],
      topic: 'Astronomy',
      correct: 0,
      explanation: 'The altitude of Polaris above the horizon equals the observer\'s latitude. An altitude of 44° means the observer is at 44°N latitude.',
      diveDeep: 'Polaris (the North Star) is located nearly directly above Earth\'s North Pole — aligned with Earth\'s rotational axis. Because of this, its angle above the horizon equals the observer\'s latitude in the Northern Hemisphere. At the North Pole (90°N), Polaris is directly overhead (90° altitude). At the equator (0°), Polaris is on the horizon (0° altitude). This relationship has been used for navigation for centuries. In the Southern Hemisphere, there is no equivalent "South Star" bright enough to use. The altitude of Polaris changes as you travel north or south.',
    },
    {
      number: 29, part: 'A',
      text: 'Which event provides the best evidence that Earth\'s continents have moved over geologic time?',
      choices: ['identical fossils found on now-separated continents', 'earthquakes occurring at plate boundaries', 'volcanoes forming near subduction zones', 'sedimentary rocks containing marine fossils'],
      topic: 'Geology',
      correct: 0,
      explanation: 'Finding identical fossils of land-dwelling organisms on now-separated continents (like Mesosaurus in both South America and Africa) provides direct evidence that these landmasses were once connected.',
      diveDeep: 'Evidence for continental drift (now plate tectonics) includes: (1) matching fossils on separated continents — Mesosaurus, Glossopteris flora; (2) matching rock types and mountain chains (Appalachians match mountains in Scotland/Norway); (3) matching coastlines that fit together like a puzzle; (4) paleomagnetic evidence of seafloor spreading; (5) current GPS measurements of plate movement. Wegener proposed continental drift in 1912 but lacked a mechanism. The seafloor spreading mechanism was identified in the 1960s, confirming plate tectonics. The Mid-Atlantic Ridge is the driving force separating North America and Europe.',
    },
    {
      number: 30, part: 'A',
      text: 'Which sedimentary rock is formed by the compaction and cementation of clay-sized particles?',
      choices: ['conglomerate', 'sandstone', 'shale', 'limestone'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Shale is formed by the compaction and cementation of clay and silt-sized particles (less than 0.0004 cm). It is the most common sedimentary rock.',
      diveDeep: 'Clastic sedimentary rocks are classified by grain size using the ESRT: conglomerate (rounded pebbles >0.2 cm), sandstone (sand 0.006–0.2 cm), siltstone (silt 0.0004–0.006 cm), and shale (clay <0.0004 cm). Shale forms in quiet, low-energy environments like lake bottoms and deep ocean floors. Its fine particles allow it to split into thin layers (fissile texture). Limestone can be chemical or bioclastic. Coal is bioclastic from compressed plant material. Knowing the ESRT rock classification chart is essential for identifying sedimentary rocks by grain size.', image: '/images/exams/es-june-2018/q30.png' },
    {
      number: 31, part: 'A',
      text: 'Which type of igneous rock has a coarse-grained texture and is composed primarily of plagioclase feldspar and pyroxene?',
      choices: ['granite', 'rhyolite', 'gabbro', 'basalt'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Gabbro is a coarse-grained (intrusive) igneous rock composed mainly of plagioclase feldspar and pyroxene, equivalent in composition to basalt but formed by slow cooling underground.',
      diveDeep: 'Igneous rock classification uses two criteria: texture (grain size) and mineral composition. Coarse-grained (phaneritic) texture indicates slow cooling deep underground (intrusive/plutonic). Fine-grained (aphanitic) texture indicates rapid cooling at the surface (extrusive/volcanic). Granite = coarse, felsic (quartz + feldspar). Rhyolite = fine-grained version of granite. Gabbro = coarse, mafic (pyroxene + plagioclase). Basalt = fine-grained version of gabbro. Using the ESRT Scheme for Igneous Rock Identification, match both composition and texture to identify the correct rock name.',
    },
    {
      number: 32, part: 'A',
      text: 'Which mineral has a hardness of 2.5, is silver in color, has a metallic luster, and is commonly used in batteries?',
      choices: ['graphite', 'galena', 'pyrite', 'magnetite'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Galena is a lead sulfide mineral (PbS) with a silver-gray color, metallic luster, hardness of 2.5, and perfect cubic cleavage. Lead from galena is used in batteries.',
      diveDeep: 'Mineral identification uses physical properties: hardness (Mohs scale 1–10), luster (metallic vs. non-metallic), color, streak, cleavage/fracture, and special properties. Galena (PbS) is distinctive for its very high density (7.6 g/cm³), silver-gray color, metallic luster, and perfect cubic cleavage in three directions. Graphite is gray but has a greasy feel and is soft (H=1–2). Pyrite ("fool\'s gold") is brassy yellow with H=6–6.5. Magnetite is black and magnetic. The ESRT provides mineral properties for identification. Always use multiple properties, not just color.', image: '/images/exams/es-june-2018/q32.png' },
    {
      number: 33, part: 'A',
      text: 'Which type of map projection shows accurate shapes of continents but distorts their sizes, especially near the poles?',
      choices: ['conic projection', 'Mercator projection', 'equal-area projection', 'polar projection'],
      topic: 'General',
      correct: 1,
      explanation: 'The Mercator projection preserves the shapes (conformal) of landmasses but distorts areas — regions near the poles appear much larger than they actually are.',
      diveDeep: 'All flat maps distort Earth\'s spherical surface in some way — you cannot perfectly represent a sphere on a flat surface. The Mercator projection preserves angles (conformal), making it useful for navigation but causing extreme size distortion near the poles (Greenland appears as large as Africa, when Africa is ~14 times larger). Equal-area projections preserve relative sizes but distort shapes. Conic projections are used for mid-latitude regions. Polar projections are used to show the poles accurately. Understanding map projections is important for interpreting global maps of climate, tectonic plates, and ocean currents.', image: '/images/exams/es-june-2018/q33.png' },
    {
      number: 34, part: 'A',
      text: 'Which two properties of a stream most directly control its ability to erode and transport sediment?',
      choices: ['temperature and color', 'velocity and discharge', 'pH and dissolved oxygen', 'width and depth only'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Stream velocity and discharge directly determine erosion and transport capacity — faster, larger-volume streams can move larger and more sediment.',
      diveDeep: 'Stream competence (maximum particle size a stream can carry) is proportional to the square of velocity — doubling velocity increases competence by four times. Stream capacity (total load a stream can carry) increases with both velocity and discharge. Discharge = width × depth × velocity. Heavy rainfall increases discharge and velocity, allowing rivers to carry more and larger sediment. When velocity decreases (e.g., where a river enters a lake), sediment is deposited in order of decreasing size. This principle explains why deltas form at river mouths and alluvial fans form at canyon exits.', image: '/images/exams/es-june-2018/q34.png' },
    {
      number: 35, part: 'A',
      text: 'Which New York State landscape region has the highest elevation and is composed primarily of metamorphic and igneous rocks?',
      choices: ['Hudson-Mohawk Lowlands', 'Catskill Mountains', 'Adirondack Mountains', 'Tug Hill Plateau'],
      topic: 'Geology',
      correct: 2,
      explanation: 'The Adirondack Mountains have the highest elevations in New York State and are composed primarily of Precambrian metamorphic and igneous rocks (anorthosite, gneiss).',
      diveDeep: 'The Adirondacks are a dome-shaped upwarp of ancient Precambrian basement rocks (~1 billion years old) that were exhumed by erosion. Mount Marcy (1629 m) is the highest peak in New York State. The bedrock is mainly anorthositic gneiss and metasedimentary rocks from the Grenville orogeny. The Catskills are a plateau of Devonian sedimentary rocks (shale, sandstone). The Hudson-Mohawk Lowlands are underlain by older sedimentary rocks. Using the ESRT Generalized Bedrock Geology of New York State map is essential for identifying landscape regions and their rock types.', image: '/images/exams/es-june-2018/q35.png' },
    // Part B-1
    {
      number: 36, part: 'B-1',
      context: 'A cross section shows a hypothetical portion of Earth\'s crust with rock layers labeled A through G from bottom to top, an igneous intrusion, a fault, and an unconformity. The layers have been deformed by tectonic activity.',
      text: 'According to the principle of superposition, which rock layer in the cross section was most likely deposited first?',
      choices: ['Layer A (deepest layer)', 'Layer D (middle layer)', 'Layer G (top layer)', 'The igneous intrusion'],
      topic: 'Geology',
      correct: 0,
      explanation: 'The principle of superposition states that in undisturbed sequences, lower layers are older. Layer A at the bottom was deposited first.',
      diveDeep: 'The principle of superposition (Nicolas Steno, 1669) states that in any sequence of undisturbed sedimentary rocks, the oldest layer is at the bottom and the youngest at the top. This applies only when layers have NOT been overturned by tectonic forces. Combined with other principles — original horizontality (layers form horizontal), lateral continuity (layers extend until thinning), cross-cutting relationships (intrusions are younger than host rock), and inclusions (fragments are older than the rock containing them) — geologists can determine relative ages of rock sequences without using radiometric dating.', image: '/images/exams/es-june-2018/context_36_39.png' },
    {
      number: 37, part: 'B-1',
      context: 'A cross section shows a hypothetical portion of Earth\'s crust with rock layers labeled A through G from bottom to top, an igneous intrusion cutting through several layers, a fault, and an unconformity between layers C and D.',
      text: 'The unconformity between layers C and D represents',
      choices: ['a period of rapid deposition', 'a missing time gap in the rock record due to erosion', 'a zone of contact metamorphism', 'a volcanic ash layer'],
      topic: 'Geology',
      correct: 1,
      explanation: 'An unconformity is a surface of erosion or non-deposition that represents a gap in the geologic record — time passed but no sediment was deposited or existing rock was removed.',
      diveDeep: 'Three types of unconformities exist: (1) disconformity — parallel layers with a missing time interval between them (erosional surface); (2) angular unconformity — tilted layers below a horizontal erosional surface (Hutton\'s Unconformity at Siccar Point); (3) nonconformity — sedimentary layers resting on igneous or metamorphic basement rock. All unconformities represent time gaps in the record. The sequence of events creating an angular unconformity: deposition → tilting/folding → erosion → subsidence → new deposition. Recognizing unconformities is key to reading geologic cross sections.', image: '/images/exams/es-june-2018/context_36_39.png' },
    {
      number: 38, part: 'B-1',
      context: 'A cross section shows a hypothetical portion of Earth\'s crust with rock layers labeled A through G, an igneous intrusion, and a fault. The igneous intrusion cuts through layers A through D but not E through G.',
      text: 'Which rock unit is younger than the igneous intrusion?',
      choices: ['Layer A', 'Layer B', 'Layer E', 'Layer C'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Layer E is above the igneous intrusion and was not cut by it, indicating that Layer E was deposited after the intrusion occurred and is therefore younger.',
      diveDeep: 'Cross-cutting relationships: any feature that cuts across another is younger. If an igneous intrusion cuts through layers A–D but not E–G, then E–G were deposited after the intrusion. Additionally, layers adjacent to the intrusion may show contact metamorphism (baked zones), confirming the intrusion is older than the unaltered layers above it. The intrusion itself is younger than layers A–D (which it cuts through) but older than layers E–G (which formed after the intrusion). This type of multi-step reasoning is required for relative dating questions on the Regents.', image: '/images/exams/es-june-2018/context_36_39.png' },
    {
      number: 39, part: 'B-1',
      context: 'A weather map of the eastern United States shows isobars (lines of equal air pressure in millibars), a high pressure system (H) over the midwest, and a low pressure system (L) over the southeast. Wind arrows are shown at various stations.',
      text: 'In the Northern Hemisphere, surface winds around the low pressure system (L) circulate',
      choices: ['outward and clockwise', 'outward and counterclockwise', 'inward and clockwise', 'inward and counterclockwise'],
      topic: 'Meteorology',
      correct: 3,
      explanation: 'In the Northern Hemisphere, surface winds around a low pressure system spiral inward and counterclockwise due to the Coriolis effect and pressure gradient force.',
      diveDeep: 'Air flows from high to low pressure due to the pressure gradient force. The Coriolis effect (from Earth\'s rotation) deflects winds to the right in the Northern Hemisphere, causing counterclockwise rotation around lows (cyclones) and clockwise around highs (anticyclones). In the Southern Hemisphere, the directions are reversed. Tightly spaced isobars indicate steep pressure gradients and strong winds. Low pressure systems bring cloudy, stormy weather; high pressure systems bring clear, calm weather. This pattern is fundamental to weather map interpretation.', image: '/images/exams/es-june-2018/context_36_39.png' },
    {
      number: 40, part: 'B-1',
      context: 'A weather map of the eastern United States shows isobars, a high pressure system (H), and a low pressure system (L). Temperature data shows 58°F at one station and 43°F at an adjacent station with a cold front between them.',
      text: 'What type of weather front separates these two air masses and what weather is typically associated with it?',
      choices: ['Warm front — gradual temperature increase and light steady rain', 'Cold front — rapid temperature drop and thunderstorms', 'Stationary front — no change in weather', 'Occluded front — mild temperatures and light precipitation'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'A cold front represents cold air rapidly advancing and undercutting warmer air, causing it to rise quickly, leading to thunderstorms and a rapid temperature drop behind the front.',
      diveDeep: 'Cold fronts are steep (nearly vertical) boundaries where advancing cold air wedges under warm air, forcing rapid uplift. This produces cumulonimbus clouds, intense (but brief) precipitation, and thunderstorms. The passage of a cold front brings a rapid temperature drop, wind shift (usually to northwest in the Northeast US), and clearing skies. Warm fronts are more gradual — warm air rises over retreating cold air, producing stratiform clouds and steady widespread precipitation. Cold fronts move faster (25–30 mph) than warm fronts (15–20 mph). Occluded fronts form when a cold front catches up to a warm front.', image: '/images/exams/es-june-2018/context_40_42.png' },
    {
      number: 41, part: 'B-1',
      context: 'A data table shows the dry-bulb temperature (24°C), wet-bulb temperature (18°C), and station pressure (1012 mb) for a weather station. Using the ESRT psychrometric tables.',
      text: 'What is the dewpoint temperature at this weather station?',
      choices: ['6°C', '13°C', '18°C', '24°C'],
      topic: 'Meteorology',
      correct: 1,
      explanation: 'With a dry-bulb of 24°C and wet-bulb of 18°C (depression of 6°C), the ESRT Dewpoint Temperature table gives a dewpoint of approximately 13°C.',
      diveDeep: 'The dewpoint is the temperature at which air must be cooled (at constant pressure and water vapor content) for condensation to begin. Using the ESRT: find the dry-bulb temperature row (24°C), find the column for wet-bulb depression (24−18=6°C), and read the dewpoint (~13°C). When the air temperature equals the dewpoint, relative humidity = 100% and condensation begins. Clouds form when rising air cools to its dewpoint. Fog forms when surface air cools to its dewpoint. The closer the air temperature and dewpoint are together, the higher the relative humidity.', image: '/images/exams/es-june-2018/context_40_42.png' },
    {
      number: 42, part: 'B-1',
      context: 'A topographic map of a region in New York State shows elevation contour lines (contour interval 20 meters), a stream flowing through a valley, and several labeled points A, B, C, and D at different elevations.',
      text: 'In which direction does the stream flow on this topographic map?',
      choices: ['From lower elevation toward higher elevation', 'From higher elevation toward lower elevation', 'Perpendicular to the contour lines toward higher ground', 'Parallel to the contour lines'],
      topic: 'General',
      correct: 1,
      explanation: 'Streams always flow from higher elevation to lower elevation, following gravity. On a topographic map, streams flow in the direction of decreasing elevation.',
      diveDeep: 'On topographic maps, streams always flow from high to low elevation. Key rule: V-shaped contour lines pointing upstream (the V points uphill toward the stream\'s source). The gradient (slope) of a stream = change in elevation ÷ horizontal distance. Gradient formula is on the ESRT. Steep gradients (close contours) produce fast, erosive streams. Gentle gradients (widely spaced contours) produce slow, depositing streams. Divides (watersheds) are ridges between drainage basins. Water on each side of a divide flows in opposite directions. Topographic profiles can be drawn perpendicular to contour lines.', image: '/images/exams/es-june-2018/context_40_42.png' },
    {
      number: 43, part: 'B-1',
      context: 'A topographic map shows a hill with the summit at 380 meters elevation. Point A is at 200 meters elevation. The horizontal distance from Point A to the summit is 2 kilometers.',
      text: 'What is the gradient between Point A and the summit?',
      choices: ['90 m/km', '190 m/km', '380 m/km', '95 m/km'],
      topic: 'General',
      correct: 0,
      explanation: 'Gradient = change in elevation ÷ horizontal distance = (380 − 200) m ÷ 2 km = 180 m ÷ 2 km = 90 m/km.',
      diveDeep: 'The gradient formula from the ESRT: gradient = change in field value ÷ distance. For topography: gradient = (elevation at top − elevation at bottom) ÷ horizontal distance. Always divide elevation change by horizontal distance, not the slope distance along the hillside. Units are typically m/km or ft/mi. Steep gradients indicate rapid erosion potential. Rivers with steep gradients have high velocities and carry larger sediment. In New York State, the Adirondack streams have steeper gradients than the Hudson River near its mouth. Gradient calculations are a common math skill tested on the Regents exam.', image: '/images/exams/es-june-2018/context_43_44.png' },
    {
      number: 44, part: 'B-1',
      context: 'A cross section represents Earth\'s interior layers. From center outward: inner core, outer core, mantle (asthenosphere + lithosphere), and crust. Approximate depths and temperatures are labeled.',
      text: 'In which layer of Earth\'s interior do convection currents help drive the movement of tectonic plates?',
      choices: ['inner core', 'outer core', 'asthenosphere (upper mantle)', 'continental crust'],
      topic: 'Geology',
      correct: 2,
      explanation: 'Convection currents in the asthenosphere (partially molten upper mantle) transfer heat from Earth\'s interior to the surface and are thought to drive plate tectonic movement.',
      diveDeep: 'The asthenosphere is a partially molten, ductile layer in the upper mantle (~100–700 km depth). Its rock can flow very slowly over millions of years. Heat from radioactive decay and residual formation heat creates convection — hot material rises, spreads, cools, and sinks. This convection is thought to be the primary mechanism driving plate motion (ridge push + slab pull also contribute). The rigid lithosphere (crust + uppermost mantle) rides on top of the asthenosphere. The boundary between crust and mantle is the Mohorovicic discontinuity (Moho), identified by a change in seismic wave velocity.', image: '/images/exams/es-june-2018/context_43_44.png' },
    {
      number: 45, part: 'B-1',
      context: 'A data table compares properties of the four inner (terrestrial) planets: Mercury, Venus, Earth, and Mars. Properties include diameter, density, distance from the Sun, and period of revolution.',
      text: 'Which terrestrial planet has the longest period of revolution around the Sun?',
      choices: ['Mercury', 'Venus', 'Earth', 'Mars'],
      topic: 'Astronomy',
      correct: 3,
      explanation: 'Mars is the farthest from the Sun among the terrestrial planets, so it has the longest orbital period (~687 Earth days), consistent with Kepler\'s third law.',
      diveDeep: 'Kepler\'s third law: the square of a planet\'s orbital period is proportional to the cube of its average orbital radius (T² ∝ r³). Planets farther from the Sun move slower AND have longer orbital paths, resulting in much longer years. Mercury orbits in 88 days, Venus in 225 days, Earth in 365 days, Mars in 687 days. The ESRT provides planetary data. A common mistake is confusing rotation period (length of a day) with revolution period (length of a year). Mars has a day similar to Earth\'s (~24.6 hours) but a much longer year.', image: '/images/exams/es-june-2018/context_45_47.png' },
    {
      number: 46, part: 'B-1',
      context: 'A map of New York State shows the location of surface bedrock outcrops. The map identifies different geologic time periods for the bedrock in different regions, ranging from Precambrian in the Adirondacks to Cretaceous on Long Island.',
      text: 'Which region of New York State has the oldest surface bedrock?',
      choices: ['Long Island', 'Catskills', 'Adirondacks', 'Hudson Valley'],
      topic: 'Geology',
      correct: 2,
      explanation: 'The Adirondack Mountains have Precambrian metamorphic and igneous bedrock (~1 billion years old), the oldest surface bedrock in New York State.',
      diveDeep: 'The ESRT\'s Generalized Bedrock Geology of New York State map is essential. The Adirondacks expose Precambrian basement rocks (~1 billion years) — the oldest. Moving south and west, progressively younger Paleozoic sedimentary rocks are exposed. The Catskills are Devonian sedimentary rocks (~400 million years). Long Island is covered by Pleistocene glacial deposits overlying Cretaceous sediments — the youngest surface materials. New York\'s rock record has several gaps (no Permian, Triassic, or Jurassic bedrock exposed) due to erosion following mountain building. This map is one of the most frequently referenced on the Regents exam.', image: '/images/exams/es-june-2018/context_45_47.png' },
    {
      number: 47, part: 'B-1',
      context: 'A table shows the half-lives of four radioactive isotopes: Carbon-14 (5,700 years), Potassium-40 (1.3 billion years), Rubidium-87 (47 billion years), and Uranium-238 (4.5 billion years).',
      text: 'Which radioactive isotope would be most appropriate for dating a wooden artifact that is approximately 10,000 years old?',
      choices: ['carbon-14', 'potassium-40', 'rubidium-87', 'uranium-238'],
      topic: 'Geologic Time',
      correct: 0,
      explanation: 'Carbon-14 (half-life ~5,700 years) is ideal for dating materials up to ~50,000 years old. A 10,000-year-old artifact would have gone through less than 2 half-lives, leaving measurable C-14.',
      diveDeep: 'Radiometric dating works best when the sample age is between 1/10 and 10 times the half-life of the isotope used. For C-14 (5,700 year half-life), reliable dating range is roughly 100–50,000 years. For older materials, potassium-40 (1.3 billion year half-life) is used for rocks ~100,000+ years old. Uranium-238 (4.5 billion year half-life) is used for the oldest rocks. Carbon-14 is produced in the upper atmosphere when cosmic rays hit nitrogen, then incorporated into living organisms. After death, C-14 decays — measuring the remaining fraction gives the age.', image: '/images/exams/es-june-2018/context_45_47.png' },
    {
      number: 48, part: 'B-1',
      context: 'A photograph shows a rock outcrop with alternating dark and light bands. The rock has a foliated texture with mineral alignment. The rock unit is found in a region that experienced intense heat and pressure during a continental collision.',
      text: 'This rock is most likely classified as',
      choices: ['basalt', 'gneiss', 'limestone', 'sandstone'],
      topic: 'Geology',
      correct: 1,
      explanation: 'Gneiss is a high-grade metamorphic rock with a distinctive foliated (banded) texture of alternating light and dark mineral layers, formed under intense heat and pressure.',
      diveDeep: 'Metamorphic rock identification uses texture and mineral content. Foliation (parallel alignment of minerals) forms perpendicular to the direction of maximum pressure. Types of foliation from low to high grade: slaty cleavage (slate) → phyllitic texture (phyllite) → schistosity (schist) → gneissic banding (gneiss). Gneiss has coarse, interlocking crystals and compositional banding (light quartz/feldspar alternating with dark amphibole/biotite layers). Contact metamorphism produces non-foliated rocks (hornfels, marble, quartzite) because it involves heat without directed pressure. The ESRT Scheme for Metamorphic Rock Identification organizes rocks by grade.', image: '/images/exams/es-june-2018/context_48_50.png' },
    {
      number: 49, part: 'B-1',
      context: 'A diagram represents a portion of the geologic time scale showing eons, eras, periods, and some key events. The Precambrian Eon encompasses about 88% of Earth\'s history.',
      text: 'Approximately what percentage of Earth\'s geologic history is represented by the Precambrian?',
      choices: ['12%', '50%', '75%', '88%'],
      topic: 'Geologic Time',
      correct: 3,
      explanation: 'The Precambrian spans from Earth\'s formation (~4.6 billion years ago) to the start of the Cambrian (~541 million years ago), encompassing about 88% of Earth\'s history.',
      diveDeep: 'Calculating Precambrian proportion: (4600 − 541) million years ÷ 4600 million years ≈ 88%. Despite comprising most of Earth\'s history, the Precambrian has relatively few fossils because most organisms lacked hard parts. The Cambrian Explosion (~541 Ma) marked the sudden appearance of organisms with shells and skeletons, dramatically improving preservation. The ESRT geologic time scale lists eons (Hadean, Archean, Proterozoic, Phanerozoic), eras, and periods with their ages. The Phanerozoic (last 541 million years) contains most of the known fossil record and represents only about 12% of Earth\'s history.', image: '/images/exams/es-june-2018/context_48_50.png' },
    {
      number: 50, part: 'B-1',
      context: 'A graph shows temperature changes over the past 800,000 years derived from Antarctic ice core data, showing cycles of glacial (cold) and interglacial (warm) periods. The current interglacial (Holocene) began about 12,000 years ago.',
      text: 'Based on the ice core data, approximately how many major glacial/interglacial cycles occurred over the past 800,000 years?',
      choices: ['2 cycles', '4 cycles', '8 cycles', '16 cycles'],
      topic: 'Climate',
      correct: 2,
      explanation: 'Ice core data shows approximately 8 major glacial-interglacial cycles over the past 800,000 years, with each cycle lasting roughly 100,000 years (Milankovitch cycle).',
      diveDeep: 'Ice cores from Antarctica and Greenland provide proxy records of past climate through trapped air bubbles (CO₂, methane), oxygen isotope ratios (temperature proxy), and dust layers (volcanic eruptions). The ~100,000 year glacial cycles correspond to Milankovitch cycles — periodic changes in Earth\'s orbital eccentricity, axial tilt, and precession that alter the distribution of solar energy. CO₂ and temperature records from ice cores are closely correlated. The current CO₂ level (~420 ppm) far exceeds any level in the 800,000-year record (~280 ppm in interglacials), providing evidence for human-caused climate change.', image: '/images/exams/es-june-2018/context_48_50.png' },
  ],
}
