import { TOPICS } from './questions'

// Each card: { id, term, definition, topic }
export const flashcards = [
  // ── Cell Biology ──────────────────────────────────────────────────────────
  { id: 'cb1',  topic: TOPICS.CELL_STRUCTURE, term: 'Cell membrane',         definition: 'Selectively permeable phospholipid bilayer that controls what enters and leaves the cell.' },
  { id: 'cb2',  topic: TOPICS.CELL_STRUCTURE, term: 'Nucleus',               definition: 'Membrane-bound organelle that contains DNA and directs cell activities; the "control center" of the cell.' },
  { id: 'cb3',  topic: TOPICS.CELL_ENERGY, term: 'Mitochondria',          definition: 'Organelle that produces ATP through cellular respiration; called the "powerhouse of the cell."' },
  { id: 'cb4',  topic: TOPICS.CELL_ENERGY, term: 'Chloroplast',           definition: 'Organelle found in plant cells that captures light energy and converts it to glucose via photosynthesis.' },
  { id: 'cb5',  topic: TOPICS.CELL_STRUCTURE, term: 'Ribosome',              definition: 'Small organelle (in cytoplasm or on rough ER) that assembles proteins from amino acids using mRNA instructions.' },
  { id: 'cb6',  topic: TOPICS.CELL_STRUCTURE, term: 'Vacuole',               definition: 'Storage organelle; in plant cells the large central vacuole maintains turgor pressure.' },
  { id: 'cb7',  topic: TOPICS.CELL_STRUCTURE, term: 'Cell wall',             definition: 'Rigid outer layer found in plant, fungal, and bacterial cells; provides structural support.' },
  { id: 'cb8',  topic: TOPICS.CELL_STRUCTURE, term: 'Prokaryote',            definition: 'Cell that lacks a membrane-bound nucleus and organelles (e.g., bacteria).' },
  { id: 'cb9',  topic: TOPICS.CELL_STRUCTURE, term: 'Eukaryote',             definition: 'Cell with a true membrane-bound nucleus and membrane-bound organelles (e.g., animal and plant cells).' },
  { id: 'cb10', topic: TOPICS.CELL_ENERGY, term: 'ATP',                   definition: 'Adenosine triphosphate — the primary energy currency of cells; releases energy when the third phosphate bond is broken.' },
  { id: 'cb11', topic: TOPICS.CELL_ENERGY, term: 'Photosynthesis',        definition: '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Process by which producers convert light energy into stored chemical (glucose) energy.' },
  { id: 'cb12', topic: TOPICS.CELL_ENERGY, term: 'Cellular respiration',  definition: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. Releases chemical energy from glucose to produce ATP.' },
  { id: 'cb13', topic: TOPICS.CELL_STRUCTURE, term: 'Diffusion',             definition: 'Passive movement of particles from high concentration to low concentration; requires no energy.' },
  { id: 'cb14', topic: TOPICS.CELL_STRUCTURE, term: 'Osmosis',               definition: 'Diffusion of water across a selectively permeable membrane from low solute to high solute concentration.' },
  { id: 'cb15', topic: TOPICS.CELL_STRUCTURE, term: 'Active transport',      definition: 'Movement of substances against the concentration gradient; requires ATP energy and carrier proteins.' },
  { id: 'cb16', topic: TOPICS.CELL_STRUCTURE, term: 'Mitosis',               definition: 'Cell division that produces 2 genetically identical daughter cells; used for growth and repair.' },
  { id: 'cb17', topic: TOPICS.BIOCHEM, term: 'Enzyme',                definition: 'Biological catalyst (protein) that speeds up chemical reactions by lowering activation energy; not consumed in the reaction.' },
  { id: 'cb18', topic: TOPICS.CELL_STRUCTURE, term: 'Organelle',             definition: 'Specialized structure within a cell that performs a specific function (e.g., mitochondria, nucleus, ribosome).' },

  // ── Genetics ──────────────────────────────────────────────────────────────
  { id: 'ge1',  topic: TOPICS.GENETICS, term: 'Gene',                      definition: 'Segment of DNA on a chromosome that codes for a specific protein or trait.' },
  { id: 'ge2',  topic: TOPICS.GENETICS, term: 'Allele',                    definition: 'One of two or more forms of a gene; inherited one from each parent.' },
  { id: 'ge3',  topic: TOPICS.GENETICS, term: 'Genotype',                  definition: 'The genetic makeup of an organism; represented by letter combinations (e.g., Tt, BB, rr).' },
  { id: 'ge4',  topic: TOPICS.GENETICS, term: 'Phenotype',                 definition: 'The observable physical traits of an organism resulting from its genotype and environment.' },
  { id: 'ge5',  topic: TOPICS.GENETICS, term: 'Dominant allele',           definition: 'Allele that is expressed in the phenotype even when only one copy is present; written as a capital letter.' },
  { id: 'ge6',  topic: TOPICS.GENETICS, term: 'Recessive allele',          definition: 'Allele expressed only when two copies are present (homozygous recessive); written as a lowercase letter.' },
  { id: 'ge7',  topic: TOPICS.GENETICS, term: 'Homozygous',                definition: 'Having two identical alleles for a trait (e.g., TT or tt); also called "true breeding."' },
  { id: 'ge8',  topic: TOPICS.GENETICS, term: 'Heterozygous',              definition: 'Having two different alleles for a trait (e.g., Tt); also called a "hybrid" or "carrier."' },
  { id: 'ge9',  topic: TOPICS.GENETICS, term: 'Punnett square',            definition: 'Grid used to predict the genotype and phenotype ratios of offspring from a genetic cross.' },
  { id: 'ge10', topic: TOPICS.GENETICS, term: 'Codominance',               definition: 'Both alleles are fully expressed in the heterozygote (e.g., AB blood type, roan coat color).' },
  { id: 'ge11', topic: TOPICS.GENETICS, term: 'Incomplete dominance',      definition: 'Neither allele is fully dominant; heterozygote shows a blended intermediate phenotype (e.g., red × white = pink).' },
  { id: 'ge12', topic: TOPICS.GENETICS, term: 'Mutation',                  definition: 'A change in the DNA sequence; can be a point mutation (single base) or chromosomal mutation.' },
  { id: 'ge13', topic: TOPICS.GENETICS, term: 'Chromosome',                definition: 'Tightly coiled DNA + protein structure; humans have 46 (23 pairs). Contains many genes.' },
  { id: 'ge14', topic: TOPICS.GENETICS, term: 'DNA',                       definition: 'Deoxyribonucleic acid — double helix molecule that stores genetic information using base pairs (A-T, G-C).' },
  { id: 'ge15', topic: TOPICS.GENETICS, term: 'Transcription',             definition: 'The process of copying DNA into mRNA in the nucleus; first step of protein synthesis.' },
  { id: 'ge16', topic: TOPICS.GENETICS, term: 'Translation',               definition: 'The process of reading mRNA codons at ribosomes to build a protein from amino acids.' },
  { id: 'ge17', topic: TOPICS.GENETICS, term: 'Sex-linked trait',          definition: 'Trait controlled by a gene on the X or Y chromosome; more common in males (e.g., color blindness, hemophilia).' },
  { id: 'ge18', topic: TOPICS.GENETICS, term: 'Meiosis',                   definition: 'Cell division that produces 4 genetically unique haploid (n) gametes; introduces genetic variation.' },
  { id: 'ge19', topic: TOPICS.GENETICS, term: 'Codon',                     definition: 'Three-base sequence on mRNA that codes for a specific amino acid during translation.' },
  { id: 'ge20', topic: TOPICS.GENETICS, term: 'Protein synthesis',         definition: 'Two-step process (transcription + translation) that uses DNA instructions to build proteins.' },

  // ── Evolution ─────────────────────────────────────────────────────────────
  { id: 'ev1',  topic: TOPICS.EVOLUTION, term: 'Natural selection',        definition: 'Process by which individuals with favorable traits survive and reproduce more than those without; mechanism of evolution.' },
  { id: 'ev2',  topic: TOPICS.EVOLUTION, term: 'Adaptation',               definition: 'An inherited trait that increases an organism\'s fitness (survival and reproduction) in its environment.' },
  { id: 'ev3',  topic: TOPICS.EVOLUTION, term: 'Fitness',                  definition: 'An organism\'s ability to survive and reproduce in its environment; measured by reproductive success.' },
  { id: 'ev4',  topic: TOPICS.EVOLUTION, term: 'Variation',                definition: 'Differences in traits among individuals in a population; the raw material for natural selection.' },
  { id: 'ev5',  topic: TOPICS.EVOLUTION, term: 'Speciation',               definition: 'The formation of a new species, usually through reproductive isolation of two populations.' },
  { id: 'ev6',  topic: TOPICS.EVOLUTION, term: 'Common ancestor',          definition: 'A shared ancestor from which two or more species evolved; evidence from fossils and DNA.' },
  { id: 'ev7',  topic: TOPICS.EVOLUTION, term: 'Homologous structures',    definition: 'Similar structures inherited from a common ancestor; may have different functions (e.g., human arm, whale flipper, bat wing).' },
  { id: 'ev8',  topic: TOPICS.EVOLUTION, term: 'Analogous structures',     definition: 'Structures that have the same function but different evolutionary origins (e.g., bird wing vs. insect wing).' },
  { id: 'ev9',  topic: TOPICS.EVOLUTION, term: 'Vestigial structure',      definition: 'Reduced, non-functional structure inherited from ancestors (e.g., human appendix, whale hip bones).' },
  { id: 'ev10', topic: TOPICS.EVOLUTION, term: 'Fossil record',            definition: 'Evidence of past life preserved in rock; shows evolutionary change over time.' },
  { id: 'ev11', topic: TOPICS.EVOLUTION, term: 'Genetic drift',            definition: 'Random change in allele frequencies in a small population; not driven by selection.' },
  { id: 'ev12', topic: TOPICS.EVOLUTION, term: 'Gene pool',                definition: 'All the alleles present in a population at a given time.' },
  { id: 'ev13', topic: TOPICS.EVOLUTION, term: 'Extinction',               definition: 'Permanent disappearance of a species; occurs when organisms can\'t adapt to environmental change.' },
  { id: 'ev14', topic: TOPICS.EVOLUTION, term: 'Reproductive isolation',   definition: 'Barrier preventing two populations from interbreeding; leads to speciation over time.' },
  { id: 'ev15', topic: TOPICS.EVOLUTION, term: 'Darwin',                   definition: 'Charles Darwin — proposed evolution by natural selection in "On the Origin of Species" (1859); observed variation and survival of the fittest.' },

  // ── Ecology ───────────────────────────────────────────────────────────────
  { id: 'ec1',  topic: TOPICS.ECOLOGY, term: 'Ecosystem',                  definition: 'All the living (biotic) and non-living (abiotic) components in an area and their interactions.' },
  { id: 'ec2',  topic: TOPICS.ECOLOGY, term: 'Food chain',                 definition: 'Linear sequence showing the flow of energy from producer → primary consumer → secondary consumer → etc.' },
  { id: 'ec3',  topic: TOPICS.ECOLOGY, term: 'Food web',                   definition: 'Interconnected network of food chains in an ecosystem; more realistic than a single chain.' },
  { id: 'ec4',  topic: TOPICS.ECOLOGY, term: 'Producer (autotroph)',       definition: 'Organism that makes its own food via photosynthesis or chemosynthesis; base of every food chain.' },
  { id: 'ec5',  topic: TOPICS.ECOLOGY, term: 'Consumer (heterotroph)',     definition: 'Organism that obtains energy by eating other organisms; cannot produce its own food.' },
  { id: 'ec6',  topic: TOPICS.ECOLOGY, term: 'Decomposer',                 definition: 'Organism (bacteria, fungi) that breaks down dead organic matter and returns nutrients to the soil.' },
  { id: 'ec7',  topic: TOPICS.ECOLOGY, term: 'Carrying capacity',          definition: 'Maximum population size an environment can sustainably support given available resources.' },
  { id: 'ec8',  topic: TOPICS.ECOLOGY, term: 'Limiting factor',            definition: 'Any resource or condition (food, water, space, predation) that restricts population growth.' },
  { id: 'ec9',  topic: TOPICS.ECOLOGY, term: 'Niche',                      definition: 'An organism\'s role in its ecosystem: what it eats, where it lives, and how it interacts with other species.' },
  { id: 'ec10', topic: TOPICS.ECOLOGY, term: 'Habitat',                    definition: 'The physical location where an organism lives (e.g., pond, forest floor, coral reef).' },
  { id: 'ec11', topic: TOPICS.ECOLOGY, term: 'Symbiosis',                  definition: 'Close, long-term interaction between two different species living together.' },
  { id: 'ec12', topic: TOPICS.ECOLOGY, term: 'Mutualism',                  definition: 'Symbiotic relationship where both species benefit (e.g., bees + flowers, clownfish + anemone).' },
  { id: 'ec13', topic: TOPICS.ECOLOGY, term: 'Commensalism',               definition: 'Symbiosis where one species benefits and the other is neither helped nor harmed (e.g., barnacles on whale).' },
  { id: 'ec14', topic: TOPICS.ECOLOGY, term: 'Parasitism',                 definition: 'Symbiosis where one species (parasite) benefits at the expense of the other (host).' },
  { id: 'ec15', topic: TOPICS.ECOLOGY, term: 'Ecological succession',      definition: 'Gradual change in species composition in an ecosystem over time (primary or secondary).' },
  { id: 'ec16', topic: TOPICS.ECOLOGY, term: 'Biodiversity',               definition: 'The variety of species in an area; high biodiversity generally means a more stable and resilient ecosystem.' },
  { id: 'ec17', topic: TOPICS.ECOLOGY, term: 'Biotic factor',              definition: 'Living component of an ecosystem (organisms, their interactions, decomposing matter).' },
  { id: 'ec18', topic: TOPICS.ECOLOGY, term: 'Abiotic factor',             definition: 'Non-living component of an ecosystem (temperature, water, light, soil, pH).' },

  // ── Human Body ────────────────────────────────────────────────────────────
  { id: 'hb1',  topic: TOPICS.HUMAN_BODY, term: 'Homeostasis',             definition: 'The process by which organisms maintain a stable internal environment despite external changes (e.g., body temperature 37°C).' },
  { id: 'hb2',  topic: TOPICS.HUMAN_BODY, term: 'Hormone',                 definition: 'Chemical messenger secreted by endocrine glands; travels through the blood to target organs.' },
  { id: 'hb3',  topic: TOPICS.HUMAN_BODY, term: 'Neuron',                  definition: 'Nerve cell that transmits electrical and chemical signals; basic unit of the nervous system.' },
  { id: 'hb4',  topic: TOPICS.HUMAN_BODY, term: 'Antibody',                definition: 'Y-shaped protein produced by B-cells that binds to a specific antigen to neutralize pathogens.' },
  { id: 'hb5',  topic: TOPICS.HUMAN_BODY, term: 'Antigen',                 definition: 'Foreign molecule (usually on a pathogen\'s surface) that triggers an immune response.' },
  { id: 'hb6',  topic: TOPICS.HUMAN_BODY, term: 'Immune response',         definition: 'The body\'s defense against pathogens; involves white blood cells, antibodies, and memory cells.' },
  { id: 'hb7',  topic: TOPICS.HUMAN_BODY, term: 'Digestive system',        definition: 'Breaks down food into small molecules (nutrients) that can be absorbed into the blood; includes stomach, intestines.' },
  { id: 'hb8',  topic: TOPICS.HUMAN_BODY, term: 'Circulatory system',      definition: 'Heart + blood vessels; transports oxygen, nutrients, hormones, and waste throughout the body.' },
  { id: 'hb9',  topic: TOPICS.HUMAN_BODY, term: 'Respiratory system',      definition: 'Lungs + airways; exchanges O₂ and CO₂ between blood and the environment.' },
  { id: 'hb10', topic: TOPICS.HUMAN_BODY, term: 'Nervous system',          definition: 'Brain, spinal cord, and nerves; controls body functions via electrical signals; coordinates responses to stimuli.' },
  { id: 'hb11', topic: TOPICS.HUMAN_BODY, term: 'Endocrine system',        definition: 'Glands (pituitary, thyroid, adrenal, etc.) that release hormones to regulate growth, metabolism, and reproduction.' },
  { id: 'hb12', topic: TOPICS.HUMAN_BODY, term: 'Negative feedback',       definition: 'Control mechanism that reverses a change to restore homeostasis (e.g., high blood sugar → insulin release → blood sugar drops).' },
  { id: 'hb13', topic: TOPICS.HUMAN_BODY, term: 'Receptor',                definition: 'Protein on a cell or sensory organ that detects a specific stimulus and initiates a response.' },
  { id: 'hb14', topic: TOPICS.HUMAN_BODY, term: 'Excretory system',        definition: 'Removes metabolic waste from the body; kidneys filter blood and produce urine.' },
  { id: 'hb15', topic: TOPICS.HUMAN_BODY, term: 'Stimulus / Response',     definition: 'Stimulus: a change that triggers a reaction. Response: the organism\'s reaction to maintain homeostasis.' },

  // ── Reproduction & Development ────────────────────────────────────────────
  { id: 're1',  topic: TOPICS.HUMAN_BODY, term: 'Asexual reproduction',  definition: 'Reproduction involving one parent; offspring are genetically identical clones (e.g., binary fission, budding, vegetative propagation).' },
  { id: 're2',  topic: TOPICS.HUMAN_BODY, term: 'Sexual reproduction',   definition: 'Reproduction involving two parents and fertilization; produces offspring with genetic variation.' },
  { id: 're3',  topic: TOPICS.HUMAN_BODY, term: 'Fertilization',         definition: 'Union of egg (n) and sperm (n) to form a diploid zygote (2n); begins development.' },
  { id: 're4',  topic: TOPICS.HUMAN_BODY, term: 'Zygote',                definition: 'The first cell formed after fertilization; contains a full diploid set of chromosomes (2n).' },
  { id: 're5',  topic: TOPICS.HUMAN_BODY, term: 'Embryo',                definition: 'Multicellular stage of development after the zygote begins dividing by mitosis.' },
  { id: 're6',  topic: TOPICS.HUMAN_BODY, term: 'Differentiation',       definition: 'Process by which cells become specialized in structure and function during development despite having the same DNA.' },
  { id: 're7',  topic: TOPICS.HUMAN_BODY, term: 'Stem cell',             definition: 'Undifferentiated cell capable of becoming many cell types; found in embryos and some adult tissues.' },
  { id: 're8',  topic: TOPICS.HUMAN_BODY, term: 'Gamete',                definition: 'Haploid (n) reproductive cell — sperm in males, egg (ovum) in females.' },
  { id: 're9',  topic: TOPICS.HUMAN_BODY, term: 'Placenta',              definition: 'Organ that exchanges nutrients, oxygen, and waste between mother and fetus during pregnancy.' },
  { id: 're10', topic: TOPICS.HUMAN_BODY, term: 'Vegetative propagation',definition: 'Asexual reproduction in plants using roots, stems, or leaves (e.g., runners, cuttings, tubers).' },

  // ── Science Practices: Data & Investigations ──────────────────────────────
  { id: 'sp1', topic: TOPICS.SCIENCE_PRACTICES, term: 'Independent variable', definition: 'The one factor a scientist deliberately changes to test its effect.' },
  { id: 'sp2', topic: TOPICS.SCIENCE_PRACTICES, term: 'Dependent variable',   definition: 'The factor measured/observed; it responds to the independent variable.' },
  { id: 'sp3', topic: TOPICS.SCIENCE_PRACTICES, term: 'Control group',        definition: 'The untreated baseline group used for comparison to isolate the variable tested.' },
  { id: 'sp4', topic: TOPICS.SCIENCE_PRACTICES, term: 'Hypothesis',           definition: 'A testable, falsifiable prediction about how variables relate.' },
  { id: 'sp5', topic: TOPICS.SCIENCE_PRACTICES, term: 'Claim–Evidence–Reasoning', definition: 'Answer structure: make a claim, cite specific data/evidence, then explain the reasoning that links them.' },
  { id: 'sp6', topic: TOPICS.SCIENCE_PRACTICES, term: 'Correlation vs. causation', definition: 'An association between variables is not by itself proof that one causes the other.' },
  { id: 'sp7', topic: TOPICS.SCIENCE_PRACTICES, term: 'Valid vs. reliable',   definition: 'Valid = tests what it intends (controlled); reliable = consistent across repeated trials / large samples.' },

  // ── Lab Skills (NY State labs) ────────────────────────────────────────────
  { id: 'lab1', topic: TOPICS.LAB_SKILLS, term: 'Diffusion Through a Membrane', definition: 'State lab: starch/iodine + glucose across a model membrane shows selective permeability and diffusion direction.' },
  { id: 'lab2', topic: TOPICS.LAB_SKILLS, term: 'The Beaks of Finches',         definition: 'State lab: tools as "beaks" competing for seeds models natural selection, variation, and competition.' },
  { id: 'lab3', topic: TOPICS.LAB_SKILLS, term: 'Relationships & Biodiversity', definition: 'State lab: structural, molecular (DNA/protein), and physical evidence used to determine evolutionary relationships.' },
  { id: 'lab4', topic: TOPICS.LAB_SKILLS, term: 'Making Connections',           definition: 'State lab: measuring a variable (e.g., pulse/squeezes) before vs. after activity; controls, hypothesis, and data analysis.' },
  { id: 'lab5', topic: TOPICS.LAB_SKILLS, term: 'Indicator',                    definition: 'A substance that changes color to signal a condition (e.g., iodine → starch, Benedict\'s → simple sugar).' },
]

export function getFlashcardsByTopic(topic) {
  if (!topic) return flashcards
  return flashcards.filter((c) => c.topic === topic)
}

export const FLASHCARD_TOPIC_LIST = [
  { label: 'All Topics', value: null },
  ...Array.from(new Set(flashcards.map((c) => c.topic))).map((t) => ({ label: t, value: t })),

  // ── HUMANITIES (ENGLISH, GLOBAL, US HISTORY) ─────────────────────────────
  { id: 'en1', topic: 'english-literature', term: 'Metaphor', definition: 'Comparison of two unlike things without using "like" or "as"; creates vivid imagery.' },
  { id: 'en2', topic: 'english-literature', term: 'Simile', definition: 'Comparison of two unlike things using "like" or "as" to highlight a shared quality.' },
  { id: 'en3', topic: 'english-literature', term: 'Personification', definition: 'Attributing human characteristics, emotions, or behaviors to non-human entities.' },
  { id: 'en4', topic: 'english-literature', term: 'Hyperbole', definition: 'Exaggerated statements or claims used for emphasis or effect, not meant to be taken literally.' },
  { id: 'en5', topic: 'english-literature', term: 'Alliteration', definition: 'Repetition of initial consonant sounds in close proximity to create rhythm or emphasis.' },
  { id: 'en6', topic: 'english-literature', term: 'Irony', definition: 'Contrast between expectation and reality (situational, dramatic, or verbal).' },
  { id: 'en7', topic: 'english-literature', term: 'Onomatopoeia', definition: 'Words that mimic the natural sounds associated with the objects or actions they refer to.' },
  { id: 'en8', topic: 'english-literature', term: 'Imagery', definition: 'Vivid sensory language that appeals to sight, sound, smell, taste, or touch to create mental pictures.' },
  { id: 'en9', topic: 'english-literature', term: 'Symbolism', definition: 'The use of an object, person, or situation to represent a deeper meaning beyond its literal sense.' },
  { id: 'en10', topic: 'english-literature', term: 'Foreshadowing', definition: 'Clues or hints in a narrative that suggest events that will occur later in the story.' },
  { id: 'en11', topic: 'english-literature', term: 'Tone', definition: 'The author\'s attitude toward the subject matter or audience, conveyed through diction and syntax.' },
  { id: 'en12', topic: 'english-literature', term: 'Mood', definition: 'The emotional atmosphere or feeling created in a text for the reader.' },
  { id: 'en13', topic: 'english-literature', term: 'Theme', definition: 'The underlying message, moral, or universal truth explored throughout a literary work.' },
  { id: 'en14', topic: 'english-literature', term: 'Point of View', definition: 'The perspective from which a story is narrated, such as first, second, or third person.' },
  { id: 'en15', topic: 'english', term: 'Subject-Verb Agreement', definition: 'Grammatical rule requiring a verb to match its subject in number (singular or plural).' },
  { id: 'en16', topic: 'english', term: 'Pronoun-Antecedent Agreement', definition: 'Rule requiring a pronoun to match the noun it replaces in number, gender, and person.' },
  { id: 'en17', topic: 'english', term: 'Parallel Structure', definition: 'Using the same pattern of words or grammatical form to show that ideas are of equal importance.' },
  { id: 'en18', topic: 'english', term: 'Fragment', definition: 'An incomplete sentence that lacks a subject, a verb, or a complete thought.' },
  { id: 'en19', topic: 'english', term: 'Run-On Sentence', definition: 'Two or more independent clauses joined incorrectly without proper punctuation or conjunctions.' },
  { id: 'en20', topic: 'english', term: 'Dangling Modifier', definition: 'A modifier that does not clearly or logically refer to any specific word in the sentence.' },
  { id: 'en21', topic: 'english', term: 'Active Voice', definition: 'Sentence structure where the subject performs the action denoted by the verb.' },
  { id: 'en22', topic: 'english', term: 'Passive Voice', definition: 'Sentence structure where the subject receives the action of the verb.' },
  { id: 'en23', topic: 'english', term: 'Inference', definition: 'A logical conclusion drawn from evidence in the text and personal reasoning.' },
  { id: 'en24', topic: 'english', term: 'Main Idea', definition: 'The primary point or central concept that the author wants to convey about a topic.' },
  { id: 'en25', topic: 'english', term: 'Author\'s Purpose', definition: 'The primary reason an author writes, typically to persuade, inform, entertain, or describe.' },
  { id: 'en26', topic: 'english', term: 'Bias', definition: 'A prejudice or leaning toward a particular perspective, opinion, or group.' },
  { id: 'en27', topic: 'english', term: 'Fact vs. Opinion', definition: 'Facts can be objectively proven; opinions express subjective beliefs, feelings, or values.' },
  { id: 'en28', topic: 'english', term: 'Context Clues', definition: 'Information near an unfamiliar word in a text that helps clarify its meaning.' },
  { id: 'en29', topic: 'english', term: 'Credibility', definition: 'The trustworthiness, reliability, and authority of a source or author.' },
  { id: 'en30', topic: 'english-rhetoric', term: 'Ethos', definition: 'Rhetorical appeal to character, credibility, or ethics to persuade an audience.' },
  { id: 'en31', topic: 'english-rhetoric', term: 'Pathos', definition: 'Rhetorical appeal to emotion, sympathy, or passion to persuade an audience.' },
  { id: 'en32', topic: 'english-rhetoric', term: 'Logos', definition: 'Rhetorical appeal to logic, reason, statistics, or evidence to persuade an audience.' },
  { id: 'en33', topic: 'english-rhetoric', term: 'Diction', definition: 'The author\'s purposeful choice of words to convey meaning, tone, or style.' },
  { id: 'en34', topic: 'english-rhetoric', term: 'Syntax', definition: 'The arrangement of words and phrases to create well-formed, impactful sentences.' },
  { id: 'en35', topic: 'english-rhetoric', term: 'Register', definition: 'The level of formality in language use, ranging from formal and academic to casual.' },
  { id: 'en36', topic: 'english-rhetoric', term: 'Rhetorical Question', definition: 'A question asked for effect or emphasis rather than to elicit an answer.' },
  { id: 'en37', topic: 'english-rhetoric', term: 'Juxtaposition', definition: 'Placing two contrasting concepts or images side-by-side to highlight differences.' },
  { id: 'en38', topic: 'english-rhetoric', term: 'Oxymoron', definition: 'A figure of speech pairing contradictory terms for rhetorical effect.' },
  { id: 'en39', topic: 'english-rhetoric', term: 'Paradox', definition: 'A statement that seems self-contradictory but reveals a deeper, underlying truth.' },
  { id: 'en40', topic: 'english-literature', term: 'Allegory', definition: 'A narrative work that carries a symbolic meaning beneath the surface story.' },
  { id: 'gh1', topic: 'geography', term: 'Peninsula', definition: 'A body of land surrounded by water on three sides (e.g., India, Italy, Korea).' },
  { id: 'gh2', topic: 'geography', term: 'Archipelago', definition: 'A chain or cluster of islands close together (e.g., Japan, Philippines).' },
  { id: 'gh3', topic: 'geography', term: 'Monsoons', definition: 'Seasonal winds that bring heavy rain or dry seasons, particularly affecting South Asia.' },
  { id: 'gh4', topic: 'geography', term: 'Trade Route', definition: 'A systematic network of pathways used for the commercial transport of cargo (e.g., Silk Road).' },
  { id: 'gh5', topic: 'world-cultures', term: 'Cultural Diffusion', definition: 'The spread of cultural beliefs, values, and social activities from one group to another.' },
  { id: 'gh6', topic: 'geography', term: 'Migration', definition: 'Physical movement by humans from one area to another for better resources or safety.' },
  { id: 'gh7', topic: 'global-history', term: 'Feudalism', definition: 'Medieval social and political system based on mutual obligations between lords, vassals, and serfs.' },
  { id: 'gh8', topic: 'global-history', term: 'Manorialism', definition: 'The economic system of the Middle Ages centered around self-sufficient agricultural estates.' },
  { id: 'gh9', topic: 'global-history', term: 'Byzantine Empire', definition: 'The Eastern half of the Roman Empire that survived the fall of Rome; capital at Constantinople.' },
  { id: 'gh10', topic: 'global-history', term: 'Islamic Caliphate', definition: 'A state led by a Caliph; preserved and advanced scientific and philosophical knowledge.' },
  { id: 'gh11', topic: 'global-history', term: 'Crusades', definition: 'Holy wars fought between European Christians and Muslims for control of Jerusalem.' },
  { id: 'gh12', topic: 'global-history', term: 'Black Death', definition: 'A devastating plague that swept through Eurasia in the 14th century, reducing the population.' },
  { id: 'gh13', topic: 'global-history', term: 'Renaissance', definition: 'Era of cultural, artistic, and scientific rebirth in Europe, beginning in 14th-century Italy.' },
  { id: 'gh14', topic: 'global-history', term: 'Scientific Revolution', definition: 'A period of drastic change in scientific thought emphasizing observation and reason (16th-17th centuries).' },
  { id: 'gh15', topic: 'global-history', term: 'Enlightenment', definition: 'Intellectual movement of the 18th century emphasizing reason, individualism, and natural rights.' },
  { id: 'gh16', topic: 'global-history', term: 'Monarchy', definition: 'Form of government with a monarch (king or queen) at the head, usually hereditary.' },
  { id: 'gh17', topic: 'global-history', term: 'Absolutism', definition: 'A political system in which a ruler holds total, unchecked power (e.g., Louis XIV).' },
  { id: 'gh18', topic: 'global-history', term: 'Democracy', definition: 'Government system where power is vested in the people, ruling directly or through representatives.' },
  { id: 'gh19', topic: 'global-history', term: 'Theocracy', definition: 'Government system ruled by religious leaders who claim divine guidance.' },
  { id: 'gh20', topic: 'global-history', term: 'Oligarchy', definition: 'A form of government in which a small group of people holds control.' },
  { id: 'gh21', topic: 'global-history', term: 'Communism', definition: 'Economic and political system aiming for a classless society with collective ownership of property.' },
  { id: 'gh22', topic: 'global-history', term: 'Capitalism', definition: 'Economic system based on private ownership of resources and free-market competition.' },
  { id: 'gh23', topic: 'global-history', term: 'Mercantilism', definition: 'Economic theory that a nation\'s power depends on accumulating gold and keeping colonies dependent.' },
  { id: 'gh24', topic: 'global-history', term: 'Imperialism', definition: 'A policy of extending a country\'s power and influence through diplomacy or military force.' },
  { id: 'gh25', topic: 'global-history', term: 'Colonialism', definition: 'The practice of acquiring political control over another country and occupying it with settlers.' },
  { id: 'gh26', topic: 'global-history', term: 'Nationalism', definition: 'Strong feeling of pride, loyalty, and devotion to one\'s own nation and self-determination.' },
  { id: 'gh27', topic: 'world-cultures', term: 'Social Hierarchy', definition: 'A system in which members of a society are ranked according to status or power.' },
  { id: 'gh28', topic: 'world-cultures', term: 'Cultural Exchange', definition: 'The sharing and blending of ideas, technology, and traditions between different cultures.' },
  { id: 'gh29', topic: 'global-history', term: 'Industrial Revolution', definition: 'Transition to new manufacturing processes using machinery and steam power, starting in Britain.' },
  { id: 'gh30', topic: 'global-history', term: 'Sovereignty', definition: 'The authority of a state to govern itself or another state independently.' },
  { id: 'gh31', topic: 'global-history', term: 'Social Contract', definition: 'Theory that individuals surrender some freedoms to government in exchange for protection.' },
  { id: 'gh32', topic: 'global-history', term: 'Secularism', definition: 'The principle of separating government and state affairs from religious beliefs.' },
  { id: 'gh33', topic: 'global-history', term: 'Totalitarianism', definition: 'Government system that is dictatorial and requires complete subservience to the state.' },
  { id: 'gh34', topic: 'global-history', term: 'Appeasement', definition: 'Policy of making concessions to dictatorial powers to avoid conflict (e.g., Munich Agreement).' },
  { id: 'gh35', topic: 'global-history', term: 'Cold War', definition: 'State of hostility between the US and USSR characterized by threats, propaganda, and proxy wars.' },
  { id: 'gh36', topic: 'global-history', term: 'Decolonization', definition: 'The process by which colonies become independent of the colonizing country after WWII.' },
  { id: 'gh37', topic: 'world-cultures', term: 'Globalization', definition: 'The process of increasing integration and interdependence of national economies and cultures.' },
  { id: 'gh38', topic: 'global-history', term: 'Humanism', definition: 'Renaissance intellectual movement focusing on human potential, achievements, and worldly matters.' },
  { id: 'gh39', topic: 'global-history', term: 'Magna Carta', definition: '1215 English document that limited the power of the king and established the rule of law.' },
  { id: 'gh40', topic: 'global-history', term: 'Neolithic Revolution', definition: 'The prehistoric transition of humans from nomadic hunter-gatherers to settled farming communities.' },
  { id: 'gh41', topic: 'global-history', term: 'Pax Romana', definition: 'A 200-year period of relative peace and stability across the Roman Empire starting under Augustus.' },
  { id: 'gh42', topic: 'geography', term: 'Silk Road', definition: 'Ancient overland trade network connecting East Asia to the Mediterranean, facilitating exchange.' },
  { id: 'gh43', topic: 'global-history', term: 'Spheres of Influence', definition: 'Territorial area in which an outside nation holds exclusive economic or political influence.' },
  { id: 'gh44', topic: 'global-history', term: 'Treaty of Versailles', definition: 'Peace treaty ending WWI that imposed harsh reparations on Germany, sparking resentment.' },
  { id: 'gh45', topic: 'geography', term: 'Urbanization', definition: 'The process of population shift from rural areas to cities, driving city growth.' },
  { id: 'gh46', topic: 'world-cultures', term: 'Westernization', definition: 'The adoption of Western culture, technology, and political ideas by non-Western societies.' },
  { id: 'gh47', topic: 'global-history', term: 'Reformation', definition: '16th-century religious movement started by Martin Luther that split Western Christianity.' },
  { id: 'gh48', topic: 'global-history', term: 'French Revolution', definition: '1789 uprising that overthrew the absolute monarchy and feudal privileges in France.' },
  { id: 'gh49', topic: 'global-history', term: 'Russian Revolution', definition: '1917 political upheaval that dismantled the Tsarist autocracy and established the Soviet Union.' },
  { id: 'gh50', topic: 'global-history', term: 'Code of Hammurabi', definition: 'Ancient Mesopotamian written legal code establishing strict guidelines and punishments.' },
  { id: 'us1', topic: 'us-government', term: 'Separation of Powers', definition: 'Division of legislative, executive, and judicial powers among three independent branches.' },
  { id: 'us2', topic: 'us-government', term: 'Checks and Balances', definition: 'Constitutional mechanism allowing each branch of government to limit the powers of the others.' },
  { id: 'us3', topic: 'us-government', term: 'Federalism', definition: 'System of government where power is shared between the national and state governments.' },
  { id: 'us4', topic: 'us-government', term: 'Due Process', definition: 'Constitutional guarantee of fair treatment through the normal judicial system (5th/14th Amendments).' },
  { id: 'us5', topic: 'us-government', term: 'Amendment', definition: 'A formal change or addition to the US Constitution (requires 2/3 of Congress and 3/4 of states).' },
  { id: 'us6', topic: 'us-government', term: 'Ratification', definition: 'The official approval of a constitution, treaty, or amendment by voting states.' },
  { id: 'us7', topic: 'us-government', term: 'Bill of Rights', definition: 'The first ten amendments to the US Constitution, safeguarding individual liberties.' },
  { id: 'us8', topic: 'us-history', term: 'Declaration of Independence', definition: '1776 document written by Thomas Jefferson declaring the colonies free from British rule.' },
  { id: 'us9', topic: 'us-government', term: 'US Constitution', definition: '1787 document establishing the supreme law and government framework of the United States.' },
  { id: 'us10', topic: 'us-history', term: 'Emancipation Proclamation', definition: '1863 executive order by Lincoln declaring all enslaved people in Confederate territory free.' },
  { id: 'us11', topic: 'us-history', term: 'Reconstruction', definition: 'The period (1865–1877) after the Civil War dedicated to rebuilding the South and integrating freedmen.' },
  { id: 'us12', topic: 'us-history', term: 'Abolitionism', definition: 'The antebellum reform movement to immediately end slavery in the United States.' },
  { id: 'us13', topic: 'us-history', term: 'Women\'s Suffrage', definition: 'The political struggle for women\'s right to vote, won with the 19th Amendment in 1920.' },
  { id: 'us14', topic: 'us-history', term: 'Labor Movement', definition: 'Organized effort by workers to secure better wages, shorter hours, and safer working conditions.' },
  { id: 'us15', topic: 'us-history', term: 'Civil Rights Movement', definition: 'Mid-20th-century campaign to end racial segregation and secure constitutional equality for African Americans.' },
  { id: 'us16', topic: 'us-history', term: 'Environmentalism', definition: 'Social and political movement focusing on environmental protection and conservation.' },
  { id: 'us17', topic: 'us-history', term: 'Progressive Era', definition: 'Period of reform (1890s–1920s) aiming to correct political, economic, and social abuses of industrialization.' },
  { id: 'us18', topic: 'us-history', term: 'New Deal', definition: 'FDR\'s package of relief, recovery, and reform programs to combat the Great Depression in the 1930s.' },
  { id: 'us19', topic: 'us-government', term: 'Judicial Review', definition: 'Power of the Supreme Court to declare laws or actions unconstitutional (Marbury v. Madison).' },
  { id: 'us20', topic: 'us-history', term: 'Monroe Doctrine', definition: '1823 policy statement opposing European colonization or intervention in the Americas.' },
  { id: 'us21', topic: 'us-history', term: 'Manifest Destiny', definition: '19th-century belief that the US was destined to expand westward to the Pacific Ocean.' },
  { id: 'us22', topic: 'us-history', term: 'Jim Crow Laws', definition: 'State and local laws enforcing racial segregation and disenfranchisement in the Southern US (1870s-1960s).' },
  { id: 'us23', topic: 'us-history', term: 'Great Migration', definition: 'Movement of millions of African Americans from the rural South to the urban North and West (1916-1970).' },
  { id: 'us24', topic: 'us-history', term: 'Cold War', definition: 'Post-WWII state of geopolitical tension and ideological rivalry between the US and the USSR.' },
  { id: 'us25', topic: 'us-civics', term: 'Electoral College', definition: 'Constitutional system for the indirect election of the US president based on state electoral votes.' },
  { id: 'us26', topic: 'us-civics', term: 'Popular Sovereignty', definition: 'Principle that a territory\'s residents should vote to decide political issues, such as slavery.' },
  { id: 'us27', topic: 'us-civics', term: 'Nullification', definition: 'The theory that states hold the right to declare a federal law void within their borders.' },
  { id: 'us28', topic: 'us-history', term: 'Sectionalism', definition: 'Loyalty or devotion to regional interests rather than national unity, leading to the Civil War.' },
  { id: 'us29', topic: 'us-history', term: 'Social Darwinism', definition: '19th-century belief applying "survival of the fittest" to society, justifying extreme wealth and inequality.' },
  { id: 'us30', topic: 'us-history', term: 'Gilded Age', definition: 'Late 19th-century era of rapid industrial growth masked by underlying poverty and corruption.' },
  { id: 'us31', topic: 'us-history', term: 'Isolationism', definition: 'Foreign policy of avoiding political alliances or entanglements with other nations.' },
  { id: 'us32', topic: 'us-history', term: 'Containment', definition: 'US Cold War foreign policy aimed at stopping the expansion of communism globally.' },
  { id: 'us33', topic: 'us-history', term: 'Great Society', definition: 'President Johnson\'s social reforms in the 1960s targeting poverty, healthcare, and education.' },
  { id: 'us34', topic: 'us-history', term: 'Sharecropping', definition: 'Southern farming system where tenant farmers paid landlords rent using a portion of their harvested crops.' },
  { id: 'us35', topic: 'us-history', term: 'Muckrakers', definition: 'Progressive Era journalists who exposed institutional and industrial corruption to the public.' },
  { id: 'us36', topic: 'us-history', term: 'Nativism', definition: 'A policy or sentiment favoring native-born citizens over newly arrived immigrants.' },
  { id: 'us37', topic: 'us-history', term: 'Mercantilism', definition: 'Economic system where colonies exist to enrich the mother country through strict trade controls.' },
  { id: 'us38', topic: 'us-history', term: 'Common Sense', definition: '1776 pamphlet by Thomas Paine urging colonies to declare independence from Great Britain.' },
  { id: 'us39', topic: 'us-history', term: 'Articles of Confederation', definition: 'The first governing constitution of the US (1781–1789), featuring a very weak central government.' },
  { id: 'us40', topic: 'us-history', term: 'Federalists vs. Antifederalists', definition: 'Federalists supported the Constitution; Antifederalists opposed it due to fear of federal tyranny.' },
  { id: 'us41', topic: 'us-history', term: 'Great Compromise', definition: '1787 constitutional agreement creating a bicameral Congress: House (by population) and Senate (equal representation).' },
  { id: 'us42', topic: 'us-history', term: 'Marshall Court', definition: 'The Supreme Court era under John Marshall (1801–1835) that expanded federal power over states.' },
  { id: 'us43', topic: 'us-history', term: 'Seneca Falls Convention', definition: '1848 women\'s rights meeting in New York that drafted the Declaration of Sentiments.' },
  { id: 'us44', topic: 'us-history', term: 'Homestead Act', definition: '1862 law offering 160 acres of free Western public land to settlers who improved it.' },
  { id: 'us45', topic: 'us-history', term: 'Civil Rights Act of 1964', definition: 'Landmark federal law outlawing discrimination based on race, color, religion, sex, or national origin.' },
]
